# PYTHON – WORKSHEET 12 (DATA CLEANING)

# Questions:

1. Determine the no. of rows and no. of columns in the dataset.

In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv('pythonworksheet12.csv')
data.head(10)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3.0,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4.0,h,1600000.0,VB,Nelson,04-06-2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4.0,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra,-37.7965,144.9965,Northern Metropolitan,4019.0
8,Abbotsford,53 Turner St,2.0,h,NaN,S,Biggin,06-08-2016,2.5,3067.0,...,1.0,2.0,201.0,NaN,1900.0,Yarra,-37.7995,144.9974,Northern Metropolitan,4019.0
9,Abbotsford,99 Turner St,2.0,h,NaN,S,Collins,06-08-2016,2.5,3067.0,...,2.0,1.0,202.0,NaN,1900.0,Yarra,-37.7996,144.9989,Northern Metropolitan,4019.0

In [2]:
# Determine the no. of rows and no. of columns in the dataset

data.shape

(23678, 21)

2. Display the datatypes of each column.

In [3]:
#Displaying the datatypes of each column

data.dtypes

Suburb            object
Address           object
Rooms            float64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

3. Determine the row indexes of rows having all null values (i.e. empty rows).

In [4]:
#rows having all null values i,e empty rows

empty_rows = data[data.isna().all(axis=1)].index
print(empty_rows)

#These are the empty rows numbers

Int64Index([   31,  1145,  1348,  2119,  3277,  3288,  3745,  3752,  3798,
             3855,
            ...
            21220, 21343, 21602, 22003, 22109, 22288, 22704, 22918, 23153,
            23341],
           dtype='int64', length=131)

4. Determine the total number of empty rows and their percentage in whole dataset and remove them

In [5]:
print('total number of empty rows :',len(empty_rows),'\n')
      
print('percentage of empty rows in the dataset',len(empty_rows)*100 / len(data))

data1=data.drop(empty_rows)
data1

total number of empty rows : 131

percentage of empty rows in the dataset 0.5532561871779711

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

5. Determine the column names having missing values.

In [6]:
# Column name having missing or null values

data1.columns[data1.isnull().any()]

Index(['Price', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

6. Determine the missing values and their percentage in each column.

In [7]:
missing_percentage = data1.isnull().sum() * 100 / len(data1)
missing_percentage

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            21.875398
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.004247
Postcode          0.004247
Bedroom2         19.030025
Bathroom         19.042766
Car              19.645815
Landsize         26.062768
BuildingArea     57.455302
YearBuilt        50.991634
CouncilArea      33.511700
Lattitude        18.278337
Longtitude       18.278337
Regionname        0.004247
Propertycount     0.004247
dtype: float64

7. Determine the row indexes having missing values.

In [8]:
#these are the rows having missing values

missing_values = data1[data1.isnull().any(axis=1)]
missing_values

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3.0,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4.0,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra,-37.79650,144.99650,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

8. Determine the missing values and their percentage in each row.

In [9]:
missing_percentage_row = data1.isnull().any(axis=1) * 100 / len(data1)
missing_percentage_row

0        0.004247
1        0.004247
2        0.000000
3        0.004247
4        0.000000
           ...
23673    0.004247
23674    0.004247
23675    0.004247
23676    0.004247
23677    0.004247
Length: 23547, dtype: float64

9. Determine the column names having more than 30% missing values and remove them from the dataset.

In [10]:
missing_percentage1 = missing_percentage > 30
print(missing_percentage1[missing_percentage1])
data2=data1.drop(['BuildingArea','YearBuilt','CouncilArea'],axis=1)
data2

BuildingArea    True
YearBuilt       True
CouncilArea     True
dtype: bool

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,2.0,1.0,1.0,126.0,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,2.0,1.0,1.0,202.0,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,3.0,2.0,1.0,0.0,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,3.0,1.0,0.0,552.0,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,4.0,3.0,2.0,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,4.0,2.0,2.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

10. Determine the number and percentage of rows having more than 5 missing values. If the percentage of such rows is less than 20% then remove all these rows

In [11]:
for i in range(len(data2.index)) : 
    print(" Total NaN values in row", i + 1, ":-", 
          data2.iloc[i].isnull().sum(),"and it's percentage :",data2.iloc[i].isnull().sum()*100 / 18)

 Total NaN values in row 1 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2 :- 0 and it's percentage : 0.0
 Total NaN values in row 3 :- 0 and it's percentage : 0.0
 Total NaN values in row 4 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5 :- 0 and it's percentage : 0.0
 Total NaN values in row 6 :- 0 and it's percentage : 0.0
 Total NaN values in row 7 :- 0 and it's percentage : 0.0
 Total NaN values in row 8 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11 :- 0 and it's percentage : 0.0
 Total NaN values in row 12 :- 0 and it's percentage : 0.0
 Total NaN values in row 13 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15 :- 0 and it's percentage : 0.0
 Total NaN values in row 16 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18 :- 0 and it's percentage : 0.0
 Total NaN values in row 19 :- 0 and it's percentage : 0.0
 Total NaN values in row 20 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 24 :- 0 and it's percentage : 0.0
 Total NaN values in row 25 :- 0 and it's percentage : 0.0
 Total NaN values in row 26 :- 0 and it's percentage : 0.0
 Total NaN values in row 27 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 28 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 29 :- 0 and it's percentage : 0.0
 Total NaN values in row 30 :- 0 and it's percentage : 0.0
 Total NaN values in row 31 :- 0 and it's percentage : 0.0
 Total NaN values in row 32 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 33 :- 0 and it's percentage : 0.0
 Total NaN values in row 34 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 35 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 36 :- 0 and it's percentage : 0.0
 Total NaN values in row 37 :- 0 and it's percentage : 0.0
 Total NaN values in row 38 :- 0 and it's percentage : 0.0
 Total NaN values in row 39 :- 0 and it's percentage : 0.0
 Total NaN values in row 40 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 41 :- 0 and it's percentage : 0.0
 Total NaN values in row 42 :- 0 and it's percentage : 0.0
 Total NaN values in row 43 :- 0 and it's percentage : 0.0
 Total NaN values in row 44 :- 0 and it's percentage : 0.0
 Total NaN values in row 45 :- 0 and it's percentage : 0.0
 Total NaN values in row 46 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 47 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 48 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 49 :- 0 and it's percentage : 0.0
 Total NaN values in row 50 :- 0 and it's percentage : 0.0
 Total NaN values in row 51 :- 0 and it's percentage : 0.0
 Total NaN values in row 52 :- 0 and it's percentage : 0.0
 Total NaN values in row 53 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 54 :- 0 and it's percentage : 0.0
 Total NaN values in row 55 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 56 :- 0 and it's percentage : 0.0
 Total NaN values in row 57 :- 0 and it's percentage : 0.0
 Total NaN values in row 58 :- 0 and it's percentage : 0.0
 Total NaN values in row 59 :- 0 and it's percentage : 0.0
 Total NaN values in row 60 :- 0 and it's percentage : 0.0
 Total NaN values in row 61 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 62 :- 0 and it's percentage : 0.0
 Total NaN values in row 63 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 64 :- 0 and it's percentage : 0.0
 Total NaN values in row 65 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 66 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 67 :- 0 and it's percentage : 0.0
 Total NaN values in row 68 :- 0 and it's percentage : 0.0
 Total NaN values in row 69 :- 0 and it's percentage : 0.0
 Total NaN values in row 70 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 71 :- 0 and it's percentage : 0.0
 Total NaN values in row 72 :- 0 and it's percentage : 0.0
 Total NaN values in row 73 :- 0 and it's percentage : 0.0
 Total NaN values in row 74 :- 0 and it's percentage : 0.0
 Total NaN values in row 75 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 76 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 77 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 78 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 79 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 80 :- 0 and it's percentage : 0.0
 Total NaN values in row 81 :- 0 and it's percentage : 0.0
 Total NaN values in row 82 :- 0 and it's percentage : 0.0
 Total NaN values in row 83 :- 0 and it's percentage : 0.0
 Total NaN values in row 84 :- 0 and it's percentage : 0.0
 Total NaN values in row 85 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 86 :- 0 and it's percentage : 0.0
 Total NaN values in row 87 :- 0 and it's percentage : 0.0
 Total NaN values in row 88 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 89 :- 0 and it's percentage : 0.0
 Total NaN values in row 90 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 91 :- 0 and it's percentage : 0.0
 Total NaN values in row 92 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 93 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 94 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 95 :- 0 and it's percentage : 0.0
 Total NaN values in row 96 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 97 :- 0 and it's percentage : 0.0
 Total NaN values in row 98 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 99 :- 0 and it's percentage : 0.0
 Total NaN values in row 100 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 101 :- 0 and it's percentage : 0.0
 Total NaN values in row 102 :- 0 and it's percentage : 0.0
 Total NaN values in row 103 :- 0 and it's percentage : 0.0
 Total NaN values in row 104 :- 0 and it's percentage : 0.0
 Total NaN values in row 105 :- 0 and it's percentage : 0.0
 Total NaN values in row 106 :- 0 and it's percentage : 0.0
 Total NaN values in row 107 :- 0 and it's percentage : 0.0
 Total NaN values in row 108 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 109 :- 0 and it's percentage : 0.0
 Total NaN values in row 110 :- 0 and it's percentage : 0.0
 Total NaN values in row 111 :- 0 and it's percentage : 0.0
 Total NaN values in row 112 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 113 :- 0 and it's percentage : 0.0
 Total NaN values in row 114 :- 0 and it's percentage : 0.0
 Total NaN values in row 115 :- 0 and it's percentage : 0.0
 Total NaN values in row 116 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 117 :- 0 and it's percentage : 0.0
 Total NaN values in row 118 :- 0 and it's percentage : 0.0
 Total NaN values in row 119 :- 0 and it's percentage : 0.0
 Total NaN values in row 120 :- 0 and it's percentage : 0.0
 Total NaN values in row 121 :- 0 and it's percentage : 0.0
 Total NaN values in row 122 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 123 :- 0 and it's percentage : 0.0
 Total NaN values in row 124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 126 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 127 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 129 :- 0 and it's percentage : 0.0
 Total NaN values in row 130 :- 0 and it's percentage : 0.0
 Total NaN values in row 131 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 132 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 133 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 134 :- 0 and it's percentage : 0.0
 Total NaN values in row 135 :- 0 and it's percentage : 0.0
 Total NaN values in row 136 :- 0 and it's percentage : 0.0
 Total NaN values in row 137 :- 0 and it's percentage : 0.0
 Total NaN values in row 138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 139 :- 0 and it's percentage : 0.0
 Total NaN values in row 140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 141 :- 0 and it's percentage : 0.0
 Total NaN values in row 142 :- 0 and it's percentage : 0.0
 Total NaN values in row 143 :- 0 and it's percentage : 0.0
 Total NaN values in row 144 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 145 :- 0 and it's percentage : 0.0
 Total NaN values in row 146 :- 0 and it's percentage : 0.0
 Total NaN values in row 147 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 148 :- 0 and it's percentage : 0.0
 Total NaN values in row 149 :- 0 and it's percentage : 0.0
 Total NaN values in row 150 :- 0 and it's percentage : 0.0
 Total NaN values in row 151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 152 :- 0 and it's percentage : 0.0
 Total NaN values in row 153 :- 0 and it's percentage : 0.0
 Total NaN values in row 154 :- 0 and it's percentage : 0.0
 Total NaN values in row 155 :- 0 and it's percentage : 0.0
 Total NaN values in row 156 :- 0 and it's percentage : 0.0
 Total NaN values in row 157 :- 0 and it's percentage : 0.0
 Total NaN values in row 158 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 159 :- 0 and it's percentage : 0.0
 Total NaN values in row 160 :- 0 and it's percentage : 0.0
 Total NaN values in row 161 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 162 :- 0 and it's percentage : 0.0
 Total NaN values in row 163 :- 0 and it's percentage : 0.0
 Total NaN values in row 164 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 165 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 166 :- 0 and it's percentage : 0.0
 Total NaN values in row 167 :- 0 and it's percentage : 0.0
 Total NaN values in row 168 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 169 :- 0 and it's percentage : 0.0
 Total NaN values in row 170 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 171 :- 0 and it's percentage : 0.0
 Total NaN values in row 172 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 173 :- 0 and it's percentage : 0.0
 Total NaN values in row 174 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 175 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 176 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 177 :- 0 and it's percentage : 0.0
 Total NaN values in row 178 :- 0 and it's percentage : 0.0
 Total NaN values in row 179 :- 0 and it's percentage : 0.0
 Total NaN values in row 180 :- 0 and it's percentage : 0.0
 Total NaN values in row 181 :- 0 and it's percentage : 0.0
 Total NaN values in row 182 :- 0 and it's percentage : 0.0
 Total NaN values in row 183 :- 0 and it's percentage : 0.0
 Total NaN values in row 184 :- 0 and it's percentage : 0.0
 Total NaN values in row 185 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 186 :- 0 and it's percentage : 0.0
 Total NaN values in row 187 :- 0 and it's percentage : 0.0
 Total NaN values in row 188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 189 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 190 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 191 :- 0 and it's percentage : 0.0
 Total NaN values in row 192 :- 0 and it's percentage : 0.0
 Total NaN values in row 193 :- 0 and it's percentage : 0.0
 Total NaN values in row 194 :- 0 and it's percentage : 0.0
 Total NaN values in row 195 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 196 :- 0 and it's percentage : 0.0
 Total NaN values in row 197 :- 0 and it's percentage : 0.0
 Total NaN values in row 198 :- 0 and it's percentage : 0.0
 Total NaN values in row 199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 201 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 202 :- 0 and it's percentage : 0.0
 Total NaN values in row 203 :- 0 and it's percentage : 0.0
 Total NaN values in row 204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 205 :- 0 and it's percentage : 0.0
 Total NaN values in row 206 :- 0 and it's percentage : 0.0
 Total NaN values in row 207 :- 0 and it's percentage : 0.0
 Total NaN values in row 208 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 209 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 210 :- 0 and it's percentage : 0.0
 Total NaN values in row 211 :- 0 and it's percentage : 0.0
 Total NaN values in row 212 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 213 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 214 :- 0 and it's percentage : 0.0
 Total NaN values in row 215 :- 0 and it's percentage : 0.0
 Total NaN values in row 216 :- 0 and it's percentage : 0.0
 Total NaN values in row 217 :- 0 and it's percentage : 0.0
 Total NaN values in row 218 :- 0 and it's percentage : 0.0
 Total NaN values in row 219 :- 0 and it's percentage : 0.0
 Total NaN values in row 220 :- 0 and it's percentage : 0.0
 Total NaN values in row 221 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 222 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 223 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 224 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 225 :- 0 and it's percentage : 0.0
 Total NaN values in row 226 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 227 :- 0 and it's percentage : 0.0
 Total NaN values in row 228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 229 :- 0 and it's percentage : 0.0
 Total NaN values in row 230 :- 0 and it's percentage : 0.0
 Total NaN values in row 231 :- 0 and it's percentage : 0.0
 Total NaN values in row 232 :- 0 and it's percentage : 0.0
 Total NaN values in row 233 :- 0 and it's percentage : 0.0
 Total NaN values in row 234 :- 0 and it's percentage : 0.0
 Total NaN values in row 235 :- 0 and it's percentage : 0.0
 Total NaN values in row 236 :- 0 and it's percentage : 0.0
 Total NaN values in row 237 :- 0 and it's percentage : 0.0
 Total NaN values in row 238 :- 0 and it's percentage : 0.0
 Total NaN values in row 239 :- 0 and it's percentage : 0.0
 Total NaN values in row 240 :- 0 and it's percentage : 0.0
 Total NaN values in row 241 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 242 :- 0 and it's percentage : 0.0
 Total NaN values in row 243 :- 0 and it's percentage : 0.0
 Total NaN values in row 244 :- 0 and it's percentage : 0.0
 Total NaN values in row 245 :- 0 and it's percentage : 0.0
 Total NaN values in row 246 :- 0 and it's percentage : 0.0
 Total NaN values in row 247 :- 0 and it's percentage : 0.0
 Total NaN values in row 248 :- 0 and it's percentage : 0.0
 Total NaN values in row 249 :- 0 and it's percentage : 0.0
 Total NaN values in row 250 :- 0 and it's percentage : 0.0
 Total NaN values in row 251 :- 0 and it's percentage : 0.0
 Total NaN values in row 252 :- 0 and it's percentage : 0.0
 Total NaN values in row 253 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 254 :- 0 and it's percentage : 0.0
 Total NaN values in row 255 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 256 :- 0 and it's percentage : 0.0
 Total NaN values in row 257 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 258 :- 0 and it's percentage : 0.0
 Total NaN values in row 259 :- 0 and it's percentage : 0.0
 Total NaN values in row 260 :- 0 and it's percentage : 0.0
 Total NaN values in row 261 :- 0 and it's percentage : 0.0
 Total NaN values in row 262 :- 0 and it's percentage : 0.0
 Total NaN values in row 263 :- 0 and it's percentage : 0.0
 Total NaN values in row 264 :- 0 and it's percentage : 0.0
 Total NaN values in row 265 :- 0 and it's percentage : 0.0
 Total NaN values in row 266 :- 0 and it's percentage : 0.0
 Total NaN values in row 267 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 268 :- 0 and it's percentage : 0.0
 Total NaN values in row 269 :- 0 and it's percentage : 0.0
 Total NaN values in row 270 :- 0 and it's percentage : 0.0
 Total NaN values in row 271 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 272 :- 0 and it's percentage : 0.0
 Total NaN values in row 273 :- 0 and it's percentage : 0.0
 Total NaN values in row 274 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 275 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 276 :- 0 and it's percentage : 0.0
 Total NaN values in row 277 :- 0 and it's percentage : 0.0
 Total NaN values in row 278 :- 0 and it's percentage : 0.0
 Total NaN values in row 279 :- 0 and it's percentage : 0.0
 Total NaN values in row 280 :- 0 and it's percentage : 0.0
 Total NaN values in row 281 :- 0 and it's percentage : 0.0
 Total NaN values in row 282 :- 0 and it's percentage : 0.0
 Total NaN values in row 283 :- 0 and it's percentage : 0.0
 Total NaN values in row 284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 285 :- 0 and it's percentage : 0.0
 Total NaN values in row 286 :- 0 and it's percentage : 0.0
 Total NaN values in row 287 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 288 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 289 :- 0 and it's percentage : 0.0
 Total NaN values in row 290 :- 0 and it's percentage : 0.0
 Total NaN values in row 291 :- 0 and it's percentage : 0.0
 Total NaN values in row 292 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 293 :- 0 and it's percentage : 0.0
 Total NaN values in row 294 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 295 :- 0 and it's percentage : 0.0
 Total NaN values in row 296 :- 0 and it's percentage : 0.0
 Total NaN values in row 297 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 298 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 299 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 300 :- 0 and it's percentage : 0.0
 Total NaN values in row 301 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 302 :- 0 and it's percentage : 0.0
 Total NaN values in row 303 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 304 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 305 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 306 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 307 :- 0 and it's percentage : 0.0
 Total NaN values in row 308 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 309 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 310 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 311 :- 0 and it's percentage : 0.0
 Total NaN values in row 312 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 313 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 314 :- 0 and it's percentage : 0.0
 Total NaN values in row 315 :- 0 and it's percentage : 0.0
 Total NaN values in row 316 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 317 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 318 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 319 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 320 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 321 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 322 :- 0 and it's percentage : 0.0
 Total NaN values in row 323 :- 0 and it's percentage : 0.0
 Total NaN values in row 324 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 325 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 326 :- 0 and it's percentage : 0.0
 Total NaN values in row 327 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 328 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 329 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 330 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 331 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 332 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 334 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 335 :- 0 and it's percentage : 0.0
 Total NaN values in row 336 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 337 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 338 :- 0 and it's percentage : 0.0
 Total NaN values in row 339 :- 0 and it's percentage : 0.0
 Total NaN values in row 340 :- 0 and it's percentage : 0.0
 Total NaN values in row 341 :- 0 and it's percentage : 0.0
 Total NaN values in row 342 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 343 :- 0 and it's percentage : 0.0
 Total NaN values in row 344 :- 0 and it's percentage : 0.0
 Total NaN values in row 345 :- 0 and it's percentage : 0.0
 Total NaN values in row 346 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 347 :- 0 and it's percentage : 0.0
 Total NaN values in row 348 :- 0 and it's percentage : 0.0
 Total NaN values in row 349 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 350 :- 0 and it's percentage : 0.0
 Total NaN values in row 351 :- 0 and it's percentage : 0.0
 Total NaN values in row 352 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 353 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 354 :- 0 and it's percentage : 0.0
 Total NaN values in row 355 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 356 :- 0 and it's percentage : 0.0
 Total NaN values in row 357 :- 0 and it's percentage : 0.0
 Total NaN values in row 358 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 359 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 360 :- 0 and it's percentage : 0.0
 Total NaN values in row 361 :- 0 and it's percentage : 0.0
 Total NaN values in row 362 :- 0 and it's percentage : 0.0
 Total NaN values in row 363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 364 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 365 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 366 :- 0 and it's percentage : 0.0
 Total NaN values in row 367 :- 0 and it's percentage : 0.0
 Total NaN values in row 368 :- 0 and it's percentage : 0.0
 Total NaN values in row 369 :- 0 and it's percentage : 0.0
 Total NaN values in row 370 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 371 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 372 :- 0 and it's percentage : 0.0
 Total NaN values in row 373 :- 0 and it's percentage : 0.0
 Total NaN values in row 374 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 376 :- 0 and it's percentage : 0.0
 Total NaN values in row 377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 378 :- 0 and it's percentage : 0.0
 Total NaN values in row 379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 380 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 381 :- 0 and it's percentage : 0.0
 Total NaN values in row 382 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 383 :- 0 and it's percentage : 0.0
 Total NaN values in row 384 :- 0 and it's percentage : 0.0
 Total NaN values in row 385 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 387 :- 0 and it's percentage : 0.0
 Total NaN values in row 388 :- 0 and it's percentage : 0.0
 Total NaN values in row 389 :- 0 and it's percentage : 0.0
 Total NaN values in row 390 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 391 :- 0 and it's percentage : 0.0

 Total NaN values in row 392 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 393 :- 0 and it's percentage : 0.0
 Total NaN values in row 394 :- 0 and it's percentage : 0.0
 Total NaN values in row 395 :- 0 and it's percentage : 0.0
 Total NaN values in row 396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 398 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 399 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 400 :- 0 and it's percentage : 0.0
 Total NaN values in row 401 :- 0 and it's percentage : 0.0
 Total NaN values in row 402 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 403 :- 0 and it's percentage : 0.0
 Total NaN values in row 404 :- 0 and it's percentage : 0.0
 Total NaN values in row 405 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 406 :- 0 and it's percentage : 0.0
 Total NaN values in row 407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 408 :- 0 and it's percentage : 0.0
 Total NaN values in row 409 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 410 :- 0 and it's percentage : 0.0
 Total NaN values in row 411 :- 0 and it's percentage : 0.0
 Total NaN values in row 412 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 413 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 414 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 415 :- 0 and it's percentage : 0.0
 Total NaN values in row 416 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 417 :- 0 and it's percentage : 0.0
 Total NaN values in row 418 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 419 :- 0 and it's percentage : 0.0
 Total NaN values in row 420 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 421 :- 0 and it's percentage : 0.0
 Total NaN values in row 422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 423 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 424 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 425 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 426 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 427 :- 0 and it's percentage : 0.0
 Total NaN values in row 428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 429 :- 0 and it's percentage : 0.0
 Total NaN values in row 430 :- 0 and it's percentage : 0.0
 Total NaN values in row 431 :- 0 and it's percentage : 0.0
 Total NaN values in row 432 :- 0 and it's percentage : 0.0
 Total NaN values in row 433 :- 0 and it's percentage : 0.0
 Total NaN values in row 434 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 435 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 436 :- 0 and it's percentage : 0.0
 Total NaN values in row 437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 438 :- 0 and it's percentage : 0.0
 Total NaN values in row 439 :- 0 and it's percentage : 0.0
 Total NaN values in row 440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 441 :- 0 and it's percentage : 0.0
 Total NaN values in row 442 :- 0 and it's percentage : 0.0
 Total NaN values in row 443 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 444 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 445 :- 0 and it's percentage : 0.0
 Total NaN values in row 446 :- 0 and it's percentage : 0.0
 Total NaN values in row 447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 449 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 450 :- 0 and it's percentage : 0.0
 Total NaN values in row 451 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 452 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 453 :- 0 and it's percentage : 0.0
 Total NaN values in row 454 :- 0 and it's percentage : 0.0
 Total NaN values in row 455 :- 0 and it's percentage : 0.0
 Total NaN values in row 456 :- 0 and it's percentage : 0.0
 Total NaN values in row 457 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 458 :- 0 and it's percentage : 0.0
 Total NaN values in row 459 :- 0 and it's percentage : 0.0
 Total NaN values in row 460 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 461 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 462 :- 0 and it's percentage : 0.0
 Total NaN values in row 463 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 464 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 465 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 466 :- 0 and it's percentage : 0.0
 Total NaN values in row 467 :- 0 and it's percentage : 0.0
 Total NaN values in row 468 :- 0 and it's percentage : 0.0
 Total NaN values in row 469 :- 0 and it's percentage : 0.0
 Total NaN values in row 470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 472 :- 0 and it's percentage : 0.0
 Total NaN values in row 473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 474 :- 0 and it's percentage : 0.0
 Total NaN values in row 475 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 478 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 479 :- 0 and it's percentage : 0.0
 Total NaN values in row 480 :- 0 and it's percentage : 0.0
 Total NaN values in row 481 :- 0 and it's percentage : 0.0
 Total NaN values in row 482 :- 0 and it's percentage : 0.0
 Total NaN values in row 483 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 484 :- 0 and it's percentage : 0.0
 Total NaN values in row 485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 486 :- 0 and it's percentage : 0.0
 Total NaN values in row 487 :- 0 and it's percentage : 0.0
 Total NaN values in row 488 :- 0 and it's percentage : 0.0
 Total NaN values in row 489 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 490 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 491 :- 0 and it's percentage : 0.0
 Total NaN values in row 492 :- 0 and it's percentage : 0.0
 Total NaN values in row 493 :- 0 and it's percentage : 0.0
 Total NaN values in row 494 :- 0 and it's percentage : 0.0
 Total NaN values in row 495 :- 0 and it's percentage : 0.0
 Total NaN values in row 496 :- 0 and it's percentage : 0.0
 Total NaN values in row 497 :- 0 and it's percentage : 0.0
 Total NaN values in row 498 :- 0 and it's percentage : 0.0
 Total NaN values in row 499 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 500 :- 0 and it's percentage : 0.0
 Total NaN values in row 501 :- 0 and it's percentage : 0.0
 Total NaN values in row 502 :- 0 and it's percentage : 0.0
 Total NaN values in row 503 :- 0 and it's percentage : 0.0
 Total NaN values in row 504 :- 0 and it's percentage : 0.0
 Total NaN values in row 505 :- 0 and it's percentage : 0.0
 Total NaN values in row 506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 507 :- 0 and it's percentage : 0.0
 Total NaN values in row 508 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 509 :- 0 and it's percentage : 0.0
 Total NaN values in row 510 :- 0 and it's percentage : 0.0
 Total NaN values in row 511 :- 0 and it's percentage : 0.0
 Total NaN values in row 512 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 513 :- 0 and it's percentage : 0.0
 Total NaN values in row 514 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 515 :- 0 and it's percentage : 0.0
 Total NaN values in row 516 :- 0 and it's percentage : 0.0
 Total NaN values in row 517 :- 0 and it's percentage : 0.0
 Total NaN values in row 518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 519 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 520 :- 0 and it's percentage : 0.0
 Total NaN values in row 521 :- 0 and it's percentage : 0.0
 Total NaN values in row 522 :- 0 and it's percentage : 0.0
 Total NaN values in row 523 :- 0 and it's percentage : 0.0
 Total NaN values in row 524 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 525 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 526 :- 0 and it's percentage : 0.0
 Total NaN values in row 527 :- 0 and it's percentage : 0.0
 Total NaN values in row 528 :- 0 and it's percentage : 0.0
 Total NaN values in row 529 :- 0 and it's percentage : 0.0
 Total NaN values in row 530 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 531 :- 0 and it's percentage : 0.0

 Total NaN values in row 532 :- 0 and it's percentage : 0.0
 Total NaN values in row 533 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 534 :- 0 and it's percentage : 0.0
 Total NaN values in row 535 :- 0 and it's percentage : 0.0
 Total NaN values in row 536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 537 :- 0 and it's percentage : 0.0
 Total NaN values in row 538 :- 0 and it's percentage : 0.0
 Total NaN values in row 539 :- 0 and it's percentage : 0.0
 Total NaN values in row 540 :- 0 and it's percentage : 0.0
 Total NaN values in row 541 :- 0 and it's percentage : 0.0
 Total NaN values in row 542 :- 0 and it's percentage : 0.0
 Total NaN values in row 543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 544 :- 0 and it's percentage : 0.0
 Total NaN values in row 545 :- 0 and it's percentage : 0.0
 Total NaN values in row 546 :- 0 and it's percentage : 0.0
 Total NaN values in row 547 :- 0 and it's percentage : 0.0
 Total NaN values in row 548 :- 0 and it's percentage : 0.0
 Total NaN values in row 549 :- 0 and it's percentage : 0.0
 Total NaN values in row 550 :- 0 and it's percentage : 0.0
 Total NaN values in row 551 :- 0 and it's percentage : 0.0
 Total NaN values in row 552 :- 0 and it's percentage : 0.0
 Total NaN values in row 553 :- 0 and it's percentage : 0.0
 Total NaN values in row 554 :- 0 and it's percentage : 0.0
 Total NaN values in row 555 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 556 :- 0 and it's percentage : 0.0
 Total NaN values in row 557 :- 0 and it's percentage : 0.0
 Total NaN values in row 558 :- 0 and it's percentage : 0.0
 Total NaN values in row 559 :- 0 and it's percentage : 0.0
 Total NaN values in row 560 :- 0 and it's percentage : 0.0
 Total NaN values in row 561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 562 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 563 :- 0 and it's percentage : 0.0
 Total NaN values in row 564 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 565 :- 0 and it's percentage : 0.0
 Total NaN values in row 566 :- 0 and it's percentage : 0.0
 Total NaN values in row 567 :- 0 and it's percentage : 0.0
 Total NaN values in row 568 :- 0 and it's percentage : 0.0
 Total NaN values in row 569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 570 :- 0 and it's percentage : 0.0
 Total NaN values in row 571 :- 0 and it's percentage : 0.0
 Total NaN values in row 572 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 573 :- 0 and it's percentage : 0.0
 Total NaN values in row 574 :- 0 and it's percentage : 0.0
 Total NaN values in row 575 :- 0 and it's percentage : 0.0
 Total NaN values in row 576 :- 0 and it's percentage : 0.0
 Total NaN values in row 577 :- 0 and it's percentage : 0.0
 Total NaN values in row 578 :- 0 and it's percentage : 0.0
 Total NaN values in row 579 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 580 :- 0 and it's percentage : 0.0
 Total NaN values in row 581 :- 0 and it's percentage : 0.0
 Total NaN values in row 582 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 583 :- 0 and it's percentage : 0.0
 Total NaN values in row 584 :- 0 and it's percentage : 0.0
 Total NaN values in row 585 :- 0 and it's percentage : 0.0
 Total NaN values in row 586 :- 0 and it's percentage : 0.0
 Total NaN values in row 587 :- 0 and it's percentage : 0.0
 Total NaN values in row 588 :- 0 and it's percentage : 0.0
 Total NaN values in row 589 :- 0 and it's percentage : 0.0
 Total NaN values in row 590 :- 0 and it's percentage : 0.0
 Total NaN values in row 591 :- 0 and it's percentage : 0.0
 Total NaN values in row 592 :- 0 and it's percentage : 0.0
 Total NaN values in row 593 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 595 :- 0 and it's percentage : 0.0
 Total NaN values in row 596 :- 0 and it's percentage : 0.0
 Total NaN values in row 597 :- 0 and it's percentage : 0.0
 Total NaN values in row 598 :- 0 and it's percentage : 0.0
 Total NaN values in row 599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 600 :- 0 and it's percentage : 0.0
 Total NaN values in row 601 :- 0 and it's percentage : 0.0
 Total NaN values in row 602 :- 0 and it's percentage : 0.0
 Total NaN values in row 603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 604 :- 0 and it's percentage : 0.0
 Total NaN values in row 605 :- 0 and it's percentage : 0.0
 Total NaN values in row 606 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 607 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 608 :- 0 and it's percentage : 0.0
 Total NaN values in row 609 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 610 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 611 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 612 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 613 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 614 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 615 :- 0 and it's percentage : 0.0
 Total NaN values in row 616 :- 0 and it's percentage : 0.0
 Total NaN values in row 617 :- 0 and it's percentage : 0.0
 Total NaN values in row 618 :- 0 and it's percentage : 0.0
 Total NaN values in row 619 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 620 :- 0 and it's percentage : 0.0
 Total NaN values in row 621 :- 0 and it's percentage : 0.0
 Total NaN values in row 622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 624 :- 0 and it's percentage : 0.0
 Total NaN values in row 625 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 626 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 627 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 629 :- 0 and it's percentage : 0.0
 Total NaN values in row 630 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 631 :- 0 and it's percentage : 0.0
 Total NaN values in row 632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 633 :- 0 and it's percentage : 0.0
 Total NaN values in row 634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 635 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 636 :- 0 and it's percentage : 0.0
 Total NaN values in row 637 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 638 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 639 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 641 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 642 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 643 :- 0 and it's percentage : 0.0
 Total NaN values in row 644 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 645 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 646 :- 0 and it's percentage : 0.0
 Total NaN values in row 647 :- 0 and it's percentage : 0.0
 Total NaN values in row 648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 649 :- 0 and it's percentage : 0.0
 Total NaN values in row 650 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 651 :- 0 and it's percentage : 0.0
 Total NaN values in row 652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 653 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 654 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 655 :- 0 and it's percentage : 0.0
 Total NaN values in row 656 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 657 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 658 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 659 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 660 :- 0 and it's percentage : 0.0
 Total NaN values in row 661 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 662 :- 7 and it's percentage : 38.888888888888886

 Total NaN values in row 663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 664 :- 0 and it's percentage : 0.0
 Total NaN values in row 665 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 666 :- 0 and it's percentage : 0.0
 Total NaN values in row 667 :- 0 and it's percentage : 0.0
 Total NaN values in row 668 :- 0 and it's percentage : 0.0
 Total NaN values in row 669 :- 0 and it's percentage : 0.0
 Total NaN values in row 670 :- 0 and it's percentage : 0.0
 Total NaN values in row 671 :- 0 and it's percentage : 0.0
 Total NaN values in row 672 :- 0 and it's percentage : 0.0
 Total NaN values in row 673 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 674 :- 0 and it's percentage : 0.0
 Total NaN values in row 675 :- 0 and it's percentage : 0.0
 Total NaN values in row 676 :- 0 and it's percentage : 0.0
 Total NaN values in row 677 :- 0 and it's percentage : 0.0
 Total NaN values in row 678 :- 0 and it's percentage : 0.0
 Total NaN values in row 679 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 681 :- 0 and it's percentage : 0.0
 Total NaN values in row 682 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 683 :- 0 and it's percentage : 0.0
 Total NaN values in row 684 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 685 :- 0 and it's percentage : 0.0
 Total NaN values in row 686 :- 0 and it's percentage : 0.0
 Total NaN values in row 687 :- 0 and it's percentage : 0.0
 Total NaN values in row 688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 689 :- 0 and it's percentage : 0.0
 Total NaN values in row 690 :- 0 and it's percentage : 0.0
 Total NaN values in row 691 :- 0 and it's percentage : 0.0
 Total NaN values in row 692 :- 0 and it's percentage : 0.0
 Total NaN values in row 693 :- 0 and it's percentage : 0.0
 Total NaN values in row 694 :- 0 and it's percentage : 0.0
 Total NaN values in row 695 :- 0 and it's percentage : 0.0
 Total NaN values in row 696 :- 0 and it's percentage : 0.0
 Total NaN values in row 697 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 698 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 699 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 701 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 702 :- 0 and it's percentage : 0.0
 Total NaN values in row 703 :- 0 and it's percentage : 0.0
 Total NaN values in row 704 :- 0 and it's percentage : 0.0
 Total NaN values in row 705 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 706 :- 0 and it's percentage : 0.0
 Total NaN values in row 707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 708 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 709 :- 0 and it's percentage : 0.0
 Total NaN values in row 710 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 711 :- 0 and it's percentage : 0.0
 Total NaN values in row 712 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 713 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 714 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 715 :- 0 and it's percentage : 0.0
 Total NaN values in row 716 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 717 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 718 :- 0 and it's percentage : 0.0
 Total NaN values in row 719 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 720 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 722 :- 0 and it's percentage : 0.0
 Total NaN values in row 723 :- 0 and it's percentage : 0.0
 Total NaN values in row 724 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 725 :- 0 and it's percentage : 0.0
 Total NaN values in row 726 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 727 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 728 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 729 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 730 :- 0 and it's percentage : 0.0
 Total NaN values in row 731 :- 0 and it's percentage : 0.0
 Total NaN values in row 732 :- 0 and it's percentage : 0.0
 Total NaN values in row 733 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 734 :- 0 and it's percentage : 0.0
 Total NaN values in row 735 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 736 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 737 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 738 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 739 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 740 :- 0 and it's percentage : 0.0
 Total NaN values in row 741 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 744 :- 0 and it's percentage : 0.0
 Total NaN values in row 745 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 746 :- 0 and it's percentage : 0.0
 Total NaN values in row 747 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 748 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 749 :- 0 and it's percentage : 0.0
 Total NaN values in row 750 :- 0 and it's percentage : 0.0
 Total NaN values in row 751 :- 0 and it's percentage : 0.0
 Total NaN values in row 752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 753 :- 0 and it's percentage : 0.0
 Total NaN values in row 754 :- 0 and it's percentage : 0.0
 Total NaN values in row 755 :- 0 and it's percentage : 0.0
 Total NaN values in row 756 :- 0 and it's percentage : 0.0
 Total NaN values in row 757 :- 0 and it's percentage : 0.0
 Total NaN values in row 758 :- 0 and it's percentage : 0.0
 Total NaN values in row 759 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 761 :- 0 and it's percentage : 0.0
 Total NaN values in row 762 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 763 :- 0 and it's percentage : 0.0
 Total NaN values in row 764 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 765 :- 0 and it's percentage : 0.0
 Total NaN values in row 766 :- 0 and it's percentage : 0.0
 Total NaN values in row 767 :- 0 and it's percentage : 0.0
 Total NaN values in row 768 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 769 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 770 :- 0 and it's percentage : 0.0
 Total NaN values in row 771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 772 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 773 :- 0 and it's percentage : 0.0
 Total NaN values in row 774 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 775 :- 0 and it's percentage : 0.0
 Total NaN values in row 776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 777 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 779 :- 0 and it's percentage : 0.0
 Total NaN values in row 780 :- 0 and it's percentage : 0.0
 Total NaN values in row 781 :- 0 and it's percentage : 0.0
 Total NaN values in row 782 :- 0 and it's percentage : 0.0
 Total NaN values in row 783 :- 0 and it's percentage : 0.0
 Total NaN values in row 784 :- 0 and it's percentage : 0.0
 Total NaN values in row 785 :- 0 and it's percentage : 0.0
 Total NaN values in row 786 :- 0 and it's percentage : 0.0
 Total NaN values in row 787 :- 0 and it's percentage : 0.0
 Total NaN values in row 788 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 789 :- 0 and it's percentage : 0.0
 Total NaN values in row 790 :- 0 and it's percentage : 0.0
 Total NaN values in row 791 :- 0 and it's percentage : 0.0
 Total NaN values in row 792 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 793 :- 0 and it's percentage : 0.0
 Total NaN values in row 794 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 795 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 796 :- 0 and it's percentage : 0.0
 Total NaN values in row 797 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 798 :- 0 and it's percentage : 0.0
 Total NaN values in row 799 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 800 :- 0 and it's percentage : 0.0
 Total NaN values in row 801 :- 0 and it's percentage : 0.0
 Total NaN values in row 802 :- 0 and it's percentage : 0.0
 Total NaN values in row 803 :- 0 and it's percentage : 0.0
 Total NaN values in row 804 :- 0 and it's percentage : 0.0
 Total NaN values in row 805 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 806 :- 0 and it's percentage : 0.0
 Total NaN values in row 807 :- 0 and it's percentage : 0.0
 Total NaN values in row 808 :- 0 and it's percentage : 0.0
 Total NaN values in row 809 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 810 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 811 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 812 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 813 :- 0 and it's percentage : 0.0
 Total NaN values in row 814 :- 0 and it's percentage : 0.0

 Total NaN values in row 815 :- 0 and it's percentage : 0.0
 Total NaN values in row 816 :- 0 and it's percentage : 0.0
 Total NaN values in row 817 :- 0 and it's percentage : 0.0
 Total NaN values in row 818 :- 0 and it's percentage : 0.0
 Total NaN values in row 819 :- 0 and it's percentage : 0.0
 Total NaN values in row 820 :- 0 and it's percentage : 0.0
 Total NaN values in row 821 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 822 :- 0 and it's percentage : 0.0
 Total NaN values in row 823 :- 0 and it's percentage : 0.0
 Total NaN values in row 824 :- 0 and it's percentage : 0.0
 Total NaN values in row 825 :- 0 and it's percentage : 0.0
 Total NaN values in row 826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 827 :- 0 and it's percentage : 0.0
 Total NaN values in row 828 :- 0 and it's percentage : 0.0
 Total NaN values in row 829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 830 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 832 :- 0 and it's percentage : 0.0
 Total NaN values in row 833 :- 0 and it's percentage : 0.0
 Total NaN values in row 834 :- 0 and it's percentage : 0.0
 Total NaN values in row 835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 836 :- 0 and it's percentage : 0.0
 Total NaN values in row 837 :- 0 and it's percentage : 0.0
 Total NaN values in row 838 :- 0 and it's percentage : 0.0
 Total NaN values in row 839 :- 0 and it's percentage : 0.0
 Total NaN values in row 840 :- 0 and it's percentage : 0.0
 Total NaN values in row 841 :- 0 and it's percentage : 0.0
 Total NaN values in row 842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 843 :- 0 and it's percentage : 0.0
 Total NaN values in row 844 :- 0 and it's percentage : 0.0
 Total NaN values in row 845 :- 0 and it's percentage : 0.0
 Total NaN values in row 846 :- 0 and it's percentage : 0.0
 Total NaN values in row 847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 848 :- 0 and it's percentage : 0.0
 Total NaN values in row 849 :- 0 and it's percentage : 0.0
 Total NaN values in row 850 :- 0 and it's percentage : 0.0
 Total NaN values in row 851 :- 0 and it's percentage : 0.0
 Total NaN values in row 852 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 853 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 854 :- 0 and it's percentage : 0.0
 Total NaN values in row 855 :- 0 and it's percentage : 0.0
 Total NaN values in row 856 :- 0 and it's percentage : 0.0
 Total NaN values in row 857 :- 0 and it's percentage : 0.0
 Total NaN values in row 858 :- 0 and it's percentage : 0.0
 Total NaN values in row 859 :- 0 and it's percentage : 0.0
 Total NaN values in row 860 :- 0 and it's percentage : 0.0
 Total NaN values in row 861 :- 0 and it's percentage : 0.0
 Total NaN values in row 862 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 863 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 865 :- 0 and it's percentage : 0.0
 Total NaN values in row 866 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 867 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 868 :- 0 and it's percentage : 0.0
 Total NaN values in row 869 :- 0 and it's percentage : 0.0
 Total NaN values in row 870 :- 0 and it's percentage : 0.0
 Total NaN values in row 871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 872 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 873 :- 0 and it's percentage : 0.0
 Total NaN values in row 874 :- 0 and it's percentage : 0.0
 Total NaN values in row 875 :- 0 and it's percentage : 0.0
 Total NaN values in row 876 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 878 :- 0 and it's percentage : 0.0
 Total NaN values in row 879 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 880 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 881 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 882 :- 0 and it's percentage : 0.0
 Total NaN values in row 883 :- 0 and it's percentage : 0.0
 Total NaN values in row 884 :- 0 and it's percentage : 0.0
 Total NaN values in row 885 :- 0 and it's percentage : 0.0
 Total NaN values in row 886 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 887 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 888 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 889 :- 0 and it's percentage : 0.0
 Total NaN values in row 890 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 891 :- 0 and it's percentage : 0.0
 Total NaN values in row 892 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 893 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 894 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 895 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 896 :- 0 and it's percentage : 0.0
 Total NaN values in row 897 :- 0 and it's percentage : 0.0
 Total NaN values in row 898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 899 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 900 :- 0 and it's percentage : 0.0
 Total NaN values in row 901 :- 0 and it's percentage : 0.0
 Total NaN values in row 902 :- 0 and it's percentage : 0.0
 Total NaN values in row 903 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 904 :- 0 and it's percentage : 0.0
 Total NaN values in row 905 :- 0 and it's percentage : 0.0
 Total NaN values in row 906 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 907 :- 0 and it's percentage : 0.0
 Total NaN values in row 908 :- 0 and it's percentage : 0.0
 Total NaN values in row 909 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 910 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 911 :- 0 and it's percentage : 0.0
 Total NaN values in row 912 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 913 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 914 :- 0 and it's percentage : 0.0
 Total NaN values in row 915 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 916 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 917 :- 0 and it's percentage : 0.0
 Total NaN values in row 918 :- 0 and it's percentage : 0.0
 Total NaN values in row 919 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 920 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 921 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 924 :- 0 and it's percentage : 0.0
 Total NaN values in row 925 :- 0 and it's percentage : 0.0
 Total NaN values in row 926 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 927 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 928 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 930 :- 0 and it's percentage : 0.0
 Total NaN values in row 931 :- 0 and it's percentage : 0.0
 Total NaN values in row 932 :- 0 and it's percentage : 0.0
 Total NaN values in row 933 :- 0 and it's percentage : 0.0
 Total NaN values in row 934 :- 0 and it's percentage : 0.0
 Total NaN values in row 935 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 936 :- 0 and it's percentage : 0.0
 Total NaN values in row 937 :- 0 and it's percentage : 0.0
 Total NaN values in row 938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 939 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 940 :- 0 and it's percentage : 0.0
 Total NaN values in row 941 :- 0 and it's percentage : 0.0
 Total NaN values in row 942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 943 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 946 :- 0 and it's percentage : 0.0
 Total NaN values in row 947 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 948 :- 0 and it's percentage : 0.0
 Total NaN values in row 949 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 950 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 951 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 952 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 954 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 955 :- 0 and it's percentage : 0.0
 Total NaN values in row 956 :- 0 and it's percentage : 0.0
 Total NaN values in row 957 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 958 :- 0 and it's percentage : 0.0
 Total NaN values in row 959 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 960 :- 7 and it's percentage : 38.888888888888886

 Total NaN values in row 961 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 962 :- 0 and it's percentage : 0.0
 Total NaN values in row 963 :- 0 and it's percentage : 0.0
 Total NaN values in row 964 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 965 :- 0 and it's percentage : 0.0
 Total NaN values in row 966 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 967 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 968 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 969 :- 0 and it's percentage : 0.0
 Total NaN values in row 970 :- 0 and it's percentage : 0.0
 Total NaN values in row 971 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 972 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 974 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 975 :- 0 and it's percentage : 0.0
 Total NaN values in row 976 :- 0 and it's percentage : 0.0
 Total NaN values in row 977 :- 0 and it's percentage : 0.0
 Total NaN values in row 978 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 979 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 982 :- 0 and it's percentage : 0.0
 Total NaN values in row 983 :- 0 and it's percentage : 0.0
 Total NaN values in row 984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 985 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 986 :- 0 and it's percentage : 0.0
 Total NaN values in row 987 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 988 :- 0 and it's percentage : 0.0
 Total NaN values in row 989 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 990 :- 0 and it's percentage : 0.0
 Total NaN values in row 991 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 992 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 993 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 994 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 995 :- 0 and it's percentage : 0.0
 Total NaN values in row 996 :- 0 and it's percentage : 0.0
 Total NaN values in row 997 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 998 :- 0 and it's percentage : 0.0
 Total NaN values in row 999 :- 0 and it's percentage : 0.0
 Total NaN values in row 1000 :- 0 and it's percentage : 0.0
 Total NaN values in row 1001 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1002 :- 0 and it's percentage : 0.0
 Total NaN values in row 1003 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1004 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1005 :- 0 and it's percentage : 0.0
 Total NaN values in row 1006 :- 0 and it's percentage : 0.0
 Total NaN values in row 1007 :- 0 and it's percentage : 0.0
 Total NaN values in row 1008 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1009 :- 0 and it's percentage : 0.0
 Total NaN values in row 1010 :- 0 and it's percentage : 0.0
 Total NaN values in row 1011 :- 0 and it's percentage : 0.0
 Total NaN values in row 1012 :- 0 and it's percentage : 0.0
 Total NaN values in row 1013 :- 0 and it's percentage : 0.0
 Total NaN values in row 1014 :- 0 and it's percentage : 0.0
 Total NaN values in row 1015 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1016 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1017 :- 0 and it's percentage : 0.0
 Total NaN values in row 1018 :- 0 and it's percentage : 0.0
 Total NaN values in row 1019 :- 0 and it's percentage : 0.0
 Total NaN values in row 1020 :- 0 and it's percentage : 0.0
 Total NaN values in row 1021 :- 0 and it's percentage : 0.0
 Total NaN values in row 1022 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1023 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1024 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1025 :- 0 and it's percentage : 0.0
 Total NaN values in row 1026 :- 0 and it's percentage : 0.0
 Total NaN values in row 1027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1028 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1029 :- 0 and it's percentage : 0.0
 Total NaN values in row 1030 :- 0 and it's percentage : 0.0
 Total NaN values in row 1031 :- 0 and it's percentage : 0.0
 Total NaN values in row 1032 :- 0 and it's percentage : 0.0
 Total NaN values in row 1033 :- 0 and it's percentage : 0.0
 Total NaN values in row 1034 :- 0 and it's percentage : 0.0
 Total NaN values in row 1035 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1036 :- 0 and it's percentage : 0.0
 Total NaN values in row 1037 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1038 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1039 :- 0 and it's percentage : 0.0
 Total NaN values in row 1040 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1041 :- 0 and it's percentage : 0.0
 Total NaN values in row 1042 :- 0 and it's percentage : 0.0
 Total NaN values in row 1043 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1044 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1045 :- 0 and it's percentage : 0.0
 Total NaN values in row 1046 :- 0 and it's percentage : 0.0
 Total NaN values in row 1047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1048 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1049 :- 0 and it's percentage : 0.0
 Total NaN values in row 1050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1051 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1052 :- 0 and it's percentage : 0.0
 Total NaN values in row 1053 :- 0 and it's percentage : 0.0
 Total NaN values in row 1054 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1055 :- 0 and it's percentage : 0.0
 Total NaN values in row 1056 :- 0 and it's percentage : 0.0
 Total NaN values in row 1057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1058 :- 0 and it's percentage : 0.0
 Total NaN values in row 1059 :- 0 and it's percentage : 0.0
 Total NaN values in row 1060 :- 0 and it's percentage : 0.0
 Total NaN values in row 1061 :- 0 and it's percentage : 0.0
 Total NaN values in row 1062 :- 0 and it's percentage : 0.0
 Total NaN values in row 1063 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1064 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1066 :- 0 and it's percentage : 0.0
 Total NaN values in row 1067 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1068 :- 0 and it's percentage : 0.0
 Total NaN values in row 1069 :- 0 and it's percentage : 0.0
 Total NaN values in row 1070 :- 0 and it's percentage : 0.0
 Total NaN values in row 1071 :- 0 and it's percentage : 0.0
 Total NaN values in row 1072 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1073 :- 0 and it's percentage : 0.0
 Total NaN values in row 1074 :- 0 and it's percentage : 0.0
 Total NaN values in row 1075 :- 0 and it's percentage : 0.0
 Total NaN values in row 1076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1077 :- 0 and it's percentage : 0.0
 Total NaN values in row 1078 :- 0 and it's percentage : 0.0
 Total NaN values in row 1079 :- 0 and it's percentage : 0.0
 Total NaN values in row 1080 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1081 :- 0 and it's percentage : 0.0
 Total NaN values in row 1082 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1083 :- 0 and it's percentage : 0.0
 Total NaN values in row 1084 :- 0 and it's percentage : 0.0
 Total NaN values in row 1085 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1086 :- 0 and it's percentage : 0.0
 Total NaN values in row 1087 :- 0 and it's percentage : 0.0
 Total NaN values in row 1088 :- 0 and it's percentage : 0.0
 Total NaN values in row 1089 :- 0 and it's percentage : 0.0
 Total NaN values in row 1090 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1091 :- 0 and it's percentage : 0.0
 Total NaN values in row 1092 :- 0 and it's percentage : 0.0
 Total NaN values in row 1093 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1094 :- 0 and it's percentage : 0.0
 Total NaN values in row 1095 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1096 :- 0 and it's percentage : 0.0
 Total NaN values in row 1097 :- 0 and it's percentage : 0.0
 Total NaN values in row 1098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1099 :- 0 and it's percentage : 0.0
 Total NaN values in row 1100 :- 0 and it's percentage : 0.0
 Total NaN values in row 1101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1102 :- 0 and it's percentage : 0.0
 Total NaN values in row 1103 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1104 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1105 :- 0 and it's percentage : 0.0
 Total NaN values in row 1106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1107 :- 0 and it's percentage : 0.0
 Total NaN values in row 1108 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1109 :- 0 and it's percentage : 0.0
 Total NaN values in row 1110 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1111 :- 0 and it's percentage : 0.0
 Total NaN values in row 1112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1113 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1114 :- 0 and it's percentage : 0.0
 Total NaN values in row 1115 :- 0 and it's percentage : 0.0
 Total NaN values in row 1116 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1117 :- 0 and it's percentage : 0.0
 Total NaN values in row 1118 :- 0 and it's percentage : 0.0

 Total NaN values in row 1119 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1120 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1121 :- 0 and it's percentage : 0.0
 Total NaN values in row 1122 :- 0 and it's percentage : 0.0
 Total NaN values in row 1123 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1124 :- 0 and it's percentage : 0.0
 Total NaN values in row 1125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1126 :- 0 and it's percentage : 0.0
 Total NaN values in row 1127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1128 :- 0 and it's percentage : 0.0
 Total NaN values in row 1129 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1130 :- 0 and it's percentage : 0.0
 Total NaN values in row 1131 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1132 :- 0 and it's percentage : 0.0
 Total NaN values in row 1133 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1134 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1135 :- 0 and it's percentage : 0.0
 Total NaN values in row 1136 :- 0 and it's percentage : 0.0
 Total NaN values in row 1137 :- 0 and it's percentage : 0.0
 Total NaN values in row 1138 :- 0 and it's percentage : 0.0
 Total NaN values in row 1139 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1140 :- 0 and it's percentage : 0.0
 Total NaN values in row 1141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1142 :- 0 and it's percentage : 0.0
 Total NaN values in row 1143 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1144 :- 0 and it's percentage : 0.0
 Total NaN values in row 1145 :- 0 and it's percentage : 0.0
 Total NaN values in row 1146 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1147 :- 0 and it's percentage : 0.0
 Total NaN values in row 1148 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1149 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1150 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1151 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1152 :- 0 and it's percentage : 0.0
 Total NaN values in row 1153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1154 :- 0 and it's percentage : 0.0
 Total NaN values in row 1155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1156 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 1157 :- 0 and it's percentage : 0.0
 Total NaN values in row 1158 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1159 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1160 :- 0 and it's percentage : 0.0
 Total NaN values in row 1161 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1162 :- 0 and it's percentage : 0.0
 Total NaN values in row 1163 :- 0 and it's percentage : 0.0
 Total NaN values in row 1164 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1165 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1166 :- 0 and it's percentage : 0.0
 Total NaN values in row 1167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1168 :- 0 and it's percentage : 0.0
 Total NaN values in row 1169 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1171 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1172 :- 0 and it's percentage : 0.0
 Total NaN values in row 1173 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1174 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1175 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1176 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1178 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1179 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1180 :- 0 and it's percentage : 0.0
 Total NaN values in row 1181 :- 0 and it's percentage : 0.0
 Total NaN values in row 1182 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1184 :- 0 and it's percentage : 0.0
 Total NaN values in row 1185 :- 0 and it's percentage : 0.0
 Total NaN values in row 1186 :- 0 and it's percentage : 0.0
 Total NaN values in row 1187 :- 0 and it's percentage : 0.0
 Total NaN values in row 1188 :- 0 and it's percentage : 0.0
 Total NaN values in row 1189 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1191 :- 0 and it's percentage : 0.0
 Total NaN values in row 1192 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1193 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1194 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1195 :- 0 and it's percentage : 0.0
 Total NaN values in row 1196 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1197 :- 0 and it's percentage : 0.0
 Total NaN values in row 1198 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1199 :- 0 and it's percentage : 0.0
 Total NaN values in row 1200 :- 0 and it's percentage : 0.0
 Total NaN values in row 1201 :- 0 and it's percentage : 0.0
 Total NaN values in row 1202 :- 0 and it's percentage : 0.0
 Total NaN values in row 1203 :- 0 and it's percentage : 0.0
 Total NaN values in row 1204 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1205 :- 0 and it's percentage : 0.0
 Total NaN values in row 1206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1207 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1208 :- 0 and it's percentage : 0.0
 Total NaN values in row 1209 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1210 :- 0 and it's percentage : 0.0
 Total NaN values in row 1211 :- 0 and it's percentage : 0.0
 Total NaN values in row 1212 :- 0 and it's percentage : 0.0
 Total NaN values in row 1213 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1214 :- 0 and it's percentage : 0.0
 Total NaN values in row 1215 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1216 :- 0 and it's percentage : 0.0
 Total NaN values in row 1217 :- 0 and it's percentage : 0.0
 Total NaN values in row 1218 :- 0 and it's percentage : 0.0
 Total NaN values in row 1219 :- 0 and it's percentage : 0.0
 Total NaN values in row 1220 :- 0 and it's percentage : 0.0
 Total NaN values in row 1221 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1222 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1223 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1224 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1225 :- 0 and it's percentage : 0.0
 Total NaN values in row 1226 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1227 :- 0 and it's percentage : 0.0
 Total NaN values in row 1228 :- 0 and it's percentage : 0.0
 Total NaN values in row 1229 :- 0 and it's percentage : 0.0
 Total NaN values in row 1230 :- 0 and it's percentage : 0.0
 Total NaN values in row 1231 :- 0 and it's percentage : 0.0
 Total NaN values in row 1232 :- 0 and it's percentage : 0.0
 Total NaN values in row 1233 :- 0 and it's percentage : 0.0
 Total NaN values in row 1234 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1235 :- 0 and it's percentage : 0.0
 Total NaN values in row 1236 :- 0 and it's percentage : 0.0
 Total NaN values in row 1237 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1238 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1239 :- 0 and it's percentage : 0.0
 Total NaN values in row 1240 :- 0 and it's percentage : 0.0
 Total NaN values in row 1241 :- 0 and it's percentage : 0.0
 Total NaN values in row 1242 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1243 :- 0 and it's percentage : 0.0
 Total NaN values in row 1244 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1245 :- 0 and it's percentage : 0.0
 Total NaN values in row 1246 :- 0 and it's percentage : 0.0
 Total NaN values in row 1247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1248 :- 0 and it's percentage : 0.0
 Total NaN values in row 1249 :- 0 and it's percentage : 0.0
 Total NaN values in row 1250 :- 0 and it's percentage : 0.0
 Total NaN values in row 1251 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1252 :- 0 and it's percentage : 0.0
 Total NaN values in row 1253 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1254 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1255 :- 0 and it's percentage : 0.0
 Total NaN values in row 1256 :- 0 and it's percentage : 0.0
 Total NaN values in row 1257 :- 0 and it's percentage : 0.0
 Total NaN values in row 1258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1259 :- 0 and it's percentage : 0.0
 Total NaN values in row 1260 :- 0 and it's percentage : 0.0
 Total NaN values in row 1261 :- 0 and it's percentage : 0.0
 Total NaN values in row 1262 :- 0 and it's percentage : 0.0
 Total NaN values in row 1263 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 1264 :- 0 and it's percentage : 0.0
 Total NaN values in row 1265 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1266 :- 0 and it's percentage : 0.0
 Total NaN values in row 1267 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1269 :- 0 and it's percentage : 0.0
 Total NaN values in row 1270 :- 0 and it's percentage : 0.0
 Total NaN values in row 1271 :- 0 and it's percentage : 0.0
 Total NaN values in row 1272 :- 0 and it's percentage : 0.0
 Total NaN values in row 1273 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1274 :- 0 and it's percentage : 0.0
 Total NaN values in row 1275 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1276 :- 0 and it's percentage : 0.0
 Total NaN values in row 1277 :- 0 and it's percentage : 0.0
 Total NaN values in row 1278 :- 0 and it's percentage : 0.0
 Total NaN values in row 1279 :- 0 and it's percentage : 0.0
 Total NaN values in row 1280 :- 0 and it's percentage : 0.0
 Total NaN values in row 1281 :- 0 and it's percentage : 0.0
 Total NaN values in row 1282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1283 :- 0 and it's percentage : 0.0
 Total NaN values in row 1284 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1285 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1286 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1287 :- 0 and it's percentage : 0.0
 Total NaN values in row 1288 :- 0 and it's percentage : 0.0
 Total NaN values in row 1289 :- 0 and it's percentage : 0.0
 Total NaN values in row 1290 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1291 :- 0 and it's percentage : 0.0
 Total NaN values in row 1292 :- 0 and it's percentage : 0.0
 Total NaN values in row 1293 :- 0 and it's percentage : 0.0
 Total NaN values in row 1294 :- 0 and it's percentage : 0.0
 Total NaN values in row 1295 :- 0 and it's percentage : 0.0
 Total NaN values in row 1296 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1297 :- 0 and it's percentage : 0.0
 Total NaN values in row 1298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1299 :- 0 and it's percentage : 0.0
 Total NaN values in row 1300 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1301 :- 0 and it's percentage : 0.0
 Total NaN values in row 1302 :- 0 and it's percentage : 0.0
 Total NaN values in row 1303 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1304 :- 0 and it's percentage : 0.0
 Total NaN values in row 1305 :- 0 and it's percentage : 0.0
 Total NaN values in row 1306 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1307 :- 0 and it's percentage : 0.0
 Total NaN values in row 1308 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1309 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1310 :- 0 and it's percentage : 0.0
 Total NaN values in row 1311 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1312 :- 0 and it's percentage : 0.0
 Total NaN values in row 1313 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1314 :- 0 and it's percentage : 0.0
 Total NaN values in row 1315 :- 0 and it's percentage : 0.0
 Total NaN values in row 1316 :- 0 and it's percentage : 0.0
 Total NaN values in row 1317 :- 0 and it's percentage : 0.0
 Total NaN values in row 1318 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1319 :- 0 and it's percentage : 0.0
 Total NaN values in row 1320 :- 0 and it's percentage : 0.0
 Total NaN values in row 1321 :- 0 and it's percentage : 0.0
 Total NaN values in row 1322 :- 0 and it's percentage : 0.0
 Total NaN values in row 1323 :- 0 and it's percentage : 0.0
 Total NaN values in row 1324 :- 0 and it's percentage : 0.0
 Total NaN values in row 1325 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1326 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1327 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1328 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1329 :- 0 and it's percentage : 0.0
 Total NaN values in row 1330 :- 0 and it's percentage : 0.0
 Total NaN values in row 1331 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1332 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1334 :- 0 and it's percentage : 0.0
 Total NaN values in row 1335 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1336 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1337 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1338 :- 0 and it's percentage : 0.0
 Total NaN values in row 1339 :- 0 and it's percentage : 0.0
 Total NaN values in row 1340 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1341 :- 0 and it's percentage : 0.0
 Total NaN values in row 1342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1343 :- 0 and it's percentage : 0.0
 Total NaN values in row 1344 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1345 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1346 :- 0 and it's percentage : 0.0
 Total NaN values in row 1347 :- 0 and it's percentage : 0.0
 Total NaN values in row 1348 :- 0 and it's percentage : 0.0
 Total NaN values in row 1349 :- 0 and it's percentage : 0.0
 Total NaN values in row 1350 :- 0 and it's percentage : 0.0
 Total NaN values in row 1351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1352 :- 0 and it's percentage : 0.0
 Total NaN values in row 1353 :- 0 and it's percentage : 0.0
 Total NaN values in row 1354 :- 0 and it's percentage : 0.0
 Total NaN values in row 1355 :- 0 and it's percentage : 0.0
 Total NaN values in row 1356 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1357 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1358 :- 0 and it's percentage : 0.0
 Total NaN values in row 1359 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1360 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1361 :- 0 and it's percentage : 0.0
 Total NaN values in row 1362 :- 0 and it's percentage : 0.0
 Total NaN values in row 1363 :- 0 and it's percentage : 0.0
 Total NaN values in row 1364 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1365 :- 0 and it's percentage : 0.0
 Total NaN values in row 1366 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1367 :- 0 and it's percentage : 0.0
 Total NaN values in row 1368 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1369 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1370 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1371 :- 0 and it's percentage : 0.0
 Total NaN values in row 1372 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1373 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1376 :- 0 and it's percentage : 0.0
 Total NaN values in row 1377 :- 0 and it's percentage : 0.0
 Total NaN values in row 1378 :- 0 and it's percentage : 0.0
 Total NaN values in row 1379 :- 0 and it's percentage : 0.0
 Total NaN values in row 1380 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1381 :- 0 and it's percentage : 0.0
 Total NaN values in row 1382 :- 0 and it's percentage : 0.0
 Total NaN values in row 1383 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1384 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1385 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1386 :- 0 and it's percentage : 0.0
 Total NaN values in row 1387 :- 0 and it's percentage : 0.0
 Total NaN values in row 1388 :- 0 and it's percentage : 0.0
 Total NaN values in row 1389 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 1390 :- 0 and it's percentage : 0.0
 Total NaN values in row 1391 :- 0 and it's percentage : 0.0
 Total NaN values in row 1392 :- 0 and it's percentage : 0.0
 Total NaN values in row 1393 :- 0 and it's percentage : 0.0
 Total NaN values in row 1394 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1395 :- 0 and it's percentage : 0.0
 Total NaN values in row 1396 :- 0 and it's percentage : 0.0
 Total NaN values in row 1397 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1398 :- 0 and it's percentage : 0.0
 Total NaN values in row 1399 :- 0 and it's percentage : 0.0
 Total NaN values in row 1400 :- 0 and it's percentage : 0.0
 Total NaN values in row 1401 :- 0 and it's percentage : 0.0
 Total NaN values in row 1402 :- 0 and it's percentage : 0.0
 Total NaN values in row 1403 :- 0 and it's percentage : 0.0
 Total NaN values in row 1404 :- 0 and it's percentage : 0.0
 Total NaN values in row 1405 :- 0 and it's percentage : 0.0
 Total NaN values in row 1406 :- 0 and it's percentage : 0.0
 Total NaN values in row 1407 :- 0 and it's percentage : 0.0
 Total NaN values in row 1408 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1409 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1410 :- 0 and it's percentage : 0.0
 Total NaN values in row 1411 :- 0 and it's percentage : 0.0
 Total NaN values in row 1412 :- 0 and it's percentage : 0.0
 Total NaN values in row 1413 :- 0 and it's percentage : 0.0
 Total NaN values in row 1414 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1417 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1418 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1419 :- 0 and it's percentage : 0.0
 Total NaN values in row 1420 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1421 :- 0 and it's percentage : 0.0
 Total NaN values in row 1422 :- 0 and it's percentage : 0.0
 Total NaN values in row 1423 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1424 :- 0 and it's percentage : 0.0
 Total NaN values in row 1425 :- 0 and it's percentage : 0.0
 Total NaN values in row 1426 :- 0 and it's percentage : 0.0
 Total NaN values in row 1427 :- 0 and it's percentage : 0.0
 Total NaN values in row 1428 :- 0 and it's percentage : 0.0
 Total NaN values in row 1429 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1430 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1431 :- 0 and it's percentage : 0.0
 Total NaN values in row 1432 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1434 :- 0 and it's percentage : 0.0
 Total NaN values in row 1435 :- 0 and it's percentage : 0.0
 Total NaN values in row 1436 :- 0 and it's percentage : 0.0
 Total NaN values in row 1437 :- 0 and it's percentage : 0.0
 Total NaN values in row 1438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1439 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1440 :- 0 and it's percentage : 0.0
 Total NaN values in row 1441 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1442 :- 0 and it's percentage : 0.0
 Total NaN values in row 1443 :- 0 and it's percentage : 0.0
 Total NaN values in row 1444 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1445 :- 0 and it's percentage : 0.0
 Total NaN values in row 1446 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1447 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1448 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1449 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1450 :- 0 and it's percentage : 0.0
 Total NaN values in row 1451 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1452 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 1453 :- 0 and it's percentage : 0.0
 Total NaN values in row 1454 :- 0 and it's percentage : 0.0
 Total NaN values in row 1455 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1456 :- 0 and it's percentage : 0.0
 Total NaN values in row 1457 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1458 :- 0 and it's percentage : 0.0
 Total NaN values in row 1459 :- 0 and it's percentage : 0.0
 Total NaN values in row 1460 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1461 :- 0 and it's percentage : 0.0
 Total NaN values in row 1462 :- 0 and it's percentage : 0.0
 Total NaN values in row 1463 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1464 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1465 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1466 :- 0 and it's percentage : 0.0
 Total NaN values in row 1467 :- 0 and it's percentage : 0.0
 Total NaN values in row 1468 :- 0 and it's percentage : 0.0
 Total NaN values in row 1469 :- 0 and it's percentage : 0.0
 Total NaN values in row 1470 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1471 :- 0 and it's percentage : 0.0
 Total NaN values in row 1472 :- 0 and it's percentage : 0.0
 Total NaN values in row 1473 :- 0 and it's percentage : 0.0
 Total NaN values in row 1474 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1475 :- 0 and it's percentage : 0.0
 Total NaN values in row 1476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1477 :- 0 and it's percentage : 0.0
 Total NaN values in row 1478 :- 0 and it's percentage : 0.0
 Total NaN values in row 1479 :- 0 and it's percentage : 0.0
 Total NaN values in row 1480 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1481 :- 0 and it's percentage : 0.0
 Total NaN values in row 1482 :- 0 and it's percentage : 0.0
 Total NaN values in row 1483 :- 0 and it's percentage : 0.0
 Total NaN values in row 1484 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1485 :- 0 and it's percentage : 0.0
 Total NaN values in row 1486 :- 0 and it's percentage : 0.0
 Total NaN values in row 1487 :- 0 and it's percentage : 0.0
 Total NaN values in row 1488 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1489 :- 0 and it's percentage : 0.0
 Total NaN values in row 1490 :- 0 and it's percentage : 0.0
 Total NaN values in row 1491 :- 0 and it's percentage : 0.0
 Total NaN values in row 1492 :- 0 and it's percentage : 0.0
 Total NaN values in row 1493 :- 0 and it's percentage : 0.0
 Total NaN values in row 1494 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1495 :- 0 and it's percentage : 0.0
 Total NaN values in row 1496 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1497 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1498 :- 0 and it's percentage : 0.0
 Total NaN values in row 1499 :- 0 and it's percentage : 0.0
 Total NaN values in row 1500 :- 0 and it's percentage : 0.0
 Total NaN values in row 1501 :- 0 and it's percentage : 0.0
 Total NaN values in row 1502 :- 0 and it's percentage : 0.0
 Total NaN values in row 1503 :- 0 and it's percentage : 0.0
 Total NaN values in row 1504 :- 0 and it's percentage : 0.0
 Total NaN values in row 1505 :- 0 and it's percentage : 0.0
 Total NaN values in row 1506 :- 0 and it's percentage : 0.0
 Total NaN values in row 1507 :- 0 and it's percentage : 0.0
 Total NaN values in row 1508 :- 0 and it's percentage : 0.0
 Total NaN values in row 1509 :- 0 and it's percentage : 0.0
 Total NaN values in row 1510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1511 :- 0 and it's percentage : 0.0
 Total NaN values in row 1512 :- 0 and it's percentage : 0.0
 Total NaN values in row 1513 :- 0 and it's percentage : 0.0
 Total NaN values in row 1514 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1515 :- 0 and it's percentage : 0.0
 Total NaN values in row 1516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1517 :- 0 and it's percentage : 0.0
 Total NaN values in row 1518 :- 0 and it's percentage : 0.0
 Total NaN values in row 1519 :- 0 and it's percentage : 0.0
 Total NaN values in row 1520 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1521 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1522 :- 0 and it's percentage : 0.0

 Total NaN values in row 1523 :- 0 and it's percentage : 0.0
 Total NaN values in row 1524 :- 0 and it's percentage : 0.0
 Total NaN values in row 1525 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1527 :- 0 and it's percentage : 0.0
 Total NaN values in row 1528 :- 0 and it's percentage : 0.0
 Total NaN values in row 1529 :- 0 and it's percentage : 0.0
 Total NaN values in row 1530 :- 0 and it's percentage : 0.0
 Total NaN values in row 1531 :- 0 and it's percentage : 0.0
 Total NaN values in row 1532 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1533 :- 0 and it's percentage : 0.0
 Total NaN values in row 1534 :- 0 and it's percentage : 0.0
 Total NaN values in row 1535 :- 0 and it's percentage : 0.0
 Total NaN values in row 1536 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1537 :- 0 and it's percentage : 0.0
 Total NaN values in row 1538 :- 0 and it's percentage : 0.0
 Total NaN values in row 1539 :- 0 and it's percentage : 0.0
 Total NaN values in row 1540 :- 0 and it's percentage : 0.0
 Total NaN values in row 1541 :- 0 and it's percentage : 0.0
 Total NaN values in row 1542 :- 0 and it's percentage : 0.0
 Total NaN values in row 1543 :- 0 and it's percentage : 0.0
 Total NaN values in row 1544 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1545 :- 0 and it's percentage : 0.0
 Total NaN values in row 1546 :- 0 and it's percentage : 0.0
 Total NaN values in row 1547 :- 0 and it's percentage : 0.0
 Total NaN values in row 1548 :- 0 and it's percentage : 0.0
 Total NaN values in row 1549 :- 0 and it's percentage : 0.0
 Total NaN values in row 1550 :- 0 and it's percentage : 0.0
 Total NaN values in row 1551 :- 0 and it's percentage : 0.0
 Total NaN values in row 1552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1553 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1554 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1555 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1556 :- 0 and it's percentage : 0.0
 Total NaN values in row 1557 :- 0 and it's percentage : 0.0
 Total NaN values in row 1558 :- 0 and it's percentage : 0.0
 Total NaN values in row 1559 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1560 :- 0 and it's percentage : 0.0
 Total NaN values in row 1561 :- 0 and it's percentage : 0.0
 Total NaN values in row 1562 :- 0 and it's percentage : 0.0
 Total NaN values in row 1563 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1564 :- 0 and it's percentage : 0.0
 Total NaN values in row 1565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1566 :- 0 and it's percentage : 0.0
 Total NaN values in row 1567 :- 0 and it's percentage : 0.0
 Total NaN values in row 1568 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1569 :- 0 and it's percentage : 0.0
 Total NaN values in row 1570 :- 0 and it's percentage : 0.0
 Total NaN values in row 1571 :- 0 and it's percentage : 0.0
 Total NaN values in row 1572 :- 0 and it's percentage : 0.0
 Total NaN values in row 1573 :- 0 and it's percentage : 0.0
 Total NaN values in row 1574 :- 0 and it's percentage : 0.0
 Total NaN values in row 1575 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1576 :- 0 and it's percentage : 0.0
 Total NaN values in row 1577 :- 0 and it's percentage : 0.0
 Total NaN values in row 1578 :- 0 and it's percentage : 0.0
 Total NaN values in row 1579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1580 :- 0 and it's percentage : 0.0
 Total NaN values in row 1581 :- 0 and it's percentage : 0.0
 Total NaN values in row 1582 :- 0 and it's percentage : 0.0
 Total NaN values in row 1583 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1584 :- 0 and it's percentage : 0.0
 Total NaN values in row 1585 :- 0 and it's percentage : 0.0
 Total NaN values in row 1586 :- 0 and it's percentage : 0.0
 Total NaN values in row 1587 :- 0 and it's percentage : 0.0
 Total NaN values in row 1588 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1589 :- 0 and it's percentage : 0.0
 Total NaN values in row 1590 :- 0 and it's percentage : 0.0
 Total NaN values in row 1591 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1592 :- 0 and it's percentage : 0.0
 Total NaN values in row 1593 :- 0 and it's percentage : 0.0
 Total NaN values in row 1594 :- 0 and it's percentage : 0.0
 Total NaN values in row 1595 :- 0 and it's percentage : 0.0
 Total NaN values in row 1596 :- 0 and it's percentage : 0.0
 Total NaN values in row 1597 :- 0 and it's percentage : 0.0
 Total NaN values in row 1598 :- 0 and it's percentage : 0.0
 Total NaN values in row 1599 :- 0 and it's percentage : 0.0
 Total NaN values in row 1600 :- 0 and it's percentage : 0.0
 Total NaN values in row 1601 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1602 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1603 :- 0 and it's percentage : 0.0
 Total NaN values in row 1604 :- 0 and it's percentage : 0.0
 Total NaN values in row 1605 :- 0 and it's percentage : 0.0
 Total NaN values in row 1606 :- 0 and it's percentage : 0.0
 Total NaN values in row 1607 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1608 :- 0 and it's percentage : 0.0
 Total NaN values in row 1609 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1610 :- 0 and it's percentage : 0.0
 Total NaN values in row 1611 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1612 :- 0 and it's percentage : 0.0
 Total NaN values in row 1613 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1614 :- 0 and it's percentage : 0.0
 Total NaN values in row 1615 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1616 :- 0 and it's percentage : 0.0
 Total NaN values in row 1617 :- 0 and it's percentage : 0.0
 Total NaN values in row 1618 :- 0 and it's percentage : 0.0
 Total NaN values in row 1619 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1620 :- 0 and it's percentage : 0.0
 Total NaN values in row 1621 :- 0 and it's percentage : 0.0
 Total NaN values in row 1622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1623 :- 0 and it's percentage : 0.0
 Total NaN values in row 1624 :- 0 and it's percentage : 0.0
 Total NaN values in row 1625 :- 0 and it's percentage : 0.0
 Total NaN values in row 1626 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1627 :- 0 and it's percentage : 0.0
 Total NaN values in row 1628 :- 0 and it's percentage : 0.0
 Total NaN values in row 1629 :- 0 and it's percentage : 0.0
 Total NaN values in row 1630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1631 :- 0 and it's percentage : 0.0
 Total NaN values in row 1632 :- 0 and it's percentage : 0.0
 Total NaN values in row 1633 :- 0 and it's percentage : 0.0
 Total NaN values in row 1634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1635 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1636 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1638 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1639 :- 0 and it's percentage : 0.0
 Total NaN values in row 1640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1642 :- 0 and it's percentage : 0.0
 Total NaN values in row 1643 :- 0 and it's percentage : 0.0
 Total NaN values in row 1644 :- 0 and it's percentage : 0.0
 Total NaN values in row 1645 :- 0 and it's percentage : 0.0
 Total NaN values in row 1646 :- 0 and it's percentage : 0.0
 Total NaN values in row 1647 :- 0 and it's percentage : 0.0
 Total NaN values in row 1648 :- 0 and it's percentage : 0.0
 Total NaN values in row 1649 :- 0 and it's percentage : 0.0
 Total NaN values in row 1650 :- 0 and it's percentage : 0.0
 Total NaN values in row 1651 :- 0 and it's percentage : 0.0
 Total NaN values in row 1652 :- 0 and it's percentage : 0.0
 Total NaN values in row 1653 :- 0 and it's percentage : 0.0
 Total NaN values in row 1654 :- 0 and it's percentage : 0.0
 Total NaN values in row 1655 :- 0 and it's percentage : 0.0
 Total NaN values in row 1656 :- 0 and it's percentage : 0.0
 Total NaN values in row 1657 :- 0 and it's percentage : 0.0
 Total NaN values in row 1658 :- 0 and it's percentage : 0.0

 Total NaN values in row 1659 :- 0 and it's percentage : 0.0
 Total NaN values in row 1660 :- 0 and it's percentage : 0.0
 Total NaN values in row 1661 :- 0 and it's percentage : 0.0
 Total NaN values in row 1662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1663 :- 0 and it's percentage : 0.0
 Total NaN values in row 1664 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1665 :- 0 and it's percentage : 0.0
 Total NaN values in row 1666 :- 0 and it's percentage : 0.0
 Total NaN values in row 1667 :- 0 and it's percentage : 0.0
 Total NaN values in row 1668 :- 0 and it's percentage : 0.0
 Total NaN values in row 1669 :- 0 and it's percentage : 0.0
 Total NaN values in row 1670 :- 0 and it's percentage : 0.0
 Total NaN values in row 1671 :- 0 and it's percentage : 0.0
 Total NaN values in row 1672 :- 0 and it's percentage : 0.0
 Total NaN values in row 1673 :- 0 and it's percentage : 0.0
 Total NaN values in row 1674 :- 0 and it's percentage : 0.0
 Total NaN values in row 1675 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1676 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1677 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1678 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1679 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1680 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 1681 :- 0 and it's percentage : 0.0
 Total NaN values in row 1682 :- 0 and it's percentage : 0.0
 Total NaN values in row 1683 :- 0 and it's percentage : 0.0
 Total NaN values in row 1684 :- 0 and it's percentage : 0.0
 Total NaN values in row 1685 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1686 :- 0 and it's percentage : 0.0
 Total NaN values in row 1687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1689 :- 0 and it's percentage : 0.0
 Total NaN values in row 1690 :- 0 and it's percentage : 0.0
 Total NaN values in row 1691 :- 0 and it's percentage : 0.0
 Total NaN values in row 1692 :- 0 and it's percentage : 0.0
 Total NaN values in row 1693 :- 0 and it's percentage : 0.0
 Total NaN values in row 1694 :- 0 and it's percentage : 0.0
 Total NaN values in row 1695 :- 0 and it's percentage : 0.0
 Total NaN values in row 1696 :- 0 and it's percentage : 0.0
 Total NaN values in row 1697 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1698 :- 0 and it's percentage : 0.0
 Total NaN values in row 1699 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1701 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1702 :- 0 and it's percentage : 0.0
 Total NaN values in row 1703 :- 0 and it's percentage : 0.0
 Total NaN values in row 1704 :- 0 and it's percentage : 0.0
 Total NaN values in row 1705 :- 0 and it's percentage : 0.0
 Total NaN values in row 1706 :- 0 and it's percentage : 0.0
 Total NaN values in row 1707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1708 :- 0 and it's percentage : 0.0
 Total NaN values in row 1709 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1710 :- 0 and it's percentage : 0.0
 Total NaN values in row 1711 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1714 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1715 :- 0 and it's percentage : 0.0
 Total NaN values in row 1716 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1717 :- 0 and it's percentage : 0.0
 Total NaN values in row 1718 :- 0 and it's percentage : 0.0
 Total NaN values in row 1719 :- 0 and it's percentage : 0.0
 Total NaN values in row 1720 :- 0 and it's percentage : 0.0
 Total NaN values in row 1721 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1722 :- 0 and it's percentage : 0.0
 Total NaN values in row 1723 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1724 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1725 :- 0 and it's percentage : 0.0
 Total NaN values in row 1726 :- 0 and it's percentage : 0.0
 Total NaN values in row 1727 :- 0 and it's percentage : 0.0
 Total NaN values in row 1728 :- 0 and it's percentage : 0.0
 Total NaN values in row 1729 :- 0 and it's percentage : 0.0
 Total NaN values in row 1730 :- 0 and it's percentage : 0.0
 Total NaN values in row 1731 :- 0 and it's percentage : 0.0
 Total NaN values in row 1732 :- 0 and it's percentage : 0.0
 Total NaN values in row 1733 :- 0 and it's percentage : 0.0
 Total NaN values in row 1734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1735 :- 0 and it's percentage : 0.0
 Total NaN values in row 1736 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1737 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1738 :- 0 and it's percentage : 0.0
 Total NaN values in row 1739 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1740 :- 0 and it's percentage : 0.0
 Total NaN values in row 1741 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1743 :- 0 and it's percentage : 0.0
 Total NaN values in row 1744 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1745 :- 0 and it's percentage : 0.0
 Total NaN values in row 1746 :- 0 and it's percentage : 0.0
 Total NaN values in row 1747 :- 0 and it's percentage : 0.0
 Total NaN values in row 1748 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1749 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1750 :- 0 and it's percentage : 0.0
 Total NaN values in row 1751 :- 0 and it's percentage : 0.0
 Total NaN values in row 1752 :- 0 and it's percentage : 0.0
 Total NaN values in row 1753 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1754 :- 0 and it's percentage : 0.0
 Total NaN values in row 1755 :- 0 and it's percentage : 0.0
 Total NaN values in row 1756 :- 0 and it's percentage : 0.0
 Total NaN values in row 1757 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1758 :- 0 and it's percentage : 0.0
 Total NaN values in row 1759 :- 0 and it's percentage : 0.0
 Total NaN values in row 1760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1761 :- 0 and it's percentage : 0.0
 Total NaN values in row 1762 :- 0 and it's percentage : 0.0
 Total NaN values in row 1763 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1764 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1765 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1766 :- 0 and it's percentage : 0.0
 Total NaN values in row 1767 :- 0 and it's percentage : 0.0
 Total NaN values in row 1768 :- 0 and it's percentage : 0.0
 Total NaN values in row 1769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1770 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1771 :- 0 and it's percentage : 0.0
 Total NaN values in row 1772 :- 0 and it's percentage : 0.0
 Total NaN values in row 1773 :- 0 and it's percentage : 0.0
 Total NaN values in row 1774 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1775 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1776 :- 0 and it's percentage : 0.0
 Total NaN values in row 1777 :- 0 and it's percentage : 0.0
 Total NaN values in row 1778 :- 0 and it's percentage : 0.0
 Total NaN values in row 1779 :- 0 and it's percentage : 0.0
 Total NaN values in row 1780 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1782 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1783 :- 0 and it's percentage : 0.0
 Total NaN values in row 1784 :- 0 and it's percentage : 0.0
 Total NaN values in row 1785 :- 0 and it's percentage : 0.0
 Total NaN values in row 1786 :- 0 and it's percentage : 0.0
 Total NaN values in row 1787 :- 0 and it's percentage : 0.0
 Total NaN values in row 1788 :- 0 and it's percentage : 0.0
 Total NaN values in row 1789 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1790 :- 0 and it's percentage : 0.0
 Total NaN values in row 1791 :- 0 and it's percentage : 0.0
 Total NaN values in row 1792 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1793 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1794 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1796 :- 0 and it's percentage : 0.0
 Total NaN values in row 1797 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1798 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1799 :- 0 and it's percentage : 0.0
 Total NaN values in row 1800 :- 0 and it's percentage : 0.0
 Total NaN values in row 1801 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1802 :- 0 and it's percentage : 0.0
 Total NaN values in row 1803 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1804 :- 0 and it's percentage : 0.0
 Total NaN values in row 1805 :- 0 and it's percentage : 0.0
 Total NaN values in row 1806 :- 0 and it's percentage : 0.0
 Total NaN values in row 1807 :- 0 and it's percentage : 0.0

 Total NaN values in row 1808 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1809 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1810 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1811 :- 0 and it's percentage : 0.0
 Total NaN values in row 1812 :- 0 and it's percentage : 0.0
 Total NaN values in row 1813 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1814 :- 0 and it's percentage : 0.0
 Total NaN values in row 1815 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1816 :- 0 and it's percentage : 0.0
 Total NaN values in row 1817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1818 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1819 :- 0 and it's percentage : 0.0
 Total NaN values in row 1820 :- 0 and it's percentage : 0.0
 Total NaN values in row 1821 :- 0 and it's percentage : 0.0
 Total NaN values in row 1822 :- 0 and it's percentage : 0.0
 Total NaN values in row 1823 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1824 :- 0 and it's percentage : 0.0
 Total NaN values in row 1825 :- 0 and it's percentage : 0.0
 Total NaN values in row 1826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1827 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1828 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1829 :- 0 and it's percentage : 0.0
 Total NaN values in row 1830 :- 0 and it's percentage : 0.0
 Total NaN values in row 1831 :- 0 and it's percentage : 0.0
 Total NaN values in row 1832 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1833 :- 0 and it's percentage : 0.0
 Total NaN values in row 1834 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1835 :- 0 and it's percentage : 0.0
 Total NaN values in row 1836 :- 0 and it's percentage : 0.0
 Total NaN values in row 1837 :- 0 and it's percentage : 0.0
 Total NaN values in row 1838 :- 0 and it's percentage : 0.0
 Total NaN values in row 1839 :- 0 and it's percentage : 0.0
 Total NaN values in row 1840 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1841 :- 0 and it's percentage : 0.0
 Total NaN values in row 1842 :- 0 and it's percentage : 0.0
 Total NaN values in row 1843 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1844 :- 0 and it's percentage : 0.0
 Total NaN values in row 1845 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1846 :- 0 and it's percentage : 0.0
 Total NaN values in row 1847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1848 :- 0 and it's percentage : 0.0
 Total NaN values in row 1849 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1850 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1851 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1852 :- 0 and it's percentage : 0.0
 Total NaN values in row 1853 :- 0 and it's percentage : 0.0
 Total NaN values in row 1854 :- 0 and it's percentage : 0.0
 Total NaN values in row 1855 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1856 :- 0 and it's percentage : 0.0
 Total NaN values in row 1857 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1858 :- 0 and it's percentage : 0.0
 Total NaN values in row 1859 :- 0 and it's percentage : 0.0
 Total NaN values in row 1860 :- 0 and it's percentage : 0.0
 Total NaN values in row 1861 :- 0 and it's percentage : 0.0
 Total NaN values in row 1862 :- 0 and it's percentage : 0.0
 Total NaN values in row 1863 :- 0 and it's percentage : 0.0
 Total NaN values in row 1864 :- 0 and it's percentage : 0.0
 Total NaN values in row 1865 :- 0 and it's percentage : 0.0
 Total NaN values in row 1866 :- 0 and it's percentage : 0.0
 Total NaN values in row 1867 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1868 :- 0 and it's percentage : 0.0
 Total NaN values in row 1869 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1870 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1872 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1873 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 1874 :- 0 and it's percentage : 0.0
 Total NaN values in row 1875 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1876 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1877 :- 0 and it's percentage : 0.0
 Total NaN values in row 1878 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1879 :- 0 and it's percentage : 0.0
 Total NaN values in row 1880 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1881 :- 0 and it's percentage : 0.0
 Total NaN values in row 1882 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1883 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1884 :- 0 and it's percentage : 0.0
 Total NaN values in row 1885 :- 0 and it's percentage : 0.0
 Total NaN values in row 1886 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1887 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1888 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1889 :- 0 and it's percentage : 0.0
 Total NaN values in row 1890 :- 0 and it's percentage : 0.0
 Total NaN values in row 1891 :- 0 and it's percentage : 0.0
 Total NaN values in row 1892 :- 0 and it's percentage : 0.0
 Total NaN values in row 1893 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1894 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1895 :- 0 and it's percentage : 0.0
 Total NaN values in row 1896 :- 0 and it's percentage : 0.0
 Total NaN values in row 1897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1898 :- 0 and it's percentage : 0.0
 Total NaN values in row 1899 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1900 :- 0 and it's percentage : 0.0
 Total NaN values in row 1901 :- 0 and it's percentage : 0.0
 Total NaN values in row 1902 :- 0 and it's percentage : 0.0
 Total NaN values in row 1903 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1904 :- 0 and it's percentage : 0.0
 Total NaN values in row 1905 :- 0 and it's percentage : 0.0
 Total NaN values in row 1906 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1907 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1908 :- 0 and it's percentage : 0.0
 Total NaN values in row 1909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1910 :- 0 and it's percentage : 0.0
 Total NaN values in row 1911 :- 0 and it's percentage : 0.0
 Total NaN values in row 1912 :- 0 and it's percentage : 0.0
 Total NaN values in row 1913 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1914 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1915 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1916 :- 0 and it's percentage : 0.0
 Total NaN values in row 1917 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1918 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1919 :- 0 and it's percentage : 0.0
 Total NaN values in row 1920 :- 0 and it's percentage : 0.0
 Total NaN values in row 1921 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1922 :- 0 and it's percentage : 0.0
 Total NaN values in row 1923 :- 0 and it's percentage : 0.0
 Total NaN values in row 1924 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1925 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1926 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1927 :- 0 and it's percentage : 0.0
 Total NaN values in row 1928 :- 0 and it's percentage : 0.0
 Total NaN values in row 1929 :- 0 and it's percentage : 0.0
 Total NaN values in row 1930 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1931 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1932 :- 0 and it's percentage : 0.0
 Total NaN values in row 1933 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 1934 :- 0 and it's percentage : 0.0
 Total NaN values in row 1935 :- 0 and it's percentage : 0.0
 Total NaN values in row 1936 :- 0 and it's percentage : 0.0
 Total NaN values in row 1937 :- 0 and it's percentage : 0.0
 Total NaN values in row 1938 :- 0 and it's percentage : 0.0
 Total NaN values in row 1939 :- 0 and it's percentage : 0.0
 Total NaN values in row 1940 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1941 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1942 :- 0 and it's percentage : 0.0
 Total NaN values in row 1943 :- 0 and it's percentage : 0.0
 Total NaN values in row 1944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1945 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1946 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1947 :- 0 and it's percentage : 0.0
 Total NaN values in row 1948 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1949 :- 0 and it's percentage : 0.0
 Total NaN values in row 1950 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1951 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1952 :- 0 and it's percentage : 0.0
 Total NaN values in row 1953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1955 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1956 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1957 :- 0 and it's percentage : 0.0
 Total NaN values in row 1958 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1959 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1960 :- 0 and it's percentage : 0.0
 Total NaN values in row 1961 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1962 :- 0 and it's percentage : 0.0
 Total NaN values in row 1963 :- 0 and it's percentage : 0.0
 Total NaN values in row 1964 :- 0 and it's percentage : 0.0
 Total NaN values in row 1965 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1966 :- 0 and it's percentage : 0.0
 Total NaN values in row 1967 :- 0 and it's percentage : 0.0
 Total NaN values in row 1968 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1969 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1970 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1971 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1972 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1974 :- 0 and it's percentage : 0.0

 Total NaN values in row 1975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1976 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1977 :- 0 and it's percentage : 0.0
 Total NaN values in row 1978 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1979 :- 0 and it's percentage : 0.0
 Total NaN values in row 1980 :- 0 and it's percentage : 0.0
 Total NaN values in row 1981 :- 0 and it's percentage : 0.0
 Total NaN values in row 1982 :- 0 and it's percentage : 0.0
 Total NaN values in row 1983 :- 0 and it's percentage : 0.0
 Total NaN values in row 1984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1985 :- 0 and it's percentage : 0.0
 Total NaN values in row 1986 :- 0 and it's percentage : 0.0
 Total NaN values in row 1987 :- 0 and it's percentage : 0.0
 Total NaN values in row 1988 :- 0 and it's percentage : 0.0
 Total NaN values in row 1989 :- 0 and it's percentage : 0.0
 Total NaN values in row 1990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1991 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 1992 :- 0 and it's percentage : 0.0
 Total NaN values in row 1993 :- 0 and it's percentage : 0.0
 Total NaN values in row 1994 :- 0 and it's percentage : 0.0
 Total NaN values in row 1995 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1996 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 1997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 1998 :- 0 and it's percentage : 0.0
 Total NaN values in row 1999 :- 0 and it's percentage : 0.0
 Total NaN values in row 2000 :- 0 and it's percentage : 0.0
 Total NaN values in row 2001 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2003 :- 0 and it's percentage : 0.0
 Total NaN values in row 2004 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2005 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2006 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2007 :- 0 and it's percentage : 0.0
 Total NaN values in row 2008 :- 0 and it's percentage : 0.0
 Total NaN values in row 2009 :- 0 and it's percentage : 0.0
 Total NaN values in row 2010 :- 0 and it's percentage : 0.0
 Total NaN values in row 2011 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2012 :- 0 and it's percentage : 0.0
 Total NaN values in row 2013 :- 0 and it's percentage : 0.0
 Total NaN values in row 2014 :- 0 and it's percentage : 0.0
 Total NaN values in row 2015 :- 0 and it's percentage : 0.0
 Total NaN values in row 2016 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2017 :- 0 and it's percentage : 0.0
 Total NaN values in row 2018 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2019 :- 0 and it's percentage : 0.0
 Total NaN values in row 2020 :- 0 and it's percentage : 0.0
 Total NaN values in row 2021 :- 0 and it's percentage : 0.0
 Total NaN values in row 2022 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2023 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2024 :- 0 and it's percentage : 0.0
 Total NaN values in row 2025 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2026 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2028 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2029 :- 0 and it's percentage : 0.0
 Total NaN values in row 2030 :- 0 and it's percentage : 0.0
 Total NaN values in row 2031 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2032 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2033 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2034 :- 0 and it's percentage : 0.0
 Total NaN values in row 2035 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2036 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2037 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2038 :- 0 and it's percentage : 0.0
 Total NaN values in row 2039 :- 0 and it's percentage : 0.0
 Total NaN values in row 2040 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2042 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2043 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2044 :- 0 and it's percentage : 0.0
 Total NaN values in row 2045 :- 0 and it's percentage : 0.0
 Total NaN values in row 2046 :- 0 and it's percentage : 0.0
 Total NaN values in row 2047 :- 0 and it's percentage : 0.0
 Total NaN values in row 2048 :- 0 and it's percentage : 0.0
 Total NaN values in row 2049 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2050 :- 0 and it's percentage : 0.0
 Total NaN values in row 2051 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2052 :- 0 and it's percentage : 0.0
 Total NaN values in row 2053 :- 0 and it's percentage : 0.0
 Total NaN values in row 2054 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2055 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2056 :- 0 and it's percentage : 0.0
 Total NaN values in row 2057 :- 0 and it's percentage : 0.0
 Total NaN values in row 2058 :- 0 and it's percentage : 0.0
 Total NaN values in row 2059 :- 0 and it's percentage : 0.0
 Total NaN values in row 2060 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2061 :- 0 and it's percentage : 0.0
 Total NaN values in row 2062 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2063 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2064 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2065 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2066 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2067 :- 0 and it's percentage : 0.0
 Total NaN values in row 2068 :- 0 and it's percentage : 0.0
 Total NaN values in row 2069 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2070 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2071 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2072 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2073 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2074 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2076 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2077 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2078 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2079 :- 0 and it's percentage : 0.0
 Total NaN values in row 2080 :- 0 and it's percentage : 0.0
 Total NaN values in row 2081 :- 0 and it's percentage : 0.0
 Total NaN values in row 2082 :- 0 and it's percentage : 0.0
 Total NaN values in row 2083 :- 0 and it's percentage : 0.0
 Total NaN values in row 2084 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2085 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2086 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2087 :- 0 and it's percentage : 0.0
 Total NaN values in row 2088 :- 0 and it's percentage : 0.0
 Total NaN values in row 2089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2090 :- 0 and it's percentage : 0.0
 Total NaN values in row 2091 :- 0 and it's percentage : 0.0
 Total NaN values in row 2092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2093 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2095 :- 0 and it's percentage : 0.0
 Total NaN values in row 2096 :- 0 and it's percentage : 0.0
 Total NaN values in row 2097 :- 0 and it's percentage : 0.0
 Total NaN values in row 2098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2099 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2100 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 2101 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2102 :- 0 and it's percentage : 0.0
 Total NaN values in row 2103 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2104 :- 0 and it's percentage : 0.0
 Total NaN values in row 2105 :- 0 and it's percentage : 0.0
 Total NaN values in row 2106 :- 0 and it's percentage : 0.0
 Total NaN values in row 2107 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2108 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2109 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2110 :- 0 and it's percentage : 0.0
 Total NaN values in row 2111 :- 0 and it's percentage : 0.0
 Total NaN values in row 2112 :- 0 and it's percentage : 0.0
 Total NaN values in row 2113 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2114 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2115 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2116 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2117 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2118 :- 0 and it's percentage : 0.0
 Total NaN values in row 2119 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2120 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2121 :- 0 and it's percentage : 0.0
 Total NaN values in row 2122 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2123 :- 0 and it's percentage : 0.0
 Total NaN values in row 2124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2125 :- 0 and it's percentage : 0.0
 Total NaN values in row 2126 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 2127 :- 0 and it's percentage : 0.0
 Total NaN values in row 2128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2129 :- 0 and it's percentage : 0.0
 Total NaN values in row 2130 :- 0 and it's percentage : 0.0
 Total NaN values in row 2131 :- 0 and it's percentage : 0.0
 Total NaN values in row 2132 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2133 :- 0 and it's percentage : 0.0
 Total NaN values in row 2134 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2135 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2136 :- 0 and it's percentage : 0.0
 Total NaN values in row 2137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2138 :- 0 and it's percentage : 0.0
 Total NaN values in row 2139 :- 0 and it's percentage : 0.0
 Total NaN values in row 2140 :- 0 and it's percentage : 0.0
 Total NaN values in row 2141 :- 0 and it's percentage : 0.0
 Total NaN values in row 2142 :- 0 and it's percentage : 0.0
 Total NaN values in row 2143 :- 0 and it's percentage : 0.0
 Total NaN values in row 2144 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2145 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2147 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2148 :- 0 and it's percentage : 0.0
 Total NaN values in row 2149 :- 0 and it's percentage : 0.0
 Total NaN values in row 2150 :- 0 and it's percentage : 0.0
 Total NaN values in row 2151 :- 0 and it's percentage : 0.0
 Total NaN values in row 2152 :- 0 and it's percentage : 0.0
 Total NaN values in row 2153 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2154 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2155 :- 0 and it's percentage : 0.0
 Total NaN values in row 2156 :- 0 and it's percentage : 0.0
 Total NaN values in row 2157 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2158 :- 0 and it's percentage : 0.0
 Total NaN values in row 2159 :- 0 and it's percentage : 0.0
 Total NaN values in row 2160 :- 0 and it's percentage : 0.0
 Total NaN values in row 2161 :- 0 and it's percentage : 0.0
 Total NaN values in row 2162 :- 0 and it's percentage : 0.0
 Total NaN values in row 2163 :- 0 and it's percentage : 0.0
 Total NaN values in row 2164 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2165 :- 0 and it's percentage : 0.0
 Total NaN values in row 2166 :- 0 and it's percentage : 0.0
 Total NaN values in row 2167 :- 0 and it's percentage : 0.0
 Total NaN values in row 2168 :- 0 and it's percentage : 0.0
 Total NaN values in row 2169 :- 0 and it's percentage : 0.0
 Total NaN values in row 2170 :- 0 and it's percentage : 0.0
 Total NaN values in row 2171 :- 0 and it's percentage : 0.0
 Total NaN values in row 2172 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2173 :- 0 and it's percentage : 0.0
 Total NaN values in row 2174 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2175 :- 0 and it's percentage : 0.0
 Total NaN values in row 2176 :- 0 and it's percentage : 0.0
 Total NaN values in row 2177 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2178 :- 0 and it's percentage : 0.0
 Total NaN values in row 2179 :- 0 and it's percentage : 0.0
 Total NaN values in row 2180 :- 0 and it's percentage : 0.0
 Total NaN values in row 2181 :- 0 and it's percentage : 0.0
 Total NaN values in row 2182 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2183 :- 0 and it's percentage : 0.0
 Total NaN values in row 2184 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2185 :- 0 and it's percentage : 0.0
 Total NaN values in row 2186 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2187 :- 0 and it's percentage : 0.0
 Total NaN values in row 2188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2189 :- 0 and it's percentage : 0.0
 Total NaN values in row 2190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2191 :- 0 and it's percentage : 0.0
 Total NaN values in row 2192 :- 0 and it's percentage : 0.0
 Total NaN values in row 2193 :- 0 and it's percentage : 0.0
 Total NaN values in row 2194 :- 0 and it's percentage : 0.0
 Total NaN values in row 2195 :- 0 and it's percentage : 0.0
 Total NaN values in row 2196 :- 0 and it's percentage : 0.0
 Total NaN values in row 2197 :- 0 and it's percentage : 0.0
 Total NaN values in row 2198 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2200 :- 0 and it's percentage : 0.0
 Total NaN values in row 2201 :- 0 and it's percentage : 0.0
 Total NaN values in row 2202 :- 0 and it's percentage : 0.0
 Total NaN values in row 2203 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2204 :- 0 and it's percentage : 0.0
 Total NaN values in row 2205 :- 0 and it's percentage : 0.0
 Total NaN values in row 2206 :- 0 and it's percentage : 0.0
 Total NaN values in row 2207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2208 :- 0 and it's percentage : 0.0
 Total NaN values in row 2209 :- 0 and it's percentage : 0.0
 Total NaN values in row 2210 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 2211 :- 0 and it's percentage : 0.0
 Total NaN values in row 2212 :- 0 and it's percentage : 0.0
 Total NaN values in row 2213 :- 0 and it's percentage : 0.0
 Total NaN values in row 2214 :- 0 and it's percentage : 0.0
 Total NaN values in row 2215 :- 0 and it's percentage : 0.0
 Total NaN values in row 2216 :- 0 and it's percentage : 0.0
 Total NaN values in row 2217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2218 :- 0 and it's percentage : 0.0
 Total NaN values in row 2219 :- 0 and it's percentage : 0.0
 Total NaN values in row 2220 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2221 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2222 :- 0 and it's percentage : 0.0
 Total NaN values in row 2223 :- 0 and it's percentage : 0.0
 Total NaN values in row 2224 :- 0 and it's percentage : 0.0
 Total NaN values in row 2225 :- 0 and it's percentage : 0.0
 Total NaN values in row 2226 :- 0 and it's percentage : 0.0
 Total NaN values in row 2227 :- 0 and it's percentage : 0.0
 Total NaN values in row 2228 :- 0 and it's percentage : 0.0
 Total NaN values in row 2229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2230 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2231 :- 0 and it's percentage : 0.0
 Total NaN values in row 2232 :- 0 and it's percentage : 0.0
 Total NaN values in row 2233 :- 0 and it's percentage : 0.0
 Total NaN values in row 2234 :- 0 and it's percentage : 0.0
 Total NaN values in row 2235 :- 0 and it's percentage : 0.0
 Total NaN values in row 2236 :- 0 and it's percentage : 0.0
 Total NaN values in row 2237 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2238 :- 0 and it's percentage : 0.0
 Total NaN values in row 2239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2240 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2241 :- 0 and it's percentage : 0.0
 Total NaN values in row 2242 :- 0 and it's percentage : 0.0
 Total NaN values in row 2243 :- 0 and it's percentage : 0.0
 Total NaN values in row 2244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2245 :- 0 and it's percentage : 0.0
 Total NaN values in row 2246 :- 0 and it's percentage : 0.0
 Total NaN values in row 2247 :- 0 and it's percentage : 0.0
 Total NaN values in row 2248 :- 0 and it's percentage : 0.0
 Total NaN values in row 2249 :- 0 and it's percentage : 0.0
 Total NaN values in row 2250 :- 0 and it's percentage : 0.0
 Total NaN values in row 2251 :- 0 and it's percentage : 0.0
 Total NaN values in row 2252 :- 0 and it's percentage : 0.0
 Total NaN values in row 2253 :- 0 and it's percentage : 0.0

 Total NaN values in row 2254 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2255 :- 0 and it's percentage : 0.0
 Total NaN values in row 2256 :- 0 and it's percentage : 0.0
 Total NaN values in row 2257 :- 0 and it's percentage : 0.0
 Total NaN values in row 2258 :- 0 and it's percentage : 0.0
 Total NaN values in row 2259 :- 0 and it's percentage : 0.0
 Total NaN values in row 2260 :- 0 and it's percentage : 0.0
 Total NaN values in row 2261 :- 0 and it's percentage : 0.0
 Total NaN values in row 2262 :- 0 and it's percentage : 0.0
 Total NaN values in row 2263 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2264 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2265 :- 0 and it's percentage : 0.0
 Total NaN values in row 2266 :- 0 and it's percentage : 0.0
 Total NaN values in row 2267 :- 0 and it's percentage : 0.0
 Total NaN values in row 2268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2270 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2271 :- 0 and it's percentage : 0.0
 Total NaN values in row 2272 :- 0 and it's percentage : 0.0
 Total NaN values in row 2273 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2274 :- 0 and it's percentage : 0.0
 Total NaN values in row 2275 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2276 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2277 :- 0 and it's percentage : 0.0
 Total NaN values in row 2278 :- 0 and it's percentage : 0.0
 Total NaN values in row 2279 :- 0 and it's percentage : 0.0
 Total NaN values in row 2280 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2281 :- 0 and it's percentage : 0.0
 Total NaN values in row 2282 :- 0 and it's percentage : 0.0
 Total NaN values in row 2283 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2284 :- 0 and it's percentage : 0.0
 Total NaN values in row 2285 :- 0 and it's percentage : 0.0
 Total NaN values in row 2286 :- 0 and it's percentage : 0.0
 Total NaN values in row 2287 :- 0 and it's percentage : 0.0
 Total NaN values in row 2288 :- 0 and it's percentage : 0.0
 Total NaN values in row 2289 :- 0 and it's percentage : 0.0
 Total NaN values in row 2290 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2291 :- 0 and it's percentage : 0.0
 Total NaN values in row 2292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2293 :- 0 and it's percentage : 0.0
 Total NaN values in row 2294 :- 0 and it's percentage : 0.0
 Total NaN values in row 2295 :- 0 and it's percentage : 0.0
 Total NaN values in row 2296 :- 0 and it's percentage : 0.0
 Total NaN values in row 2297 :- 0 and it's percentage : 0.0
 Total NaN values in row 2298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2299 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2300 :- 0 and it's percentage : 0.0
 Total NaN values in row 2301 :- 0 and it's percentage : 0.0
 Total NaN values in row 2302 :- 0 and it's percentage : 0.0
 Total NaN values in row 2303 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2304 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2305 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2306 :- 0 and it's percentage : 0.0
 Total NaN values in row 2307 :- 0 and it's percentage : 0.0
 Total NaN values in row 2308 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2309 :- 0 and it's percentage : 0.0
 Total NaN values in row 2310 :- 0 and it's percentage : 0.0
 Total NaN values in row 2311 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2312 :- 0 and it's percentage : 0.0
 Total NaN values in row 2313 :- 0 and it's percentage : 0.0
 Total NaN values in row 2314 :- 0 and it's percentage : 0.0
 Total NaN values in row 2315 :- 0 and it's percentage : 0.0
 Total NaN values in row 2316 :- 0 and it's percentage : 0.0
 Total NaN values in row 2317 :- 0 and it's percentage : 0.0
 Total NaN values in row 2318 :- 0 and it's percentage : 0.0
 Total NaN values in row 2319 :- 0 and it's percentage : 0.0
 Total NaN values in row 2320 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2321 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2322 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2323 :- 0 and it's percentage : 0.0
 Total NaN values in row 2324 :- 0 and it's percentage : 0.0
 Total NaN values in row 2325 :- 0 and it's percentage : 0.0
 Total NaN values in row 2326 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2327 :- 0 and it's percentage : 0.0
 Total NaN values in row 2328 :- 0 and it's percentage : 0.0
 Total NaN values in row 2329 :- 0 and it's percentage : 0.0
 Total NaN values in row 2330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2331 :- 0 and it's percentage : 0.0
 Total NaN values in row 2332 :- 0 and it's percentage : 0.0
 Total NaN values in row 2333 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2334 :- 0 and it's percentage : 0.0
 Total NaN values in row 2335 :- 0 and it's percentage : 0.0
 Total NaN values in row 2336 :- 0 and it's percentage : 0.0
 Total NaN values in row 2337 :- 0 and it's percentage : 0.0
 Total NaN values in row 2338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2339 :- 0 and it's percentage : 0.0
 Total NaN values in row 2340 :- 0 and it's percentage : 0.0
 Total NaN values in row 2341 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2344 :- 0 and it's percentage : 0.0
 Total NaN values in row 2345 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2346 :- 0 and it's percentage : 0.0
 Total NaN values in row 2347 :- 0 and it's percentage : 0.0
 Total NaN values in row 2348 :- 0 and it's percentage : 0.0
 Total NaN values in row 2349 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2350 :- 0 and it's percentage : 0.0
 Total NaN values in row 2351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2352 :- 0 and it's percentage : 0.0
 Total NaN values in row 2353 :- 0 and it's percentage : 0.0
 Total NaN values in row 2354 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2355 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2356 :- 0 and it's percentage : 0.0
 Total NaN values in row 2357 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2358 :- 0 and it's percentage : 0.0
 Total NaN values in row 2359 :- 0 and it's percentage : 0.0
 Total NaN values in row 2360 :- 0 and it's percentage : 0.0
 Total NaN values in row 2361 :- 0 and it's percentage : 0.0
 Total NaN values in row 2362 :- 0 and it's percentage : 0.0
 Total NaN values in row 2363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2364 :- 0 and it's percentage : 0.0
 Total NaN values in row 2365 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2366 :- 0 and it's percentage : 0.0
 Total NaN values in row 2367 :- 0 and it's percentage : 0.0
 Total NaN values in row 2368 :- 0 and it's percentage : 0.0
 Total NaN values in row 2369 :- 0 and it's percentage : 0.0
 Total NaN values in row 2370 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2371 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2372 :- 0 and it's percentage : 0.0
 Total NaN values in row 2373 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2375 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2376 :- 0 and it's percentage : 0.0
 Total NaN values in row 2377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2378 :- 0 and it's percentage : 0.0
 Total NaN values in row 2379 :- 0 and it's percentage : 0.0
 Total NaN values in row 2380 :- 0 and it's percentage : 0.0
 Total NaN values in row 2381 :- 0 and it's percentage : 0.0
 Total NaN values in row 2382 :- 0 and it's percentage : 0.0
 Total NaN values in row 2383 :- 0 and it's percentage : 0.0
 Total NaN values in row 2384 :- 0 and it's percentage : 0.0
 Total NaN values in row 2385 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2386 :- 0 and it's percentage : 0.0
 Total NaN values in row 2387 :- 0 and it's percentage : 0.0
 Total NaN values in row 2388 :- 0 and it's percentage : 0.0
 Total NaN values in row 2389 :- 0 and it's percentage : 0.0
 Total NaN values in row 2390 :- 0 and it's percentage : 0.0
 Total NaN values in row 2391 :- 0 and it's percentage : 0.0

 Total NaN values in row 2392 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2393 :- 0 and it's percentage : 0.0
 Total NaN values in row 2394 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2395 :- 0 and it's percentage : 0.0
 Total NaN values in row 2396 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2397 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2398 :- 0 and it's percentage : 0.0
 Total NaN values in row 2399 :- 0 and it's percentage : 0.0
 Total NaN values in row 2400 :- 0 and it's percentage : 0.0
 Total NaN values in row 2401 :- 0 and it's percentage : 0.0
 Total NaN values in row 2402 :- 0 and it's percentage : 0.0
 Total NaN values in row 2403 :- 0 and it's percentage : 0.0
 Total NaN values in row 2404 :- 0 and it's percentage : 0.0
 Total NaN values in row 2405 :- 0 and it's percentage : 0.0
 Total NaN values in row 2406 :- 0 and it's percentage : 0.0
 Total NaN values in row 2407 :- 0 and it's percentage : 0.0
 Total NaN values in row 2408 :- 0 and it's percentage : 0.0
 Total NaN values in row 2409 :- 0 and it's percentage : 0.0
 Total NaN values in row 2410 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2411 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2412 :- 0 and it's percentage : 0.0
 Total NaN values in row 2413 :- 0 and it's percentage : 0.0
 Total NaN values in row 2414 :- 0 and it's percentage : 0.0
 Total NaN values in row 2415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2417 :- 0 and it's percentage : 0.0
 Total NaN values in row 2418 :- 0 and it's percentage : 0.0
 Total NaN values in row 2419 :- 0 and it's percentage : 0.0
 Total NaN values in row 2420 :- 0 and it's percentage : 0.0
 Total NaN values in row 2421 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2422 :- 0 and it's percentage : 0.0
 Total NaN values in row 2423 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2424 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2425 :- 0 and it's percentage : 0.0
 Total NaN values in row 2426 :- 0 and it's percentage : 0.0
 Total NaN values in row 2427 :- 0 and it's percentage : 0.0
 Total NaN values in row 2428 :- 0 and it's percentage : 0.0
 Total NaN values in row 2429 :- 0 and it's percentage : 0.0
 Total NaN values in row 2430 :- 0 and it's percentage : 0.0
 Total NaN values in row 2431 :- 0 and it's percentage : 0.0
 Total NaN values in row 2432 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2433 :- 0 and it's percentage : 0.0
 Total NaN values in row 2434 :- 0 and it's percentage : 0.0
 Total NaN values in row 2435 :- 0 and it's percentage : 0.0
 Total NaN values in row 2436 :- 0 and it's percentage : 0.0
 Total NaN values in row 2437 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2438 :- 0 and it's percentage : 0.0
 Total NaN values in row 2439 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2440 :- 0 and it's percentage : 0.0
 Total NaN values in row 2441 :- 0 and it's percentage : 0.0
 Total NaN values in row 2442 :- 0 and it's percentage : 0.0
 Total NaN values in row 2443 :- 0 and it's percentage : 0.0
 Total NaN values in row 2444 :- 0 and it's percentage : 0.0
 Total NaN values in row 2445 :- 0 and it's percentage : 0.0
 Total NaN values in row 2446 :- 0 and it's percentage : 0.0
 Total NaN values in row 2447 :- 0 and it's percentage : 0.0
 Total NaN values in row 2448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2449 :- 0 and it's percentage : 0.0
 Total NaN values in row 2450 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2451 :- 0 and it's percentage : 0.0
 Total NaN values in row 2452 :- 0 and it's percentage : 0.0
 Total NaN values in row 2453 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2454 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2455 :- 0 and it's percentage : 0.0
 Total NaN values in row 2456 :- 0 and it's percentage : 0.0
 Total NaN values in row 2457 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2458 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2459 :- 0 and it's percentage : 0.0
 Total NaN values in row 2460 :- 0 and it's percentage : 0.0
 Total NaN values in row 2461 :- 0 and it's percentage : 0.0
 Total NaN values in row 2462 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2463 :- 0 and it's percentage : 0.0
 Total NaN values in row 2464 :- 0 and it's percentage : 0.0
 Total NaN values in row 2465 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2466 :- 0 and it's percentage : 0.0
 Total NaN values in row 2467 :- 0 and it's percentage : 0.0
 Total NaN values in row 2468 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2469 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2470 :- 0 and it's percentage : 0.0
 Total NaN values in row 2471 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2472 :- 0 and it's percentage : 0.0
 Total NaN values in row 2473 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2474 :- 0 and it's percentage : 0.0
 Total NaN values in row 2475 :- 0 and it's percentage : 0.0
 Total NaN values in row 2476 :- 0 and it's percentage : 0.0
 Total NaN values in row 2477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2478 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2479 :- 0 and it's percentage : 0.0
 Total NaN values in row 2480 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2481 :- 0 and it's percentage : 0.0
 Total NaN values in row 2482 :- 0 and it's percentage : 0.0
 Total NaN values in row 2483 :- 0 and it's percentage : 0.0
 Total NaN values in row 2484 :- 0 and it's percentage : 0.0
 Total NaN values in row 2485 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2486 :- 0 and it's percentage : 0.0
 Total NaN values in row 2487 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2488 :- 0 and it's percentage : 0.0
 Total NaN values in row 2489 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2491 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2492 :- 0 and it's percentage : 0.0
 Total NaN values in row 2493 :- 0 and it's percentage : 0.0
 Total NaN values in row 2494 :- 0 and it's percentage : 0.0
 Total NaN values in row 2495 :- 0 and it's percentage : 0.0
 Total NaN values in row 2496 :- 0 and it's percentage : 0.0
 Total NaN values in row 2497 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2498 :- 0 and it's percentage : 0.0
 Total NaN values in row 2499 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2501 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2502 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2503 :- 0 and it's percentage : 0.0
 Total NaN values in row 2504 :- 0 and it's percentage : 0.0
 Total NaN values in row 2505 :- 0 and it's percentage : 0.0
 Total NaN values in row 2506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2507 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2508 :- 0 and it's percentage : 0.0
 Total NaN values in row 2509 :- 0 and it's percentage : 0.0
 Total NaN values in row 2510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2511 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2512 :- 0 and it's percentage : 0.0
 Total NaN values in row 2513 :- 0 and it's percentage : 0.0
 Total NaN values in row 2514 :- 0 and it's percentage : 0.0
 Total NaN values in row 2515 :- 0 and it's percentage : 0.0
 Total NaN values in row 2516 :- 0 and it's percentage : 0.0
 Total NaN values in row 2517 :- 0 and it's percentage : 0.0
 Total NaN values in row 2518 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2519 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 2520 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2521 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2522 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2523 :- 0 and it's percentage : 0.0
 Total NaN values in row 2524 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2525 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2526 :- 0 and it's percentage : 0.0
 Total NaN values in row 2527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2528 :- 0 and it's percentage : 0.0
 Total NaN values in row 2529 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2530 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2531 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2532 :- 0 and it's percentage : 0.0
 Total NaN values in row 2533 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2534 :- 0 and it's percentage : 0.0
 Total NaN values in row 2535 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2538 :- 0 and it's percentage : 0.0
 Total NaN values in row 2539 :- 0 and it's percentage : 0.0
 Total NaN values in row 2540 :- 0 and it's percentage : 0.0
 Total NaN values in row 2541 :- 0 and it's percentage : 0.0
 Total NaN values in row 2542 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2543 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2544 :- 0 and it's percentage : 0.0
 Total NaN values in row 2545 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2546 :- 0 and it's percentage : 0.0
 Total NaN values in row 2547 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2548 :- 0 and it's percentage : 0.0
 Total NaN values in row 2549 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2550 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2551 :- 0 and it's percentage : 0.0
 Total NaN values in row 2552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2553 :- 0 and it's percentage : 0.0
 Total NaN values in row 2554 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2555 :- 0 and it's percentage : 0.0
 Total NaN values in row 2556 :- 0 and it's percentage : 0.0
 Total NaN values in row 2557 :- 0 and it's percentage : 0.0
 Total NaN values in row 2558 :- 0 and it's percentage : 0.0
 Total NaN values in row 2559 :- 0 and it's percentage : 0.0
 Total NaN values in row 2560 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2562 :- 0 and it's percentage : 0.0
 Total NaN values in row 2563 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2564 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2565 :- 0 and it's percentage : 0.0
 Total NaN values in row 2566 :- 0 and it's percentage : 0.0
 Total NaN values in row 2567 :- 0 and it's percentage : 0.0
 Total NaN values in row 2568 :- 0 and it's percentage : 0.0
 Total NaN values in row 2569 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2570 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2571 :- 0 and it's percentage : 0.0
 Total NaN values in row 2572 :- 0 and it's percentage : 0.0
 Total NaN values in row 2573 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 2574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2575 :- 0 and it's percentage : 0.0
 Total NaN values in row 2576 :- 0 and it's percentage : 0.0
 Total NaN values in row 2577 :- 0 and it's percentage : 0.0
 Total NaN values in row 2578 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2579 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2580 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2581 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2582 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2583 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2584 :- 0 and it's percentage : 0.0
 Total NaN values in row 2585 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2586 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2587 :- 0 and it's percentage : 0.0
 Total NaN values in row 2588 :- 0 and it's percentage : 0.0
 Total NaN values in row 2589 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2590 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2591 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2592 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 2593 :- 0 and it's percentage : 0.0
 Total NaN values in row 2594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2595 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2596 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2597 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2598 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2599 :- 0 and it's percentage : 0.0
 Total NaN values in row 2600 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2601 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2602 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2603 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2604 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2605 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2606 :- 0 and it's percentage : 0.0
 Total NaN values in row 2607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2608 :- 0 and it's percentage : 0.0
 Total NaN values in row 2609 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2610 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2611 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2612 :- 0 and it's percentage : 0.0
 Total NaN values in row 2613 :- 0 and it's percentage : 0.0
 Total NaN values in row 2614 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 2615 :- 0 and it's percentage : 0.0
 Total NaN values in row 2616 :- 0 and it's percentage : 0.0
 Total NaN values in row 2617 :- 0 and it's percentage : 0.0
 Total NaN values in row 2618 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2619 :- 0 and it's percentage : 0.0
 Total NaN values in row 2620 :- 0 and it's percentage : 0.0
 Total NaN values in row 2621 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2622 :- 0 and it's percentage : 0.0
 Total NaN values in row 2623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2624 :- 0 and it's percentage : 0.0
 Total NaN values in row 2625 :- 0 and it's percentage : 0.0
 Total NaN values in row 2626 :- 0 and it's percentage : 0.0
 Total NaN values in row 2627 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2628 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2629 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2630 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2631 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2632 :- 0 and it's percentage : 0.0
 Total NaN values in row 2633 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2635 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2636 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2637 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2638 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2639 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2640 :- 0 and it's percentage : 0.0
 Total NaN values in row 2641 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2642 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2643 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2644 :- 0 and it's percentage : 0.0
 Total NaN values in row 2645 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2646 :- 0 and it's percentage : 0.0
 Total NaN values in row 2647 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2649 :- 0 and it's percentage : 0.0
 Total NaN values in row 2650 :- 0 and it's percentage : 0.0
 Total NaN values in row 2651 :- 0 and it's percentage : 0.0
 Total NaN values in row 2652 :- 0 and it's percentage : 0.0
 Total NaN values in row 2653 :- 0 and it's percentage : 0.0
 Total NaN values in row 2654 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2655 :- 0 and it's percentage : 0.0
 Total NaN values in row 2656 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2657 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2658 :- 7 and it's percentage : 38.888888888888886

 Total NaN values in row 2659 :- 0 and it's percentage : 0.0
 Total NaN values in row 2660 :- 0 and it's percentage : 0.0
 Total NaN values in row 2661 :- 0 and it's percentage : 0.0
 Total NaN values in row 2662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2664 :- 0 and it's percentage : 0.0
 Total NaN values in row 2665 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2666 :- 0 and it's percentage : 0.0
 Total NaN values in row 2667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2669 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2670 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2671 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2672 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2673 :- 0 and it's percentage : 0.0
 Total NaN values in row 2674 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2675 :- 0 and it's percentage : 0.0
 Total NaN values in row 2676 :- 0 and it's percentage : 0.0
 Total NaN values in row 2677 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2679 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2680 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2681 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2682 :- 0 and it's percentage : 0.0
 Total NaN values in row 2683 :- 0 and it's percentage : 0.0
 Total NaN values in row 2684 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2685 :- 0 and it's percentage : 0.0
 Total NaN values in row 2686 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2687 :- 0 and it's percentage : 0.0
 Total NaN values in row 2688 :- 0 and it's percentage : 0.0
 Total NaN values in row 2689 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2690 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2691 :- 0 and it's percentage : 0.0
 Total NaN values in row 2692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2693 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2694 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2696 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2697 :- 0 and it's percentage : 0.0
 Total NaN values in row 2698 :- 0 and it's percentage : 0.0
 Total NaN values in row 2699 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2700 :- 0 and it's percentage : 0.0
 Total NaN values in row 2701 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2702 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2703 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2705 :- 0 and it's percentage : 0.0
 Total NaN values in row 2706 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2707 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2708 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2709 :- 0 and it's percentage : 0.0
 Total NaN values in row 2710 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2712 :- 0 and it's percentage : 0.0
 Total NaN values in row 2713 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2714 :- 0 and it's percentage : 0.0
 Total NaN values in row 2715 :- 0 and it's percentage : 0.0
 Total NaN values in row 2716 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2717 :- 0 and it's percentage : 0.0
 Total NaN values in row 2718 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2719 :- 0 and it's percentage : 0.0
 Total NaN values in row 2720 :- 0 and it's percentage : 0.0
 Total NaN values in row 2721 :- 0 and it's percentage : 0.0
 Total NaN values in row 2722 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2723 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2724 :- 0 and it's percentage : 0.0
 Total NaN values in row 2725 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2726 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2727 :- 0 and it's percentage : 0.0
 Total NaN values in row 2728 :- 0 and it's percentage : 0.0
 Total NaN values in row 2729 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2730 :- 0 and it's percentage : 0.0
 Total NaN values in row 2731 :- 0 and it's percentage : 0.0
 Total NaN values in row 2732 :- 0 and it's percentage : 0.0
 Total NaN values in row 2733 :- 0 and it's percentage : 0.0
 Total NaN values in row 2734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2735 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2736 :- 0 and it's percentage : 0.0
 Total NaN values in row 2737 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2738 :- 0 and it's percentage : 0.0
 Total NaN values in row 2739 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2740 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2741 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2742 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2743 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2744 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2745 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2746 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2747 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2748 :- 0 and it's percentage : 0.0
 Total NaN values in row 2749 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2750 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2751 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2752 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2753 :- 0 and it's percentage : 0.0
 Total NaN values in row 2754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2755 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2756 :- 0 and it's percentage : 0.0
 Total NaN values in row 2757 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2758 :- 0 and it's percentage : 0.0
 Total NaN values in row 2759 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2762 :- 0 and it's percentage : 0.0
 Total NaN values in row 2763 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2764 :- 0 and it's percentage : 0.0
 Total NaN values in row 2765 :- 0 and it's percentage : 0.0
 Total NaN values in row 2766 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2767 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2768 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2769 :- 0 and it's percentage : 0.0
 Total NaN values in row 2770 :- 0 and it's percentage : 0.0
 Total NaN values in row 2771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2772 :- 0 and it's percentage : 0.0
 Total NaN values in row 2773 :- 0 and it's percentage : 0.0
 Total NaN values in row 2774 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2775 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2776 :- 0 and it's percentage : 0.0
 Total NaN values in row 2777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2779 :- 0 and it's percentage : 0.0
 Total NaN values in row 2780 :- 0 and it's percentage : 0.0
 Total NaN values in row 2781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2782 :- 0 and it's percentage : 0.0
 Total NaN values in row 2783 :- 0 and it's percentage : 0.0
 Total NaN values in row 2784 :- 0 and it's percentage : 0.0
 Total NaN values in row 2785 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2787 :- 0 and it's percentage : 0.0
 Total NaN values in row 2788 :- 0 and it's percentage : 0.0
 Total NaN values in row 2789 :- 0 and it's percentage : 0.0
 Total NaN values in row 2790 :- 0 and it's percentage : 0.0
 Total NaN values in row 2791 :- 0 and it's percentage : 0.0
 Total NaN values in row 2792 :- 0 and it's percentage : 0.0
 Total NaN values in row 2793 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2794 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 2795 :- 0 and it's percentage : 0.0
 Total NaN values in row 2796 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2797 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2798 :- 0 and it's percentage : 0.0
 Total NaN values in row 2799 :- 0 and it's percentage : 0.0
 Total NaN values in row 2800 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2801 :- 0 and it's percentage : 0.0
 Total NaN values in row 2802 :- 0 and it's percentage : 0.0
 Total NaN values in row 2803 :- 0 and it's percentage : 0.0
 Total NaN values in row 2804 :- 0 and it's percentage : 0.0
 Total NaN values in row 2805 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2806 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2807 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2808 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2809 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2810 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2811 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2812 :- 0 and it's percentage : 0.0
 Total NaN values in row 2813 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2814 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2815 :- 0 and it's percentage : 0.0
 Total NaN values in row 2816 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2818 :- 0 and it's percentage : 0.0
 Total NaN values in row 2819 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2820 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2821 :- 0 and it's percentage : 0.0
 Total NaN values in row 2822 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2823 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2824 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2825 :- 0 and it's percentage : 0.0
 Total NaN values in row 2826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2827 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2828 :- 0 and it's percentage : 0.0
 Total NaN values in row 2829 :- 0 and it's percentage : 0.0
 Total NaN values in row 2830 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2831 :- 0 and it's percentage : 0.0
 Total NaN values in row 2832 :- 0 and it's percentage : 0.0
 Total NaN values in row 2833 :- 0 and it's percentage : 0.0
 Total NaN values in row 2834 :- 0 and it's percentage : 0.0
 Total NaN values in row 2835 :- 0 and it's percentage : 0.0
 Total NaN values in row 2836 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2837 :- 0 and it's percentage : 0.0
 Total NaN values in row 2838 :- 0 and it's percentage : 0.0
 Total NaN values in row 2839 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2840 :- 0 and it's percentage : 0.0
 Total NaN values in row 2841 :- 0 and it's percentage : 0.0
 Total NaN values in row 2842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2843 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2844 :- 0 and it's percentage : 0.0
 Total NaN values in row 2845 :- 0 and it's percentage : 0.0
 Total NaN values in row 2846 :- 0 and it's percentage : 0.0
 Total NaN values in row 2847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2848 :- 0 and it's percentage : 0.0
 Total NaN values in row 2849 :- 0 and it's percentage : 0.0
 Total NaN values in row 2850 :- 0 and it's percentage : 0.0
 Total NaN values in row 2851 :- 0 and it's percentage : 0.0
 Total NaN values in row 2852 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2853 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2855 :- 0 and it's percentage : 0.0
 Total NaN values in row 2856 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2857 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2858 :- 0 and it's percentage : 0.0
 Total NaN values in row 2859 :- 0 and it's percentage : 0.0
 Total NaN values in row 2860 :- 0 and it's percentage : 0.0
 Total NaN values in row 2861 :- 0 and it's percentage : 0.0
 Total NaN values in row 2862 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2863 :- 0 and it's percentage : 0.0
 Total NaN values in row 2864 :- 0 and it's percentage : 0.0
 Total NaN values in row 2865 :- 0 and it's percentage : 0.0
 Total NaN values in row 2866 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2867 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2868 :- 0 and it's percentage : 0.0
 Total NaN values in row 2869 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2870 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2872 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2873 :- 0 and it's percentage : 0.0
 Total NaN values in row 2874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2875 :- 0 and it's percentage : 0.0
 Total NaN values in row 2876 :- 0 and it's percentage : 0.0
 Total NaN values in row 2877 :- 0 and it's percentage : 0.0
 Total NaN values in row 2878 :- 0 and it's percentage : 0.0
 Total NaN values in row 2879 :- 0 and it's percentage : 0.0
 Total NaN values in row 2880 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2881 :- 0 and it's percentage : 0.0
 Total NaN values in row 2882 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2883 :- 0 and it's percentage : 0.0
 Total NaN values in row 2884 :- 0 and it's percentage : 0.0
 Total NaN values in row 2885 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2886 :- 0 and it's percentage : 0.0
 Total NaN values in row 2887 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2888 :- 0 and it's percentage : 0.0
 Total NaN values in row 2889 :- 0 and it's percentage : 0.0
 Total NaN values in row 2890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2891 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2892 :- 0 and it's percentage : 0.0
 Total NaN values in row 2893 :- 0 and it's percentage : 0.0
 Total NaN values in row 2894 :- 0 and it's percentage : 0.0
 Total NaN values in row 2895 :- 0 and it's percentage : 0.0
 Total NaN values in row 2896 :- 0 and it's percentage : 0.0
 Total NaN values in row 2897 :- 0 and it's percentage : 0.0
 Total NaN values in row 2898 :- 0 and it's percentage : 0.0
 Total NaN values in row 2899 :- 0 and it's percentage : 0.0
 Total NaN values in row 2900 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2901 :- 0 and it's percentage : 0.0
 Total NaN values in row 2902 :- 0 and it's percentage : 0.0
 Total NaN values in row 2903 :- 0 and it's percentage : 0.0
 Total NaN values in row 2904 :- 0 and it's percentage : 0.0
 Total NaN values in row 2905 :- 0 and it's percentage : 0.0
 Total NaN values in row 2906 :- 0 and it's percentage : 0.0
 Total NaN values in row 2907 :- 0 and it's percentage : 0.0
 Total NaN values in row 2908 :- 0 and it's percentage : 0.0
 Total NaN values in row 2909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2910 :- 0 and it's percentage : 0.0
 Total NaN values in row 2911 :- 0 and it's percentage : 0.0
 Total NaN values in row 2912 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2913 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2914 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2915 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2916 :- 0 and it's percentage : 0.0
 Total NaN values in row 2917 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2918 :- 0 and it's percentage : 0.0
 Total NaN values in row 2919 :- 0 and it's percentage : 0.0
 Total NaN values in row 2920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2922 :- 0 and it's percentage : 0.0
 Total NaN values in row 2923 :- 0 and it's percentage : 0.0

 Total NaN values in row 2924 :- 0 and it's percentage : 0.0
 Total NaN values in row 2925 :- 0 and it's percentage : 0.0
 Total NaN values in row 2926 :- 0 and it's percentage : 0.0
 Total NaN values in row 2927 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2928 :- 0 and it's percentage : 0.0
 Total NaN values in row 2929 :- 0 and it's percentage : 0.0
 Total NaN values in row 2930 :- 0 and it's percentage : 0.0
 Total NaN values in row 2931 :- 0 and it's percentage : 0.0
 Total NaN values in row 2932 :- 0 and it's percentage : 0.0
 Total NaN values in row 2933 :- 0 and it's percentage : 0.0
 Total NaN values in row 2934 :- 0 and it's percentage : 0.0
 Total NaN values in row 2935 :- 0 and it's percentage : 0.0
 Total NaN values in row 2936 :- 0 and it's percentage : 0.0
 Total NaN values in row 2937 :- 0 and it's percentage : 0.0
 Total NaN values in row 2938 :- 0 and it's percentage : 0.0
 Total NaN values in row 2939 :- 0 and it's percentage : 0.0
 Total NaN values in row 2940 :- 0 and it's percentage : 0.0
 Total NaN values in row 2941 :- 0 and it's percentage : 0.0
 Total NaN values in row 2942 :- 0 and it's percentage : 0.0
 Total NaN values in row 2943 :- 0 and it's percentage : 0.0
 Total NaN values in row 2944 :- 0 and it's percentage : 0.0
 Total NaN values in row 2945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2946 :- 0 and it's percentage : 0.0
 Total NaN values in row 2947 :- 0 and it's percentage : 0.0
 Total NaN values in row 2948 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2949 :- 0 and it's percentage : 0.0
 Total NaN values in row 2950 :- 0 and it's percentage : 0.0
 Total NaN values in row 2951 :- 0 and it's percentage : 0.0
 Total NaN values in row 2952 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2954 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2955 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2956 :- 0 and it's percentage : 0.0
 Total NaN values in row 2957 :- 0 and it's percentage : 0.0
 Total NaN values in row 2958 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2959 :- 0 and it's percentage : 0.0
 Total NaN values in row 2960 :- 0 and it's percentage : 0.0
 Total NaN values in row 2961 :- 0 and it's percentage : 0.0
 Total NaN values in row 2962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2963 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2964 :- 0 and it's percentage : 0.0
 Total NaN values in row 2965 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2966 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2967 :- 0 and it's percentage : 0.0
 Total NaN values in row 2968 :- 0 and it's percentage : 0.0
 Total NaN values in row 2969 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2970 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2971 :- 0 and it's percentage : 0.0
 Total NaN values in row 2972 :- 0 and it's percentage : 0.0
 Total NaN values in row 2973 :- 0 and it's percentage : 0.0
 Total NaN values in row 2974 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 2975 :- 0 and it's percentage : 0.0
 Total NaN values in row 2976 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2977 :- 0 and it's percentage : 0.0
 Total NaN values in row 2978 :- 0 and it's percentage : 0.0
 Total NaN values in row 2979 :- 0 and it's percentage : 0.0
 Total NaN values in row 2980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2981 :- 0 and it's percentage : 0.0
 Total NaN values in row 2982 :- 0 and it's percentage : 0.0
 Total NaN values in row 2983 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2984 :- 0 and it's percentage : 0.0
 Total NaN values in row 2985 :- 0 and it's percentage : 0.0
 Total NaN values in row 2986 :- 0 and it's percentage : 0.0
 Total NaN values in row 2987 :- 0 and it's percentage : 0.0
 Total NaN values in row 2988 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 2989 :- 0 and it's percentage : 0.0
 Total NaN values in row 2990 :- 0 and it's percentage : 0.0
 Total NaN values in row 2991 :- 0 and it's percentage : 0.0
 Total NaN values in row 2992 :- 0 and it's percentage : 0.0
 Total NaN values in row 2993 :- 0 and it's percentage : 0.0
 Total NaN values in row 2994 :- 0 and it's percentage : 0.0
 Total NaN values in row 2995 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2996 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 2997 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 2998 :- 0 and it's percentage : 0.0
 Total NaN values in row 2999 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3000 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3001 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3002 :- 0 and it's percentage : 0.0
 Total NaN values in row 3003 :- 0 and it's percentage : 0.0
 Total NaN values in row 3004 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3005 :- 0 and it's percentage : 0.0
 Total NaN values in row 3006 :- 0 and it's percentage : 0.0
 Total NaN values in row 3007 :- 0 and it's percentage : 0.0
 Total NaN values in row 3008 :- 0 and it's percentage : 0.0
 Total NaN values in row 3009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3010 :- 0 and it's percentage : 0.0
 Total NaN values in row 3011 :- 0 and it's percentage : 0.0
 Total NaN values in row 3012 :- 0 and it's percentage : 0.0
 Total NaN values in row 3013 :- 0 and it's percentage : 0.0
 Total NaN values in row 3014 :- 0 and it's percentage : 0.0
 Total NaN values in row 3015 :- 0 and it's percentage : 0.0
 Total NaN values in row 3016 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3017 :- 0 and it's percentage : 0.0
 Total NaN values in row 3018 :- 0 and it's percentage : 0.0
 Total NaN values in row 3019 :- 0 and it's percentage : 0.0
 Total NaN values in row 3020 :- 0 and it's percentage : 0.0
 Total NaN values in row 3021 :- 0 and it's percentage : 0.0
 Total NaN values in row 3022 :- 0 and it's percentage : 0.0
 Total NaN values in row 3023 :- 0 and it's percentage : 0.0
 Total NaN values in row 3024 :- 0 and it's percentage : 0.0
 Total NaN values in row 3025 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3026 :- 0 and it's percentage : 0.0
 Total NaN values in row 3027 :- 0 and it's percentage : 0.0
 Total NaN values in row 3028 :- 0 and it's percentage : 0.0
 Total NaN values in row 3029 :- 0 and it's percentage : 0.0
 Total NaN values in row 3030 :- 0 and it's percentage : 0.0
 Total NaN values in row 3031 :- 0 and it's percentage : 0.0
 Total NaN values in row 3032 :- 0 and it's percentage : 0.0
 Total NaN values in row 3033 :- 0 and it's percentage : 0.0
 Total NaN values in row 3034 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3035 :- 0 and it's percentage : 0.0
 Total NaN values in row 3036 :- 0 and it's percentage : 0.0
 Total NaN values in row 3037 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3038 :- 0 and it's percentage : 0.0
 Total NaN values in row 3039 :- 0 and it's percentage : 0.0
 Total NaN values in row 3040 :- 0 and it's percentage : 0.0
 Total NaN values in row 3041 :- 0 and it's percentage : 0.0
 Total NaN values in row 3042 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3043 :- 0 and it's percentage : 0.0
 Total NaN values in row 3044 :- 0 and it's percentage : 0.0
 Total NaN values in row 3045 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3046 :- 0 and it's percentage : 0.0
 Total NaN values in row 3047 :- 0 and it's percentage : 0.0
 Total NaN values in row 3048 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3049 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3051 :- 0 and it's percentage : 0.0
 Total NaN values in row 3052 :- 0 and it's percentage : 0.0
 Total NaN values in row 3053 :- 0 and it's percentage : 0.0
 Total NaN values in row 3054 :- 0 and it's percentage : 0.0
 Total NaN values in row 3055 :- 0 and it's percentage : 0.0
 Total NaN values in row 3056 :- 0 and it's percentage : 0.0
 Total NaN values in row 3057 :- 0 and it's percentage : 0.0
 Total NaN values in row 3058 :- 0 and it's percentage : 0.0
 Total NaN values in row 3059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3060 :- 0 and it's percentage : 0.0
 Total NaN values in row 3061 :- 0 and it's percentage : 0.0
 Total NaN values in row 3062 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3063 :- 0 and it's percentage : 0.0
 Total NaN values in row 3064 :- 0 and it's percentage : 0.0
 Total NaN values in row 3065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3066 :- 0 and it's percentage : 0.0
 Total NaN values in row 3067 :- 0 and it's percentage : 0.0
 Total NaN values in row 3068 :- 0 and it's percentage : 0.0
 Total NaN values in row 3069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3070 :- 0 and it's percentage : 0.0
 Total NaN values in row 3071 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3072 :- 0 and it's percentage : 0.0
 Total NaN values in row 3073 :- 0 and it's percentage : 0.0
 Total NaN values in row 3074 :- 0 and it's percentage : 0.0
 Total NaN values in row 3075 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3076 :- 0 and it's percentage : 0.0

 Total NaN values in row 3077 :- 0 and it's percentage : 0.0
 Total NaN values in row 3078 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3079 :- 0 and it's percentage : 0.0
 Total NaN values in row 3080 :- 0 and it's percentage : 0.0
 Total NaN values in row 3081 :- 0 and it's percentage : 0.0
 Total NaN values in row 3082 :- 0 and it's percentage : 0.0
 Total NaN values in row 3083 :- 0 and it's percentage : 0.0
 Total NaN values in row 3084 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 3085 :- 0 and it's percentage : 0.0
 Total NaN values in row 3086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3087 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3088 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3089 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3090 :- 0 and it's percentage : 0.0
 Total NaN values in row 3091 :- 0 and it's percentage : 0.0
 Total NaN values in row 3092 :- 0 and it's percentage : 0.0
 Total NaN values in row 3093 :- 0 and it's percentage : 0.0
 Total NaN values in row 3094 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3095 :- 0 and it's percentage : 0.0
 Total NaN values in row 3096 :- 0 and it's percentage : 0.0
 Total NaN values in row 3097 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3099 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3100 :- 0 and it's percentage : 0.0
 Total NaN values in row 3101 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 3102 :- 0 and it's percentage : 0.0
 Total NaN values in row 3103 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3104 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3105 :- 0 and it's percentage : 0.0
 Total NaN values in row 3106 :- 0 and it's percentage : 0.0
 Total NaN values in row 3107 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3108 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3109 :- 0 and it's percentage : 0.0
 Total NaN values in row 3110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3111 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3113 :- 0 and it's percentage : 0.0
 Total NaN values in row 3114 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3115 :- 0 and it's percentage : 0.0
 Total NaN values in row 3116 :- 0 and it's percentage : 0.0
 Total NaN values in row 3117 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3119 :- 0 and it's percentage : 0.0
 Total NaN values in row 3120 :- 0 and it's percentage : 0.0
 Total NaN values in row 3121 :- 0 and it's percentage : 0.0
 Total NaN values in row 3122 :- 0 and it's percentage : 0.0
 Total NaN values in row 3123 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3124 :- 0 and it's percentage : 0.0
 Total NaN values in row 3125 :- 0 and it's percentage : 0.0
 Total NaN values in row 3126 :- 0 and it's percentage : 0.0
 Total NaN values in row 3127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3128 :- 0 and it's percentage : 0.0
 Total NaN values in row 3129 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3130 :- 0 and it's percentage : 0.0
 Total NaN values in row 3131 :- 0 and it's percentage : 0.0
 Total NaN values in row 3132 :- 0 and it's percentage : 0.0
 Total NaN values in row 3133 :- 0 and it's percentage : 0.0
 Total NaN values in row 3134 :- 0 and it's percentage : 0.0
 Total NaN values in row 3135 :- 0 and it's percentage : 0.0
 Total NaN values in row 3136 :- 0 and it's percentage : 0.0
 Total NaN values in row 3137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3138 :- 0 and it's percentage : 0.0
 Total NaN values in row 3139 :- 0 and it's percentage : 0.0
 Total NaN values in row 3140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3143 :- 0 and it's percentage : 0.0
 Total NaN values in row 3144 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3145 :- 0 and it's percentage : 0.0
 Total NaN values in row 3146 :- 0 and it's percentage : 0.0
 Total NaN values in row 3147 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3148 :- 0 and it's percentage : 0.0
 Total NaN values in row 3149 :- 0 and it's percentage : 0.0
 Total NaN values in row 3150 :- 0 and it's percentage : 0.0
 Total NaN values in row 3151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3152 :- 0 and it's percentage : 0.0
 Total NaN values in row 3153 :- 0 and it's percentage : 0.0
 Total NaN values in row 3154 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3155 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3156 :- 0 and it's percentage : 0.0
 Total NaN values in row 3157 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3158 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3159 :- 0 and it's percentage : 0.0
 Total NaN values in row 3160 :- 0 and it's percentage : 0.0
 Total NaN values in row 3161 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3162 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3163 :- 0 and it's percentage : 0.0
 Total NaN values in row 3164 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3165 :- 0 and it's percentage : 0.0
 Total NaN values in row 3166 :- 0 and it's percentage : 0.0
 Total NaN values in row 3167 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3168 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3169 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3171 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3172 :- 0 and it's percentage : 0.0
 Total NaN values in row 3173 :- 0 and it's percentage : 0.0
 Total NaN values in row 3174 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3175 :- 0 and it's percentage : 0.0
 Total NaN values in row 3176 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3177 :- 0 and it's percentage : 0.0
 Total NaN values in row 3178 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3180 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3181 :- 0 and it's percentage : 0.0
 Total NaN values in row 3182 :- 0 and it's percentage : 0.0
 Total NaN values in row 3183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3184 :- 0 and it's percentage : 0.0
 Total NaN values in row 3185 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3187 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3189 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3190 :- 0 and it's percentage : 0.0
 Total NaN values in row 3191 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3192 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3193 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3194 :- 0 and it's percentage : 0.0
 Total NaN values in row 3195 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3196 :- 0 and it's percentage : 0.0
 Total NaN values in row 3197 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3198 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3199 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3200 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3201 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 3202 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3203 :- 0 and it's percentage : 0.0
 Total NaN values in row 3204 :- 0 and it's percentage : 0.0
 Total NaN values in row 3205 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3206 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3208 :- 0 and it's percentage : 0.0
 Total NaN values in row 3209 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3210 :- 0 and it's percentage : 0.0
 Total NaN values in row 3211 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 3212 :- 0 and it's percentage : 0.0
 Total NaN values in row 3213 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3214 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3215 :- 0 and it's percentage : 0.0
 Total NaN values in row 3216 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3217 :- 0 and it's percentage : 0.0
 Total NaN values in row 3218 :- 0 and it's percentage : 0.0
 Total NaN values in row 3219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3220 :- 0 and it's percentage : 0.0
 Total NaN values in row 3221 :- 0 and it's percentage : 0.0
 Total NaN values in row 3222 :- 0 and it's percentage : 0.0
 Total NaN values in row 3223 :- 0 and it's percentage : 0.0
 Total NaN values in row 3224 :- 0 and it's percentage : 0.0
 Total NaN values in row 3225 :- 0 and it's percentage : 0.0
 Total NaN values in row 3226 :- 0 and it's percentage : 0.0
 Total NaN values in row 3227 :- 0 and it's percentage : 0.0
 Total NaN values in row 3228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3230 :- 0 and it's percentage : 0.0
 Total NaN values in row 3231 :- 0 and it's percentage : 0.0
 Total NaN values in row 3232 :- 0 and it's percentage : 0.0
 Total NaN values in row 3233 :- 0 and it's percentage : 0.0
 Total NaN values in row 3234 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3235 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3236 :- 0 and it's percentage : 0.0
 Total NaN values in row 3237 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3238 :- 0 and it's percentage : 0.0
 Total NaN values in row 3239 :- 0 and it's percentage : 0.0
 Total NaN values in row 3240 :- 0 and it's percentage : 0.0
 Total NaN values in row 3241 :- 0 and it's percentage : 0.0
 Total NaN values in row 3242 :- 0 and it's percentage : 0.0
 Total NaN values in row 3243 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3245 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3246 :- 0 and it's percentage : 0.0
 Total NaN values in row 3247 :- 0 and it's percentage : 0.0
 Total NaN values in row 3248 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3249 :- 0 and it's percentage : 0.0
 Total NaN values in row 3250 :- 0 and it's percentage : 0.0
 Total NaN values in row 3251 :- 0 and it's percentage : 0.0
 Total NaN values in row 3252 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3253 :- 0 and it's percentage : 0.0
 Total NaN values in row 3254 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3255 :- 0 and it's percentage : 0.0
 Total NaN values in row 3256 :- 0 and it's percentage : 0.0
 Total NaN values in row 3257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3258 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 3259 :- 0 and it's percentage : 0.0
 Total NaN values in row 3260 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3261 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3262 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3263 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3264 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3265 :- 0 and it's percentage : 0.0
 Total NaN values in row 3266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3268 :- 0 and it's percentage : 0.0
 Total NaN values in row 3269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3271 :- 0 and it's percentage : 0.0
 Total NaN values in row 3272 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3273 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3274 :- 0 and it's percentage : 0.0
 Total NaN values in row 3275 :- 0 and it's percentage : 0.0
 Total NaN values in row 3276 :- 0 and it's percentage : 0.0
 Total NaN values in row 3277 :- 0 and it's percentage : 0.0
 Total NaN values in row 3278 :- 0 and it's percentage : 0.0
 Total NaN values in row 3279 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3280 :- 0 and it's percentage : 0.0
 Total NaN values in row 3281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3282 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3283 :- 0 and it's percentage : 0.0
 Total NaN values in row 3284 :- 0 and it's percentage : 0.0
 Total NaN values in row 3285 :- 0 and it's percentage : 0.0
 Total NaN values in row 3286 :- 0 and it's percentage : 0.0
 Total NaN values in row 3287 :- 0 and it's percentage : 0.0
 Total NaN values in row 3288 :- 0 and it's percentage : 0.0
 Total NaN values in row 3289 :- 0 and it's percentage : 0.0
 Total NaN values in row 3290 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3291 :- 0 and it's percentage : 0.0
 Total NaN values in row 3292 :- 0 and it's percentage : 0.0
 Total NaN values in row 3293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3294 :- 0 and it's percentage : 0.0
 Total NaN values in row 3295 :- 0 and it's percentage : 0.0
 Total NaN values in row 3296 :- 0 and it's percentage : 0.0
 Total NaN values in row 3297 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3298 :- 0 and it's percentage : 0.0
 Total NaN values in row 3299 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3300 :- 0 and it's percentage : 0.0
 Total NaN values in row 3301 :- 0 and it's percentage : 0.0
 Total NaN values in row 3302 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3303 :- 0 and it's percentage : 0.0
 Total NaN values in row 3304 :- 0 and it's percentage : 0.0
 Total NaN values in row 3305 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3306 :- 0 and it's percentage : 0.0
 Total NaN values in row 3307 :- 0 and it's percentage : 0.0
 Total NaN values in row 3308 :- 0 and it's percentage : 0.0
 Total NaN values in row 3309 :- 0 and it's percentage : 0.0
 Total NaN values in row 3310 :- 0 and it's percentage : 0.0
 Total NaN values in row 3311 :- 0 and it's percentage : 0.0
 Total NaN values in row 3312 :- 0 and it's percentage : 0.0
 Total NaN values in row 3313 :- 0 and it's percentage : 0.0
 Total NaN values in row 3314 :- 0 and it's percentage : 0.0
 Total NaN values in row 3315 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3316 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3317 :- 0 and it's percentage : 0.0
 Total NaN values in row 3318 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3319 :- 0 and it's percentage : 0.0
 Total NaN values in row 3320 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3321 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3322 :- 0 and it's percentage : 0.0
 Total NaN values in row 3323 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3324 :- 0 and it's percentage : 0.0
 Total NaN values in row 3325 :- 0 and it's percentage : 0.0
 Total NaN values in row 3326 :- 0 and it's percentage : 0.0
 Total NaN values in row 3327 :- 0 and it's percentage : 0.0
 Total NaN values in row 3328 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3330 :- 0 and it's percentage : 0.0
 Total NaN values in row 3331 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3332 :- 0 and it's percentage : 0.0
 Total NaN values in row 3333 :- 0 and it's percentage : 0.0
 Total NaN values in row 3334 :- 0 and it's percentage : 0.0
 Total NaN values in row 3335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3336 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3337 :- 0 and it's percentage : 0.0
 Total NaN values in row 3338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3339 :- 0 and it's percentage : 0.0
 Total NaN values in row 3340 :- 0 and it's percentage : 0.0
 Total NaN values in row 3341 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3342 :- 0 and it's percentage : 0.0
 Total NaN values in row 3343 :- 0 and it's percentage : 0.0
 Total NaN values in row 3344 :- 0 and it's percentage : 0.0
 Total NaN values in row 3345 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 3346 :- 0 and it's percentage : 0.0
 Total NaN values in row 3347 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3348 :- 0 and it's percentage : 0.0
 Total NaN values in row 3349 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3350 :- 0 and it's percentage : 0.0
 Total NaN values in row 3351 :- 0 and it's percentage : 0.0
 Total NaN values in row 3352 :- 0 and it's percentage : 0.0
 Total NaN values in row 3353 :- 0 and it's percentage : 0.0
 Total NaN values in row 3354 :- 0 and it's percentage : 0.0
 Total NaN values in row 3355 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3356 :- 0 and it's percentage : 0.0
 Total NaN values in row 3357 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3358 :- 0 and it's percentage : 0.0
 Total NaN values in row 3359 :- 0 and it's percentage : 0.0
 Total NaN values in row 3360 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3361 :- 0 and it's percentage : 0.0
 Total NaN values in row 3362 :- 0 and it's percentage : 0.0
 Total NaN values in row 3363 :- 0 and it's percentage : 0.0
 Total NaN values in row 3364 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3365 :- 0 and it's percentage : 0.0
 Total NaN values in row 3366 :- 0 and it's percentage : 0.0
 Total NaN values in row 3367 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3369 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3370 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3371 :- 0 and it's percentage : 0.0
 Total NaN values in row 3372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3373 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3375 :- 0 and it's percentage : 0.0
 Total NaN values in row 3376 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3378 :- 0 and it's percentage : 0.0
 Total NaN values in row 3379 :- 0 and it's percentage : 0.0
 Total NaN values in row 3380 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3381 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3382 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3383 :- 0 and it's percentage : 0.0
 Total NaN values in row 3384 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3385 :- 0 and it's percentage : 0.0
 Total NaN values in row 3386 :- 0 and it's percentage : 0.0
 Total NaN values in row 3387 :- 0 and it's percentage : 0.0
 Total NaN values in row 3388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3389 :- 0 and it's percentage : 0.0
 Total NaN values in row 3390 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3391 :- 0 and it's percentage : 0.0
 Total NaN values in row 3392 :- 0 and it's percentage : 0.0
 Total NaN values in row 3393 :- 0 and it's percentage : 0.0
 Total NaN values in row 3394 :- 0 and it's percentage : 0.0
 Total NaN values in row 3395 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3397 :- 0 and it's percentage : 0.0
 Total NaN values in row 3398 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3399 :- 0 and it's percentage : 0.0
 Total NaN values in row 3400 :- 0 and it's percentage : 0.0
 Total NaN values in row 3401 :- 0 and it's percentage : 0.0
 Total NaN values in row 3402 :- 0 and it's percentage : 0.0
 Total NaN values in row 3403 :- 0 and it's percentage : 0.0
 Total NaN values in row 3404 :- 0 and it's percentage : 0.0
 Total NaN values in row 3405 :- 0 and it's percentage : 0.0
 Total NaN values in row 3406 :- 0 and it's percentage : 0.0
 Total NaN values in row 3407 :- 0 and it's percentage : 0.0
 Total NaN values in row 3408 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3409 :- 0 and it's percentage : 0.0
 Total NaN values in row 3410 :- 0 and it's percentage : 0.0
 Total NaN values in row 3411 :- 0 and it's percentage : 0.0
 Total NaN values in row 3412 :- 0 and it's percentage : 0.0
 Total NaN values in row 3413 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3414 :- 0 and it's percentage : 0.0
 Total NaN values in row 3415 :- 0 and it's percentage : 0.0
 Total NaN values in row 3416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3417 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3418 :- 0 and it's percentage : 0.0
 Total NaN values in row 3419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3420 :- 0 and it's percentage : 0.0
 Total NaN values in row 3421 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3423 :- 0 and it's percentage : 0.0
 Total NaN values in row 3424 :- 0 and it's percentage : 0.0
 Total NaN values in row 3425 :- 0 and it's percentage : 0.0
 Total NaN values in row 3426 :- 0 and it's percentage : 0.0
 Total NaN values in row 3427 :- 0 and it's percentage : 0.0
 Total NaN values in row 3428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3429 :- 0 and it's percentage : 0.0
 Total NaN values in row 3430 :- 0 and it's percentage : 0.0
 Total NaN values in row 3431 :- 0 and it's percentage : 0.0
 Total NaN values in row 3432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3433 :- 0 and it's percentage : 0.0
 Total NaN values in row 3434 :- 0 and it's percentage : 0.0
 Total NaN values in row 3435 :- 0 and it's percentage : 0.0
 Total NaN values in row 3436 :- 0 and it's percentage : 0.0
 Total NaN values in row 3437 :- 0 and it's percentage : 0.0
 Total NaN values in row 3438 :- 0 and it's percentage : 0.0
 Total NaN values in row 3439 :- 0 and it's percentage : 0.0
 Total NaN values in row 3440 :- 0 and it's percentage : 0.0
 Total NaN values in row 3441 :- 0 and it's percentage : 0.0
 Total NaN values in row 3442 :- 0 and it's percentage : 0.0
 Total NaN values in row 3443 :- 0 and it's percentage : 0.0
 Total NaN values in row 3444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3445 :- 0 and it's percentage : 0.0
 Total NaN values in row 3446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3447 :- 0 and it's percentage : 0.0
 Total NaN values in row 3448 :- 0 and it's percentage : 0.0
 Total NaN values in row 3449 :- 0 and it's percentage : 0.0
 Total NaN values in row 3450 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3451 :- 0 and it's percentage : 0.0
 Total NaN values in row 3452 :- 0 and it's percentage : 0.0
 Total NaN values in row 3453 :- 0 and it's percentage : 0.0
 Total NaN values in row 3454 :- 0 and it's percentage : 0.0
 Total NaN values in row 3455 :- 0 and it's percentage : 0.0
 Total NaN values in row 3456 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3457 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3458 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3459 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3460 :- 0 and it's percentage : 0.0
 Total NaN values in row 3461 :- 0 and it's percentage : 0.0
 Total NaN values in row 3462 :- 0 and it's percentage : 0.0
 Total NaN values in row 3463 :- 0 and it's percentage : 0.0
 Total NaN values in row 3464 :- 0 and it's percentage : 0.0
 Total NaN values in row 3465 :- 0 and it's percentage : 0.0
 Total NaN values in row 3466 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3467 :- 0 and it's percentage : 0.0
 Total NaN values in row 3468 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3469 :- 0 and it's percentage : 0.0
 Total NaN values in row 3470 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3471 :- 0 and it's percentage : 0.0
 Total NaN values in row 3472 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3473 :- 0 and it's percentage : 0.0
 Total NaN values in row 3474 :- 0 and it's percentage : 0.0
 Total NaN values in row 3475 :- 0 and it's percentage : 0.0
 Total NaN values in row 3476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3477 :- 0 and it's percentage : 0.0
 Total NaN values in row 3478 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3479 :- 0 and it's percentage : 0.0
 Total NaN values in row 3480 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3481 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3482 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3483 :- 0 and it's percentage : 0.0
 Total NaN values in row 3484 :- 0 and it's percentage : 0.0
 Total NaN values in row 3485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3486 :- 0 and it's percentage : 0.0
 Total NaN values in row 3487 :- 0 and it's percentage : 0.0
 Total NaN values in row 3488 :- 0 and it's percentage : 0.0
 Total NaN values in row 3489 :- 0 and it's percentage : 0.0
 Total NaN values in row 3490 :- 0 and it's percentage : 0.0
 Total NaN values in row 3491 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3492 :- 0 and it's percentage : 0.0
 Total NaN values in row 3493 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3494 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3495 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3496 :- 0 and it's percentage : 0.0
 Total NaN values in row 3497 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3498 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3499 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3501 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3502 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3503 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3504 :- 0 and it's percentage : 0.0
 Total NaN values in row 3505 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3506 :- 0 and it's percentage : 0.0
 Total NaN values in row 3507 :- 0 and it's percentage : 0.0
 Total NaN values in row 3508 :- 0 and it's percentage : 0.0
 Total NaN values in row 3509 :- 0 and it's percentage : 0.0
 Total NaN values in row 3510 :- 0 and it's percentage : 0.0
 Total NaN values in row 3511 :- 0 and it's percentage : 0.0
 Total NaN values in row 3512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3513 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3514 :- 0 and it's percentage : 0.0
 Total NaN values in row 3515 :- 0 and it's percentage : 0.0

 Total NaN values in row 3516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3517 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3518 :- 0 and it's percentage : 0.0
 Total NaN values in row 3519 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 3520 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3521 :- 0 and it's percentage : 0.0
 Total NaN values in row 3522 :- 0 and it's percentage : 0.0
 Total NaN values in row 3523 :- 0 and it's percentage : 0.0
 Total NaN values in row 3524 :- 0 and it's percentage : 0.0
 Total NaN values in row 3525 :- 0 and it's percentage : 0.0
 Total NaN values in row 3526 :- 0 and it's percentage : 0.0
 Total NaN values in row 3527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3528 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3529 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3530 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3531 :- 0 and it's percentage : 0.0
 Total NaN values in row 3532 :- 0 and it's percentage : 0.0
 Total NaN values in row 3533 :- 0 and it's percentage : 0.0
 Total NaN values in row 3534 :- 0 and it's percentage : 0.0
 Total NaN values in row 3535 :- 0 and it's percentage : 0.0
 Total NaN values in row 3536 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3537 :- 0 and it's percentage : 0.0
 Total NaN values in row 3538 :- 0 and it's percentage : 0.0
 Total NaN values in row 3539 :- 0 and it's percentage : 0.0
 Total NaN values in row 3540 :- 0 and it's percentage : 0.0
 Total NaN values in row 3541 :- 0 and it's percentage : 0.0
 Total NaN values in row 3542 :- 0 and it's percentage : 0.0
 Total NaN values in row 3543 :- 0 and it's percentage : 0.0
 Total NaN values in row 3544 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3545 :- 0 and it's percentage : 0.0
 Total NaN values in row 3546 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3547 :- 0 and it's percentage : 0.0
 Total NaN values in row 3548 :- 0 and it's percentage : 0.0
 Total NaN values in row 3549 :- 0 and it's percentage : 0.0
 Total NaN values in row 3550 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3551 :- 0 and it's percentage : 0.0
 Total NaN values in row 3552 :- 0 and it's percentage : 0.0
 Total NaN values in row 3553 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3554 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3555 :- 0 and it's percentage : 0.0
 Total NaN values in row 3556 :- 0 and it's percentage : 0.0
 Total NaN values in row 3557 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3558 :- 0 and it's percentage : 0.0
 Total NaN values in row 3559 :- 0 and it's percentage : 0.0
 Total NaN values in row 3560 :- 0 and it's percentage : 0.0
 Total NaN values in row 3561 :- 0 and it's percentage : 0.0
 Total NaN values in row 3562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3563 :- 0 and it's percentage : 0.0
 Total NaN values in row 3564 :- 0 and it's percentage : 0.0
 Total NaN values in row 3565 :- 0 and it's percentage : 0.0
 Total NaN values in row 3566 :- 0 and it's percentage : 0.0
 Total NaN values in row 3567 :- 0 and it's percentage : 0.0
 Total NaN values in row 3568 :- 0 and it's percentage : 0.0
 Total NaN values in row 3569 :- 0 and it's percentage : 0.0
 Total NaN values in row 3570 :- 0 and it's percentage : 0.0
 Total NaN values in row 3571 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3572 :- 0 and it's percentage : 0.0
 Total NaN values in row 3573 :- 0 and it's percentage : 0.0
 Total NaN values in row 3574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3575 :- 0 and it's percentage : 0.0
 Total NaN values in row 3576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3577 :- 0 and it's percentage : 0.0
 Total NaN values in row 3578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3580 :- 0 and it's percentage : 0.0
 Total NaN values in row 3581 :- 0 and it's percentage : 0.0
 Total NaN values in row 3582 :- 0 and it's percentage : 0.0
 Total NaN values in row 3583 :- 0 and it's percentage : 0.0
 Total NaN values in row 3584 :- 0 and it's percentage : 0.0
 Total NaN values in row 3585 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3586 :- 0 and it's percentage : 0.0
 Total NaN values in row 3587 :- 0 and it's percentage : 0.0
 Total NaN values in row 3588 :- 0 and it's percentage : 0.0
 Total NaN values in row 3589 :- 0 and it's percentage : 0.0
 Total NaN values in row 3590 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3591 :- 0 and it's percentage : 0.0
 Total NaN values in row 3592 :- 0 and it's percentage : 0.0
 Total NaN values in row 3593 :- 0 and it's percentage : 0.0
 Total NaN values in row 3594 :- 0 and it's percentage : 0.0
 Total NaN values in row 3595 :- 0 and it's percentage : 0.0
 Total NaN values in row 3596 :- 0 and it's percentage : 0.0
 Total NaN values in row 3597 :- 0 and it's percentage : 0.0
 Total NaN values in row 3598 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3600 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3601 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3602 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3603 :- 0 and it's percentage : 0.0
 Total NaN values in row 3604 :- 0 and it's percentage : 0.0
 Total NaN values in row 3605 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3606 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3607 :- 0 and it's percentage : 0.0
 Total NaN values in row 3608 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3609 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3610 :- 0 and it's percentage : 0.0
 Total NaN values in row 3611 :- 0 and it's percentage : 0.0
 Total NaN values in row 3612 :- 0 and it's percentage : 0.0
 Total NaN values in row 3613 :- 0 and it's percentage : 0.0
 Total NaN values in row 3614 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3615 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3616 :- 0 and it's percentage : 0.0
 Total NaN values in row 3617 :- 0 and it's percentage : 0.0
 Total NaN values in row 3618 :- 0 and it's percentage : 0.0
 Total NaN values in row 3619 :- 0 and it's percentage : 0.0
 Total NaN values in row 3620 :- 0 and it's percentage : 0.0
 Total NaN values in row 3621 :- 0 and it's percentage : 0.0
 Total NaN values in row 3622 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3624 :- 0 and it's percentage : 0.0
 Total NaN values in row 3625 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3626 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3627 :- 0 and it's percentage : 0.0
 Total NaN values in row 3628 :- 0 and it's percentage : 0.0
 Total NaN values in row 3629 :- 0 and it's percentage : 0.0
 Total NaN values in row 3630 :- 0 and it's percentage : 0.0
 Total NaN values in row 3631 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3632 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3633 :- 0 and it's percentage : 0.0
 Total NaN values in row 3634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3635 :- 0 and it's percentage : 0.0
 Total NaN values in row 3636 :- 0 and it's percentage : 0.0
 Total NaN values in row 3637 :- 0 and it's percentage : 0.0
 Total NaN values in row 3638 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3639 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3640 :- 0 and it's percentage : 0.0
 Total NaN values in row 3641 :- 0 and it's percentage : 0.0

 Total NaN values in row 3642 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3643 :- 0 and it's percentage : 0.0
 Total NaN values in row 3644 :- 0 and it's percentage : 0.0
 Total NaN values in row 3645 :- 0 and it's percentage : 0.0
 Total NaN values in row 3646 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3647 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3649 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3650 :- 0 and it's percentage : 0.0
 Total NaN values in row 3651 :- 0 and it's percentage : 0.0
 Total NaN values in row 3652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3653 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3654 :- 0 and it's percentage : 0.0
 Total NaN values in row 3655 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3656 :- 0 and it's percentage : 0.0
 Total NaN values in row 3657 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3658 :- 0 and it's percentage : 0.0
 Total NaN values in row 3659 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3660 :- 0 and it's percentage : 0.0
 Total NaN values in row 3661 :- 0 and it's percentage : 0.0
 Total NaN values in row 3662 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3663 :- 0 and it's percentage : 0.0
 Total NaN values in row 3664 :- 0 and it's percentage : 0.0
 Total NaN values in row 3665 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3666 :- 0 and it's percentage : 0.0
 Total NaN values in row 3667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3668 :- 0 and it's percentage : 0.0
 Total NaN values in row 3669 :- 0 and it's percentage : 0.0
 Total NaN values in row 3670 :- 0 and it's percentage : 0.0
 Total NaN values in row 3671 :- 0 and it's percentage : 0.0
 Total NaN values in row 3672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3673 :- 0 and it's percentage : 0.0
 Total NaN values in row 3674 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3675 :- 0 and it's percentage : 0.0
 Total NaN values in row 3676 :- 0 and it's percentage : 0.0
 Total NaN values in row 3677 :- 0 and it's percentage : 0.0
 Total NaN values in row 3678 :- 0 and it's percentage : 0.0
 Total NaN values in row 3679 :- 0 and it's percentage : 0.0
 Total NaN values in row 3680 :- 0 and it's percentage : 0.0
 Total NaN values in row 3681 :- 0 and it's percentage : 0.0
 Total NaN values in row 3682 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3683 :- 0 and it's percentage : 0.0
 Total NaN values in row 3684 :- 0 and it's percentage : 0.0
 Total NaN values in row 3685 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3686 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3687 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3688 :- 0 and it's percentage : 0.0
 Total NaN values in row 3689 :- 0 and it's percentage : 0.0
 Total NaN values in row 3690 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3691 :- 0 and it's percentage : 0.0
 Total NaN values in row 3692 :- 0 and it's percentage : 0.0
 Total NaN values in row 3693 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3694 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3696 :- 0 and it's percentage : 0.0
 Total NaN values in row 3697 :- 0 and it's percentage : 0.0
 Total NaN values in row 3698 :- 0 and it's percentage : 0.0
 Total NaN values in row 3699 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3700 :- 0 and it's percentage : 0.0
 Total NaN values in row 3701 :- 0 and it's percentage : 0.0
 Total NaN values in row 3702 :- 0 and it's percentage : 0.0
 Total NaN values in row 3703 :- 0 and it's percentage : 0.0
 Total NaN values in row 3704 :- 0 and it's percentage : 0.0
 Total NaN values in row 3705 :- 0 and it's percentage : 0.0
 Total NaN values in row 3706 :- 0 and it's percentage : 0.0
 Total NaN values in row 3707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3708 :- 0 and it's percentage : 0.0
 Total NaN values in row 3709 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3710 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3711 :- 0 and it's percentage : 0.0
 Total NaN values in row 3712 :- 0 and it's percentage : 0.0
 Total NaN values in row 3713 :- 0 and it's percentage : 0.0
 Total NaN values in row 3714 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3715 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3716 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3717 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3718 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3719 :- 0 and it's percentage : 0.0
 Total NaN values in row 3720 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3721 :- 0 and it's percentage : 0.0
 Total NaN values in row 3722 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3723 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3724 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3725 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3726 :- 0 and it's percentage : 0.0
 Total NaN values in row 3727 :- 0 and it's percentage : 0.0
 Total NaN values in row 3728 :- 0 and it's percentage : 0.0
 Total NaN values in row 3729 :- 0 and it's percentage : 0.0
 Total NaN values in row 3730 :- 0 and it's percentage : 0.0
 Total NaN values in row 3731 :- 0 and it's percentage : 0.0
 Total NaN values in row 3732 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3733 :- 0 and it's percentage : 0.0
 Total NaN values in row 3734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3735 :- 0 and it's percentage : 0.0
 Total NaN values in row 3736 :- 0 and it's percentage : 0.0
 Total NaN values in row 3737 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3738 :- 0 and it's percentage : 0.0
 Total NaN values in row 3739 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3740 :- 0 and it's percentage : 0.0
 Total NaN values in row 3741 :- 0 and it's percentage : 0.0
 Total NaN values in row 3742 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3744 :- 0 and it's percentage : 0.0
 Total NaN values in row 3745 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3746 :- 0 and it's percentage : 0.0
 Total NaN values in row 3747 :- 0 and it's percentage : 0.0
 Total NaN values in row 3748 :- 0 and it's percentage : 0.0
 Total NaN values in row 3749 :- 0 and it's percentage : 0.0
 Total NaN values in row 3750 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3751 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3752 :- 0 and it's percentage : 0.0
 Total NaN values in row 3753 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3754 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 3755 :- 0 and it's percentage : 0.0
 Total NaN values in row 3756 :- 0 and it's percentage : 0.0
 Total NaN values in row 3757 :- 0 and it's percentage : 0.0
 Total NaN values in row 3758 :- 0 and it's percentage : 0.0
 Total NaN values in row 3759 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3761 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3762 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3763 :- 0 and it's percentage : 0.0
 Total NaN values in row 3764 :- 0 and it's percentage : 0.0
 Total NaN values in row 3765 :- 0 and it's percentage : 0.0
 Total NaN values in row 3766 :- 0 and it's percentage : 0.0
 Total NaN values in row 3767 :- 0 and it's percentage : 0.0
 Total NaN values in row 3768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3769 :- 0 and it's percentage : 0.0
 Total NaN values in row 3770 :- 0 and it's percentage : 0.0
 Total NaN values in row 3771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3772 :- 0 and it's percentage : 0.0
 Total NaN values in row 3773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3774 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3775 :- 0 and it's percentage : 0.0
 Total NaN values in row 3776 :- 0 and it's percentage : 0.0
 Total NaN values in row 3777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3778 :- 0 and it's percentage : 0.0
 Total NaN values in row 3779 :- 0 and it's percentage : 0.0
 Total NaN values in row 3780 :- 0 and it's percentage : 0.0
 Total NaN values in row 3781 :- 0 and it's percentage : 0.0
 Total NaN values in row 3782 :- 0 and it's percentage : 0.0
 Total NaN values in row 3783 :- 0 and it's percentage : 0.0
 Total NaN values in row 3784 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3785 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3786 :- 0 and it's percentage : 0.0
 Total NaN values in row 3787 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3788 :- 0 and it's percentage : 0.0
 Total NaN values in row 3789 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3790 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3791 :- 0 and it's percentage : 0.0
 Total NaN values in row 3792 :- 0 and it's percentage : 0.0
 Total NaN values in row 3793 :- 0 and it's percentage : 0.0
 Total NaN values in row 3794 :- 0 and it's percentage : 0.0
 Total NaN values in row 3795 :- 0 and it's percentage : 0.0
 Total NaN values in row 3796 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3797 :- 0 and it's percentage : 0.0
 Total NaN values in row 3798 :- 0 and it's percentage : 0.0
 Total NaN values in row 3799 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3800 :- 0 and it's percentage : 0.0
 Total NaN values in row 3801 :- 0 and it's percentage : 0.0
 Total NaN values in row 3802 :- 0 and it's percentage : 0.0
 Total NaN values in row 3803 :- 0 and it's percentage : 0.0
 Total NaN values in row 3804 :- 0 and it's percentage : 0.0

 Total NaN values in row 3805 :- 0 and it's percentage : 0.0
 Total NaN values in row 3806 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3809 :- 0 and it's percentage : 0.0
 Total NaN values in row 3810 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3811 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3813 :- 0 and it's percentage : 0.0
 Total NaN values in row 3814 :- 0 and it's percentage : 0.0
 Total NaN values in row 3815 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3816 :- 0 and it's percentage : 0.0
 Total NaN values in row 3817 :- 0 and it's percentage : 0.0
 Total NaN values in row 3818 :- 0 and it's percentage : 0.0
 Total NaN values in row 3819 :- 0 and it's percentage : 0.0
 Total NaN values in row 3820 :- 0 and it's percentage : 0.0
 Total NaN values in row 3821 :- 0 and it's percentage : 0.0
 Total NaN values in row 3822 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3823 :- 0 and it's percentage : 0.0
 Total NaN values in row 3824 :- 0 and it's percentage : 0.0
 Total NaN values in row 3825 :- 0 and it's percentage : 0.0
 Total NaN values in row 3826 :- 0 and it's percentage : 0.0
 Total NaN values in row 3827 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3828 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3829 :- 0 and it's percentage : 0.0
 Total NaN values in row 3830 :- 0 and it's percentage : 0.0
 Total NaN values in row 3831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3832 :- 0 and it's percentage : 0.0
 Total NaN values in row 3833 :- 0 and it's percentage : 0.0
 Total NaN values in row 3834 :- 0 and it's percentage : 0.0
 Total NaN values in row 3835 :- 0 and it's percentage : 0.0
 Total NaN values in row 3836 :- 0 and it's percentage : 0.0
 Total NaN values in row 3837 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3838 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3839 :- 0 and it's percentage : 0.0
 Total NaN values in row 3840 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3841 :- 0 and it's percentage : 0.0
 Total NaN values in row 3842 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3843 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3844 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3845 :- 0 and it's percentage : 0.0
 Total NaN values in row 3846 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3847 :- 0 and it's percentage : 0.0
 Total NaN values in row 3848 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3849 :- 0 and it's percentage : 0.0
 Total NaN values in row 3850 :- 0 and it's percentage : 0.0
 Total NaN values in row 3851 :- 0 and it's percentage : 0.0
 Total NaN values in row 3852 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3853 :- 0 and it's percentage : 0.0
 Total NaN values in row 3854 :- 0 and it's percentage : 0.0
 Total NaN values in row 3855 :- 0 and it's percentage : 0.0
 Total NaN values in row 3856 :- 0 and it's percentage : 0.0
 Total NaN values in row 3857 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3858 :- 0 and it's percentage : 0.0
 Total NaN values in row 3859 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3860 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3861 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3862 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3863 :- 0 and it's percentage : 0.0
 Total NaN values in row 3864 :- 0 and it's percentage : 0.0
 Total NaN values in row 3865 :- 0 and it's percentage : 0.0
 Total NaN values in row 3866 :- 0 and it's percentage : 0.0
 Total NaN values in row 3867 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3868 :- 0 and it's percentage : 0.0
 Total NaN values in row 3869 :- 0 and it's percentage : 0.0
 Total NaN values in row 3870 :- 0 and it's percentage : 0.0
 Total NaN values in row 3871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3872 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3873 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3874 :- 0 and it's percentage : 0.0
 Total NaN values in row 3875 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3876 :- 0 and it's percentage : 0.0
 Total NaN values in row 3877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3878 :- 0 and it's percentage : 0.0
 Total NaN values in row 3879 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3880 :- 0 and it's percentage : 0.0
 Total NaN values in row 3881 :- 0 and it's percentage : 0.0
 Total NaN values in row 3882 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3884 :- 0 and it's percentage : 0.0
 Total NaN values in row 3885 :- 0 and it's percentage : 0.0
 Total NaN values in row 3886 :- 0 and it's percentage : 0.0
 Total NaN values in row 3887 :- 0 and it's percentage : 0.0
 Total NaN values in row 3888 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3889 :- 0 and it's percentage : 0.0
 Total NaN values in row 3890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3891 :- 0 and it's percentage : 0.0
 Total NaN values in row 3892 :- 0 and it's percentage : 0.0
 Total NaN values in row 3893 :- 0 and it's percentage : 0.0
 Total NaN values in row 3894 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3895 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3896 :- 0 and it's percentage : 0.0
 Total NaN values in row 3897 :- 0 and it's percentage : 0.0
 Total NaN values in row 3898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3899 :- 0 and it's percentage : 0.0
 Total NaN values in row 3900 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3901 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3902 :- 0 and it's percentage : 0.0
 Total NaN values in row 3903 :- 0 and it's percentage : 0.0
 Total NaN values in row 3904 :- 0 and it's percentage : 0.0
 Total NaN values in row 3905 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3906 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3907 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3908 :- 0 and it's percentage : 0.0
 Total NaN values in row 3909 :- 0 and it's percentage : 0.0
 Total NaN values in row 3910 :- 0 and it's percentage : 0.0
 Total NaN values in row 3911 :- 0 and it's percentage : 0.0
 Total NaN values in row 3912 :- 0 and it's percentage : 0.0
 Total NaN values in row 3913 :- 0 and it's percentage : 0.0
 Total NaN values in row 3914 :- 0 and it's percentage : 0.0
 Total NaN values in row 3915 :- 0 and it's percentage : 0.0
 Total NaN values in row 3916 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3917 :- 0 and it's percentage : 0.0
 Total NaN values in row 3918 :- 0 and it's percentage : 0.0
 Total NaN values in row 3919 :- 0 and it's percentage : 0.0
 Total NaN values in row 3920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3921 :- 0 and it's percentage : 0.0
 Total NaN values in row 3922 :- 0 and it's percentage : 0.0
 Total NaN values in row 3923 :- 0 and it's percentage : 0.0
 Total NaN values in row 3924 :- 0 and it's percentage : 0.0
 Total NaN values in row 3925 :- 0 and it's percentage : 0.0
 Total NaN values in row 3926 :- 0 and it's percentage : 0.0
 Total NaN values in row 3927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3928 :- 0 and it's percentage : 0.0
 Total NaN values in row 3929 :- 0 and it's percentage : 0.0
 Total NaN values in row 3930 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3932 :- 0 and it's percentage : 0.0
 Total NaN values in row 3933 :- 0 and it's percentage : 0.0
 Total NaN values in row 3934 :- 0 and it's percentage : 0.0
 Total NaN values in row 3935 :- 0 and it's percentage : 0.0
 Total NaN values in row 3936 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3937 :- 0 and it's percentage : 0.0
 Total NaN values in row 3938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3939 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 3940 :- 0 and it's percentage : 0.0
 Total NaN values in row 3941 :- 0 and it's percentage : 0.0
 Total NaN values in row 3942 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3943 :- 0 and it's percentage : 0.0

 Total NaN values in row 3944 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3945 :- 0 and it's percentage : 0.0
 Total NaN values in row 3946 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3947 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3948 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3949 :- 0 and it's percentage : 0.0
 Total NaN values in row 3950 :- 0 and it's percentage : 0.0
 Total NaN values in row 3951 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3952 :- 0 and it's percentage : 0.0
 Total NaN values in row 3953 :- 0 and it's percentage : 0.0
 Total NaN values in row 3954 :- 0 and it's percentage : 0.0
 Total NaN values in row 3955 :- 0 and it's percentage : 0.0
 Total NaN values in row 3956 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3957 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3958 :- 0 and it's percentage : 0.0
 Total NaN values in row 3959 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3960 :- 0 and it's percentage : 0.0
 Total NaN values in row 3961 :- 0 and it's percentage : 0.0
 Total NaN values in row 3962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3963 :- 0 and it's percentage : 0.0
 Total NaN values in row 3964 :- 0 and it's percentage : 0.0
 Total NaN values in row 3965 :- 0 and it's percentage : 0.0
 Total NaN values in row 3966 :- 0 and it's percentage : 0.0
 Total NaN values in row 3967 :- 0 and it's percentage : 0.0
 Total NaN values in row 3968 :- 0 and it's percentage : 0.0
 Total NaN values in row 3969 :- 0 and it's percentage : 0.0
 Total NaN values in row 3970 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3971 :- 0 and it's percentage : 0.0
 Total NaN values in row 3972 :- 0 and it's percentage : 0.0
 Total NaN values in row 3973 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3974 :- 0 and it's percentage : 0.0
 Total NaN values in row 3975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3976 :- 0 and it's percentage : 0.0
 Total NaN values in row 3977 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3978 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3979 :- 0 and it's percentage : 0.0
 Total NaN values in row 3980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3981 :- 0 and it's percentage : 0.0
 Total NaN values in row 3982 :- 0 and it's percentage : 0.0
 Total NaN values in row 3983 :- 0 and it's percentage : 0.0
 Total NaN values in row 3984 :- 0 and it's percentage : 0.0
 Total NaN values in row 3985 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3986 :- 0 and it's percentage : 0.0
 Total NaN values in row 3987 :- 0 and it's percentage : 0.0
 Total NaN values in row 3988 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3989 :- 0 and it's percentage : 0.0
 Total NaN values in row 3990 :- 0 and it's percentage : 0.0
 Total NaN values in row 3991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 3992 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3993 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3994 :- 0 and it's percentage : 0.0
 Total NaN values in row 3995 :- 0 and it's percentage : 0.0
 Total NaN values in row 3996 :- 0 and it's percentage : 0.0
 Total NaN values in row 3997 :- 0 and it's percentage : 0.0
 Total NaN values in row 3998 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 3999 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4000 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4001 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4002 :- 0 and it's percentage : 0.0
 Total NaN values in row 4003 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4004 :- 0 and it's percentage : 0.0
 Total NaN values in row 4005 :- 0 and it's percentage : 0.0
 Total NaN values in row 4006 :- 0 and it's percentage : 0.0
 Total NaN values in row 4007 :- 0 and it's percentage : 0.0
 Total NaN values in row 4008 :- 0 and it's percentage : 0.0
 Total NaN values in row 4009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4010 :- 0 and it's percentage : 0.0
 Total NaN values in row 4011 :- 0 and it's percentage : 0.0
 Total NaN values in row 4012 :- 0 and it's percentage : 0.0
 Total NaN values in row 4013 :- 0 and it's percentage : 0.0
 Total NaN values in row 4014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4015 :- 0 and it's percentage : 0.0
 Total NaN values in row 4016 :- 0 and it's percentage : 0.0
 Total NaN values in row 4017 :- 0 and it's percentage : 0.0
 Total NaN values in row 4018 :- 0 and it's percentage : 0.0
 Total NaN values in row 4019 :- 0 and it's percentage : 0.0
 Total NaN values in row 4020 :- 0 and it's percentage : 0.0
 Total NaN values in row 4021 :- 0 and it's percentage : 0.0
 Total NaN values in row 4022 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4023 :- 0 and it's percentage : 0.0
 Total NaN values in row 4024 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4025 :- 0 and it's percentage : 0.0
 Total NaN values in row 4026 :- 0 and it's percentage : 0.0
 Total NaN values in row 4027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4028 :- 0 and it's percentage : 0.0
 Total NaN values in row 4029 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4030 :- 0 and it's percentage : 0.0
 Total NaN values in row 4031 :- 0 and it's percentage : 0.0
 Total NaN values in row 4032 :- 0 and it's percentage : 0.0
 Total NaN values in row 4033 :- 0 and it's percentage : 0.0
 Total NaN values in row 4034 :- 0 and it's percentage : 0.0
 Total NaN values in row 4035 :- 0 and it's percentage : 0.0
 Total NaN values in row 4036 :- 0 and it's percentage : 0.0
 Total NaN values in row 4037 :- 0 and it's percentage : 0.0
 Total NaN values in row 4038 :- 0 and it's percentage : 0.0
 Total NaN values in row 4039 :- 0 and it's percentage : 0.0
 Total NaN values in row 4040 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4041 :- 0 and it's percentage : 0.0
 Total NaN values in row 4042 :- 0 and it's percentage : 0.0
 Total NaN values in row 4043 :- 0 and it's percentage : 0.0
 Total NaN values in row 4044 :- 0 and it's percentage : 0.0
 Total NaN values in row 4045 :- 0 and it's percentage : 0.0
 Total NaN values in row 4046 :- 0 and it's percentage : 0.0
 Total NaN values in row 4047 :- 0 and it's percentage : 0.0
 Total NaN values in row 4048 :- 0 and it's percentage : 0.0
 Total NaN values in row 4049 :- 0 and it's percentage : 0.0
 Total NaN values in row 4050 :- 0 and it's percentage : 0.0
 Total NaN values in row 4051 :- 0 and it's percentage : 0.0
 Total NaN values in row 4052 :- 0 and it's percentage : 0.0
 Total NaN values in row 4053 :- 0 and it's percentage : 0.0
 Total NaN values in row 4054 :- 0 and it's percentage : 0.0
 Total NaN values in row 4055 :- 0 and it's percentage : 0.0
 Total NaN values in row 4056 :- 0 and it's percentage : 0.0
 Total NaN values in row 4057 :- 0 and it's percentage : 0.0
 Total NaN values in row 4058 :- 0 and it's percentage : 0.0
 Total NaN values in row 4059 :- 0 and it's percentage : 0.0
 Total NaN values in row 4060 :- 0 and it's percentage : 0.0
 Total NaN values in row 4061 :- 0 and it's percentage : 0.0
 Total NaN values in row 4062 :- 0 and it's percentage : 0.0
 Total NaN values in row 4063 :- 0 and it's percentage : 0.0
 Total NaN values in row 4064 :- 0 and it's percentage : 0.0
 Total NaN values in row 4065 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 4066 :- 0 and it's percentage : 0.0
 Total NaN values in row 4067 :- 0 and it's percentage : 0.0
 Total NaN values in row 4068 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4070 :- 0 and it's percentage : 0.0
 Total NaN values in row 4071 :- 0 and it's percentage : 0.0
 Total NaN values in row 4072 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4073 :- 0 and it's percentage : 0.0
 Total NaN values in row 4074 :- 0 and it's percentage : 0.0
 Total NaN values in row 4075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4076 :- 0 and it's percentage : 0.0
 Total NaN values in row 4077 :- 0 and it's percentage : 0.0
 Total NaN values in row 4078 :- 0 and it's percentage : 0.0
 Total NaN values in row 4079 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4080 :- 0 and it's percentage : 0.0
 Total NaN values in row 4081 :- 0 and it's percentage : 0.0
 Total NaN values in row 4082 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4083 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4084 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4085 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4086 :- 0 and it's percentage : 0.0
 Total NaN values in row 4087 :- 0 and it's percentage : 0.0
 Total NaN values in row 4088 :- 0 and it's percentage : 0.0
 Total NaN values in row 4089 :- 0 and it's percentage : 0.0
 Total NaN values in row 4090 :- 0 and it's percentage : 0.0
 Total NaN values in row 4091 :- 0 and it's percentage : 0.0
 Total NaN values in row 4092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4093 :- 0 and it's percentage : 0.0
 Total NaN values in row 4094 :- 0 and it's percentage : 0.0
 Total NaN values in row 4095 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4096 :- 0 and it's percentage : 0.0
 Total NaN values in row 4097 :- 0 and it's percentage : 0.0
 Total NaN values in row 4098 :- 0 and it's percentage : 0.0
 Total NaN values in row 4099 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4100 :- 0 and it's percentage : 0.0
 Total NaN values in row 4101 :- 0 and it's percentage : 0.0
 Total NaN values in row 4102 :- 0 and it's percentage : 0.0
 Total NaN values in row 4103 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4104 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4105 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4106 :- 0 and it's percentage : 0.0
 Total NaN values in row 4107 :- 0 and it's percentage : 0.0
 Total NaN values in row 4108 :- 0 and it's percentage : 0.0
 Total NaN values in row 4109 :- 0 and it's percentage : 0.0
 Total NaN values in row 4110 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 4111 :- 0 and it's percentage : 0.0
 Total NaN values in row 4112 :- 0 and it's percentage : 0.0
 Total NaN values in row 4113 :- 0 and it's percentage : 0.0
 Total NaN values in row 4114 :- 0 and it's percentage : 0.0
 Total NaN values in row 4115 :- 0 and it's percentage : 0.0
 Total NaN values in row 4116 :- 0 and it's percentage : 0.0
 Total NaN values in row 4117 :- 0 and it's percentage : 0.0
 Total NaN values in row 4118 :- 0 and it's percentage : 0.0
 Total NaN values in row 4119 :- 0 and it's percentage : 0.0
 Total NaN values in row 4120 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4122 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4123 :- 0 and it's percentage : 0.0
 Total NaN values in row 4124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4125 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4126 :- 0 and it's percentage : 0.0
 Total NaN values in row 4127 :- 0 and it's percentage : 0.0
 Total NaN values in row 4128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4129 :- 0 and it's percentage : 0.0
 Total NaN values in row 4130 :- 0 and it's percentage : 0.0
 Total NaN values in row 4131 :- 0 and it's percentage : 0.0
 Total NaN values in row 4132 :- 0 and it's percentage : 0.0
 Total NaN values in row 4133 :- 0 and it's percentage : 0.0
 Total NaN values in row 4134 :- 0 and it's percentage : 0.0
 Total NaN values in row 4135 :- 0 and it's percentage : 0.0
 Total NaN values in row 4136 :- 0 and it's percentage : 0.0
 Total NaN values in row 4137 :- 0 and it's percentage : 0.0
 Total NaN values in row 4138 :- 0 and it's percentage : 0.0
 Total NaN values in row 4139 :- 0 and it's percentage : 0.0
 Total NaN values in row 4140 :- 0 and it's percentage : 0.0
 Total NaN values in row 4141 :- 0 and it's percentage : 0.0
 Total NaN values in row 4142 :- 0 and it's percentage : 0.0
 Total NaN values in row 4143 :- 0 and it's percentage : 0.0
 Total NaN values in row 4144 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4145 :- 0 and it's percentage : 0.0
 Total NaN values in row 4146 :- 0 and it's percentage : 0.0
 Total NaN values in row 4147 :- 0 and it's percentage : 0.0
 Total NaN values in row 4148 :- 0 and it's percentage : 0.0
 Total NaN values in row 4149 :- 0 and it's percentage : 0.0
 Total NaN values in row 4150 :- 0 and it's percentage : 0.0
 Total NaN values in row 4151 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4152 :- 0 and it's percentage : 0.0
 Total NaN values in row 4153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4154 :- 0 and it's percentage : 0.0
 Total NaN values in row 4155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4156 :- 0 and it's percentage : 0.0
 Total NaN values in row 4157 :- 0 and it's percentage : 0.0
 Total NaN values in row 4158 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4159 :- 0 and it's percentage : 0.0
 Total NaN values in row 4160 :- 0 and it's percentage : 0.0
 Total NaN values in row 4161 :- 0 and it's percentage : 0.0
 Total NaN values in row 4162 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4163 :- 0 and it's percentage : 0.0
 Total NaN values in row 4164 :- 0 and it's percentage : 0.0
 Total NaN values in row 4165 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4166 :- 0 and it's percentage : 0.0
 Total NaN values in row 4167 :- 0 and it's percentage : 0.0
 Total NaN values in row 4168 :- 0 and it's percentage : 0.0
 Total NaN values in row 4169 :- 0 and it's percentage : 0.0
 Total NaN values in row 4170 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4171 :- 0 and it's percentage : 0.0
 Total NaN values in row 4172 :- 0 and it's percentage : 0.0
 Total NaN values in row 4173 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4174 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4175 :- 0 and it's percentage : 0.0
 Total NaN values in row 4176 :- 0 and it's percentage : 0.0
 Total NaN values in row 4177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4178 :- 0 and it's percentage : 0.0
 Total NaN values in row 4179 :- 0 and it's percentage : 0.0
 Total NaN values in row 4180 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4182 :- 0 and it's percentage : 0.0
 Total NaN values in row 4183 :- 0 and it's percentage : 0.0
 Total NaN values in row 4184 :- 0 and it's percentage : 0.0
 Total NaN values in row 4185 :- 0 and it's percentage : 0.0
 Total NaN values in row 4186 :- 0 and it's percentage : 0.0
 Total NaN values in row 4187 :- 0 and it's percentage : 0.0
 Total NaN values in row 4188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4189 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4190 :- 0 and it's percentage : 0.0
 Total NaN values in row 4191 :- 0 and it's percentage : 0.0
 Total NaN values in row 4192 :- 0 and it's percentage : 0.0
 Total NaN values in row 4193 :- 0 and it's percentage : 0.0
 Total NaN values in row 4194 :- 0 and it's percentage : 0.0
 Total NaN values in row 4195 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4196 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4197 :- 0 and it's percentage : 0.0
 Total NaN values in row 4198 :- 0 and it's percentage : 0.0
 Total NaN values in row 4199 :- 0 and it's percentage : 0.0
 Total NaN values in row 4200 :- 0 and it's percentage : 0.0
 Total NaN values in row 4201 :- 0 and it's percentage : 0.0
 Total NaN values in row 4202 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4204 :- 0 and it's percentage : 0.0
 Total NaN values in row 4205 :- 0 and it's percentage : 0.0
 Total NaN values in row 4206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4207 :- 0 and it's percentage : 0.0
 Total NaN values in row 4208 :- 0 and it's percentage : 0.0
 Total NaN values in row 4209 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4210 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4211 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4212 :- 0 and it's percentage : 0.0
 Total NaN values in row 4213 :- 0 and it's percentage : 0.0
 Total NaN values in row 4214 :- 0 and it's percentage : 0.0
 Total NaN values in row 4215 :- 0 and it's percentage : 0.0
 Total NaN values in row 4216 :- 0 and it's percentage : 0.0
 Total NaN values in row 4217 :- 0 and it's percentage : 0.0
 Total NaN values in row 4218 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4219 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4220 :- 0 and it's percentage : 0.0
 Total NaN values in row 4221 :- 0 and it's percentage : 0.0
 Total NaN values in row 4222 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4223 :- 0 and it's percentage : 0.0
 Total NaN values in row 4224 :- 0 and it's percentage : 0.0
 Total NaN values in row 4225 :- 0 and it's percentage : 0.0
 Total NaN values in row 4226 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4227 :- 0 and it's percentage : 0.0
 Total NaN values in row 4228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4229 :- 0 and it's percentage : 0.0
 Total NaN values in row 4230 :- 0 and it's percentage : 0.0
 Total NaN values in row 4231 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4232 :- 0 and it's percentage : 0.0
 Total NaN values in row 4233 :- 0 and it's percentage : 0.0
 Total NaN values in row 4234 :- 0 and it's percentage : 0.0
 Total NaN values in row 4235 :- 0 and it's percentage : 0.0
 Total NaN values in row 4236 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4237 :- 0 and it's percentage : 0.0
 Total NaN values in row 4238 :- 0 and it's percentage : 0.0

 Total NaN values in row 4239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4240 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4241 :- 0 and it's percentage : 0.0
 Total NaN values in row 4242 :- 0 and it's percentage : 0.0
 Total NaN values in row 4243 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4244 :- 0 and it's percentage : 0.0
 Total NaN values in row 4245 :- 0 and it's percentage : 0.0
 Total NaN values in row 4246 :- 0 and it's percentage : 0.0
 Total NaN values in row 4247 :- 0 and it's percentage : 0.0
 Total NaN values in row 4248 :- 0 and it's percentage : 0.0
 Total NaN values in row 4249 :- 0 and it's percentage : 0.0
 Total NaN values in row 4250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4251 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4252 :- 0 and it's percentage : 0.0
 Total NaN values in row 4253 :- 0 and it's percentage : 0.0
 Total NaN values in row 4254 :- 0 and it's percentage : 0.0
 Total NaN values in row 4255 :- 0 and it's percentage : 0.0
 Total NaN values in row 4256 :- 0 and it's percentage : 0.0
 Total NaN values in row 4257 :- 0 and it's percentage : 0.0
 Total NaN values in row 4258 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4259 :- 0 and it's percentage : 0.0
 Total NaN values in row 4260 :- 0 and it's percentage : 0.0
 Total NaN values in row 4261 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4262 :- 0 and it's percentage : 0.0
 Total NaN values in row 4263 :- 0 and it's percentage : 0.0
 Total NaN values in row 4264 :- 0 and it's percentage : 0.0
 Total NaN values in row 4265 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4266 :- 0 and it's percentage : 0.0
 Total NaN values in row 4267 :- 0 and it's percentage : 0.0
 Total NaN values in row 4268 :- 0 and it's percentage : 0.0
 Total NaN values in row 4269 :- 0 and it's percentage : 0.0
 Total NaN values in row 4270 :- 0 and it's percentage : 0.0
 Total NaN values in row 4271 :- 0 and it's percentage : 0.0
 Total NaN values in row 4272 :- 0 and it's percentage : 0.0
 Total NaN values in row 4273 :- 0 and it's percentage : 0.0
 Total NaN values in row 4274 :- 0 and it's percentage : 0.0
 Total NaN values in row 4275 :- 0 and it's percentage : 0.0
 Total NaN values in row 4276 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4277 :- 0 and it's percentage : 0.0
 Total NaN values in row 4278 :- 0 and it's percentage : 0.0
 Total NaN values in row 4279 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4280 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4281 :- 0 and it's percentage : 0.0
 Total NaN values in row 4282 :- 0 and it's percentage : 0.0
 Total NaN values in row 4283 :- 0 and it's percentage : 0.0
 Total NaN values in row 4284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4285 :- 0 and it's percentage : 0.0
 Total NaN values in row 4286 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4287 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4288 :- 0 and it's percentage : 0.0
 Total NaN values in row 4289 :- 0 and it's percentage : 0.0
 Total NaN values in row 4290 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4291 :- 0 and it's percentage : 0.0
 Total NaN values in row 4292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4293 :- 0 and it's percentage : 0.0
 Total NaN values in row 4294 :- 0 and it's percentage : 0.0
 Total NaN values in row 4295 :- 0 and it's percentage : 0.0
 Total NaN values in row 4296 :- 0 and it's percentage : 0.0
 Total NaN values in row 4297 :- 0 and it's percentage : 0.0
 Total NaN values in row 4298 :- 0 and it's percentage : 0.0
 Total NaN values in row 4299 :- 0 and it's percentage : 0.0
 Total NaN values in row 4300 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4301 :- 0 and it's percentage : 0.0
 Total NaN values in row 4302 :- 0 and it's percentage : 0.0
 Total NaN values in row 4303 :- 0 and it's percentage : 0.0
 Total NaN values in row 4304 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4305 :- 0 and it's percentage : 0.0
 Total NaN values in row 4306 :- 0 and it's percentage : 0.0
 Total NaN values in row 4307 :- 0 and it's percentage : 0.0
 Total NaN values in row 4308 :- 0 and it's percentage : 0.0
 Total NaN values in row 4309 :- 0 and it's percentage : 0.0
 Total NaN values in row 4310 :- 0 and it's percentage : 0.0
 Total NaN values in row 4311 :- 0 and it's percentage : 0.0
 Total NaN values in row 4312 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4313 :- 0 and it's percentage : 0.0
 Total NaN values in row 4314 :- 0 and it's percentage : 0.0
 Total NaN values in row 4315 :- 0 and it's percentage : 0.0
 Total NaN values in row 4316 :- 0 and it's percentage : 0.0
 Total NaN values in row 4317 :- 0 and it's percentage : 0.0
 Total NaN values in row 4318 :- 0 and it's percentage : 0.0
 Total NaN values in row 4319 :- 0 and it's percentage : 0.0
 Total NaN values in row 4320 :- 0 and it's percentage : 0.0
 Total NaN values in row 4321 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 4322 :- 0 and it's percentage : 0.0
 Total NaN values in row 4323 :- 0 and it's percentage : 0.0
 Total NaN values in row 4324 :- 0 and it's percentage : 0.0
 Total NaN values in row 4325 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4326 :- 0 and it's percentage : 0.0
 Total NaN values in row 4327 :- 0 and it's percentage : 0.0
 Total NaN values in row 4328 :- 0 and it's percentage : 0.0
 Total NaN values in row 4329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4331 :- 0 and it's percentage : 0.0
 Total NaN values in row 4332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4333 :- 0 and it's percentage : 0.0
 Total NaN values in row 4334 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4335 :- 0 and it's percentage : 0.0
 Total NaN values in row 4336 :- 0 and it's percentage : 0.0
 Total NaN values in row 4337 :- 0 and it's percentage : 0.0
 Total NaN values in row 4338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4339 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4340 :- 0 and it's percentage : 0.0
 Total NaN values in row 4341 :- 0 and it's percentage : 0.0
 Total NaN values in row 4342 :- 0 and it's percentage : 0.0
 Total NaN values in row 4343 :- 0 and it's percentage : 0.0
 Total NaN values in row 4344 :- 0 and it's percentage : 0.0
 Total NaN values in row 4345 :- 0 and it's percentage : 0.0
 Total NaN values in row 4346 :- 0 and it's percentage : 0.0
 Total NaN values in row 4347 :- 0 and it's percentage : 0.0
 Total NaN values in row 4348 :- 0 and it's percentage : 0.0
 Total NaN values in row 4349 :- 0 and it's percentage : 0.0
 Total NaN values in row 4350 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4352 :- 0 and it's percentage : 0.0
 Total NaN values in row 4353 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4354 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4355 :- 0 and it's percentage : 0.0
 Total NaN values in row 4356 :- 0 and it's percentage : 0.0
 Total NaN values in row 4357 :- 0 and it's percentage : 0.0
 Total NaN values in row 4358 :- 0 and it's percentage : 0.0
 Total NaN values in row 4359 :- 0 and it's percentage : 0.0
 Total NaN values in row 4360 :- 0 and it's percentage : 0.0
 Total NaN values in row 4361 :- 0 and it's percentage : 0.0
 Total NaN values in row 4362 :- 0 and it's percentage : 0.0
 Total NaN values in row 4363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4364 :- 0 and it's percentage : 0.0
 Total NaN values in row 4365 :- 0 and it's percentage : 0.0
 Total NaN values in row 4366 :- 0 and it's percentage : 0.0
 Total NaN values in row 4367 :- 0 and it's percentage : 0.0
 Total NaN values in row 4368 :- 0 and it's percentage : 0.0
 Total NaN values in row 4369 :- 0 and it's percentage : 0.0
 Total NaN values in row 4370 :- 0 and it's percentage : 0.0
 Total NaN values in row 4371 :- 0 and it's percentage : 0.0
 Total NaN values in row 4372 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4373 :- 0 and it's percentage : 0.0
 Total NaN values in row 4374 :- 0 and it's percentage : 0.0
 Total NaN values in row 4375 :- 0 and it's percentage : 0.0
 Total NaN values in row 4376 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4378 :- 0 and it's percentage : 0.0
 Total NaN values in row 4379 :- 0 and it's percentage : 0.0
 Total NaN values in row 4380 :- 0 and it's percentage : 0.0
 Total NaN values in row 4381 :- 0 and it's percentage : 0.0
 Total NaN values in row 4382 :- 0 and it's percentage : 0.0
 Total NaN values in row 4383 :- 0 and it's percentage : 0.0
 Total NaN values in row 4384 :- 0 and it's percentage : 0.0
 Total NaN values in row 4385 :- 0 and it's percentage : 0.0
 Total NaN values in row 4386 :- 0 and it's percentage : 0.0
 Total NaN values in row 4387 :- 0 and it's percentage : 0.0
 Total NaN values in row 4388 :- 0 and it's percentage : 0.0
 Total NaN values in row 4389 :- 0 and it's percentage : 0.0
 Total NaN values in row 4390 :- 0 and it's percentage : 0.0
 Total NaN values in row 4391 :- 0 and it's percentage : 0.0
 Total NaN values in row 4392 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4393 :- 0 and it's percentage : 0.0
 Total NaN values in row 4394 :- 0 and it's percentage : 0.0
 Total NaN values in row 4395 :- 0 and it's percentage : 0.0
 Total NaN values in row 4396 :- 0 and it's percentage : 0.0
 Total NaN values in row 4397 :- 0 and it's percentage : 0.0
 Total NaN values in row 4398 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 4399 :- 0 and it's percentage : 0.0
 Total NaN values in row 4400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4401 :- 0 and it's percentage : 0.0
 Total NaN values in row 4402 :- 0 and it's percentage : 0.0
 Total NaN values in row 4403 :- 0 and it's percentage : 0.0
 Total NaN values in row 4404 :- 0 and it's percentage : 0.0
 Total NaN values in row 4405 :- 0 and it's percentage : 0.0
 Total NaN values in row 4406 :- 0 and it's percentage : 0.0
 Total NaN values in row 4407 :- 0 and it's percentage : 0.0
 Total NaN values in row 4408 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4409 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4410 :- 0 and it's percentage : 0.0
 Total NaN values in row 4411 :- 0 and it's percentage : 0.0

 Total NaN values in row 4412 :- 0 and it's percentage : 0.0
 Total NaN values in row 4413 :- 0 and it's percentage : 0.0
 Total NaN values in row 4414 :- 0 and it's percentage : 0.0
 Total NaN values in row 4415 :- 0 and it's percentage : 0.0
 Total NaN values in row 4416 :- 0 and it's percentage : 0.0
 Total NaN values in row 4417 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4418 :- 0 and it's percentage : 0.0
 Total NaN values in row 4419 :- 0 and it's percentage : 0.0
 Total NaN values in row 4420 :- 0 and it's percentage : 0.0
 Total NaN values in row 4421 :- 0 and it's percentage : 0.0
 Total NaN values in row 4422 :- 0 and it's percentage : 0.0
 Total NaN values in row 4423 :- 0 and it's percentage : 0.0
 Total NaN values in row 4424 :- 0 and it's percentage : 0.0
 Total NaN values in row 4425 :- 0 and it's percentage : 0.0
 Total NaN values in row 4426 :- 0 and it's percentage : 0.0
 Total NaN values in row 4427 :- 0 and it's percentage : 0.0
 Total NaN values in row 4428 :- 0 and it's percentage : 0.0
 Total NaN values in row 4429 :- 0 and it's percentage : 0.0
 Total NaN values in row 4430 :- 0 and it's percentage : 0.0
 Total NaN values in row 4431 :- 0 and it's percentage : 0.0
 Total NaN values in row 4432 :- 0 and it's percentage : 0.0
 Total NaN values in row 4433 :- 0 and it's percentage : 0.0
 Total NaN values in row 4434 :- 0 and it's percentage : 0.0
 Total NaN values in row 4435 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4436 :- 0 and it's percentage : 0.0
 Total NaN values in row 4437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4438 :- 0 and it's percentage : 0.0
 Total NaN values in row 4439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4440 :- 0 and it's percentage : 0.0
 Total NaN values in row 4441 :- 0 and it's percentage : 0.0
 Total NaN values in row 4442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4443 :- 0 and it's percentage : 0.0
 Total NaN values in row 4444 :- 0 and it's percentage : 0.0
 Total NaN values in row 4445 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4446 :- 0 and it's percentage : 0.0
 Total NaN values in row 4447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4448 :- 0 and it's percentage : 0.0
 Total NaN values in row 4449 :- 0 and it's percentage : 0.0
 Total NaN values in row 4450 :- 0 and it's percentage : 0.0
 Total NaN values in row 4451 :- 0 and it's percentage : 0.0
 Total NaN values in row 4452 :- 0 and it's percentage : 0.0
 Total NaN values in row 4453 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4454 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4456 :- 0 and it's percentage : 0.0
 Total NaN values in row 4457 :- 0 and it's percentage : 0.0
 Total NaN values in row 4458 :- 0 and it's percentage : 0.0
 Total NaN values in row 4459 :- 0 and it's percentage : 0.0
 Total NaN values in row 4460 :- 0 and it's percentage : 0.0
 Total NaN values in row 4461 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4462 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4463 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4464 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4465 :- 0 and it's percentage : 0.0
 Total NaN values in row 4466 :- 0 and it's percentage : 0.0
 Total NaN values in row 4467 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4468 :- 0 and it's percentage : 0.0
 Total NaN values in row 4469 :- 0 and it's percentage : 0.0
 Total NaN values in row 4470 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4471 :- 0 and it's percentage : 0.0
 Total NaN values in row 4472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4473 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 4474 :- 0 and it's percentage : 0.0
 Total NaN values in row 4475 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4477 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4478 :- 0 and it's percentage : 0.0
 Total NaN values in row 4479 :- 0 and it's percentage : 0.0
 Total NaN values in row 4480 :- 0 and it's percentage : 0.0
 Total NaN values in row 4481 :- 0 and it's percentage : 0.0
 Total NaN values in row 4482 :- 0 and it's percentage : 0.0
 Total NaN values in row 4483 :- 0 and it's percentage : 0.0
 Total NaN values in row 4484 :- 0 and it's percentage : 0.0
 Total NaN values in row 4485 :- 0 and it's percentage : 0.0
 Total NaN values in row 4486 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 4487 :- 0 and it's percentage : 0.0
 Total NaN values in row 4488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4489 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4490 :- 0 and it's percentage : 0.0
 Total NaN values in row 4491 :- 0 and it's percentage : 0.0
 Total NaN values in row 4492 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4493 :- 0 and it's percentage : 0.0
 Total NaN values in row 4494 :- 0 and it's percentage : 0.0
 Total NaN values in row 4495 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4496 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4497 :- 0 and it's percentage : 0.0
 Total NaN values in row 4498 :- 0 and it's percentage : 0.0
 Total NaN values in row 4499 :- 0 and it's percentage : 0.0
 Total NaN values in row 4500 :- 0 and it's percentage : 0.0
 Total NaN values in row 4501 :- 0 and it's percentage : 0.0
 Total NaN values in row 4502 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4503 :- 0 and it's percentage : 0.0
 Total NaN values in row 4504 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4505 :- 0 and it's percentage : 0.0
 Total NaN values in row 4506 :- 0 and it's percentage : 0.0
 Total NaN values in row 4507 :- 0 and it's percentage : 0.0
 Total NaN values in row 4508 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4509 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4510 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4511 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4513 :- 0 and it's percentage : 0.0
 Total NaN values in row 4514 :- 0 and it's percentage : 0.0
 Total NaN values in row 4515 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4516 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4517 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4518 :- 0 and it's percentage : 0.0
 Total NaN values in row 4519 :- 0 and it's percentage : 0.0
 Total NaN values in row 4520 :- 0 and it's percentage : 0.0
 Total NaN values in row 4521 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4522 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4523 :- 0 and it's percentage : 0.0
 Total NaN values in row 4524 :- 0 and it's percentage : 0.0
 Total NaN values in row 4525 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4528 :- 0 and it's percentage : 0.0
 Total NaN values in row 4529 :- 0 and it's percentage : 0.0
 Total NaN values in row 4530 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4531 :- 0 and it's percentage : 0.0
 Total NaN values in row 4532 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4534 :- 0 and it's percentage : 0.0
 Total NaN values in row 4535 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4536 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4537 :- 0 and it's percentage : 0.0

 Total NaN values in row 4538 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4539 :- 0 and it's percentage : 0.0
 Total NaN values in row 4540 :- 0 and it's percentage : 0.0
 Total NaN values in row 4541 :- 0 and it's percentage : 0.0
 Total NaN values in row 4542 :- 0 and it's percentage : 0.0
 Total NaN values in row 4543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4544 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4545 :- 0 and it's percentage : 0.0
 Total NaN values in row 4546 :- 0 and it's percentage : 0.0
 Total NaN values in row 4547 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4549 :- 0 and it's percentage : 0.0
 Total NaN values in row 4550 :- 0 and it's percentage : 0.0
 Total NaN values in row 4551 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4552 :- 0 and it's percentage : 0.0
 Total NaN values in row 4553 :- 0 and it's percentage : 0.0
 Total NaN values in row 4554 :- 0 and it's percentage : 0.0
 Total NaN values in row 4555 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4556 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4557 :- 0 and it's percentage : 0.0
 Total NaN values in row 4558 :- 0 and it's percentage : 0.0
 Total NaN values in row 4559 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4560 :- 0 and it's percentage : 0.0
 Total NaN values in row 4561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4562 :- 0 and it's percentage : 0.0
 Total NaN values in row 4563 :- 0 and it's percentage : 0.0
 Total NaN values in row 4564 :- 0 and it's percentage : 0.0
 Total NaN values in row 4565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4566 :- 0 and it's percentage : 0.0
 Total NaN values in row 4567 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4568 :- 0 and it's percentage : 0.0
 Total NaN values in row 4569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4570 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4571 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4572 :- 0 and it's percentage : 0.0
 Total NaN values in row 4573 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4575 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4576 :- 0 and it's percentage : 0.0
 Total NaN values in row 4577 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4579 :- 0 and it's percentage : 0.0
 Total NaN values in row 4580 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4581 :- 0 and it's percentage : 0.0
 Total NaN values in row 4582 :- 0 and it's percentage : 0.0
 Total NaN values in row 4583 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4584 :- 0 and it's percentage : 0.0
 Total NaN values in row 4585 :- 0 and it's percentage : 0.0
 Total NaN values in row 4586 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4587 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4588 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4589 :- 0 and it's percentage : 0.0
 Total NaN values in row 4590 :- 0 and it's percentage : 0.0
 Total NaN values in row 4591 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4592 :- 0 and it's percentage : 0.0
 Total NaN values in row 4593 :- 0 and it's percentage : 0.0
 Total NaN values in row 4594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4595 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4596 :- 0 and it's percentage : 0.0
 Total NaN values in row 4597 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4598 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4600 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4601 :- 0 and it's percentage : 0.0
 Total NaN values in row 4602 :- 0 and it's percentage : 0.0
 Total NaN values in row 4603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4604 :- 0 and it's percentage : 0.0
 Total NaN values in row 4605 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4606 :- 0 and it's percentage : 0.0
 Total NaN values in row 4607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4608 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4609 :- 0 and it's percentage : 0.0
 Total NaN values in row 4610 :- 0 and it's percentage : 0.0
 Total NaN values in row 4611 :- 0 and it's percentage : 0.0
 Total NaN values in row 4612 :- 0 and it's percentage : 0.0
 Total NaN values in row 4613 :- 0 and it's percentage : 0.0
 Total NaN values in row 4614 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4615 :- 0 and it's percentage : 0.0
 Total NaN values in row 4616 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4617 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4618 :- 0 and it's percentage : 0.0
 Total NaN values in row 4619 :- 0 and it's percentage : 0.0
 Total NaN values in row 4620 :- 0 and it's percentage : 0.0
 Total NaN values in row 4621 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4622 :- 0 and it's percentage : 0.0
 Total NaN values in row 4623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4624 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4625 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4626 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4627 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4628 :- 0 and it's percentage : 0.0
 Total NaN values in row 4629 :- 0 and it's percentage : 0.0
 Total NaN values in row 4630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4631 :- 0 and it's percentage : 0.0
 Total NaN values in row 4632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4633 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4635 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4636 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4637 :- 0 and it's percentage : 0.0
 Total NaN values in row 4638 :- 0 and it's percentage : 0.0
 Total NaN values in row 4639 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4640 :- 0 and it's percentage : 0.0
 Total NaN values in row 4641 :- 0 and it's percentage : 0.0
 Total NaN values in row 4642 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4643 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4644 :- 0 and it's percentage : 0.0
 Total NaN values in row 4645 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4646 :- 0 and it's percentage : 0.0
 Total NaN values in row 4647 :- 0 and it's percentage : 0.0
 Total NaN values in row 4648 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 4649 :- 0 and it's percentage : 0.0
 Total NaN values in row 4650 :- 0 and it's percentage : 0.0
 Total NaN values in row 4651 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4652 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4653 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4654 :- 0 and it's percentage : 0.0
 Total NaN values in row 4655 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4656 :- 0 and it's percentage : 0.0
 Total NaN values in row 4657 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4658 :- 0 and it's percentage : 0.0
 Total NaN values in row 4659 :- 0 and it's percentage : 0.0
 Total NaN values in row 4660 :- 0 and it's percentage : 0.0
 Total NaN values in row 4661 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4664 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4665 :- 0 and it's percentage : 0.0
 Total NaN values in row 4666 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4667 :- 0 and it's percentage : 0.0
 Total NaN values in row 4668 :- 0 and it's percentage : 0.0
 Total NaN values in row 4669 :- 0 and it's percentage : 0.0
 Total NaN values in row 4670 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4672 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4673 :- 0 and it's percentage : 0.0
 Total NaN values in row 4674 :- 0 and it's percentage : 0.0
 Total NaN values in row 4675 :- 0 and it's percentage : 0.0
 Total NaN values in row 4676 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4677 :- 0 and it's percentage : 0.0
 Total NaN values in row 4678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4679 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4681 :- 0 and it's percentage : 0.0
 Total NaN values in row 4682 :- 0 and it's percentage : 0.0
 Total NaN values in row 4683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4684 :- 0 and it's percentage : 0.0
 Total NaN values in row 4685 :- 0 and it's percentage : 0.0
 Total NaN values in row 4686 :- 0 and it's percentage : 0.0
 Total NaN values in row 4687 :- 0 and it's percentage : 0.0
 Total NaN values in row 4688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4689 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4690 :- 0 and it's percentage : 0.0
 Total NaN values in row 4691 :- 0 and it's percentage : 0.0

 Total NaN values in row 4692 :- 0 and it's percentage : 0.0
 Total NaN values in row 4693 :- 0 and it's percentage : 0.0
 Total NaN values in row 4694 :- 0 and it's percentage : 0.0
 Total NaN values in row 4695 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4696 :- 0 and it's percentage : 0.0
 Total NaN values in row 4697 :- 0 and it's percentage : 0.0
 Total NaN values in row 4698 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4699 :- 0 and it's percentage : 0.0
 Total NaN values in row 4700 :- 0 and it's percentage : 0.0
 Total NaN values in row 4701 :- 0 and it's percentage : 0.0
 Total NaN values in row 4702 :- 0 and it's percentage : 0.0
 Total NaN values in row 4703 :- 0 and it's percentage : 0.0
 Total NaN values in row 4704 :- 0 and it's percentage : 0.0
 Total NaN values in row 4705 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4706 :- 0 and it's percentage : 0.0
 Total NaN values in row 4707 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4708 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4709 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4710 :- 0 and it's percentage : 0.0
 Total NaN values in row 4711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4713 :- 0 and it's percentage : 0.0
 Total NaN values in row 4714 :- 0 and it's percentage : 0.0
 Total NaN values in row 4715 :- 0 and it's percentage : 0.0
 Total NaN values in row 4716 :- 0 and it's percentage : 0.0
 Total NaN values in row 4717 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4718 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4719 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4720 :- 0 and it's percentage : 0.0
 Total NaN values in row 4721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4722 :- 0 and it's percentage : 0.0
 Total NaN values in row 4723 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4724 :- 0 and it's percentage : 0.0
 Total NaN values in row 4725 :- 0 and it's percentage : 0.0
 Total NaN values in row 4726 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4727 :- 0 and it's percentage : 0.0
 Total NaN values in row 4728 :- 0 and it's percentage : 0.0
 Total NaN values in row 4729 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4730 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4731 :- 0 and it's percentage : 0.0
 Total NaN values in row 4732 :- 0 and it's percentage : 0.0
 Total NaN values in row 4733 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4734 :- 0 and it's percentage : 0.0
 Total NaN values in row 4735 :- 0 and it's percentage : 0.0
 Total NaN values in row 4736 :- 0 and it's percentage : 0.0
 Total NaN values in row 4737 :- 0 and it's percentage : 0.0
 Total NaN values in row 4738 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4739 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4740 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4741 :- 0 and it's percentage : 0.0
 Total NaN values in row 4742 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4743 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4744 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4745 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4746 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4747 :- 0 and it's percentage : 0.0
 Total NaN values in row 4748 :- 0 and it's percentage : 0.0
 Total NaN values in row 4749 :- 0 and it's percentage : 0.0
 Total NaN values in row 4750 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4751 :- 0 and it's percentage : 0.0
 Total NaN values in row 4752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4753 :- 0 and it's percentage : 0.0
 Total NaN values in row 4754 :- 0 and it's percentage : 0.0
 Total NaN values in row 4755 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4756 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4757 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4758 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4759 :- 0 and it's percentage : 0.0
 Total NaN values in row 4760 :- 0 and it's percentage : 0.0
 Total NaN values in row 4761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4762 :- 0 and it's percentage : 0.0
 Total NaN values in row 4763 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4764 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4765 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4766 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4767 :- 0 and it's percentage : 0.0
 Total NaN values in row 4768 :- 0 and it's percentage : 0.0
 Total NaN values in row 4769 :- 0 and it's percentage : 0.0
 Total NaN values in row 4770 :- 0 and it's percentage : 0.0
 Total NaN values in row 4771 :- 0 and it's percentage : 0.0
 Total NaN values in row 4772 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4773 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4774 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4775 :- 0 and it's percentage : 0.0
 Total NaN values in row 4776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4777 :- 0 and it's percentage : 0.0
 Total NaN values in row 4778 :- 0 and it's percentage : 0.0
 Total NaN values in row 4779 :- 0 and it's percentage : 0.0
 Total NaN values in row 4780 :- 0 and it's percentage : 0.0
 Total NaN values in row 4781 :- 0 and it's percentage : 0.0
 Total NaN values in row 4782 :- 0 and it's percentage : 0.0
 Total NaN values in row 4783 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4784 :- 0 and it's percentage : 0.0
 Total NaN values in row 4785 :- 0 and it's percentage : 0.0
 Total NaN values in row 4786 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4787 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4788 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4789 :- 0 and it's percentage : 0.0
 Total NaN values in row 4790 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4791 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4792 :- 0 and it's percentage : 0.0
 Total NaN values in row 4793 :- 0 and it's percentage : 0.0
 Total NaN values in row 4794 :- 0 and it's percentage : 0.0
 Total NaN values in row 4795 :- 0 and it's percentage : 0.0
 Total NaN values in row 4796 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4797 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4798 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4799 :- 0 and it's percentage : 0.0
 Total NaN values in row 4800 :- 0 and it's percentage : 0.0
 Total NaN values in row 4801 :- 0 and it's percentage : 0.0
 Total NaN values in row 4802 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4803 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4804 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4805 :- 0 and it's percentage : 0.0
 Total NaN values in row 4806 :- 0 and it's percentage : 0.0
 Total NaN values in row 4807 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4808 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4809 :- 0 and it's percentage : 0.0
 Total NaN values in row 4810 :- 0 and it's percentage : 0.0
 Total NaN values in row 4811 :- 0 and it's percentage : 0.0
 Total NaN values in row 4812 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4813 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 4814 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4815 :- 0 and it's percentage : 0.0
 Total NaN values in row 4816 :- 0 and it's percentage : 0.0
 Total NaN values in row 4817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4818 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4819 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4820 :- 0 and it's percentage : 0.0
 Total NaN values in row 4821 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4822 :- 0 and it's percentage : 0.0
 Total NaN values in row 4823 :- 0 and it's percentage : 0.0
 Total NaN values in row 4824 :- 0 and it's percentage : 0.0
 Total NaN values in row 4825 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4826 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4827 :- 0 and it's percentage : 0.0
 Total NaN values in row 4828 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4830 :- 0 and it's percentage : 0.0
 Total NaN values in row 4831 :- 0 and it's percentage : 0.0
 Total NaN values in row 4832 :- 0 and it's percentage : 0.0
 Total NaN values in row 4833 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4834 :- 0 and it's percentage : 0.0
 Total NaN values in row 4835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4836 :- 0 and it's percentage : 0.0
 Total NaN values in row 4837 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4838 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4839 :- 0 and it's percentage : 0.0
 Total NaN values in row 4840 :- 0 and it's percentage : 0.0
 Total NaN values in row 4841 :- 0 and it's percentage : 0.0
 Total NaN values in row 4842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4843 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4844 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4845 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4846 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4848 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4849 :- 0 and it's percentage : 0.0
 Total NaN values in row 4850 :- 0 and it's percentage : 0.0
 Total NaN values in row 4851 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4852 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4853 :- 0 and it's percentage : 0.0
 Total NaN values in row 4854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4855 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4856 :- 0 and it's percentage : 0.0
 Total NaN values in row 4857 :- 0 and it's percentage : 0.0
 Total NaN values in row 4858 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4859 :- 0 and it's percentage : 0.0
 Total NaN values in row 4860 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4861 :- 0 and it's percentage : 0.0
 Total NaN values in row 4862 :- 0 and it's percentage : 0.0
 Total NaN values in row 4863 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4864 :- 0 and it's percentage : 0.0
 Total NaN values in row 4865 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4866 :- 0 and it's percentage : 0.0
 Total NaN values in row 4867 :- 0 and it's percentage : 0.0
 Total NaN values in row 4868 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4869 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4870 :- 0 and it's percentage : 0.0
 Total NaN values in row 4871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4872 :- 0 and it's percentage : 0.0
 Total NaN values in row 4873 :- 0 and it's percentage : 0.0
 Total NaN values in row 4874 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4875 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4876 :- 0 and it's percentage : 0.0
 Total NaN values in row 4877 :- 0 and it's percentage : 0.0
 Total NaN values in row 4878 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4879 :- 0 and it's percentage : 0.0
 Total NaN values in row 4880 :- 0 and it's percentage : 0.0
 Total NaN values in row 4881 :- 0 and it's percentage : 0.0
 Total NaN values in row 4882 :- 0 and it's percentage : 0.0
 Total NaN values in row 4883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4884 :- 0 and it's percentage : 0.0
 Total NaN values in row 4885 :- 0 and it's percentage : 0.0
 Total NaN values in row 4886 :- 0 and it's percentage : 0.0
 Total NaN values in row 4887 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4888 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4889 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4890 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4891 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4892 :- 0 and it's percentage : 0.0
 Total NaN values in row 4893 :- 0 and it's percentage : 0.0
 Total NaN values in row 4894 :- 0 and it's percentage : 0.0
 Total NaN values in row 4895 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4896 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4898 :- 0 and it's percentage : 0.0
 Total NaN values in row 4899 :- 0 and it's percentage : 0.0
 Total NaN values in row 4900 :- 0 and it's percentage : 0.0
 Total NaN values in row 4901 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4902 :- 0 and it's percentage : 0.0
 Total NaN values in row 4903 :- 0 and it's percentage : 0.0
 Total NaN values in row 4904 :- 0 and it's percentage : 0.0
 Total NaN values in row 4905 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4906 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4907 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4908 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4909 :- 0 and it's percentage : 0.0
 Total NaN values in row 4910 :- 0 and it's percentage : 0.0
 Total NaN values in row 4911 :- 0 and it's percentage : 0.0
 Total NaN values in row 4912 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4913 :- 0 and it's percentage : 0.0
 Total NaN values in row 4914 :- 0 and it's percentage : 0.0
 Total NaN values in row 4915 :- 0 and it's percentage : 0.0
 Total NaN values in row 4916 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4917 :- 0 and it's percentage : 0.0
 Total NaN values in row 4918 :- 0 and it's percentage : 0.0
 Total NaN values in row 4919 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4920 :- 0 and it's percentage : 0.0
 Total NaN values in row 4921 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4922 :- 0 and it's percentage : 0.0
 Total NaN values in row 4923 :- 0 and it's percentage : 0.0
 Total NaN values in row 4924 :- 0 and it's percentage : 0.0
 Total NaN values in row 4925 :- 0 and it's percentage : 0.0
 Total NaN values in row 4926 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4927 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4928 :- 0 and it's percentage : 0.0
 Total NaN values in row 4929 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4930 :- 0 and it's percentage : 0.0
 Total NaN values in row 4931 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4932 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4933 :- 0 and it's percentage : 0.0
 Total NaN values in row 4934 :- 0 and it's percentage : 0.0
 Total NaN values in row 4935 :- 0 and it's percentage : 0.0
 Total NaN values in row 4936 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4937 :- 0 and it's percentage : 0.0
 Total NaN values in row 4938 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4939 :- 0 and it's percentage : 0.0
 Total NaN values in row 4940 :- 0 and it's percentage : 0.0
 Total NaN values in row 4941 :- 0 and it's percentage : 0.0
 Total NaN values in row 4942 :- 0 and it's percentage : 0.0
 Total NaN values in row 4943 :- 0 and it's percentage : 0.0
 Total NaN values in row 4944 :- 0 and it's percentage : 0.0
 Total NaN values in row 4945 :- 0 and it's percentage : 0.0
 Total NaN values in row 4946 :- 0 and it's percentage : 0.0
 Total NaN values in row 4947 :- 0 and it's percentage : 0.0
 Total NaN values in row 4948 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4949 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4950 :- 0 and it's percentage : 0.0
 Total NaN values in row 4951 :- 0 and it's percentage : 0.0
 Total NaN values in row 4952 :- 0 and it's percentage : 0.0

 Total NaN values in row 4953 :- 0 and it's percentage : 0.0
 Total NaN values in row 4954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4955 :- 0 and it's percentage : 0.0
 Total NaN values in row 4956 :- 0 and it's percentage : 0.0
 Total NaN values in row 4957 :- 0 and it's percentage : 0.0
 Total NaN values in row 4958 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4959 :- 0 and it's percentage : 0.0
 Total NaN values in row 4960 :- 0 and it's percentage : 0.0
 Total NaN values in row 4961 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4962 :- 0 and it's percentage : 0.0
 Total NaN values in row 4963 :- 0 and it's percentage : 0.0
 Total NaN values in row 4964 :- 0 and it's percentage : 0.0
 Total NaN values in row 4965 :- 0 and it's percentage : 0.0
 Total NaN values in row 4966 :- 0 and it's percentage : 0.0
 Total NaN values in row 4967 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4968 :- 0 and it's percentage : 0.0
 Total NaN values in row 4969 :- 0 and it's percentage : 0.0
 Total NaN values in row 4970 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4971 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4972 :- 0 and it's percentage : 0.0
 Total NaN values in row 4973 :- 0 and it's percentage : 0.0
 Total NaN values in row 4974 :- 0 and it's percentage : 0.0
 Total NaN values in row 4975 :- 0 and it's percentage : 0.0
 Total NaN values in row 4976 :- 0 and it's percentage : 0.0
 Total NaN values in row 4977 :- 0 and it's percentage : 0.0
 Total NaN values in row 4978 :- 0 and it's percentage : 0.0
 Total NaN values in row 4979 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4980 :- 0 and it's percentage : 0.0
 Total NaN values in row 4981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4982 :- 0 and it's percentage : 0.0
 Total NaN values in row 4983 :- 0 and it's percentage : 0.0
 Total NaN values in row 4984 :- 0 and it's percentage : 0.0
 Total NaN values in row 4985 :- 0 and it's percentage : 0.0
 Total NaN values in row 4986 :- 0 and it's percentage : 0.0
 Total NaN values in row 4987 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 4988 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 4989 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 4991 :- 0 and it's percentage : 0.0
 Total NaN values in row 4992 :- 0 and it's percentage : 0.0
 Total NaN values in row 4993 :- 0 and it's percentage : 0.0
 Total NaN values in row 4994 :- 0 and it's percentage : 0.0
 Total NaN values in row 4995 :- 0 and it's percentage : 0.0
 Total NaN values in row 4996 :- 0 and it's percentage : 0.0
 Total NaN values in row 4997 :- 0 and it's percentage : 0.0
 Total NaN values in row 4998 :- 0 and it's percentage : 0.0
 Total NaN values in row 4999 :- 0 and it's percentage : 0.0
 Total NaN values in row 5000 :- 0 and it's percentage : 0.0
 Total NaN values in row 5001 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5002 :- 0 and it's percentage : 0.0
 Total NaN values in row 5003 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5004 :- 0 and it's percentage : 0.0
 Total NaN values in row 5005 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5006 :- 0 and it's percentage : 0.0
 Total NaN values in row 5007 :- 0 and it's percentage : 0.0
 Total NaN values in row 5008 :- 0 and it's percentage : 0.0
 Total NaN values in row 5009 :- 0 and it's percentage : 0.0
 Total NaN values in row 5010 :- 0 and it's percentage : 0.0
 Total NaN values in row 5011 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5012 :- 0 and it's percentage : 0.0
 Total NaN values in row 5013 :- 0 and it's percentage : 0.0
 Total NaN values in row 5014 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5015 :- 0 and it's percentage : 0.0
 Total NaN values in row 5016 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5017 :- 0 and it's percentage : 0.0
 Total NaN values in row 5018 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5019 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5020 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5021 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5022 :- 0 and it's percentage : 0.0
 Total NaN values in row 5023 :- 0 and it's percentage : 0.0
 Total NaN values in row 5024 :- 0 and it's percentage : 0.0
 Total NaN values in row 5025 :- 0 and it's percentage : 0.0
 Total NaN values in row 5026 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5028 :- 0 and it's percentage : 0.0
 Total NaN values in row 5029 :- 0 and it's percentage : 0.0
 Total NaN values in row 5030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5031 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5032 :- 0 and it's percentage : 0.0
 Total NaN values in row 5033 :- 0 and it's percentage : 0.0
 Total NaN values in row 5034 :- 0 and it's percentage : 0.0
 Total NaN values in row 5035 :- 0 and it's percentage : 0.0
 Total NaN values in row 5036 :- 0 and it's percentage : 0.0
 Total NaN values in row 5037 :- 0 and it's percentage : 0.0
 Total NaN values in row 5038 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5039 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5040 :- 0 and it's percentage : 0.0
 Total NaN values in row 5041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5042 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5043 :- 0 and it's percentage : 0.0
 Total NaN values in row 5044 :- 0 and it's percentage : 0.0
 Total NaN values in row 5045 :- 0 and it's percentage : 0.0
 Total NaN values in row 5046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5047 :- 0 and it's percentage : 0.0
 Total NaN values in row 5048 :- 0 and it's percentage : 0.0
 Total NaN values in row 5049 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5050 :- 0 and it's percentage : 0.0
 Total NaN values in row 5051 :- 0 and it's percentage : 0.0
 Total NaN values in row 5052 :- 0 and it's percentage : 0.0
 Total NaN values in row 5053 :- 0 and it's percentage : 0.0
 Total NaN values in row 5054 :- 0 and it's percentage : 0.0
 Total NaN values in row 5055 :- 0 and it's percentage : 0.0
 Total NaN values in row 5056 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5057 :- 0 and it's percentage : 0.0
 Total NaN values in row 5058 :- 0 and it's percentage : 0.0
 Total NaN values in row 5059 :- 0 and it's percentage : 0.0
 Total NaN values in row 5060 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5061 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5062 :- 0 and it's percentage : 0.0
 Total NaN values in row 5063 :- 0 and it's percentage : 0.0
 Total NaN values in row 5064 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5066 :- 0 and it's percentage : 0.0
 Total NaN values in row 5067 :- 0 and it's percentage : 0.0
 Total NaN values in row 5068 :- 0 and it's percentage : 0.0
 Total NaN values in row 5069 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5070 :- 0 and it's percentage : 0.0
 Total NaN values in row 5071 :- 0 and it's percentage : 0.0
 Total NaN values in row 5072 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5073 :- 0 and it's percentage : 0.0
 Total NaN values in row 5074 :- 0 and it's percentage : 0.0
 Total NaN values in row 5075 :- 0 and it's percentage : 0.0
 Total NaN values in row 5076 :- 0 and it's percentage : 0.0
 Total NaN values in row 5077 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5078 :- 0 and it's percentage : 0.0
 Total NaN values in row 5079 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5080 :- 0 and it's percentage : 0.0
 Total NaN values in row 5081 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5082 :- 0 and it's percentage : 0.0
 Total NaN values in row 5083 :- 0 and it's percentage : 0.0
 Total NaN values in row 5084 :- 0 and it's percentage : 0.0
 Total NaN values in row 5085 :- 0 and it's percentage : 0.0
 Total NaN values in row 5086 :- 0 and it's percentage : 0.0
 Total NaN values in row 5087 :- 0 and it's percentage : 0.0
 Total NaN values in row 5088 :- 0 and it's percentage : 0.0
 Total NaN values in row 5089 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5090 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5091 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5092 :- 0 and it's percentage : 0.0
 Total NaN values in row 5093 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5094 :- 0 and it's percentage : 0.0
 Total NaN values in row 5095 :- 0 and it's percentage : 0.0
 Total NaN values in row 5096 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5097 :- 0 and it's percentage : 0.0
 Total NaN values in row 5098 :- 0 and it's percentage : 0.0
 Total NaN values in row 5099 :- 0 and it's percentage : 0.0
 Total NaN values in row 5100 :- 0 and it's percentage : 0.0
 Total NaN values in row 5101 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5102 :- 0 and it's percentage : 0.0
 Total NaN values in row 5103 :- 0 and it's percentage : 0.0
 Total NaN values in row 5104 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5105 :- 0 and it's percentage : 0.0

 Total NaN values in row 5106 :- 0 and it's percentage : 0.0
 Total NaN values in row 5107 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5108 :- 0 and it's percentage : 0.0
 Total NaN values in row 5109 :- 0 and it's percentage : 0.0
 Total NaN values in row 5110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5111 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5112 :- 0 and it's percentage : 0.0
 Total NaN values in row 5113 :- 0 and it's percentage : 0.0
 Total NaN values in row 5114 :- 0 and it's percentage : 0.0
 Total NaN values in row 5115 :- 0 and it's percentage : 0.0
 Total NaN values in row 5116 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5117 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5118 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5119 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5120 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5121 :- 0 and it's percentage : 0.0
 Total NaN values in row 5122 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5123 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5125 :- 0 and it's percentage : 0.0
 Total NaN values in row 5126 :- 0 and it's percentage : 0.0
 Total NaN values in row 5127 :- 0 and it's percentage : 0.0
 Total NaN values in row 5128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5129 :- 0 and it's percentage : 0.0
 Total NaN values in row 5130 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5131 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5132 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5133 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5134 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5135 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5136 :- 0 and it's percentage : 0.0
 Total NaN values in row 5137 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5138 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5139 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5140 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5143 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5144 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5145 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5147 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5148 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5149 :- 0 and it's percentage : 0.0
 Total NaN values in row 5150 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5151 :- 0 and it's percentage : 0.0
 Total NaN values in row 5152 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5153 :- 0 and it's percentage : 0.0
 Total NaN values in row 5154 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5155 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5156 :- 0 and it's percentage : 0.0
 Total NaN values in row 5157 :- 0 and it's percentage : 0.0
 Total NaN values in row 5158 :- 0 and it's percentage : 0.0
 Total NaN values in row 5159 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5160 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5161 :- 0 and it's percentage : 0.0
 Total NaN values in row 5162 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5163 :- 0 and it's percentage : 0.0
 Total NaN values in row 5164 :- 0 and it's percentage : 0.0
 Total NaN values in row 5165 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5166 :- 0 and it's percentage : 0.0
 Total NaN values in row 5167 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5168 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5169 :- 0 and it's percentage : 0.0
 Total NaN values in row 5170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5171 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 5172 :- 0 and it's percentage : 0.0
 Total NaN values in row 5173 :- 0 and it's percentage : 0.0
 Total NaN values in row 5174 :- 0 and it's percentage : 0.0
 Total NaN values in row 5175 :- 0 and it's percentage : 0.0
 Total NaN values in row 5176 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5177 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5178 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5180 :- 0 and it's percentage : 0.0
 Total NaN values in row 5181 :- 0 and it's percentage : 0.0
 Total NaN values in row 5182 :- 0 and it's percentage : 0.0
 Total NaN values in row 5183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5184 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5185 :- 0 and it's percentage : 0.0
 Total NaN values in row 5186 :- 0 and it's percentage : 0.0
 Total NaN values in row 5187 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5188 :- 0 and it's percentage : 0.0
 Total NaN values in row 5189 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5190 :- 0 and it's percentage : 0.0
 Total NaN values in row 5191 :- 0 and it's percentage : 0.0
 Total NaN values in row 5192 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5193 :- 0 and it's percentage : 0.0
 Total NaN values in row 5194 :- 0 and it's percentage : 0.0
 Total NaN values in row 5195 :- 0 and it's percentage : 0.0
 Total NaN values in row 5196 :- 0 and it's percentage : 0.0
 Total NaN values in row 5197 :- 0 and it's percentage : 0.0
 Total NaN values in row 5198 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5201 :- 0 and it's percentage : 0.0
 Total NaN values in row 5202 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5204 :- 0 and it's percentage : 0.0
 Total NaN values in row 5205 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5206 :- 0 and it's percentage : 0.0
 Total NaN values in row 5207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5208 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5209 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5210 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5211 :- 0 and it's percentage : 0.0
 Total NaN values in row 5212 :- 0 and it's percentage : 0.0
 Total NaN values in row 5213 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5214 :- 0 and it's percentage : 0.0
 Total NaN values in row 5215 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5216 :- 0 and it's percentage : 0.0
 Total NaN values in row 5217 :- 0 and it's percentage : 0.0
 Total NaN values in row 5218 :- 0 and it's percentage : 0.0
 Total NaN values in row 5219 :- 0 and it's percentage : 0.0
 Total NaN values in row 5220 :- 0 and it's percentage : 0.0
 Total NaN values in row 5221 :- 0 and it's percentage : 0.0
 Total NaN values in row 5222 :- 0 and it's percentage : 0.0
 Total NaN values in row 5223 :- 0 and it's percentage : 0.0
 Total NaN values in row 5224 :- 0 and it's percentage : 0.0
 Total NaN values in row 5225 :- 0 and it's percentage : 0.0
 Total NaN values in row 5226 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5228 :- 0 and it's percentage : 0.0
 Total NaN values in row 5229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5230 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5231 :- 0 and it's percentage : 0.0
 Total NaN values in row 5232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5233 :- 0 and it's percentage : 0.0
 Total NaN values in row 5234 :- 0 and it's percentage : 0.0
 Total NaN values in row 5235 :- 0 and it's percentage : 0.0

 Total NaN values in row 5236 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 5237 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5238 :- 0 and it's percentage : 0.0
 Total NaN values in row 5239 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5240 :- 0 and it's percentage : 0.0
 Total NaN values in row 5241 :- 0 and it's percentage : 0.0
 Total NaN values in row 5242 :- 0 and it's percentage : 0.0
 Total NaN values in row 5243 :- 0 and it's percentage : 0.0
 Total NaN values in row 5244 :- 0 and it's percentage : 0.0
 Total NaN values in row 5245 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5246 :- 0 and it's percentage : 0.0
 Total NaN values in row 5247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5248 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5249 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5251 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5252 :- 0 and it's percentage : 0.0
 Total NaN values in row 5253 :- 0 and it's percentage : 0.0
 Total NaN values in row 5254 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5255 :- 0 and it's percentage : 0.0
 Total NaN values in row 5256 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5257 :- 0 and it's percentage : 0.0
 Total NaN values in row 5258 :- 0 and it's percentage : 0.0
 Total NaN values in row 5259 :- 0 and it's percentage : 0.0
 Total NaN values in row 5260 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5261 :- 0 and it's percentage : 0.0
 Total NaN values in row 5262 :- 0 and it's percentage : 0.0
 Total NaN values in row 5263 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5264 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5265 :- 0 and it's percentage : 0.0
 Total NaN values in row 5266 :- 0 and it's percentage : 0.0
 Total NaN values in row 5267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5269 :- 0 and it's percentage : 0.0
 Total NaN values in row 5270 :- 0 and it's percentage : 0.0
 Total NaN values in row 5271 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5272 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5273 :- 0 and it's percentage : 0.0
 Total NaN values in row 5274 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5275 :- 0 and it's percentage : 0.0
 Total NaN values in row 5276 :- 0 and it's percentage : 0.0
 Total NaN values in row 5277 :- 0 and it's percentage : 0.0
 Total NaN values in row 5278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5279 :- 0 and it's percentage : 0.0
 Total NaN values in row 5280 :- 0 and it's percentage : 0.0
 Total NaN values in row 5281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5283 :- 0 and it's percentage : 0.0
 Total NaN values in row 5284 :- 0 and it's percentage : 0.0
 Total NaN values in row 5285 :- 0 and it's percentage : 0.0
 Total NaN values in row 5286 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5287 :- 0 and it's percentage : 0.0
 Total NaN values in row 5288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5289 :- 0 and it's percentage : 0.0
 Total NaN values in row 5290 :- 0 and it's percentage : 0.0
 Total NaN values in row 5291 :- 0 and it's percentage : 0.0
 Total NaN values in row 5292 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5293 :- 0 and it's percentage : 0.0
 Total NaN values in row 5294 :- 0 and it's percentage : 0.0
 Total NaN values in row 5295 :- 0 and it's percentage : 0.0
 Total NaN values in row 5296 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5297 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5300 :- 0 and it's percentage : 0.0
 Total NaN values in row 5301 :- 0 and it's percentage : 0.0
 Total NaN values in row 5302 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5303 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5304 :- 0 and it's percentage : 0.0
 Total NaN values in row 5305 :- 0 and it's percentage : 0.0
 Total NaN values in row 5306 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5308 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5309 :- 0 and it's percentage : 0.0
 Total NaN values in row 5310 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5311 :- 0 and it's percentage : 0.0
 Total NaN values in row 5312 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5313 :- 0 and it's percentage : 0.0
 Total NaN values in row 5314 :- 0 and it's percentage : 0.0
 Total NaN values in row 5315 :- 0 and it's percentage : 0.0
 Total NaN values in row 5316 :- 0 and it's percentage : 0.0
 Total NaN values in row 5317 :- 0 and it's percentage : 0.0
 Total NaN values in row 5318 :- 0 and it's percentage : 0.0
 Total NaN values in row 5319 :- 0 and it's percentage : 0.0
 Total NaN values in row 5320 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5321 :- 0 and it's percentage : 0.0
 Total NaN values in row 5322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5323 :- 0 and it's percentage : 0.0
 Total NaN values in row 5324 :- 0 and it's percentage : 0.0
 Total NaN values in row 5325 :- 0 and it's percentage : 0.0
 Total NaN values in row 5326 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5327 :- 0 and it's percentage : 0.0
 Total NaN values in row 5328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5329 :- 0 and it's percentage : 0.0
 Total NaN values in row 5330 :- 0 and it's percentage : 0.0
 Total NaN values in row 5331 :- 0 and it's percentage : 0.0
 Total NaN values in row 5332 :- 0 and it's percentage : 0.0
 Total NaN values in row 5333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5334 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5335 :- 0 and it's percentage : 0.0
 Total NaN values in row 5336 :- 0 and it's percentage : 0.0
 Total NaN values in row 5337 :- 0 and it's percentage : 0.0
 Total NaN values in row 5338 :- 0 and it's percentage : 0.0
 Total NaN values in row 5339 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5340 :- 0 and it's percentage : 0.0
 Total NaN values in row 5341 :- 0 and it's percentage : 0.0
 Total NaN values in row 5342 :- 0 and it's percentage : 0.0
 Total NaN values in row 5343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5344 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5345 :- 0 and it's percentage : 0.0
 Total NaN values in row 5346 :- 0 and it's percentage : 0.0
 Total NaN values in row 5347 :- 0 and it's percentage : 0.0
 Total NaN values in row 5348 :- 0 and it's percentage : 0.0
 Total NaN values in row 5349 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5350 :- 0 and it's percentage : 0.0
 Total NaN values in row 5351 :- 0 and it's percentage : 0.0
 Total NaN values in row 5352 :- 0 and it's percentage : 0.0
 Total NaN values in row 5353 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5354 :- 0 and it's percentage : 0.0
 Total NaN values in row 5355 :- 0 and it's percentage : 0.0
 Total NaN values in row 5356 :- 0 and it's percentage : 0.0
 Total NaN values in row 5357 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5358 :- 0 and it's percentage : 0.0

 Total NaN values in row 5359 :- 0 and it's percentage : 0.0
 Total NaN values in row 5360 :- 0 and it's percentage : 0.0
 Total NaN values in row 5361 :- 0 and it's percentage : 0.0
 Total NaN values in row 5362 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5363 :- 0 and it's percentage : 0.0
 Total NaN values in row 5364 :- 0 and it's percentage : 0.0
 Total NaN values in row 5365 :- 0 and it's percentage : 0.0
 Total NaN values in row 5366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5367 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5368 :- 0 and it's percentage : 0.0
 Total NaN values in row 5369 :- 0 and it's percentage : 0.0
 Total NaN values in row 5370 :- 0 and it's percentage : 0.0
 Total NaN values in row 5371 :- 0 and it's percentage : 0.0
 Total NaN values in row 5372 :- 0 and it's percentage : 0.0
 Total NaN values in row 5373 :- 0 and it's percentage : 0.0
 Total NaN values in row 5374 :- 0 and it's percentage : 0.0
 Total NaN values in row 5375 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5376 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5378 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5380 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5381 :- 0 and it's percentage : 0.0
 Total NaN values in row 5382 :- 0 and it's percentage : 0.0
 Total NaN values in row 5383 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5384 :- 0 and it's percentage : 0.0
 Total NaN values in row 5385 :- 0 and it's percentage : 0.0
 Total NaN values in row 5386 :- 0 and it's percentage : 0.0
 Total NaN values in row 5387 :- 0 and it's percentage : 0.0
 Total NaN values in row 5388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5389 :- 0 and it's percentage : 0.0
 Total NaN values in row 5390 :- 0 and it's percentage : 0.0
 Total NaN values in row 5391 :- 0 and it's percentage : 0.0
 Total NaN values in row 5392 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5393 :- 0 and it's percentage : 0.0
 Total NaN values in row 5394 :- 0 and it's percentage : 0.0
 Total NaN values in row 5395 :- 0 and it's percentage : 0.0
 Total NaN values in row 5396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5397 :- 0 and it's percentage : 0.0
 Total NaN values in row 5398 :- 0 and it's percentage : 0.0
 Total NaN values in row 5399 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5400 :- 0 and it's percentage : 0.0
 Total NaN values in row 5401 :- 0 and it's percentage : 0.0
 Total NaN values in row 5402 :- 0 and it's percentage : 0.0
 Total NaN values in row 5403 :- 0 and it's percentage : 0.0
 Total NaN values in row 5404 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5405 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5406 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5408 :- 0 and it's percentage : 0.0
 Total NaN values in row 5409 :- 0 and it's percentage : 0.0
 Total NaN values in row 5410 :- 0 and it's percentage : 0.0
 Total NaN values in row 5411 :- 0 and it's percentage : 0.0
 Total NaN values in row 5412 :- 0 and it's percentage : 0.0
 Total NaN values in row 5413 :- 0 and it's percentage : 0.0
 Total NaN values in row 5414 :- 0 and it's percentage : 0.0
 Total NaN values in row 5415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5417 :- 0 and it's percentage : 0.0
 Total NaN values in row 5418 :- 0 and it's percentage : 0.0
 Total NaN values in row 5419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5420 :- 0 and it's percentage : 0.0
 Total NaN values in row 5421 :- 0 and it's percentage : 0.0
 Total NaN values in row 5422 :- 0 and it's percentage : 0.0
 Total NaN values in row 5423 :- 0 and it's percentage : 0.0
 Total NaN values in row 5424 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5425 :- 0 and it's percentage : 0.0
 Total NaN values in row 5426 :- 0 and it's percentage : 0.0
 Total NaN values in row 5427 :- 0 and it's percentage : 0.0
 Total NaN values in row 5428 :- 0 and it's percentage : 0.0
 Total NaN values in row 5429 :- 0 and it's percentage : 0.0
 Total NaN values in row 5430 :- 0 and it's percentage : 0.0
 Total NaN values in row 5431 :- 0 and it's percentage : 0.0
 Total NaN values in row 5432 :- 0 and it's percentage : 0.0
 Total NaN values in row 5433 :- 0 and it's percentage : 0.0
 Total NaN values in row 5434 :- 0 and it's percentage : 0.0
 Total NaN values in row 5435 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5436 :- 0 and it's percentage : 0.0
 Total NaN values in row 5437 :- 0 and it's percentage : 0.0
 Total NaN values in row 5438 :- 0 and it's percentage : 0.0
 Total NaN values in row 5439 :- 0 and it's percentage : 0.0
 Total NaN values in row 5440 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5441 :- 0 and it's percentage : 0.0
 Total NaN values in row 5442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5443 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5445 :- 0 and it's percentage : 0.0
 Total NaN values in row 5446 :- 0 and it's percentage : 0.0
 Total NaN values in row 5447 :- 0 and it's percentage : 0.0
 Total NaN values in row 5448 :- 0 and it's percentage : 0.0
 Total NaN values in row 5449 :- 0 and it's percentage : 0.0
 Total NaN values in row 5450 :- 0 and it's percentage : 0.0
 Total NaN values in row 5451 :- 0 and it's percentage : 0.0
 Total NaN values in row 5452 :- 0 and it's percentage : 0.0
 Total NaN values in row 5453 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5454 :- 0 and it's percentage : 0.0
 Total NaN values in row 5455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5456 :- 0 and it's percentage : 0.0
 Total NaN values in row 5457 :- 0 and it's percentage : 0.0
 Total NaN values in row 5458 :- 0 and it's percentage : 0.0
 Total NaN values in row 5459 :- 0 and it's percentage : 0.0
 Total NaN values in row 5460 :- 0 and it's percentage : 0.0
 Total NaN values in row 5461 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5462 :- 0 and it's percentage : 0.0
 Total NaN values in row 5463 :- 0 and it's percentage : 0.0
 Total NaN values in row 5464 :- 0 and it's percentage : 0.0
 Total NaN values in row 5465 :- 0 and it's percentage : 0.0
 Total NaN values in row 5466 :- 0 and it's percentage : 0.0
 Total NaN values in row 5467 :- 0 and it's percentage : 0.0
 Total NaN values in row 5468 :- 0 and it's percentage : 0.0
 Total NaN values in row 5469 :- 0 and it's percentage : 0.0
 Total NaN values in row 5470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5471 :- 0 and it's percentage : 0.0
 Total NaN values in row 5472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5473 :- 0 and it's percentage : 0.0
 Total NaN values in row 5474 :- 0 and it's percentage : 0.0
 Total NaN values in row 5475 :- 0 and it's percentage : 0.0
 Total NaN values in row 5476 :- 0 and it's percentage : 0.0
 Total NaN values in row 5477 :- 0 and it's percentage : 0.0
 Total NaN values in row 5478 :- 0 and it's percentage : 0.0
 Total NaN values in row 5479 :- 0 and it's percentage : 0.0
 Total NaN values in row 5480 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5482 :- 0 and it's percentage : 0.0
 Total NaN values in row 5483 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5484 :- 0 and it's percentage : 0.0
 Total NaN values in row 5485 :- 0 and it's percentage : 0.0
 Total NaN values in row 5486 :- 0 and it's percentage : 0.0
 Total NaN values in row 5487 :- 0 and it's percentage : 0.0
 Total NaN values in row 5488 :- 0 and it's percentage : 0.0
 Total NaN values in row 5489 :- 0 and it's percentage : 0.0
 Total NaN values in row 5490 :- 0 and it's percentage : 0.0
 Total NaN values in row 5491 :- 0 and it's percentage : 0.0
 Total NaN values in row 5492 :- 0 and it's percentage : 0.0
 Total NaN values in row 5493 :- 0 and it's percentage : 0.0
 Total NaN values in row 5494 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5495 :- 0 and it's percentage : 0.0
 Total NaN values in row 5496 :- 0 and it's percentage : 0.0
 Total NaN values in row 5497 :- 0 and it's percentage : 0.0
 Total NaN values in row 5498 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5499 :- 0 and it's percentage : 0.0
 Total NaN values in row 5500 :- 0 and it's percentage : 0.0
 Total NaN values in row 5501 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5502 :- 0 and it's percentage : 0.0
 Total NaN values in row 5503 :- 0 and it's percentage : 0.0
 Total NaN values in row 5504 :- 0 and it's percentage : 0.0
 Total NaN values in row 5505 :- 0 and it's percentage : 0.0
 Total NaN values in row 5506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5507 :- 0 and it's percentage : 0.0
 Total NaN values in row 5508 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5509 :- 0 and it's percentage : 0.0

 Total NaN values in row 5510 :- 0 and it's percentage : 0.0
 Total NaN values in row 5511 :- 0 and it's percentage : 0.0
 Total NaN values in row 5512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5513 :- 0 and it's percentage : 0.0
 Total NaN values in row 5514 :- 0 and it's percentage : 0.0
 Total NaN values in row 5515 :- 0 and it's percentage : 0.0
 Total NaN values in row 5516 :- 0 and it's percentage : 0.0
 Total NaN values in row 5517 :- 0 and it's percentage : 0.0
 Total NaN values in row 5518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5519 :- 0 and it's percentage : 0.0
 Total NaN values in row 5520 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5521 :- 0 and it's percentage : 0.0
 Total NaN values in row 5522 :- 0 and it's percentage : 0.0
 Total NaN values in row 5523 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5524 :- 0 and it's percentage : 0.0
 Total NaN values in row 5525 :- 0 and it's percentage : 0.0
 Total NaN values in row 5526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5527 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5528 :- 0 and it's percentage : 0.0
 Total NaN values in row 5529 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5530 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5531 :- 0 and it's percentage : 0.0
 Total NaN values in row 5532 :- 0 and it's percentage : 0.0
 Total NaN values in row 5533 :- 0 and it's percentage : 0.0
 Total NaN values in row 5534 :- 0 and it's percentage : 0.0
 Total NaN values in row 5535 :- 0 and it's percentage : 0.0
 Total NaN values in row 5536 :- 0 and it's percentage : 0.0
 Total NaN values in row 5537 :- 0 and it's percentage : 0.0
 Total NaN values in row 5538 :- 0 and it's percentage : 0.0
 Total NaN values in row 5539 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5540 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5541 :- 0 and it's percentage : 0.0
 Total NaN values in row 5542 :- 0 and it's percentage : 0.0
 Total NaN values in row 5543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5544 :- 0 and it's percentage : 0.0
 Total NaN values in row 5545 :- 0 and it's percentage : 0.0
 Total NaN values in row 5546 :- 0 and it's percentage : 0.0
 Total NaN values in row 5547 :- 0 and it's percentage : 0.0
 Total NaN values in row 5548 :- 0 and it's percentage : 0.0
 Total NaN values in row 5549 :- 0 and it's percentage : 0.0
 Total NaN values in row 5550 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5551 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5552 :- 0 and it's percentage : 0.0
 Total NaN values in row 5553 :- 0 and it's percentage : 0.0
 Total NaN values in row 5554 :- 0 and it's percentage : 0.0
 Total NaN values in row 5555 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5556 :- 0 and it's percentage : 0.0
 Total NaN values in row 5557 :- 0 and it's percentage : 0.0
 Total NaN values in row 5558 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5559 :- 0 and it's percentage : 0.0
 Total NaN values in row 5560 :- 0 and it's percentage : 0.0
 Total NaN values in row 5561 :- 0 and it's percentage : 0.0
 Total NaN values in row 5562 :- 0 and it's percentage : 0.0
 Total NaN values in row 5563 :- 0 and it's percentage : 0.0
 Total NaN values in row 5564 :- 0 and it's percentage : 0.0
 Total NaN values in row 5565 :- 0 and it's percentage : 0.0
 Total NaN values in row 5566 :- 0 and it's percentage : 0.0
 Total NaN values in row 5567 :- 0 and it's percentage : 0.0
 Total NaN values in row 5568 :- 0 and it's percentage : 0.0
 Total NaN values in row 5569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5570 :- 0 and it's percentage : 0.0
 Total NaN values in row 5571 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5572 :- 0 and it's percentage : 0.0
 Total NaN values in row 5573 :- 0 and it's percentage : 0.0
 Total NaN values in row 5574 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5575 :- 0 and it's percentage : 0.0
 Total NaN values in row 5576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5577 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5578 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5580 :- 0 and it's percentage : 0.0
 Total NaN values in row 5581 :- 0 and it's percentage : 0.0
 Total NaN values in row 5582 :- 0 and it's percentage : 0.0
 Total NaN values in row 5583 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5584 :- 0 and it's percentage : 0.0
 Total NaN values in row 5585 :- 0 and it's percentage : 0.0
 Total NaN values in row 5586 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5587 :- 0 and it's percentage : 0.0
 Total NaN values in row 5588 :- 0 and it's percentage : 0.0
 Total NaN values in row 5589 :- 0 and it's percentage : 0.0
 Total NaN values in row 5590 :- 0 and it's percentage : 0.0
 Total NaN values in row 5591 :- 0 and it's percentage : 0.0
 Total NaN values in row 5592 :- 0 and it's percentage : 0.0
 Total NaN values in row 5593 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5594 :- 0 and it's percentage : 0.0
 Total NaN values in row 5595 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5596 :- 0 and it's percentage : 0.0
 Total NaN values in row 5597 :- 0 and it's percentage : 0.0
 Total NaN values in row 5598 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5600 :- 0 and it's percentage : 0.0
 Total NaN values in row 5601 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5602 :- 0 and it's percentage : 0.0
 Total NaN values in row 5603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5604 :- 0 and it's percentage : 0.0
 Total NaN values in row 5605 :- 0 and it's percentage : 0.0
 Total NaN values in row 5606 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5607 :- 0 and it's percentage : 0.0
 Total NaN values in row 5608 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5609 :- 0 and it's percentage : 0.0
 Total NaN values in row 5610 :- 0 and it's percentage : 0.0
 Total NaN values in row 5611 :- 0 and it's percentage : 0.0
 Total NaN values in row 5612 :- 0 and it's percentage : 0.0
 Total NaN values in row 5613 :- 0 and it's percentage : 0.0
 Total NaN values in row 5614 :- 0 and it's percentage : 0.0
 Total NaN values in row 5615 :- 0 and it's percentage : 0.0
 Total NaN values in row 5616 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5617 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5618 :- 0 and it's percentage : 0.0
 Total NaN values in row 5619 :- 0 and it's percentage : 0.0
 Total NaN values in row 5620 :- 0 and it's percentage : 0.0
 Total NaN values in row 5621 :- 0 and it's percentage : 0.0
 Total NaN values in row 5622 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5624 :- 0 and it's percentage : 0.0
 Total NaN values in row 5625 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5626 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5627 :- 0 and it's percentage : 0.0
 Total NaN values in row 5628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5629 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5630 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5631 :- 0 and it's percentage : 0.0
 Total NaN values in row 5632 :- 0 and it's percentage : 0.0
 Total NaN values in row 5633 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5634 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5635 :- 0 and it's percentage : 0.0
 Total NaN values in row 5636 :- 0 and it's percentage : 0.0
 Total NaN values in row 5637 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5638 :- 0 and it's percentage : 0.0
 Total NaN values in row 5639 :- 0 and it's percentage : 0.0
 Total NaN values in row 5640 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5642 :- 0 and it's percentage : 0.0
 Total NaN values in row 5643 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5644 :- 0 and it's percentage : 0.0
 Total NaN values in row 5645 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5646 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5647 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5648 :- 0 and it's percentage : 0.0
 Total NaN values in row 5649 :- 0 and it's percentage : 0.0
 Total NaN values in row 5650 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5651 :- 0 and it's percentage : 0.0
 Total NaN values in row 5652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5653 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5654 :- 0 and it's percentage : 0.0
 Total NaN values in row 5655 :- 0 and it's percentage : 0.0
 Total NaN values in row 5656 :- 0 and it's percentage : 0.0
 Total NaN values in row 5657 :- 0 and it's percentage : 0.0
 Total NaN values in row 5658 :- 0 and it's percentage : 0.0
 Total NaN values in row 5659 :- 0 and it's percentage : 0.0
 Total NaN values in row 5660 :- 0 and it's percentage : 0.0
 Total NaN values in row 5661 :- 0 and it's percentage : 0.0
 Total NaN values in row 5662 :- 0 and it's percentage : 0.0
 Total NaN values in row 5663 :- 0 and it's percentage : 0.0
 Total NaN values in row 5664 :- 0 and it's percentage : 0.0
 Total NaN values in row 5665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5666 :- 0 and it's percentage : 0.0
 Total NaN values in row 5667 :- 0 and it's percentage : 0.0
 Total NaN values in row 5668 :- 0 and it's percentage : 0.0
 Total NaN values in row 5669 :- 0 and it's percentage : 0.0
 Total NaN values in row 5670 :- 0 and it's percentage : 0.0
 Total NaN values in row 5671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5672 :- 0 and it's percentage : 0.0
 Total NaN values in row 5673 :- 0 and it's percentage : 0.0
 Total NaN values in row 5674 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5675 :- 0 and it's percentage : 0.0
 Total NaN values in row 5676 :- 0 and it's percentage : 0.0
 Total NaN values in row 5677 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5678 :- 0 and it's percentage : 0.0
 Total NaN values in row 5679 :- 0 and it's percentage : 0.0
 Total NaN values in row 5680 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5681 :- 0 and it's percentage : 0.0
 Total NaN values in row 5682 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5683 :- 0 and it's percentage : 0.0
 Total NaN values in row 5684 :- 0 and it's percentage : 0.0

 Total NaN values in row 5685 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5686 :- 0 and it's percentage : 0.0
 Total NaN values in row 5687 :- 0 and it's percentage : 0.0
 Total NaN values in row 5688 :- 0 and it's percentage : 0.0
 Total NaN values in row 5689 :- 0 and it's percentage : 0.0
 Total NaN values in row 5690 :- 0 and it's percentage : 0.0
 Total NaN values in row 5691 :- 0 and it's percentage : 0.0
 Total NaN values in row 5692 :- 0 and it's percentage : 0.0
 Total NaN values in row 5693 :- 0 and it's percentage : 0.0
 Total NaN values in row 5694 :- 0 and it's percentage : 0.0
 Total NaN values in row 5695 :- 0 and it's percentage : 0.0
 Total NaN values in row 5696 :- 0 and it's percentage : 0.0
 Total NaN values in row 5697 :- 0 and it's percentage : 0.0
 Total NaN values in row 5698 :- 0 and it's percentage : 0.0
 Total NaN values in row 5699 :- 0 and it's percentage : 0.0
 Total NaN values in row 5700 :- 0 and it's percentage : 0.0
 Total NaN values in row 5701 :- 0 and it's percentage : 0.0
 Total NaN values in row 5702 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5703 :- 0 and it's percentage : 0.0
 Total NaN values in row 5704 :- 0 and it's percentage : 0.0
 Total NaN values in row 5705 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5706 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5707 :- 0 and it's percentage : 0.0
 Total NaN values in row 5708 :- 0 and it's percentage : 0.0
 Total NaN values in row 5709 :- 0 and it's percentage : 0.0
 Total NaN values in row 5710 :- 0 and it's percentage : 0.0
 Total NaN values in row 5711 :- 0 and it's percentage : 0.0
 Total NaN values in row 5712 :- 0 and it's percentage : 0.0
 Total NaN values in row 5713 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5714 :- 0 and it's percentage : 0.0
 Total NaN values in row 5715 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5716 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5717 :- 0 and it's percentage : 0.0
 Total NaN values in row 5718 :- 0 and it's percentage : 0.0
 Total NaN values in row 5719 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5720 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5721 :- 0 and it's percentage : 0.0
 Total NaN values in row 5722 :- 0 and it's percentage : 0.0
 Total NaN values in row 5723 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5724 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5725 :- 0 and it's percentage : 0.0
 Total NaN values in row 5726 :- 0 and it's percentage : 0.0
 Total NaN values in row 5727 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5728 :- 0 and it's percentage : 0.0
 Total NaN values in row 5729 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5730 :- 0 and it's percentage : 0.0
 Total NaN values in row 5731 :- 0 and it's percentage : 0.0
 Total NaN values in row 5732 :- 0 and it's percentage : 0.0
 Total NaN values in row 5733 :- 0 and it's percentage : 0.0
 Total NaN values in row 5734 :- 0 and it's percentage : 0.0
 Total NaN values in row 5735 :- 0 and it's percentage : 0.0
 Total NaN values in row 5736 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5737 :- 0 and it's percentage : 0.0
 Total NaN values in row 5738 :- 0 and it's percentage : 0.0
 Total NaN values in row 5739 :- 0 and it's percentage : 0.0
 Total NaN values in row 5740 :- 0 and it's percentage : 0.0
 Total NaN values in row 5741 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5743 :- 0 and it's percentage : 0.0
 Total NaN values in row 5744 :- 0 and it's percentage : 0.0
 Total NaN values in row 5745 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5746 :- 0 and it's percentage : 0.0
 Total NaN values in row 5747 :- 0 and it's percentage : 0.0
 Total NaN values in row 5748 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5749 :- 0 and it's percentage : 0.0
 Total NaN values in row 5750 :- 0 and it's percentage : 0.0
 Total NaN values in row 5751 :- 0 and it's percentage : 0.0
 Total NaN values in row 5752 :- 0 and it's percentage : 0.0
 Total NaN values in row 5753 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5754 :- 0 and it's percentage : 0.0
 Total NaN values in row 5755 :- 0 and it's percentage : 0.0
 Total NaN values in row 5756 :- 0 and it's percentage : 0.0
 Total NaN values in row 5757 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5758 :- 0 and it's percentage : 0.0
 Total NaN values in row 5759 :- 0 and it's percentage : 0.0
 Total NaN values in row 5760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5761 :- 0 and it's percentage : 0.0
 Total NaN values in row 5762 :- 0 and it's percentage : 0.0
 Total NaN values in row 5763 :- 0 and it's percentage : 0.0
 Total NaN values in row 5764 :- 0 and it's percentage : 0.0
 Total NaN values in row 5765 :- 0 and it's percentage : 0.0
 Total NaN values in row 5766 :- 0 and it's percentage : 0.0
 Total NaN values in row 5767 :- 0 and it's percentage : 0.0
 Total NaN values in row 5768 :- 0 and it's percentage : 0.0
 Total NaN values in row 5769 :- 0 and it's percentage : 0.0
 Total NaN values in row 5770 :- 0 and it's percentage : 0.0
 Total NaN values in row 5771 :- 0 and it's percentage : 0.0
 Total NaN values in row 5772 :- 0 and it's percentage : 0.0
 Total NaN values in row 5773 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5774 :- 0 and it's percentage : 0.0
 Total NaN values in row 5775 :- 0 and it's percentage : 0.0
 Total NaN values in row 5776 :- 0 and it's percentage : 0.0
 Total NaN values in row 5777 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5778 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5779 :- 0 and it's percentage : 0.0
 Total NaN values in row 5780 :- 0 and it's percentage : 0.0
 Total NaN values in row 5781 :- 0 and it's percentage : 0.0
 Total NaN values in row 5782 :- 0 and it's percentage : 0.0
 Total NaN values in row 5783 :- 0 and it's percentage : 0.0
 Total NaN values in row 5784 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5785 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5786 :- 0 and it's percentage : 0.0
 Total NaN values in row 5787 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5788 :- 0 and it's percentage : 0.0
 Total NaN values in row 5789 :- 0 and it's percentage : 0.0
 Total NaN values in row 5790 :- 0 and it's percentage : 0.0
 Total NaN values in row 5791 :- 0 and it's percentage : 0.0
 Total NaN values in row 5792 :- 0 and it's percentage : 0.0
 Total NaN values in row 5793 :- 0 and it's percentage : 0.0
 Total NaN values in row 5794 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5795 :- 0 and it's percentage : 0.0
 Total NaN values in row 5796 :- 0 and it's percentage : 0.0
 Total NaN values in row 5797 :- 0 and it's percentage : 0.0
 Total NaN values in row 5798 :- 0 and it's percentage : 0.0
 Total NaN values in row 5799 :- 0 and it's percentage : 0.0
 Total NaN values in row 5800 :- 0 and it's percentage : 0.0
 Total NaN values in row 5801 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5802 :- 0 and it's percentage : 0.0
 Total NaN values in row 5803 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5804 :- 0 and it's percentage : 0.0
 Total NaN values in row 5805 :- 0 and it's percentage : 0.0
 Total NaN values in row 5806 :- 0 and it's percentage : 0.0
 Total NaN values in row 5807 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5808 :- 0 and it's percentage : 0.0
 Total NaN values in row 5809 :- 0 and it's percentage : 0.0
 Total NaN values in row 5810 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5811 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5812 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5813 :- 0 and it's percentage : 0.0
 Total NaN values in row 5814 :- 0 and it's percentage : 0.0
 Total NaN values in row 5815 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5816 :- 0 and it's percentage : 0.0
 Total NaN values in row 5817 :- 0 and it's percentage : 0.0
 Total NaN values in row 5818 :- 0 and it's percentage : 0.0
 Total NaN values in row 5819 :- 0 and it's percentage : 0.0
 Total NaN values in row 5820 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5821 :- 0 and it's percentage : 0.0
 Total NaN values in row 5822 :- 0 and it's percentage : 0.0
 Total NaN values in row 5823 :- 0 and it's percentage : 0.0
 Total NaN values in row 5824 :- 0 and it's percentage : 0.0
 Total NaN values in row 5825 :- 0 and it's percentage : 0.0
 Total NaN values in row 5826 :- 0 and it's percentage : 0.0
 Total NaN values in row 5827 :- 0 and it's percentage : 0.0
 Total NaN values in row 5828 :- 0 and it's percentage : 0.0
 Total NaN values in row 5829 :- 0 and it's percentage : 0.0
 Total NaN values in row 5830 :- 0 and it's percentage : 0.0
 Total NaN values in row 5831 :- 0 and it's percentage : 0.0
 Total NaN values in row 5832 :- 0 and it's percentage : 0.0
 Total NaN values in row 5833 :- 0 and it's percentage : 0.0
 Total NaN values in row 5834 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5835 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5836 :- 0 and it's percentage : 0.0
 Total NaN values in row 5837 :- 0 and it's percentage : 0.0
 Total NaN values in row 5838 :- 0 and it's percentage : 0.0
 Total NaN values in row 5839 :- 0 and it's percentage : 0.0
 Total NaN values in row 5840 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5841 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5842 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5843 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5844 :- 0 and it's percentage : 0.0
 Total NaN values in row 5845 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5846 :- 0 and it's percentage : 0.0
 Total NaN values in row 5847 :- 0 and it's percentage : 0.0
 Total NaN values in row 5848 :- 0 and it's percentage : 0.0
 Total NaN values in row 5849 :- 0 and it's percentage : 0.0
 Total NaN values in row 5850 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5851 :- 0 and it's percentage : 0.0
 Total NaN values in row 5852 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5853 :- 0 and it's percentage : 0.0
 Total NaN values in row 5854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5855 :- 0 and it's percentage : 0.0
 Total NaN values in row 5856 :- 0 and it's percentage : 0.0
 Total NaN values in row 5857 :- 0 and it's percentage : 0.0
 Total NaN values in row 5858 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5859 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5860 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5861 :- 0 and it's percentage : 0.0
 Total NaN values in row 5862 :- 0 and it's percentage : 0.0

 Total NaN values in row 5863 :- 0 and it's percentage : 0.0
 Total NaN values in row 5864 :- 0 and it's percentage : 0.0
 Total NaN values in row 5865 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5866 :- 0 and it's percentage : 0.0
 Total NaN values in row 5867 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5868 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5869 :- 0 and it's percentage : 0.0
 Total NaN values in row 5870 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 5871 :- 0 and it's percentage : 0.0
 Total NaN values in row 5872 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5873 :- 0 and it's percentage : 0.0
 Total NaN values in row 5874 :- 0 and it's percentage : 0.0
 Total NaN values in row 5875 :- 0 and it's percentage : 0.0
 Total NaN values in row 5876 :- 0 and it's percentage : 0.0
 Total NaN values in row 5877 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5878 :- 0 and it's percentage : 0.0
 Total NaN values in row 5879 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5880 :- 0 and it's percentage : 0.0
 Total NaN values in row 5881 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5882 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5883 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 5884 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5885 :- 0 and it's percentage : 0.0
 Total NaN values in row 5886 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5887 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5888 :- 0 and it's percentage : 0.0
 Total NaN values in row 5889 :- 0 and it's percentage : 0.0
 Total NaN values in row 5890 :- 0 and it's percentage : 0.0
 Total NaN values in row 5891 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5892 :- 0 and it's percentage : 0.0
 Total NaN values in row 5893 :- 0 and it's percentage : 0.0
 Total NaN values in row 5894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5895 :- 0 and it's percentage : 0.0
 Total NaN values in row 5896 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5898 :- 0 and it's percentage : 0.0
 Total NaN values in row 5899 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5900 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5901 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5902 :- 0 and it's percentage : 0.0
 Total NaN values in row 5903 :- 0 and it's percentage : 0.0
 Total NaN values in row 5904 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5905 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5906 :- 0 and it's percentage : 0.0
 Total NaN values in row 5907 :- 0 and it's percentage : 0.0
 Total NaN values in row 5908 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5909 :- 0 and it's percentage : 0.0
 Total NaN values in row 5910 :- 0 and it's percentage : 0.0
 Total NaN values in row 5911 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5912 :- 0 and it's percentage : 0.0
 Total NaN values in row 5913 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5915 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5916 :- 0 and it's percentage : 0.0
 Total NaN values in row 5917 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5918 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5919 :- 0 and it's percentage : 0.0
 Total NaN values in row 5920 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5921 :- 0 and it's percentage : 0.0
 Total NaN values in row 5922 :- 0 and it's percentage : 0.0
 Total NaN values in row 5923 :- 0 and it's percentage : 0.0
 Total NaN values in row 5924 :- 0 and it's percentage : 0.0
 Total NaN values in row 5925 :- 0 and it's percentage : 0.0
 Total NaN values in row 5926 :- 0 and it's percentage : 0.0
 Total NaN values in row 5927 :- 0 and it's percentage : 0.0
 Total NaN values in row 5928 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5930 :- 0 and it's percentage : 0.0
 Total NaN values in row 5931 :- 0 and it's percentage : 0.0
 Total NaN values in row 5932 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5933 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5935 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5936 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5937 :- 0 and it's percentage : 0.0
 Total NaN values in row 5938 :- 0 and it's percentage : 0.0
 Total NaN values in row 5939 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5940 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5941 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5943 :- 0 and it's percentage : 0.0
 Total NaN values in row 5944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5945 :- 0 and it's percentage : 0.0
 Total NaN values in row 5946 :- 0 and it's percentage : 0.0
 Total NaN values in row 5947 :- 0 and it's percentage : 0.0
 Total NaN values in row 5948 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5949 :- 0 and it's percentage : 0.0
 Total NaN values in row 5950 :- 0 and it's percentage : 0.0
 Total NaN values in row 5951 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5955 :- 0 and it's percentage : 0.0
 Total NaN values in row 5956 :- 0 and it's percentage : 0.0
 Total NaN values in row 5957 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5958 :- 0 and it's percentage : 0.0
 Total NaN values in row 5959 :- 0 and it's percentage : 0.0
 Total NaN values in row 5960 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5961 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5962 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5963 :- 0 and it's percentage : 0.0
 Total NaN values in row 5964 :- 0 and it's percentage : 0.0
 Total NaN values in row 5965 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5966 :- 0 and it's percentage : 0.0
 Total NaN values in row 5967 :- 0 and it's percentage : 0.0
 Total NaN values in row 5968 :- 0 and it's percentage : 0.0
 Total NaN values in row 5969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5970 :- 0 and it's percentage : 0.0
 Total NaN values in row 5971 :- 0 and it's percentage : 0.0
 Total NaN values in row 5972 :- 0 and it's percentage : 0.0
 Total NaN values in row 5973 :- 0 and it's percentage : 0.0
 Total NaN values in row 5974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5976 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5977 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5978 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5979 :- 0 and it's percentage : 0.0
 Total NaN values in row 5980 :- 0 and it's percentage : 0.0
 Total NaN values in row 5981 :- 0 and it's percentage : 0.0
 Total NaN values in row 5982 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5983 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 5984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5985 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5986 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 5987 :- 0 and it's percentage : 0.0
 Total NaN values in row 5988 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 5989 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5992 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5993 :- 0 and it's percentage : 0.0
 Total NaN values in row 5994 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5995 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 5996 :- 0 and it's percentage : 0.0
 Total NaN values in row 5997 :- 0 and it's percentage : 0.0
 Total NaN values in row 5998 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 5999 :- 0 and it's percentage : 0.0
 Total NaN values in row 6000 :- 0 and it's percentage : 0.0
 Total NaN values in row 6001 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6002 :- 0 and it's percentage : 0.0
 Total NaN values in row 6003 :- 0 and it's percentage : 0.0
 Total NaN values in row 6004 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6005 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6006 :- 0 and it's percentage : 0.0
 Total NaN values in row 6007 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6008 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6010 :- 0 and it's percentage : 0.0
 Total NaN values in row 6011 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6012 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 6013 :- 0 and it's percentage : 0.0
 Total NaN values in row 6014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6015 :- 0 and it's percentage : 0.0
 Total NaN values in row 6016 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6017 :- 0 and it's percentage : 0.0
 Total NaN values in row 6018 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6019 :- 0 and it's percentage : 0.0
 Total NaN values in row 6020 :- 0 and it's percentage : 0.0
 Total NaN values in row 6021 :- 0 and it's percentage : 0.0
 Total NaN values in row 6022 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6023 :- 0 and it's percentage : 0.0
 Total NaN values in row 6024 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6025 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6026 :- 0 and it's percentage : 0.0
 Total NaN values in row 6027 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6029 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6030 :- 0 and it's percentage : 0.0
 Total NaN values in row 6031 :- 0 and it's percentage : 0.0
 Total NaN values in row 6032 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6033 :- 0 and it's percentage : 0.0
 Total NaN values in row 6034 :- 0 and it's percentage : 0.0
 Total NaN values in row 6035 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6036 :- 0 and it's percentage : 0.0
 Total NaN values in row 6037 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6038 :- 0 and it's percentage : 0.0
 Total NaN values in row 6039 :- 0 and it's percentage : 0.0
 Total NaN values in row 6040 :- 0 and it's percentage : 0.0
 Total NaN values in row 6041 :- 0 and it's percentage : 0.0
 Total NaN values in row 6042 :- 0 and it's percentage : 0.0
 Total NaN values in row 6043 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6044 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6045 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6047 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6048 :- 0 and it's percentage : 0.0
 Total NaN values in row 6049 :- 0 and it's percentage : 0.0
 Total NaN values in row 6050 :- 0 and it's percentage : 0.0
 Total NaN values in row 6051 :- 0 and it's percentage : 0.0
 Total NaN values in row 6052 :- 0 and it's percentage : 0.0
 Total NaN values in row 6053 :- 0 and it's percentage : 0.0
 Total NaN values in row 6054 :- 0 and it's percentage : 0.0
 Total NaN values in row 6055 :- 0 and it's percentage : 0.0
 Total NaN values in row 6056 :- 0 and it's percentage : 0.0
 Total NaN values in row 6057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6058 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6059 :- 0 and it's percentage : 0.0
 Total NaN values in row 6060 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6061 :- 0 and it's percentage : 0.0
 Total NaN values in row 6062 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6063 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6064 :- 0 and it's percentage : 0.0
 Total NaN values in row 6065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6066 :- 0 and it's percentage : 0.0
 Total NaN values in row 6067 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6068 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6069 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6070 :- 0 and it's percentage : 0.0
 Total NaN values in row 6071 :- 0 and it's percentage : 0.0
 Total NaN values in row 6072 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6073 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6074 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 6075 :- 0 and it's percentage : 0.0
 Total NaN values in row 6076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6077 :- 0 and it's percentage : 0.0
 Total NaN values in row 6078 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6079 :- 0 and it's percentage : 0.0
 Total NaN values in row 6080 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6081 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6082 :- 0 and it's percentage : 0.0
 Total NaN values in row 6083 :- 0 and it's percentage : 0.0
 Total NaN values in row 6084 :- 0 and it's percentage : 0.0
 Total NaN values in row 6085 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6087 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 6088 :- 0 and it's percentage : 0.0
 Total NaN values in row 6089 :- 0 and it's percentage : 0.0
 Total NaN values in row 6090 :- 0 and it's percentage : 0.0
 Total NaN values in row 6091 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6092 :- 0 and it's percentage : 0.0
 Total NaN values in row 6093 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6094 :- 0 and it's percentage : 0.0
 Total NaN values in row 6095 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6096 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6097 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6098 :- 0 and it's percentage : 0.0
 Total NaN values in row 6099 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6100 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6101 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6102 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6103 :- 0 and it's percentage : 0.0
 Total NaN values in row 6104 :- 0 and it's percentage : 0.0
 Total NaN values in row 6105 :- 0 and it's percentage : 0.0
 Total NaN values in row 6106 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6107 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6108 :- 0 and it's percentage : 0.0
 Total NaN values in row 6109 :- 0 and it's percentage : 0.0
 Total NaN values in row 6110 :- 0 and it's percentage : 0.0
 Total NaN values in row 6111 :- 0 and it's percentage : 0.0
 Total NaN values in row 6112 :- 0 and it's percentage : 0.0
 Total NaN values in row 6113 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6114 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6115 :- 0 and it's percentage : 0.0
 Total NaN values in row 6116 :- 0 and it's percentage : 0.0
 Total NaN values in row 6117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6118 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6119 :- 0 and it's percentage : 0.0
 Total NaN values in row 6120 :- 0 and it's percentage : 0.0
 Total NaN values in row 6121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6122 :- 0 and it's percentage : 0.0
 Total NaN values in row 6123 :- 0 and it's percentage : 0.0
 Total NaN values in row 6124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6125 :- 0 and it's percentage : 0.0
 Total NaN values in row 6126 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6127 :- 0 and it's percentage : 0.0
 Total NaN values in row 6128 :- 0 and it's percentage : 0.0
 Total NaN values in row 6129 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 6130 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6131 :- 0 and it's percentage : 0.0
 Total NaN values in row 6132 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6133 :- 0 and it's percentage : 0.0
 Total NaN values in row 6134 :- 0 and it's percentage : 0.0
 Total NaN values in row 6135 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6136 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6138 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6139 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6143 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6144 :- 0 and it's percentage : 0.0
 Total NaN values in row 6145 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6146 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6147 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6148 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6149 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6150 :- 0 and it's percentage : 0.0
 Total NaN values in row 6151 :- 0 and it's percentage : 0.0
 Total NaN values in row 6152 :- 0 and it's percentage : 0.0
 Total NaN values in row 6153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6154 :- 0 and it's percentage : 0.0
 Total NaN values in row 6155 :- 0 and it's percentage : 0.0
 Total NaN values in row 6156 :- 0 and it's percentage : 0.0
 Total NaN values in row 6157 :- 0 and it's percentage : 0.0
 Total NaN values in row 6158 :- 0 and it's percentage : 0.0
 Total NaN values in row 6159 :- 0 and it's percentage : 0.0
 Total NaN values in row 6160 :- 0 and it's percentage : 0.0
 Total NaN values in row 6161 :- 0 and it's percentage : 0.0
 Total NaN values in row 6162 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6163 :- 0 and it's percentage : 0.0
 Total NaN values in row 6164 :- 0 and it's percentage : 0.0
 Total NaN values in row 6165 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6166 :- 0 and it's percentage : 0.0
 Total NaN values in row 6167 :- 0 and it's percentage : 0.0
 Total NaN values in row 6168 :- 0 and it's percentage : 0.0
 Total NaN values in row 6169 :- 0 and it's percentage : 0.0
 Total NaN values in row 6170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6171 :- 0 and it's percentage : 0.0
 Total NaN values in row 6172 :- 0 and it's percentage : 0.0
 Total NaN values in row 6173 :- 0 and it's percentage : 0.0
 Total NaN values in row 6174 :- 0 and it's percentage : 0.0
 Total NaN values in row 6175 :- 0 and it's percentage : 0.0
 Total NaN values in row 6176 :- 0 and it's percentage : 0.0
 Total NaN values in row 6177 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6178 :- 0 and it's percentage : 0.0
 Total NaN values in row 6179 :- 0 and it's percentage : 0.0
 Total NaN values in row 6180 :- 0 and it's percentage : 0.0
 Total NaN values in row 6181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6182 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6183 :- 0 and it's percentage : 0.0
 Total NaN values in row 6184 :- 0 and it's percentage : 0.0
 Total NaN values in row 6185 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6186 :- 0 and it's percentage : 0.0
 Total NaN values in row 6187 :- 0 and it's percentage : 0.0
 Total NaN values in row 6188 :- 0 and it's percentage : 0.0
 Total NaN values in row 6189 :- 0 and it's percentage : 0.0
 Total NaN values in row 6190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6191 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6192 :- 0 and it's percentage : 0.0
 Total NaN values in row 6193 :- 0 and it's percentage : 0.0
 Total NaN values in row 6194 :- 0 and it's percentage : 0.0
 Total NaN values in row 6195 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6196 :- 0 and it's percentage : 0.0
 Total NaN values in row 6197 :- 0 and it's percentage : 0.0
 Total NaN values in row 6198 :- 0 and it's percentage : 0.0
 Total NaN values in row 6199 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6200 :- 0 and it's percentage : 0.0
 Total NaN values in row 6201 :- 0 and it's percentage : 0.0
 Total NaN values in row 6202 :- 0 and it's percentage : 0.0
 Total NaN values in row 6203 :- 0 and it's percentage : 0.0
 Total NaN values in row 6204 :- 0 and it's percentage : 0.0
 Total NaN values in row 6205 :- 0 and it's percentage : 0.0
 Total NaN values in row 6206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6207 :- 0 and it's percentage : 0.0
 Total NaN values in row 6208 :- 0 and it's percentage : 0.0
 Total NaN values in row 6209 :- 0 and it's percentage : 0.0
 Total NaN values in row 6210 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6211 :- 0 and it's percentage : 0.0
 Total NaN values in row 6212 :- 0 and it's percentage : 0.0
 Total NaN values in row 6213 :- 0 and it's percentage : 0.0
 Total NaN values in row 6214 :- 0 and it's percentage : 0.0
 Total NaN values in row 6215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6216 :- 0 and it's percentage : 0.0
 Total NaN values in row 6217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6218 :- 0 and it's percentage : 0.0
 Total NaN values in row 6219 :- 0 and it's percentage : 0.0
 Total NaN values in row 6220 :- 0 and it's percentage : 0.0
 Total NaN values in row 6221 :- 0 and it's percentage : 0.0
 Total NaN values in row 6222 :- 0 and it's percentage : 0.0
 Total NaN values in row 6223 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6224 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6225 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6226 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6227 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6228 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6230 :- 0 and it's percentage : 0.0
 Total NaN values in row 6231 :- 0 and it's percentage : 0.0
 Total NaN values in row 6232 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6233 :- 0 and it's percentage : 0.0
 Total NaN values in row 6234 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6235 :- 0 and it's percentage : 0.0
 Total NaN values in row 6236 :- 0 and it's percentage : 0.0
 Total NaN values in row 6237 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6238 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6239 :- 0 and it's percentage : 0.0
 Total NaN values in row 6240 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6241 :- 0 and it's percentage : 0.0
 Total NaN values in row 6242 :- 0 and it's percentage : 0.0
 Total NaN values in row 6243 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6245 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6246 :- 0 and it's percentage : 0.0
 Total NaN values in row 6247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6248 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6249 :- 0 and it's percentage : 0.0
 Total NaN values in row 6250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6251 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6252 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6253 :- 0 and it's percentage : 0.0
 Total NaN values in row 6254 :- 0 and it's percentage : 0.0
 Total NaN values in row 6255 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6256 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6259 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6260 :- 0 and it's percentage : 0.0
 Total NaN values in row 6261 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6262 :- 0 and it's percentage : 0.0
 Total NaN values in row 6263 :- 0 and it's percentage : 0.0
 Total NaN values in row 6264 :- 0 and it's percentage : 0.0
 Total NaN values in row 6265 :- 0 and it's percentage : 0.0
 Total NaN values in row 6266 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6267 :- 0 and it's percentage : 0.0
 Total NaN values in row 6268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6269 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6271 :- 0 and it's percentage : 0.0
 Total NaN values in row 6272 :- 0 and it's percentage : 0.0
 Total NaN values in row 6273 :- 0 and it's percentage : 0.0
 Total NaN values in row 6274 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6275 :- 0 and it's percentage : 0.0
 Total NaN values in row 6276 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6277 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6279 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6280 :- 0 and it's percentage : 0.0
 Total NaN values in row 6281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6283 :- 0 and it's percentage : 0.0
 Total NaN values in row 6284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6285 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6286 :- 0 and it's percentage : 0.0

 Total NaN values in row 6287 :- 0 and it's percentage : 0.0
 Total NaN values in row 6288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6289 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6290 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6291 :- 0 and it's percentage : 0.0
 Total NaN values in row 6292 :- 0 and it's percentage : 0.0
 Total NaN values in row 6293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6294 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6295 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6296 :- 0 and it's percentage : 0.0
 Total NaN values in row 6297 :- 0 and it's percentage : 0.0
 Total NaN values in row 6298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6300 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6301 :- 0 and it's percentage : 0.0
 Total NaN values in row 6302 :- 0 and it's percentage : 0.0
 Total NaN values in row 6303 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6304 :- 0 and it's percentage : 0.0
 Total NaN values in row 6305 :- 0 and it's percentage : 0.0
 Total NaN values in row 6306 :- 0 and it's percentage : 0.0
 Total NaN values in row 6307 :- 0 and it's percentage : 0.0
 Total NaN values in row 6308 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6309 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6310 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6311 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6312 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6313 :- 0 and it's percentage : 0.0
 Total NaN values in row 6314 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6315 :- 0 and it's percentage : 0.0
 Total NaN values in row 6316 :- 0 and it's percentage : 0.0
 Total NaN values in row 6317 :- 0 and it's percentage : 0.0
 Total NaN values in row 6318 :- 0 and it's percentage : 0.0
 Total NaN values in row 6319 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6320 :- 0 and it's percentage : 0.0
 Total NaN values in row 6321 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6323 :- 0 and it's percentage : 0.0
 Total NaN values in row 6324 :- 0 and it's percentage : 0.0
 Total NaN values in row 6325 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6326 :- 0 and it's percentage : 0.0
 Total NaN values in row 6327 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6329 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6331 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6332 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6333 :- 0 and it's percentage : 0.0
 Total NaN values in row 6334 :- 0 and it's percentage : 0.0
 Total NaN values in row 6335 :- 0 and it's percentage : 0.0
 Total NaN values in row 6336 :- 0 and it's percentage : 0.0
 Total NaN values in row 6337 :- 0 and it's percentage : 0.0
 Total NaN values in row 6338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6339 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6340 :- 0 and it's percentage : 0.0
 Total NaN values in row 6341 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6342 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6343 :- 0 and it's percentage : 0.0
 Total NaN values in row 6344 :- 0 and it's percentage : 0.0
 Total NaN values in row 6345 :- 0 and it's percentage : 0.0
 Total NaN values in row 6346 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6347 :- 0 and it's percentage : 0.0
 Total NaN values in row 6348 :- 0 and it's percentage : 0.0
 Total NaN values in row 6349 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6350 :- 0 and it's percentage : 0.0
 Total NaN values in row 6351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6352 :- 0 and it's percentage : 0.0
 Total NaN values in row 6353 :- 0 and it's percentage : 0.0
 Total NaN values in row 6354 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6355 :- 0 and it's percentage : 0.0
 Total NaN values in row 6356 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6357 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6358 :- 0 and it's percentage : 0.0
 Total NaN values in row 6359 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6360 :- 0 and it's percentage : 0.0
 Total NaN values in row 6361 :- 0 and it's percentage : 0.0
 Total NaN values in row 6362 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6364 :- 0 and it's percentage : 0.0
 Total NaN values in row 6365 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6367 :- 0 and it's percentage : 0.0
 Total NaN values in row 6368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6369 :- 0 and it's percentage : 0.0
 Total NaN values in row 6370 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6371 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6372 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6373 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6376 :- 0 and it's percentage : 0.0
 Total NaN values in row 6377 :- 0 and it's percentage : 0.0
 Total NaN values in row 6378 :- 0 and it's percentage : 0.0
 Total NaN values in row 6379 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6380 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6381 :- 0 and it's percentage : 0.0
 Total NaN values in row 6382 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6383 :- 0 and it's percentage : 0.0
 Total NaN values in row 6384 :- 0 and it's percentage : 0.0
 Total NaN values in row 6385 :- 0 and it's percentage : 0.0
 Total NaN values in row 6386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6387 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6389 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6390 :- 0 and it's percentage : 0.0
 Total NaN values in row 6391 :- 0 and it's percentage : 0.0
 Total NaN values in row 6392 :- 0 and it's percentage : 0.0
 Total NaN values in row 6393 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6394 :- 0 and it's percentage : 0.0
 Total NaN values in row 6395 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6396 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6398 :- 0 and it's percentage : 0.0
 Total NaN values in row 6399 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6401 :- 0 and it's percentage : 0.0
 Total NaN values in row 6402 :- 0 and it's percentage : 0.0
 Total NaN values in row 6403 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6404 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6405 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6406 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6408 :- 0 and it's percentage : 0.0
 Total NaN values in row 6409 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6410 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6411 :- 0 and it's percentage : 0.0
 Total NaN values in row 6412 :- 0 and it's percentage : 0.0
 Total NaN values in row 6413 :- 0 and it's percentage : 0.0

 Total NaN values in row 6414 :- 0 and it's percentage : 0.0
 Total NaN values in row 6415 :- 0 and it's percentage : 0.0
 Total NaN values in row 6416 :- 0 and it's percentage : 0.0
 Total NaN values in row 6417 :- 0 and it's percentage : 0.0
 Total NaN values in row 6418 :- 0 and it's percentage : 0.0
 Total NaN values in row 6419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6420 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6421 :- 0 and it's percentage : 0.0
 Total NaN values in row 6422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6423 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6424 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6425 :- 0 and it's percentage : 0.0
 Total NaN values in row 6426 :- 0 and it's percentage : 0.0
 Total NaN values in row 6427 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6428 :- 0 and it's percentage : 0.0
 Total NaN values in row 6429 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6432 :- 0 and it's percentage : 0.0
 Total NaN values in row 6433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6434 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6435 :- 0 and it's percentage : 0.0
 Total NaN values in row 6436 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6437 :- 0 and it's percentage : 0.0
 Total NaN values in row 6438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6439 :- 0 and it's percentage : 0.0
 Total NaN values in row 6440 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6442 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6443 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6444 :- 0 and it's percentage : 0.0
 Total NaN values in row 6445 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6447 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6448 :- 0 and it's percentage : 0.0
 Total NaN values in row 6449 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6450 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6451 :- 0 and it's percentage : 0.0
 Total NaN values in row 6452 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6453 :- 0 and it's percentage : 0.0
 Total NaN values in row 6454 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6455 :- 0 and it's percentage : 0.0
 Total NaN values in row 6456 :- 0 and it's percentage : 0.0
 Total NaN values in row 6457 :- 0 and it's percentage : 0.0
 Total NaN values in row 6458 :- 0 and it's percentage : 0.0
 Total NaN values in row 6459 :- 0 and it's percentage : 0.0
 Total NaN values in row 6460 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6461 :- 0 and it's percentage : 0.0
 Total NaN values in row 6462 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6463 :- 0 and it's percentage : 0.0
 Total NaN values in row 6464 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6465 :- 0 and it's percentage : 0.0
 Total NaN values in row 6466 :- 0 and it's percentage : 0.0
 Total NaN values in row 6467 :- 0 and it's percentage : 0.0
 Total NaN values in row 6468 :- 0 and it's percentage : 0.0
 Total NaN values in row 6469 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6470 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6471 :- 0 and it's percentage : 0.0
 Total NaN values in row 6472 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6474 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6475 :- 0 and it's percentage : 0.0
 Total NaN values in row 6476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6478 :- 0 and it's percentage : 0.0
 Total NaN values in row 6479 :- 0 and it's percentage : 0.0
 Total NaN values in row 6480 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6481 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6482 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6483 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6486 :- 0 and it's percentage : 0.0
 Total NaN values in row 6487 :- 0 and it's percentage : 0.0
 Total NaN values in row 6488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6489 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6490 :- 0 and it's percentage : 0.0
 Total NaN values in row 6491 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6492 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6493 :- 0 and it's percentage : 0.0
 Total NaN values in row 6494 :- 0 and it's percentage : 0.0
 Total NaN values in row 6495 :- 0 and it's percentage : 0.0
 Total NaN values in row 6496 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6497 :- 0 and it's percentage : 0.0
 Total NaN values in row 6498 :- 0 and it's percentage : 0.0
 Total NaN values in row 6499 :- 0 and it's percentage : 0.0
 Total NaN values in row 6500 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6501 :- 0 and it's percentage : 0.0
 Total NaN values in row 6502 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6503 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6504 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6505 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6507 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6508 :- 0 and it's percentage : 0.0
 Total NaN values in row 6509 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6510 :- 0 and it's percentage : 0.0
 Total NaN values in row 6511 :- 0 and it's percentage : 0.0
 Total NaN values in row 6512 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6513 :- 0 and it's percentage : 0.0
 Total NaN values in row 6514 :- 0 and it's percentage : 0.0
 Total NaN values in row 6515 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6517 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6519 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6520 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6521 :- 0 and it's percentage : 0.0
 Total NaN values in row 6522 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6523 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6524 :- 0 and it's percentage : 0.0
 Total NaN values in row 6525 :- 0 and it's percentage : 0.0
 Total NaN values in row 6526 :- 0 and it's percentage : 0.0
 Total NaN values in row 6527 :- 0 and it's percentage : 0.0
 Total NaN values in row 6528 :- 0 and it's percentage : 0.0
 Total NaN values in row 6529 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6530 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6531 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6532 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6534 :- 0 and it's percentage : 0.0

 Total NaN values in row 6535 :- 0 and it's percentage : 0.0
 Total NaN values in row 6536 :- 0 and it's percentage : 0.0
 Total NaN values in row 6537 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6538 :- 0 and it's percentage : 0.0
 Total NaN values in row 6539 :- 0 and it's percentage : 0.0
 Total NaN values in row 6540 :- 0 and it's percentage : 0.0
 Total NaN values in row 6541 :- 0 and it's percentage : 0.0
 Total NaN values in row 6542 :- 0 and it's percentage : 0.0
 Total NaN values in row 6543 :- 0 and it's percentage : 0.0
 Total NaN values in row 6544 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6545 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6546 :- 0 and it's percentage : 0.0
 Total NaN values in row 6547 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6548 :- 0 and it's percentage : 0.0
 Total NaN values in row 6549 :- 0 and it's percentage : 0.0
 Total NaN values in row 6550 :- 0 and it's percentage : 0.0
 Total NaN values in row 6551 :- 0 and it's percentage : 0.0
 Total NaN values in row 6552 :- 0 and it's percentage : 0.0
 Total NaN values in row 6553 :- 0 and it's percentage : 0.0
 Total NaN values in row 6554 :- 0 and it's percentage : 0.0
 Total NaN values in row 6555 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6556 :- 0 and it's percentage : 0.0
 Total NaN values in row 6557 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6558 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6559 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6560 :- 0 and it's percentage : 0.0
 Total NaN values in row 6561 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6562 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6563 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6564 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6566 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6567 :- 0 and it's percentage : 0.0
 Total NaN values in row 6568 :- 0 and it's percentage : 0.0
 Total NaN values in row 6569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6570 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6571 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6572 :- 0 and it's percentage : 0.0
 Total NaN values in row 6573 :- 0 and it's percentage : 0.0
 Total NaN values in row 6574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6575 :- 0 and it's percentage : 0.0
 Total NaN values in row 6576 :- 0 and it's percentage : 0.0
 Total NaN values in row 6577 :- 0 and it's percentage : 0.0
 Total NaN values in row 6578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6579 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6580 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6581 :- 0 and it's percentage : 0.0
 Total NaN values in row 6582 :- 0 and it's percentage : 0.0
 Total NaN values in row 6583 :- 0 and it's percentage : 0.0
 Total NaN values in row 6584 :- 0 and it's percentage : 0.0
 Total NaN values in row 6585 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6586 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6587 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6588 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6589 :- 0 and it's percentage : 0.0
 Total NaN values in row 6590 :- 0 and it's percentage : 0.0
 Total NaN values in row 6591 :- 0 and it's percentage : 0.0
 Total NaN values in row 6592 :- 0 and it's percentage : 0.0
 Total NaN values in row 6593 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6594 :- 0 and it's percentage : 0.0
 Total NaN values in row 6595 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6596 :- 0 and it's percentage : 0.0
 Total NaN values in row 6597 :- 0 and it's percentage : 0.0
 Total NaN values in row 6598 :- 0 and it's percentage : 0.0
 Total NaN values in row 6599 :- 0 and it's percentage : 0.0
 Total NaN values in row 6600 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6601 :- 0 and it's percentage : 0.0
 Total NaN values in row 6602 :- 0 and it's percentage : 0.0
 Total NaN values in row 6603 :- 0 and it's percentage : 0.0
 Total NaN values in row 6604 :- 0 and it's percentage : 0.0
 Total NaN values in row 6605 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6606 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6607 :- 0 and it's percentage : 0.0
 Total NaN values in row 6608 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6609 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6610 :- 0 and it's percentage : 0.0
 Total NaN values in row 6611 :- 0 and it's percentage : 0.0
 Total NaN values in row 6612 :- 0 and it's percentage : 0.0
 Total NaN values in row 6613 :- 0 and it's percentage : 0.0
 Total NaN values in row 6614 :- 0 and it's percentage : 0.0
 Total NaN values in row 6615 :- 0 and it's percentage : 0.0
 Total NaN values in row 6616 :- 0 and it's percentage : 0.0
 Total NaN values in row 6617 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6618 :- 0 and it's percentage : 0.0
 Total NaN values in row 6619 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6620 :- 0 and it's percentage : 0.0
 Total NaN values in row 6621 :- 0 and it's percentage : 0.0
 Total NaN values in row 6622 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6623 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6624 :- 0 and it's percentage : 0.0
 Total NaN values in row 6625 :- 0 and it's percentage : 0.0
 Total NaN values in row 6626 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6627 :- 0 and it's percentage : 0.0
 Total NaN values in row 6628 :- 0 and it's percentage : 0.0
 Total NaN values in row 6629 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6630 :- 0 and it's percentage : 0.0
 Total NaN values in row 6631 :- 0 and it's percentage : 0.0
 Total NaN values in row 6632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6633 :- 0 and it's percentage : 0.0
 Total NaN values in row 6634 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6635 :- 0 and it's percentage : 0.0
 Total NaN values in row 6636 :- 0 and it's percentage : 0.0
 Total NaN values in row 6637 :- 0 and it's percentage : 0.0
 Total NaN values in row 6638 :- 0 and it's percentage : 0.0
 Total NaN values in row 6639 :- 0 and it's percentage : 0.0
 Total NaN values in row 6640 :- 0 and it's percentage : 0.0
 Total NaN values in row 6641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6642 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6643 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6644 :- 0 and it's percentage : 0.0
 Total NaN values in row 6645 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6646 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6647 :- 0 and it's percentage : 0.0
 Total NaN values in row 6648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6649 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6650 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6651 :- 0 and it's percentage : 0.0
 Total NaN values in row 6652 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6653 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6654 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6655 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6656 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 6657 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6658 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6659 :- 0 and it's percentage : 0.0
 Total NaN values in row 6660 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6661 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6663 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6664 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6665 :- 0 and it's percentage : 0.0
 Total NaN values in row 6666 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6667 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6668 :- 0 and it's percentage : 0.0
 Total NaN values in row 6669 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6670 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6671 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6672 :- 0 and it's percentage : 0.0
 Total NaN values in row 6673 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6674 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6675 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6676 :- 0 and it's percentage : 0.0
 Total NaN values in row 6677 :- 0 and it's percentage : 0.0
 Total NaN values in row 6678 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6679 :- 0 and it's percentage : 0.0
 Total NaN values in row 6680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6681 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6682 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6683 :- 0 and it's percentage : 0.0
 Total NaN values in row 6684 :- 0 and it's percentage : 0.0
 Total NaN values in row 6685 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6686 :- 0 and it's percentage : 0.0
 Total NaN values in row 6687 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6688 :- 0 and it's percentage : 0.0
 Total NaN values in row 6689 :- 0 and it's percentage : 0.0
 Total NaN values in row 6690 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6691 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6693 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6694 :- 0 and it's percentage : 0.0
 Total NaN values in row 6695 :- 0 and it's percentage : 0.0
 Total NaN values in row 6696 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6697 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6698 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6699 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6701 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6702 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6703 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6705 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6706 :- 0 and it's percentage : 0.0
 Total NaN values in row 6707 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6708 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6709 :- 0 and it's percentage : 0.0
 Total NaN values in row 6710 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6711 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6712 :- 0 and it's percentage : 0.0
 Total NaN values in row 6713 :- 0 and it's percentage : 0.0
 Total NaN values in row 6714 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6715 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6716 :- 0 and it's percentage : 0.0
 Total NaN values in row 6717 :- 0 and it's percentage : 0.0
 Total NaN values in row 6718 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6719 :- 0 and it's percentage : 0.0
 Total NaN values in row 6720 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6721 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6722 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6723 :- 0 and it's percentage : 0.0
 Total NaN values in row 6724 :- 0 and it's percentage : 0.0
 Total NaN values in row 6725 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6726 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6727 :- 0 and it's percentage : 0.0
 Total NaN values in row 6728 :- 0 and it's percentage : 0.0
 Total NaN values in row 6729 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6730 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6731 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6732 :- 0 and it's percentage : 0.0
 Total NaN values in row 6733 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6734 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6735 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6736 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6737 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6738 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6739 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6740 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6741 :- 0 and it's percentage : 0.0
 Total NaN values in row 6742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6743 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6744 :- 0 and it's percentage : 0.0
 Total NaN values in row 6745 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6746 :- 0 and it's percentage : 0.0
 Total NaN values in row 6747 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6748 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6749 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6750 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6751 :- 0 and it's percentage : 0.0
 Total NaN values in row 6752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6753 :- 0 and it's percentage : 0.0
 Total NaN values in row 6754 :- 0 and it's percentage : 0.0
 Total NaN values in row 6755 :- 0 and it's percentage : 0.0
 Total NaN values in row 6756 :- 0 and it's percentage : 0.0
 Total NaN values in row 6757 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6758 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6759 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6760 :- 0 and it's percentage : 0.0
 Total NaN values in row 6761 :- 0 and it's percentage : 0.0
 Total NaN values in row 6762 :- 0 and it's percentage : 0.0
 Total NaN values in row 6763 :- 0 and it's percentage : 0.0
 Total NaN values in row 6764 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6765 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6766 :- 0 and it's percentage : 0.0
 Total NaN values in row 6767 :- 0 and it's percentage : 0.0
 Total NaN values in row 6768 :- 0 and it's percentage : 0.0
 Total NaN values in row 6769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6770 :- 0 and it's percentage : 0.0
 Total NaN values in row 6771 :- 0 and it's percentage : 0.0
 Total NaN values in row 6772 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6773 :- 0 and it's percentage : 0.0
 Total NaN values in row 6774 :- 0 and it's percentage : 0.0
 Total NaN values in row 6775 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6776 :- 0 and it's percentage : 0.0

 Total NaN values in row 6777 :- 0 and it's percentage : 0.0
 Total NaN values in row 6778 :- 0 and it's percentage : 0.0
 Total NaN values in row 6779 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6780 :- 0 and it's percentage : 0.0
 Total NaN values in row 6781 :- 0 and it's percentage : 0.0
 Total NaN values in row 6782 :- 0 and it's percentage : 0.0
 Total NaN values in row 6783 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6784 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6785 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6786 :- 0 and it's percentage : 0.0
 Total NaN values in row 6787 :- 0 and it's percentage : 0.0
 Total NaN values in row 6788 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6789 :- 0 and it's percentage : 0.0
 Total NaN values in row 6790 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6791 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6792 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6793 :- 0 and it's percentage : 0.0
 Total NaN values in row 6794 :- 0 and it's percentage : 0.0
 Total NaN values in row 6795 :- 0 and it's percentage : 0.0
 Total NaN values in row 6796 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6797 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6798 :- 0 and it's percentage : 0.0
 Total NaN values in row 6799 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6800 :- 0 and it's percentage : 0.0
 Total NaN values in row 6801 :- 0 and it's percentage : 0.0
 Total NaN values in row 6802 :- 0 and it's percentage : 0.0
 Total NaN values in row 6803 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6804 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 6805 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6806 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6807 :- 0 and it's percentage : 0.0
 Total NaN values in row 6808 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6809 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6810 :- 0 and it's percentage : 0.0
 Total NaN values in row 6811 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6812 :- 0 and it's percentage : 0.0
 Total NaN values in row 6813 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6814 :- 0 and it's percentage : 0.0
 Total NaN values in row 6815 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6816 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6817 :- 0 and it's percentage : 0.0
 Total NaN values in row 6818 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6819 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6820 :- 0 and it's percentage : 0.0
 Total NaN values in row 6821 :- 0 and it's percentage : 0.0
 Total NaN values in row 6822 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6823 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6824 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6825 :- 0 and it's percentage : 0.0
 Total NaN values in row 6826 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6827 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6828 :- 0 and it's percentage : 0.0
 Total NaN values in row 6829 :- 0 and it's percentage : 0.0
 Total NaN values in row 6830 :- 0 and it's percentage : 0.0
 Total NaN values in row 6831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6832 :- 0 and it's percentage : 0.0
 Total NaN values in row 6833 :- 0 and it's percentage : 0.0
 Total NaN values in row 6834 :- 0 and it's percentage : 0.0
 Total NaN values in row 6835 :- 0 and it's percentage : 0.0
 Total NaN values in row 6836 :- 0 and it's percentage : 0.0
 Total NaN values in row 6837 :- 0 and it's percentage : 0.0
 Total NaN values in row 6838 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6839 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6840 :- 0 and it's percentage : 0.0
 Total NaN values in row 6841 :- 0 and it's percentage : 0.0
 Total NaN values in row 6842 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6843 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6844 :- 0 and it's percentage : 0.0
 Total NaN values in row 6845 :- 0 and it's percentage : 0.0
 Total NaN values in row 6846 :- 0 and it's percentage : 0.0
 Total NaN values in row 6847 :- 0 and it's percentage : 0.0
 Total NaN values in row 6848 :- 0 and it's percentage : 0.0
 Total NaN values in row 6849 :- 0 and it's percentage : 0.0
 Total NaN values in row 6850 :- 0 and it's percentage : 0.0
 Total NaN values in row 6851 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6852 :- 0 and it's percentage : 0.0
 Total NaN values in row 6853 :- 0 and it's percentage : 0.0
 Total NaN values in row 6854 :- 0 and it's percentage : 0.0
 Total NaN values in row 6855 :- 0 and it's percentage : 0.0
 Total NaN values in row 6856 :- 0 and it's percentage : 0.0
 Total NaN values in row 6857 :- 0 and it's percentage : 0.0
 Total NaN values in row 6858 :- 0 and it's percentage : 0.0
 Total NaN values in row 6859 :- 0 and it's percentage : 0.0
 Total NaN values in row 6860 :- 0 and it's percentage : 0.0
 Total NaN values in row 6861 :- 0 and it's percentage : 0.0
 Total NaN values in row 6862 :- 0 and it's percentage : 0.0
 Total NaN values in row 6863 :- 0 and it's percentage : 0.0
 Total NaN values in row 6864 :- 0 and it's percentage : 0.0
 Total NaN values in row 6865 :- 0 and it's percentage : 0.0
 Total NaN values in row 6866 :- 0 and it's percentage : 0.0
 Total NaN values in row 6867 :- 0 and it's percentage : 0.0
 Total NaN values in row 6868 :- 0 and it's percentage : 0.0
 Total NaN values in row 6869 :- 0 and it's percentage : 0.0
 Total NaN values in row 6870 :- 0 and it's percentage : 0.0
 Total NaN values in row 6871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6872 :- 0 and it's percentage : 0.0
 Total NaN values in row 6873 :- 0 and it's percentage : 0.0
 Total NaN values in row 6874 :- 0 and it's percentage : 0.0
 Total NaN values in row 6875 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6876 :- 0 and it's percentage : 0.0
 Total NaN values in row 6877 :- 0 and it's percentage : 0.0
 Total NaN values in row 6878 :- 0 and it's percentage : 0.0
 Total NaN values in row 6879 :- 0 and it's percentage : 0.0
 Total NaN values in row 6880 :- 0 and it's percentage : 0.0
 Total NaN values in row 6881 :- 0 and it's percentage : 0.0
 Total NaN values in row 6882 :- 0 and it's percentage : 0.0
 Total NaN values in row 6883 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6884 :- 0 and it's percentage : 0.0
 Total NaN values in row 6885 :- 0 and it's percentage : 0.0
 Total NaN values in row 6886 :- 0 and it's percentage : 0.0
 Total NaN values in row 6887 :- 0 and it's percentage : 0.0
 Total NaN values in row 6888 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6889 :- 0 and it's percentage : 0.0
 Total NaN values in row 6890 :- 0 and it's percentage : 0.0
 Total NaN values in row 6891 :- 0 and it's percentage : 0.0
 Total NaN values in row 6892 :- 0 and it's percentage : 0.0
 Total NaN values in row 6893 :- 0 and it's percentage : 0.0
 Total NaN values in row 6894 :- 0 and it's percentage : 0.0
 Total NaN values in row 6895 :- 0 and it's percentage : 0.0
 Total NaN values in row 6896 :- 0 and it's percentage : 0.0
 Total NaN values in row 6897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6898 :- 0 and it's percentage : 0.0
 Total NaN values in row 6899 :- 0 and it's percentage : 0.0
 Total NaN values in row 6900 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6901 :- 0 and it's percentage : 0.0
 Total NaN values in row 6902 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6903 :- 0 and it's percentage : 0.0
 Total NaN values in row 6904 :- 0 and it's percentage : 0.0
 Total NaN values in row 6905 :- 0 and it's percentage : 0.0
 Total NaN values in row 6906 :- 0 and it's percentage : 0.0
 Total NaN values in row 6907 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 6908 :- 0 and it's percentage : 0.0
 Total NaN values in row 6909 :- 0 and it's percentage : 0.0
 Total NaN values in row 6910 :- 0 and it's percentage : 0.0
 Total NaN values in row 6911 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6912 :- 0 and it's percentage : 0.0
 Total NaN values in row 6913 :- 0 and it's percentage : 0.0
 Total NaN values in row 6914 :- 0 and it's percentage : 0.0
 Total NaN values in row 6915 :- 0 and it's percentage : 0.0
 Total NaN values in row 6916 :- 0 and it's percentage : 0.0
 Total NaN values in row 6917 :- 0 and it's percentage : 0.0
 Total NaN values in row 6918 :- 0 and it's percentage : 0.0
 Total NaN values in row 6919 :- 0 and it's percentage : 0.0
 Total NaN values in row 6920 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6921 :- 0 and it's percentage : 0.0
 Total NaN values in row 6922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6924 :- 0 and it's percentage : 0.0
 Total NaN values in row 6925 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6926 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 6927 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6928 :- 0 and it's percentage : 0.0
 Total NaN values in row 6929 :- 0 and it's percentage : 0.0
 Total NaN values in row 6930 :- 0 and it's percentage : 0.0
 Total NaN values in row 6931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6932 :- 0 and it's percentage : 0.0
 Total NaN values in row 6933 :- 0 and it's percentage : 0.0
 Total NaN values in row 6934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6935 :- 0 and it's percentage : 0.0
 Total NaN values in row 6936 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6937 :- 0 and it's percentage : 0.0
 Total NaN values in row 6938 :- 0 and it's percentage : 0.0
 Total NaN values in row 6939 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6940 :- 0 and it's percentage : 0.0
 Total NaN values in row 6941 :- 0 and it's percentage : 0.0
 Total NaN values in row 6942 :- 0 and it's percentage : 0.0
 Total NaN values in row 6943 :- 0 and it's percentage : 0.0
 Total NaN values in row 6944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6945 :- 0 and it's percentage : 0.0
 Total NaN values in row 6946 :- 0 and it's percentage : 0.0
 Total NaN values in row 6947 :- 0 and it's percentage : 0.0
 Total NaN values in row 6948 :- 0 and it's percentage : 0.0
 Total NaN values in row 6949 :- 0 and it's percentage : 0.0
 Total NaN values in row 6950 :- 0 and it's percentage : 0.0
 Total NaN values in row 6951 :- 0 and it's percentage : 0.0

 Total NaN values in row 6952 :- 0 and it's percentage : 0.0
 Total NaN values in row 6953 :- 0 and it's percentage : 0.0
 Total NaN values in row 6954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6955 :- 0 and it's percentage : 0.0
 Total NaN values in row 6956 :- 0 and it's percentage : 0.0
 Total NaN values in row 6957 :- 0 and it's percentage : 0.0
 Total NaN values in row 6958 :- 0 and it's percentage : 0.0
 Total NaN values in row 6959 :- 0 and it's percentage : 0.0
 Total NaN values in row 6960 :- 0 and it's percentage : 0.0
 Total NaN values in row 6961 :- 0 and it's percentage : 0.0
 Total NaN values in row 6962 :- 0 and it's percentage : 0.0
 Total NaN values in row 6963 :- 0 and it's percentage : 0.0
 Total NaN values in row 6964 :- 0 and it's percentage : 0.0
 Total NaN values in row 6965 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6966 :- 0 and it's percentage : 0.0
 Total NaN values in row 6967 :- 0 and it's percentage : 0.0
 Total NaN values in row 6968 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6969 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6970 :- 0 and it's percentage : 0.0
 Total NaN values in row 6971 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6972 :- 0 and it's percentage : 0.0
 Total NaN values in row 6973 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6974 :- 0 and it's percentage : 0.0
 Total NaN values in row 6975 :- 0 and it's percentage : 0.0
 Total NaN values in row 6976 :- 0 and it's percentage : 0.0
 Total NaN values in row 6977 :- 0 and it's percentage : 0.0
 Total NaN values in row 6978 :- 0 and it's percentage : 0.0
 Total NaN values in row 6979 :- 0 and it's percentage : 0.0
 Total NaN values in row 6980 :- 0 and it's percentage : 0.0
 Total NaN values in row 6981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6982 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6983 :- 0 and it's percentage : 0.0
 Total NaN values in row 6984 :- 0 and it's percentage : 0.0
 Total NaN values in row 6985 :- 0 and it's percentage : 0.0
 Total NaN values in row 6986 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 6987 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6988 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 6989 :- 0 and it's percentage : 0.0
 Total NaN values in row 6990 :- 0 and it's percentage : 0.0
 Total NaN values in row 6991 :- 0 and it's percentage : 0.0
 Total NaN values in row 6992 :- 0 and it's percentage : 0.0
 Total NaN values in row 6993 :- 0 and it's percentage : 0.0
 Total NaN values in row 6994 :- 0 and it's percentage : 0.0
 Total NaN values in row 6995 :- 0 and it's percentage : 0.0
 Total NaN values in row 6996 :- 0 and it's percentage : 0.0
 Total NaN values in row 6997 :- 0 and it's percentage : 0.0
 Total NaN values in row 6998 :- 0 and it's percentage : 0.0
 Total NaN values in row 6999 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7000 :- 0 and it's percentage : 0.0
 Total NaN values in row 7001 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7002 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7003 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7004 :- 0 and it's percentage : 0.0
 Total NaN values in row 7005 :- 0 and it's percentage : 0.0
 Total NaN values in row 7006 :- 0 and it's percentage : 0.0
 Total NaN values in row 7007 :- 0 and it's percentage : 0.0
 Total NaN values in row 7008 :- 0 and it's percentage : 0.0
 Total NaN values in row 7009 :- 0 and it's percentage : 0.0
 Total NaN values in row 7010 :- 0 and it's percentage : 0.0
 Total NaN values in row 7011 :- 0 and it's percentage : 0.0
 Total NaN values in row 7012 :- 0 and it's percentage : 0.0
 Total NaN values in row 7013 :- 0 and it's percentage : 0.0
 Total NaN values in row 7014 :- 0 and it's percentage : 0.0
 Total NaN values in row 7015 :- 0 and it's percentage : 0.0
 Total NaN values in row 7016 :- 0 and it's percentage : 0.0
 Total NaN values in row 7017 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7018 :- 0 and it's percentage : 0.0
 Total NaN values in row 7019 :- 0 and it's percentage : 0.0
 Total NaN values in row 7020 :- 0 and it's percentage : 0.0
 Total NaN values in row 7021 :- 0 and it's percentage : 0.0
 Total NaN values in row 7022 :- 0 and it's percentage : 0.0
 Total NaN values in row 7023 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7024 :- 0 and it's percentage : 0.0
 Total NaN values in row 7025 :- 0 and it's percentage : 0.0
 Total NaN values in row 7026 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7027 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7028 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7029 :- 0 and it's percentage : 0.0
 Total NaN values in row 7030 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7031 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7032 :- 0 and it's percentage : 0.0
 Total NaN values in row 7033 :- 0 and it's percentage : 0.0
 Total NaN values in row 7034 :- 0 and it's percentage : 0.0
 Total NaN values in row 7035 :- 0 and it's percentage : 0.0
 Total NaN values in row 7036 :- 0 and it's percentage : 0.0
 Total NaN values in row 7037 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7038 :- 0 and it's percentage : 0.0
 Total NaN values in row 7039 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7040 :- 0 and it's percentage : 0.0
 Total NaN values in row 7041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7042 :- 0 and it's percentage : 0.0
 Total NaN values in row 7043 :- 0 and it's percentage : 0.0
 Total NaN values in row 7044 :- 0 and it's percentage : 0.0
 Total NaN values in row 7045 :- 0 and it's percentage : 0.0
 Total NaN values in row 7046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7048 :- 0 and it's percentage : 0.0
 Total NaN values in row 7049 :- 0 and it's percentage : 0.0
 Total NaN values in row 7050 :- 0 and it's percentage : 0.0
 Total NaN values in row 7051 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7052 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 7053 :- 0 and it's percentage : 0.0
 Total NaN values in row 7054 :- 0 and it's percentage : 0.0
 Total NaN values in row 7055 :- 0 and it's percentage : 0.0
 Total NaN values in row 7056 :- 0 and it's percentage : 0.0
 Total NaN values in row 7057 :- 0 and it's percentage : 0.0
 Total NaN values in row 7058 :- 0 and it's percentage : 0.0
 Total NaN values in row 7059 :- 0 and it's percentage : 0.0
 Total NaN values in row 7060 :- 0 and it's percentage : 0.0
 Total NaN values in row 7061 :- 0 and it's percentage : 0.0
 Total NaN values in row 7062 :- 0 and it's percentage : 0.0
 Total NaN values in row 7063 :- 0 and it's percentage : 0.0
 Total NaN values in row 7064 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7065 :- 0 and it's percentage : 0.0
 Total NaN values in row 7066 :- 0 and it's percentage : 0.0
 Total NaN values in row 7067 :- 0 and it's percentage : 0.0
 Total NaN values in row 7068 :- 0 and it's percentage : 0.0
 Total NaN values in row 7069 :- 0 and it's percentage : 0.0
 Total NaN values in row 7070 :- 0 and it's percentage : 0.0
 Total NaN values in row 7071 :- 0 and it's percentage : 0.0
 Total NaN values in row 7072 :- 0 and it's percentage : 0.0
 Total NaN values in row 7073 :- 0 and it's percentage : 0.0
 Total NaN values in row 7074 :- 0 and it's percentage : 0.0
 Total NaN values in row 7075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7076 :- 0 and it's percentage : 0.0
 Total NaN values in row 7077 :- 0 and it's percentage : 0.0
 Total NaN values in row 7078 :- 0 and it's percentage : 0.0
 Total NaN values in row 7079 :- 0 and it's percentage : 0.0
 Total NaN values in row 7080 :- 0 and it's percentage : 0.0
 Total NaN values in row 7081 :- 0 and it's percentage : 0.0
 Total NaN values in row 7082 :- 0 and it's percentage : 0.0
 Total NaN values in row 7083 :- 0 and it's percentage : 0.0
 Total NaN values in row 7084 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7085 :- 0 and it's percentage : 0.0
 Total NaN values in row 7086 :- 0 and it's percentage : 0.0
 Total NaN values in row 7087 :- 0 and it's percentage : 0.0
 Total NaN values in row 7088 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7090 :- 0 and it's percentage : 0.0
 Total NaN values in row 7091 :- 0 and it's percentage : 0.0
 Total NaN values in row 7092 :- 0 and it's percentage : 0.0
 Total NaN values in row 7093 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7094 :- 0 and it's percentage : 0.0
 Total NaN values in row 7095 :- 0 and it's percentage : 0.0
 Total NaN values in row 7096 :- 0 and it's percentage : 0.0
 Total NaN values in row 7097 :- 0 and it's percentage : 0.0
 Total NaN values in row 7098 :- 0 and it's percentage : 0.0
 Total NaN values in row 7099 :- 0 and it's percentage : 0.0
 Total NaN values in row 7100 :- 0 and it's percentage : 0.0
 Total NaN values in row 7101 :- 0 and it's percentage : 0.0
 Total NaN values in row 7102 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7103 :- 0 and it's percentage : 0.0
 Total NaN values in row 7104 :- 0 and it's percentage : 0.0
 Total NaN values in row 7105 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7106 :- 0 and it's percentage : 0.0
 Total NaN values in row 7107 :- 0 and it's percentage : 0.0
 Total NaN values in row 7108 :- 0 and it's percentage : 0.0
 Total NaN values in row 7109 :- 0 and it's percentage : 0.0
 Total NaN values in row 7110 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 7111 :- 0 and it's percentage : 0.0
 Total NaN values in row 7112 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7113 :- 0 and it's percentage : 0.0
 Total NaN values in row 7114 :- 0 and it's percentage : 0.0
 Total NaN values in row 7115 :- 0 and it's percentage : 0.0
 Total NaN values in row 7116 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7117 :- 0 and it's percentage : 0.0
 Total NaN values in row 7118 :- 0 and it's percentage : 0.0
 Total NaN values in row 7119 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7120 :- 0 and it's percentage : 0.0
 Total NaN values in row 7121 :- 0 and it's percentage : 0.0
 Total NaN values in row 7122 :- 0 and it's percentage : 0.0
 Total NaN values in row 7123 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7124 :- 0 and it's percentage : 0.0
 Total NaN values in row 7125 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7126 :- 0 and it's percentage : 0.0
 Total NaN values in row 7127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7128 :- 0 and it's percentage : 0.0
 Total NaN values in row 7129 :- 0 and it's percentage : 0.0
 Total NaN values in row 7130 :- 0 and it's percentage : 0.0
 Total NaN values in row 7131 :- 0 and it's percentage : 0.0
 Total NaN values in row 7132 :- 0 and it's percentage : 0.0
 Total NaN values in row 7133 :- 0 and it's percentage : 0.0
 Total NaN values in row 7134 :- 0 and it's percentage : 0.0
 Total NaN values in row 7135 :- 0 and it's percentage : 0.0
 Total NaN values in row 7136 :- 0 and it's percentage : 0.0
 Total NaN values in row 7137 :- 0 and it's percentage : 0.0
 Total NaN values in row 7138 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7139 :- 0 and it's percentage : 0.0
 Total NaN values in row 7140 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7141 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7142 :- 0 and it's percentage : 0.0
 Total NaN values in row 7143 :- 0 and it's percentage : 0.0
 Total NaN values in row 7144 :- 0 and it's percentage : 0.0
 Total NaN values in row 7145 :- 0 and it's percentage : 0.0
 Total NaN values in row 7146 :- 0 and it's percentage : 0.0
 Total NaN values in row 7147 :- 0 and it's percentage : 0.0
 Total NaN values in row 7148 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7149 :- 0 and it's percentage : 0.0
 Total NaN values in row 7150 :- 0 and it's percentage : 0.0
 Total NaN values in row 7151 :- 0 and it's percentage : 0.0
 Total NaN values in row 7152 :- 0 and it's percentage : 0.0
 Total NaN values in row 7153 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7154 :- 0 and it's percentage : 0.0
 Total NaN values in row 7155 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7156 :- 0 and it's percentage : 0.0
 Total NaN values in row 7157 :- 0 and it's percentage : 0.0
 Total NaN values in row 7158 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7159 :- 0 and it's percentage : 0.0
 Total NaN values in row 7160 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7161 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7162 :- 0 and it's percentage : 0.0
 Total NaN values in row 7163 :- 0 and it's percentage : 0.0
 Total NaN values in row 7164 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7165 :- 0 and it's percentage : 0.0
 Total NaN values in row 7166 :- 0 and it's percentage : 0.0
 Total NaN values in row 7167 :- 0 and it's percentage : 0.0
 Total NaN values in row 7168 :- 0 and it's percentage : 0.0
 Total NaN values in row 7169 :- 0 and it's percentage : 0.0
 Total NaN values in row 7170 :- 0 and it's percentage : 0.0
 Total NaN values in row 7171 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7172 :- 0 and it's percentage : 0.0
 Total NaN values in row 7173 :- 0 and it's percentage : 0.0
 Total NaN values in row 7174 :- 0 and it's percentage : 0.0
 Total NaN values in row 7175 :- 0 and it's percentage : 0.0
 Total NaN values in row 7176 :- 0 and it's percentage : 0.0
 Total NaN values in row 7177 :- 0 and it's percentage : 0.0
 Total NaN values in row 7178 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7179 :- 0 and it's percentage : 0.0
 Total NaN values in row 7180 :- 0 and it's percentage : 0.0
 Total NaN values in row 7181 :- 0 and it's percentage : 0.0
 Total NaN values in row 7182 :- 0 and it's percentage : 0.0
 Total NaN values in row 7183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7184 :- 0 and it's percentage : 0.0
 Total NaN values in row 7185 :- 0 and it's percentage : 0.0
 Total NaN values in row 7186 :- 0 and it's percentage : 0.0
 Total NaN values in row 7187 :- 0 and it's percentage : 0.0
 Total NaN values in row 7188 :- 0 and it's percentage : 0.0
 Total NaN values in row 7189 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7190 :- 0 and it's percentage : 0.0
 Total NaN values in row 7191 :- 0 and it's percentage : 0.0
 Total NaN values in row 7192 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7193 :- 0 and it's percentage : 0.0
 Total NaN values in row 7194 :- 0 and it's percentage : 0.0
 Total NaN values in row 7195 :- 0 and it's percentage : 0.0
 Total NaN values in row 7196 :- 0 and it's percentage : 0.0
 Total NaN values in row 7197 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7198 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7199 :- 0 and it's percentage : 0.0
 Total NaN values in row 7200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7201 :- 0 and it's percentage : 0.0
 Total NaN values in row 7202 :- 0 and it's percentage : 0.0
 Total NaN values in row 7203 :- 0 and it's percentage : 0.0
 Total NaN values in row 7204 :- 0 and it's percentage : 0.0
 Total NaN values in row 7205 :- 0 and it's percentage : 0.0
 Total NaN values in row 7206 :- 0 and it's percentage : 0.0
 Total NaN values in row 7207 :- 0 and it's percentage : 0.0
 Total NaN values in row 7208 :- 0 and it's percentage : 0.0
 Total NaN values in row 7209 :- 0 and it's percentage : 0.0
 Total NaN values in row 7210 :- 0 and it's percentage : 0.0
 Total NaN values in row 7211 :- 0 and it's percentage : 0.0
 Total NaN values in row 7212 :- 0 and it's percentage : 0.0
 Total NaN values in row 7213 :- 0 and it's percentage : 0.0
 Total NaN values in row 7214 :- 0 and it's percentage : 0.0
 Total NaN values in row 7215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7216 :- 0 and it's percentage : 0.0
 Total NaN values in row 7217 :- 0 and it's percentage : 0.0
 Total NaN values in row 7218 :- 0 and it's percentage : 0.0
 Total NaN values in row 7219 :- 0 and it's percentage : 0.0
 Total NaN values in row 7220 :- 0 and it's percentage : 0.0
 Total NaN values in row 7221 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7222 :- 0 and it's percentage : 0.0
 Total NaN values in row 7223 :- 0 and it's percentage : 0.0
 Total NaN values in row 7224 :- 0 and it's percentage : 0.0
 Total NaN values in row 7225 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7226 :- 0 and it's percentage : 0.0
 Total NaN values in row 7227 :- 0 and it's percentage : 0.0
 Total NaN values in row 7228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7230 :- 0 and it's percentage : 0.0
 Total NaN values in row 7231 :- 0 and it's percentage : 0.0
 Total NaN values in row 7232 :- 0 and it's percentage : 0.0
 Total NaN values in row 7233 :- 0 and it's percentage : 0.0
 Total NaN values in row 7234 :- 0 and it's percentage : 0.0
 Total NaN values in row 7235 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7236 :- 0 and it's percentage : 0.0
 Total NaN values in row 7237 :- 0 and it's percentage : 0.0
 Total NaN values in row 7238 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7239 :- 0 and it's percentage : 0.0
 Total NaN values in row 7240 :- 0 and it's percentage : 0.0
 Total NaN values in row 7241 :- 0 and it's percentage : 0.0

 Total NaN values in row 7242 :- 0 and it's percentage : 0.0
 Total NaN values in row 7243 :- 0 and it's percentage : 0.0
 Total NaN values in row 7244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7245 :- 0 and it's percentage : 0.0
 Total NaN values in row 7246 :- 0 and it's percentage : 0.0
 Total NaN values in row 7247 :- 0 and it's percentage : 0.0
 Total NaN values in row 7248 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7249 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7250 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7251 :- 0 and it's percentage : 0.0
 Total NaN values in row 7252 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7253 :- 0 and it's percentage : 0.0
 Total NaN values in row 7254 :- 0 and it's percentage : 0.0
 Total NaN values in row 7255 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7256 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7257 :- 0 and it's percentage : 0.0
 Total NaN values in row 7258 :- 0 and it's percentage : 0.0
 Total NaN values in row 7259 :- 0 and it's percentage : 0.0
 Total NaN values in row 7260 :- 0 and it's percentage : 0.0
 Total NaN values in row 7261 :- 0 and it's percentage : 0.0
 Total NaN values in row 7262 :- 0 and it's percentage : 0.0
 Total NaN values in row 7263 :- 0 and it's percentage : 0.0
 Total NaN values in row 7264 :- 0 and it's percentage : 0.0
 Total NaN values in row 7265 :- 0 and it's percentage : 0.0
 Total NaN values in row 7266 :- 0 and it's percentage : 0.0
 Total NaN values in row 7267 :- 0 and it's percentage : 0.0
 Total NaN values in row 7268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7270 :- 0 and it's percentage : 0.0
 Total NaN values in row 7271 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7272 :- 0 and it's percentage : 0.0
 Total NaN values in row 7273 :- 0 and it's percentage : 0.0
 Total NaN values in row 7274 :- 0 and it's percentage : 0.0
 Total NaN values in row 7275 :- 0 and it's percentage : 0.0
 Total NaN values in row 7276 :- 0 and it's percentage : 0.0
 Total NaN values in row 7277 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7279 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7280 :- 0 and it's percentage : 0.0
 Total NaN values in row 7281 :- 0 and it's percentage : 0.0
 Total NaN values in row 7282 :- 0 and it's percentage : 0.0
 Total NaN values in row 7283 :- 0 and it's percentage : 0.0
 Total NaN values in row 7284 :- 0 and it's percentage : 0.0
 Total NaN values in row 7285 :- 0 and it's percentage : 0.0
 Total NaN values in row 7286 :- 0 and it's percentage : 0.0
 Total NaN values in row 7287 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7288 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7289 :- 0 and it's percentage : 0.0
 Total NaN values in row 7290 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7291 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7292 :- 0 and it's percentage : 0.0
 Total NaN values in row 7293 :- 0 and it's percentage : 0.0
 Total NaN values in row 7294 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7295 :- 0 and it's percentage : 0.0
 Total NaN values in row 7296 :- 0 and it's percentage : 0.0
 Total NaN values in row 7297 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7300 :- 0 and it's percentage : 0.0
 Total NaN values in row 7301 :- 0 and it's percentage : 0.0
 Total NaN values in row 7302 :- 0 and it's percentage : 0.0
 Total NaN values in row 7303 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7304 :- 0 and it's percentage : 0.0
 Total NaN values in row 7305 :- 0 and it's percentage : 0.0
 Total NaN values in row 7306 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7307 :- 0 and it's percentage : 0.0
 Total NaN values in row 7308 :- 0 and it's percentage : 0.0
 Total NaN values in row 7309 :- 0 and it's percentage : 0.0
 Total NaN values in row 7310 :- 0 and it's percentage : 0.0
 Total NaN values in row 7311 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7312 :- 0 and it's percentage : 0.0
 Total NaN values in row 7313 :- 0 and it's percentage : 0.0
 Total NaN values in row 7314 :- 0 and it's percentage : 0.0
 Total NaN values in row 7315 :- 0 and it's percentage : 0.0
 Total NaN values in row 7316 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7317 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7318 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7319 :- 0 and it's percentage : 0.0
 Total NaN values in row 7320 :- 0 and it's percentage : 0.0
 Total NaN values in row 7321 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7323 :- 0 and it's percentage : 0.0
 Total NaN values in row 7324 :- 0 and it's percentage : 0.0
 Total NaN values in row 7325 :- 0 and it's percentage : 0.0
 Total NaN values in row 7326 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7327 :- 0 and it's percentage : 0.0
 Total NaN values in row 7328 :- 0 and it's percentage : 0.0
 Total NaN values in row 7329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7331 :- 0 and it's percentage : 0.0
 Total NaN values in row 7332 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7334 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7335 :- 0 and it's percentage : 0.0
 Total NaN values in row 7336 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7337 :- 0 and it's percentage : 0.0
 Total NaN values in row 7338 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7339 :- 0 and it's percentage : 0.0
 Total NaN values in row 7340 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7341 :- 0 and it's percentage : 0.0
 Total NaN values in row 7342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7344 :- 0 and it's percentage : 0.0
 Total NaN values in row 7345 :- 0 and it's percentage : 0.0
 Total NaN values in row 7346 :- 0 and it's percentage : 0.0
 Total NaN values in row 7347 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7348 :- 0 and it's percentage : 0.0
 Total NaN values in row 7349 :- 0 and it's percentage : 0.0
 Total NaN values in row 7350 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7352 :- 0 and it's percentage : 0.0
 Total NaN values in row 7353 :- 0 and it's percentage : 0.0
 Total NaN values in row 7354 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7355 :- 0 and it's percentage : 0.0
 Total NaN values in row 7356 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7357 :- 0 and it's percentage : 0.0
 Total NaN values in row 7358 :- 0 and it's percentage : 0.0
 Total NaN values in row 7359 :- 0 and it's percentage : 0.0
 Total NaN values in row 7360 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7361 :- 0 and it's percentage : 0.0
 Total NaN values in row 7362 :- 0 and it's percentage : 0.0
 Total NaN values in row 7363 :- 0 and it's percentage : 0.0
 Total NaN values in row 7364 :- 0 and it's percentage : 0.0
 Total NaN values in row 7365 :- 0 and it's percentage : 0.0
 Total NaN values in row 7366 :- 0 and it's percentage : 0.0
 Total NaN values in row 7367 :- 0 and it's percentage : 0.0
 Total NaN values in row 7368 :- 0 and it's percentage : 0.0
 Total NaN values in row 7369 :- 0 and it's percentage : 0.0
 Total NaN values in row 7370 :- 0 and it's percentage : 0.0
 Total NaN values in row 7371 :- 0 and it's percentage : 0.0
 Total NaN values in row 7372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7373 :- 0 and it's percentage : 0.0
 Total NaN values in row 7374 :- 0 and it's percentage : 0.0
 Total NaN values in row 7375 :- 0 and it's percentage : 0.0

 Total NaN values in row 7376 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7378 :- 0 and it's percentage : 0.0
 Total NaN values in row 7379 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7380 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7381 :- 0 and it's percentage : 0.0
 Total NaN values in row 7382 :- 0 and it's percentage : 0.0
 Total NaN values in row 7383 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7384 :- 0 and it's percentage : 0.0
 Total NaN values in row 7385 :- 0 and it's percentage : 0.0
 Total NaN values in row 7386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7387 :- 0 and it's percentage : 0.0
 Total NaN values in row 7388 :- 0 and it's percentage : 0.0
 Total NaN values in row 7389 :- 0 and it's percentage : 0.0
 Total NaN values in row 7390 :- 0 and it's percentage : 0.0
 Total NaN values in row 7391 :- 0 and it's percentage : 0.0
 Total NaN values in row 7392 :- 0 and it's percentage : 0.0
 Total NaN values in row 7393 :- 0 and it's percentage : 0.0
 Total NaN values in row 7394 :- 0 and it's percentage : 0.0
 Total NaN values in row 7395 :- 0 and it's percentage : 0.0
 Total NaN values in row 7396 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7397 :- 0 and it's percentage : 0.0
 Total NaN values in row 7398 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7399 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7400 :- 0 and it's percentage : 0.0
 Total NaN values in row 7401 :- 0 and it's percentage : 0.0
 Total NaN values in row 7402 :- 0 and it's percentage : 0.0
 Total NaN values in row 7403 :- 0 and it's percentage : 0.0
 Total NaN values in row 7404 :- 0 and it's percentage : 0.0
 Total NaN values in row 7405 :- 0 and it's percentage : 0.0
 Total NaN values in row 7406 :- 0 and it's percentage : 0.0
 Total NaN values in row 7407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7408 :- 0 and it's percentage : 0.0
 Total NaN values in row 7409 :- 0 and it's percentage : 0.0
 Total NaN values in row 7410 :- 0 and it's percentage : 0.0
 Total NaN values in row 7411 :- 0 and it's percentage : 0.0
 Total NaN values in row 7412 :- 0 and it's percentage : 0.0
 Total NaN values in row 7413 :- 0 and it's percentage : 0.0
 Total NaN values in row 7414 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7415 :- 0 and it's percentage : 0.0
 Total NaN values in row 7416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7417 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7418 :- 0 and it's percentage : 0.0
 Total NaN values in row 7419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7420 :- 0 and it's percentage : 0.0
 Total NaN values in row 7421 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7422 :- 0 and it's percentage : 0.0
 Total NaN values in row 7423 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7424 :- 0 and it's percentage : 0.0
 Total NaN values in row 7425 :- 0 and it's percentage : 0.0
 Total NaN values in row 7426 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7427 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7428 :- 0 and it's percentage : 0.0
 Total NaN values in row 7429 :- 0 and it's percentage : 0.0
 Total NaN values in row 7430 :- 0 and it's percentage : 0.0
 Total NaN values in row 7431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7432 :- 0 and it's percentage : 0.0
 Total NaN values in row 7433 :- 0 and it's percentage : 0.0
 Total NaN values in row 7434 :- 0 and it's percentage : 0.0
 Total NaN values in row 7435 :- 0 and it's percentage : 0.0
 Total NaN values in row 7436 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7439 :- 0 and it's percentage : 0.0
 Total NaN values in row 7440 :- 0 and it's percentage : 0.0
 Total NaN values in row 7441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7442 :- 0 and it's percentage : 0.0
 Total NaN values in row 7443 :- 0 and it's percentage : 0.0
 Total NaN values in row 7444 :- 0 and it's percentage : 0.0
 Total NaN values in row 7445 :- 0 and it's percentage : 0.0
 Total NaN values in row 7446 :- 0 and it's percentage : 0.0
 Total NaN values in row 7447 :- 0 and it's percentage : 0.0
 Total NaN values in row 7448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7449 :- 0 and it's percentage : 0.0
 Total NaN values in row 7450 :- 0 and it's percentage : 0.0
 Total NaN values in row 7451 :- 0 and it's percentage : 0.0
 Total NaN values in row 7452 :- 0 and it's percentage : 0.0
 Total NaN values in row 7453 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7454 :- 0 and it's percentage : 0.0
 Total NaN values in row 7455 :- 0 and it's percentage : 0.0
 Total NaN values in row 7456 :- 0 and it's percentage : 0.0
 Total NaN values in row 7457 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7458 :- 0 and it's percentage : 0.0
 Total NaN values in row 7459 :- 0 and it's percentage : 0.0
 Total NaN values in row 7460 :- 0 and it's percentage : 0.0
 Total NaN values in row 7461 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7462 :- 0 and it's percentage : 0.0
 Total NaN values in row 7463 :- 0 and it's percentage : 0.0
 Total NaN values in row 7464 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7465 :- 0 and it's percentage : 0.0
 Total NaN values in row 7466 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7467 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7468 :- 0 and it's percentage : 0.0
 Total NaN values in row 7469 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7470 :- 0 and it's percentage : 0.0
 Total NaN values in row 7471 :- 0 and it's percentage : 0.0
 Total NaN values in row 7472 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7474 :- 0 and it's percentage : 0.0
 Total NaN values in row 7475 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7476 :- 0 and it's percentage : 0.0
 Total NaN values in row 7477 :- 0 and it's percentage : 0.0
 Total NaN values in row 7478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7479 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7480 :- 0 and it's percentage : 0.0
 Total NaN values in row 7481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7482 :- 0 and it's percentage : 0.0
 Total NaN values in row 7483 :- 0 and it's percentage : 0.0
 Total NaN values in row 7484 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7485 :- 0 and it's percentage : 0.0
 Total NaN values in row 7486 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7487 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7488 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7489 :- 0 and it's percentage : 0.0
 Total NaN values in row 7490 :- 0 and it's percentage : 0.0
 Total NaN values in row 7491 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7492 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7493 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7494 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7495 :- 0 and it's percentage : 0.0
 Total NaN values in row 7496 :- 0 and it's percentage : 0.0
 Total NaN values in row 7497 :- 0 and it's percentage : 0.0
 Total NaN values in row 7498 :- 0 and it's percentage : 0.0
 Total NaN values in row 7499 :- 0 and it's percentage : 0.0
 Total NaN values in row 7500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7501 :- 0 and it's percentage : 0.0

 Total NaN values in row 7502 :- 0 and it's percentage : 0.0
 Total NaN values in row 7503 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7504 :- 0 and it's percentage : 0.0
 Total NaN values in row 7505 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7507 :- 0 and it's percentage : 0.0
 Total NaN values in row 7508 :- 0 and it's percentage : 0.0
 Total NaN values in row 7509 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7510 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7511 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7512 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7513 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7514 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7515 :- 0 and it's percentage : 0.0
 Total NaN values in row 7516 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7517 :- 0 and it's percentage : 0.0
 Total NaN values in row 7518 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7519 :- 0 and it's percentage : 0.0
 Total NaN values in row 7520 :- 0 and it's percentage : 0.0
 Total NaN values in row 7521 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7522 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7523 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7524 :- 0 and it's percentage : 0.0
 Total NaN values in row 7525 :- 0 and it's percentage : 0.0
 Total NaN values in row 7526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7527 :- 0 and it's percentage : 0.0
 Total NaN values in row 7528 :- 0 and it's percentage : 0.0
 Total NaN values in row 7529 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7530 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7531 :- 0 and it's percentage : 0.0
 Total NaN values in row 7532 :- 0 and it's percentage : 0.0
 Total NaN values in row 7533 :- 0 and it's percentage : 0.0
 Total NaN values in row 7534 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7535 :- 0 and it's percentage : 0.0
 Total NaN values in row 7536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7537 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7538 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7539 :- 0 and it's percentage : 0.0
 Total NaN values in row 7540 :- 0 and it's percentage : 0.0
 Total NaN values in row 7541 :- 0 and it's percentage : 0.0
 Total NaN values in row 7542 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7544 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7545 :- 0 and it's percentage : 0.0
 Total NaN values in row 7546 :- 0 and it's percentage : 0.0
 Total NaN values in row 7547 :- 0 and it's percentage : 0.0
 Total NaN values in row 7548 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7549 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7550 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7551 :- 0 and it's percentage : 0.0
 Total NaN values in row 7552 :- 0 and it's percentage : 0.0
 Total NaN values in row 7553 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7554 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7555 :- 0 and it's percentage : 0.0
 Total NaN values in row 7556 :- 0 and it's percentage : 0.0
 Total NaN values in row 7557 :- 0 and it's percentage : 0.0
 Total NaN values in row 7558 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7559 :- 0 and it's percentage : 0.0
 Total NaN values in row 7560 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7561 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7563 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7564 :- 0 and it's percentage : 0.0
 Total NaN values in row 7565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7566 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7567 :- 0 and it's percentage : 0.0
 Total NaN values in row 7568 :- 0 and it's percentage : 0.0
 Total NaN values in row 7569 :- 0 and it's percentage : 0.0
 Total NaN values in row 7570 :- 0 and it's percentage : 0.0
 Total NaN values in row 7571 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 7572 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7573 :- 0 and it's percentage : 0.0
 Total NaN values in row 7574 :- 0 and it's percentage : 0.0
 Total NaN values in row 7575 :- 0 and it's percentage : 0.0
 Total NaN values in row 7576 :- 0 and it's percentage : 0.0
 Total NaN values in row 7577 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7579 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7580 :- 0 and it's percentage : 0.0
 Total NaN values in row 7581 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7582 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7583 :- 0 and it's percentage : 0.0
 Total NaN values in row 7584 :- 0 and it's percentage : 0.0
 Total NaN values in row 7585 :- 0 and it's percentage : 0.0
 Total NaN values in row 7586 :- 0 and it's percentage : 0.0
 Total NaN values in row 7587 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7588 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7589 :- 0 and it's percentage : 0.0
 Total NaN values in row 7590 :- 0 and it's percentage : 0.0
 Total NaN values in row 7591 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7592 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7593 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7594 :- 0 and it's percentage : 0.0
 Total NaN values in row 7595 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7596 :- 0 and it's percentage : 0.0
 Total NaN values in row 7597 :- 0 and it's percentage : 0.0
 Total NaN values in row 7598 :- 0 and it's percentage : 0.0
 Total NaN values in row 7599 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 7600 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7601 :- 0 and it's percentage : 0.0
 Total NaN values in row 7602 :- 0 and it's percentage : 0.0
 Total NaN values in row 7603 :- 0 and it's percentage : 0.0
 Total NaN values in row 7604 :- 0 and it's percentage : 0.0
 Total NaN values in row 7605 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7606 :- 0 and it's percentage : 0.0
 Total NaN values in row 7607 :- 0 and it's percentage : 0.0
 Total NaN values in row 7608 :- 0 and it's percentage : 0.0
 Total NaN values in row 7609 :- 0 and it's percentage : 0.0
 Total NaN values in row 7610 :- 0 and it's percentage : 0.0
 Total NaN values in row 7611 :- 0 and it's percentage : 0.0
 Total NaN values in row 7612 :- 0 and it's percentage : 0.0
 Total NaN values in row 7613 :- 0 and it's percentage : 0.0
 Total NaN values in row 7614 :- 0 and it's percentage : 0.0
 Total NaN values in row 7615 :- 0 and it's percentage : 0.0
 Total NaN values in row 7616 :- 0 and it's percentage : 0.0
 Total NaN values in row 7617 :- 0 and it's percentage : 0.0
 Total NaN values in row 7618 :- 0 and it's percentage : 0.0
 Total NaN values in row 7619 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7621 :- 0 and it's percentage : 0.0
 Total NaN values in row 7622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7623 :- 0 and it's percentage : 0.0
 Total NaN values in row 7624 :- 0 and it's percentage : 0.0
 Total NaN values in row 7625 :- 0 and it's percentage : 0.0
 Total NaN values in row 7626 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7627 :- 0 and it's percentage : 0.0
 Total NaN values in row 7628 :- 0 and it's percentage : 0.0
 Total NaN values in row 7629 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7631 :- 0 and it's percentage : 0.0
 Total NaN values in row 7632 :- 0 and it's percentage : 0.0
 Total NaN values in row 7633 :- 0 and it's percentage : 0.0
 Total NaN values in row 7634 :- 0 and it's percentage : 0.0
 Total NaN values in row 7635 :- 0 and it's percentage : 0.0
 Total NaN values in row 7636 :- 0 and it's percentage : 0.0
 Total NaN values in row 7637 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7638 :- 0 and it's percentage : 0.0
 Total NaN values in row 7639 :- 0 and it's percentage : 0.0
 Total NaN values in row 7640 :- 0 and it's percentage : 0.0
 Total NaN values in row 7641 :- 0 and it's percentage : 0.0
 Total NaN values in row 7642 :- 0 and it's percentage : 0.0
 Total NaN values in row 7643 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7644 :- 0 and it's percentage : 0.0
 Total NaN values in row 7645 :- 0 and it's percentage : 0.0
 Total NaN values in row 7646 :- 0 and it's percentage : 0.0
 Total NaN values in row 7647 :- 0 and it's percentage : 0.0
 Total NaN values in row 7648 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7649 :- 0 and it's percentage : 0.0
 Total NaN values in row 7650 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7651 :- 0 and it's percentage : 0.0
 Total NaN values in row 7652 :- 0 and it's percentage : 0.0
 Total NaN values in row 7653 :- 0 and it's percentage : 0.0
 Total NaN values in row 7654 :- 0 and it's percentage : 0.0
 Total NaN values in row 7655 :- 0 and it's percentage : 0.0
 Total NaN values in row 7656 :- 0 and it's percentage : 0.0
 Total NaN values in row 7657 :- 0 and it's percentage : 0.0
 Total NaN values in row 7658 :- 0 and it's percentage : 0.0
 Total NaN values in row 7659 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 7660 :- 0 and it's percentage : 0.0
 Total NaN values in row 7661 :- 0 and it's percentage : 0.0
 Total NaN values in row 7662 :- 0 and it's percentage : 0.0
 Total NaN values in row 7663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7664 :- 0 and it's percentage : 0.0
 Total NaN values in row 7665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7666 :- 0 and it's percentage : 0.0
 Total NaN values in row 7667 :- 0 and it's percentage : 0.0
 Total NaN values in row 7668 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7669 :- 0 and it's percentage : 0.0
 Total NaN values in row 7670 :- 0 and it's percentage : 0.0
 Total NaN values in row 7671 :- 0 and it's percentage : 0.0
 Total NaN values in row 7672 :- 0 and it's percentage : 0.0
 Total NaN values in row 7673 :- 0 and it's percentage : 0.0
 Total NaN values in row 7674 :- 0 and it's percentage : 0.0
 Total NaN values in row 7675 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7676 :- 0 and it's percentage : 0.0
 Total NaN values in row 7677 :- 0 and it's percentage : 0.0
 Total NaN values in row 7678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7679 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7680 :- 0 and it's percentage : 0.0
 Total NaN values in row 7681 :- 0 and it's percentage : 0.0
 Total NaN values in row 7682 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7684 :- 0 and it's percentage : 0.0
 Total NaN values in row 7685 :- 0 and it's percentage : 0.0
 Total NaN values in row 7686 :- 0 and it's percentage : 0.0
 Total NaN values in row 7687 :- 0 and it's percentage : 0.0
 Total NaN values in row 7688 :- 0 and it's percentage : 0.0
 Total NaN values in row 7689 :- 0 and it's percentage : 0.0
 Total NaN values in row 7690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7691 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7693 :- 0 and it's percentage : 0.0
 Total NaN values in row 7694 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7695 :- 0 and it's percentage : 0.0
 Total NaN values in row 7696 :- 0 and it's percentage : 0.0
 Total NaN values in row 7697 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7698 :- 0 and it's percentage : 0.0
 Total NaN values in row 7699 :- 0 and it's percentage : 0.0
 Total NaN values in row 7700 :- 0 and it's percentage : 0.0
 Total NaN values in row 7701 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7702 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 7703 :- 0 and it's percentage : 0.0
 Total NaN values in row 7704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7705 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7706 :- 0 and it's percentage : 0.0
 Total NaN values in row 7707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7708 :- 0 and it's percentage : 0.0
 Total NaN values in row 7709 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7710 :- 0 and it's percentage : 0.0
 Total NaN values in row 7711 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7712 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7714 :- 0 and it's percentage : 0.0
 Total NaN values in row 7715 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7716 :- 0 and it's percentage : 0.0
 Total NaN values in row 7717 :- 0 and it's percentage : 0.0
 Total NaN values in row 7718 :- 0 and it's percentage : 0.0
 Total NaN values in row 7719 :- 0 and it's percentage : 0.0
 Total NaN values in row 7720 :- 0 and it's percentage : 0.0
 Total NaN values in row 7721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7722 :- 0 and it's percentage : 0.0
 Total NaN values in row 7723 :- 0 and it's percentage : 0.0
 Total NaN values in row 7724 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7725 :- 0 and it's percentage : 0.0
 Total NaN values in row 7726 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7727 :- 0 and it's percentage : 0.0
 Total NaN values in row 7728 :- 0 and it's percentage : 0.0
 Total NaN values in row 7729 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7730 :- 0 and it's percentage : 0.0
 Total NaN values in row 7731 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7732 :- 0 and it's percentage : 0.0
 Total NaN values in row 7733 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7734 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7735 :- 0 and it's percentage : 0.0
 Total NaN values in row 7736 :- 0 and it's percentage : 0.0
 Total NaN values in row 7737 :- 0 and it's percentage : 0.0
 Total NaN values in row 7738 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7739 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7740 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7741 :- 0 and it's percentage : 0.0
 Total NaN values in row 7742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7743 :- 0 and it's percentage : 0.0
 Total NaN values in row 7744 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7745 :- 0 and it's percentage : 0.0
 Total NaN values in row 7746 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7747 :- 0 and it's percentage : 0.0
 Total NaN values in row 7748 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7749 :- 0 and it's percentage : 0.0
 Total NaN values in row 7750 :- 0 and it's percentage : 0.0
 Total NaN values in row 7751 :- 0 and it's percentage : 0.0
 Total NaN values in row 7752 :- 0 and it's percentage : 0.0
 Total NaN values in row 7753 :- 0 and it's percentage : 0.0
 Total NaN values in row 7754 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7755 :- 0 and it's percentage : 0.0
 Total NaN values in row 7756 :- 0 and it's percentage : 0.0
 Total NaN values in row 7757 :- 0 and it's percentage : 0.0
 Total NaN values in row 7758 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7759 :- 0 and it's percentage : 0.0
 Total NaN values in row 7760 :- 0 and it's percentage : 0.0
 Total NaN values in row 7761 :- 0 and it's percentage : 0.0
 Total NaN values in row 7762 :- 0 and it's percentage : 0.0
 Total NaN values in row 7763 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7764 :- 0 and it's percentage : 0.0
 Total NaN values in row 7765 :- 0 and it's percentage : 0.0
 Total NaN values in row 7766 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7767 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7768 :- 0 and it's percentage : 0.0
 Total NaN values in row 7769 :- 0 and it's percentage : 0.0
 Total NaN values in row 7770 :- 0 and it's percentage : 0.0
 Total NaN values in row 7771 :- 0 and it's percentage : 0.0
 Total NaN values in row 7772 :- 0 and it's percentage : 0.0
 Total NaN values in row 7773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7774 :- 0 and it's percentage : 0.0
 Total NaN values in row 7775 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7776 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7779 :- 0 and it's percentage : 0.0
 Total NaN values in row 7780 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7781 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7782 :- 0 and it's percentage : 0.0
 Total NaN values in row 7783 :- 0 and it's percentage : 0.0
 Total NaN values in row 7784 :- 0 and it's percentage : 0.0
 Total NaN values in row 7785 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7786 :- 0 and it's percentage : 0.0
 Total NaN values in row 7787 :- 0 and it's percentage : 0.0
 Total NaN values in row 7788 :- 0 and it's percentage : 0.0
 Total NaN values in row 7789 :- 0 and it's percentage : 0.0
 Total NaN values in row 7790 :- 0 and it's percentage : 0.0
 Total NaN values in row 7791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7792 :- 0 and it's percentage : 0.0
 Total NaN values in row 7793 :- 0 and it's percentage : 0.0

 Total NaN values in row 7794 :- 0 and it's percentage : 0.0
 Total NaN values in row 7795 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7796 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7797 :- 0 and it's percentage : 0.0
 Total NaN values in row 7798 :- 0 and it's percentage : 0.0
 Total NaN values in row 7799 :- 0 and it's percentage : 0.0
 Total NaN values in row 7800 :- 0 and it's percentage : 0.0
 Total NaN values in row 7801 :- 0 and it's percentage : 0.0
 Total NaN values in row 7802 :- 0 and it's percentage : 0.0
 Total NaN values in row 7803 :- 0 and it's percentage : 0.0
 Total NaN values in row 7804 :- 0 and it's percentage : 0.0
 Total NaN values in row 7805 :- 0 and it's percentage : 0.0
 Total NaN values in row 7806 :- 0 and it's percentage : 0.0
 Total NaN values in row 7807 :- 0 and it's percentage : 0.0
 Total NaN values in row 7808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7809 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7810 :- 0 and it's percentage : 0.0
 Total NaN values in row 7811 :- 0 and it's percentage : 0.0
 Total NaN values in row 7812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7813 :- 0 and it's percentage : 0.0
 Total NaN values in row 7814 :- 0 and it's percentage : 0.0
 Total NaN values in row 7815 :- 0 and it's percentage : 0.0
 Total NaN values in row 7816 :- 0 and it's percentage : 0.0
 Total NaN values in row 7817 :- 0 and it's percentage : 0.0
 Total NaN values in row 7818 :- 0 and it's percentage : 0.0
 Total NaN values in row 7819 :- 0 and it's percentage : 0.0
 Total NaN values in row 7820 :- 0 and it's percentage : 0.0
 Total NaN values in row 7821 :- 0 and it's percentage : 0.0
 Total NaN values in row 7822 :- 0 and it's percentage : 0.0
 Total NaN values in row 7823 :- 0 and it's percentage : 0.0
 Total NaN values in row 7824 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7825 :- 0 and it's percentage : 0.0
 Total NaN values in row 7826 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7827 :- 0 and it's percentage : 0.0
 Total NaN values in row 7828 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7829 :- 0 and it's percentage : 0.0
 Total NaN values in row 7830 :- 0 and it's percentage : 0.0
 Total NaN values in row 7831 :- 0 and it's percentage : 0.0
 Total NaN values in row 7832 :- 0 and it's percentage : 0.0
 Total NaN values in row 7833 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7834 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7835 :- 0 and it's percentage : 0.0
 Total NaN values in row 7836 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7837 :- 0 and it's percentage : 0.0
 Total NaN values in row 7838 :- 0 and it's percentage : 0.0
 Total NaN values in row 7839 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7840 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7841 :- 0 and it's percentage : 0.0
 Total NaN values in row 7842 :- 0 and it's percentage : 0.0
 Total NaN values in row 7843 :- 0 and it's percentage : 0.0
 Total NaN values in row 7844 :- 0 and it's percentage : 0.0
 Total NaN values in row 7845 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7846 :- 0 and it's percentage : 0.0
 Total NaN values in row 7847 :- 0 and it's percentage : 0.0
 Total NaN values in row 7848 :- 0 and it's percentage : 0.0
 Total NaN values in row 7849 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7850 :- 0 and it's percentage : 0.0
 Total NaN values in row 7851 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7852 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7853 :- 0 and it's percentage : 0.0
 Total NaN values in row 7854 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7855 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7856 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7857 :- 0 and it's percentage : 0.0
 Total NaN values in row 7858 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7859 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7860 :- 0 and it's percentage : 0.0
 Total NaN values in row 7861 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7862 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7863 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7864 :- 0 and it's percentage : 0.0
 Total NaN values in row 7865 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7866 :- 0 and it's percentage : 0.0
 Total NaN values in row 7867 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7868 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7869 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7870 :- 0 and it's percentage : 0.0
 Total NaN values in row 7871 :- 0 and it's percentage : 0.0
 Total NaN values in row 7872 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 7873 :- 0 and it's percentage : 0.0
 Total NaN values in row 7874 :- 0 and it's percentage : 0.0
 Total NaN values in row 7875 :- 0 and it's percentage : 0.0
 Total NaN values in row 7876 :- 0 and it's percentage : 0.0
 Total NaN values in row 7877 :- 0 and it's percentage : 0.0
 Total NaN values in row 7878 :- 0 and it's percentage : 0.0
 Total NaN values in row 7879 :- 0 and it's percentage : 0.0
 Total NaN values in row 7880 :- 0 and it's percentage : 0.0
 Total NaN values in row 7881 :- 0 and it's percentage : 0.0
 Total NaN values in row 7882 :- 0 and it's percentage : 0.0
 Total NaN values in row 7883 :- 0 and it's percentage : 0.0
 Total NaN values in row 7884 :- 0 and it's percentage : 0.0
 Total NaN values in row 7885 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7886 :- 0 and it's percentage : 0.0
 Total NaN values in row 7887 :- 0 and it's percentage : 0.0
 Total NaN values in row 7888 :- 0 and it's percentage : 0.0
 Total NaN values in row 7889 :- 0 and it's percentage : 0.0
 Total NaN values in row 7890 :- 0 and it's percentage : 0.0
 Total NaN values in row 7891 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7892 :- 0 and it's percentage : 0.0
 Total NaN values in row 7893 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7895 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7896 :- 0 and it's percentage : 0.0
 Total NaN values in row 7897 :- 0 and it's percentage : 0.0
 Total NaN values in row 7898 :- 0 and it's percentage : 0.0
 Total NaN values in row 7899 :- 0 and it's percentage : 0.0
 Total NaN values in row 7900 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7901 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7902 :- 0 and it's percentage : 0.0
 Total NaN values in row 7903 :- 0 and it's percentage : 0.0
 Total NaN values in row 7904 :- 0 and it's percentage : 0.0
 Total NaN values in row 7905 :- 0 and it's percentage : 0.0
 Total NaN values in row 7906 :- 0 and it's percentage : 0.0
 Total NaN values in row 7907 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7908 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7909 :- 0 and it's percentage : 0.0
 Total NaN values in row 7910 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7911 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7912 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7913 :- 0 and it's percentage : 0.0
 Total NaN values in row 7914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7915 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7916 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7917 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7918 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7919 :- 0 and it's percentage : 0.0
 Total NaN values in row 7920 :- 0 and it's percentage : 0.0
 Total NaN values in row 7921 :- 0 and it's percentage : 0.0
 Total NaN values in row 7922 :- 0 and it's percentage : 0.0
 Total NaN values in row 7923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7924 :- 0 and it's percentage : 0.0
 Total NaN values in row 7925 :- 0 and it's percentage : 0.0

 Total NaN values in row 7926 :- 0 and it's percentage : 0.0
 Total NaN values in row 7927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7928 :- 0 and it's percentage : 0.0
 Total NaN values in row 7929 :- 0 and it's percentage : 0.0
 Total NaN values in row 7930 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7932 :- 0 and it's percentage : 0.0
 Total NaN values in row 7933 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7935 :- 0 and it's percentage : 0.0
 Total NaN values in row 7936 :- 0 and it's percentage : 0.0
 Total NaN values in row 7937 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7938 :- 0 and it's percentage : 0.0
 Total NaN values in row 7939 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7940 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7941 :- 0 and it's percentage : 0.0
 Total NaN values in row 7942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7943 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7945 :- 0 and it's percentage : 0.0
 Total NaN values in row 7946 :- 0 and it's percentage : 0.0
 Total NaN values in row 7947 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7948 :- 0 and it's percentage : 0.0
 Total NaN values in row 7949 :- 0 and it's percentage : 0.0
 Total NaN values in row 7950 :- 0 and it's percentage : 0.0
 Total NaN values in row 7951 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7953 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7955 :- 0 and it's percentage : 0.0
 Total NaN values in row 7956 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7957 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7958 :- 0 and it's percentage : 0.0
 Total NaN values in row 7959 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7960 :- 0 and it's percentage : 0.0
 Total NaN values in row 7961 :- 0 and it's percentage : 0.0
 Total NaN values in row 7962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7963 :- 0 and it's percentage : 0.0
 Total NaN values in row 7964 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7965 :- 0 and it's percentage : 0.0
 Total NaN values in row 7966 :- 0 and it's percentage : 0.0
 Total NaN values in row 7967 :- 0 and it's percentage : 0.0
 Total NaN values in row 7968 :- 0 and it's percentage : 0.0
 Total NaN values in row 7969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7970 :- 0 and it's percentage : 0.0
 Total NaN values in row 7971 :- 0 and it's percentage : 0.0
 Total NaN values in row 7972 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7974 :- 0 and it's percentage : 0.0
 Total NaN values in row 7975 :- 0 and it's percentage : 0.0
 Total NaN values in row 7976 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7977 :- 0 and it's percentage : 0.0
 Total NaN values in row 7978 :- 0 and it's percentage : 0.0
 Total NaN values in row 7979 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7982 :- 0 and it's percentage : 0.0
 Total NaN values in row 7983 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7984 :- 0 and it's percentage : 0.0
 Total NaN values in row 7985 :- 0 and it's percentage : 0.0
 Total NaN values in row 7986 :- 0 and it's percentage : 0.0
 Total NaN values in row 7987 :- 0 and it's percentage : 0.0
 Total NaN values in row 7988 :- 0 and it's percentage : 0.0
 Total NaN values in row 7989 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 7990 :- 0 and it's percentage : 0.0
 Total NaN values in row 7991 :- 0 and it's percentage : 0.0
 Total NaN values in row 7992 :- 0 and it's percentage : 0.0
 Total NaN values in row 7993 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7994 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7995 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7996 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 7997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 7998 :- 0 and it's percentage : 0.0
 Total NaN values in row 7999 :- 0 and it's percentage : 0.0
 Total NaN values in row 8000 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8001 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8002 :- 0 and it's percentage : 0.0
 Total NaN values in row 8003 :- 0 and it's percentage : 0.0
 Total NaN values in row 8004 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8005 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8006 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8007 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8008 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8009 :- 0 and it's percentage : 0.0
 Total NaN values in row 8010 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8011 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8012 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8013 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8014 :- 0 and it's percentage : 0.0
 Total NaN values in row 8015 :- 0 and it's percentage : 0.0
 Total NaN values in row 8016 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8017 :- 0 and it's percentage : 0.0
 Total NaN values in row 8018 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8019 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8020 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8021 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8022 :- 0 and it's percentage : 0.0
 Total NaN values in row 8023 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8024 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8025 :- 0 and it's percentage : 0.0
 Total NaN values in row 8026 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8029 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8031 :- 0 and it's percentage : 0.0
 Total NaN values in row 8032 :- 0 and it's percentage : 0.0
 Total NaN values in row 8033 :- 0 and it's percentage : 0.0
 Total NaN values in row 8034 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8035 :- 0 and it's percentage : 0.0
 Total NaN values in row 8036 :- 0 and it's percentage : 0.0
 Total NaN values in row 8037 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8038 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8039 :- 0 and it's percentage : 0.0
 Total NaN values in row 8040 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8043 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8044 :- 0 and it's percentage : 0.0
 Total NaN values in row 8045 :- 0 and it's percentage : 0.0
 Total NaN values in row 8046 :- 0 and it's percentage : 0.0

 Total NaN values in row 8047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8048 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8049 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 8050 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8051 :- 0 and it's percentage : 0.0
 Total NaN values in row 8052 :- 0 and it's percentage : 0.0
 Total NaN values in row 8053 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8054 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8055 :- 0 and it's percentage : 0.0
 Total NaN values in row 8056 :- 0 and it's percentage : 0.0
 Total NaN values in row 8057 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8058 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8060 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8061 :- 0 and it's percentage : 0.0
 Total NaN values in row 8062 :- 0 and it's percentage : 0.0
 Total NaN values in row 8063 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8064 :- 0 and it's percentage : 0.0
 Total NaN values in row 8065 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8066 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8067 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8068 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8070 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8071 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8072 :- 0 and it's percentage : 0.0
 Total NaN values in row 8073 :- 0 and it's percentage : 0.0
 Total NaN values in row 8074 :- 0 and it's percentage : 0.0
 Total NaN values in row 8075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8077 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8078 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8079 :- 0 and it's percentage : 0.0
 Total NaN values in row 8080 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8081 :- 0 and it's percentage : 0.0
 Total NaN values in row 8082 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8083 :- 0 and it's percentage : 0.0
 Total NaN values in row 8084 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8085 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8086 :- 0 and it's percentage : 0.0
 Total NaN values in row 8087 :- 0 and it's percentage : 0.0
 Total NaN values in row 8088 :- 0 and it's percentage : 0.0
 Total NaN values in row 8089 :- 0 and it's percentage : 0.0
 Total NaN values in row 8090 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8091 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8092 :- 0 and it's percentage : 0.0
 Total NaN values in row 8093 :- 0 and it's percentage : 0.0
 Total NaN values in row 8094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8095 :- 0 and it's percentage : 0.0
 Total NaN values in row 8096 :- 0 and it's percentage : 0.0
 Total NaN values in row 8097 :- 0 and it's percentage : 0.0
 Total NaN values in row 8098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8099 :- 0 and it's percentage : 0.0
 Total NaN values in row 8100 :- 0 and it's percentage : 0.0
 Total NaN values in row 8101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8102 :- 0 and it's percentage : 0.0
 Total NaN values in row 8103 :- 0 and it's percentage : 0.0
 Total NaN values in row 8104 :- 0 and it's percentage : 0.0
 Total NaN values in row 8105 :- 0 and it's percentage : 0.0
 Total NaN values in row 8106 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8107 :- 0 and it's percentage : 0.0
 Total NaN values in row 8108 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8109 :- 0 and it's percentage : 0.0
 Total NaN values in row 8110 :- 0 and it's percentage : 0.0
 Total NaN values in row 8111 :- 0 and it's percentage : 0.0
 Total NaN values in row 8112 :- 0 and it's percentage : 0.0
 Total NaN values in row 8113 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8114 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8115 :- 0 and it's percentage : 0.0
 Total NaN values in row 8116 :- 0 and it's percentage : 0.0
 Total NaN values in row 8117 :- 0 and it's percentage : 0.0
 Total NaN values in row 8118 :- 0 and it's percentage : 0.0
 Total NaN values in row 8119 :- 0 and it's percentage : 0.0
 Total NaN values in row 8120 :- 0 and it's percentage : 0.0
 Total NaN values in row 8121 :- 0 and it's percentage : 0.0
 Total NaN values in row 8122 :- 0 and it's percentage : 0.0
 Total NaN values in row 8123 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8124 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8126 :- 0 and it's percentage : 0.0
 Total NaN values in row 8127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8128 :- 0 and it's percentage : 0.0
 Total NaN values in row 8129 :- 0 and it's percentage : 0.0
 Total NaN values in row 8130 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8131 :- 0 and it's percentage : 0.0
 Total NaN values in row 8132 :- 0 and it's percentage : 0.0
 Total NaN values in row 8133 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8134 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8135 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8136 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8137 :- 0 and it's percentage : 0.0
 Total NaN values in row 8138 :- 0 and it's percentage : 0.0
 Total NaN values in row 8139 :- 0 and it's percentage : 0.0
 Total NaN values in row 8140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8141 :- 0 and it's percentage : 0.0
 Total NaN values in row 8142 :- 0 and it's percentage : 0.0
 Total NaN values in row 8143 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8144 :- 0 and it's percentage : 0.0
 Total NaN values in row 8145 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8147 :- 0 and it's percentage : 0.0
 Total NaN values in row 8148 :- 0 and it's percentage : 0.0
 Total NaN values in row 8149 :- 0 and it's percentage : 0.0
 Total NaN values in row 8150 :- 0 and it's percentage : 0.0
 Total NaN values in row 8151 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8152 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8153 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8154 :- 0 and it's percentage : 0.0
 Total NaN values in row 8155 :- 0 and it's percentage : 0.0
 Total NaN values in row 8156 :- 0 and it's percentage : 0.0
 Total NaN values in row 8157 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8158 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8159 :- 0 and it's percentage : 0.0
 Total NaN values in row 8160 :- 0 and it's percentage : 0.0
 Total NaN values in row 8161 :- 0 and it's percentage : 0.0
 Total NaN values in row 8162 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8163 :- 0 and it's percentage : 0.0
 Total NaN values in row 8164 :- 0 and it's percentage : 0.0
 Total NaN values in row 8165 :- 0 and it's percentage : 0.0
 Total NaN values in row 8166 :- 0 and it's percentage : 0.0
 Total NaN values in row 8167 :- 0 and it's percentage : 0.0
 Total NaN values in row 8168 :- 0 and it's percentage : 0.0
 Total NaN values in row 8169 :- 0 and it's percentage : 0.0
 Total NaN values in row 8170 :- 0 and it's percentage : 0.0
 Total NaN values in row 8171 :- 0 and it's percentage : 0.0
 Total NaN values in row 8172 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8173 :- 0 and it's percentage : 0.0
 Total NaN values in row 8174 :- 0 and it's percentage : 0.0
 Total NaN values in row 8175 :- 0 and it's percentage : 0.0
 Total NaN values in row 8176 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8178 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8179 :- 0 and it's percentage : 0.0
 Total NaN values in row 8180 :- 0 and it's percentage : 0.0
 Total NaN values in row 8181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8182 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8183 :- 0 and it's percentage : 0.0
 Total NaN values in row 8184 :- 0 and it's percentage : 0.0
 Total NaN values in row 8185 :- 0 and it's percentage : 0.0
 Total NaN values in row 8186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8187 :- 0 and it's percentage : 0.0
 Total NaN values in row 8188 :- 0 and it's percentage : 0.0
 Total NaN values in row 8189 :- 0 and it's percentage : 0.0
 Total NaN values in row 8190 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8191 :- 0 and it's percentage : 0.0
 Total NaN values in row 8192 :- 0 and it's percentage : 0.0
 Total NaN values in row 8193 :- 0 and it's percentage : 0.0
 Total NaN values in row 8194 :- 0 and it's percentage : 0.0
 Total NaN values in row 8195 :- 0 and it's percentage : 0.0
 Total NaN values in row 8196 :- 0 and it's percentage : 0.0
 Total NaN values in row 8197 :- 0 and it's percentage : 0.0
 Total NaN values in row 8198 :- 0 and it's percentage : 0.0
 Total NaN values in row 8199 :- 0 and it's percentage : 0.0
 Total NaN values in row 8200 :- 0 and it's percentage : 0.0
 Total NaN values in row 8201 :- 0 and it's percentage : 0.0
 Total NaN values in row 8202 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8203 :- 0 and it's percentage : 0.0
 Total NaN values in row 8204 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 8205 :- 0 and it's percentage : 0.0
 Total NaN values in row 8206 :- 0 and it's percentage : 0.0
 Total NaN values in row 8207 :- 0 and it's percentage : 0.0
 Total NaN values in row 8208 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8209 :- 0 and it's percentage : 0.0
 Total NaN values in row 8210 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8211 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8212 :- 0 and it's percentage : 0.0
 Total NaN values in row 8213 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8214 :- 0 and it's percentage : 0.0
 Total NaN values in row 8215 :- 0 and it's percentage : 0.0
 Total NaN values in row 8216 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8217 :- 0 and it's percentage : 0.0
 Total NaN values in row 8218 :- 0 and it's percentage : 0.0
 Total NaN values in row 8219 :- 0 and it's percentage : 0.0
 Total NaN values in row 8220 :- 0 and it's percentage : 0.0
 Total NaN values in row 8221 :- 0 and it's percentage : 0.0
 Total NaN values in row 8222 :- 0 and it's percentage : 0.0
 Total NaN values in row 8223 :- 0 and it's percentage : 0.0
 Total NaN values in row 8224 :- 0 and it's percentage : 0.0
 Total NaN values in row 8225 :- 0 and it's percentage : 0.0
 Total NaN values in row 8226 :- 0 and it's percentage : 0.0
 Total NaN values in row 8227 :- 0 and it's percentage : 0.0
 Total NaN values in row 8228 :- 0 and it's percentage : 0.0
 Total NaN values in row 8229 :- 0 and it's percentage : 0.0
 Total NaN values in row 8230 :- 0 and it's percentage : 0.0
 Total NaN values in row 8231 :- 0 and it's percentage : 0.0
 Total NaN values in row 8232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8233 :- 0 and it's percentage : 0.0
 Total NaN values in row 8234 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8235 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8236 :- 0 and it's percentage : 0.0
 Total NaN values in row 8237 :- 0 and it's percentage : 0.0
 Total NaN values in row 8238 :- 0 and it's percentage : 0.0
 Total NaN values in row 8239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8240 :- 0 and it's percentage : 0.0
 Total NaN values in row 8241 :- 0 and it's percentage : 0.0
 Total NaN values in row 8242 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8243 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8244 :- 0 and it's percentage : 0.0
 Total NaN values in row 8245 :- 0 and it's percentage : 0.0
 Total NaN values in row 8246 :- 0 and it's percentage : 0.0
 Total NaN values in row 8247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8248 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8249 :- 0 and it's percentage : 0.0
 Total NaN values in row 8250 :- 0 and it's percentage : 0.0
 Total NaN values in row 8251 :- 0 and it's percentage : 0.0
 Total NaN values in row 8252 :- 0 and it's percentage : 0.0
 Total NaN values in row 8253 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8254 :- 0 and it's percentage : 0.0
 Total NaN values in row 8255 :- 0 and it's percentage : 0.0
 Total NaN values in row 8256 :- 0 and it's percentage : 0.0
 Total NaN values in row 8257 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8258 :- 0 and it's percentage : 0.0
 Total NaN values in row 8259 :- 0 and it's percentage : 0.0
 Total NaN values in row 8260 :- 0 and it's percentage : 0.0
 Total NaN values in row 8261 :- 0 and it's percentage : 0.0
 Total NaN values in row 8262 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8263 :- 0 and it's percentage : 0.0
 Total NaN values in row 8264 :- 0 and it's percentage : 0.0
 Total NaN values in row 8265 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8266 :- 0 and it's percentage : 0.0
 Total NaN values in row 8267 :- 0 and it's percentage : 0.0
 Total NaN values in row 8268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8269 :- 0 and it's percentage : 0.0
 Total NaN values in row 8270 :- 0 and it's percentage : 0.0
 Total NaN values in row 8271 :- 0 and it's percentage : 0.0
 Total NaN values in row 8272 :- 0 and it's percentage : 0.0
 Total NaN values in row 8273 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8274 :- 0 and it's percentage : 0.0
 Total NaN values in row 8275 :- 0 and it's percentage : 0.0
 Total NaN values in row 8276 :- 0 and it's percentage : 0.0
 Total NaN values in row 8277 :- 0 and it's percentage : 0.0
 Total NaN values in row 8278 :- 0 and it's percentage : 0.0
 Total NaN values in row 8279 :- 0 and it's percentage : 0.0
 Total NaN values in row 8280 :- 0 and it's percentage : 0.0
 Total NaN values in row 8281 :- 0 and it's percentage : 0.0
 Total NaN values in row 8282 :- 0 and it's percentage : 0.0
 Total NaN values in row 8283 :- 0 and it's percentage : 0.0
 Total NaN values in row 8284 :- 0 and it's percentage : 0.0
 Total NaN values in row 8285 :- 0 and it's percentage : 0.0
 Total NaN values in row 8286 :- 0 and it's percentage : 0.0
 Total NaN values in row 8287 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8288 :- 0 and it's percentage : 0.0
 Total NaN values in row 8289 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8290 :- 0 and it's percentage : 0.0
 Total NaN values in row 8291 :- 0 and it's percentage : 0.0
 Total NaN values in row 8292 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8294 :- 0 and it's percentage : 0.0
 Total NaN values in row 8295 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8296 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8297 :- 0 and it's percentage : 0.0
 Total NaN values in row 8298 :- 0 and it's percentage : 0.0
 Total NaN values in row 8299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8300 :- 0 and it's percentage : 0.0
 Total NaN values in row 8301 :- 0 and it's percentage : 0.0
 Total NaN values in row 8302 :- 0 and it's percentage : 0.0
 Total NaN values in row 8303 :- 0 and it's percentage : 0.0
 Total NaN values in row 8304 :- 0 and it's percentage : 0.0
 Total NaN values in row 8305 :- 0 and it's percentage : 0.0
 Total NaN values in row 8306 :- 0 and it's percentage : 0.0
 Total NaN values in row 8307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8308 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8309 :- 0 and it's percentage : 0.0
 Total NaN values in row 8310 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8311 :- 0 and it's percentage : 0.0
 Total NaN values in row 8312 :- 0 and it's percentage : 0.0
 Total NaN values in row 8313 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8314 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8315 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8316 :- 0 and it's percentage : 0.0
 Total NaN values in row 8317 :- 0 and it's percentage : 0.0
 Total NaN values in row 8318 :- 0 and it's percentage : 0.0
 Total NaN values in row 8319 :- 0 and it's percentage : 0.0
 Total NaN values in row 8320 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8321 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8323 :- 0 and it's percentage : 0.0
 Total NaN values in row 8324 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8325 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8326 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8327 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8329 :- 0 and it's percentage : 0.0
 Total NaN values in row 8330 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8331 :- 0 and it's percentage : 0.0
 Total NaN values in row 8332 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8334 :- 0 and it's percentage : 0.0
 Total NaN values in row 8335 :- 0 and it's percentage : 0.0
 Total NaN values in row 8336 :- 0 and it's percentage : 0.0
 Total NaN values in row 8337 :- 0 and it's percentage : 0.0
 Total NaN values in row 8338 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8339 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8340 :- 0 and it's percentage : 0.0
 Total NaN values in row 8341 :- 0 and it's percentage : 0.0
 Total NaN values in row 8342 :- 0 and it's percentage : 0.0
 Total NaN values in row 8343 :- 0 and it's percentage : 0.0
 Total NaN values in row 8344 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8345 :- 0 and it's percentage : 0.0
 Total NaN values in row 8346 :- 0 and it's percentage : 0.0
 Total NaN values in row 8347 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8348 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8349 :- 0 and it's percentage : 0.0
 Total NaN values in row 8350 :- 0 and it's percentage : 0.0
 Total NaN values in row 8351 :- 0 and it's percentage : 0.0
 Total NaN values in row 8352 :- 0 and it's percentage : 0.0
 Total NaN values in row 8353 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8354 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8355 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8356 :- 0 and it's percentage : 0.0
 Total NaN values in row 8357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8358 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8359 :- 0 and it's percentage : 0.0
 Total NaN values in row 8360 :- 0 and it's percentage : 0.0
 Total NaN values in row 8361 :- 0 and it's percentage : 0.0
 Total NaN values in row 8362 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8363 :- 0 and it's percentage : 0.0
 Total NaN values in row 8364 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8365 :- 0 and it's percentage : 0.0
 Total NaN values in row 8366 :- 0 and it's percentage : 0.0
 Total NaN values in row 8367 :- 0 and it's percentage : 0.0
 Total NaN values in row 8368 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8369 :- 0 and it's percentage : 0.0
 Total NaN values in row 8370 :- 0 and it's percentage : 0.0
 Total NaN values in row 8371 :- 0 and it's percentage : 0.0
 Total NaN values in row 8372 :- 0 and it's percentage : 0.0
 Total NaN values in row 8373 :- 0 and it's percentage : 0.0
 Total NaN values in row 8374 :- 0 and it's percentage : 0.0
 Total NaN values in row 8375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8376 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8378 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8379 :- 0 and it's percentage : 0.0
 Total NaN values in row 8380 :- 0 and it's percentage : 0.0
 Total NaN values in row 8381 :- 0 and it's percentage : 0.0
 Total NaN values in row 8382 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8383 :- 0 and it's percentage : 0.0

 Total NaN values in row 8384 :- 0 and it's percentage : 0.0
 Total NaN values in row 8385 :- 0 and it's percentage : 0.0
 Total NaN values in row 8386 :- 0 and it's percentage : 0.0
 Total NaN values in row 8387 :- 0 and it's percentage : 0.0
 Total NaN values in row 8388 :- 0 and it's percentage : 0.0
 Total NaN values in row 8389 :- 0 and it's percentage : 0.0
 Total NaN values in row 8390 :- 0 and it's percentage : 0.0
 Total NaN values in row 8391 :- 0 and it's percentage : 0.0
 Total NaN values in row 8392 :- 0 and it's percentage : 0.0
 Total NaN values in row 8393 :- 0 and it's percentage : 0.0
 Total NaN values in row 8394 :- 0 and it's percentage : 0.0
 Total NaN values in row 8395 :- 0 and it's percentage : 0.0
 Total NaN values in row 8396 :- 0 and it's percentage : 0.0
 Total NaN values in row 8397 :- 0 and it's percentage : 0.0
 Total NaN values in row 8398 :- 0 and it's percentage : 0.0
 Total NaN values in row 8399 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8400 :- 0 and it's percentage : 0.0
 Total NaN values in row 8401 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8402 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8403 :- 0 and it's percentage : 0.0
 Total NaN values in row 8404 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8405 :- 0 and it's percentage : 0.0
 Total NaN values in row 8406 :- 0 and it's percentage : 0.0
 Total NaN values in row 8407 :- 0 and it's percentage : 0.0
 Total NaN values in row 8408 :- 0 and it's percentage : 0.0
 Total NaN values in row 8409 :- 0 and it's percentage : 0.0
 Total NaN values in row 8410 :- 0 and it's percentage : 0.0
 Total NaN values in row 8411 :- 0 and it's percentage : 0.0
 Total NaN values in row 8412 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8413 :- 0 and it's percentage : 0.0
 Total NaN values in row 8414 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8415 :- 0 and it's percentage : 0.0
 Total NaN values in row 8416 :- 0 and it's percentage : 0.0
 Total NaN values in row 8417 :- 0 and it's percentage : 0.0
 Total NaN values in row 8418 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8419 :- 0 and it's percentage : 0.0
 Total NaN values in row 8420 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8421 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8422 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8423 :- 0 and it's percentage : 0.0
 Total NaN values in row 8424 :- 0 and it's percentage : 0.0
 Total NaN values in row 8425 :- 0 and it's percentage : 0.0
 Total NaN values in row 8426 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8427 :- 0 and it's percentage : 0.0
 Total NaN values in row 8428 :- 0 and it's percentage : 0.0
 Total NaN values in row 8429 :- 0 and it's percentage : 0.0
 Total NaN values in row 8430 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8431 :- 0 and it's percentage : 0.0
 Total NaN values in row 8432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8433 :- 0 and it's percentage : 0.0
 Total NaN values in row 8434 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8435 :- 0 and it's percentage : 0.0
 Total NaN values in row 8436 :- 0 and it's percentage : 0.0
 Total NaN values in row 8437 :- 0 and it's percentage : 0.0
 Total NaN values in row 8438 :- 0 and it's percentage : 0.0
 Total NaN values in row 8439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8440 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8441 :- 0 and it's percentage : 0.0
 Total NaN values in row 8442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8443 :- 0 and it's percentage : 0.0
 Total NaN values in row 8444 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8445 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8446 :- 0 and it's percentage : 0.0
 Total NaN values in row 8447 :- 0 and it's percentage : 0.0
 Total NaN values in row 8448 :- 0 and it's percentage : 0.0
 Total NaN values in row 8449 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8450 :- 0 and it's percentage : 0.0
 Total NaN values in row 8451 :- 0 and it's percentage : 0.0
 Total NaN values in row 8452 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8453 :- 0 and it's percentage : 0.0
 Total NaN values in row 8454 :- 0 and it's percentage : 0.0
 Total NaN values in row 8455 :- 0 and it's percentage : 0.0
 Total NaN values in row 8456 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8457 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8458 :- 0 and it's percentage : 0.0
 Total NaN values in row 8459 :- 0 and it's percentage : 0.0
 Total NaN values in row 8460 :- 0 and it's percentage : 0.0
 Total NaN values in row 8461 :- 0 and it's percentage : 0.0
 Total NaN values in row 8462 :- 0 and it's percentage : 0.0
 Total NaN values in row 8463 :- 0 and it's percentage : 0.0
 Total NaN values in row 8464 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8465 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8466 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8467 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8468 :- 0 and it's percentage : 0.0
 Total NaN values in row 8469 :- 0 and it's percentage : 0.0
 Total NaN values in row 8470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8471 :- 0 and it's percentage : 0.0
 Total NaN values in row 8472 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8473 :- 0 and it's percentage : 0.0
 Total NaN values in row 8474 :- 0 and it's percentage : 0.0
 Total NaN values in row 8475 :- 0 and it's percentage : 0.0
 Total NaN values in row 8476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8477 :- 0 and it's percentage : 0.0
 Total NaN values in row 8478 :- 0 and it's percentage : 0.0
 Total NaN values in row 8479 :- 0 and it's percentage : 0.0
 Total NaN values in row 8480 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8481 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8482 :- 0 and it's percentage : 0.0
 Total NaN values in row 8483 :- 0 and it's percentage : 0.0
 Total NaN values in row 8484 :- 0 and it's percentage : 0.0
 Total NaN values in row 8485 :- 0 and it's percentage : 0.0
 Total NaN values in row 8486 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8487 :- 0 and it's percentage : 0.0
 Total NaN values in row 8488 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8489 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8490 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8491 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8492 :- 0 and it's percentage : 0.0
 Total NaN values in row 8493 :- 0 and it's percentage : 0.0
 Total NaN values in row 8494 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8495 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8496 :- 0 and it's percentage : 0.0
 Total NaN values in row 8497 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8498 :- 0 and it's percentage : 0.0
 Total NaN values in row 8499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8500 :- 0 and it's percentage : 0.0
 Total NaN values in row 8501 :- 0 and it's percentage : 0.0
 Total NaN values in row 8502 :- 0 and it's percentage : 0.0
 Total NaN values in row 8503 :- 0 and it's percentage : 0.0
 Total NaN values in row 8504 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8505 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8506 :- 0 and it's percentage : 0.0
 Total NaN values in row 8507 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8508 :- 0 and it's percentage : 0.0
 Total NaN values in row 8509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8510 :- 0 and it's percentage : 0.0
 Total NaN values in row 8511 :- 0 and it's percentage : 0.0
 Total NaN values in row 8512 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8513 :- 0 and it's percentage : 0.0
 Total NaN values in row 8514 :- 0 and it's percentage : 0.0
 Total NaN values in row 8515 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8516 :- 0 and it's percentage : 0.0
 Total NaN values in row 8517 :- 0 and it's percentage : 0.0
 Total NaN values in row 8518 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8519 :- 0 and it's percentage : 0.0
 Total NaN values in row 8520 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8521 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8522 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8523 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8524 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8525 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8527 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8528 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8529 :- 0 and it's percentage : 0.0
 Total NaN values in row 8530 :- 0 and it's percentage : 0.0
 Total NaN values in row 8531 :- 0 and it's percentage : 0.0
 Total NaN values in row 8532 :- 0 and it's percentage : 0.0
 Total NaN values in row 8533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8534 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8535 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8536 :- 0 and it's percentage : 0.0
 Total NaN values in row 8537 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8538 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8539 :- 0 and it's percentage : 0.0
 Total NaN values in row 8540 :- 7 and it's percentage : 38.888888888888886

 Total NaN values in row 8541 :- 0 and it's percentage : 0.0
 Total NaN values in row 8542 :- 0 and it's percentage : 0.0
 Total NaN values in row 8543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8544 :- 0 and it's percentage : 0.0
 Total NaN values in row 8545 :- 0 and it's percentage : 0.0
 Total NaN values in row 8546 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8547 :- 0 and it's percentage : 0.0
 Total NaN values in row 8548 :- 0 and it's percentage : 0.0
 Total NaN values in row 8549 :- 0 and it's percentage : 0.0
 Total NaN values in row 8550 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8551 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8552 :- 0 and it's percentage : 0.0
 Total NaN values in row 8553 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8554 :- 0 and it's percentage : 0.0
 Total NaN values in row 8555 :- 0 and it's percentage : 0.0
 Total NaN values in row 8556 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8557 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8558 :- 0 and it's percentage : 0.0
 Total NaN values in row 8559 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8560 :- 0 and it's percentage : 0.0
 Total NaN values in row 8561 :- 0 and it's percentage : 0.0
 Total NaN values in row 8562 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8563 :- 0 and it's percentage : 0.0
 Total NaN values in row 8564 :- 0 and it's percentage : 0.0
 Total NaN values in row 8565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8566 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8567 :- 0 and it's percentage : 0.0
 Total NaN values in row 8568 :- 0 and it's percentage : 0.0
 Total NaN values in row 8569 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8570 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8571 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8572 :- 0 and it's percentage : 0.0
 Total NaN values in row 8573 :- 0 and it's percentage : 0.0
 Total NaN values in row 8574 :- 0 and it's percentage : 0.0
 Total NaN values in row 8575 :- 0 and it's percentage : 0.0
 Total NaN values in row 8576 :- 0 and it's percentage : 0.0
 Total NaN values in row 8577 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8578 :- 0 and it's percentage : 0.0
 Total NaN values in row 8579 :- 0 and it's percentage : 0.0
 Total NaN values in row 8580 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8581 :- 0 and it's percentage : 0.0
 Total NaN values in row 8582 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8583 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8584 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8585 :- 0 and it's percentage : 0.0
 Total NaN values in row 8586 :- 0 and it's percentage : 0.0
 Total NaN values in row 8587 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8588 :- 0 and it's percentage : 0.0
 Total NaN values in row 8589 :- 0 and it's percentage : 0.0
 Total NaN values in row 8590 :- 0 and it's percentage : 0.0
 Total NaN values in row 8591 :- 0 and it's percentage : 0.0
 Total NaN values in row 8592 :- 0 and it's percentage : 0.0
 Total NaN values in row 8593 :- 0 and it's percentage : 0.0
 Total NaN values in row 8594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8595 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8596 :- 0 and it's percentage : 0.0
 Total NaN values in row 8597 :- 0 and it's percentage : 0.0
 Total NaN values in row 8598 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8599 :- 0 and it's percentage : 0.0
 Total NaN values in row 8600 :- 0 and it's percentage : 0.0
 Total NaN values in row 8601 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8602 :- 0 and it's percentage : 0.0
 Total NaN values in row 8603 :- 0 and it's percentage : 0.0
 Total NaN values in row 8604 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8605 :- 0 and it's percentage : 0.0
 Total NaN values in row 8606 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8607 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8608 :- 0 and it's percentage : 0.0
 Total NaN values in row 8609 :- 0 and it's percentage : 0.0
 Total NaN values in row 8610 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8611 :- 0 and it's percentage : 0.0
 Total NaN values in row 8612 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8613 :- 0 and it's percentage : 0.0
 Total NaN values in row 8614 :- 0 and it's percentage : 0.0
 Total NaN values in row 8615 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8616 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8617 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8618 :- 0 and it's percentage : 0.0
 Total NaN values in row 8619 :- 0 and it's percentage : 0.0
 Total NaN values in row 8620 :- 0 and it's percentage : 0.0
 Total NaN values in row 8621 :- 0 and it's percentage : 0.0
 Total NaN values in row 8622 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8623 :- 0 and it's percentage : 0.0
 Total NaN values in row 8624 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8625 :- 0 and it's percentage : 0.0
 Total NaN values in row 8626 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8627 :- 0 and it's percentage : 0.0
 Total NaN values in row 8628 :- 0 and it's percentage : 0.0
 Total NaN values in row 8629 :- 0 and it's percentage : 0.0
 Total NaN values in row 8630 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8631 :- 0 and it's percentage : 0.0
 Total NaN values in row 8632 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8633 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8634 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8635 :- 0 and it's percentage : 0.0
 Total NaN values in row 8636 :- 0 and it's percentage : 0.0
 Total NaN values in row 8637 :- 0 and it's percentage : 0.0
 Total NaN values in row 8638 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8639 :- 0 and it's percentage : 0.0
 Total NaN values in row 8640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8641 :- 0 and it's percentage : 0.0
 Total NaN values in row 8642 :- 0 and it's percentage : 0.0
 Total NaN values in row 8643 :- 0 and it's percentage : 0.0
 Total NaN values in row 8644 :- 0 and it's percentage : 0.0
 Total NaN values in row 8645 :- 0 and it's percentage : 0.0
 Total NaN values in row 8646 :- 0 and it's percentage : 0.0
 Total NaN values in row 8647 :- 0 and it's percentage : 0.0
 Total NaN values in row 8648 :- 0 and it's percentage : 0.0
 Total NaN values in row 8649 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8650 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8651 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8652 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8653 :- 0 and it's percentage : 0.0
 Total NaN values in row 8654 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8655 :- 0 and it's percentage : 0.0
 Total NaN values in row 8656 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8657 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8658 :- 0 and it's percentage : 0.0
 Total NaN values in row 8659 :- 0 and it's percentage : 0.0
 Total NaN values in row 8660 :- 0 and it's percentage : 0.0
 Total NaN values in row 8661 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8662 :- 0 and it's percentage : 0.0
 Total NaN values in row 8663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8664 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8666 :- 0 and it's percentage : 0.0
 Total NaN values in row 8667 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8668 :- 0 and it's percentage : 0.0
 Total NaN values in row 8669 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8670 :- 0 and it's percentage : 0.0
 Total NaN values in row 8671 :- 0 and it's percentage : 0.0
 Total NaN values in row 8672 :- 0 and it's percentage : 0.0
 Total NaN values in row 8673 :- 0 and it's percentage : 0.0
 Total NaN values in row 8674 :- 0 and it's percentage : 0.0
 Total NaN values in row 8675 :- 0 and it's percentage : 0.0

 Total NaN values in row 8676 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8677 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8678 :- 0 and it's percentage : 0.0
 Total NaN values in row 8679 :- 0 and it's percentage : 0.0
 Total NaN values in row 8680 :- 0 and it's percentage : 0.0
 Total NaN values in row 8681 :- 0 and it's percentage : 0.0
 Total NaN values in row 8682 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8683 :- 0 and it's percentage : 0.0
 Total NaN values in row 8684 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8685 :- 0 and it's percentage : 0.0
 Total NaN values in row 8686 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8687 :- 0 and it's percentage : 0.0
 Total NaN values in row 8688 :- 0 and it's percentage : 0.0
 Total NaN values in row 8689 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8690 :- 0 and it's percentage : 0.0
 Total NaN values in row 8691 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8692 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8693 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8694 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8696 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8697 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8698 :- 0 and it's percentage : 0.0
 Total NaN values in row 8699 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8701 :- 0 and it's percentage : 0.0
 Total NaN values in row 8702 :- 0 and it's percentage : 0.0
 Total NaN values in row 8703 :- 0 and it's percentage : 0.0
 Total NaN values in row 8704 :- 0 and it's percentage : 0.0
 Total NaN values in row 8705 :- 0 and it's percentage : 0.0
 Total NaN values in row 8706 :- 0 and it's percentage : 0.0
 Total NaN values in row 8707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8708 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8709 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8710 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8712 :- 0 and it's percentage : 0.0
 Total NaN values in row 8713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8714 :- 0 and it's percentage : 0.0
 Total NaN values in row 8715 :- 0 and it's percentage : 0.0
 Total NaN values in row 8716 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8717 :- 0 and it's percentage : 0.0
 Total NaN values in row 8718 :- 0 and it's percentage : 0.0
 Total NaN values in row 8719 :- 0 and it's percentage : 0.0
 Total NaN values in row 8720 :- 0 and it's percentage : 0.0
 Total NaN values in row 8721 :- 0 and it's percentage : 0.0
 Total NaN values in row 8722 :- 0 and it's percentage : 0.0
 Total NaN values in row 8723 :- 0 and it's percentage : 0.0
 Total NaN values in row 8724 :- 0 and it's percentage : 0.0
 Total NaN values in row 8725 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8726 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8727 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8728 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8729 :- 0 and it's percentage : 0.0
 Total NaN values in row 8730 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8731 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8732 :- 0 and it's percentage : 0.0
 Total NaN values in row 8733 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8734 :- 0 and it's percentage : 0.0
 Total NaN values in row 8735 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8736 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8737 :- 0 and it's percentage : 0.0
 Total NaN values in row 8738 :- 0 and it's percentage : 0.0
 Total NaN values in row 8739 :- 0 and it's percentage : 0.0
 Total NaN values in row 8740 :- 0 and it's percentage : 0.0
 Total NaN values in row 8741 :- 0 and it's percentage : 0.0
 Total NaN values in row 8742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8743 :- 0 and it's percentage : 0.0
 Total NaN values in row 8744 :- 0 and it's percentage : 0.0
 Total NaN values in row 8745 :- 0 and it's percentage : 0.0
 Total NaN values in row 8746 :- 0 and it's percentage : 0.0
 Total NaN values in row 8747 :- 0 and it's percentage : 0.0
 Total NaN values in row 8748 :- 0 and it's percentage : 0.0
 Total NaN values in row 8749 :- 0 and it's percentage : 0.0
 Total NaN values in row 8750 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8751 :- 0 and it's percentage : 0.0
 Total NaN values in row 8752 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8753 :- 0 and it's percentage : 0.0
 Total NaN values in row 8754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8755 :- 0 and it's percentage : 0.0
 Total NaN values in row 8756 :- 0 and it's percentage : 0.0
 Total NaN values in row 8757 :- 0 and it's percentage : 0.0
 Total NaN values in row 8758 :- 0 and it's percentage : 0.0
 Total NaN values in row 8759 :- 0 and it's percentage : 0.0
 Total NaN values in row 8760 :- 0 and it's percentage : 0.0
 Total NaN values in row 8761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8762 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8763 :- 0 and it's percentage : 0.0
 Total NaN values in row 8764 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8765 :- 0 and it's percentage : 0.0
 Total NaN values in row 8766 :- 0 and it's percentage : 0.0
 Total NaN values in row 8767 :- 0 and it's percentage : 0.0
 Total NaN values in row 8768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8770 :- 0 and it's percentage : 0.0
 Total NaN values in row 8771 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8772 :- 0 and it's percentage : 0.0
 Total NaN values in row 8773 :- 0 and it's percentage : 0.0
 Total NaN values in row 8774 :- 0 and it's percentage : 0.0
 Total NaN values in row 8775 :- 0 and it's percentage : 0.0
 Total NaN values in row 8776 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8778 :- 0 and it's percentage : 0.0
 Total NaN values in row 8779 :- 0 and it's percentage : 0.0
 Total NaN values in row 8780 :- 0 and it's percentage : 0.0
 Total NaN values in row 8781 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8782 :- 0 and it's percentage : 0.0
 Total NaN values in row 8783 :- 0 and it's percentage : 0.0
 Total NaN values in row 8784 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8785 :- 0 and it's percentage : 0.0
 Total NaN values in row 8786 :- 0 and it's percentage : 0.0
 Total NaN values in row 8787 :- 0 and it's percentage : 0.0
 Total NaN values in row 8788 :- 0 and it's percentage : 0.0
 Total NaN values in row 8789 :- 0 and it's percentage : 0.0
 Total NaN values in row 8790 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8792 :- 0 and it's percentage : 0.0
 Total NaN values in row 8793 :- 0 and it's percentage : 0.0
 Total NaN values in row 8794 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8795 :- 0 and it's percentage : 0.0
 Total NaN values in row 8796 :- 0 and it's percentage : 0.0
 Total NaN values in row 8797 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8798 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8799 :- 0 and it's percentage : 0.0
 Total NaN values in row 8800 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8801 :- 0 and it's percentage : 0.0
 Total NaN values in row 8802 :- 0 and it's percentage : 0.0
 Total NaN values in row 8803 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8804 :- 0 and it's percentage : 0.0
 Total NaN values in row 8805 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8806 :- 0 and it's percentage : 0.0
 Total NaN values in row 8807 :- 0 and it's percentage : 0.0
 Total NaN values in row 8808 :- 0 and it's percentage : 0.0
 Total NaN values in row 8809 :- 0 and it's percentage : 0.0
 Total NaN values in row 8810 :- 0 and it's percentage : 0.0
 Total NaN values in row 8811 :- 0 and it's percentage : 0.0

 Total NaN values in row 8812 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8813 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8814 :- 0 and it's percentage : 0.0
 Total NaN values in row 8815 :- 0 and it's percentage : 0.0
 Total NaN values in row 8816 :- 0 and it's percentage : 0.0
 Total NaN values in row 8817 :- 0 and it's percentage : 0.0
 Total NaN values in row 8818 :- 0 and it's percentage : 0.0
 Total NaN values in row 8819 :- 0 and it's percentage : 0.0
 Total NaN values in row 8820 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8821 :- 0 and it's percentage : 0.0
 Total NaN values in row 8822 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8823 :- 0 and it's percentage : 0.0
 Total NaN values in row 8824 :- 0 and it's percentage : 0.0
 Total NaN values in row 8825 :- 0 and it's percentage : 0.0
 Total NaN values in row 8826 :- 0 and it's percentage : 0.0
 Total NaN values in row 8827 :- 0 and it's percentage : 0.0
 Total NaN values in row 8828 :- 0 and it's percentage : 0.0
 Total NaN values in row 8829 :- 0 and it's percentage : 0.0
 Total NaN values in row 8830 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8831 :- 0 and it's percentage : 0.0
 Total NaN values in row 8832 :- 0 and it's percentage : 0.0
 Total NaN values in row 8833 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8834 :- 0 and it's percentage : 0.0
 Total NaN values in row 8835 :- 0 and it's percentage : 0.0
 Total NaN values in row 8836 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8837 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8838 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8839 :- 0 and it's percentage : 0.0
 Total NaN values in row 8840 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8841 :- 0 and it's percentage : 0.0
 Total NaN values in row 8842 :- 0 and it's percentage : 0.0
 Total NaN values in row 8843 :- 0 and it's percentage : 0.0
 Total NaN values in row 8844 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8845 :- 0 and it's percentage : 0.0
 Total NaN values in row 8846 :- 0 and it's percentage : 0.0
 Total NaN values in row 8847 :- 0 and it's percentage : 0.0
 Total NaN values in row 8848 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8849 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8850 :- 0 and it's percentage : 0.0
 Total NaN values in row 8851 :- 0 and it's percentage : 0.0
 Total NaN values in row 8852 :- 0 and it's percentage : 0.0
 Total NaN values in row 8853 :- 0 and it's percentage : 0.0
 Total NaN values in row 8854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8855 :- 0 and it's percentage : 0.0
 Total NaN values in row 8856 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8857 :- 0 and it's percentage : 0.0
 Total NaN values in row 8858 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8859 :- 0 and it's percentage : 0.0
 Total NaN values in row 8860 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8861 :- 0 and it's percentage : 0.0
 Total NaN values in row 8862 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 8863 :- 0 and it's percentage : 0.0
 Total NaN values in row 8864 :- 0 and it's percentage : 0.0
 Total NaN values in row 8865 :- 0 and it's percentage : 0.0
 Total NaN values in row 8866 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8867 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8868 :- 0 and it's percentage : 0.0
 Total NaN values in row 8869 :- 0 and it's percentage : 0.0
 Total NaN values in row 8870 :- 0 and it's percentage : 0.0
 Total NaN values in row 8871 :- 0 and it's percentage : 0.0
 Total NaN values in row 8872 :- 0 and it's percentage : 0.0
 Total NaN values in row 8873 :- 0 and it's percentage : 0.0
 Total NaN values in row 8874 :- 0 and it's percentage : 0.0
 Total NaN values in row 8875 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8876 :- 0 and it's percentage : 0.0
 Total NaN values in row 8877 :- 0 and it's percentage : 0.0
 Total NaN values in row 8878 :- 0 and it's percentage : 0.0
 Total NaN values in row 8879 :- 0 and it's percentage : 0.0
 Total NaN values in row 8880 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8881 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8882 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8883 :- 0 and it's percentage : 0.0
 Total NaN values in row 8884 :- 0 and it's percentage : 0.0
 Total NaN values in row 8885 :- 0 and it's percentage : 0.0
 Total NaN values in row 8886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8887 :- 0 and it's percentage : 0.0
 Total NaN values in row 8888 :- 0 and it's percentage : 0.0
 Total NaN values in row 8889 :- 0 and it's percentage : 0.0
 Total NaN values in row 8890 :- 0 and it's percentage : 0.0
 Total NaN values in row 8891 :- 0 and it's percentage : 0.0
 Total NaN values in row 8892 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8893 :- 0 and it's percentage : 0.0
 Total NaN values in row 8894 :- 0 and it's percentage : 0.0
 Total NaN values in row 8895 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8896 :- 0 and it's percentage : 0.0
 Total NaN values in row 8897 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8899 :- 0 and it's percentage : 0.0
 Total NaN values in row 8900 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8901 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8902 :- 0 and it's percentage : 0.0
 Total NaN values in row 8903 :- 0 and it's percentage : 0.0
 Total NaN values in row 8904 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8905 :- 0 and it's percentage : 0.0
 Total NaN values in row 8906 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8907 :- 0 and it's percentage : 0.0
 Total NaN values in row 8908 :- 0 and it's percentage : 0.0
 Total NaN values in row 8909 :- 0 and it's percentage : 0.0
 Total NaN values in row 8910 :- 0 and it's percentage : 0.0
 Total NaN values in row 8911 :- 0 and it's percentage : 0.0
 Total NaN values in row 8912 :- 0 and it's percentage : 0.0
 Total NaN values in row 8913 :- 0 and it's percentage : 0.0
 Total NaN values in row 8914 :- 0 and it's percentage : 0.0
 Total NaN values in row 8915 :- 0 and it's percentage : 0.0
 Total NaN values in row 8916 :- 0 and it's percentage : 0.0
 Total NaN values in row 8917 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8918 :- 0 and it's percentage : 0.0
 Total NaN values in row 8919 :- 0 and it's percentage : 0.0
 Total NaN values in row 8920 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8921 :- 0 and it's percentage : 0.0
 Total NaN values in row 8922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8923 :- 0 and it's percentage : 0.0
 Total NaN values in row 8924 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8925 :- 0 and it's percentage : 0.0
 Total NaN values in row 8926 :- 0 and it's percentage : 0.0
 Total NaN values in row 8927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8928 :- 0 and it's percentage : 0.0
 Total NaN values in row 8929 :- 0 and it's percentage : 0.0
 Total NaN values in row 8930 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8932 :- 0 and it's percentage : 0.0
 Total NaN values in row 8933 :- 0 and it's percentage : 0.0
 Total NaN values in row 8934 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8935 :- 0 and it's percentage : 0.0
 Total NaN values in row 8936 :- 0 and it's percentage : 0.0
 Total NaN values in row 8937 :- 0 and it's percentage : 0.0
 Total NaN values in row 8938 :- 0 and it's percentage : 0.0
 Total NaN values in row 8939 :- 0 and it's percentage : 0.0
 Total NaN values in row 8940 :- 0 and it's percentage : 0.0
 Total NaN values in row 8941 :- 0 and it's percentage : 0.0
 Total NaN values in row 8942 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 8943 :- 0 and it's percentage : 0.0
 Total NaN values in row 8944 :- 0 and it's percentage : 0.0
 Total NaN values in row 8945 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8946 :- 0 and it's percentage : 0.0
 Total NaN values in row 8947 :- 0 and it's percentage : 0.0
 Total NaN values in row 8948 :- 0 and it's percentage : 0.0

 Total NaN values in row 8949 :- 0 and it's percentage : 0.0
 Total NaN values in row 8950 :- 0 and it's percentage : 0.0
 Total NaN values in row 8951 :- 0 and it's percentage : 0.0
 Total NaN values in row 8952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8953 :- 0 and it's percentage : 0.0
 Total NaN values in row 8954 :- 0 and it's percentage : 0.0
 Total NaN values in row 8955 :- 0 and it's percentage : 0.0
 Total NaN values in row 8956 :- 0 and it's percentage : 0.0
 Total NaN values in row 8957 :- 0 and it's percentage : 0.0
 Total NaN values in row 8958 :- 0 and it's percentage : 0.0
 Total NaN values in row 8959 :- 0 and it's percentage : 0.0
 Total NaN values in row 8960 :- 0 and it's percentage : 0.0
 Total NaN values in row 8961 :- 0 and it's percentage : 0.0
 Total NaN values in row 8962 :- 0 and it's percentage : 0.0
 Total NaN values in row 8963 :- 0 and it's percentage : 0.0
 Total NaN values in row 8964 :- 0 and it's percentage : 0.0
 Total NaN values in row 8965 :- 0 and it's percentage : 0.0
 Total NaN values in row 8966 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8967 :- 0 and it's percentage : 0.0
 Total NaN values in row 8968 :- 0 and it's percentage : 0.0
 Total NaN values in row 8969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8970 :- 0 and it's percentage : 0.0
 Total NaN values in row 8971 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8972 :- 0 and it's percentage : 0.0
 Total NaN values in row 8973 :- 0 and it's percentage : 0.0
 Total NaN values in row 8974 :- 0 and it's percentage : 0.0
 Total NaN values in row 8975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8976 :- 0 and it's percentage : 0.0
 Total NaN values in row 8977 :- 0 and it's percentage : 0.0
 Total NaN values in row 8978 :- 0 and it's percentage : 0.0
 Total NaN values in row 8979 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 8980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8981 :- 0 and it's percentage : 0.0
 Total NaN values in row 8982 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8983 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8985 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8986 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8987 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8988 :- 0 and it's percentage : 0.0
 Total NaN values in row 8989 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8991 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8992 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8993 :- 0 and it's percentage : 0.0
 Total NaN values in row 8994 :- 0 and it's percentage : 0.0
 Total NaN values in row 8995 :- 0 and it's percentage : 0.0
 Total NaN values in row 8996 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 8997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 8998 :- 0 and it's percentage : 0.0
 Total NaN values in row 8999 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9000 :- 0 and it's percentage : 0.0
 Total NaN values in row 9001 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9003 :- 0 and it's percentage : 0.0
 Total NaN values in row 9004 :- 0 and it's percentage : 0.0
 Total NaN values in row 9005 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9006 :- 0 and it's percentage : 0.0
 Total NaN values in row 9007 :- 0 and it's percentage : 0.0
 Total NaN values in row 9008 :- 0 and it's percentage : 0.0
 Total NaN values in row 9009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9010 :- 0 and it's percentage : 0.0
 Total NaN values in row 9011 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9012 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9013 :- 0 and it's percentage : 0.0
 Total NaN values in row 9014 :- 0 and it's percentage : 0.0
 Total NaN values in row 9015 :- 0 and it's percentage : 0.0
 Total NaN values in row 9016 :- 0 and it's percentage : 0.0
 Total NaN values in row 9017 :- 0 and it's percentage : 0.0
 Total NaN values in row 9018 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9019 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9020 :- 0 and it's percentage : 0.0
 Total NaN values in row 9021 :- 0 and it's percentage : 0.0
 Total NaN values in row 9022 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9023 :- 0 and it's percentage : 0.0
 Total NaN values in row 9024 :- 0 and it's percentage : 0.0
 Total NaN values in row 9025 :- 0 and it's percentage : 0.0
 Total NaN values in row 9026 :- 0 and it's percentage : 0.0
 Total NaN values in row 9027 :- 0 and it's percentage : 0.0
 Total NaN values in row 9028 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9029 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9030 :- 0 and it's percentage : 0.0
 Total NaN values in row 9031 :- 0 and it's percentage : 0.0
 Total NaN values in row 9032 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9033 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9034 :- 0 and it's percentage : 0.0
 Total NaN values in row 9035 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9036 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9037 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9038 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9039 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9040 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9041 :- 0 and it's percentage : 0.0
 Total NaN values in row 9042 :- 0 and it's percentage : 0.0
 Total NaN values in row 9043 :- 0 and it's percentage : 0.0
 Total NaN values in row 9044 :- 0 and it's percentage : 0.0
 Total NaN values in row 9045 :- 0 and it's percentage : 0.0
 Total NaN values in row 9046 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9048 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9049 :- 0 and it's percentage : 0.0
 Total NaN values in row 9050 :- 0 and it's percentage : 0.0
 Total NaN values in row 9051 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9052 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9053 :- 0 and it's percentage : 0.0
 Total NaN values in row 9054 :- 0 and it's percentage : 0.0
 Total NaN values in row 9055 :- 0 and it's percentage : 0.0
 Total NaN values in row 9056 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9057 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9058 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9059 :- 0 and it's percentage : 0.0
 Total NaN values in row 9060 :- 0 and it's percentage : 0.0
 Total NaN values in row 9061 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9062 :- 0 and it's percentage : 0.0
 Total NaN values in row 9063 :- 0 and it's percentage : 0.0
 Total NaN values in row 9064 :- 0 and it's percentage : 0.0
 Total NaN values in row 9065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9066 :- 0 and it's percentage : 0.0
 Total NaN values in row 9067 :- 0 and it's percentage : 0.0
 Total NaN values in row 9068 :- 0 and it's percentage : 0.0
 Total NaN values in row 9069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9070 :- 0 and it's percentage : 0.0
 Total NaN values in row 9071 :- 0 and it's percentage : 0.0
 Total NaN values in row 9072 :- 0 and it's percentage : 0.0
 Total NaN values in row 9073 :- 0 and it's percentage : 0.0
 Total NaN values in row 9074 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9075 :- 0 and it's percentage : 0.0
 Total NaN values in row 9076 :- 0 and it's percentage : 0.0
 Total NaN values in row 9077 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9078 :- 0 and it's percentage : 0.0
 Total NaN values in row 9079 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 9080 :- 0 and it's percentage : 0.0
 Total NaN values in row 9081 :- 0 and it's percentage : 0.0
 Total NaN values in row 9082 :- 0 and it's percentage : 0.0
 Total NaN values in row 9083 :- 0 and it's percentage : 0.0
 Total NaN values in row 9084 :- 0 and it's percentage : 0.0
 Total NaN values in row 9085 :- 0 and it's percentage : 0.0
 Total NaN values in row 9086 :- 0 and it's percentage : 0.0
 Total NaN values in row 9087 :- 0 and it's percentage : 0.0
 Total NaN values in row 9088 :- 0 and it's percentage : 0.0
 Total NaN values in row 9089 :- 0 and it's percentage : 0.0
 Total NaN values in row 9090 :- 0 and it's percentage : 0.0
 Total NaN values in row 9091 :- 0 and it's percentage : 0.0
 Total NaN values in row 9092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9093 :- 0 and it's percentage : 0.0
 Total NaN values in row 9094 :- 0 and it's percentage : 0.0
 Total NaN values in row 9095 :- 0 and it's percentage : 0.0
 Total NaN values in row 9096 :- 0 and it's percentage : 0.0
 Total NaN values in row 9097 :- 0 and it's percentage : 0.0
 Total NaN values in row 9098 :- 0 and it's percentage : 0.0
 Total NaN values in row 9099 :- 0 and it's percentage : 0.0
 Total NaN values in row 9100 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9101 :- 0 and it's percentage : 0.0
 Total NaN values in row 9102 :- 0 and it's percentage : 0.0
 Total NaN values in row 9103 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9104 :- 0 and it's percentage : 0.0
 Total NaN values in row 9105 :- 0 and it's percentage : 0.0
 Total NaN values in row 9106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9107 :- 0 and it's percentage : 0.0
 Total NaN values in row 9108 :- 0 and it's percentage : 0.0
 Total NaN values in row 9109 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9110 :- 0 and it's percentage : 0.0
 Total NaN values in row 9111 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9112 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9113 :- 0 and it's percentage : 0.0
 Total NaN values in row 9114 :- 0 and it's percentage : 0.0
 Total NaN values in row 9115 :- 0 and it's percentage : 0.0
 Total NaN values in row 9116 :- 0 and it's percentage : 0.0
 Total NaN values in row 9117 :- 0 and it's percentage : 0.0
 Total NaN values in row 9118 :- 0 and it's percentage : 0.0
 Total NaN values in row 9119 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9120 :- 0 and it's percentage : 0.0
 Total NaN values in row 9121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9122 :- 0 and it's percentage : 0.0
 Total NaN values in row 9123 :- 0 and it's percentage : 0.0
 Total NaN values in row 9124 :- 0 and it's percentage : 0.0
 Total NaN values in row 9125 :- 0 and it's percentage : 0.0
 Total NaN values in row 9126 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9127 :- 0 and it's percentage : 0.0
 Total NaN values in row 9128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9129 :- 0 and it's percentage : 0.0
 Total NaN values in row 9130 :- 0 and it's percentage : 0.0
 Total NaN values in row 9131 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9132 :- 0 and it's percentage : 0.0
 Total NaN values in row 9133 :- 0 and it's percentage : 0.0
 Total NaN values in row 9134 :- 0 and it's percentage : 0.0
 Total NaN values in row 9135 :- 0 and it's percentage : 0.0
 Total NaN values in row 9136 :- 0 and it's percentage : 0.0
 Total NaN values in row 9137 :- 0 and it's percentage : 0.0
 Total NaN values in row 9138 :- 0 and it's percentage : 0.0
 Total NaN values in row 9139 :- 0 and it's percentage : 0.0
 Total NaN values in row 9140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9141 :- 0 and it's percentage : 0.0
 Total NaN values in row 9142 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9143 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9144 :- 0 and it's percentage : 0.0
 Total NaN values in row 9145 :- 0 and it's percentage : 0.0
 Total NaN values in row 9146 :- 0 and it's percentage : 0.0
 Total NaN values in row 9147 :- 0 and it's percentage : 0.0
 Total NaN values in row 9148 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9149 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9150 :- 0 and it's percentage : 0.0
 Total NaN values in row 9151 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9152 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9153 :- 0 and it's percentage : 0.0
 Total NaN values in row 9154 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9155 :- 0 and it's percentage : 0.0
 Total NaN values in row 9156 :- 0 and it's percentage : 0.0
 Total NaN values in row 9157 :- 0 and it's percentage : 0.0
 Total NaN values in row 9158 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9159 :- 0 and it's percentage : 0.0
 Total NaN values in row 9160 :- 0 and it's percentage : 0.0
 Total NaN values in row 9161 :- 0 and it's percentage : 0.0
 Total NaN values in row 9162 :- 0 and it's percentage : 0.0
 Total NaN values in row 9163 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9164 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9165 :- 0 and it's percentage : 0.0
 Total NaN values in row 9166 :- 0 and it's percentage : 0.0
 Total NaN values in row 9167 :- 0 and it's percentage : 0.0
 Total NaN values in row 9168 :- 0 and it's percentage : 0.0
 Total NaN values in row 9169 :- 0 and it's percentage : 0.0
 Total NaN values in row 9170 :- 0 and it's percentage : 0.0
 Total NaN values in row 9171 :- 0 and it's percentage : 0.0
 Total NaN values in row 9172 :- 0 and it's percentage : 0.0
 Total NaN values in row 9173 :- 0 and it's percentage : 0.0
 Total NaN values in row 9174 :- 0 and it's percentage : 0.0
 Total NaN values in row 9175 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9176 :- 0 and it's percentage : 0.0
 Total NaN values in row 9177 :- 0 and it's percentage : 0.0
 Total NaN values in row 9178 :- 0 and it's percentage : 0.0
 Total NaN values in row 9179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9180 :- 0 and it's percentage : 0.0
 Total NaN values in row 9181 :- 0 and it's percentage : 0.0
 Total NaN values in row 9182 :- 0 and it's percentage : 0.0
 Total NaN values in row 9183 :- 0 and it's percentage : 0.0
 Total NaN values in row 9184 :- 0 and it's percentage : 0.0
 Total NaN values in row 9185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9187 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9189 :- 0 and it's percentage : 0.0
 Total NaN values in row 9190 :- 0 and it's percentage : 0.0
 Total NaN values in row 9191 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9192 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9193 :- 0 and it's percentage : 0.0
 Total NaN values in row 9194 :- 0 and it's percentage : 0.0
 Total NaN values in row 9195 :- 0 and it's percentage : 0.0
 Total NaN values in row 9196 :- 0 and it's percentage : 0.0
 Total NaN values in row 9197 :- 0 and it's percentage : 0.0
 Total NaN values in row 9198 :- 0 and it's percentage : 0.0
 Total NaN values in row 9199 :- 0 and it's percentage : 0.0
 Total NaN values in row 9200 :- 0 and it's percentage : 0.0
 Total NaN values in row 9201 :- 0 and it's percentage : 0.0
 Total NaN values in row 9202 :- 0 and it's percentage : 0.0
 Total NaN values in row 9203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9205 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9206 :- 0 and it's percentage : 0.0
 Total NaN values in row 9207 :- 0 and it's percentage : 0.0
 Total NaN values in row 9208 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9209 :- 0 and it's percentage : 0.0
 Total NaN values in row 9210 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9211 :- 0 and it's percentage : 0.0
 Total NaN values in row 9212 :- 0 and it's percentage : 0.0
 Total NaN values in row 9213 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9214 :- 0 and it's percentage : 0.0
 Total NaN values in row 9215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9216 :- 0 and it's percentage : 0.0
 Total NaN values in row 9217 :- 0 and it's percentage : 0.0
 Total NaN values in row 9218 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9219 :- 0 and it's percentage : 0.0
 Total NaN values in row 9220 :- 0 and it's percentage : 0.0
 Total NaN values in row 9221 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9222 :- 0 and it's percentage : 0.0
 Total NaN values in row 9223 :- 0 and it's percentage : 0.0
 Total NaN values in row 9224 :- 0 and it's percentage : 0.0
 Total NaN values in row 9225 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9226 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9227 :- 0 and it's percentage : 0.0
 Total NaN values in row 9228 :- 0 and it's percentage : 0.0
 Total NaN values in row 9229 :- 0 and it's percentage : 0.0
 Total NaN values in row 9230 :- 0 and it's percentage : 0.0
 Total NaN values in row 9231 :- 0 and it's percentage : 0.0
 Total NaN values in row 9232 :- 0 and it's percentage : 0.0
 Total NaN values in row 9233 :- 0 and it's percentage : 0.0
 Total NaN values in row 9234 :- 0 and it's percentage : 0.0
 Total NaN values in row 9235 :- 0 and it's percentage : 0.0

 Total NaN values in row 9236 :- 0 and it's percentage : 0.0
 Total NaN values in row 9237 :- 0 and it's percentage : 0.0
 Total NaN values in row 9238 :- 0 and it's percentage : 0.0
 Total NaN values in row 9239 :- 0 and it's percentage : 0.0
 Total NaN values in row 9240 :- 0 and it's percentage : 0.0
 Total NaN values in row 9241 :- 0 and it's percentage : 0.0
 Total NaN values in row 9242 :- 0 and it's percentage : 0.0
 Total NaN values in row 9243 :- 0 and it's percentage : 0.0
 Total NaN values in row 9244 :- 0 and it's percentage : 0.0
 Total NaN values in row 9245 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9246 :- 0 and it's percentage : 0.0
 Total NaN values in row 9247 :- 0 and it's percentage : 0.0
 Total NaN values in row 9248 :- 0 and it's percentage : 0.0
 Total NaN values in row 9249 :- 0 and it's percentage : 0.0
 Total NaN values in row 9250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9251 :- 0 and it's percentage : 0.0
 Total NaN values in row 9252 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9253 :- 0 and it's percentage : 0.0
 Total NaN values in row 9254 :- 0 and it's percentage : 0.0
 Total NaN values in row 9255 :- 0 and it's percentage : 0.0
 Total NaN values in row 9256 :- 0 and it's percentage : 0.0
 Total NaN values in row 9257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9258 :- 0 and it's percentage : 0.0
 Total NaN values in row 9259 :- 0 and it's percentage : 0.0
 Total NaN values in row 9260 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9261 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9262 :- 0 and it's percentage : 0.0
 Total NaN values in row 9263 :- 0 and it's percentage : 0.0
 Total NaN values in row 9264 :- 0 and it's percentage : 0.0
 Total NaN values in row 9265 :- 0 and it's percentage : 0.0
 Total NaN values in row 9266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9267 :- 0 and it's percentage : 0.0
 Total NaN values in row 9268 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9269 :- 0 and it's percentage : 0.0
 Total NaN values in row 9270 :- 0 and it's percentage : 0.0
 Total NaN values in row 9271 :- 0 and it's percentage : 0.0
 Total NaN values in row 9272 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9273 :- 0 and it's percentage : 0.0
 Total NaN values in row 9274 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9275 :- 0 and it's percentage : 0.0
 Total NaN values in row 9276 :- 0 and it's percentage : 0.0
 Total NaN values in row 9277 :- 0 and it's percentage : 0.0
 Total NaN values in row 9278 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9279 :- 0 and it's percentage : 0.0
 Total NaN values in row 9280 :- 0 and it's percentage : 0.0
 Total NaN values in row 9281 :- 0 and it's percentage : 0.0
 Total NaN values in row 9282 :- 0 and it's percentage : 0.0
 Total NaN values in row 9283 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9284 :- 0 and it's percentage : 0.0
 Total NaN values in row 9285 :- 0 and it's percentage : 0.0
 Total NaN values in row 9286 :- 0 and it's percentage : 0.0
 Total NaN values in row 9287 :- 0 and it's percentage : 0.0
 Total NaN values in row 9288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9289 :- 0 and it's percentage : 0.0
 Total NaN values in row 9290 :- 0 and it's percentage : 0.0
 Total NaN values in row 9291 :- 0 and it's percentage : 0.0
 Total NaN values in row 9292 :- 0 and it's percentage : 0.0
 Total NaN values in row 9293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9294 :- 0 and it's percentage : 0.0
 Total NaN values in row 9295 :- 0 and it's percentage : 0.0
 Total NaN values in row 9296 :- 0 and it's percentage : 0.0
 Total NaN values in row 9297 :- 0 and it's percentage : 0.0
 Total NaN values in row 9298 :- 0 and it's percentage : 0.0
 Total NaN values in row 9299 :- 0 and it's percentage : 0.0
 Total NaN values in row 9300 :- 0 and it's percentage : 0.0
 Total NaN values in row 9301 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9302 :- 0 and it's percentage : 0.0
 Total NaN values in row 9303 :- 0 and it's percentage : 0.0
 Total NaN values in row 9304 :- 0 and it's percentage : 0.0
 Total NaN values in row 9305 :- 0 and it's percentage : 0.0
 Total NaN values in row 9306 :- 0 and it's percentage : 0.0
 Total NaN values in row 9307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9308 :- 0 and it's percentage : 0.0
 Total NaN values in row 9309 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9310 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9311 :- 0 and it's percentage : 0.0
 Total NaN values in row 9312 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9313 :- 0 and it's percentage : 0.0
 Total NaN values in row 9314 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9315 :- 0 and it's percentage : 0.0
 Total NaN values in row 9316 :- 0 and it's percentage : 0.0
 Total NaN values in row 9317 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9318 :- 0 and it's percentage : 0.0
 Total NaN values in row 9319 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9320 :- 0 and it's percentage : 0.0
 Total NaN values in row 9321 :- 0 and it's percentage : 0.0
 Total NaN values in row 9322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9323 :- 0 and it's percentage : 0.0
 Total NaN values in row 9324 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9325 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9326 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9327 :- 0 and it's percentage : 0.0
 Total NaN values in row 9328 :- 0 and it's percentage : 0.0
 Total NaN values in row 9329 :- 0 and it's percentage : 0.0
 Total NaN values in row 9330 :- 0 and it's percentage : 0.0
 Total NaN values in row 9331 :- 0 and it's percentage : 0.0
 Total NaN values in row 9332 :- 0 and it's percentage : 0.0
 Total NaN values in row 9333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9334 :- 0 and it's percentage : 0.0
 Total NaN values in row 9335 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9336 :- 0 and it's percentage : 0.0
 Total NaN values in row 9337 :- 0 and it's percentage : 0.0
 Total NaN values in row 9338 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9339 :- 0 and it's percentage : 0.0
 Total NaN values in row 9340 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9341 :- 0 and it's percentage : 0.0
 Total NaN values in row 9342 :- 0 and it's percentage : 0.0
 Total NaN values in row 9343 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9344 :- 0 and it's percentage : 0.0
 Total NaN values in row 9345 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9346 :- 0 and it's percentage : 0.0
 Total NaN values in row 9347 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9349 :- 0 and it's percentage : 0.0
 Total NaN values in row 9350 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9352 :- 0 and it's percentage : 0.0
 Total NaN values in row 9353 :- 0 and it's percentage : 0.0
 Total NaN values in row 9354 :- 0 and it's percentage : 0.0
 Total NaN values in row 9355 :- 0 and it's percentage : 0.0
 Total NaN values in row 9356 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9357 :- 0 and it's percentage : 0.0
 Total NaN values in row 9358 :- 0 and it's percentage : 0.0
 Total NaN values in row 9359 :- 0 and it's percentage : 0.0
 Total NaN values in row 9360 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9361 :- 0 and it's percentage : 0.0
 Total NaN values in row 9362 :- 0 and it's percentage : 0.0
 Total NaN values in row 9363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9364 :- 0 and it's percentage : 0.0
 Total NaN values in row 9365 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9367 :- 0 and it's percentage : 0.0
 Total NaN values in row 9368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9369 :- 0 and it's percentage : 0.0
 Total NaN values in row 9370 :- 0 and it's percentage : 0.0
 Total NaN values in row 9371 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9372 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9373 :- 0 and it's percentage : 0.0
 Total NaN values in row 9374 :- 0 and it's percentage : 0.0
 Total NaN values in row 9375 :- 0 and it's percentage : 0.0
 Total NaN values in row 9376 :- 0 and it's percentage : 0.0
 Total NaN values in row 9377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9378 :- 0 and it's percentage : 0.0
 Total NaN values in row 9379 :- 0 and it's percentage : 0.0
 Total NaN values in row 9380 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9381 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9382 :- 0 and it's percentage : 0.0
 Total NaN values in row 9383 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9384 :- 0 and it's percentage : 0.0
 Total NaN values in row 9385 :- 0 and it's percentage : 0.0
 Total NaN values in row 9386 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9387 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 9388 :- 0 and it's percentage : 0.0
 Total NaN values in row 9389 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9390 :- 0 and it's percentage : 0.0
 Total NaN values in row 9391 :- 0 and it's percentage : 0.0
 Total NaN values in row 9392 :- 0 and it's percentage : 0.0
 Total NaN values in row 9393 :- 0 and it's percentage : 0.0
 Total NaN values in row 9394 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9395 :- 0 and it's percentage : 0.0
 Total NaN values in row 9396 :- 0 and it's percentage : 0.0
 Total NaN values in row 9397 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9398 :- 0 and it's percentage : 0.0
 Total NaN values in row 9399 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9400 :- 0 and it's percentage : 0.0
 Total NaN values in row 9401 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9402 :- 0 and it's percentage : 0.0
 Total NaN values in row 9403 :- 0 and it's percentage : 0.0
 Total NaN values in row 9404 :- 0 and it's percentage : 0.0
 Total NaN values in row 9405 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9406 :- 0 and it's percentage : 0.0
 Total NaN values in row 9407 :- 0 and it's percentage : 0.0
 Total NaN values in row 9408 :- 0 and it's percentage : 0.0
 Total NaN values in row 9409 :- 0 and it's percentage : 0.0
 Total NaN values in row 9410 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9411 :- 0 and it's percentage : 0.0
 Total NaN values in row 9412 :- 0 and it's percentage : 0.0
 Total NaN values in row 9413 :- 0 and it's percentage : 0.0
 Total NaN values in row 9414 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9415 :- 0 and it's percentage : 0.0
 Total NaN values in row 9416 :- 0 and it's percentage : 0.0
 Total NaN values in row 9417 :- 0 and it's percentage : 0.0
 Total NaN values in row 9418 :- 0 and it's percentage : 0.0
 Total NaN values in row 9419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9420 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9421 :- 0 and it's percentage : 0.0
 Total NaN values in row 9422 :- 0 and it's percentage : 0.0
 Total NaN values in row 9423 :- 0 and it's percentage : 0.0
 Total NaN values in row 9424 :- 0 and it's percentage : 0.0
 Total NaN values in row 9425 :- 0 and it's percentage : 0.0
 Total NaN values in row 9426 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9427 :- 0 and it's percentage : 0.0
 Total NaN values in row 9428 :- 0 and it's percentage : 0.0
 Total NaN values in row 9429 :- 0 and it's percentage : 0.0
 Total NaN values in row 9430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9432 :- 0 and it's percentage : 0.0
 Total NaN values in row 9433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9434 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9435 :- 0 and it's percentage : 0.0
 Total NaN values in row 9436 :- 0 and it's percentage : 0.0
 Total NaN values in row 9437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9438 :- 0 and it's percentage : 0.0
 Total NaN values in row 9439 :- 0 and it's percentage : 0.0
 Total NaN values in row 9440 :- 0 and it's percentage : 0.0
 Total NaN values in row 9441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9442 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9443 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9444 :- 0 and it's percentage : 0.0
 Total NaN values in row 9445 :- 0 and it's percentage : 0.0
 Total NaN values in row 9446 :- 0 and it's percentage : 0.0
 Total NaN values in row 9447 :- 0 and it's percentage : 0.0
 Total NaN values in row 9448 :- 0 and it's percentage : 0.0
 Total NaN values in row 9449 :- 0 and it's percentage : 0.0
 Total NaN values in row 9450 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9451 :- 0 and it's percentage : 0.0
 Total NaN values in row 9452 :- 0 and it's percentage : 0.0
 Total NaN values in row 9453 :- 0 and it's percentage : 0.0
 Total NaN values in row 9454 :- 0 and it's percentage : 0.0
 Total NaN values in row 9455 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9456 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9457 :- 0 and it's percentage : 0.0
 Total NaN values in row 9458 :- 0 and it's percentage : 0.0
 Total NaN values in row 9459 :- 0 and it's percentage : 0.0
 Total NaN values in row 9460 :- 0 and it's percentage : 0.0
 Total NaN values in row 9461 :- 0 and it's percentage : 0.0
 Total NaN values in row 9462 :- 0 and it's percentage : 0.0
 Total NaN values in row 9463 :- 0 and it's percentage : 0.0
 Total NaN values in row 9464 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9465 :- 0 and it's percentage : 0.0
 Total NaN values in row 9466 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9467 :- 0 and it's percentage : 0.0
 Total NaN values in row 9468 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9469 :- 0 and it's percentage : 0.0
 Total NaN values in row 9470 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9474 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9475 :- 0 and it's percentage : 0.0
 Total NaN values in row 9476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9477 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9478 :- 0 and it's percentage : 0.0
 Total NaN values in row 9479 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9480 :- 0 and it's percentage : 0.0
 Total NaN values in row 9481 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9482 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9483 :- 0 and it's percentage : 0.0
 Total NaN values in row 9484 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9485 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9486 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9487 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9488 :- 0 and it's percentage : 0.0
 Total NaN values in row 9489 :- 0 and it's percentage : 0.0
 Total NaN values in row 9490 :- 0 and it's percentage : 0.0
 Total NaN values in row 9491 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9492 :- 0 and it's percentage : 0.0
 Total NaN values in row 9493 :- 0 and it's percentage : 0.0
 Total NaN values in row 9494 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9495 :- 0 and it's percentage : 0.0
 Total NaN values in row 9496 :- 0 and it's percentage : 0.0
 Total NaN values in row 9497 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9498 :- 0 and it's percentage : 0.0
 Total NaN values in row 9499 :- 0 and it's percentage : 0.0
 Total NaN values in row 9500 :- 0 and it's percentage : 0.0
 Total NaN values in row 9501 :- 0 and it's percentage : 0.0
 Total NaN values in row 9502 :- 0 and it's percentage : 0.0
 Total NaN values in row 9503 :- 0 and it's percentage : 0.0
 Total NaN values in row 9504 :- 0 and it's percentage : 0.0
 Total NaN values in row 9505 :- 0 and it's percentage : 0.0
 Total NaN values in row 9506 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9507 :- 0 and it's percentage : 0.0
 Total NaN values in row 9508 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9509 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9511 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9512 :- 0 and it's percentage : 0.0

 Total NaN values in row 9513 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9514 :- 0 and it's percentage : 0.0
 Total NaN values in row 9515 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9516 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9517 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9518 :- 0 and it's percentage : 0.0
 Total NaN values in row 9519 :- 0 and it's percentage : 0.0
 Total NaN values in row 9520 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9521 :- 0 and it's percentage : 0.0
 Total NaN values in row 9522 :- 0 and it's percentage : 0.0
 Total NaN values in row 9523 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9524 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9525 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9526 :- 0 and it's percentage : 0.0
 Total NaN values in row 9527 :- 0 and it's percentage : 0.0
 Total NaN values in row 9528 :- 0 and it's percentage : 0.0
 Total NaN values in row 9529 :- 0 and it's percentage : 0.0
 Total NaN values in row 9530 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9531 :- 0 and it's percentage : 0.0
 Total NaN values in row 9532 :- 0 and it's percentage : 0.0
 Total NaN values in row 9533 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9534 :- 0 and it's percentage : 0.0
 Total NaN values in row 9535 :- 0 and it's percentage : 0.0
 Total NaN values in row 9536 :- 0 and it's percentage : 0.0
 Total NaN values in row 9537 :- 0 and it's percentage : 0.0
 Total NaN values in row 9538 :- 0 and it's percentage : 0.0
 Total NaN values in row 9539 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9540 :- 0 and it's percentage : 0.0
 Total NaN values in row 9541 :- 0 and it's percentage : 0.0
 Total NaN values in row 9542 :- 0 and it's percentage : 0.0
 Total NaN values in row 9543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9544 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9545 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9546 :- 0 and it's percentage : 0.0
 Total NaN values in row 9547 :- 0 and it's percentage : 0.0
 Total NaN values in row 9548 :- 0 and it's percentage : 0.0
 Total NaN values in row 9549 :- 0 and it's percentage : 0.0
 Total NaN values in row 9550 :- 0 and it's percentage : 0.0
 Total NaN values in row 9551 :- 0 and it's percentage : 0.0
 Total NaN values in row 9552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9553 :- 0 and it's percentage : 0.0
 Total NaN values in row 9554 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9555 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9556 :- 0 and it's percentage : 0.0
 Total NaN values in row 9557 :- 0 and it's percentage : 0.0
 Total NaN values in row 9558 :- 0 and it's percentage : 0.0
 Total NaN values in row 9559 :- 0 and it's percentage : 0.0
 Total NaN values in row 9560 :- 0 and it's percentage : 0.0
 Total NaN values in row 9561 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9562 :- 0 and it's percentage : 0.0
 Total NaN values in row 9563 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9564 :- 0 and it's percentage : 0.0
 Total NaN values in row 9565 :- 0 and it's percentage : 0.0
 Total NaN values in row 9566 :- 0 and it's percentage : 0.0
 Total NaN values in row 9567 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9568 :- 0 and it's percentage : 0.0
 Total NaN values in row 9569 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9570 :- 0 and it's percentage : 0.0
 Total NaN values in row 9571 :- 0 and it's percentage : 0.0
 Total NaN values in row 9572 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9573 :- 0 and it's percentage : 0.0
 Total NaN values in row 9574 :- 0 and it's percentage : 0.0
 Total NaN values in row 9575 :- 0 and it's percentage : 0.0
 Total NaN values in row 9576 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9577 :- 0 and it's percentage : 0.0
 Total NaN values in row 9578 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9579 :- 0 and it's percentage : 0.0
 Total NaN values in row 9580 :- 0 and it's percentage : 0.0
 Total NaN values in row 9581 :- 0 and it's percentage : 0.0
 Total NaN values in row 9582 :- 0 and it's percentage : 0.0
 Total NaN values in row 9583 :- 0 and it's percentage : 0.0
 Total NaN values in row 9584 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9585 :- 0 and it's percentage : 0.0
 Total NaN values in row 9586 :- 0 and it's percentage : 0.0
 Total NaN values in row 9587 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9588 :- 0 and it's percentage : 0.0
 Total NaN values in row 9589 :- 0 and it's percentage : 0.0
 Total NaN values in row 9590 :- 0 and it's percentage : 0.0
 Total NaN values in row 9591 :- 0 and it's percentage : 0.0
 Total NaN values in row 9592 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9593 :- 0 and it's percentage : 0.0
 Total NaN values in row 9594 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9595 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9596 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9597 :- 0 and it's percentage : 0.0
 Total NaN values in row 9598 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9599 :- 0 and it's percentage : 0.0
 Total NaN values in row 9600 :- 0 and it's percentage : 0.0
 Total NaN values in row 9601 :- 0 and it's percentage : 0.0
 Total NaN values in row 9602 :- 0 and it's percentage : 0.0
 Total NaN values in row 9603 :- 0 and it's percentage : 0.0
 Total NaN values in row 9604 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9605 :- 0 and it's percentage : 0.0
 Total NaN values in row 9606 :- 0 and it's percentage : 0.0
 Total NaN values in row 9607 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9608 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9609 :- 0 and it's percentage : 0.0
 Total NaN values in row 9610 :- 0 and it's percentage : 0.0
 Total NaN values in row 9611 :- 0 and it's percentage : 0.0
 Total NaN values in row 9612 :- 0 and it's percentage : 0.0
 Total NaN values in row 9613 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9614 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9615 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9616 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9617 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9618 :- 0 and it's percentage : 0.0
 Total NaN values in row 9619 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9621 :- 0 and it's percentage : 0.0
 Total NaN values in row 9622 :- 0 and it's percentage : 0.0
 Total NaN values in row 9623 :- 0 and it's percentage : 0.0
 Total NaN values in row 9624 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9625 :- 0 and it's percentage : 0.0
 Total NaN values in row 9626 :- 0 and it's percentage : 0.0
 Total NaN values in row 9627 :- 0 and it's percentage : 0.0
 Total NaN values in row 9628 :- 0 and it's percentage : 0.0
 Total NaN values in row 9629 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9630 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9631 :- 0 and it's percentage : 0.0
 Total NaN values in row 9632 :- 0 and it's percentage : 0.0
 Total NaN values in row 9633 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9634 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9635 :- 0 and it's percentage : 0.0
 Total NaN values in row 9636 :- 0 and it's percentage : 0.0
 Total NaN values in row 9637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9638 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 9639 :- 0 and it's percentage : 0.0
 Total NaN values in row 9640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9641 :- 0 and it's percentage : 0.0
 Total NaN values in row 9642 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9643 :- 0 and it's percentage : 0.0
 Total NaN values in row 9644 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9645 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9646 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 9647 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9648 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9649 :- 0 and it's percentage : 0.0
 Total NaN values in row 9650 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9651 :- 0 and it's percentage : 0.0
 Total NaN values in row 9652 :- 0 and it's percentage : 0.0
 Total NaN values in row 9653 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9654 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9655 :- 0 and it's percentage : 0.0
 Total NaN values in row 9656 :- 0 and it's percentage : 0.0
 Total NaN values in row 9657 :- 0 and it's percentage : 0.0
 Total NaN values in row 9658 :- 0 and it's percentage : 0.0
 Total NaN values in row 9659 :- 0 and it's percentage : 0.0
 Total NaN values in row 9660 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9661 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9662 :- 0 and it's percentage : 0.0
 Total NaN values in row 9663 :- 0 and it's percentage : 0.0
 Total NaN values in row 9664 :- 0 and it's percentage : 0.0
 Total NaN values in row 9665 :- 0 and it's percentage : 0.0
 Total NaN values in row 9666 :- 0 and it's percentage : 0.0
 Total NaN values in row 9667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9668 :- 0 and it's percentage : 0.0
 Total NaN values in row 9669 :- 0 and it's percentage : 0.0
 Total NaN values in row 9670 :- 0 and it's percentage : 0.0
 Total NaN values in row 9671 :- 0 and it's percentage : 0.0
 Total NaN values in row 9672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9673 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9674 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9675 :- 0 and it's percentage : 0.0
 Total NaN values in row 9676 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9677 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9679 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9681 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9682 :- 0 and it's percentage : 0.0
 Total NaN values in row 9683 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9684 :- 0 and it's percentage : 0.0
 Total NaN values in row 9685 :- 0 and it's percentage : 0.0
 Total NaN values in row 9686 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9687 :- 0 and it's percentage : 0.0
 Total NaN values in row 9688 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9689 :- 0 and it's percentage : 0.0
 Total NaN values in row 9690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9691 :- 0 and it's percentage : 0.0
 Total NaN values in row 9692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9693 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9694 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9695 :- 0 and it's percentage : 0.0
 Total NaN values in row 9696 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9697 :- 0 and it's percentage : 0.0
 Total NaN values in row 9698 :- 0 and it's percentage : 0.0
 Total NaN values in row 9699 :- 0 and it's percentage : 0.0
 Total NaN values in row 9700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9701 :- 0 and it's percentage : 0.0
 Total NaN values in row 9702 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9703 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9705 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9706 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9707 :- 0 and it's percentage : 0.0
 Total NaN values in row 9708 :- 0 and it's percentage : 0.0
 Total NaN values in row 9709 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9710 :- 0 and it's percentage : 0.0
 Total NaN values in row 9711 :- 0 and it's percentage : 0.0
 Total NaN values in row 9712 :- 0 and it's percentage : 0.0
 Total NaN values in row 9713 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9714 :- 0 and it's percentage : 0.0
 Total NaN values in row 9715 :- 0 and it's percentage : 0.0
 Total NaN values in row 9716 :- 0 and it's percentage : 0.0
 Total NaN values in row 9717 :- 0 and it's percentage : 0.0
 Total NaN values in row 9718 :- 0 and it's percentage : 0.0
 Total NaN values in row 9719 :- 0 and it's percentage : 0.0
 Total NaN values in row 9720 :- 0 and it's percentage : 0.0
 Total NaN values in row 9721 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9722 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9723 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9724 :- 0 and it's percentage : 0.0
 Total NaN values in row 9725 :- 0 and it's percentage : 0.0
 Total NaN values in row 9726 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9727 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9728 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9729 :- 0 and it's percentage : 0.0
 Total NaN values in row 9730 :- 0 and it's percentage : 0.0
 Total NaN values in row 9731 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9732 :- 0 and it's percentage : 0.0
 Total NaN values in row 9733 :- 0 and it's percentage : 0.0
 Total NaN values in row 9734 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9735 :- 0 and it's percentage : 0.0
 Total NaN values in row 9736 :- 0 and it's percentage : 0.0
 Total NaN values in row 9737 :- 0 and it's percentage : 0.0
 Total NaN values in row 9738 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9739 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9740 :- 0 and it's percentage : 0.0
 Total NaN values in row 9741 :- 0 and it's percentage : 0.0
 Total NaN values in row 9742 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9743 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9744 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9745 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9746 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9747 :- 0 and it's percentage : 0.0
 Total NaN values in row 9748 :- 0 and it's percentage : 0.0
 Total NaN values in row 9749 :- 0 and it's percentage : 0.0
 Total NaN values in row 9750 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9751 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9752 :- 0 and it's percentage : 0.0
 Total NaN values in row 9753 :- 0 and it's percentage : 0.0
 Total NaN values in row 9754 :- 0 and it's percentage : 0.0
 Total NaN values in row 9755 :- 0 and it's percentage : 0.0
 Total NaN values in row 9756 :- 0 and it's percentage : 0.0
 Total NaN values in row 9757 :- 0 and it's percentage : 0.0
 Total NaN values in row 9758 :- 0 and it's percentage : 0.0
 Total NaN values in row 9759 :- 0 and it's percentage : 0.0
 Total NaN values in row 9760 :- 0 and it's percentage : 0.0
 Total NaN values in row 9761 :- 0 and it's percentage : 0.0
 Total NaN values in row 9762 :- 0 and it's percentage : 0.0
 Total NaN values in row 9763 :- 0 and it's percentage : 0.0
 Total NaN values in row 9764 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9765 :- 0 and it's percentage : 0.0
 Total NaN values in row 9766 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9767 :- 0 and it's percentage : 0.0
 Total NaN values in row 9768 :- 0 and it's percentage : 0.0

 Total NaN values in row 9769 :- 0 and it's percentage : 0.0
 Total NaN values in row 9770 :- 0 and it's percentage : 0.0
 Total NaN values in row 9771 :- 0 and it's percentage : 0.0
 Total NaN values in row 9772 :- 0 and it's percentage : 0.0
 Total NaN values in row 9773 :- 0 and it's percentage : 0.0
 Total NaN values in row 9774 :- 0 and it's percentage : 0.0
 Total NaN values in row 9775 :- 0 and it's percentage : 0.0
 Total NaN values in row 9776 :- 0 and it's percentage : 0.0
 Total NaN values in row 9777 :- 0 and it's percentage : 0.0
 Total NaN values in row 9778 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9779 :- 0 and it's percentage : 0.0
 Total NaN values in row 9780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9781 :- 0 and it's percentage : 0.0
 Total NaN values in row 9782 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9783 :- 0 and it's percentage : 0.0
 Total NaN values in row 9784 :- 0 and it's percentage : 0.0
 Total NaN values in row 9785 :- 0 and it's percentage : 0.0
 Total NaN values in row 9786 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9787 :- 0 and it's percentage : 0.0
 Total NaN values in row 9788 :- 0 and it's percentage : 0.0
 Total NaN values in row 9789 :- 0 and it's percentage : 0.0
 Total NaN values in row 9790 :- 0 and it's percentage : 0.0
 Total NaN values in row 9791 :- 0 and it's percentage : 0.0
 Total NaN values in row 9792 :- 0 and it's percentage : 0.0
 Total NaN values in row 9793 :- 0 and it's percentage : 0.0
 Total NaN values in row 9794 :- 0 and it's percentage : 0.0
 Total NaN values in row 9795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9796 :- 0 and it's percentage : 0.0
 Total NaN values in row 9797 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9798 :- 0 and it's percentage : 0.0
 Total NaN values in row 9799 :- 0 and it's percentage : 0.0
 Total NaN values in row 9800 :- 0 and it's percentage : 0.0
 Total NaN values in row 9801 :- 0 and it's percentage : 0.0
 Total NaN values in row 9802 :- 0 and it's percentage : 0.0
 Total NaN values in row 9803 :- 0 and it's percentage : 0.0
 Total NaN values in row 9804 :- 0 and it's percentage : 0.0
 Total NaN values in row 9805 :- 0 and it's percentage : 0.0
 Total NaN values in row 9806 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9807 :- 0 and it's percentage : 0.0
 Total NaN values in row 9808 :- 0 and it's percentage : 0.0
 Total NaN values in row 9809 :- 0 and it's percentage : 0.0
 Total NaN values in row 9810 :- 0 and it's percentage : 0.0
 Total NaN values in row 9811 :- 0 and it's percentage : 0.0
 Total NaN values in row 9812 :- 0 and it's percentage : 0.0
 Total NaN values in row 9813 :- 0 and it's percentage : 0.0
 Total NaN values in row 9814 :- 0 and it's percentage : 0.0
 Total NaN values in row 9815 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9816 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 9817 :- 0 and it's percentage : 0.0
 Total NaN values in row 9818 :- 0 and it's percentage : 0.0
 Total NaN values in row 9819 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9820 :- 0 and it's percentage : 0.0
 Total NaN values in row 9821 :- 0 and it's percentage : 0.0
 Total NaN values in row 9822 :- 0 and it's percentage : 0.0
 Total NaN values in row 9823 :- 0 and it's percentage : 0.0
 Total NaN values in row 9824 :- 0 and it's percentage : 0.0
 Total NaN values in row 9825 :- 0 and it's percentage : 0.0
 Total NaN values in row 9826 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9827 :- 0 and it's percentage : 0.0
 Total NaN values in row 9828 :- 0 and it's percentage : 0.0
 Total NaN values in row 9829 :- 0 and it's percentage : 0.0
 Total NaN values in row 9830 :- 0 and it's percentage : 0.0
 Total NaN values in row 9831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9832 :- 0 and it's percentage : 0.0
 Total NaN values in row 9833 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9834 :- 0 and it's percentage : 0.0
 Total NaN values in row 9835 :- 0 and it's percentage : 0.0
 Total NaN values in row 9836 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9837 :- 0 and it's percentage : 0.0
 Total NaN values in row 9838 :- 0 and it's percentage : 0.0
 Total NaN values in row 9839 :- 0 and it's percentage : 0.0
 Total NaN values in row 9840 :- 0 and it's percentage : 0.0
 Total NaN values in row 9841 :- 0 and it's percentage : 0.0
 Total NaN values in row 9842 :- 0 and it's percentage : 0.0
 Total NaN values in row 9843 :- 0 and it's percentage : 0.0
 Total NaN values in row 9844 :- 0 and it's percentage : 0.0
 Total NaN values in row 9845 :- 0 and it's percentage : 0.0
 Total NaN values in row 9846 :- 0 and it's percentage : 0.0
 Total NaN values in row 9847 :- 0 and it's percentage : 0.0
 Total NaN values in row 9848 :- 0 and it's percentage : 0.0
 Total NaN values in row 9849 :- 0 and it's percentage : 0.0
 Total NaN values in row 9850 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9851 :- 0 and it's percentage : 0.0
 Total NaN values in row 9852 :- 0 and it's percentage : 0.0
 Total NaN values in row 9853 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9854 :- 0 and it's percentage : 0.0
 Total NaN values in row 9855 :- 0 and it's percentage : 0.0
 Total NaN values in row 9856 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9857 :- 0 and it's percentage : 0.0
 Total NaN values in row 9858 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9859 :- 0 and it's percentage : 0.0
 Total NaN values in row 9860 :- 0 and it's percentage : 0.0
 Total NaN values in row 9861 :- 0 and it's percentage : 0.0
 Total NaN values in row 9862 :- 0 and it's percentage : 0.0
 Total NaN values in row 9863 :- 0 and it's percentage : 0.0
 Total NaN values in row 9864 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9865 :- 0 and it's percentage : 0.0
 Total NaN values in row 9866 :- 0 and it's percentage : 0.0
 Total NaN values in row 9867 :- 0 and it's percentage : 0.0
 Total NaN values in row 9868 :- 0 and it's percentage : 0.0
 Total NaN values in row 9869 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9870 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9871 :- 0 and it's percentage : 0.0
 Total NaN values in row 9872 :- 0 and it's percentage : 0.0
 Total NaN values in row 9873 :- 0 and it's percentage : 0.0
 Total NaN values in row 9874 :- 0 and it's percentage : 0.0
 Total NaN values in row 9875 :- 0 and it's percentage : 0.0
 Total NaN values in row 9876 :- 0 and it's percentage : 0.0
 Total NaN values in row 9877 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9878 :- 0 and it's percentage : 0.0
 Total NaN values in row 9879 :- 0 and it's percentage : 0.0
 Total NaN values in row 9880 :- 0 and it's percentage : 0.0
 Total NaN values in row 9881 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9882 :- 0 and it's percentage : 0.0
 Total NaN values in row 9883 :- 0 and it's percentage : 0.0
 Total NaN values in row 9884 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9885 :- 0 and it's percentage : 0.0
 Total NaN values in row 9886 :- 0 and it's percentage : 0.0
 Total NaN values in row 9887 :- 0 and it's percentage : 0.0
 Total NaN values in row 9888 :- 0 and it's percentage : 0.0
 Total NaN values in row 9889 :- 0 and it's percentage : 0.0
 Total NaN values in row 9890 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9891 :- 0 and it's percentage : 0.0
 Total NaN values in row 9892 :- 0 and it's percentage : 0.0
 Total NaN values in row 9893 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9894 :- 0 and it's percentage : 0.0
 Total NaN values in row 9895 :- 0 and it's percentage : 0.0
 Total NaN values in row 9896 :- 0 and it's percentage : 0.0
 Total NaN values in row 9897 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 9898 :- 0 and it's percentage : 0.0
 Total NaN values in row 9899 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9900 :- 0 and it's percentage : 0.0
 Total NaN values in row 9901 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9902 :- 0 and it's percentage : 0.0
 Total NaN values in row 9903 :- 0 and it's percentage : 0.0
 Total NaN values in row 9904 :- 0 and it's percentage : 0.0
 Total NaN values in row 9905 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9906 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9907 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9908 :- 0 and it's percentage : 0.0
 Total NaN values in row 9909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9910 :- 0 and it's percentage : 0.0
 Total NaN values in row 9911 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9912 :- 0 and it's percentage : 0.0
 Total NaN values in row 9913 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9914 :- 0 and it's percentage : 0.0
 Total NaN values in row 9915 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9916 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9917 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9918 :- 0 and it's percentage : 0.0
 Total NaN values in row 9919 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9920 :- 0 and it's percentage : 0.0
 Total NaN values in row 9921 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9922 :- 0 and it's percentage : 0.0
 Total NaN values in row 9923 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9924 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9925 :- 0 and it's percentage : 0.0
 Total NaN values in row 9926 :- 0 and it's percentage : 0.0
 Total NaN values in row 9927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9928 :- 0 and it's percentage : 0.0
 Total NaN values in row 9929 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9930 :- 0 and it's percentage : 0.0
 Total NaN values in row 9931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9932 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9933 :- 0 and it's percentage : 0.0
 Total NaN values in row 9934 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9935 :- 0 and it's percentage : 0.0
 Total NaN values in row 9936 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9937 :- 0 and it's percentage : 0.0
 Total NaN values in row 9938 :- 0 and it's percentage : 0.0
 Total NaN values in row 9939 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9940 :- 0 and it's percentage : 0.0
 Total NaN values in row 9941 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9942 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9943 :- 0 and it's percentage : 0.0
 Total NaN values in row 9944 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9945 :- 0 and it's percentage : 0.0
 Total NaN values in row 9946 :- 0 and it's percentage : 0.0
 Total NaN values in row 9947 :- 0 and it's percentage : 0.0
 Total NaN values in row 9948 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9949 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9950 :- 0 and it's percentage : 0.0
 Total NaN values in row 9951 :- 0 and it's percentage : 0.0
 Total NaN values in row 9952 :- 0 and it's percentage : 0.0
 Total NaN values in row 9953 :- 0 and it's percentage : 0.0
 Total NaN values in row 9954 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9955 :- 0 and it's percentage : 0.0
 Total NaN values in row 9956 :- 0 and it's percentage : 0.0
 Total NaN values in row 9957 :- 0 and it's percentage : 0.0
 Total NaN values in row 9958 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9959 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9960 :- 0 and it's percentage : 0.0
 Total NaN values in row 9961 :- 0 and it's percentage : 0.0
 Total NaN values in row 9962 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9963 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9964 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9965 :- 0 and it's percentage : 0.0
 Total NaN values in row 9966 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 9967 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9968 :- 0 and it's percentage : 0.0
 Total NaN values in row 9969 :- 0 and it's percentage : 0.0
 Total NaN values in row 9970 :- 0 and it's percentage : 0.0
 Total NaN values in row 9971 :- 0 and it's percentage : 0.0
 Total NaN values in row 9972 :- 0 and it's percentage : 0.0
 Total NaN values in row 9973 :- 0 and it's percentage : 0.0
 Total NaN values in row 9974 :- 0 and it's percentage : 0.0
 Total NaN values in row 9975 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9976 :- 0 and it's percentage : 0.0
 Total NaN values in row 9977 :- 0 and it's percentage : 0.0
 Total NaN values in row 9978 :- 0 and it's percentage : 0.0
 Total NaN values in row 9979 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9980 :- 0 and it's percentage : 0.0
 Total NaN values in row 9981 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9982 :- 0 and it's percentage : 0.0
 Total NaN values in row 9983 :- 0 and it's percentage : 0.0
 Total NaN values in row 9984 :- 0 and it's percentage : 0.0
 Total NaN values in row 9985 :- 0 and it's percentage : 0.0
 Total NaN values in row 9986 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9987 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9988 :- 0 and it's percentage : 0.0
 Total NaN values in row 9989 :- 0 and it's percentage : 0.0
 Total NaN values in row 9990 :- 0 and it's percentage : 0.0
 Total NaN values in row 9991 :- 0 and it's percentage : 0.0
 Total NaN values in row 9992 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 9993 :- 0 and it's percentage : 0.0
 Total NaN values in row 9994 :- 0 and it's percentage : 0.0
 Total NaN values in row 9995 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 9996 :- 0 and it's percentage : 0.0
 Total NaN values in row 9997 :- 0 and it's percentage : 0.0
 Total NaN values in row 9998 :- 0 and it's percentage : 0.0
 Total NaN values in row 9999 :- 0 and it's percentage : 0.0
 Total NaN values in row 10000 :- 0 and it's percentage : 0.0
 Total NaN values in row 10001 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10002 :- 0 and it's percentage : 0.0
 Total NaN values in row 10003 :- 0 and it's percentage : 0.0
 Total NaN values in row 10004 :- 0 and it's percentage : 0.0
 Total NaN values in row 10005 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10006 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10007 :- 0 and it's percentage : 0.0
 Total NaN values in row 10008 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10009 :- 0 and it's percentage : 0.0
 Total NaN values in row 10010 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10011 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10012 :- 0 and it's percentage : 0.0
 Total NaN values in row 10013 :- 0 and it's percentage : 0.0
 Total NaN values in row 10014 :- 0 and it's percentage : 0.0
 Total NaN values in row 10015 :- 0 and it's percentage : 0.0
 Total NaN values in row 10016 :- 0 and it's percentage : 0.0
 Total NaN values in row 10017 :- 0 and it's percentage : 0.0
 Total NaN values in row 10018 :- 0 and it's percentage : 0.0
 Total NaN values in row 10019 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10020 :- 0 and it's percentage : 0.0
 Total NaN values in row 10021 :- 0 and it's percentage : 0.0
 Total NaN values in row 10022 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10023 :- 0 and it's percentage : 0.0
 Total NaN values in row 10024 :- 0 and it's percentage : 0.0
 Total NaN values in row 10025 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10026 :- 0 and it's percentage : 0.0
 Total NaN values in row 10027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10029 :- 0 and it's percentage : 0.0
 Total NaN values in row 10030 :- 0 and it's percentage : 0.0
 Total NaN values in row 10031 :- 0 and it's percentage : 0.0
 Total NaN values in row 10032 :- 0 and it's percentage : 0.0
 Total NaN values in row 10033 :- 0 and it's percentage : 0.0
 Total NaN values in row 10034 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10035 :- 0 and it's percentage : 0.0

 Total NaN values in row 10036 :- 0 and it's percentage : 0.0
 Total NaN values in row 10037 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10038 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10039 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10040 :- 0 and it's percentage : 0.0
 Total NaN values in row 10041 :- 0 and it's percentage : 0.0
 Total NaN values in row 10042 :- 0 and it's percentage : 0.0
 Total NaN values in row 10043 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10044 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10045 :- 0 and it's percentage : 0.0
 Total NaN values in row 10046 :- 0 and it's percentage : 0.0
 Total NaN values in row 10047 :- 0 and it's percentage : 0.0
 Total NaN values in row 10048 :- 0 and it's percentage : 0.0
 Total NaN values in row 10049 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10050 :- 0 and it's percentage : 0.0
 Total NaN values in row 10051 :- 0 and it's percentage : 0.0
 Total NaN values in row 10052 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10053 :- 0 and it's percentage : 0.0
 Total NaN values in row 10054 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10055 :- 0 and it's percentage : 0.0
 Total NaN values in row 10056 :- 0 and it's percentage : 0.0
 Total NaN values in row 10057 :- 0 and it's percentage : 0.0
 Total NaN values in row 10058 :- 0 and it's percentage : 0.0
 Total NaN values in row 10059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10060 :- 0 and it's percentage : 0.0
 Total NaN values in row 10061 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10062 :- 0 and it's percentage : 0.0
 Total NaN values in row 10063 :- 0 and it's percentage : 0.0
 Total NaN values in row 10064 :- 0 and it's percentage : 0.0
 Total NaN values in row 10065 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10066 :- 0 and it's percentage : 0.0
 Total NaN values in row 10067 :- 0 and it's percentage : 0.0
 Total NaN values in row 10068 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10069 :- 0 and it's percentage : 0.0
 Total NaN values in row 10070 :- 0 and it's percentage : 0.0
 Total NaN values in row 10071 :- 0 and it's percentage : 0.0
 Total NaN values in row 10072 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10073 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10074 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10075 :- 0 and it's percentage : 0.0
 Total NaN values in row 10076 :- 0 and it's percentage : 0.0
 Total NaN values in row 10077 :- 0 and it's percentage : 0.0
 Total NaN values in row 10078 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10079 :- 0 and it's percentage : 0.0
 Total NaN values in row 10080 :- 0 and it's percentage : 0.0
 Total NaN values in row 10081 :- 0 and it's percentage : 0.0
 Total NaN values in row 10082 :- 0 and it's percentage : 0.0
 Total NaN values in row 10083 :- 0 and it's percentage : 0.0
 Total NaN values in row 10084 :- 0 and it's percentage : 0.0
 Total NaN values in row 10085 :- 0 and it's percentage : 0.0
 Total NaN values in row 10086 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10087 :- 0 and it's percentage : 0.0
 Total NaN values in row 10088 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10090 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10091 :- 0 and it's percentage : 0.0
 Total NaN values in row 10092 :- 0 and it's percentage : 0.0
 Total NaN values in row 10093 :- 0 and it's percentage : 0.0
 Total NaN values in row 10094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10095 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10096 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10097 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10098 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10099 :- 0 and it's percentage : 0.0
 Total NaN values in row 10100 :- 0 and it's percentage : 0.0
 Total NaN values in row 10101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10102 :- 0 and it's percentage : 0.0
 Total NaN values in row 10103 :- 0 and it's percentage : 0.0
 Total NaN values in row 10104 :- 0 and it's percentage : 0.0
 Total NaN values in row 10105 :- 0 and it's percentage : 0.0
 Total NaN values in row 10106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10107 :- 0 and it's percentage : 0.0
 Total NaN values in row 10108 :- 0 and it's percentage : 0.0
 Total NaN values in row 10109 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10111 :- 0 and it's percentage : 0.0
 Total NaN values in row 10112 :- 0 and it's percentage : 0.0
 Total NaN values in row 10113 :- 0 and it's percentage : 0.0
 Total NaN values in row 10114 :- 0 and it's percentage : 0.0
 Total NaN values in row 10115 :- 0 and it's percentage : 0.0
 Total NaN values in row 10116 :- 0 and it's percentage : 0.0
 Total NaN values in row 10117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10119 :- 0 and it's percentage : 0.0
 Total NaN values in row 10120 :- 0 and it's percentage : 0.0
 Total NaN values in row 10121 :- 0 and it's percentage : 0.0
 Total NaN values in row 10122 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10123 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10124 :- 0 and it's percentage : 0.0
 Total NaN values in row 10125 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10126 :- 0 and it's percentage : 0.0
 Total NaN values in row 10127 :- 0 and it's percentage : 0.0
 Total NaN values in row 10128 :- 0 and it's percentage : 0.0
 Total NaN values in row 10129 :- 0 and it's percentage : 0.0
 Total NaN values in row 10130 :- 0 and it's percentage : 0.0
 Total NaN values in row 10131 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10132 :- 0 and it's percentage : 0.0
 Total NaN values in row 10133 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10134 :- 0 and it's percentage : 0.0
 Total NaN values in row 10135 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10136 :- 0 and it's percentage : 0.0
 Total NaN values in row 10137 :- 0 and it's percentage : 0.0
 Total NaN values in row 10138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10139 :- 0 and it's percentage : 0.0
 Total NaN values in row 10140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10141 :- 0 and it's percentage : 0.0
 Total NaN values in row 10142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10143 :- 0 and it's percentage : 0.0
 Total NaN values in row 10144 :- 0 and it's percentage : 0.0
 Total NaN values in row 10145 :- 0 and it's percentage : 0.0
 Total NaN values in row 10146 :- 0 and it's percentage : 0.0
 Total NaN values in row 10147 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10148 :- 0 and it's percentage : 0.0
 Total NaN values in row 10149 :- 0 and it's percentage : 0.0
 Total NaN values in row 10150 :- 0 and it's percentage : 0.0
 Total NaN values in row 10151 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10152 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10153 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10154 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10155 :- 0 and it's percentage : 0.0
 Total NaN values in row 10156 :- 0 and it's percentage : 0.0
 Total NaN values in row 10157 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10158 :- 0 and it's percentage : 0.0
 Total NaN values in row 10159 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10160 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10161 :- 0 and it's percentage : 0.0

 Total NaN values in row 10162 :- 0 and it's percentage : 0.0
 Total NaN values in row 10163 :- 0 and it's percentage : 0.0
 Total NaN values in row 10164 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10165 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10166 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10167 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10168 :- 0 and it's percentage : 0.0
 Total NaN values in row 10169 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10170 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10171 :- 0 and it's percentage : 0.0
 Total NaN values in row 10172 :- 0 and it's percentage : 0.0
 Total NaN values in row 10173 :- 0 and it's percentage : 0.0
 Total NaN values in row 10174 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10175 :- 0 and it's percentage : 0.0
 Total NaN values in row 10176 :- 0 and it's percentage : 0.0
 Total NaN values in row 10177 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10178 :- 0 and it's percentage : 0.0
 Total NaN values in row 10179 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10180 :- 0 and it's percentage : 0.0
 Total NaN values in row 10181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10182 :- 0 and it's percentage : 0.0
 Total NaN values in row 10183 :- 0 and it's percentage : 0.0
 Total NaN values in row 10184 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10185 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10186 :- 0 and it's percentage : 0.0
 Total NaN values in row 10187 :- 0 and it's percentage : 0.0
 Total NaN values in row 10188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10189 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10190 :- 0 and it's percentage : 0.0
 Total NaN values in row 10191 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10192 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10193 :- 0 and it's percentage : 0.0
 Total NaN values in row 10194 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10195 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10196 :- 0 and it's percentage : 0.0
 Total NaN values in row 10197 :- 0 and it's percentage : 0.0
 Total NaN values in row 10198 :- 0 and it's percentage : 0.0
 Total NaN values in row 10199 :- 0 and it's percentage : 0.0
 Total NaN values in row 10200 :- 0 and it's percentage : 0.0
 Total NaN values in row 10201 :- 0 and it's percentage : 0.0
 Total NaN values in row 10202 :- 0 and it's percentage : 0.0
 Total NaN values in row 10203 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10204 :- 0 and it's percentage : 0.0
 Total NaN values in row 10205 :- 0 and it's percentage : 0.0
 Total NaN values in row 10206 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10207 :- 0 and it's percentage : 0.0
 Total NaN values in row 10208 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10209 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10210 :- 0 and it's percentage : 0.0
 Total NaN values in row 10211 :- 0 and it's percentage : 0.0
 Total NaN values in row 10212 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10213 :- 0 and it's percentage : 0.0
 Total NaN values in row 10214 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10215 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10216 :- 0 and it's percentage : 0.0
 Total NaN values in row 10217 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10218 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10219 :- 0 and it's percentage : 0.0
 Total NaN values in row 10220 :- 0 and it's percentage : 0.0
 Total NaN values in row 10221 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10222 :- 0 and it's percentage : 0.0
 Total NaN values in row 10223 :- 0 and it's percentage : 0.0
 Total NaN values in row 10224 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10225 :- 0 and it's percentage : 0.0
 Total NaN values in row 10226 :- 0 and it's percentage : 0.0
 Total NaN values in row 10227 :- 0 and it's percentage : 0.0
 Total NaN values in row 10228 :- 0 and it's percentage : 0.0
 Total NaN values in row 10229 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10230 :- 0 and it's percentage : 0.0
 Total NaN values in row 10231 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10232 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10233 :- 0 and it's percentage : 0.0
 Total NaN values in row 10234 :- 0 and it's percentage : 0.0
 Total NaN values in row 10235 :- 0 and it's percentage : 0.0
 Total NaN values in row 10236 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10237 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10238 :- 0 and it's percentage : 0.0
 Total NaN values in row 10239 :- 0 and it's percentage : 0.0
 Total NaN values in row 10240 :- 0 and it's percentage : 0.0
 Total NaN values in row 10241 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10242 :- 0 and it's percentage : 0.0
 Total NaN values in row 10243 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10244 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10245 :- 0 and it's percentage : 0.0
 Total NaN values in row 10246 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10247 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10248 :- 0 and it's percentage : 0.0
 Total NaN values in row 10249 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10250 :- 0 and it's percentage : 0.0
 Total NaN values in row 10251 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10252 :- 0 and it's percentage : 0.0
 Total NaN values in row 10253 :- 0 and it's percentage : 0.0
 Total NaN values in row 10254 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10255 :- 0 and it's percentage : 0.0
 Total NaN values in row 10256 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10257 :- 0 and it's percentage : 0.0
 Total NaN values in row 10258 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10259 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10260 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10261 :- 0 and it's percentage : 0.0
 Total NaN values in row 10262 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10263 :- 0 and it's percentage : 0.0
 Total NaN values in row 10264 :- 0 and it's percentage : 0.0
 Total NaN values in row 10265 :- 0 and it's percentage : 0.0
 Total NaN values in row 10266 :- 0 and it's percentage : 0.0
 Total NaN values in row 10267 :- 0 and it's percentage : 0.0
 Total NaN values in row 10268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10269 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10270 :- 0 and it's percentage : 0.0
 Total NaN values in row 10271 :- 0 and it's percentage : 0.0
 Total NaN values in row 10272 :- 0 and it's percentage : 0.0
 Total NaN values in row 10273 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10274 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10275 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10276 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10277 :- 0 and it's percentage : 0.0
 Total NaN values in row 10278 :- 0 and it's percentage : 0.0
 Total NaN values in row 10279 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10280 :- 0 and it's percentage : 0.0
 Total NaN values in row 10281 :- 0 and it's percentage : 0.0
 Total NaN values in row 10282 :- 0 and it's percentage : 0.0
 Total NaN values in row 10283 :- 0 and it's percentage : 0.0
 Total NaN values in row 10284 :- 0 and it's percentage : 0.0
 Total NaN values in row 10285 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10286 :- 0 and it's percentage : 0.0
 Total NaN values in row 10287 :- 0 and it's percentage : 0.0
 Total NaN values in row 10288 :- 0 and it's percentage : 0.0
 Total NaN values in row 10289 :- 0 and it's percentage : 0.0
 Total NaN values in row 10290 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10291 :- 0 and it's percentage : 0.0
 Total NaN values in row 10292 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10293 :- 0 and it's percentage : 0.0
 Total NaN values in row 10294 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10295 :- 0 and it's percentage : 0.0
 Total NaN values in row 10296 :- 0 and it's percentage : 0.0
 Total NaN values in row 10297 :- 0 and it's percentage : 0.0
 Total NaN values in row 10298 :- 0 and it's percentage : 0.0
 Total NaN values in row 10299 :- 0 and it's percentage : 0.0
 Total NaN values in row 10300 :- 0 and it's percentage : 0.0
 Total NaN values in row 10301 :- 0 and it's percentage : 0.0
 Total NaN values in row 10302 :- 0 and it's percentage : 0.0
 Total NaN values in row 10303 :- 0 and it's percentage : 0.0
 Total NaN values in row 10304 :- 0 and it's percentage : 0.0
 Total NaN values in row 10305 :- 0 and it's percentage : 0.0

 Total NaN values in row 10306 :- 0 and it's percentage : 0.0
 Total NaN values in row 10307 :- 0 and it's percentage : 0.0
 Total NaN values in row 10308 :- 0 and it's percentage : 0.0
 Total NaN values in row 10309 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10310 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10311 :- 0 and it's percentage : 0.0
 Total NaN values in row 10312 :- 0 and it's percentage : 0.0
 Total NaN values in row 10313 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10314 :- 0 and it's percentage : 0.0
 Total NaN values in row 10315 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10316 :- 0 and it's percentage : 0.0
 Total NaN values in row 10317 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10318 :- 0 and it's percentage : 0.0
 Total NaN values in row 10319 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10320 :- 0 and it's percentage : 0.0
 Total NaN values in row 10321 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10322 :- 0 and it's percentage : 0.0
 Total NaN values in row 10323 :- 0 and it's percentage : 0.0
 Total NaN values in row 10324 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10325 :- 0 and it's percentage : 0.0
 Total NaN values in row 10326 :- 0 and it's percentage : 0.0
 Total NaN values in row 10327 :- 0 and it's percentage : 0.0
 Total NaN values in row 10328 :- 0 and it's percentage : 0.0
 Total NaN values in row 10329 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10330 :- 0 and it's percentage : 0.0
 Total NaN values in row 10331 :- 0 and it's percentage : 0.0
 Total NaN values in row 10332 :- 0 and it's percentage : 0.0
 Total NaN values in row 10333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10334 :- 0 and it's percentage : 0.0
 Total NaN values in row 10335 :- 0 and it's percentage : 0.0
 Total NaN values in row 10336 :- 0 and it's percentage : 0.0
 Total NaN values in row 10337 :- 0 and it's percentage : 0.0
 Total NaN values in row 10338 :- 0 and it's percentage : 0.0
 Total NaN values in row 10339 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10340 :- 0 and it's percentage : 0.0
 Total NaN values in row 10341 :- 0 and it's percentage : 0.0
 Total NaN values in row 10342 :- 0 and it's percentage : 0.0
 Total NaN values in row 10343 :- 0 and it's percentage : 0.0
 Total NaN values in row 10344 :- 0 and it's percentage : 0.0
 Total NaN values in row 10345 :- 0 and it's percentage : 0.0
 Total NaN values in row 10346 :- 0 and it's percentage : 0.0
 Total NaN values in row 10347 :- 0 and it's percentage : 0.0
 Total NaN values in row 10348 :- 0 and it's percentage : 0.0
 Total NaN values in row 10349 :- 0 and it's percentage : 0.0
 Total NaN values in row 10350 :- 0 and it's percentage : 0.0
 Total NaN values in row 10351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10352 :- 0 and it's percentage : 0.0
 Total NaN values in row 10353 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10354 :- 0 and it's percentage : 0.0
 Total NaN values in row 10355 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10356 :- 0 and it's percentage : 0.0
 Total NaN values in row 10357 :- 0 and it's percentage : 0.0
 Total NaN values in row 10358 :- 0 and it's percentage : 0.0
 Total NaN values in row 10359 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10360 :- 0 and it's percentage : 0.0
 Total NaN values in row 10361 :- 0 and it's percentage : 0.0
 Total NaN values in row 10362 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10363 :- 0 and it's percentage : 0.0
 Total NaN values in row 10364 :- 0 and it's percentage : 0.0
 Total NaN values in row 10365 :- 0 and it's percentage : 0.0
 Total NaN values in row 10366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10367 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10368 :- 0 and it's percentage : 0.0
 Total NaN values in row 10369 :- 0 and it's percentage : 0.0
 Total NaN values in row 10370 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10371 :- 0 and it's percentage : 0.0
 Total NaN values in row 10372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10373 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10375 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10376 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10377 :- 0 and it's percentage : 0.0
 Total NaN values in row 10378 :- 0 and it's percentage : 0.0
 Total NaN values in row 10379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10380 :- 0 and it's percentage : 0.0
 Total NaN values in row 10381 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10382 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10383 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10384 :- 0 and it's percentage : 0.0
 Total NaN values in row 10385 :- 0 and it's percentage : 0.0
 Total NaN values in row 10386 :- 0 and it's percentage : 0.0
 Total NaN values in row 10387 :- 0 and it's percentage : 0.0
 Total NaN values in row 10388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10389 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10390 :- 0 and it's percentage : 0.0
 Total NaN values in row 10391 :- 0 and it's percentage : 0.0
 Total NaN values in row 10392 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10393 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10394 :- 0 and it's percentage : 0.0
 Total NaN values in row 10395 :- 0 and it's percentage : 0.0
 Total NaN values in row 10396 :- 0 and it's percentage : 0.0
 Total NaN values in row 10397 :- 0 and it's percentage : 0.0
 Total NaN values in row 10398 :- 0 and it's percentage : 0.0
 Total NaN values in row 10399 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10400 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10401 :- 0 and it's percentage : 0.0
 Total NaN values in row 10402 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10403 :- 0 and it's percentage : 0.0
 Total NaN values in row 10404 :- 0 and it's percentage : 0.0
 Total NaN values in row 10405 :- 0 and it's percentage : 0.0
 Total NaN values in row 10406 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10407 :- 0 and it's percentage : 0.0
 Total NaN values in row 10408 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10409 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10410 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10411 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10412 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10413 :- 0 and it's percentage : 0.0
 Total NaN values in row 10414 :- 0 and it's percentage : 0.0
 Total NaN values in row 10415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10416 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10417 :- 0 and it's percentage : 0.0
 Total NaN values in row 10418 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10419 :- 0 and it's percentage : 0.0
 Total NaN values in row 10420 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10421 :- 0 and it's percentage : 0.0
 Total NaN values in row 10422 :- 0 and it's percentage : 0.0
 Total NaN values in row 10423 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10424 :- 0 and it's percentage : 0.0
 Total NaN values in row 10425 :- 0 and it's percentage : 0.0
 Total NaN values in row 10426 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10427 :- 0 and it's percentage : 0.0
 Total NaN values in row 10428 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10429 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10430 :- 0 and it's percentage : 0.0
 Total NaN values in row 10431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10433 :- 0 and it's percentage : 0.0
 Total NaN values in row 10434 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10435 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10436 :- 0 and it's percentage : 0.0
 Total NaN values in row 10437 :- 0 and it's percentage : 0.0
 Total NaN values in row 10438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10439 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10440 :- 0 and it's percentage : 0.0
 Total NaN values in row 10441 :- 0 and it's percentage : 0.0
 Total NaN values in row 10442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10443 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10445 :- 0 and it's percentage : 0.0
 Total NaN values in row 10446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10447 :- 0 and it's percentage : 0.0
 Total NaN values in row 10448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10449 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10450 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10451 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10452 :- 0 and it's percentage : 0.0
 Total NaN values in row 10453 :- 0 and it's percentage : 0.0
 Total NaN values in row 10454 :- 0 and it's percentage : 0.0
 Total NaN values in row 10455 :- 0 and it's percentage : 0.0
 Total NaN values in row 10456 :- 0 and it's percentage : 0.0
 Total NaN values in row 10457 :- 0 and it's percentage : 0.0
 Total NaN values in row 10458 :- 0 and it's percentage : 0.0
 Total NaN values in row 10459 :- 0 and it's percentage : 0.0
 Total NaN values in row 10460 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10461 :- 0 and it's percentage : 0.0
 Total NaN values in row 10462 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10463 :- 0 and it's percentage : 0.0
 Total NaN values in row 10464 :- 0 and it's percentage : 0.0
 Total NaN values in row 10465 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10466 :- 0 and it's percentage : 0.0
 Total NaN values in row 10467 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10468 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10469 :- 0 and it's percentage : 0.0
 Total NaN values in row 10470 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10471 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10472 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10473 :- 0 and it's percentage : 0.0
 Total NaN values in row 10474 :- 0 and it's percentage : 0.0
 Total NaN values in row 10475 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10476 :- 0 and it's percentage : 0.0
 Total NaN values in row 10477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10478 :- 0 and it's percentage : 0.0
 Total NaN values in row 10479 :- 0 and it's percentage : 0.0
 Total NaN values in row 10480 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10481 :- 0 and it's percentage : 0.0
 Total NaN values in row 10482 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10483 :- 0 and it's percentage : 0.0
 Total NaN values in row 10484 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10485 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 10486 :- 0 and it's percentage : 0.0
 Total NaN values in row 10487 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10488 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 10489 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10490 :- 0 and it's percentage : 0.0
 Total NaN values in row 10491 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10492 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10493 :- 0 and it's percentage : 0.0
 Total NaN values in row 10494 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10495 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10496 :- 0 and it's percentage : 0.0
 Total NaN values in row 10497 :- 0 and it's percentage : 0.0
 Total NaN values in row 10498 :- 0 and it's percentage : 0.0
 Total NaN values in row 10499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10501 :- 0 and it's percentage : 0.0
 Total NaN values in row 10502 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10503 :- 0 and it's percentage : 0.0
 Total NaN values in row 10504 :- 0 and it's percentage : 0.0
 Total NaN values in row 10505 :- 0 and it's percentage : 0.0
 Total NaN values in row 10506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10507 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10508 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10511 :- 0 and it's percentage : 0.0
 Total NaN values in row 10512 :- 0 and it's percentage : 0.0
 Total NaN values in row 10513 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10514 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10515 :- 0 and it's percentage : 0.0
 Total NaN values in row 10516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10517 :- 0 and it's percentage : 0.0
 Total NaN values in row 10518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10519 :- 0 and it's percentage : 0.0
 Total NaN values in row 10520 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10521 :- 0 and it's percentage : 0.0
 Total NaN values in row 10522 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10523 :- 0 and it's percentage : 0.0
 Total NaN values in row 10524 :- 0 and it's percentage : 0.0
 Total NaN values in row 10525 :- 0 and it's percentage : 0.0
 Total NaN values in row 10526 :- 0 and it's percentage : 0.0
 Total NaN values in row 10527 :- 0 and it's percentage : 0.0
 Total NaN values in row 10528 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10529 :- 0 and it's percentage : 0.0
 Total NaN values in row 10530 :- 0 and it's percentage : 0.0
 Total NaN values in row 10531 :- 0 and it's percentage : 0.0
 Total NaN values in row 10532 :- 0 and it's percentage : 0.0
 Total NaN values in row 10533 :- 0 and it's percentage : 0.0
 Total NaN values in row 10534 :- 0 and it's percentage : 0.0
 Total NaN values in row 10535 :- 0 and it's percentage : 0.0
 Total NaN values in row 10536 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10538 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10539 :- 0 and it's percentage : 0.0
 Total NaN values in row 10540 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10541 :- 0 and it's percentage : 0.0
 Total NaN values in row 10542 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10543 :- 0 and it's percentage : 0.0
 Total NaN values in row 10544 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10545 :- 0 and it's percentage : 0.0
 Total NaN values in row 10546 :- 0 and it's percentage : 0.0
 Total NaN values in row 10547 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10548 :- 0 and it's percentage : 0.0
 Total NaN values in row 10549 :- 0 and it's percentage : 0.0
 Total NaN values in row 10550 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10551 :- 0 and it's percentage : 0.0
 Total NaN values in row 10552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10553 :- 0 and it's percentage : 0.0
 Total NaN values in row 10554 :- 0 and it's percentage : 0.0
 Total NaN values in row 10555 :- 0 and it's percentage : 0.0
 Total NaN values in row 10556 :- 0 and it's percentage : 0.0
 Total NaN values in row 10557 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10558 :- 0 and it's percentage : 0.0
 Total NaN values in row 10559 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10560 :- 0 and it's percentage : 0.0
 Total NaN values in row 10561 :- 0 and it's percentage : 0.0
 Total NaN values in row 10562 :- 0 and it's percentage : 0.0
 Total NaN values in row 10563 :- 0 and it's percentage : 0.0
 Total NaN values in row 10564 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10565 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10566 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10567 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10568 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10569 :- 0 and it's percentage : 0.0
 Total NaN values in row 10570 :- 0 and it's percentage : 0.0
 Total NaN values in row 10571 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10572 :- 0 and it's percentage : 0.0
 Total NaN values in row 10573 :- 0 and it's percentage : 0.0
 Total NaN values in row 10574 :- 0 and it's percentage : 0.0
 Total NaN values in row 10575 :- 0 and it's percentage : 0.0
 Total NaN values in row 10576 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10577 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10578 :- 0 and it's percentage : 0.0
 Total NaN values in row 10579 :- 0 and it's percentage : 0.0
 Total NaN values in row 10580 :- 0 and it's percentage : 0.0
 Total NaN values in row 10581 :- 0 and it's percentage : 0.0
 Total NaN values in row 10582 :- 0 and it's percentage : 0.0
 Total NaN values in row 10583 :- 0 and it's percentage : 0.0
 Total NaN values in row 10584 :- 0 and it's percentage : 0.0
 Total NaN values in row 10585 :- 0 and it's percentage : 0.0
 Total NaN values in row 10586 :- 0 and it's percentage : 0.0
 Total NaN values in row 10587 :- 0 and it's percentage : 0.0
 Total NaN values in row 10588 :- 0 and it's percentage : 0.0
 Total NaN values in row 10589 :- 0 and it's percentage : 0.0
 Total NaN values in row 10590 :- 0 and it's percentage : 0.0
 Total NaN values in row 10591 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10592 :- 0 and it's percentage : 0.0
 Total NaN values in row 10593 :- 0 and it's percentage : 0.0
 Total NaN values in row 10594 :- 0 and it's percentage : 0.0
 Total NaN values in row 10595 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10596 :- 0 and it's percentage : 0.0
 Total NaN values in row 10597 :- 0 and it's percentage : 0.0
 Total NaN values in row 10598 :- 0 and it's percentage : 0.0
 Total NaN values in row 10599 :- 0 and it's percentage : 0.0
 Total NaN values in row 10600 :- 0 and it's percentage : 0.0
 Total NaN values in row 10601 :- 0 and it's percentage : 0.0
 Total NaN values in row 10602 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10603 :- 0 and it's percentage : 0.0
 Total NaN values in row 10604 :- 0 and it's percentage : 0.0
 Total NaN values in row 10605 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10606 :- 0 and it's percentage : 0.0
 Total NaN values in row 10607 :- 0 and it's percentage : 0.0
 Total NaN values in row 10608 :- 0 and it's percentage : 0.0
 Total NaN values in row 10609 :- 0 and it's percentage : 0.0
 Total NaN values in row 10610 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10611 :- 0 and it's percentage : 0.0
 Total NaN values in row 10612 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10613 :- 0 and it's percentage : 0.0
 Total NaN values in row 10614 :- 0 and it's percentage : 0.0
 Total NaN values in row 10615 :- 0 and it's percentage : 0.0
 Total NaN values in row 10616 :- 0 and it's percentage : 0.0
 Total NaN values in row 10617 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10618 :- 0 and it's percentage : 0.0
 Total NaN values in row 10619 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10621 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10623 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10624 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 10625 :- 0 and it's percentage : 0.0
 Total NaN values in row 10626 :- 0 and it's percentage : 0.0
 Total NaN values in row 10627 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10628 :- 0 and it's percentage : 0.0
 Total NaN values in row 10629 :- 0 and it's percentage : 0.0
 Total NaN values in row 10630 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10631 :- 0 and it's percentage : 0.0
 Total NaN values in row 10632 :- 0 and it's percentage : 0.0
 Total NaN values in row 10633 :- 0 and it's percentage : 0.0
 Total NaN values in row 10634 :- 0 and it's percentage : 0.0
 Total NaN values in row 10635 :- 0 and it's percentage : 0.0
 Total NaN values in row 10636 :- 0 and it's percentage : 0.0
 Total NaN values in row 10637 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10638 :- 0 and it's percentage : 0.0
 Total NaN values in row 10639 :- 0 and it's percentage : 0.0
 Total NaN values in row 10640 :- 0 and it's percentage : 0.0
 Total NaN values in row 10641 :- 0 and it's percentage : 0.0
 Total NaN values in row 10642 :- 0 and it's percentage : 0.0
 Total NaN values in row 10643 :- 0 and it's percentage : 0.0
 Total NaN values in row 10644 :- 0 and it's percentage : 0.0
 Total NaN values in row 10645 :- 0 and it's percentage : 0.0
 Total NaN values in row 10646 :- 0 and it's percentage : 0.0
 Total NaN values in row 10647 :- 0 and it's percentage : 0.0
 Total NaN values in row 10648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10649 :- 0 and it's percentage : 0.0
 Total NaN values in row 10650 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10651 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10652 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10653 :- 0 and it's percentage : 0.0
 Total NaN values in row 10654 :- 0 and it's percentage : 0.0
 Total NaN values in row 10655 :- 0 and it's percentage : 0.0
 Total NaN values in row 10656 :- 0 and it's percentage : 0.0
 Total NaN values in row 10657 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10658 :- 0 and it's percentage : 0.0
 Total NaN values in row 10659 :- 0 and it's percentage : 0.0
 Total NaN values in row 10660 :- 0 and it's percentage : 0.0
 Total NaN values in row 10661 :- 0 and it's percentage : 0.0
 Total NaN values in row 10662 :- 0 and it's percentage : 0.0
 Total NaN values in row 10663 :- 0 and it's percentage : 0.0
 Total NaN values in row 10664 :- 0 and it's percentage : 0.0
 Total NaN values in row 10665 :- 0 and it's percentage : 0.0
 Total NaN values in row 10666 :- 0 and it's percentage : 0.0
 Total NaN values in row 10667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10669 :- 0 and it's percentage : 0.0
 Total NaN values in row 10670 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10671 :- 0 and it's percentage : 0.0
 Total NaN values in row 10672 :- 0 and it's percentage : 0.0
 Total NaN values in row 10673 :- 0 and it's percentage : 0.0
 Total NaN values in row 10674 :- 0 and it's percentage : 0.0
 Total NaN values in row 10675 :- 0 and it's percentage : 0.0
 Total NaN values in row 10676 :- 0 and it's percentage : 0.0
 Total NaN values in row 10677 :- 0 and it's percentage : 0.0
 Total NaN values in row 10678 :- 0 and it's percentage : 0.0
 Total NaN values in row 10679 :- 0 and it's percentage : 0.0
 Total NaN values in row 10680 :- 0 and it's percentage : 0.0
 Total NaN values in row 10681 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10682 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10683 :- 0 and it's percentage : 0.0
 Total NaN values in row 10684 :- 0 and it's percentage : 0.0
 Total NaN values in row 10685 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10686 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10689 :- 0 and it's percentage : 0.0
 Total NaN values in row 10690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10691 :- 0 and it's percentage : 0.0
 Total NaN values in row 10692 :- 0 and it's percentage : 0.0
 Total NaN values in row 10693 :- 0 and it's percentage : 0.0
 Total NaN values in row 10694 :- 0 and it's percentage : 0.0
 Total NaN values in row 10695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10696 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10697 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10698 :- 0 and it's percentage : 0.0
 Total NaN values in row 10699 :- 0 and it's percentage : 0.0
 Total NaN values in row 10700 :- 0 and it's percentage : 0.0
 Total NaN values in row 10701 :- 0 and it's percentage : 0.0
 Total NaN values in row 10702 :- 0 and it's percentage : 0.0
 Total NaN values in row 10703 :- 0 and it's percentage : 0.0
 Total NaN values in row 10704 :- 0 and it's percentage : 0.0
 Total NaN values in row 10705 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10706 :- 0 and it's percentage : 0.0
 Total NaN values in row 10707 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10708 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10709 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10710 :- 0 and it's percentage : 0.0
 Total NaN values in row 10711 :- 0 and it's percentage : 0.0
 Total NaN values in row 10712 :- 0 and it's percentage : 0.0
 Total NaN values in row 10713 :- 0 and it's percentage : 0.0
 Total NaN values in row 10714 :- 0 and it's percentage : 0.0
 Total NaN values in row 10715 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10717 :- 0 and it's percentage : 0.0
 Total NaN values in row 10718 :- 0 and it's percentage : 0.0
 Total NaN values in row 10719 :- 0 and it's percentage : 0.0
 Total NaN values in row 10720 :- 0 and it's percentage : 0.0
 Total NaN values in row 10721 :- 0 and it's percentage : 0.0
 Total NaN values in row 10722 :- 0 and it's percentage : 0.0
 Total NaN values in row 10723 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10724 :- 0 and it's percentage : 0.0
 Total NaN values in row 10725 :- 0 and it's percentage : 0.0
 Total NaN values in row 10726 :- 0 and it's percentage : 0.0
 Total NaN values in row 10727 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10728 :- 0 and it's percentage : 0.0
 Total NaN values in row 10729 :- 0 and it's percentage : 0.0
 Total NaN values in row 10730 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10731 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10732 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10733 :- 0 and it's percentage : 0.0
 Total NaN values in row 10734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10735 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10736 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10737 :- 0 and it's percentage : 0.0
 Total NaN values in row 10738 :- 0 and it's percentage : 0.0
 Total NaN values in row 10739 :- 0 and it's percentage : 0.0
 Total NaN values in row 10740 :- 0 and it's percentage : 0.0
 Total NaN values in row 10741 :- 0 and it's percentage : 0.0
 Total NaN values in row 10742 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10743 :- 0 and it's percentage : 0.0
 Total NaN values in row 10744 :- 0 and it's percentage : 0.0
 Total NaN values in row 10745 :- 0 and it's percentage : 0.0
 Total NaN values in row 10746 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 10747 :- 0 and it's percentage : 0.0
 Total NaN values in row 10748 :- 0 and it's percentage : 0.0
 Total NaN values in row 10749 :- 0 and it's percentage : 0.0
 Total NaN values in row 10750 :- 0 and it's percentage : 0.0
 Total NaN values in row 10751 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10752 :- 0 and it's percentage : 0.0
 Total NaN values in row 10753 :- 0 and it's percentage : 0.0
 Total NaN values in row 10754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10755 :- 0 and it's percentage : 0.0
 Total NaN values in row 10756 :- 0 and it's percentage : 0.0
 Total NaN values in row 10757 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10758 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10759 :- 0 and it's percentage : 0.0
 Total NaN values in row 10760 :- 0 and it's percentage : 0.0
 Total NaN values in row 10761 :- 0 and it's percentage : 0.0
 Total NaN values in row 10762 :- 0 and it's percentage : 0.0
 Total NaN values in row 10763 :- 0 and it's percentage : 0.0
 Total NaN values in row 10764 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10765 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10766 :- 0 and it's percentage : 0.0
 Total NaN values in row 10767 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10770 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10771 :- 0 and it's percentage : 0.0
 Total NaN values in row 10772 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10773 :- 0 and it's percentage : 0.0
 Total NaN values in row 10774 :- 0 and it's percentage : 0.0
 Total NaN values in row 10775 :- 0 and it's percentage : 0.0
 Total NaN values in row 10776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10779 :- 0 and it's percentage : 0.0

 Total NaN values in row 10780 :- 0 and it's percentage : 0.0
 Total NaN values in row 10781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10782 :- 0 and it's percentage : 0.0
 Total NaN values in row 10783 :- 0 and it's percentage : 0.0
 Total NaN values in row 10784 :- 0 and it's percentage : 0.0
 Total NaN values in row 10785 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10787 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10788 :- 0 and it's percentage : 0.0
 Total NaN values in row 10789 :- 0 and it's percentage : 0.0
 Total NaN values in row 10790 :- 0 and it's percentage : 0.0
 Total NaN values in row 10791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10792 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10793 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10794 :- 0 and it's percentage : 0.0
 Total NaN values in row 10795 :- 0 and it's percentage : 0.0
 Total NaN values in row 10796 :- 0 and it's percentage : 0.0
 Total NaN values in row 10797 :- 0 and it's percentage : 0.0
 Total NaN values in row 10798 :- 0 and it's percentage : 0.0
 Total NaN values in row 10799 :- 0 and it's percentage : 0.0
 Total NaN values in row 10800 :- 0 and it's percentage : 0.0
 Total NaN values in row 10801 :- 0 and it's percentage : 0.0
 Total NaN values in row 10802 :- 0 and it's percentage : 0.0
 Total NaN values in row 10803 :- 0 and it's percentage : 0.0
 Total NaN values in row 10804 :- 0 and it's percentage : 0.0
 Total NaN values in row 10805 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10806 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10808 :- 0 and it's percentage : 0.0
 Total NaN values in row 10809 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10810 :- 0 and it's percentage : 0.0
 Total NaN values in row 10811 :- 0 and it's percentage : 0.0
 Total NaN values in row 10812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10813 :- 0 and it's percentage : 0.0
 Total NaN values in row 10814 :- 0 and it's percentage : 0.0
 Total NaN values in row 10815 :- 0 and it's percentage : 0.0
 Total NaN values in row 10816 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10817 :- 0 and it's percentage : 0.0
 Total NaN values in row 10818 :- 0 and it's percentage : 0.0
 Total NaN values in row 10819 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10820 :- 0 and it's percentage : 0.0
 Total NaN values in row 10821 :- 0 and it's percentage : 0.0
 Total NaN values in row 10822 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10823 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10824 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10825 :- 0 and it's percentage : 0.0
 Total NaN values in row 10826 :- 0 and it's percentage : 0.0
 Total NaN values in row 10827 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10828 :- 0 and it's percentage : 0.0
 Total NaN values in row 10829 :- 0 and it's percentage : 0.0
 Total NaN values in row 10830 :- 0 and it's percentage : 0.0
 Total NaN values in row 10831 :- 0 and it's percentage : 0.0
 Total NaN values in row 10832 :- 0 and it's percentage : 0.0
 Total NaN values in row 10833 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10834 :- 0 and it's percentage : 0.0
 Total NaN values in row 10835 :- 0 and it's percentage : 0.0
 Total NaN values in row 10836 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10837 :- 0 and it's percentage : 0.0
 Total NaN values in row 10838 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10839 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10840 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10841 :- 0 and it's percentage : 0.0
 Total NaN values in row 10842 :- 0 and it's percentage : 0.0
 Total NaN values in row 10843 :- 0 and it's percentage : 0.0
 Total NaN values in row 10844 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10845 :- 0 and it's percentage : 0.0
 Total NaN values in row 10846 :- 0 and it's percentage : 0.0
 Total NaN values in row 10847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10848 :- 0 and it's percentage : 0.0
 Total NaN values in row 10849 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10850 :- 0 and it's percentage : 0.0
 Total NaN values in row 10851 :- 0 and it's percentage : 0.0
 Total NaN values in row 10852 :- 0 and it's percentage : 0.0
 Total NaN values in row 10853 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10854 :- 0 and it's percentage : 0.0
 Total NaN values in row 10855 :- 0 and it's percentage : 0.0
 Total NaN values in row 10856 :- 0 and it's percentage : 0.0
 Total NaN values in row 10857 :- 0 and it's percentage : 0.0
 Total NaN values in row 10858 :- 0 and it's percentage : 0.0
 Total NaN values in row 10859 :- 0 and it's percentage : 0.0
 Total NaN values in row 10860 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10861 :- 0 and it's percentage : 0.0
 Total NaN values in row 10862 :- 0 and it's percentage : 0.0
 Total NaN values in row 10863 :- 0 and it's percentage : 0.0
 Total NaN values in row 10864 :- 0 and it's percentage : 0.0
 Total NaN values in row 10865 :- 0 and it's percentage : 0.0
 Total NaN values in row 10866 :- 0 and it's percentage : 0.0
 Total NaN values in row 10867 :- 0 and it's percentage : 0.0
 Total NaN values in row 10868 :- 0 and it's percentage : 0.0
 Total NaN values in row 10869 :- 0 and it's percentage : 0.0
 Total NaN values in row 10870 :- 0 and it's percentage : 0.0
 Total NaN values in row 10871 :- 0 and it's percentage : 0.0
 Total NaN values in row 10872 :- 0 and it's percentage : 0.0
 Total NaN values in row 10873 :- 0 and it's percentage : 0.0
 Total NaN values in row 10874 :- 0 and it's percentage : 0.0
 Total NaN values in row 10875 :- 0 and it's percentage : 0.0
 Total NaN values in row 10876 :- 0 and it's percentage : 0.0
 Total NaN values in row 10877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10878 :- 0 and it's percentage : 0.0
 Total NaN values in row 10879 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10880 :- 0 and it's percentage : 0.0
 Total NaN values in row 10881 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10882 :- 0 and it's percentage : 0.0
 Total NaN values in row 10883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10884 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10885 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10887 :- 0 and it's percentage : 0.0
 Total NaN values in row 10888 :- 0 and it's percentage : 0.0
 Total NaN values in row 10889 :- 0 and it's percentage : 0.0
 Total NaN values in row 10890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10891 :- 0 and it's percentage : 0.0
 Total NaN values in row 10892 :- 0 and it's percentage : 0.0
 Total NaN values in row 10893 :- 0 and it's percentage : 0.0
 Total NaN values in row 10894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10895 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10896 :- 0 and it's percentage : 0.0
 Total NaN values in row 10897 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10899 :- 0 and it's percentage : 0.0
 Total NaN values in row 10900 :- 0 and it's percentage : 0.0
 Total NaN values in row 10901 :- 0 and it's percentage : 0.0
 Total NaN values in row 10902 :- 0 and it's percentage : 0.0

 Total NaN values in row 10903 :- 0 and it's percentage : 0.0
 Total NaN values in row 10904 :- 0 and it's percentage : 0.0
 Total NaN values in row 10905 :- 0 and it's percentage : 0.0
 Total NaN values in row 10906 :- 0 and it's percentage : 0.0
 Total NaN values in row 10907 :- 0 and it's percentage : 0.0
 Total NaN values in row 10908 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10910 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10911 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10912 :- 0 and it's percentage : 0.0
 Total NaN values in row 10913 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10914 :- 0 and it's percentage : 0.0
 Total NaN values in row 10915 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10916 :- 0 and it's percentage : 0.0
 Total NaN values in row 10917 :- 0 and it's percentage : 0.0
 Total NaN values in row 10918 :- 0 and it's percentage : 0.0
 Total NaN values in row 10919 :- 0 and it's percentage : 0.0
 Total NaN values in row 10920 :- 0 and it's percentage : 0.0
 Total NaN values in row 10921 :- 0 and it's percentage : 0.0
 Total NaN values in row 10922 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10923 :- 0 and it's percentage : 0.0
 Total NaN values in row 10924 :- 0 and it's percentage : 0.0
 Total NaN values in row 10925 :- 0 and it's percentage : 0.0
 Total NaN values in row 10926 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10927 :- 0 and it's percentage : 0.0
 Total NaN values in row 10928 :- 0 and it's percentage : 0.0
 Total NaN values in row 10929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10930 :- 0 and it's percentage : 0.0
 Total NaN values in row 10931 :- 0 and it's percentage : 0.0
 Total NaN values in row 10932 :- 0 and it's percentage : 0.0
 Total NaN values in row 10933 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10934 :- 0 and it's percentage : 0.0
 Total NaN values in row 10935 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10936 :- 0 and it's percentage : 0.0
 Total NaN values in row 10937 :- 0 and it's percentage : 0.0
 Total NaN values in row 10938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10939 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10940 :- 0 and it's percentage : 0.0
 Total NaN values in row 10941 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10942 :- 0 and it's percentage : 0.0
 Total NaN values in row 10943 :- 0 and it's percentage : 0.0
 Total NaN values in row 10944 :- 0 and it's percentage : 0.0
 Total NaN values in row 10945 :- 0 and it's percentage : 0.0
 Total NaN values in row 10946 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10947 :- 0 and it's percentage : 0.0
 Total NaN values in row 10948 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10949 :- 0 and it's percentage : 0.0
 Total NaN values in row 10950 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10951 :- 0 and it's percentage : 0.0
 Total NaN values in row 10952 :- 0 and it's percentage : 0.0
 Total NaN values in row 10953 :- 0 and it's percentage : 0.0
 Total NaN values in row 10954 :- 0 and it's percentage : 0.0
 Total NaN values in row 10955 :- 0 and it's percentage : 0.0
 Total NaN values in row 10956 :- 0 and it's percentage : 0.0
 Total NaN values in row 10957 :- 0 and it's percentage : 0.0
 Total NaN values in row 10958 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10959 :- 0 and it's percentage : 0.0
 Total NaN values in row 10960 :- 0 and it's percentage : 0.0
 Total NaN values in row 10961 :- 0 and it's percentage : 0.0
 Total NaN values in row 10962 :- 0 and it's percentage : 0.0
 Total NaN values in row 10963 :- 0 and it's percentage : 0.0
 Total NaN values in row 10964 :- 0 and it's percentage : 0.0
 Total NaN values in row 10965 :- 0 and it's percentage : 0.0
 Total NaN values in row 10966 :- 0 and it's percentage : 0.0
 Total NaN values in row 10967 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 10968 :- 0 and it's percentage : 0.0
 Total NaN values in row 10969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10970 :- 0 and it's percentage : 0.0
 Total NaN values in row 10971 :- 0 and it's percentage : 0.0
 Total NaN values in row 10972 :- 0 and it's percentage : 0.0
 Total NaN values in row 10973 :- 0 and it's percentage : 0.0
 Total NaN values in row 10974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10975 :- 0 and it's percentage : 0.0
 Total NaN values in row 10976 :- 0 and it's percentage : 0.0
 Total NaN values in row 10977 :- 0 and it's percentage : 0.0
 Total NaN values in row 10978 :- 0 and it's percentage : 0.0
 Total NaN values in row 10979 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 10980 :- 0 and it's percentage : 0.0
 Total NaN values in row 10981 :- 0 and it's percentage : 0.0
 Total NaN values in row 10982 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10983 :- 0 and it's percentage : 0.0
 Total NaN values in row 10984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10985 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10986 :- 0 and it's percentage : 0.0
 Total NaN values in row 10987 :- 0 and it's percentage : 0.0
 Total NaN values in row 10988 :- 0 and it's percentage : 0.0
 Total NaN values in row 10989 :- 0 and it's percentage : 0.0
 Total NaN values in row 10990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10991 :- 0 and it's percentage : 0.0
 Total NaN values in row 10992 :- 0 and it's percentage : 0.0
 Total NaN values in row 10993 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 10994 :- 0 and it's percentage : 0.0
 Total NaN values in row 10995 :- 0 and it's percentage : 0.0
 Total NaN values in row 10996 :- 0 and it's percentage : 0.0
 Total NaN values in row 10997 :- 0 and it's percentage : 0.0
 Total NaN values in row 10998 :- 0 and it's percentage : 0.0
 Total NaN values in row 10999 :- 0 and it's percentage : 0.0
 Total NaN values in row 11000 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11001 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11002 :- 0 and it's percentage : 0.0
 Total NaN values in row 11003 :- 0 and it's percentage : 0.0
 Total NaN values in row 11004 :- 0 and it's percentage : 0.0
 Total NaN values in row 11005 :- 0 and it's percentage : 0.0
 Total NaN values in row 11006 :- 0 and it's percentage : 0.0
 Total NaN values in row 11007 :- 0 and it's percentage : 0.0
 Total NaN values in row 11008 :- 0 and it's percentage : 0.0
 Total NaN values in row 11009 :- 0 and it's percentage : 0.0
 Total NaN values in row 11010 :- 0 and it's percentage : 0.0
 Total NaN values in row 11011 :- 0 and it's percentage : 0.0
 Total NaN values in row 11012 :- 0 and it's percentage : 0.0
 Total NaN values in row 11013 :- 0 and it's percentage : 0.0
 Total NaN values in row 11014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11015 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11016 :- 0 and it's percentage : 0.0
 Total NaN values in row 11017 :- 0 and it's percentage : 0.0
 Total NaN values in row 11018 :- 0 and it's percentage : 0.0
 Total NaN values in row 11019 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11020 :- 0 and it's percentage : 0.0
 Total NaN values in row 11021 :- 0 and it's percentage : 0.0
 Total NaN values in row 11022 :- 0 and it's percentage : 0.0
 Total NaN values in row 11023 :- 0 and it's percentage : 0.0
 Total NaN values in row 11024 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11025 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11026 :- 0 and it's percentage : 0.0
 Total NaN values in row 11027 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11028 :- 0 and it's percentage : 0.0
 Total NaN values in row 11029 :- 0 and it's percentage : 0.0
 Total NaN values in row 11030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11031 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11032 :- 0 and it's percentage : 0.0
 Total NaN values in row 11033 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11034 :- 0 and it's percentage : 0.0
 Total NaN values in row 11035 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11036 :- 0 and it's percentage : 0.0
 Total NaN values in row 11037 :- 0 and it's percentage : 0.0
 Total NaN values in row 11038 :- 0 and it's percentage : 0.0
 Total NaN values in row 11039 :- 0 and it's percentage : 0.0
 Total NaN values in row 11040 :- 0 and it's percentage : 0.0
 Total NaN values in row 11041 :- 0 and it's percentage : 0.0
 Total NaN values in row 11042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11043 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11044 :- 0 and it's percentage : 0.0
 Total NaN values in row 11045 :- 0 and it's percentage : 0.0
 Total NaN values in row 11046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11047 :- 0 and it's percentage : 0.0
 Total NaN values in row 11048 :- 0 and it's percentage : 0.0
 Total NaN values in row 11049 :- 0 and it's percentage : 0.0
 Total NaN values in row 11050 :- 0 and it's percentage : 0.0
 Total NaN values in row 11051 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11052 :- 0 and it's percentage : 0.0
 Total NaN values in row 11053 :- 0 and it's percentage : 0.0
 Total NaN values in row 11054 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11055 :- 0 and it's percentage : 0.0
 Total NaN values in row 11056 :- 0 and it's percentage : 0.0
 Total NaN values in row 11057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11058 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11060 :- 0 and it's percentage : 0.0
 Total NaN values in row 11061 :- 0 and it's percentage : 0.0
 Total NaN values in row 11062 :- 0 and it's percentage : 0.0
 Total NaN values in row 11063 :- 0 and it's percentage : 0.0
 Total NaN values in row 11064 :- 0 and it's percentage : 0.0
 Total NaN values in row 11065 :- 0 and it's percentage : 0.0
 Total NaN values in row 11066 :- 0 and it's percentage : 0.0
 Total NaN values in row 11067 :- 0 and it's percentage : 0.0

 Total NaN values in row 11068 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11070 :- 0 and it's percentage : 0.0
 Total NaN values in row 11071 :- 0 and it's percentage : 0.0
 Total NaN values in row 11072 :- 0 and it's percentage : 0.0
 Total NaN values in row 11073 :- 0 and it's percentage : 0.0
 Total NaN values in row 11074 :- 0 and it's percentage : 0.0
 Total NaN values in row 11075 :- 0 and it's percentage : 0.0
 Total NaN values in row 11076 :- 0 and it's percentage : 0.0
 Total NaN values in row 11077 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11078 :- 0 and it's percentage : 0.0
 Total NaN values in row 11079 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11080 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11081 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11082 :- 0 and it's percentage : 0.0
 Total NaN values in row 11083 :- 0 and it's percentage : 0.0
 Total NaN values in row 11084 :- 0 and it's percentage : 0.0
 Total NaN values in row 11085 :- 0 and it's percentage : 0.0
 Total NaN values in row 11086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11087 :- 0 and it's percentage : 0.0
 Total NaN values in row 11088 :- 0 and it's percentage : 0.0
 Total NaN values in row 11089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11090 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11091 :- 0 and it's percentage : 0.0
 Total NaN values in row 11092 :- 0 and it's percentage : 0.0
 Total NaN values in row 11093 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11094 :- 0 and it's percentage : 0.0
 Total NaN values in row 11095 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11096 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11097 :- 0 and it's percentage : 0.0
 Total NaN values in row 11098 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11099 :- 0 and it's percentage : 0.0
 Total NaN values in row 11100 :- 0 and it's percentage : 0.0
 Total NaN values in row 11101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11102 :- 0 and it's percentage : 0.0
 Total NaN values in row 11103 :- 0 and it's percentage : 0.0
 Total NaN values in row 11104 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11105 :- 0 and it's percentage : 0.0
 Total NaN values in row 11106 :- 0 and it's percentage : 0.0
 Total NaN values in row 11107 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11108 :- 0 and it's percentage : 0.0
 Total NaN values in row 11109 :- 0 and it's percentage : 0.0
 Total NaN values in row 11110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11111 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11112 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11113 :- 0 and it's percentage : 0.0
 Total NaN values in row 11114 :- 0 and it's percentage : 0.0
 Total NaN values in row 11115 :- 0 and it's percentage : 0.0
 Total NaN values in row 11116 :- 0 and it's percentage : 0.0
 Total NaN values in row 11117 :- 0 and it's percentage : 0.0
 Total NaN values in row 11118 :- 0 and it's percentage : 0.0
 Total NaN values in row 11119 :- 0 and it's percentage : 0.0
 Total NaN values in row 11120 :- 0 and it's percentage : 0.0
 Total NaN values in row 11121 :- 0 and it's percentage : 0.0
 Total NaN values in row 11122 :- 0 and it's percentage : 0.0
 Total NaN values in row 11123 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11124 :- 0 and it's percentage : 0.0
 Total NaN values in row 11125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11126 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11127 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11129 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11130 :- 0 and it's percentage : 0.0
 Total NaN values in row 11131 :- 0 and it's percentage : 0.0
 Total NaN values in row 11132 :- 0 and it's percentage : 0.0
 Total NaN values in row 11133 :- 0 and it's percentage : 0.0
 Total NaN values in row 11134 :- 0 and it's percentage : 0.0
 Total NaN values in row 11135 :- 0 and it's percentage : 0.0
 Total NaN values in row 11136 :- 0 and it's percentage : 0.0
 Total NaN values in row 11137 :- 0 and it's percentage : 0.0
 Total NaN values in row 11138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11139 :- 0 and it's percentage : 0.0
 Total NaN values in row 11140 :- 0 and it's percentage : 0.0
 Total NaN values in row 11141 :- 0 and it's percentage : 0.0
 Total NaN values in row 11142 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11143 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11144 :- 0 and it's percentage : 0.0
 Total NaN values in row 11145 :- 0 and it's percentage : 0.0
 Total NaN values in row 11146 :- 0 and it's percentage : 0.0
 Total NaN values in row 11147 :- 0 and it's percentage : 0.0
 Total NaN values in row 11148 :- 0 and it's percentage : 0.0
 Total NaN values in row 11149 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11150 :- 0 and it's percentage : 0.0
 Total NaN values in row 11151 :- 0 and it's percentage : 0.0
 Total NaN values in row 11152 :- 0 and it's percentage : 0.0
 Total NaN values in row 11153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11154 :- 0 and it's percentage : 0.0
 Total NaN values in row 11155 :- 0 and it's percentage : 0.0
 Total NaN values in row 11156 :- 0 and it's percentage : 0.0
 Total NaN values in row 11157 :- 0 and it's percentage : 0.0
 Total NaN values in row 11158 :- 0 and it's percentage : 0.0
 Total NaN values in row 11159 :- 0 and it's percentage : 0.0
 Total NaN values in row 11160 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11161 :- 0 and it's percentage : 0.0
 Total NaN values in row 11162 :- 0 and it's percentage : 0.0
 Total NaN values in row 11163 :- 0 and it's percentage : 0.0
 Total NaN values in row 11164 :- 0 and it's percentage : 0.0
 Total NaN values in row 11165 :- 0 and it's percentage : 0.0
 Total NaN values in row 11166 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11167 :- 0 and it's percentage : 0.0
 Total NaN values in row 11168 :- 0 and it's percentage : 0.0
 Total NaN values in row 11169 :- 0 and it's percentage : 0.0
 Total NaN values in row 11170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11171 :- 0 and it's percentage : 0.0
 Total NaN values in row 11172 :- 0 and it's percentage : 0.0
 Total NaN values in row 11173 :- 0 and it's percentage : 0.0
 Total NaN values in row 11174 :- 0 and it's percentage : 0.0
 Total NaN values in row 11175 :- 0 and it's percentage : 0.0
 Total NaN values in row 11176 :- 0 and it's percentage : 0.0
 Total NaN values in row 11177 :- 0 and it's percentage : 0.0
 Total NaN values in row 11178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11180 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11182 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11183 :- 0 and it's percentage : 0.0
 Total NaN values in row 11184 :- 0 and it's percentage : 0.0
 Total NaN values in row 11185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11187 :- 0 and it's percentage : 0.0
 Total NaN values in row 11188 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11189 :- 0 and it's percentage : 0.0
 Total NaN values in row 11190 :- 0 and it's percentage : 0.0
 Total NaN values in row 11191 :- 0 and it's percentage : 0.0
 Total NaN values in row 11192 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 11193 :- 0 and it's percentage : 0.0
 Total NaN values in row 11194 :- 0 and it's percentage : 0.0
 Total NaN values in row 11195 :- 0 and it's percentage : 0.0
 Total NaN values in row 11196 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11197 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11198 :- 0 and it's percentage : 0.0
 Total NaN values in row 11199 :- 0 and it's percentage : 0.0
 Total NaN values in row 11200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11201 :- 0 and it's percentage : 0.0
 Total NaN values in row 11202 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11203 :- 0 and it's percentage : 0.0
 Total NaN values in row 11204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11205 :- 0 and it's percentage : 0.0
 Total NaN values in row 11206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11207 :- 0 and it's percentage : 0.0
 Total NaN values in row 11208 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11209 :- 0 and it's percentage : 0.0
 Total NaN values in row 11210 :- 0 and it's percentage : 0.0
 Total NaN values in row 11211 :- 0 and it's percentage : 0.0
 Total NaN values in row 11212 :- 0 and it's percentage : 0.0
 Total NaN values in row 11213 :- 0 and it's percentage : 0.0
 Total NaN values in row 11214 :- 0 and it's percentage : 0.0
 Total NaN values in row 11215 :- 0 and it's percentage : 0.0
 Total NaN values in row 11216 :- 0 and it's percentage : 0.0
 Total NaN values in row 11217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11218 :- 0 and it's percentage : 0.0
 Total NaN values in row 11219 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11220 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11221 :- 0 and it's percentage : 0.0
 Total NaN values in row 11222 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11223 :- 0 and it's percentage : 0.0
 Total NaN values in row 11224 :- 0 and it's percentage : 0.0
 Total NaN values in row 11225 :- 0 and it's percentage : 0.0
 Total NaN values in row 11226 :- 0 and it's percentage : 0.0

 Total NaN values in row 11227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11228 :- 0 and it's percentage : 0.0
 Total NaN values in row 11229 :- 0 and it's percentage : 0.0
 Total NaN values in row 11230 :- 0 and it's percentage : 0.0
 Total NaN values in row 11231 :- 0 and it's percentage : 0.0
 Total NaN values in row 11232 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11233 :- 0 and it's percentage : 0.0
 Total NaN values in row 11234 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11235 :- 0 and it's percentage : 0.0
 Total NaN values in row 11236 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11237 :- 0 and it's percentage : 0.0
 Total NaN values in row 11238 :- 0 and it's percentage : 0.0
 Total NaN values in row 11239 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11240 :- 0 and it's percentage : 0.0
 Total NaN values in row 11241 :- 0 and it's percentage : 0.0
 Total NaN values in row 11242 :- 0 and it's percentage : 0.0
 Total NaN values in row 11243 :- 0 and it's percentage : 0.0
 Total NaN values in row 11244 :- 0 and it's percentage : 0.0
 Total NaN values in row 11245 :- 0 and it's percentage : 0.0
 Total NaN values in row 11246 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11248 :- 0 and it's percentage : 0.0
 Total NaN values in row 11249 :- 0 and it's percentage : 0.0
 Total NaN values in row 11250 :- 0 and it's percentage : 0.0
 Total NaN values in row 11251 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11252 :- 0 and it's percentage : 0.0
 Total NaN values in row 11253 :- 0 and it's percentage : 0.0
 Total NaN values in row 11254 :- 0 and it's percentage : 0.0
 Total NaN values in row 11255 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11256 :- 0 and it's percentage : 0.0
 Total NaN values in row 11257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11258 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11259 :- 0 and it's percentage : 0.0
 Total NaN values in row 11260 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11261 :- 0 and it's percentage : 0.0
 Total NaN values in row 11262 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11263 :- 0 and it's percentage : 0.0
 Total NaN values in row 11264 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11265 :- 0 and it's percentage : 0.0
 Total NaN values in row 11266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11267 :- 0 and it's percentage : 0.0
 Total NaN values in row 11268 :- 0 and it's percentage : 0.0
 Total NaN values in row 11269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11271 :- 0 and it's percentage : 0.0
 Total NaN values in row 11272 :- 0 and it's percentage : 0.0
 Total NaN values in row 11273 :- 0 and it's percentage : 0.0
 Total NaN values in row 11274 :- 0 and it's percentage : 0.0
 Total NaN values in row 11275 :- 0 and it's percentage : 0.0
 Total NaN values in row 11276 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11277 :- 0 and it's percentage : 0.0
 Total NaN values in row 11278 :- 0 and it's percentage : 0.0
 Total NaN values in row 11279 :- 0 and it's percentage : 0.0
 Total NaN values in row 11280 :- 0 and it's percentage : 0.0
 Total NaN values in row 11281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11282 :- 0 and it's percentage : 0.0
 Total NaN values in row 11283 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11285 :- 0 and it's percentage : 0.0
 Total NaN values in row 11286 :- 0 and it's percentage : 0.0
 Total NaN values in row 11287 :- 0 and it's percentage : 0.0
 Total NaN values in row 11288 :- 0 and it's percentage : 0.0
 Total NaN values in row 11289 :- 0 and it's percentage : 0.0
 Total NaN values in row 11290 :- 0 and it's percentage : 0.0
 Total NaN values in row 11291 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11292 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11294 :- 0 and it's percentage : 0.0
 Total NaN values in row 11295 :- 0 and it's percentage : 0.0
 Total NaN values in row 11296 :- 0 and it's percentage : 0.0
 Total NaN values in row 11297 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11298 :- 0 and it's percentage : 0.0
 Total NaN values in row 11299 :- 0 and it's percentage : 0.0
 Total NaN values in row 11300 :- 0 and it's percentage : 0.0
 Total NaN values in row 11301 :- 0 and it's percentage : 0.0
 Total NaN values in row 11302 :- 0 and it's percentage : 0.0
 Total NaN values in row 11303 :- 0 and it's percentage : 0.0
 Total NaN values in row 11304 :- 0 and it's percentage : 0.0
 Total NaN values in row 11305 :- 0 and it's percentage : 0.0
 Total NaN values in row 11306 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11308 :- 0 and it's percentage : 0.0
 Total NaN values in row 11309 :- 0 and it's percentage : 0.0
 Total NaN values in row 11310 :- 0 and it's percentage : 0.0
 Total NaN values in row 11311 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11312 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11313 :- 0 and it's percentage : 0.0
 Total NaN values in row 11314 :- 0 and it's percentage : 0.0
 Total NaN values in row 11315 :- 0 and it's percentage : 0.0
 Total NaN values in row 11316 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11317 :- 0 and it's percentage : 0.0
 Total NaN values in row 11318 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11319 :- 0 and it's percentage : 0.0
 Total NaN values in row 11320 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11321 :- 0 and it's percentage : 0.0
 Total NaN values in row 11322 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11323 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11324 :- 0 and it's percentage : 0.0
 Total NaN values in row 11325 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11326 :- 0 and it's percentage : 0.0
 Total NaN values in row 11327 :- 0 and it's percentage : 0.0
 Total NaN values in row 11328 :- 0 and it's percentage : 0.0
 Total NaN values in row 11329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11330 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11331 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11332 :- 0 and it's percentage : 0.0
 Total NaN values in row 11333 :- 0 and it's percentage : 0.0
 Total NaN values in row 11334 :- 0 and it's percentage : 0.0
 Total NaN values in row 11335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11336 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11337 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11338 :- 0 and it's percentage : 0.0
 Total NaN values in row 11339 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11340 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11341 :- 0 and it's percentage : 0.0
 Total NaN values in row 11342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11343 :- 0 and it's percentage : 0.0
 Total NaN values in row 11344 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11345 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11346 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11347 :- 0 and it's percentage : 0.0
 Total NaN values in row 11348 :- 0 and it's percentage : 0.0
 Total NaN values in row 11349 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11350 :- 0 and it's percentage : 0.0
 Total NaN values in row 11351 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11352 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11353 :- 0 and it's percentage : 0.0
 Total NaN values in row 11354 :- 0 and it's percentage : 0.0
 Total NaN values in row 11355 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11356 :- 0 and it's percentage : 0.0
 Total NaN values in row 11357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11358 :- 0 and it's percentage : 0.0
 Total NaN values in row 11359 :- 0 and it's percentage : 0.0
 Total NaN values in row 11360 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11361 :- 0 and it's percentage : 0.0
 Total NaN values in row 11362 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11363 :- 0 and it's percentage : 0.0
 Total NaN values in row 11364 :- 0 and it's percentage : 0.0
 Total NaN values in row 11365 :- 0 and it's percentage : 0.0
 Total NaN values in row 11366 :- 0 and it's percentage : 0.0
 Total NaN values in row 11367 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11368 :- 0 and it's percentage : 0.0
 Total NaN values in row 11369 :- 0 and it's percentage : 0.0
 Total NaN values in row 11370 :- 0 and it's percentage : 0.0

 Total NaN values in row 11371 :- 0 and it's percentage : 0.0
 Total NaN values in row 11372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11373 :- 0 and it's percentage : 0.0
 Total NaN values in row 11374 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11376 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11377 :- 0 and it's percentage : 0.0
 Total NaN values in row 11378 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11379 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11380 :- 0 and it's percentage : 0.0
 Total NaN values in row 11381 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11382 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11383 :- 0 and it's percentage : 0.0
 Total NaN values in row 11384 :- 0 and it's percentage : 0.0
 Total NaN values in row 11385 :- 0 and it's percentage : 0.0
 Total NaN values in row 11386 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11387 :- 0 and it's percentage : 0.0
 Total NaN values in row 11388 :- 0 and it's percentage : 0.0
 Total NaN values in row 11389 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11390 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11391 :- 0 and it's percentage : 0.0
 Total NaN values in row 11392 :- 0 and it's percentage : 0.0
 Total NaN values in row 11393 :- 0 and it's percentage : 0.0
 Total NaN values in row 11394 :- 0 and it's percentage : 0.0
 Total NaN values in row 11395 :- 0 and it's percentage : 0.0
 Total NaN values in row 11396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11397 :- 0 and it's percentage : 0.0
 Total NaN values in row 11398 :- 0 and it's percentage : 0.0
 Total NaN values in row 11399 :- 0 and it's percentage : 0.0
 Total NaN values in row 11400 :- 0 and it's percentage : 0.0
 Total NaN values in row 11401 :- 0 and it's percentage : 0.0
 Total NaN values in row 11402 :- 0 and it's percentage : 0.0
 Total NaN values in row 11403 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11404 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11405 :- 0 and it's percentage : 0.0
 Total NaN values in row 11406 :- 0 and it's percentage : 0.0
 Total NaN values in row 11407 :- 0 and it's percentage : 0.0
 Total NaN values in row 11408 :- 0 and it's percentage : 0.0
 Total NaN values in row 11409 :- 0 and it's percentage : 0.0
 Total NaN values in row 11410 :- 0 and it's percentage : 0.0
 Total NaN values in row 11411 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11412 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11413 :- 0 and it's percentage : 0.0
 Total NaN values in row 11414 :- 0 and it's percentage : 0.0
 Total NaN values in row 11415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11416 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11417 :- 0 and it's percentage : 0.0
 Total NaN values in row 11418 :- 0 and it's percentage : 0.0
 Total NaN values in row 11419 :- 0 and it's percentage : 0.0
 Total NaN values in row 11420 :- 0 and it's percentage : 0.0
 Total NaN values in row 11421 :- 0 and it's percentage : 0.0
 Total NaN values in row 11422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11423 :- 0 and it's percentage : 0.0
 Total NaN values in row 11424 :- 0 and it's percentage : 0.0
 Total NaN values in row 11425 :- 0 and it's percentage : 0.0
 Total NaN values in row 11426 :- 0 and it's percentage : 0.0
 Total NaN values in row 11427 :- 0 and it's percentage : 0.0
 Total NaN values in row 11428 :- 0 and it's percentage : 0.0
 Total NaN values in row 11429 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11430 :- 0 and it's percentage : 0.0
 Total NaN values in row 11431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11434 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11435 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11436 :- 0 and it's percentage : 0.0
 Total NaN values in row 11437 :- 0 and it's percentage : 0.0
 Total NaN values in row 11438 :- 0 and it's percentage : 0.0
 Total NaN values in row 11439 :- 0 and it's percentage : 0.0
 Total NaN values in row 11440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11441 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11443 :- 0 and it's percentage : 0.0
 Total NaN values in row 11444 :- 0 and it's percentage : 0.0
 Total NaN values in row 11445 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11446 :- 0 and it's percentage : 0.0
 Total NaN values in row 11447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11449 :- 0 and it's percentage : 0.0
 Total NaN values in row 11450 :- 0 and it's percentage : 0.0
 Total NaN values in row 11451 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11452 :- 0 and it's percentage : 0.0
 Total NaN values in row 11453 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11454 :- 0 and it's percentage : 0.0
 Total NaN values in row 11455 :- 0 and it's percentage : 0.0
 Total NaN values in row 11456 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11457 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11458 :- 0 and it's percentage : 0.0
 Total NaN values in row 11459 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11460 :- 0 and it's percentage : 0.0
 Total NaN values in row 11461 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11462 :- 0 and it's percentage : 0.0
 Total NaN values in row 11463 :- 0 and it's percentage : 0.0
 Total NaN values in row 11464 :- 0 and it's percentage : 0.0
 Total NaN values in row 11465 :- 0 and it's percentage : 0.0
 Total NaN values in row 11466 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11467 :- 0 and it's percentage : 0.0
 Total NaN values in row 11468 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11469 :- 0 and it's percentage : 0.0
 Total NaN values in row 11470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11471 :- 0 and it's percentage : 0.0
 Total NaN values in row 11472 :- 0 and it's percentage : 0.0
 Total NaN values in row 11473 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11474 :- 0 and it's percentage : 0.0
 Total NaN values in row 11475 :- 0 and it's percentage : 0.0
 Total NaN values in row 11476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11478 :- 0 and it's percentage : 0.0
 Total NaN values in row 11479 :- 0 and it's percentage : 0.0
 Total NaN values in row 11480 :- 0 and it's percentage : 0.0
 Total NaN values in row 11481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11482 :- 0 and it's percentage : 0.0
 Total NaN values in row 11483 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11486 :- 0 and it's percentage : 0.0
 Total NaN values in row 11487 :- 0 and it's percentage : 0.0
 Total NaN values in row 11488 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11489 :- 0 and it's percentage : 0.0
 Total NaN values in row 11490 :- 0 and it's percentage : 0.0
 Total NaN values in row 11491 :- 0 and it's percentage : 0.0
 Total NaN values in row 11492 :- 0 and it's percentage : 0.0
 Total NaN values in row 11493 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11494 :- 0 and it's percentage : 0.0
 Total NaN values in row 11495 :- 0 and it's percentage : 0.0
 Total NaN values in row 11496 :- 0 and it's percentage : 0.0
 Total NaN values in row 11497 :- 0 and it's percentage : 0.0
 Total NaN values in row 11498 :- 0 and it's percentage : 0.0
 Total NaN values in row 11499 :- 0 and it's percentage : 0.0

 Total NaN values in row 11500 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11501 :- 0 and it's percentage : 0.0
 Total NaN values in row 11502 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11503 :- 0 and it's percentage : 0.0
 Total NaN values in row 11504 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11505 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11506 :- 0 and it's percentage : 0.0
 Total NaN values in row 11507 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11508 :- 0 and it's percentage : 0.0
 Total NaN values in row 11509 :- 0 and it's percentage : 0.0
 Total NaN values in row 11510 :- 0 and it's percentage : 0.0
 Total NaN values in row 11511 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11512 :- 0 and it's percentage : 0.0
 Total NaN values in row 11513 :- 0 and it's percentage : 0.0
 Total NaN values in row 11514 :- 0 and it's percentage : 0.0
 Total NaN values in row 11515 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11517 :- 0 and it's percentage : 0.0
 Total NaN values in row 11518 :- 0 and it's percentage : 0.0
 Total NaN values in row 11519 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11520 :- 0 and it's percentage : 0.0
 Total NaN values in row 11521 :- 0 and it's percentage : 0.0
 Total NaN values in row 11522 :- 0 and it's percentage : 0.0
 Total NaN values in row 11523 :- 0 and it's percentage : 0.0
 Total NaN values in row 11524 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11525 :- 0 and it's percentage : 0.0
 Total NaN values in row 11526 :- 0 and it's percentage : 0.0
 Total NaN values in row 11527 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11528 :- 0 and it's percentage : 0.0
 Total NaN values in row 11529 :- 0 and it's percentage : 0.0
 Total NaN values in row 11530 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11531 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11532 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11534 :- 0 and it's percentage : 0.0
 Total NaN values in row 11535 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11537 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11538 :- 0 and it's percentage : 0.0
 Total NaN values in row 11539 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11540 :- 0 and it's percentage : 0.0
 Total NaN values in row 11541 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11542 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11543 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11544 :- 0 and it's percentage : 0.0
 Total NaN values in row 11545 :- 0 and it's percentage : 0.0
 Total NaN values in row 11546 :- 0 and it's percentage : 0.0
 Total NaN values in row 11547 :- 0 and it's percentage : 0.0
 Total NaN values in row 11548 :- 0 and it's percentage : 0.0
 Total NaN values in row 11549 :- 0 and it's percentage : 0.0
 Total NaN values in row 11550 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11551 :- 0 and it's percentage : 0.0
 Total NaN values in row 11552 :- 0 and it's percentage : 0.0
 Total NaN values in row 11553 :- 0 and it's percentage : 0.0
 Total NaN values in row 11554 :- 0 and it's percentage : 0.0
 Total NaN values in row 11555 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11556 :- 0 and it's percentage : 0.0
 Total NaN values in row 11557 :- 0 and it's percentage : 0.0
 Total NaN values in row 11558 :- 0 and it's percentage : 0.0
 Total NaN values in row 11559 :- 0 and it's percentage : 0.0
 Total NaN values in row 11560 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11561 :- 0 and it's percentage : 0.0
 Total NaN values in row 11562 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11563 :- 0 and it's percentage : 0.0
 Total NaN values in row 11564 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11566 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11567 :- 0 and it's percentage : 0.0
 Total NaN values in row 11568 :- 0 and it's percentage : 0.0
 Total NaN values in row 11569 :- 0 and it's percentage : 0.0
 Total NaN values in row 11570 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11571 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11572 :- 0 and it's percentage : 0.0
 Total NaN values in row 11573 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11574 :- 0 and it's percentage : 0.0
 Total NaN values in row 11575 :- 0 and it's percentage : 0.0
 Total NaN values in row 11576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11577 :- 0 and it's percentage : 0.0
 Total NaN values in row 11578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11579 :- 0 and it's percentage : 0.0
 Total NaN values in row 11580 :- 0 and it's percentage : 0.0
 Total NaN values in row 11581 :- 0 and it's percentage : 0.0
 Total NaN values in row 11582 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11583 :- 0 and it's percentage : 0.0
 Total NaN values in row 11584 :- 0 and it's percentage : 0.0
 Total NaN values in row 11585 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11586 :- 0 and it's percentage : 0.0
 Total NaN values in row 11587 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11588 :- 0 and it's percentage : 0.0
 Total NaN values in row 11589 :- 0 and it's percentage : 0.0
 Total NaN values in row 11590 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11591 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11592 :- 0 and it's percentage : 0.0
 Total NaN values in row 11593 :- 0 and it's percentage : 0.0
 Total NaN values in row 11594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11595 :- 0 and it's percentage : 0.0
 Total NaN values in row 11596 :- 0 and it's percentage : 0.0
 Total NaN values in row 11597 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11598 :- 0 and it's percentage : 0.0
 Total NaN values in row 11599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11600 :- 0 and it's percentage : 0.0
 Total NaN values in row 11601 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11602 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11603 :- 0 and it's percentage : 0.0
 Total NaN values in row 11604 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11605 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11606 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11608 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11609 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11610 :- 0 and it's percentage : 0.0
 Total NaN values in row 11611 :- 0 and it's percentage : 0.0
 Total NaN values in row 11612 :- 0 and it's percentage : 0.0
 Total NaN values in row 11613 :- 0 and it's percentage : 0.0
 Total NaN values in row 11614 :- 0 and it's percentage : 0.0
 Total NaN values in row 11615 :- 0 and it's percentage : 0.0
 Total NaN values in row 11616 :- 0 and it's percentage : 0.0
 Total NaN values in row 11617 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11618 :- 0 and it's percentage : 0.0
 Total NaN values in row 11619 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 11620 :- 0 and it's percentage : 0.0
 Total NaN values in row 11621 :- 0 and it's percentage : 0.0
 Total NaN values in row 11622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11624 :- 0 and it's percentage : 0.0
 Total NaN values in row 11625 :- 0 and it's percentage : 0.0
 Total NaN values in row 11626 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11627 :- 0 and it's percentage : 0.0
 Total NaN values in row 11628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11629 :- 0 and it's percentage : 0.0
 Total NaN values in row 11630 :- 0 and it's percentage : 0.0
 Total NaN values in row 11631 :- 0 and it's percentage : 0.0
 Total NaN values in row 11632 :- 0 and it's percentage : 0.0
 Total NaN values in row 11633 :- 0 and it's percentage : 0.0
 Total NaN values in row 11634 :- 0 and it's percentage : 0.0
 Total NaN values in row 11635 :- 0 and it's percentage : 0.0
 Total NaN values in row 11636 :- 0 and it's percentage : 0.0
 Total NaN values in row 11637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11638 :- 0 and it's percentage : 0.0
 Total NaN values in row 11639 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11641 :- 0 and it's percentage : 0.0
 Total NaN values in row 11642 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11643 :- 0 and it's percentage : 0.0
 Total NaN values in row 11644 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11645 :- 0 and it's percentage : 0.0
 Total NaN values in row 11646 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11647 :- 0 and it's percentage : 0.0
 Total NaN values in row 11648 :- 0 and it's percentage : 0.0
 Total NaN values in row 11649 :- 0 and it's percentage : 0.0
 Total NaN values in row 11650 :- 0 and it's percentage : 0.0
 Total NaN values in row 11651 :- 0 and it's percentage : 0.0
 Total NaN values in row 11652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11653 :- 0 and it's percentage : 0.0
 Total NaN values in row 11654 :- 0 and it's percentage : 0.0
 Total NaN values in row 11655 :- 0 and it's percentage : 0.0
 Total NaN values in row 11656 :- 0 and it's percentage : 0.0
 Total NaN values in row 11657 :- 0 and it's percentage : 0.0
 Total NaN values in row 11658 :- 0 and it's percentage : 0.0
 Total NaN values in row 11659 :- 0 and it's percentage : 0.0
 Total NaN values in row 11660 :- 0 and it's percentage : 0.0
 Total NaN values in row 11661 :- 0 and it's percentage : 0.0
 Total NaN values in row 11662 :- 0 and it's percentage : 0.0
 Total NaN values in row 11663 :- 0 and it's percentage : 0.0
 Total NaN values in row 11664 :- 0 and it's percentage : 0.0
 Total NaN values in row 11665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11666 :- 0 and it's percentage : 0.0
 Total NaN values in row 11667 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11668 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11669 :- 0 and it's percentage : 0.0
 Total NaN values in row 11670 :- 0 and it's percentage : 0.0
 Total NaN values in row 11671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11673 :- 0 and it's percentage : 0.0
 Total NaN values in row 11674 :- 0 and it's percentage : 0.0
 Total NaN values in row 11675 :- 0 and it's percentage : 0.0
 Total NaN values in row 11676 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11677 :- 0 and it's percentage : 0.0
 Total NaN values in row 11678 :- 0 and it's percentage : 0.0
 Total NaN values in row 11679 :- 0 and it's percentage : 0.0
 Total NaN values in row 11680 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11681 :- 0 and it's percentage : 0.0
 Total NaN values in row 11682 :- 0 and it's percentage : 0.0
 Total NaN values in row 11683 :- 0 and it's percentage : 0.0
 Total NaN values in row 11684 :- 0 and it's percentage : 0.0
 Total NaN values in row 11685 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11686 :- 0 and it's percentage : 0.0
 Total NaN values in row 11687 :- 0 and it's percentage : 0.0
 Total NaN values in row 11688 :- 0 and it's percentage : 0.0
 Total NaN values in row 11689 :- 0 and it's percentage : 0.0
 Total NaN values in row 11690 :- 0 and it's percentage : 0.0
 Total NaN values in row 11691 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11692 :- 0 and it's percentage : 0.0
 Total NaN values in row 11693 :- 0 and it's percentage : 0.0
 Total NaN values in row 11694 :- 0 and it's percentage : 0.0
 Total NaN values in row 11695 :- 0 and it's percentage : 0.0
 Total NaN values in row 11696 :- 0 and it's percentage : 0.0
 Total NaN values in row 11697 :- 0 and it's percentage : 0.0
 Total NaN values in row 11698 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11699 :- 0 and it's percentage : 0.0
 Total NaN values in row 11700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11701 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11702 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11703 :- 0 and it's percentage : 0.0
 Total NaN values in row 11704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11705 :- 0 and it's percentage : 0.0
 Total NaN values in row 11706 :- 0 and it's percentage : 0.0
 Total NaN values in row 11707 :- 0 and it's percentage : 0.0
 Total NaN values in row 11708 :- 0 and it's percentage : 0.0
 Total NaN values in row 11709 :- 0 and it's percentage : 0.0
 Total NaN values in row 11710 :- 0 and it's percentage : 0.0
 Total NaN values in row 11711 :- 0 and it's percentage : 0.0
 Total NaN values in row 11712 :- 0 and it's percentage : 0.0
 Total NaN values in row 11713 :- 0 and it's percentage : 0.0
 Total NaN values in row 11714 :- 0 and it's percentage : 0.0
 Total NaN values in row 11715 :- 0 and it's percentage : 0.0
 Total NaN values in row 11716 :- 0 and it's percentage : 0.0
 Total NaN values in row 11717 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11718 :- 0 and it's percentage : 0.0
 Total NaN values in row 11719 :- 0 and it's percentage : 0.0
 Total NaN values in row 11720 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11722 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11723 :- 0 and it's percentage : 0.0
 Total NaN values in row 11724 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11725 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11726 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11727 :- 0 and it's percentage : 0.0
 Total NaN values in row 11728 :- 0 and it's percentage : 0.0
 Total NaN values in row 11729 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11730 :- 0 and it's percentage : 0.0
 Total NaN values in row 11731 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11732 :- 0 and it's percentage : 0.0
 Total NaN values in row 11733 :- 0 and it's percentage : 0.0
 Total NaN values in row 11734 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11735 :- 0 and it's percentage : 0.0
 Total NaN values in row 11736 :- 0 and it's percentage : 0.0
 Total NaN values in row 11737 :- 0 and it's percentage : 0.0
 Total NaN values in row 11738 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11739 :- 0 and it's percentage : 0.0
 Total NaN values in row 11740 :- 0 and it's percentage : 0.0
 Total NaN values in row 11741 :- 0 and it's percentage : 0.0
 Total NaN values in row 11742 :- 0 and it's percentage : 0.0
 Total NaN values in row 11743 :- 0 and it's percentage : 0.0
 Total NaN values in row 11744 :- 0 and it's percentage : 0.0
 Total NaN values in row 11745 :- 0 and it's percentage : 0.0
 Total NaN values in row 11746 :- 0 and it's percentage : 0.0
 Total NaN values in row 11747 :- 0 and it's percentage : 0.0
 Total NaN values in row 11748 :- 0 and it's percentage : 0.0
 Total NaN values in row 11749 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11750 :- 0 and it's percentage : 0.0
 Total NaN values in row 11751 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11752 :- 0 and it's percentage : 0.0
 Total NaN values in row 11753 :- 0 and it's percentage : 0.0
 Total NaN values in row 11754 :- 0 and it's percentage : 0.0
 Total NaN values in row 11755 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11756 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 11757 :- 0 and it's percentage : 0.0
 Total NaN values in row 11758 :- 0 and it's percentage : 0.0
 Total NaN values in row 11759 :- 0 and it's percentage : 0.0
 Total NaN values in row 11760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11761 :- 0 and it's percentage : 0.0
 Total NaN values in row 11762 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11763 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11764 :- 0 and it's percentage : 0.0
 Total NaN values in row 11765 :- 0 and it's percentage : 0.0
 Total NaN values in row 11766 :- 0 and it's percentage : 0.0
 Total NaN values in row 11767 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11768 :- 0 and it's percentage : 0.0
 Total NaN values in row 11769 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11770 :- 0 and it's percentage : 0.0
 Total NaN values in row 11771 :- 0 and it's percentage : 0.0
 Total NaN values in row 11772 :- 0 and it's percentage : 0.0
 Total NaN values in row 11773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11774 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11775 :- 0 and it's percentage : 0.0
 Total NaN values in row 11776 :- 0 and it's percentage : 0.0
 Total NaN values in row 11777 :- 0 and it's percentage : 0.0
 Total NaN values in row 11778 :- 0 and it's percentage : 0.0
 Total NaN values in row 11779 :- 0 and it's percentage : 0.0
 Total NaN values in row 11780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11782 :- 0 and it's percentage : 0.0
 Total NaN values in row 11783 :- 0 and it's percentage : 0.0
 Total NaN values in row 11784 :- 0 and it's percentage : 0.0
 Total NaN values in row 11785 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11786 :- 0 and it's percentage : 0.0
 Total NaN values in row 11787 :- 0 and it's percentage : 0.0
 Total NaN values in row 11788 :- 0 and it's percentage : 0.0
 Total NaN values in row 11789 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11790 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11791 :- 0 and it's percentage : 0.0
 Total NaN values in row 11792 :- 0 and it's percentage : 0.0
 Total NaN values in row 11793 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11794 :- 0 and it's percentage : 0.0
 Total NaN values in row 11795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11796 :- 0 and it's percentage : 0.0
 Total NaN values in row 11797 :- 0 and it's percentage : 0.0
 Total NaN values in row 11798 :- 0 and it's percentage : 0.0
 Total NaN values in row 11799 :- 0 and it's percentage : 0.0
 Total NaN values in row 11800 :- 0 and it's percentage : 0.0
 Total NaN values in row 11801 :- 0 and it's percentage : 0.0
 Total NaN values in row 11802 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11803 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11804 :- 0 and it's percentage : 0.0
 Total NaN values in row 11805 :- 0 and it's percentage : 0.0
 Total NaN values in row 11806 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11807 :- 0 and it's percentage : 0.0
 Total NaN values in row 11808 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11809 :- 0 and it's percentage : 0.0
 Total NaN values in row 11810 :- 0 and it's percentage : 0.0
 Total NaN values in row 11811 :- 0 and it's percentage : 0.0
 Total NaN values in row 11812 :- 0 and it's percentage : 0.0
 Total NaN values in row 11813 :- 0 and it's percentage : 0.0
 Total NaN values in row 11814 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11815 :- 0 and it's percentage : 0.0
 Total NaN values in row 11816 :- 0 and it's percentage : 0.0
 Total NaN values in row 11817 :- 0 and it's percentage : 0.0
 Total NaN values in row 11818 :- 0 and it's percentage : 0.0
 Total NaN values in row 11819 :- 0 and it's percentage : 0.0
 Total NaN values in row 11820 :- 0 and it's percentage : 0.0
 Total NaN values in row 11821 :- 0 and it's percentage : 0.0
 Total NaN values in row 11822 :- 0 and it's percentage : 0.0
 Total NaN values in row 11823 :- 0 and it's percentage : 0.0
 Total NaN values in row 11824 :- 0 and it's percentage : 0.0
 Total NaN values in row 11825 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11826 :- 0 and it's percentage : 0.0
 Total NaN values in row 11827 :- 0 and it's percentage : 0.0
 Total NaN values in row 11828 :- 0 and it's percentage : 0.0
 Total NaN values in row 11829 :- 0 and it's percentage : 0.0
 Total NaN values in row 11830 :- 0 and it's percentage : 0.0
 Total NaN values in row 11831 :- 0 and it's percentage : 0.0
 Total NaN values in row 11832 :- 0 and it's percentage : 0.0
 Total NaN values in row 11833 :- 0 and it's percentage : 0.0
 Total NaN values in row 11834 :- 0 and it's percentage : 0.0
 Total NaN values in row 11835 :- 0 and it's percentage : 0.0
 Total NaN values in row 11836 :- 0 and it's percentage : 0.0
 Total NaN values in row 11837 :- 0 and it's percentage : 0.0
 Total NaN values in row 11838 :- 0 and it's percentage : 0.0
 Total NaN values in row 11839 :- 0 and it's percentage : 0.0
 Total NaN values in row 11840 :- 0 and it's percentage : 0.0
 Total NaN values in row 11841 :- 0 and it's percentage : 0.0
 Total NaN values in row 11842 :- 0 and it's percentage : 0.0
 Total NaN values in row 11843 :- 0 and it's percentage : 0.0
 Total NaN values in row 11844 :- 0 and it's percentage : 0.0
 Total NaN values in row 11845 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11846 :- 0 and it's percentage : 0.0
 Total NaN values in row 11847 :- 0 and it's percentage : 0.0
 Total NaN values in row 11848 :- 0 and it's percentage : 0.0
 Total NaN values in row 11849 :- 0 and it's percentage : 0.0
 Total NaN values in row 11850 :- 0 and it's percentage : 0.0
 Total NaN values in row 11851 :- 0 and it's percentage : 0.0
 Total NaN values in row 11852 :- 0 and it's percentage : 0.0
 Total NaN values in row 11853 :- 0 and it's percentage : 0.0
 Total NaN values in row 11854 :- 0 and it's percentage : 0.0
 Total NaN values in row 11855 :- 0 and it's percentage : 0.0
 Total NaN values in row 11856 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11857 :- 0 and it's percentage : 0.0
 Total NaN values in row 11858 :- 0 and it's percentage : 0.0
 Total NaN values in row 11859 :- 0 and it's percentage : 0.0
 Total NaN values in row 11860 :- 0 and it's percentage : 0.0
 Total NaN values in row 11861 :- 0 and it's percentage : 0.0
 Total NaN values in row 11862 :- 0 and it's percentage : 0.0
 Total NaN values in row 11863 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11864 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11865 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11866 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11867 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11868 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11869 :- 0 and it's percentage : 0.0
 Total NaN values in row 11870 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11872 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11873 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11874 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11875 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11876 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11877 :- 0 and it's percentage : 0.0
 Total NaN values in row 11878 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11879 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11880 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11881 :- 0 and it's percentage : 0.0
 Total NaN values in row 11882 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11883 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11884 :- 0 and it's percentage : 0.0
 Total NaN values in row 11885 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11886 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11887 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 11888 :- 0 and it's percentage : 0.0
 Total NaN values in row 11889 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11890 :- 0 and it's percentage : 0.0
 Total NaN values in row 11891 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11892 :- 0 and it's percentage : 0.0

 Total NaN values in row 11893 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11894 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11895 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11896 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11899 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11900 :- 0 and it's percentage : 0.0
 Total NaN values in row 11901 :- 0 and it's percentage : 0.0
 Total NaN values in row 11902 :- 0 and it's percentage : 0.0
 Total NaN values in row 11903 :- 0 and it's percentage : 0.0
 Total NaN values in row 11904 :- 0 and it's percentage : 0.0
 Total NaN values in row 11905 :- 0 and it's percentage : 0.0
 Total NaN values in row 11906 :- 0 and it's percentage : 0.0
 Total NaN values in row 11907 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11908 :- 0 and it's percentage : 0.0
 Total NaN values in row 11909 :- 0 and it's percentage : 0.0
 Total NaN values in row 11910 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11911 :- 0 and it's percentage : 0.0
 Total NaN values in row 11912 :- 0 and it's percentage : 0.0
 Total NaN values in row 11913 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11915 :- 0 and it's percentage : 0.0
 Total NaN values in row 11916 :- 0 and it's percentage : 0.0
 Total NaN values in row 11917 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11918 :- 0 and it's percentage : 0.0
 Total NaN values in row 11919 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11920 :- 0 and it's percentage : 0.0
 Total NaN values in row 11921 :- 0 and it's percentage : 0.0
 Total NaN values in row 11922 :- 0 and it's percentage : 0.0
 Total NaN values in row 11923 :- 0 and it's percentage : 0.0
 Total NaN values in row 11924 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11925 :- 0 and it's percentage : 0.0
 Total NaN values in row 11926 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11927 :- 0 and it's percentage : 0.0
 Total NaN values in row 11928 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11929 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11930 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11932 :- 0 and it's percentage : 0.0
 Total NaN values in row 11933 :- 0 and it's percentage : 0.0
 Total NaN values in row 11934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11935 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11936 :- 0 and it's percentage : 0.0
 Total NaN values in row 11937 :- 0 and it's percentage : 0.0
 Total NaN values in row 11938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11939 :- 0 and it's percentage : 0.0
 Total NaN values in row 11940 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11941 :- 0 and it's percentage : 0.0
 Total NaN values in row 11942 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11943 :- 0 and it's percentage : 0.0
 Total NaN values in row 11944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11946 :- 0 and it's percentage : 0.0
 Total NaN values in row 11947 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11948 :- 0 and it's percentage : 0.0
 Total NaN values in row 11949 :- 0 and it's percentage : 0.0
 Total NaN values in row 11950 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11951 :- 0 and it's percentage : 0.0
 Total NaN values in row 11952 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11953 :- 0 and it's percentage : 0.0
 Total NaN values in row 11954 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11955 :- 0 and it's percentage : 0.0
 Total NaN values in row 11956 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11957 :- 0 and it's percentage : 0.0
 Total NaN values in row 11958 :- 0 and it's percentage : 0.0
 Total NaN values in row 11959 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11960 :- 0 and it's percentage : 0.0
 Total NaN values in row 11961 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11962 :- 0 and it's percentage : 0.0
 Total NaN values in row 11963 :- 0 and it's percentage : 0.0
 Total NaN values in row 11964 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11965 :- 0 and it's percentage : 0.0
 Total NaN values in row 11966 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11967 :- 0 and it's percentage : 0.0
 Total NaN values in row 11968 :- 0 and it's percentage : 0.0
 Total NaN values in row 11969 :- 0 and it's percentage : 0.0
 Total NaN values in row 11970 :- 0 and it's percentage : 0.0
 Total NaN values in row 11971 :- 0 and it's percentage : 0.0
 Total NaN values in row 11972 :- 0 and it's percentage : 0.0
 Total NaN values in row 11973 :- 0 and it's percentage : 0.0
 Total NaN values in row 11974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11975 :- 0 and it's percentage : 0.0
 Total NaN values in row 11976 :- 0 and it's percentage : 0.0
 Total NaN values in row 11977 :- 0 and it's percentage : 0.0
 Total NaN values in row 11978 :- 0 and it's percentage : 0.0
 Total NaN values in row 11979 :- 0 and it's percentage : 0.0
 Total NaN values in row 11980 :- 0 and it's percentage : 0.0
 Total NaN values in row 11981 :- 0 and it's percentage : 0.0
 Total NaN values in row 11982 :- 0 and it's percentage : 0.0
 Total NaN values in row 11983 :- 0 and it's percentage : 0.0
 Total NaN values in row 11984 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11985 :- 0 and it's percentage : 0.0
 Total NaN values in row 11986 :- 0 and it's percentage : 0.0
 Total NaN values in row 11987 :- 0 and it's percentage : 0.0
 Total NaN values in row 11988 :- 0 and it's percentage : 0.0
 Total NaN values in row 11989 :- 0 and it's percentage : 0.0
 Total NaN values in row 11990 :- 0 and it's percentage : 0.0
 Total NaN values in row 11991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11992 :- 0 and it's percentage : 0.0
 Total NaN values in row 11993 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11994 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11995 :- 0 and it's percentage : 0.0
 Total NaN values in row 11996 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 11997 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 11998 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 11999 :- 0 and it's percentage : 0.0
 Total NaN values in row 12000 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12001 :- 0 and it's percentage : 0.0
 Total NaN values in row 12002 :- 0 and it's percentage : 0.0
 Total NaN values in row 12003 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12004 :- 0 and it's percentage : 0.0
 Total NaN values in row 12005 :- 0 and it's percentage : 0.0
 Total NaN values in row 12006 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12007 :- 0 and it's percentage : 0.0
 Total NaN values in row 12008 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12010 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12011 :- 0 and it's percentage : 0.0
 Total NaN values in row 12012 :- 0 and it's percentage : 0.0
 Total NaN values in row 12013 :- 0 and it's percentage : 0.0

 Total NaN values in row 12014 :- 0 and it's percentage : 0.0
 Total NaN values in row 12015 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12016 :- 0 and it's percentage : 0.0
 Total NaN values in row 12017 :- 0 and it's percentage : 0.0
 Total NaN values in row 12018 :- 0 and it's percentage : 0.0
 Total NaN values in row 12019 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12020 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12021 :- 0 and it's percentage : 0.0
 Total NaN values in row 12022 :- 0 and it's percentage : 0.0
 Total NaN values in row 12023 :- 0 and it's percentage : 0.0
 Total NaN values in row 12024 :- 0 and it's percentage : 0.0
 Total NaN values in row 12025 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12026 :- 0 and it's percentage : 0.0
 Total NaN values in row 12027 :- 0 and it's percentage : 0.0
 Total NaN values in row 12028 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12029 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12030 :- 0 and it's percentage : 0.0
 Total NaN values in row 12031 :- 0 and it's percentage : 0.0
 Total NaN values in row 12032 :- 0 and it's percentage : 0.0
 Total NaN values in row 12033 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12034 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12035 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12036 :- 0 and it's percentage : 0.0
 Total NaN values in row 12037 :- 0 and it's percentage : 0.0
 Total NaN values in row 12038 :- 0 and it's percentage : 0.0
 Total NaN values in row 12039 :- 0 and it's percentage : 0.0
 Total NaN values in row 12040 :- 0 and it's percentage : 0.0
 Total NaN values in row 12041 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12043 :- 0 and it's percentage : 0.0
 Total NaN values in row 12044 :- 0 and it's percentage : 0.0
 Total NaN values in row 12045 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12046 :- 0 and it's percentage : 0.0
 Total NaN values in row 12047 :- 0 and it's percentage : 0.0
 Total NaN values in row 12048 :- 0 and it's percentage : 0.0
 Total NaN values in row 12049 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12050 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12051 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12052 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12053 :- 0 and it's percentage : 0.0
 Total NaN values in row 12054 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12055 :- 0 and it's percentage : 0.0
 Total NaN values in row 12056 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12057 :- 0 and it's percentage : 0.0
 Total NaN values in row 12058 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12059 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12060 :- 0 and it's percentage : 0.0
 Total NaN values in row 12061 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12062 :- 0 and it's percentage : 0.0
 Total NaN values in row 12063 :- 0 and it's percentage : 0.0
 Total NaN values in row 12064 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12065 :- 0 and it's percentage : 0.0
 Total NaN values in row 12066 :- 0 and it's percentage : 0.0
 Total NaN values in row 12067 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12068 :- 0 and it's percentage : 0.0
 Total NaN values in row 12069 :- 0 and it's percentage : 0.0
 Total NaN values in row 12070 :- 0 and it's percentage : 0.0
 Total NaN values in row 12071 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12072 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12073 :- 0 and it's percentage : 0.0
 Total NaN values in row 12074 :- 0 and it's percentage : 0.0
 Total NaN values in row 12075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12076 :- 0 and it's percentage : 0.0
 Total NaN values in row 12077 :- 0 and it's percentage : 0.0
 Total NaN values in row 12078 :- 0 and it's percentage : 0.0
 Total NaN values in row 12079 :- 0 and it's percentage : 0.0
 Total NaN values in row 12080 :- 0 and it's percentage : 0.0
 Total NaN values in row 12081 :- 0 and it's percentage : 0.0
 Total NaN values in row 12082 :- 0 and it's percentage : 0.0
 Total NaN values in row 12083 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12084 :- 0 and it's percentage : 0.0
 Total NaN values in row 12085 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12086 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12087 :- 0 and it's percentage : 0.0
 Total NaN values in row 12088 :- 0 and it's percentage : 0.0
 Total NaN values in row 12089 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12090 :- 0 and it's percentage : 0.0
 Total NaN values in row 12091 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12092 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12093 :- 0 and it's percentage : 0.0
 Total NaN values in row 12094 :- 0 and it's percentage : 0.0
 Total NaN values in row 12095 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12096 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12097 :- 0 and it's percentage : 0.0
 Total NaN values in row 12098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12099 :- 0 and it's percentage : 0.0
 Total NaN values in row 12100 :- 0 and it's percentage : 0.0
 Total NaN values in row 12101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12102 :- 0 and it's percentage : 0.0
 Total NaN values in row 12103 :- 0 and it's percentage : 0.0
 Total NaN values in row 12104 :- 0 and it's percentage : 0.0
 Total NaN values in row 12105 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12107 :- 0 and it's percentage : 0.0
 Total NaN values in row 12108 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12109 :- 0 and it's percentage : 0.0
 Total NaN values in row 12110 :- 0 and it's percentage : 0.0
 Total NaN values in row 12111 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12112 :- 0 and it's percentage : 0.0
 Total NaN values in row 12113 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12114 :- 0 and it's percentage : 0.0
 Total NaN values in row 12115 :- 0 and it's percentage : 0.0
 Total NaN values in row 12116 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12117 :- 0 and it's percentage : 0.0
 Total NaN values in row 12118 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12119 :- 0 and it's percentage : 0.0
 Total NaN values in row 12120 :- 0 and it's percentage : 0.0
 Total NaN values in row 12121 :- 0 and it's percentage : 0.0
 Total NaN values in row 12122 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12123 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12126 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12127 :- 0 and it's percentage : 0.0
 Total NaN values in row 12128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12129 :- 0 and it's percentage : 0.0
 Total NaN values in row 12130 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12131 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12132 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12133 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12134 :- 0 and it's percentage : 0.0
 Total NaN values in row 12135 :- 0 and it's percentage : 0.0
 Total NaN values in row 12136 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12137 :- 0 and it's percentage : 0.0
 Total NaN values in row 12138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12139 :- 0 and it's percentage : 0.0
 Total NaN values in row 12140 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 12141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12142 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12143 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12144 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12145 :- 0 and it's percentage : 0.0
 Total NaN values in row 12146 :- 0 and it's percentage : 0.0
 Total NaN values in row 12147 :- 0 and it's percentage : 0.0
 Total NaN values in row 12148 :- 0 and it's percentage : 0.0
 Total NaN values in row 12149 :- 0 and it's percentage : 0.0
 Total NaN values in row 12150 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12152 :- 0 and it's percentage : 0.0
 Total NaN values in row 12153 :- 0 and it's percentage : 0.0
 Total NaN values in row 12154 :- 0 and it's percentage : 0.0
 Total NaN values in row 12155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12156 :- 0 and it's percentage : 0.0
 Total NaN values in row 12157 :- 0 and it's percentage : 0.0
 Total NaN values in row 12158 :- 0 and it's percentage : 0.0
 Total NaN values in row 12159 :- 0 and it's percentage : 0.0
 Total NaN values in row 12160 :- 0 and it's percentage : 0.0
 Total NaN values in row 12161 :- 0 and it's percentage : 0.0
 Total NaN values in row 12162 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12163 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12164 :- 0 and it's percentage : 0.0
 Total NaN values in row 12165 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12166 :- 0 and it's percentage : 0.0
 Total NaN values in row 12167 :- 0 and it's percentage : 0.0
 Total NaN values in row 12168 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12169 :- 0 and it's percentage : 0.0
 Total NaN values in row 12170 :- 0 and it's percentage : 0.0
 Total NaN values in row 12171 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12172 :- 0 and it's percentage : 0.0
 Total NaN values in row 12173 :- 0 and it's percentage : 0.0
 Total NaN values in row 12174 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12175 :- 0 and it's percentage : 0.0
 Total NaN values in row 12176 :- 0 and it's percentage : 0.0
 Total NaN values in row 12177 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12180 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12182 :- 0 and it's percentage : 0.0
 Total NaN values in row 12183 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12184 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12185 :- 0 and it's percentage : 0.0
 Total NaN values in row 12186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12187 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12188 :- 0 and it's percentage : 0.0
 Total NaN values in row 12189 :- 0 and it's percentage : 0.0
 Total NaN values in row 12190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12191 :- 0 and it's percentage : 0.0
 Total NaN values in row 12192 :- 0 and it's percentage : 0.0
 Total NaN values in row 12193 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12194 :- 0 and it's percentage : 0.0
 Total NaN values in row 12195 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12196 :- 0 and it's percentage : 0.0
 Total NaN values in row 12197 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12198 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12199 :- 0 and it's percentage : 0.0
 Total NaN values in row 12200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12201 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12202 :- 0 and it's percentage : 0.0
 Total NaN values in row 12203 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12204 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12205 :- 0 and it's percentage : 0.0
 Total NaN values in row 12206 :- 0 and it's percentage : 0.0
 Total NaN values in row 12207 :- 0 and it's percentage : 0.0
 Total NaN values in row 12208 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12209 :- 0 and it's percentage : 0.0
 Total NaN values in row 12210 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12211 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12212 :- 0 and it's percentage : 0.0
 Total NaN values in row 12213 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12214 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12216 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12218 :- 0 and it's percentage : 0.0
 Total NaN values in row 12219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12220 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12221 :- 0 and it's percentage : 0.0
 Total NaN values in row 12222 :- 0 and it's percentage : 0.0
 Total NaN values in row 12223 :- 0 and it's percentage : 0.0
 Total NaN values in row 12224 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12225 :- 0 and it's percentage : 0.0
 Total NaN values in row 12226 :- 0 and it's percentage : 0.0
 Total NaN values in row 12227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12228 :- 0 and it's percentage : 0.0
 Total NaN values in row 12229 :- 0 and it's percentage : 0.0
 Total NaN values in row 12230 :- 0 and it's percentage : 0.0
 Total NaN values in row 12231 :- 0 and it's percentage : 0.0
 Total NaN values in row 12232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12233 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12234 :- 0 and it's percentage : 0.0
 Total NaN values in row 12235 :- 0 and it's percentage : 0.0
 Total NaN values in row 12236 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12237 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12238 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12239 :- 0 and it's percentage : 0.0
 Total NaN values in row 12240 :- 0 and it's percentage : 0.0
 Total NaN values in row 12241 :- 0 and it's percentage : 0.0
 Total NaN values in row 12242 :- 0 and it's percentage : 0.0
 Total NaN values in row 12243 :- 0 and it's percentage : 0.0
 Total NaN values in row 12244 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12245 :- 0 and it's percentage : 0.0
 Total NaN values in row 12246 :- 0 and it's percentage : 0.0
 Total NaN values in row 12247 :- 0 and it's percentage : 0.0
 Total NaN values in row 12248 :- 0 and it's percentage : 0.0
 Total NaN values in row 12249 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12251 :- 0 and it's percentage : 0.0
 Total NaN values in row 12252 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12253 :- 0 and it's percentage : 0.0
 Total NaN values in row 12254 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12255 :- 0 and it's percentage : 0.0
 Total NaN values in row 12256 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12257 :- 0 and it's percentage : 0.0
 Total NaN values in row 12258 :- 0 and it's percentage : 0.0
 Total NaN values in row 12259 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12260 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12261 :- 0 and it's percentage : 0.0
 Total NaN values in row 12262 :- 0 and it's percentage : 0.0
 Total NaN values in row 12263 :- 0 and it's percentage : 0.0
 Total NaN values in row 12264 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12265 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12266 :- 0 and it's percentage : 0.0
 Total NaN values in row 12267 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12269 :- 0 and it's percentage : 0.0
 Total NaN values in row 12270 :- 0 and it's percentage : 0.0
 Total NaN values in row 12271 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12272 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12273 :- 0 and it's percentage : 0.0
 Total NaN values in row 12274 :- 0 and it's percentage : 0.0
 Total NaN values in row 12275 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12276 :- 0 and it's percentage : 0.0
 Total NaN values in row 12277 :- 0 and it's percentage : 0.0
 Total NaN values in row 12278 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12279 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 12280 :- 0 and it's percentage : 0.0
 Total NaN values in row 12281 :- 0 and it's percentage : 0.0
 Total NaN values in row 12282 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12283 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12284 :- 0 and it's percentage : 0.0

 Total NaN values in row 12285 :- 0 and it's percentage : 0.0
 Total NaN values in row 12286 :- 0 and it's percentage : 0.0
 Total NaN values in row 12287 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12288 :- 0 and it's percentage : 0.0
 Total NaN values in row 12289 :- 0 and it's percentage : 0.0
 Total NaN values in row 12290 :- 0 and it's percentage : 0.0
 Total NaN values in row 12291 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12293 :- 0 and it's percentage : 0.0
 Total NaN values in row 12294 :- 0 and it's percentage : 0.0
 Total NaN values in row 12295 :- 0 and it's percentage : 0.0
 Total NaN values in row 12296 :- 0 and it's percentage : 0.0
 Total NaN values in row 12297 :- 0 and it's percentage : 0.0
 Total NaN values in row 12298 :- 0 and it's percentage : 0.0
 Total NaN values in row 12299 :- 0 and it's percentage : 0.0
 Total NaN values in row 12300 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12301 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12302 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12303 :- 0 and it's percentage : 0.0
 Total NaN values in row 12304 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12305 :- 0 and it's percentage : 0.0
 Total NaN values in row 12306 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12307 :- 0 and it's percentage : 0.0
 Total NaN values in row 12308 :- 0 and it's percentage : 0.0
 Total NaN values in row 12309 :- 0 and it's percentage : 0.0
 Total NaN values in row 12310 :- 0 and it's percentage : 0.0
 Total NaN values in row 12311 :- 0 and it's percentage : 0.0
 Total NaN values in row 12312 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12313 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12314 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12315 :- 0 and it's percentage : 0.0
 Total NaN values in row 12316 :- 0 and it's percentage : 0.0
 Total NaN values in row 12317 :- 0 and it's percentage : 0.0
 Total NaN values in row 12318 :- 0 and it's percentage : 0.0
 Total NaN values in row 12319 :- 0 and it's percentage : 0.0
 Total NaN values in row 12320 :- 0 and it's percentage : 0.0
 Total NaN values in row 12321 :- 0 and it's percentage : 0.0
 Total NaN values in row 12322 :- 0 and it's percentage : 0.0
 Total NaN values in row 12323 :- 0 and it's percentage : 0.0
 Total NaN values in row 12324 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12325 :- 0 and it's percentage : 0.0
 Total NaN values in row 12326 :- 0 and it's percentage : 0.0
 Total NaN values in row 12327 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12328 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12329 :- 0 and it's percentage : 0.0
 Total NaN values in row 12330 :- 0 and it's percentage : 0.0
 Total NaN values in row 12331 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12332 :- 0 and it's percentage : 0.0
 Total NaN values in row 12333 :- 0 and it's percentage : 0.0
 Total NaN values in row 12334 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12336 :- 0 and it's percentage : 0.0
 Total NaN values in row 12337 :- 0 and it's percentage : 0.0
 Total NaN values in row 12338 :- 0 and it's percentage : 0.0
 Total NaN values in row 12339 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12340 :- 0 and it's percentage : 0.0
 Total NaN values in row 12341 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12342 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12343 :- 0 and it's percentage : 0.0
 Total NaN values in row 12344 :- 0 and it's percentage : 0.0
 Total NaN values in row 12345 :- 0 and it's percentage : 0.0
 Total NaN values in row 12346 :- 0 and it's percentage : 0.0
 Total NaN values in row 12347 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12348 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12349 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12350 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12351 :- 0 and it's percentage : 0.0
 Total NaN values in row 12352 :- 0 and it's percentage : 0.0
 Total NaN values in row 12353 :- 0 and it's percentage : 0.0
 Total NaN values in row 12354 :- 0 and it's percentage : 0.0
 Total NaN values in row 12355 :- 0 and it's percentage : 0.0
 Total NaN values in row 12356 :- 0 and it's percentage : 0.0
 Total NaN values in row 12357 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12358 :- 0 and it's percentage : 0.0
 Total NaN values in row 12359 :- 0 and it's percentage : 0.0
 Total NaN values in row 12360 :- 0 and it's percentage : 0.0
 Total NaN values in row 12361 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12362 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12364 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12365 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12367 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12368 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12369 :- 0 and it's percentage : 0.0
 Total NaN values in row 12370 :- 0 and it's percentage : 0.0
 Total NaN values in row 12371 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 12372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12373 :- 0 and it's percentage : 0.0
 Total NaN values in row 12374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12376 :- 0 and it's percentage : 0.0
 Total NaN values in row 12377 :- 0 and it's percentage : 0.0
 Total NaN values in row 12378 :- 0 and it's percentage : 0.0
 Total NaN values in row 12379 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12380 :- 0 and it's percentage : 0.0
 Total NaN values in row 12381 :- 0 and it's percentage : 0.0
 Total NaN values in row 12382 :- 0 and it's percentage : 0.0
 Total NaN values in row 12383 :- 0 and it's percentage : 0.0
 Total NaN values in row 12384 :- 0 and it's percentage : 0.0
 Total NaN values in row 12385 :- 0 and it's percentage : 0.0
 Total NaN values in row 12386 :- 0 and it's percentage : 0.0
 Total NaN values in row 12387 :- 0 and it's percentage : 0.0
 Total NaN values in row 12388 :- 0 and it's percentage : 0.0
 Total NaN values in row 12389 :- 0 and it's percentage : 0.0
 Total NaN values in row 12390 :- 0 and it's percentage : 0.0
 Total NaN values in row 12391 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12392 :- 0 and it's percentage : 0.0
 Total NaN values in row 12393 :- 0 and it's percentage : 0.0
 Total NaN values in row 12394 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12395 :- 0 and it's percentage : 0.0
 Total NaN values in row 12396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12397 :- 0 and it's percentage : 0.0
 Total NaN values in row 12398 :- 0 and it's percentage : 0.0
 Total NaN values in row 12399 :- 0 and it's percentage : 0.0
 Total NaN values in row 12400 :- 0 and it's percentage : 0.0
 Total NaN values in row 12401 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12402 :- 0 and it's percentage : 0.0
 Total NaN values in row 12403 :- 0 and it's percentage : 0.0
 Total NaN values in row 12404 :- 0 and it's percentage : 0.0
 Total NaN values in row 12405 :- 0 and it's percentage : 0.0
 Total NaN values in row 12406 :- 0 and it's percentage : 0.0
 Total NaN values in row 12407 :- 0 and it's percentage : 0.0
 Total NaN values in row 12408 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12409 :- 0 and it's percentage : 0.0
 Total NaN values in row 12410 :- 0 and it's percentage : 0.0
 Total NaN values in row 12411 :- 0 and it's percentage : 0.0
 Total NaN values in row 12412 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12413 :- 0 and it's percentage : 0.0
 Total NaN values in row 12414 :- 0 and it's percentage : 0.0
 Total NaN values in row 12415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12416 :- 0 and it's percentage : 0.0
 Total NaN values in row 12417 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12418 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12419 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12420 :- 0 and it's percentage : 0.0
 Total NaN values in row 12421 :- 0 and it's percentage : 0.0
 Total NaN values in row 12422 :- 0 and it's percentage : 0.0
 Total NaN values in row 12423 :- 0 and it's percentage : 0.0
 Total NaN values in row 12424 :- 0 and it's percentage : 0.0
 Total NaN values in row 12425 :- 0 and it's percentage : 0.0
 Total NaN values in row 12426 :- 0 and it's percentage : 0.0
 Total NaN values in row 12427 :- 0 and it's percentage : 0.0
 Total NaN values in row 12428 :- 0 and it's percentage : 0.0
 Total NaN values in row 12429 :- 0 and it's percentage : 0.0
 Total NaN values in row 12430 :- 0 and it's percentage : 0.0
 Total NaN values in row 12431 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12432 :- 0 and it's percentage : 0.0
 Total NaN values in row 12433 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12434 :- 0 and it's percentage : 0.0
 Total NaN values in row 12435 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12436 :- 0 and it's percentage : 0.0
 Total NaN values in row 12437 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12438 :- 0 and it's percentage : 0.0
 Total NaN values in row 12439 :- 0 and it's percentage : 0.0
 Total NaN values in row 12440 :- 0 and it's percentage : 0.0
 Total NaN values in row 12441 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12443 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12445 :- 0 and it's percentage : 0.0

 Total NaN values in row 12446 :- 0 and it's percentage : 0.0
 Total NaN values in row 12447 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12448 :- 0 and it's percentage : 0.0
 Total NaN values in row 12449 :- 0 and it's percentage : 0.0
 Total NaN values in row 12450 :- 0 and it's percentage : 0.0
 Total NaN values in row 12451 :- 0 and it's percentage : 0.0
 Total NaN values in row 12452 :- 0 and it's percentage : 0.0
 Total NaN values in row 12453 :- 0 and it's percentage : 0.0
 Total NaN values in row 12454 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12456 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12457 :- 0 and it's percentage : 0.0
 Total NaN values in row 12458 :- 0 and it's percentage : 0.0
 Total NaN values in row 12459 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12460 :- 0 and it's percentage : 0.0
 Total NaN values in row 12461 :- 0 and it's percentage : 0.0
 Total NaN values in row 12462 :- 0 and it's percentage : 0.0
 Total NaN values in row 12463 :- 0 and it's percentage : 0.0
 Total NaN values in row 12464 :- 0 and it's percentage : 0.0
 Total NaN values in row 12465 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12466 :- 0 and it's percentage : 0.0
 Total NaN values in row 12467 :- 0 and it's percentage : 0.0
 Total NaN values in row 12468 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12469 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12470 :- 0 and it's percentage : 0.0
 Total NaN values in row 12471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12472 :- 0 and it's percentage : 0.0
 Total NaN values in row 12473 :- 0 and it's percentage : 0.0
 Total NaN values in row 12474 :- 0 and it's percentage : 0.0
 Total NaN values in row 12475 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12477 :- 0 and it's percentage : 0.0
 Total NaN values in row 12478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12479 :- 0 and it's percentage : 0.0
 Total NaN values in row 12480 :- 0 and it's percentage : 0.0
 Total NaN values in row 12481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12482 :- 0 and it's percentage : 0.0
 Total NaN values in row 12483 :- 0 and it's percentage : 0.0
 Total NaN values in row 12484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12485 :- 0 and it's percentage : 0.0
 Total NaN values in row 12486 :- 0 and it's percentage : 0.0
 Total NaN values in row 12487 :- 0 and it's percentage : 0.0
 Total NaN values in row 12488 :- 0 and it's percentage : 0.0
 Total NaN values in row 12489 :- 0 and it's percentage : 0.0
 Total NaN values in row 12490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12491 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12492 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12493 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12494 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 12495 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12496 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12497 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12498 :- 0 and it's percentage : 0.0
 Total NaN values in row 12499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12500 :- 0 and it's percentage : 0.0
 Total NaN values in row 12501 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12502 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12503 :- 0 and it's percentage : 0.0
 Total NaN values in row 12504 :- 0 and it's percentage : 0.0
 Total NaN values in row 12505 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12506 :- 0 and it's percentage : 0.0
 Total NaN values in row 12507 :- 0 and it's percentage : 0.0
 Total NaN values in row 12508 :- 0 and it's percentage : 0.0
 Total NaN values in row 12509 :- 0 and it's percentage : 0.0
 Total NaN values in row 12510 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12511 :- 0 and it's percentage : 0.0
 Total NaN values in row 12512 :- 0 and it's percentage : 0.0
 Total NaN values in row 12513 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12514 :- 0 and it's percentage : 0.0
 Total NaN values in row 12515 :- 0 and it's percentage : 0.0
 Total NaN values in row 12516 :- 0 and it's percentage : 0.0
 Total NaN values in row 12517 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12518 :- 0 and it's percentage : 0.0
 Total NaN values in row 12519 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12520 :- 0 and it's percentage : 0.0
 Total NaN values in row 12521 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12522 :- 0 and it's percentage : 0.0
 Total NaN values in row 12523 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12524 :- 0 and it's percentage : 0.0
 Total NaN values in row 12525 :- 0 and it's percentage : 0.0
 Total NaN values in row 12526 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12527 :- 0 and it's percentage : 0.0
 Total NaN values in row 12528 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12529 :- 0 and it's percentage : 0.0
 Total NaN values in row 12530 :- 0 and it's percentage : 0.0
 Total NaN values in row 12531 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12532 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12534 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12535 :- 0 and it's percentage : 0.0
 Total NaN values in row 12536 :- 0 and it's percentage : 0.0
 Total NaN values in row 12537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12538 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12539 :- 0 and it's percentage : 0.0
 Total NaN values in row 12540 :- 0 and it's percentage : 0.0
 Total NaN values in row 12541 :- 0 and it's percentage : 0.0
 Total NaN values in row 12542 :- 0 and it's percentage : 0.0
 Total NaN values in row 12543 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12544 :- 0 and it's percentage : 0.0
 Total NaN values in row 12545 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12546 :- 0 and it's percentage : 0.0
 Total NaN values in row 12547 :- 0 and it's percentage : 0.0
 Total NaN values in row 12548 :- 0 and it's percentage : 0.0
 Total NaN values in row 12549 :- 0 and it's percentage : 0.0
 Total NaN values in row 12550 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12551 :- 0 and it's percentage : 0.0
 Total NaN values in row 12552 :- 0 and it's percentage : 0.0
 Total NaN values in row 12553 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12554 :- 0 and it's percentage : 0.0
 Total NaN values in row 12555 :- 0 and it's percentage : 0.0
 Total NaN values in row 12556 :- 0 and it's percentage : 0.0
 Total NaN values in row 12557 :- 0 and it's percentage : 0.0
 Total NaN values in row 12558 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12559 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12560 :- 0 and it's percentage : 0.0
 Total NaN values in row 12561 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12563 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12564 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12565 :- 0 and it's percentage : 0.0
 Total NaN values in row 12566 :- 0 and it's percentage : 0.0
 Total NaN values in row 12567 :- 0 and it's percentage : 0.0
 Total NaN values in row 12568 :- 0 and it's percentage : 0.0
 Total NaN values in row 12569 :- 0 and it's percentage : 0.0
 Total NaN values in row 12570 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12571 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12572 :- 0 and it's percentage : 0.0
 Total NaN values in row 12573 :- 0 and it's percentage : 0.0
 Total NaN values in row 12574 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12575 :- 0 and it's percentage : 0.0
 Total NaN values in row 12576 :- 0 and it's percentage : 0.0
 Total NaN values in row 12577 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12579 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 12580 :- 0 and it's percentage : 0.0
 Total NaN values in row 12581 :- 0 and it's percentage : 0.0
 Total NaN values in row 12582 :- 0 and it's percentage : 0.0
 Total NaN values in row 12583 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12584 :- 0 and it's percentage : 0.0
 Total NaN values in row 12585 :- 0 and it's percentage : 0.0
 Total NaN values in row 12586 :- 0 and it's percentage : 0.0
 Total NaN values in row 12587 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12588 :- 0 and it's percentage : 0.0
 Total NaN values in row 12589 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12590 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12591 :- 0 and it's percentage : 0.0
 Total NaN values in row 12592 :- 0 and it's percentage : 0.0
 Total NaN values in row 12593 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12594 :- 0 and it's percentage : 0.0
 Total NaN values in row 12595 :- 0 and it's percentage : 0.0
 Total NaN values in row 12596 :- 0 and it's percentage : 0.0
 Total NaN values in row 12597 :- 0 and it's percentage : 0.0
 Total NaN values in row 12598 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12599 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12600 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12601 :- 0 and it's percentage : 0.0
 Total NaN values in row 12602 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12603 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12604 :- 0 and it's percentage : 0.0
 Total NaN values in row 12605 :- 0 and it's percentage : 0.0
 Total NaN values in row 12606 :- 0 and it's percentage : 0.0
 Total NaN values in row 12607 :- 0 and it's percentage : 0.0
 Total NaN values in row 12608 :- 0 and it's percentage : 0.0
 Total NaN values in row 12609 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12610 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12611 :- 0 and it's percentage : 0.0
 Total NaN values in row 12612 :- 0 and it's percentage : 0.0
 Total NaN values in row 12613 :- 0 and it's percentage : 0.0
 Total NaN values in row 12614 :- 0 and it's percentage : 0.0
 Total NaN values in row 12615 :- 0 and it's percentage : 0.0
 Total NaN values in row 12616 :- 0 and it's percentage : 0.0
 Total NaN values in row 12617 :- 0 and it's percentage : 0.0
 Total NaN values in row 12618 :- 0 and it's percentage : 0.0
 Total NaN values in row 12619 :- 0 and it's percentage : 0.0
 Total NaN values in row 12620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12621 :- 0 and it's percentage : 0.0
 Total NaN values in row 12622 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12623 :- 0 and it's percentage : 0.0
 Total NaN values in row 12624 :- 0 and it's percentage : 0.0
 Total NaN values in row 12625 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12626 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12627 :- 0 and it's percentage : 0.0
 Total NaN values in row 12628 :- 0 and it's percentage : 0.0
 Total NaN values in row 12629 :- 0 and it's percentage : 0.0
 Total NaN values in row 12630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12631 :- 0 and it's percentage : 0.0
 Total NaN values in row 12632 :- 0 and it's percentage : 0.0
 Total NaN values in row 12633 :- 0 and it's percentage : 0.0
 Total NaN values in row 12634 :- 0 and it's percentage : 0.0
 Total NaN values in row 12635 :- 0 and it's percentage : 0.0
 Total NaN values in row 12636 :- 0 and it's percentage : 0.0
 Total NaN values in row 12637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12638 :- 0 and it's percentage : 0.0
 Total NaN values in row 12639 :- 0 and it's percentage : 0.0
 Total NaN values in row 12640 :- 0 and it's percentage : 0.0
 Total NaN values in row 12641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12642 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12643 :- 0 and it's percentage : 0.0
 Total NaN values in row 12644 :- 0 and it's percentage : 0.0
 Total NaN values in row 12645 :- 0 and it's percentage : 0.0
 Total NaN values in row 12646 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12647 :- 0 and it's percentage : 0.0
 Total NaN values in row 12648 :- 0 and it's percentage : 0.0
 Total NaN values in row 12649 :- 0 and it's percentage : 0.0
 Total NaN values in row 12650 :- 0 and it's percentage : 0.0
 Total NaN values in row 12651 :- 0 and it's percentage : 0.0
 Total NaN values in row 12652 :- 0 and it's percentage : 0.0
 Total NaN values in row 12653 :- 0 and it's percentage : 0.0
 Total NaN values in row 12654 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12655 :- 0 and it's percentage : 0.0
 Total NaN values in row 12656 :- 0 and it's percentage : 0.0
 Total NaN values in row 12657 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12658 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12659 :- 0 and it's percentage : 0.0
 Total NaN values in row 12660 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12661 :- 0 and it's percentage : 0.0
 Total NaN values in row 12662 :- 0 and it's percentage : 0.0
 Total NaN values in row 12663 :- 0 and it's percentage : 0.0
 Total NaN values in row 12664 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12665 :- 0 and it's percentage : 0.0
 Total NaN values in row 12666 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12668 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12669 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12670 :- 0 and it's percentage : 0.0
 Total NaN values in row 12671 :- 0 and it's percentage : 0.0
 Total NaN values in row 12672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12673 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12674 :- 0 and it's percentage : 0.0
 Total NaN values in row 12675 :- 0 and it's percentage : 0.0
 Total NaN values in row 12676 :- 0 and it's percentage : 0.0
 Total NaN values in row 12677 :- 0 and it's percentage : 0.0
 Total NaN values in row 12678 :- 0 and it's percentage : 0.0
 Total NaN values in row 12679 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12680 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12681 :- 0 and it's percentage : 0.0
 Total NaN values in row 12682 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12684 :- 0 and it's percentage : 0.0
 Total NaN values in row 12685 :- 0 and it's percentage : 0.0
 Total NaN values in row 12686 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12688 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12689 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12691 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12693 :- 0 and it's percentage : 0.0
 Total NaN values in row 12694 :- 0 and it's percentage : 0.0
 Total NaN values in row 12695 :- 0 and it's percentage : 0.0
 Total NaN values in row 12696 :- 0 and it's percentage : 0.0
 Total NaN values in row 12697 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12698 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12699 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12701 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12702 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12703 :- 0 and it's percentage : 0.0
 Total NaN values in row 12704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12705 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12706 :- 0 and it's percentage : 0.0
 Total NaN values in row 12707 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12708 :- 0 and it's percentage : 0.0
 Total NaN values in row 12709 :- 0 and it's percentage : 0.0
 Total NaN values in row 12710 :- 0 and it's percentage : 0.0
 Total NaN values in row 12711 :- 0 and it's percentage : 0.0
 Total NaN values in row 12712 :- 0 and it's percentage : 0.0
 Total NaN values in row 12713 :- 0 and it's percentage : 0.0
 Total NaN values in row 12714 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12715 :- 0 and it's percentage : 0.0
 Total NaN values in row 12716 :- 0 and it's percentage : 0.0

 Total NaN values in row 12717 :- 0 and it's percentage : 0.0
 Total NaN values in row 12718 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12719 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12720 :- 0 and it's percentage : 0.0
 Total NaN values in row 12721 :- 0 and it's percentage : 0.0
 Total NaN values in row 12722 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12723 :- 0 and it's percentage : 0.0
 Total NaN values in row 12724 :- 0 and it's percentage : 0.0
 Total NaN values in row 12725 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12726 :- 0 and it's percentage : 0.0
 Total NaN values in row 12727 :- 0 and it's percentage : 0.0
 Total NaN values in row 12728 :- 0 and it's percentage : 0.0
 Total NaN values in row 12729 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12730 :- 0 and it's percentage : 0.0
 Total NaN values in row 12731 :- 0 and it's percentage : 0.0
 Total NaN values in row 12732 :- 0 and it's percentage : 0.0
 Total NaN values in row 12733 :- 0 and it's percentage : 0.0
 Total NaN values in row 12734 :- 0 and it's percentage : 0.0
 Total NaN values in row 12735 :- 0 and it's percentage : 0.0
 Total NaN values in row 12736 :- 0 and it's percentage : 0.0
 Total NaN values in row 12737 :- 0 and it's percentage : 0.0
 Total NaN values in row 12738 :- 0 and it's percentage : 0.0
 Total NaN values in row 12739 :- 0 and it's percentage : 0.0
 Total NaN values in row 12740 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12741 :- 0 and it's percentage : 0.0
 Total NaN values in row 12742 :- 0 and it's percentage : 0.0
 Total NaN values in row 12743 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12744 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12745 :- 0 and it's percentage : 0.0
 Total NaN values in row 12746 :- 0 and it's percentage : 0.0
 Total NaN values in row 12747 :- 0 and it's percentage : 0.0
 Total NaN values in row 12748 :- 0 and it's percentage : 0.0
 Total NaN values in row 12749 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12750 :- 0 and it's percentage : 0.0
 Total NaN values in row 12751 :- 0 and it's percentage : 0.0
 Total NaN values in row 12752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12753 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12754 :- 0 and it's percentage : 0.0
 Total NaN values in row 12755 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12756 :- 0 and it's percentage : 0.0
 Total NaN values in row 12757 :- 0 and it's percentage : 0.0
 Total NaN values in row 12758 :- 0 and it's percentage : 0.0
 Total NaN values in row 12759 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12760 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12761 :- 0 and it's percentage : 0.0
 Total NaN values in row 12762 :- 0 and it's percentage : 0.0
 Total NaN values in row 12763 :- 0 and it's percentage : 0.0
 Total NaN values in row 12764 :- 0 and it's percentage : 0.0
 Total NaN values in row 12765 :- 0 and it's percentage : 0.0
 Total NaN values in row 12766 :- 0 and it's percentage : 0.0
 Total NaN values in row 12767 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12768 :- 0 and it's percentage : 0.0
 Total NaN values in row 12769 :- 0 and it's percentage : 0.0
 Total NaN values in row 12770 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12771 :- 0 and it's percentage : 0.0
 Total NaN values in row 12772 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12773 :- 0 and it's percentage : 0.0
 Total NaN values in row 12774 :- 0 and it's percentage : 0.0
 Total NaN values in row 12775 :- 0 and it's percentage : 0.0
 Total NaN values in row 12776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12777 :- 0 and it's percentage : 0.0
 Total NaN values in row 12778 :- 0 and it's percentage : 0.0
 Total NaN values in row 12779 :- 0 and it's percentage : 0.0
 Total NaN values in row 12780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12781 :- 0 and it's percentage : 0.0
 Total NaN values in row 12782 :- 0 and it's percentage : 0.0
 Total NaN values in row 12783 :- 0 and it's percentage : 0.0
 Total NaN values in row 12784 :- 0 and it's percentage : 0.0
 Total NaN values in row 12785 :- 0 and it's percentage : 0.0
 Total NaN values in row 12786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12787 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12788 :- 0 and it's percentage : 0.0
 Total NaN values in row 12789 :- 0 and it's percentage : 0.0
 Total NaN values in row 12790 :- 0 and it's percentage : 0.0
 Total NaN values in row 12791 :- 0 and it's percentage : 0.0
 Total NaN values in row 12792 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12793 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12794 :- 0 and it's percentage : 0.0
 Total NaN values in row 12795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12796 :- 0 and it's percentage : 0.0
 Total NaN values in row 12797 :- 0 and it's percentage : 0.0
 Total NaN values in row 12798 :- 0 and it's percentage : 0.0
 Total NaN values in row 12799 :- 0 and it's percentage : 0.0
 Total NaN values in row 12800 :- 0 and it's percentage : 0.0
 Total NaN values in row 12801 :- 0 and it's percentage : 0.0
 Total NaN values in row 12802 :- 0 and it's percentage : 0.0
 Total NaN values in row 12803 :- 0 and it's percentage : 0.0
 Total NaN values in row 12804 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12805 :- 0 and it's percentage : 0.0
 Total NaN values in row 12806 :- 0 and it's percentage : 0.0
 Total NaN values in row 12807 :- 0 and it's percentage : 0.0
 Total NaN values in row 12808 :- 0 and it's percentage : 0.0
 Total NaN values in row 12809 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12810 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12811 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12812 :- 0 and it's percentage : 0.0
 Total NaN values in row 12813 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12814 :- 0 and it's percentage : 0.0
 Total NaN values in row 12815 :- 0 and it's percentage : 0.0
 Total NaN values in row 12816 :- 0 and it's percentage : 0.0
 Total NaN values in row 12817 :- 0 and it's percentage : 0.0
 Total NaN values in row 12818 :- 0 and it's percentage : 0.0
 Total NaN values in row 12819 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12820 :- 0 and it's percentage : 0.0
 Total NaN values in row 12821 :- 0 and it's percentage : 0.0
 Total NaN values in row 12822 :- 0 and it's percentage : 0.0
 Total NaN values in row 12823 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12824 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12825 :- 0 and it's percentage : 0.0
 Total NaN values in row 12826 :- 0 and it's percentage : 0.0
 Total NaN values in row 12827 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12828 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12829 :- 0 and it's percentage : 0.0
 Total NaN values in row 12830 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12831 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12832 :- 0 and it's percentage : 0.0
 Total NaN values in row 12833 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12834 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12835 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12836 :- 0 and it's percentage : 0.0
 Total NaN values in row 12837 :- 0 and it's percentage : 0.0
 Total NaN values in row 12838 :- 0 and it's percentage : 0.0
 Total NaN values in row 12839 :- 0 and it's percentage : 0.0
 Total NaN values in row 12840 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12841 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12843 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12844 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12845 :- 0 and it's percentage : 0.0
 Total NaN values in row 12846 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12847 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12848 :- 0 and it's percentage : 0.0
 Total NaN values in row 12849 :- 0 and it's percentage : 0.0
 Total NaN values in row 12850 :- 0 and it's percentage : 0.0
 Total NaN values in row 12851 :- 0 and it's percentage : 0.0
 Total NaN values in row 12852 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12853 :- 0 and it's percentage : 0.0
 Total NaN values in row 12854 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12855 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12856 :- 0 and it's percentage : 0.0
 Total NaN values in row 12857 :- 0 and it's percentage : 0.0
 Total NaN values in row 12858 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12859 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12860 :- 0 and it's percentage : 0.0
 Total NaN values in row 12861 :- 0 and it's percentage : 0.0
 Total NaN values in row 12862 :- 0 and it's percentage : 0.0
 Total NaN values in row 12863 :- 0 and it's percentage : 0.0
 Total NaN values in row 12864 :- 0 and it's percentage : 0.0
 Total NaN values in row 12865 :- 0 and it's percentage : 0.0
 Total NaN values in row 12866 :- 0 and it's percentage : 0.0
 Total NaN values in row 12867 :- 0 and it's percentage : 0.0
 Total NaN values in row 12868 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12869 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 12870 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12872 :- 0 and it's percentage : 0.0
 Total NaN values in row 12873 :- 0 and it's percentage : 0.0
 Total NaN values in row 12874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12875 :- 0 and it's percentage : 0.0
 Total NaN values in row 12876 :- 0 and it's percentage : 0.0
 Total NaN values in row 12877 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12878 :- 0 and it's percentage : 0.0
 Total NaN values in row 12879 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12880 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12881 :- 0 and it's percentage : 0.0
 Total NaN values in row 12882 :- 0 and it's percentage : 0.0
 Total NaN values in row 12883 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12884 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12885 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12886 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12887 :- 0 and it's percentage : 0.0
 Total NaN values in row 12888 :- 0 and it's percentage : 0.0
 Total NaN values in row 12889 :- 0 and it's percentage : 0.0
 Total NaN values in row 12890 :- 0 and it's percentage : 0.0
 Total NaN values in row 12891 :- 0 and it's percentage : 0.0
 Total NaN values in row 12892 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12893 :- 0 and it's percentage : 0.0
 Total NaN values in row 12894 :- 0 and it's percentage : 0.0
 Total NaN values in row 12895 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12896 :- 0 and it's percentage : 0.0
 Total NaN values in row 12897 :- 0 and it's percentage : 0.0
 Total NaN values in row 12898 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12899 :- 0 and it's percentage : 0.0
 Total NaN values in row 12900 :- 0 and it's percentage : 0.0
 Total NaN values in row 12901 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12902 :- 0 and it's percentage : 0.0
 Total NaN values in row 12903 :- 0 and it's percentage : 0.0
 Total NaN values in row 12904 :- 0 and it's percentage : 0.0
 Total NaN values in row 12905 :- 0 and it's percentage : 0.0
 Total NaN values in row 12906 :- 0 and it's percentage : 0.0
 Total NaN values in row 12907 :- 0 and it's percentage : 0.0
 Total NaN values in row 12908 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12910 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12911 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12912 :- 0 and it's percentage : 0.0
 Total NaN values in row 12913 :- 0 and it's percentage : 0.0
 Total NaN values in row 12914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12915 :- 0 and it's percentage : 0.0
 Total NaN values in row 12916 :- 0 and it's percentage : 0.0
 Total NaN values in row 12917 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12918 :- 0 and it's percentage : 0.0
 Total NaN values in row 12919 :- 0 and it's percentage : 0.0
 Total NaN values in row 12920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12922 :- 0 and it's percentage : 0.0
 Total NaN values in row 12923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12924 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12925 :- 0 and it's percentage : 0.0
 Total NaN values in row 12926 :- 0 and it's percentage : 0.0
 Total NaN values in row 12927 :- 0 and it's percentage : 0.0
 Total NaN values in row 12928 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12929 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12930 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12931 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12932 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12933 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12934 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12935 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12936 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12937 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12938 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12939 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12940 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12941 :- 0 and it's percentage : 0.0
 Total NaN values in row 12942 :- 0 and it's percentage : 0.0
 Total NaN values in row 12943 :- 0 and it's percentage : 0.0
 Total NaN values in row 12944 :- 0 and it's percentage : 0.0
 Total NaN values in row 12945 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12946 :- 0 and it's percentage : 0.0
 Total NaN values in row 12947 :- 0 and it's percentage : 0.0
 Total NaN values in row 12948 :- 0 and it's percentage : 0.0
 Total NaN values in row 12949 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12950 :- 0 and it's percentage : 0.0
 Total NaN values in row 12951 :- 0 and it's percentage : 0.0
 Total NaN values in row 12952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12953 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12954 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12955 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12956 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12957 :- 0 and it's percentage : 0.0
 Total NaN values in row 12958 :- 0 and it's percentage : 0.0
 Total NaN values in row 12959 :- 0 and it's percentage : 0.0
 Total NaN values in row 12960 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 12961 :- 0 and it's percentage : 0.0
 Total NaN values in row 12962 :- 0 and it's percentage : 0.0
 Total NaN values in row 12963 :- 0 and it's percentage : 0.0
 Total NaN values in row 12964 :- 0 and it's percentage : 0.0
 Total NaN values in row 12965 :- 0 and it's percentage : 0.0
 Total NaN values in row 12966 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12967 :- 0 and it's percentage : 0.0
 Total NaN values in row 12968 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12970 :- 0 and it's percentage : 0.0
 Total NaN values in row 12971 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12972 :- 0 and it's percentage : 0.0
 Total NaN values in row 12973 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 12974 :- 0 and it's percentage : 0.0
 Total NaN values in row 12975 :- 0 and it's percentage : 0.0
 Total NaN values in row 12976 :- 0 and it's percentage : 0.0
 Total NaN values in row 12977 :- 0 and it's percentage : 0.0
 Total NaN values in row 12978 :- 0 and it's percentage : 0.0
 Total NaN values in row 12979 :- 0 and it's percentage : 0.0
 Total NaN values in row 12980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12981 :- 0 and it's percentage : 0.0
 Total NaN values in row 12982 :- 0 and it's percentage : 0.0
 Total NaN values in row 12983 :- 0 and it's percentage : 0.0
 Total NaN values in row 12984 :- 0 and it's percentage : 0.0
 Total NaN values in row 12985 :- 0 and it's percentage : 0.0
 Total NaN values in row 12986 :- 0 and it's percentage : 0.0
 Total NaN values in row 12987 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12988 :- 0 and it's percentage : 0.0
 Total NaN values in row 12989 :- 0 and it's percentage : 0.0
 Total NaN values in row 12990 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 12991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12992 :- 0 and it's percentage : 0.0
 Total NaN values in row 12993 :- 0 and it's percentage : 0.0
 Total NaN values in row 12994 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12995 :- 0 and it's percentage : 0.0
 Total NaN values in row 12996 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 12998 :- 0 and it's percentage : 0.0
 Total NaN values in row 12999 :- 0 and it's percentage : 0.0
 Total NaN values in row 13000 :- 0 and it's percentage : 0.0
 Total NaN values in row 13001 :- 0 and it's percentage : 0.0
 Total NaN values in row 13002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13003 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13004 :- 0 and it's percentage : 0.0
 Total NaN values in row 13005 :- 0 and it's percentage : 0.0
 Total NaN values in row 13006 :- 0 and it's percentage : 0.0
 Total NaN values in row 13007 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13008 :- 0 and it's percentage : 0.0
 Total NaN values in row 13009 :- 0 and it's percentage : 0.0
 Total NaN values in row 13010 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13011 :- 0 and it's percentage : 0.0
 Total NaN values in row 13012 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13013 :- 0 and it's percentage : 0.0
 Total NaN values in row 13014 :- 0 and it's percentage : 0.0
 Total NaN values in row 13015 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13016 :- 0 and it's percentage : 0.0
 Total NaN values in row 13017 :- 0 and it's percentage : 0.0
 Total NaN values in row 13018 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13019 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13020 :- 0 and it's percentage : 0.0
 Total NaN values in row 13021 :- 0 and it's percentage : 0.0
 Total NaN values in row 13022 :- 0 and it's percentage : 0.0
 Total NaN values in row 13023 :- 0 and it's percentage : 0.0
 Total NaN values in row 13024 :- 0 and it's percentage : 0.0
 Total NaN values in row 13025 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13026 :- 0 and it's percentage : 0.0
 Total NaN values in row 13027 :- 0 and it's percentage : 0.0
 Total NaN values in row 13028 :- 0 and it's percentage : 0.0
 Total NaN values in row 13029 :- 0 and it's percentage : 0.0
 Total NaN values in row 13030 :- 0 and it's percentage : 0.0

 Total NaN values in row 13031 :- 0 and it's percentage : 0.0
 Total NaN values in row 13032 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13033 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13034 :- 0 and it's percentage : 0.0
 Total NaN values in row 13035 :- 0 and it's percentage : 0.0
 Total NaN values in row 13036 :- 0 and it's percentage : 0.0
 Total NaN values in row 13037 :- 0 and it's percentage : 0.0
 Total NaN values in row 13038 :- 0 and it's percentage : 0.0
 Total NaN values in row 13039 :- 0 and it's percentage : 0.0
 Total NaN values in row 13040 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13042 :- 0 and it's percentage : 0.0
 Total NaN values in row 13043 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13044 :- 0 and it's percentage : 0.0
 Total NaN values in row 13045 :- 0 and it's percentage : 0.0
 Total NaN values in row 13046 :- 0 and it's percentage : 0.0
 Total NaN values in row 13047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13048 :- 0 and it's percentage : 0.0
 Total NaN values in row 13049 :- 0 and it's percentage : 0.0
 Total NaN values in row 13050 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13051 :- 0 and it's percentage : 0.0
 Total NaN values in row 13052 :- 0 and it's percentage : 0.0
 Total NaN values in row 13053 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13054 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13055 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13056 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13058 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13059 :- 0 and it's percentage : 0.0
 Total NaN values in row 13060 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13061 :- 0 and it's percentage : 0.0
 Total NaN values in row 13062 :- 0 and it's percentage : 0.0
 Total NaN values in row 13063 :- 0 and it's percentage : 0.0
 Total NaN values in row 13064 :- 0 and it's percentage : 0.0
 Total NaN values in row 13065 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13066 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13067 :- 0 and it's percentage : 0.0
 Total NaN values in row 13068 :- 0 and it's percentage : 0.0
 Total NaN values in row 13069 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13070 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13071 :- 0 and it's percentage : 0.0
 Total NaN values in row 13072 :- 0 and it's percentage : 0.0
 Total NaN values in row 13073 :- 0 and it's percentage : 0.0
 Total NaN values in row 13074 :- 0 and it's percentage : 0.0
 Total NaN values in row 13075 :- 0 and it's percentage : 0.0
 Total NaN values in row 13076 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13077 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13078 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13079 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13080 :- 0 and it's percentage : 0.0
 Total NaN values in row 13081 :- 0 and it's percentage : 0.0
 Total NaN values in row 13082 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13083 :- 0 and it's percentage : 0.0
 Total NaN values in row 13084 :- 0 and it's percentage : 0.0
 Total NaN values in row 13085 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13087 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13088 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13090 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13091 :- 0 and it's percentage : 0.0
 Total NaN values in row 13092 :- 0 and it's percentage : 0.0
 Total NaN values in row 13093 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13094 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13095 :- 0 and it's percentage : 0.0
 Total NaN values in row 13096 :- 0 and it's percentage : 0.0
 Total NaN values in row 13097 :- 0 and it's percentage : 0.0
 Total NaN values in row 13098 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13099 :- 0 and it's percentage : 0.0
 Total NaN values in row 13100 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13102 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13103 :- 0 and it's percentage : 0.0
 Total NaN values in row 13104 :- 0 and it's percentage : 0.0
 Total NaN values in row 13105 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13106 :- 0 and it's percentage : 0.0
 Total NaN values in row 13107 :- 0 and it's percentage : 0.0
 Total NaN values in row 13108 :- 0 and it's percentage : 0.0
 Total NaN values in row 13109 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13110 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13111 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13112 :- 0 and it's percentage : 0.0
 Total NaN values in row 13113 :- 0 and it's percentage : 0.0
 Total NaN values in row 13114 :- 0 and it's percentage : 0.0
 Total NaN values in row 13115 :- 0 and it's percentage : 0.0
 Total NaN values in row 13116 :- 0 and it's percentage : 0.0
 Total NaN values in row 13117 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13119 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13120 :- 0 and it's percentage : 0.0
 Total NaN values in row 13121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13122 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13123 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13124 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13126 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13127 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13129 :- 0 and it's percentage : 0.0
 Total NaN values in row 13130 :- 0 and it's percentage : 0.0
 Total NaN values in row 13131 :- 0 and it's percentage : 0.0
 Total NaN values in row 13132 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13133 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13134 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13135 :- 0 and it's percentage : 0.0
 Total NaN values in row 13136 :- 0 and it's percentage : 0.0
 Total NaN values in row 13137 :- 0 and it's percentage : 0.0
 Total NaN values in row 13138 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13139 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13141 :- 0 and it's percentage : 0.0
 Total NaN values in row 13142 :- 0 and it's percentage : 0.0
 Total NaN values in row 13143 :- 0 and it's percentage : 0.0
 Total NaN values in row 13144 :- 0 and it's percentage : 0.0
 Total NaN values in row 13145 :- 0 and it's percentage : 0.0
 Total NaN values in row 13146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13147 :- 0 and it's percentage : 0.0
 Total NaN values in row 13148 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13149 :- 0 and it's percentage : 0.0
 Total NaN values in row 13150 :- 0 and it's percentage : 0.0
 Total NaN values in row 13151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13152 :- 0 and it's percentage : 0.0
 Total NaN values in row 13153 :- 0 and it's percentage : 0.0
 Total NaN values in row 13154 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13155 :- 0 and it's percentage : 0.0
 Total NaN values in row 13156 :- 0 and it's percentage : 0.0
 Total NaN values in row 13157 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13158 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13159 :- 0 and it's percentage : 0.0
 Total NaN values in row 13160 :- 0 and it's percentage : 0.0
 Total NaN values in row 13161 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13162 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13163 :- 0 and it's percentage : 0.0
 Total NaN values in row 13164 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13165 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13166 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13168 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13169 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13170 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13171 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13172 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13173 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13174 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13175 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13176 :- 0 and it's percentage : 0.0
 Total NaN values in row 13177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13178 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13180 :- 0 and it's percentage : 0.0
 Total NaN values in row 13181 :- 0 and it's percentage : 0.0
 Total NaN values in row 13182 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13183 :- 0 and it's percentage : 0.0
 Total NaN values in row 13184 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13187 :- 0 and it's percentage : 0.0
 Total NaN values in row 13188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13189 :- 0 and it's percentage : 0.0

 Total NaN values in row 13190 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13191 :- 0 and it's percentage : 0.0
 Total NaN values in row 13192 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13193 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13194 :- 0 and it's percentage : 0.0
 Total NaN values in row 13195 :- 0 and it's percentage : 0.0
 Total NaN values in row 13196 :- 0 and it's percentage : 0.0
 Total NaN values in row 13197 :- 0 and it's percentage : 0.0
 Total NaN values in row 13198 :- 0 and it's percentage : 0.0
 Total NaN values in row 13199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13200 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13201 :- 0 and it's percentage : 0.0
 Total NaN values in row 13202 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13203 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13204 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13205 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13206 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13208 :- 0 and it's percentage : 0.0
 Total NaN values in row 13209 :- 0 and it's percentage : 0.0
 Total NaN values in row 13210 :- 0 and it's percentage : 0.0
 Total NaN values in row 13211 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13212 :- 0 and it's percentage : 0.0
 Total NaN values in row 13213 :- 0 and it's percentage : 0.0
 Total NaN values in row 13214 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13215 :- 0 and it's percentage : 0.0
 Total NaN values in row 13216 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13217 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13218 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13219 :- 0 and it's percentage : 0.0
 Total NaN values in row 13220 :- 0 and it's percentage : 0.0
 Total NaN values in row 13221 :- 0 and it's percentage : 0.0
 Total NaN values in row 13222 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13223 :- 0 and it's percentage : 0.0
 Total NaN values in row 13224 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 13225 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13226 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13227 :- 0 and it's percentage : 0.0
 Total NaN values in row 13228 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13229 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13230 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13231 :- 0 and it's percentage : 0.0
 Total NaN values in row 13232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13233 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13234 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13235 :- 0 and it's percentage : 0.0
 Total NaN values in row 13236 :- 0 and it's percentage : 0.0
 Total NaN values in row 13237 :- 0 and it's percentage : 0.0
 Total NaN values in row 13238 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13240 :- 0 and it's percentage : 0.0
 Total NaN values in row 13241 :- 0 and it's percentage : 0.0
 Total NaN values in row 13242 :- 0 and it's percentage : 0.0
 Total NaN values in row 13243 :- 0 and it's percentage : 0.0
 Total NaN values in row 13244 :- 0 and it's percentage : 0.0
 Total NaN values in row 13245 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13246 :- 0 and it's percentage : 0.0
 Total NaN values in row 13247 :- 0 and it's percentage : 0.0
 Total NaN values in row 13248 :- 0 and it's percentage : 0.0
 Total NaN values in row 13249 :- 0 and it's percentage : 0.0
 Total NaN values in row 13250 :- 0 and it's percentage : 0.0
 Total NaN values in row 13251 :- 0 and it's percentage : 0.0
 Total NaN values in row 13252 :- 0 and it's percentage : 0.0
 Total NaN values in row 13253 :- 0 and it's percentage : 0.0
 Total NaN values in row 13254 :- 0 and it's percentage : 0.0
 Total NaN values in row 13255 :- 0 and it's percentage : 0.0
 Total NaN values in row 13256 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13257 :- 0 and it's percentage : 0.0
 Total NaN values in row 13258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13259 :- 0 and it's percentage : 0.0
 Total NaN values in row 13260 :- 0 and it's percentage : 0.0
 Total NaN values in row 13261 :- 0 and it's percentage : 0.0
 Total NaN values in row 13262 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13263 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13264 :- 0 and it's percentage : 0.0
 Total NaN values in row 13265 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13266 :- 0 and it's percentage : 0.0
 Total NaN values in row 13267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13268 :- 0 and it's percentage : 0.0
 Total NaN values in row 13269 :- 0 and it's percentage : 0.0
 Total NaN values in row 13270 :- 0 and it's percentage : 0.0
 Total NaN values in row 13271 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13272 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13273 :- 0 and it's percentage : 0.0
 Total NaN values in row 13274 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13275 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13276 :- 0 and it's percentage : 0.0
 Total NaN values in row 13277 :- 0 and it's percentage : 0.0
 Total NaN values in row 13278 :- 0 and it's percentage : 0.0
 Total NaN values in row 13279 :- 0 and it's percentage : 0.0
 Total NaN values in row 13280 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13281 :- 0 and it's percentage : 0.0
 Total NaN values in row 13282 :- 0 and it's percentage : 0.0
 Total NaN values in row 13283 :- 0 and it's percentage : 0.0
 Total NaN values in row 13284 :- 0 and it's percentage : 0.0
 Total NaN values in row 13285 :- 0 and it's percentage : 0.0
 Total NaN values in row 13286 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13287 :- 0 and it's percentage : 0.0
 Total NaN values in row 13288 :- 0 and it's percentage : 0.0
 Total NaN values in row 13289 :- 0 and it's percentage : 0.0
 Total NaN values in row 13290 :- 0 and it's percentage : 0.0
 Total NaN values in row 13291 :- 0 and it's percentage : 0.0
 Total NaN values in row 13292 :- 0 and it's percentage : 0.0
 Total NaN values in row 13293 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13294 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13295 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13296 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13297 :- 0 and it's percentage : 0.0
 Total NaN values in row 13298 :- 0 and it's percentage : 0.0
 Total NaN values in row 13299 :- 0 and it's percentage : 0.0
 Total NaN values in row 13300 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13301 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13302 :- 0 and it's percentage : 0.0
 Total NaN values in row 13303 :- 0 and it's percentage : 0.0
 Total NaN values in row 13304 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13305 :- 0 and it's percentage : 0.0
 Total NaN values in row 13306 :- 0 and it's percentage : 0.0
 Total NaN values in row 13307 :- 0 and it's percentage : 0.0
 Total NaN values in row 13308 :- 0 and it's percentage : 0.0
 Total NaN values in row 13309 :- 0 and it's percentage : 0.0
 Total NaN values in row 13310 :- 0 and it's percentage : 0.0
 Total NaN values in row 13311 :- 0 and it's percentage : 0.0
 Total NaN values in row 13312 :- 0 and it's percentage : 0.0
 Total NaN values in row 13313 :- 0 and it's percentage : 0.0
 Total NaN values in row 13314 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13315 :- 0 and it's percentage : 0.0
 Total NaN values in row 13316 :- 0 and it's percentage : 0.0
 Total NaN values in row 13317 :- 0 and it's percentage : 0.0
 Total NaN values in row 13318 :- 0 and it's percentage : 0.0
 Total NaN values in row 13319 :- 0 and it's percentage : 0.0
 Total NaN values in row 13320 :- 0 and it's percentage : 0.0
 Total NaN values in row 13321 :- 0 and it's percentage : 0.0
 Total NaN values in row 13322 :- 0 and it's percentage : 0.0
 Total NaN values in row 13323 :- 0 and it's percentage : 0.0
 Total NaN values in row 13324 :- 0 and it's percentage : 0.0
 Total NaN values in row 13325 :- 0 and it's percentage : 0.0
 Total NaN values in row 13326 :- 0 and it's percentage : 0.0
 Total NaN values in row 13327 :- 0 and it's percentage : 0.0
 Total NaN values in row 13328 :- 0 and it's percentage : 0.0
 Total NaN values in row 13329 :- 0 and it's percentage : 0.0
 Total NaN values in row 13330 :- 0 and it's percentage : 0.0
 Total NaN values in row 13331 :- 0 and it's percentage : 0.0
 Total NaN values in row 13332 :- 0 and it's percentage : 0.0
 Total NaN values in row 13333 :- 0 and it's percentage : 0.0
 Total NaN values in row 13334 :- 0 and it's percentage : 0.0
 Total NaN values in row 13335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13336 :- 0 and it's percentage : 0.0
 Total NaN values in row 13337 :- 0 and it's percentage : 0.0
 Total NaN values in row 13338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13339 :- 0 and it's percentage : 0.0
 Total NaN values in row 13340 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13341 :- 0 and it's percentage : 0.0
 Total NaN values in row 13342 :- 0 and it's percentage : 0.0
 Total NaN values in row 13343 :- 0 and it's percentage : 0.0
 Total NaN values in row 13344 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13345 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 13346 :- 0 and it's percentage : 0.0
 Total NaN values in row 13347 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13348 :- 0 and it's percentage : 0.0
 Total NaN values in row 13349 :- 0 and it's percentage : 0.0
 Total NaN values in row 13350 :- 0 and it's percentage : 0.0
 Total NaN values in row 13351 :- 0 and it's percentage : 0.0
 Total NaN values in row 13352 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13353 :- 0 and it's percentage : 0.0
 Total NaN values in row 13354 :- 0 and it's percentage : 0.0
 Total NaN values in row 13355 :- 0 and it's percentage : 0.0
 Total NaN values in row 13356 :- 0 and it's percentage : 0.0
 Total NaN values in row 13357 :- 0 and it's percentage : 0.0
 Total NaN values in row 13358 :- 0 and it's percentage : 0.0
 Total NaN values in row 13359 :- 0 and it's percentage : 0.0
 Total NaN values in row 13360 :- 0 and it's percentage : 0.0
 Total NaN values in row 13361 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13362 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13363 :- 0 and it's percentage : 0.0
 Total NaN values in row 13364 :- 0 and it's percentage : 0.0
 Total NaN values in row 13365 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13367 :- 0 and it's percentage : 0.0
 Total NaN values in row 13368 :- 0 and it's percentage : 0.0
 Total NaN values in row 13369 :- 0 and it's percentage : 0.0
 Total NaN values in row 13370 :- 0 and it's percentage : 0.0
 Total NaN values in row 13371 :- 0 and it's percentage : 0.0
 Total NaN values in row 13372 :- 0 and it's percentage : 0.0
 Total NaN values in row 13373 :- 0 and it's percentage : 0.0
 Total NaN values in row 13374 :- 0 and it's percentage : 0.0
 Total NaN values in row 13375 :- 0 and it's percentage : 0.0
 Total NaN values in row 13376 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13377 :- 0 and it's percentage : 0.0
 Total NaN values in row 13378 :- 0 and it's percentage : 0.0
 Total NaN values in row 13379 :- 0 and it's percentage : 0.0
 Total NaN values in row 13380 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13381 :- 0 and it's percentage : 0.0
 Total NaN values in row 13382 :- 0 and it's percentage : 0.0
 Total NaN values in row 13383 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13384 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13385 :- 0 and it's percentage : 0.0
 Total NaN values in row 13386 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13387 :- 0 and it's percentage : 0.0
 Total NaN values in row 13388 :- 0 and it's percentage : 0.0
 Total NaN values in row 13389 :- 0 and it's percentage : 0.0
 Total NaN values in row 13390 :- 0 and it's percentage : 0.0
 Total NaN values in row 13391 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13392 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13393 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13394 :- 0 and it's percentage : 0.0
 Total NaN values in row 13395 :- 0 and it's percentage : 0.0
 Total NaN values in row 13396 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13398 :- 0 and it's percentage : 0.0
 Total NaN values in row 13399 :- 0 and it's percentage : 0.0
 Total NaN values in row 13400 :- 0 and it's percentage : 0.0
 Total NaN values in row 13401 :- 0 and it's percentage : 0.0
 Total NaN values in row 13402 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13403 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13404 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13405 :- 0 and it's percentage : 0.0
 Total NaN values in row 13406 :- 0 and it's percentage : 0.0
 Total NaN values in row 13407 :- 0 and it's percentage : 0.0
 Total NaN values in row 13408 :- 0 and it's percentage : 0.0
 Total NaN values in row 13409 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13410 :- 0 and it's percentage : 0.0
 Total NaN values in row 13411 :- 0 and it's percentage : 0.0
 Total NaN values in row 13412 :- 0 and it's percentage : 0.0
 Total NaN values in row 13413 :- 0 and it's percentage : 0.0
 Total NaN values in row 13414 :- 0 and it's percentage : 0.0
 Total NaN values in row 13415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13416 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13417 :- 0 and it's percentage : 0.0
 Total NaN values in row 13418 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13419 :- 0 and it's percentage : 0.0
 Total NaN values in row 13420 :- 0 and it's percentage : 0.0
 Total NaN values in row 13421 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13422 :- 0 and it's percentage : 0.0
 Total NaN values in row 13423 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13424 :- 0 and it's percentage : 0.0
 Total NaN values in row 13425 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13426 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13427 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13428 :- 0 and it's percentage : 0.0
 Total NaN values in row 13429 :- 0 and it's percentage : 0.0
 Total NaN values in row 13430 :- 0 and it's percentage : 0.0
 Total NaN values in row 13431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13433 :- 0 and it's percentage : 0.0
 Total NaN values in row 13434 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13435 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13436 :- 0 and it's percentage : 0.0
 Total NaN values in row 13437 :- 0 and it's percentage : 0.0
 Total NaN values in row 13438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13440 :- 0 and it's percentage : 0.0
 Total NaN values in row 13441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13443 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13445 :- 0 and it's percentage : 0.0
 Total NaN values in row 13446 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13448 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13449 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13450 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13451 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13452 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13453 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13454 :- 0 and it's percentage : 0.0
 Total NaN values in row 13455 :- 0 and it's percentage : 0.0
 Total NaN values in row 13456 :- 0 and it's percentage : 0.0
 Total NaN values in row 13457 :- 0 and it's percentage : 0.0
 Total NaN values in row 13458 :- 0 and it's percentage : 0.0
 Total NaN values in row 13459 :- 0 and it's percentage : 0.0
 Total NaN values in row 13460 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13461 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13462 :- 0 and it's percentage : 0.0
 Total NaN values in row 13463 :- 0 and it's percentage : 0.0
 Total NaN values in row 13464 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13465 :- 0 and it's percentage : 0.0
 Total NaN values in row 13466 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13467 :- 0 and it's percentage : 0.0

 Total NaN values in row 13468 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13469 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13470 :- 0 and it's percentage : 0.0
 Total NaN values in row 13471 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13472 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13474 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13475 :- 0 and it's percentage : 0.0
 Total NaN values in row 13476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13477 :- 0 and it's percentage : 0.0
 Total NaN values in row 13478 :- 0 and it's percentage : 0.0
 Total NaN values in row 13479 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13480 :- 0 and it's percentage : 0.0
 Total NaN values in row 13481 :- 0 and it's percentage : 0.0
 Total NaN values in row 13482 :- 0 and it's percentage : 0.0
 Total NaN values in row 13483 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13484 :- 0 and it's percentage : 0.0
 Total NaN values in row 13485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13486 :- 0 and it's percentage : 0.0
 Total NaN values in row 13487 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13488 :- 0 and it's percentage : 0.0
 Total NaN values in row 13489 :- 0 and it's percentage : 0.0
 Total NaN values in row 13490 :- 0 and it's percentage : 0.0
 Total NaN values in row 13491 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13492 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13493 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13494 :- 0 and it's percentage : 0.0
 Total NaN values in row 13495 :- 0 and it's percentage : 0.0
 Total NaN values in row 13496 :- 0 and it's percentage : 0.0
 Total NaN values in row 13497 :- 0 and it's percentage : 0.0
 Total NaN values in row 13498 :- 0 and it's percentage : 0.0
 Total NaN values in row 13499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13500 :- 0 and it's percentage : 0.0
 Total NaN values in row 13501 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13502 :- 0 and it's percentage : 0.0
 Total NaN values in row 13503 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13504 :- 0 and it's percentage : 0.0
 Total NaN values in row 13505 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13506 :- 0 and it's percentage : 0.0
 Total NaN values in row 13507 :- 0 and it's percentage : 0.0
 Total NaN values in row 13508 :- 0 and it's percentage : 0.0
 Total NaN values in row 13509 :- 0 and it's percentage : 0.0
 Total NaN values in row 13510 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13511 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13512 :- 0 and it's percentage : 0.0
 Total NaN values in row 13513 :- 0 and it's percentage : 0.0
 Total NaN values in row 13514 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13515 :- 0 and it's percentage : 0.0
 Total NaN values in row 13516 :- 0 and it's percentage : 0.0
 Total NaN values in row 13517 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13518 :- 0 and it's percentage : 0.0
 Total NaN values in row 13519 :- 0 and it's percentage : 0.0
 Total NaN values in row 13520 :- 0 and it's percentage : 0.0
 Total NaN values in row 13521 :- 0 and it's percentage : 0.0
 Total NaN values in row 13522 :- 0 and it's percentage : 0.0
 Total NaN values in row 13523 :- 0 and it's percentage : 0.0
 Total NaN values in row 13524 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13525 :- 0 and it's percentage : 0.0
 Total NaN values in row 13526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13527 :- 0 and it's percentage : 0.0
 Total NaN values in row 13528 :- 0 and it's percentage : 0.0
 Total NaN values in row 13529 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13530 :- 0 and it's percentage : 0.0
 Total NaN values in row 13531 :- 0 and it's percentage : 0.0
 Total NaN values in row 13532 :- 0 and it's percentage : 0.0
 Total NaN values in row 13533 :- 0 and it's percentage : 0.0
 Total NaN values in row 13534 :- 0 and it's percentage : 0.0
 Total NaN values in row 13535 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13538 :- 0 and it's percentage : 0.0
 Total NaN values in row 13539 :- 0 and it's percentage : 0.0
 Total NaN values in row 13540 :- 0 and it's percentage : 0.0
 Total NaN values in row 13541 :- 0 and it's percentage : 0.0
 Total NaN values in row 13542 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13543 :- 0 and it's percentage : 0.0
 Total NaN values in row 13544 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13545 :- 0 and it's percentage : 0.0
 Total NaN values in row 13546 :- 0 and it's percentage : 0.0
 Total NaN values in row 13547 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13548 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13549 :- 0 and it's percentage : 0.0
 Total NaN values in row 13550 :- 0 and it's percentage : 0.0
 Total NaN values in row 13551 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13552 :- 0 and it's percentage : 0.0
 Total NaN values in row 13553 :- 0 and it's percentage : 0.0
 Total NaN values in row 13554 :- 0 and it's percentage : 0.0
 Total NaN values in row 13555 :- 0 and it's percentage : 0.0
 Total NaN values in row 13556 :- 0 and it's percentage : 0.0
 Total NaN values in row 13557 :- 0 and it's percentage : 0.0
 Total NaN values in row 13558 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13559 :- 0 and it's percentage : 0.0
 Total NaN values in row 13560 :- 0 and it's percentage : 0.0
 Total NaN values in row 13561 :- 0 and it's percentage : 0.0
 Total NaN values in row 13562 :- 0 and it's percentage : 0.0
 Total NaN values in row 13563 :- 0 and it's percentage : 0.0
 Total NaN values in row 13564 :- 0 and it's percentage : 0.0
 Total NaN values in row 13565 :- 0 and it's percentage : 0.0
 Total NaN values in row 13566 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13567 :- 0 and it's percentage : 0.0
 Total NaN values in row 13568 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13569 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13570 :- 0 and it's percentage : 0.0
 Total NaN values in row 13571 :- 0 and it's percentage : 0.0
 Total NaN values in row 13572 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13573 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13574 :- 0 and it's percentage : 0.0
 Total NaN values in row 13575 :- 0 and it's percentage : 0.0
 Total NaN values in row 13576 :- 0 and it's percentage : 0.0
 Total NaN values in row 13577 :- 0 and it's percentage : 0.0
 Total NaN values in row 13578 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13579 :- 0 and it's percentage : 0.0
 Total NaN values in row 13580 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13581 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13582 :- 0 and it's percentage : 0.0
 Total NaN values in row 13583 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13584 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13585 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13586 :- 0 and it's percentage : 0.0
 Total NaN values in row 13587 :- 0 and it's percentage : 0.0
 Total NaN values in row 13588 :- 0 and it's percentage : 0.0
 Total NaN values in row 13589 :- 0 and it's percentage : 0.0
 Total NaN values in row 13590 :- 0 and it's percentage : 0.0
 Total NaN values in row 13591 :- 0 and it's percentage : 0.0
 Total NaN values in row 13592 :- 0 and it's percentage : 0.0
 Total NaN values in row 13593 :- 0 and it's percentage : 0.0
 Total NaN values in row 13594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13595 :- 0 and it's percentage : 0.0

 Total NaN values in row 13596 :- 0 and it's percentage : 0.0
 Total NaN values in row 13597 :- 0 and it's percentage : 0.0
 Total NaN values in row 13598 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13599 :- 0 and it's percentage : 0.0
 Total NaN values in row 13600 :- 0 and it's percentage : 0.0
 Total NaN values in row 13601 :- 0 and it's percentage : 0.0
 Total NaN values in row 13602 :- 0 and it's percentage : 0.0
 Total NaN values in row 13603 :- 0 and it's percentage : 0.0
 Total NaN values in row 13604 :- 0 and it's percentage : 0.0
 Total NaN values in row 13605 :- 0 and it's percentage : 0.0
 Total NaN values in row 13606 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13608 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13609 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13610 :- 0 and it's percentage : 0.0
 Total NaN values in row 13611 :- 0 and it's percentage : 0.0
 Total NaN values in row 13612 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13613 :- 0 and it's percentage : 0.0
 Total NaN values in row 13614 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13615 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13616 :- 0 and it's percentage : 0.0
 Total NaN values in row 13617 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13618 :- 0 and it's percentage : 0.0
 Total NaN values in row 13619 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 13620 :- 0 and it's percentage : 0.0
 Total NaN values in row 13621 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13622 :- 0 and it's percentage : 0.0
 Total NaN values in row 13623 :- 0 and it's percentage : 0.0
 Total NaN values in row 13624 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13625 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13626 :- 0 and it's percentage : 0.0
 Total NaN values in row 13627 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13629 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13630 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13631 :- 0 and it's percentage : 0.0
 Total NaN values in row 13632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13633 :- 0 and it's percentage : 0.0
 Total NaN values in row 13634 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13635 :- 0 and it's percentage : 0.0
 Total NaN values in row 13636 :- 0 and it's percentage : 0.0
 Total NaN values in row 13637 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13638 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13639 :- 0 and it's percentage : 0.0
 Total NaN values in row 13640 :- 0 and it's percentage : 0.0
 Total NaN values in row 13641 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13642 :- 0 and it's percentage : 0.0
 Total NaN values in row 13643 :- 0 and it's percentage : 0.0
 Total NaN values in row 13644 :- 0 and it's percentage : 0.0
 Total NaN values in row 13645 :- 0 and it's percentage : 0.0
 Total NaN values in row 13646 :- 0 and it's percentage : 0.0
 Total NaN values in row 13647 :- 0 and it's percentage : 0.0
 Total NaN values in row 13648 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13649 :- 0 and it's percentage : 0.0
 Total NaN values in row 13650 :- 0 and it's percentage : 0.0
 Total NaN values in row 13651 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13652 :- 0 and it's percentage : 0.0
 Total NaN values in row 13653 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13654 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13655 :- 0 and it's percentage : 0.0
 Total NaN values in row 13656 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13657 :- 0 and it's percentage : 0.0
 Total NaN values in row 13658 :- 0 and it's percentage : 0.0
 Total NaN values in row 13659 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13660 :- 0 and it's percentage : 0.0
 Total NaN values in row 13661 :- 0 and it's percentage : 0.0
 Total NaN values in row 13662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13663 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13664 :- 0 and it's percentage : 0.0
 Total NaN values in row 13665 :- 0 and it's percentage : 0.0
 Total NaN values in row 13666 :- 0 and it's percentage : 0.0
 Total NaN values in row 13667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13669 :- 0 and it's percentage : 0.0
 Total NaN values in row 13670 :- 0 and it's percentage : 0.0
 Total NaN values in row 13671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13673 :- 0 and it's percentage : 0.0
 Total NaN values in row 13674 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13675 :- 0 and it's percentage : 0.0
 Total NaN values in row 13676 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13677 :- 0 and it's percentage : 0.0
 Total NaN values in row 13678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13679 :- 0 and it's percentage : 0.0
 Total NaN values in row 13680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13681 :- 0 and it's percentage : 0.0
 Total NaN values in row 13682 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13683 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13684 :- 0 and it's percentage : 0.0
 Total NaN values in row 13685 :- 0 and it's percentage : 0.0
 Total NaN values in row 13686 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13688 :- 0 and it's percentage : 0.0
 Total NaN values in row 13689 :- 0 and it's percentage : 0.0
 Total NaN values in row 13690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13691 :- 0 and it's percentage : 0.0
 Total NaN values in row 13692 :- 0 and it's percentage : 0.0
 Total NaN values in row 13693 :- 0 and it's percentage : 0.0
 Total NaN values in row 13694 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13695 :- 0 and it's percentage : 0.0
 Total NaN values in row 13696 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13697 :- 0 and it's percentage : 0.0
 Total NaN values in row 13698 :- 0 and it's percentage : 0.0
 Total NaN values in row 13699 :- 0 and it's percentage : 0.0
 Total NaN values in row 13700 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13701 :- 0 and it's percentage : 0.0
 Total NaN values in row 13702 :- 0 and it's percentage : 0.0
 Total NaN values in row 13703 :- 0 and it's percentage : 0.0
 Total NaN values in row 13704 :- 0 and it's percentage : 0.0
 Total NaN values in row 13705 :- 0 and it's percentage : 0.0
 Total NaN values in row 13706 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13707 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13708 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13709 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13710 :- 0 and it's percentage : 0.0
 Total NaN values in row 13711 :- 0 and it's percentage : 0.0
 Total NaN values in row 13712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13713 :- 0 and it's percentage : 0.0
 Total NaN values in row 13714 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13715 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13716 :- 0 and it's percentage : 0.0
 Total NaN values in row 13717 :- 0 and it's percentage : 0.0

 Total NaN values in row 13718 :- 0 and it's percentage : 0.0
 Total NaN values in row 13719 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13720 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13721 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13722 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13723 :- 0 and it's percentage : 0.0
 Total NaN values in row 13724 :- 0 and it's percentage : 0.0
 Total NaN values in row 13725 :- 0 and it's percentage : 0.0
 Total NaN values in row 13726 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13727 :- 0 and it's percentage : 0.0
 Total NaN values in row 13728 :- 0 and it's percentage : 0.0
 Total NaN values in row 13729 :- 0 and it's percentage : 0.0
 Total NaN values in row 13730 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13731 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13732 :- 0 and it's percentage : 0.0
 Total NaN values in row 13733 :- 0 and it's percentage : 0.0
 Total NaN values in row 13734 :- 0 and it's percentage : 0.0
 Total NaN values in row 13735 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13736 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13737 :- 0 and it's percentage : 0.0
 Total NaN values in row 13738 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13739 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13740 :- 0 and it's percentage : 0.0
 Total NaN values in row 13741 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13742 :- 0 and it's percentage : 0.0
 Total NaN values in row 13743 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13744 :- 0 and it's percentage : 0.0
 Total NaN values in row 13745 :- 0 and it's percentage : 0.0
 Total NaN values in row 13746 :- 0 and it's percentage : 0.0
 Total NaN values in row 13747 :- 0 and it's percentage : 0.0
 Total NaN values in row 13748 :- 0 and it's percentage : 0.0
 Total NaN values in row 13749 :- 0 and it's percentage : 0.0
 Total NaN values in row 13750 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13751 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13752 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13753 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13754 :- 0 and it's percentage : 0.0
 Total NaN values in row 13755 :- 0 and it's percentage : 0.0
 Total NaN values in row 13756 :- 0 and it's percentage : 0.0
 Total NaN values in row 13757 :- 0 and it's percentage : 0.0
 Total NaN values in row 13758 :- 0 and it's percentage : 0.0
 Total NaN values in row 13759 :- 0 and it's percentage : 0.0
 Total NaN values in row 13760 :- 0 and it's percentage : 0.0
 Total NaN values in row 13761 :- 0 and it's percentage : 0.0
 Total NaN values in row 13762 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13763 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13764 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13765 :- 0 and it's percentage : 0.0
 Total NaN values in row 13766 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13767 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13769 :- 0 and it's percentage : 0.0
 Total NaN values in row 13770 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13771 :- 0 and it's percentage : 0.0
 Total NaN values in row 13772 :- 0 and it's percentage : 0.0
 Total NaN values in row 13773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13774 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13775 :- 0 and it's percentage : 0.0
 Total NaN values in row 13776 :- 0 and it's percentage : 0.0
 Total NaN values in row 13777 :- 0 and it's percentage : 0.0
 Total NaN values in row 13778 :- 0 and it's percentage : 0.0
 Total NaN values in row 13779 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13782 :- 0 and it's percentage : 0.0
 Total NaN values in row 13783 :- 0 and it's percentage : 0.0
 Total NaN values in row 13784 :- 0 and it's percentage : 0.0
 Total NaN values in row 13785 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13786 :- 0 and it's percentage : 0.0
 Total NaN values in row 13787 :- 0 and it's percentage : 0.0
 Total NaN values in row 13788 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13789 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13790 :- 0 and it's percentage : 0.0
 Total NaN values in row 13791 :- 0 and it's percentage : 0.0
 Total NaN values in row 13792 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13793 :- 0 and it's percentage : 0.0
 Total NaN values in row 13794 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13796 :- 0 and it's percentage : 0.0
 Total NaN values in row 13797 :- 0 and it's percentage : 0.0
 Total NaN values in row 13798 :- 0 and it's percentage : 0.0
 Total NaN values in row 13799 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13800 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13801 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13802 :- 0 and it's percentage : 0.0
 Total NaN values in row 13803 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13804 :- 0 and it's percentage : 0.0
 Total NaN values in row 13805 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13806 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13809 :- 0 and it's percentage : 0.0
 Total NaN values in row 13810 :- 0 and it's percentage : 0.0
 Total NaN values in row 13811 :- 0 and it's percentage : 0.0
 Total NaN values in row 13812 :- 0 and it's percentage : 0.0
 Total NaN values in row 13813 :- 0 and it's percentage : 0.0
 Total NaN values in row 13814 :- 0 and it's percentage : 0.0
 Total NaN values in row 13815 :- 0 and it's percentage : 0.0
 Total NaN values in row 13816 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13817 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13818 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13819 :- 0 and it's percentage : 0.0
 Total NaN values in row 13820 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13821 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13822 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13823 :- 0 and it's percentage : 0.0
 Total NaN values in row 13824 :- 0 and it's percentage : 0.0
 Total NaN values in row 13825 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13826 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13827 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13828 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13829 :- 0 and it's percentage : 0.0
 Total NaN values in row 13830 :- 0 and it's percentage : 0.0
 Total NaN values in row 13831 :- 0 and it's percentage : 0.0
 Total NaN values in row 13832 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13833 :- 0 and it's percentage : 0.0
 Total NaN values in row 13834 :- 0 and it's percentage : 0.0
 Total NaN values in row 13835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13836 :- 0 and it's percentage : 0.0
 Total NaN values in row 13837 :- 0 and it's percentage : 0.0
 Total NaN values in row 13838 :- 0 and it's percentage : 0.0
 Total NaN values in row 13839 :- 0 and it's percentage : 0.0
 Total NaN values in row 13840 :- 0 and it's percentage : 0.0
 Total NaN values in row 13841 :- 0 and it's percentage : 0.0
 Total NaN values in row 13842 :- 0 and it's percentage : 0.0
 Total NaN values in row 13843 :- 0 and it's percentage : 0.0
 Total NaN values in row 13844 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13845 :- 0 and it's percentage : 0.0
 Total NaN values in row 13846 :- 0 and it's percentage : 0.0
 Total NaN values in row 13847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13848 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 13849 :- 0 and it's percentage : 0.0
 Total NaN values in row 13850 :- 0 and it's percentage : 0.0
 Total NaN values in row 13851 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13852 :- 0 and it's percentage : 0.0
 Total NaN values in row 13853 :- 0 and it's percentage : 0.0
 Total NaN values in row 13854 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13855 :- 0 and it's percentage : 0.0
 Total NaN values in row 13856 :- 0 and it's percentage : 0.0
 Total NaN values in row 13857 :- 0 and it's percentage : 0.0
 Total NaN values in row 13858 :- 0 and it's percentage : 0.0
 Total NaN values in row 13859 :- 0 and it's percentage : 0.0
 Total NaN values in row 13860 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13861 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13862 :- 0 and it's percentage : 0.0
 Total NaN values in row 13863 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13864 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13865 :- 0 and it's percentage : 0.0
 Total NaN values in row 13866 :- 0 and it's percentage : 0.0
 Total NaN values in row 13867 :- 0 and it's percentage : 0.0
 Total NaN values in row 13868 :- 0 and it's percentage : 0.0
 Total NaN values in row 13869 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13870 :- 0 and it's percentage : 0.0
 Total NaN values in row 13871 :- 0 and it's percentage : 0.0
 Total NaN values in row 13872 :- 0 and it's percentage : 0.0
 Total NaN values in row 13873 :- 0 and it's percentage : 0.0
 Total NaN values in row 13874 :- 0 and it's percentage : 0.0
 Total NaN values in row 13875 :- 0 and it's percentage : 0.0
 Total NaN values in row 13876 :- 0 and it's percentage : 0.0
 Total NaN values in row 13877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13878 :- 0 and it's percentage : 0.0
 Total NaN values in row 13879 :- 0 and it's percentage : 0.0
 Total NaN values in row 13880 :- 0 and it's percentage : 0.0
 Total NaN values in row 13881 :- 0 and it's percentage : 0.0
 Total NaN values in row 13882 :- 0 and it's percentage : 0.0
 Total NaN values in row 13883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13884 :- 0 and it's percentage : 0.0
 Total NaN values in row 13885 :- 0 and it's percentage : 0.0
 Total NaN values in row 13886 :- 0 and it's percentage : 0.0
 Total NaN values in row 13887 :- 0 and it's percentage : 0.0
 Total NaN values in row 13888 :- 0 and it's percentage : 0.0
 Total NaN values in row 13889 :- 0 and it's percentage : 0.0
 Total NaN values in row 13890 :- 0 and it's percentage : 0.0
 Total NaN values in row 13891 :- 0 and it's percentage : 0.0
 Total NaN values in row 13892 :- 0 and it's percentage : 0.0
 Total NaN values in row 13893 :- 0 and it's percentage : 0.0
 Total NaN values in row 13894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13895 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13896 :- 0 and it's percentage : 0.0
 Total NaN values in row 13897 :- 0 and it's percentage : 0.0
 Total NaN values in row 13898 :- 0 and it's percentage : 0.0
 Total NaN values in row 13899 :- 0 and it's percentage : 0.0
 Total NaN values in row 13900 :- 0 and it's percentage : 0.0
 Total NaN values in row 13901 :- 0 and it's percentage : 0.0
 Total NaN values in row 13902 :- 0 and it's percentage : 0.0
 Total NaN values in row 13903 :- 0 and it's percentage : 0.0
 Total NaN values in row 13904 :- 0 and it's percentage : 0.0
 Total NaN values in row 13905 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13906 :- 0 and it's percentage : 0.0
 Total NaN values in row 13907 :- 0 and it's percentage : 0.0
 Total NaN values in row 13908 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13909 :- 0 and it's percentage : 0.0
 Total NaN values in row 13910 :- 0 and it's percentage : 0.0
 Total NaN values in row 13911 :- 0 and it's percentage : 0.0
 Total NaN values in row 13912 :- 0 and it's percentage : 0.0
 Total NaN values in row 13913 :- 0 and it's percentage : 0.0
 Total NaN values in row 13914 :- 0 and it's percentage : 0.0
 Total NaN values in row 13915 :- 0 and it's percentage : 0.0
 Total NaN values in row 13916 :- 0 and it's percentage : 0.0
 Total NaN values in row 13917 :- 0 and it's percentage : 0.0
 Total NaN values in row 13918 :- 0 and it's percentage : 0.0
 Total NaN values in row 13919 :- 0 and it's percentage : 0.0
 Total NaN values in row 13920 :- 0 and it's percentage : 0.0
 Total NaN values in row 13921 :- 0 and it's percentage : 0.0
 Total NaN values in row 13922 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 13923 :- 0 and it's percentage : 0.0
 Total NaN values in row 13924 :- 0 and it's percentage : 0.0
 Total NaN values in row 13925 :- 0 and it's percentage : 0.0
 Total NaN values in row 13926 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13927 :- 0 and it's percentage : 0.0
 Total NaN values in row 13928 :- 0 and it's percentage : 0.0
 Total NaN values in row 13929 :- 0 and it's percentage : 0.0
 Total NaN values in row 13930 :- 0 and it's percentage : 0.0
 Total NaN values in row 13931 :- 0 and it's percentage : 0.0
 Total NaN values in row 13932 :- 0 and it's percentage : 0.0
 Total NaN values in row 13933 :- 0 and it's percentage : 0.0
 Total NaN values in row 13934 :- 0 and it's percentage : 0.0
 Total NaN values in row 13935 :- 0 and it's percentage : 0.0
 Total NaN values in row 13936 :- 0 and it's percentage : 0.0
 Total NaN values in row 13937 :- 0 and it's percentage : 0.0
 Total NaN values in row 13938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13939 :- 0 and it's percentage : 0.0
 Total NaN values in row 13940 :- 0 and it's percentage : 0.0
 Total NaN values in row 13941 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13942 :- 0 and it's percentage : 0.0
 Total NaN values in row 13943 :- 0 and it's percentage : 0.0
 Total NaN values in row 13944 :- 0 and it's percentage : 0.0
 Total NaN values in row 13945 :- 0 and it's percentage : 0.0
 Total NaN values in row 13946 :- 0 and it's percentage : 0.0
 Total NaN values in row 13947 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 13948 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13949 :- 0 and it's percentage : 0.0
 Total NaN values in row 13950 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13951 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 13952 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13953 :- 0 and it's percentage : 0.0
 Total NaN values in row 13954 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13955 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13956 :- 0 and it's percentage : 0.0
 Total NaN values in row 13957 :- 0 and it's percentage : 0.0
 Total NaN values in row 13958 :- 0 and it's percentage : 0.0
 Total NaN values in row 13959 :- 0 and it's percentage : 0.0
 Total NaN values in row 13960 :- 0 and it's percentage : 0.0
 Total NaN values in row 13961 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13962 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13963 :- 0 and it's percentage : 0.0
 Total NaN values in row 13964 :- 0 and it's percentage : 0.0
 Total NaN values in row 13965 :- 0 and it's percentage : 0.0
 Total NaN values in row 13966 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13967 :- 0 and it's percentage : 0.0
 Total NaN values in row 13968 :- 0 and it's percentage : 0.0
 Total NaN values in row 13969 :- 0 and it's percentage : 0.0
 Total NaN values in row 13970 :- 0 and it's percentage : 0.0
 Total NaN values in row 13971 :- 0 and it's percentage : 0.0
 Total NaN values in row 13972 :- 0 and it's percentage : 0.0
 Total NaN values in row 13973 :- 0 and it's percentage : 0.0
 Total NaN values in row 13974 :- 0 and it's percentage : 0.0
 Total NaN values in row 13975 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13976 :- 0 and it's percentage : 0.0
 Total NaN values in row 13977 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13978 :- 0 and it's percentage : 0.0
 Total NaN values in row 13979 :- 0 and it's percentage : 0.0
 Total NaN values in row 13980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13981 :- 0 and it's percentage : 0.0
 Total NaN values in row 13982 :- 0 and it's percentage : 0.0
 Total NaN values in row 13983 :- 0 and it's percentage : 0.0
 Total NaN values in row 13984 :- 0 and it's percentage : 0.0
 Total NaN values in row 13985 :- 0 and it's percentage : 0.0
 Total NaN values in row 13986 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13987 :- 0 and it's percentage : 0.0
 Total NaN values in row 13988 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13989 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13990 :- 0 and it's percentage : 0.0
 Total NaN values in row 13991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13992 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13993 :- 0 and it's percentage : 0.0
 Total NaN values in row 13994 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13995 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13996 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 13997 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 13998 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 13999 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14000 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14001 :- 0 and it's percentage : 0.0
 Total NaN values in row 14002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14003 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 14004 :- 0 and it's percentage : 0.0
 Total NaN values in row 14005 :- 0 and it's percentage : 0.0
 Total NaN values in row 14006 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14007 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14008 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14009 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 14010 :- 0 and it's percentage : 0.0
 Total NaN values in row 14011 :- 0 and it's percentage : 0.0

 Total NaN values in row 14012 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14013 :- 0 and it's percentage : 0.0
 Total NaN values in row 14014 :- 0 and it's percentage : 0.0
 Total NaN values in row 14015 :- 0 and it's percentage : 0.0
 Total NaN values in row 14016 :- 0 and it's percentage : 0.0
 Total NaN values in row 14017 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14018 :- 0 and it's percentage : 0.0
 Total NaN values in row 14019 :- 0 and it's percentage : 0.0
 Total NaN values in row 14020 :- 0 and it's percentage : 0.0
 Total NaN values in row 14021 :- 0 and it's percentage : 0.0
 Total NaN values in row 14022 :- 0 and it's percentage : 0.0
 Total NaN values in row 14023 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14024 :- 0 and it's percentage : 0.0
 Total NaN values in row 14025 :- 0 and it's percentage : 0.0
 Total NaN values in row 14026 :- 0 and it's percentage : 0.0
 Total NaN values in row 14027 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14029 :- 0 and it's percentage : 0.0
 Total NaN values in row 14030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14031 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14032 :- 0 and it's percentage : 0.0
 Total NaN values in row 14033 :- 0 and it's percentage : 0.0
 Total NaN values in row 14034 :- 0 and it's percentage : 0.0
 Total NaN values in row 14035 :- 0 and it's percentage : 0.0
 Total NaN values in row 14036 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14037 :- 0 and it's percentage : 0.0
 Total NaN values in row 14038 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 14039 :- 0 and it's percentage : 0.0
 Total NaN values in row 14040 :- 0 and it's percentage : 0.0
 Total NaN values in row 14041 :- 0 and it's percentage : 0.0
 Total NaN values in row 14042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14043 :- 0 and it's percentage : 0.0
 Total NaN values in row 14044 :- 0 and it's percentage : 0.0
 Total NaN values in row 14045 :- 0 and it's percentage : 0.0
 Total NaN values in row 14046 :- 0 and it's percentage : 0.0
 Total NaN values in row 14047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14048 :- 0 and it's percentage : 0.0
 Total NaN values in row 14049 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14051 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14052 :- 0 and it's percentage : 0.0
 Total NaN values in row 14053 :- 0 and it's percentage : 0.0
 Total NaN values in row 14054 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14055 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14056 :- 0 and it's percentage : 0.0
 Total NaN values in row 14057 :- 0 and it's percentage : 0.0
 Total NaN values in row 14058 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14059 :- 0 and it's percentage : 0.0
 Total NaN values in row 14060 :- 0 and it's percentage : 0.0
 Total NaN values in row 14061 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14062 :- 0 and it's percentage : 0.0
 Total NaN values in row 14063 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14064 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14066 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14067 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14068 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14069 :- 0 and it's percentage : 0.0
 Total NaN values in row 14070 :- 0 and it's percentage : 0.0
 Total NaN values in row 14071 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14072 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14073 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14074 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14075 :- 0 and it's percentage : 0.0
 Total NaN values in row 14076 :- 0 and it's percentage : 0.0
 Total NaN values in row 14077 :- 0 and it's percentage : 0.0
 Total NaN values in row 14078 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14079 :- 0 and it's percentage : 0.0
 Total NaN values in row 14080 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14081 :- 0 and it's percentage : 0.0
 Total NaN values in row 14082 :- 0 and it's percentage : 0.0
 Total NaN values in row 14083 :- 0 and it's percentage : 0.0
 Total NaN values in row 14084 :- 0 and it's percentage : 0.0
 Total NaN values in row 14085 :- 0 and it's percentage : 0.0
 Total NaN values in row 14086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14087 :- 0 and it's percentage : 0.0
 Total NaN values in row 14088 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14090 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14091 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14092 :- 0 and it's percentage : 0.0
 Total NaN values in row 14093 :- 0 and it's percentage : 0.0
 Total NaN values in row 14094 :- 0 and it's percentage : 0.0
 Total NaN values in row 14095 :- 0 and it's percentage : 0.0
 Total NaN values in row 14096 :- 0 and it's percentage : 0.0
 Total NaN values in row 14097 :- 0 and it's percentage : 0.0
 Total NaN values in row 14098 :- 0 and it's percentage : 0.0
 Total NaN values in row 14099 :- 0 and it's percentage : 0.0
 Total NaN values in row 14100 :- 0 and it's percentage : 0.0
 Total NaN values in row 14101 :- 0 and it's percentage : 0.0
 Total NaN values in row 14102 :- 0 and it's percentage : 0.0
 Total NaN values in row 14103 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14104 :- 0 and it's percentage : 0.0
 Total NaN values in row 14105 :- 0 and it's percentage : 0.0
 Total NaN values in row 14106 :- 0 and it's percentage : 0.0
 Total NaN values in row 14107 :- 0 and it's percentage : 0.0
 Total NaN values in row 14108 :- 0 and it's percentage : 0.0
 Total NaN values in row 14109 :- 0 and it's percentage : 0.0
 Total NaN values in row 14110 :- 0 and it's percentage : 0.0
 Total NaN values in row 14111 :- 0 and it's percentage : 0.0
 Total NaN values in row 14112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14113 :- 0 and it's percentage : 0.0
 Total NaN values in row 14114 :- 0 and it's percentage : 0.0
 Total NaN values in row 14115 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14116 :- 0 and it's percentage : 0.0
 Total NaN values in row 14117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14118 :- 0 and it's percentage : 0.0
 Total NaN values in row 14119 :- 0 and it's percentage : 0.0
 Total NaN values in row 14120 :- 0 and it's percentage : 0.0
 Total NaN values in row 14121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14122 :- 0 and it's percentage : 0.0
 Total NaN values in row 14123 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14124 :- 0 and it's percentage : 0.0
 Total NaN values in row 14125 :- 0 and it's percentage : 0.0
 Total NaN values in row 14126 :- 0 and it's percentage : 0.0
 Total NaN values in row 14127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14129 :- 0 and it's percentage : 0.0
 Total NaN values in row 14130 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14131 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14132 :- 0 and it's percentage : 0.0
 Total NaN values in row 14133 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 14134 :- 0 and it's percentage : 0.0
 Total NaN values in row 14135 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 14136 :- 0 and it's percentage : 0.0
 Total NaN values in row 14137 :- 0 and it's percentage : 0.0
 Total NaN values in row 14138 :- 0 and it's percentage : 0.0
 Total NaN values in row 14139 :- 0 and it's percentage : 0.0
 Total NaN values in row 14140 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 14141 :- 0 and it's percentage : 0.0
 Total NaN values in row 14142 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 14143 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 14144 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 14145 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14147 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14148 :- 0 and it's percentage : 0.0
 Total NaN values in row 14149 :- 0 and it's percentage : 0.0
 Total NaN values in row 14150 :- 0 and it's percentage : 0.0
 Total NaN values in row 14151 :- 0 and it's percentage : 0.0
 Total NaN values in row 14152 :- 0 and it's percentage : 0.0
 Total NaN values in row 14153 :- 0 and it's percentage : 0.0
 Total NaN values in row 14154 :- 0 and it's percentage : 0.0
 Total NaN values in row 14155 :- 0 and it's percentage : 0.0
 Total NaN values in row 14156 :- 0 and it's percentage : 0.0
 Total NaN values in row 14157 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14158 :- 0 and it's percentage : 0.0
 Total NaN values in row 14159 :- 0 and it's percentage : 0.0
 Total NaN values in row 14160 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14161 :- 0 and it's percentage : 0.0
 Total NaN values in row 14162 :- 0 and it's percentage : 0.0
 Total NaN values in row 14163 :- 0 and it's percentage : 0.0
 Total NaN values in row 14164 :- 0 and it's percentage : 0.0
 Total NaN values in row 14165 :- 0 and it's percentage : 0.0
 Total NaN values in row 14166 :- 0 and it's percentage : 0.0
 Total NaN values in row 14167 :- 0 and it's percentage : 0.0
 Total NaN values in row 14168 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14169 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14170 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14171 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14172 :- 0 and it's percentage : 0.0
 Total NaN values in row 14173 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14174 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14175 :- 0 and it's percentage : 0.0
 Total NaN values in row 14176 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14177 :- 0 and it's percentage : 0.0
 Total NaN values in row 14178 :- 0 and it's percentage : 0.0
 Total NaN values in row 14179 :- 0 and it's percentage : 0.0
 Total NaN values in row 14180 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14181 :- 0 and it's percentage : 0.0
 Total NaN values in row 14182 :- 0 and it's percentage : 0.0
 Total NaN values in row 14183 :- 0 and it's percentage : 0.0

 Total NaN values in row 14184 :- 0 and it's percentage : 0.0
 Total NaN values in row 14185 :- 0 and it's percentage : 0.0
 Total NaN values in row 14186 :- 0 and it's percentage : 0.0
 Total NaN values in row 14187 :- 0 and it's percentage : 0.0
 Total NaN values in row 14188 :- 0 and it's percentage : 0.0
 Total NaN values in row 14189 :- 0 and it's percentage : 0.0
 Total NaN values in row 14190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14191 :- 0 and it's percentage : 0.0
 Total NaN values in row 14192 :- 0 and it's percentage : 0.0
 Total NaN values in row 14193 :- 0 and it's percentage : 0.0
 Total NaN values in row 14194 :- 0 and it's percentage : 0.0
 Total NaN values in row 14195 :- 0 and it's percentage : 0.0
 Total NaN values in row 14196 :- 0 and it's percentage : 0.0
 Total NaN values in row 14197 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14198 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14199 :- 0 and it's percentage : 0.0
 Total NaN values in row 14200 :- 0 and it's percentage : 0.0
 Total NaN values in row 14201 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14202 :- 0 and it's percentage : 0.0
 Total NaN values in row 14203 :- 0 and it's percentage : 0.0
 Total NaN values in row 14204 :- 0 and it's percentage : 0.0
 Total NaN values in row 14205 :- 0 and it's percentage : 0.0
 Total NaN values in row 14206 :- 0 and it's percentage : 0.0
 Total NaN values in row 14207 :- 0 and it's percentage : 0.0
 Total NaN values in row 14208 :- 0 and it's percentage : 0.0
 Total NaN values in row 14209 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14210 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14211 :- 0 and it's percentage : 0.0
 Total NaN values in row 14212 :- 0 and it's percentage : 0.0
 Total NaN values in row 14213 :- 0 and it's percentage : 0.0
 Total NaN values in row 14214 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14216 :- 0 and it's percentage : 0.0
 Total NaN values in row 14217 :- 0 and it's percentage : 0.0
 Total NaN values in row 14218 :- 0 and it's percentage : 0.0
 Total NaN values in row 14219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14220 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14221 :- 0 and it's percentage : 0.0
 Total NaN values in row 14222 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14223 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14224 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14225 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14226 :- 0 and it's percentage : 0.0
 Total NaN values in row 14227 :- 0 and it's percentage : 0.0
 Total NaN values in row 14228 :- 0 and it's percentage : 0.0
 Total NaN values in row 14229 :- 0 and it's percentage : 0.0
 Total NaN values in row 14230 :- 0 and it's percentage : 0.0
 Total NaN values in row 14231 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14233 :- 0 and it's percentage : 0.0
 Total NaN values in row 14234 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14235 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14236 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14237 :- 0 and it's percentage : 0.0
 Total NaN values in row 14238 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14240 :- 0 and it's percentage : 0.0
 Total NaN values in row 14241 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14242 :- 0 and it's percentage : 0.0
 Total NaN values in row 14243 :- 0 and it's percentage : 0.0
 Total NaN values in row 14244 :- 0 and it's percentage : 0.0
 Total NaN values in row 14245 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14246 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14247 :- 0 and it's percentage : 0.0
 Total NaN values in row 14248 :- 0 and it's percentage : 0.0
 Total NaN values in row 14249 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14250 :- 0 and it's percentage : 0.0
 Total NaN values in row 14251 :- 0 and it's percentage : 0.0
 Total NaN values in row 14252 :- 0 and it's percentage : 0.0
 Total NaN values in row 14253 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14254 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14255 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14256 :- 0 and it's percentage : 0.0
 Total NaN values in row 14257 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14259 :- 0 and it's percentage : 0.0
 Total NaN values in row 14260 :- 0 and it's percentage : 0.0
 Total NaN values in row 14261 :- 0 and it's percentage : 0.0
 Total NaN values in row 14262 :- 0 and it's percentage : 0.0
 Total NaN values in row 14263 :- 0 and it's percentage : 0.0
 Total NaN values in row 14264 :- 0 and it's percentage : 0.0
 Total NaN values in row 14265 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14267 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14268 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14269 :- 0 and it's percentage : 0.0
 Total NaN values in row 14270 :- 0 and it's percentage : 0.0
 Total NaN values in row 14271 :- 0 and it's percentage : 0.0
 Total NaN values in row 14272 :- 0 and it's percentage : 0.0
 Total NaN values in row 14273 :- 0 and it's percentage : 0.0
 Total NaN values in row 14274 :- 0 and it's percentage : 0.0
 Total NaN values in row 14275 :- 0 and it's percentage : 0.0
 Total NaN values in row 14276 :- 0 and it's percentage : 0.0
 Total NaN values in row 14277 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14278 :- 0 and it's percentage : 0.0
 Total NaN values in row 14279 :- 0 and it's percentage : 0.0
 Total NaN values in row 14280 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14281 :- 0 and it's percentage : 0.0
 Total NaN values in row 14282 :- 0 and it's percentage : 0.0
 Total NaN values in row 14283 :- 0 and it's percentage : 0.0
 Total NaN values in row 14284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14285 :- 0 and it's percentage : 0.0
 Total NaN values in row 14286 :- 0 and it's percentage : 0.0
 Total NaN values in row 14287 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14288 :- 0 and it's percentage : 0.0
 Total NaN values in row 14289 :- 0 and it's percentage : 0.0
 Total NaN values in row 14290 :- 0 and it's percentage : 0.0
 Total NaN values in row 14291 :- 0 and it's percentage : 0.0
 Total NaN values in row 14292 :- 0 and it's percentage : 0.0
 Total NaN values in row 14293 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14294 :- 0 and it's percentage : 0.0
 Total NaN values in row 14295 :- 0 and it's percentage : 0.0
 Total NaN values in row 14296 :- 0 and it's percentage : 0.0
 Total NaN values in row 14297 :- 0 and it's percentage : 0.0
 Total NaN values in row 14298 :- 0 and it's percentage : 0.0
 Total NaN values in row 14299 :- 0 and it's percentage : 0.0
 Total NaN values in row 14300 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14301 :- 0 and it's percentage : 0.0
 Total NaN values in row 14302 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14303 :- 0 and it's percentage : 0.0
 Total NaN values in row 14304 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14305 :- 0 and it's percentage : 0.0
 Total NaN values in row 14306 :- 0 and it's percentage : 0.0
 Total NaN values in row 14307 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14308 :- 0 and it's percentage : 0.0
 Total NaN values in row 14309 :- 0 and it's percentage : 0.0
 Total NaN values in row 14310 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14311 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14312 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 14313 :- 0 and it's percentage : 0.0
 Total NaN values in row 14314 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14315 :- 0 and it's percentage : 0.0
 Total NaN values in row 14316 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14317 :- 0 and it's percentage : 0.0
 Total NaN values in row 14318 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14319 :- 0 and it's percentage : 0.0
 Total NaN values in row 14320 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14321 :- 0 and it's percentage : 0.0
 Total NaN values in row 14322 :- 0 and it's percentage : 0.0
 Total NaN values in row 14323 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14324 :- 0 and it's percentage : 0.0
 Total NaN values in row 14325 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14326 :- 0 and it's percentage : 0.0
 Total NaN values in row 14327 :- 0 and it's percentage : 0.0
 Total NaN values in row 14328 :- 0 and it's percentage : 0.0
 Total NaN values in row 14329 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14330 :- 0 and it's percentage : 0.0
 Total NaN values in row 14331 :- 0 and it's percentage : 0.0
 Total NaN values in row 14332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14333 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 14334 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14335 :- 0 and it's percentage : 0.0
 Total NaN values in row 14336 :- 0 and it's percentage : 0.0
 Total NaN values in row 14337 :- 0 and it's percentage : 0.0
 Total NaN values in row 14338 :- 0 and it's percentage : 0.0
 Total NaN values in row 14339 :- 0 and it's percentage : 0.0
 Total NaN values in row 14340 :- 0 and it's percentage : 0.0
 Total NaN values in row 14341 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14342 :- 0 and it's percentage : 0.0
 Total NaN values in row 14343 :- 0 and it's percentage : 0.0
 Total NaN values in row 14344 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14345 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14346 :- 0 and it's percentage : 0.0
 Total NaN values in row 14347 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14349 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14350 :- 0 and it's percentage : 0.0
 Total NaN values in row 14351 :- 0 and it's percentage : 0.0
 Total NaN values in row 14352 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14353 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14354 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14355 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14356 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14358 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14359 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14360 :- 0 and it's percentage : 0.0
 Total NaN values in row 14361 :- 0 and it's percentage : 0.0
 Total NaN values in row 14362 :- 0 and it's percentage : 0.0
 Total NaN values in row 14363 :- 0 and it's percentage : 0.0
 Total NaN values in row 14364 :- 0 and it's percentage : 0.0
 Total NaN values in row 14365 :- 0 and it's percentage : 0.0
 Total NaN values in row 14366 :- 0 and it's percentage : 0.0
 Total NaN values in row 14367 :- 0 and it's percentage : 0.0
 Total NaN values in row 14368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14369 :- 0 and it's percentage : 0.0
 Total NaN values in row 14370 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14371 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14372 :- 0 and it's percentage : 0.0
 Total NaN values in row 14373 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14374 :- 0 and it's percentage : 0.0
 Total NaN values in row 14375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14376 :- 0 and it's percentage : 0.0
 Total NaN values in row 14377 :- 0 and it's percentage : 0.0
 Total NaN values in row 14378 :- 0 and it's percentage : 0.0
 Total NaN values in row 14379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14380 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14381 :- 0 and it's percentage : 0.0
 Total NaN values in row 14382 :- 0 and it's percentage : 0.0
 Total NaN values in row 14383 :- 0 and it's percentage : 0.0
 Total NaN values in row 14384 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14385 :- 0 and it's percentage : 0.0
 Total NaN values in row 14386 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14387 :- 0 and it's percentage : 0.0
 Total NaN values in row 14388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14389 :- 0 and it's percentage : 0.0
 Total NaN values in row 14390 :- 0 and it's percentage : 0.0
 Total NaN values in row 14391 :- 0 and it's percentage : 0.0
 Total NaN values in row 14392 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14393 :- 0 and it's percentage : 0.0
 Total NaN values in row 14394 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14395 :- 0 and it's percentage : 0.0
 Total NaN values in row 14396 :- 0 and it's percentage : 0.0
 Total NaN values in row 14397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14398 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14399 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14400 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14401 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14402 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14403 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14404 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14405 :- 0 and it's percentage : 0.0
 Total NaN values in row 14406 :- 0 and it's percentage : 0.0
 Total NaN values in row 14407 :- 0 and it's percentage : 0.0
 Total NaN values in row 14408 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14409 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14410 :- 0 and it's percentage : 0.0
 Total NaN values in row 14411 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14412 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14413 :- 0 and it's percentage : 0.0
 Total NaN values in row 14414 :- 0 and it's percentage : 0.0
 Total NaN values in row 14415 :- 0 and it's percentage : 0.0
 Total NaN values in row 14416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14417 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14418 :- 0 and it's percentage : 0.0
 Total NaN values in row 14419 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14420 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14421 :- 0 and it's percentage : 0.0
 Total NaN values in row 14422 :- 0 and it's percentage : 0.0
 Total NaN values in row 14423 :- 0 and it's percentage : 0.0
 Total NaN values in row 14424 :- 0 and it's percentage : 0.0
 Total NaN values in row 14425 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14426 :- 0 and it's percentage : 0.0
 Total NaN values in row 14427 :- 0 and it's percentage : 0.0
 Total NaN values in row 14428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14429 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14433 :- 0 and it's percentage : 0.0
 Total NaN values in row 14434 :- 0 and it's percentage : 0.0
 Total NaN values in row 14435 :- 0 and it's percentage : 0.0
 Total NaN values in row 14436 :- 0 and it's percentage : 0.0
 Total NaN values in row 14437 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14439 :- 0 and it's percentage : 0.0
 Total NaN values in row 14440 :- 0 and it's percentage : 0.0
 Total NaN values in row 14441 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14442 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14443 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14445 :- 0 and it's percentage : 0.0
 Total NaN values in row 14446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14448 :- 0 and it's percentage : 0.0
 Total NaN values in row 14449 :- 0 and it's percentage : 0.0
 Total NaN values in row 14450 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14451 :- 0 and it's percentage : 0.0
 Total NaN values in row 14452 :- 0 and it's percentage : 0.0
 Total NaN values in row 14453 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14454 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14455 :- 0 and it's percentage : 0.0
 Total NaN values in row 14456 :- 0 and it's percentage : 0.0
 Total NaN values in row 14457 :- 0 and it's percentage : 0.0
 Total NaN values in row 14458 :- 0 and it's percentage : 0.0
 Total NaN values in row 14459 :- 0 and it's percentage : 0.0
 Total NaN values in row 14460 :- 0 and it's percentage : 0.0
 Total NaN values in row 14461 :- 0 and it's percentage : 0.0
 Total NaN values in row 14462 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14463 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14464 :- 0 and it's percentage : 0.0
 Total NaN values in row 14465 :- 0 and it's percentage : 0.0
 Total NaN values in row 14466 :- 0 and it's percentage : 0.0
 Total NaN values in row 14467 :- 0 and it's percentage : 0.0
 Total NaN values in row 14468 :- 0 and it's percentage : 0.0
 Total NaN values in row 14469 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 14470 :- 0 and it's percentage : 0.0
 Total NaN values in row 14471 :- 0 and it's percentage : 0.0
 Total NaN values in row 14472 :- 0 and it's percentage : 0.0
 Total NaN values in row 14473 :- 0 and it's percentage : 0.0
 Total NaN values in row 14474 :- 0 and it's percentage : 0.0
 Total NaN values in row 14475 :- 0 and it's percentage : 0.0
 Total NaN values in row 14476 :- 0 and it's percentage : 0.0
 Total NaN values in row 14477 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14478 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14479 :- 0 and it's percentage : 0.0
 Total NaN values in row 14480 :- 0 and it's percentage : 0.0
 Total NaN values in row 14481 :- 0 and it's percentage : 0.0
 Total NaN values in row 14482 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14483 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14484 :- 0 and it's percentage : 0.0
 Total NaN values in row 14485 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14486 :- 0 and it's percentage : 0.0
 Total NaN values in row 14487 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14488 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14489 :- 0 and it's percentage : 0.0
 Total NaN values in row 14490 :- 0 and it's percentage : 0.0
 Total NaN values in row 14491 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14492 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14493 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14494 :- 0 and it's percentage : 0.0
 Total NaN values in row 14495 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14496 :- 0 and it's percentage : 0.0
 Total NaN values in row 14497 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14498 :- 0 and it's percentage : 0.0
 Total NaN values in row 14499 :- 0 and it's percentage : 0.0
 Total NaN values in row 14500 :- 0 and it's percentage : 0.0
 Total NaN values in row 14501 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14502 :- 0 and it's percentage : 0.0
 Total NaN values in row 14503 :- 0 and it's percentage : 0.0
 Total NaN values in row 14504 :- 0 and it's percentage : 0.0
 Total NaN values in row 14505 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14506 :- 0 and it's percentage : 0.0
 Total NaN values in row 14507 :- 0 and it's percentage : 0.0
 Total NaN values in row 14508 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14509 :- 0 and it's percentage : 0.0
 Total NaN values in row 14510 :- 0 and it's percentage : 0.0
 Total NaN values in row 14511 :- 0 and it's percentage : 0.0
 Total NaN values in row 14512 :- 0 and it's percentage : 0.0
 Total NaN values in row 14513 :- 0 and it's percentage : 0.0
 Total NaN values in row 14514 :- 0 and it's percentage : 0.0
 Total NaN values in row 14515 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14517 :- 0 and it's percentage : 0.0
 Total NaN values in row 14518 :- 0 and it's percentage : 0.0
 Total NaN values in row 14519 :- 0 and it's percentage : 0.0
 Total NaN values in row 14520 :- 0 and it's percentage : 0.0
 Total NaN values in row 14521 :- 0 and it's percentage : 0.0
 Total NaN values in row 14522 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14523 :- 0 and it's percentage : 0.0
 Total NaN values in row 14524 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14525 :- 0 and it's percentage : 0.0
 Total NaN values in row 14526 :- 0 and it's percentage : 0.0
 Total NaN values in row 14527 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14528 :- 0 and it's percentage : 0.0
 Total NaN values in row 14529 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14530 :- 0 and it's percentage : 0.0
 Total NaN values in row 14531 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14532 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14533 :- 0 and it's percentage : 0.0
 Total NaN values in row 14534 :- 0 and it's percentage : 0.0
 Total NaN values in row 14535 :- 0 and it's percentage : 0.0
 Total NaN values in row 14536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14537 :- 0 and it's percentage : 0.0
 Total NaN values in row 14538 :- 0 and it's percentage : 0.0
 Total NaN values in row 14539 :- 0 and it's percentage : 0.0
 Total NaN values in row 14540 :- 0 and it's percentage : 0.0
 Total NaN values in row 14541 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14542 :- 0 and it's percentage : 0.0
 Total NaN values in row 14543 :- 0 and it's percentage : 0.0
 Total NaN values in row 14544 :- 0 and it's percentage : 0.0
 Total NaN values in row 14545 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14546 :- 0 and it's percentage : 0.0
 Total NaN values in row 14547 :- 0 and it's percentage : 0.0
 Total NaN values in row 14548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14549 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14550 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14551 :- 0 and it's percentage : 0.0
 Total NaN values in row 14552 :- 0 and it's percentage : 0.0
 Total NaN values in row 14553 :- 0 and it's percentage : 0.0
 Total NaN values in row 14554 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14555 :- 0 and it's percentage : 0.0
 Total NaN values in row 14556 :- 0 and it's percentage : 0.0
 Total NaN values in row 14557 :- 0 and it's percentage : 0.0
 Total NaN values in row 14558 :- 0 and it's percentage : 0.0
 Total NaN values in row 14559 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14560 :- 0 and it's percentage : 0.0
 Total NaN values in row 14561 :- 0 and it's percentage : 0.0
 Total NaN values in row 14562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14563 :- 0 and it's percentage : 0.0
 Total NaN values in row 14564 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14565 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14566 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14567 :- 0 and it's percentage : 0.0
 Total NaN values in row 14568 :- 0 and it's percentage : 0.0
 Total NaN values in row 14569 :- 0 and it's percentage : 0.0
 Total NaN values in row 14570 :- 0 and it's percentage : 0.0
 Total NaN values in row 14571 :- 0 and it's percentage : 0.0
 Total NaN values in row 14572 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14573 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14574 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 14575 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14577 :- 0 and it's percentage : 0.0
 Total NaN values in row 14578 :- 0 and it's percentage : 0.0
 Total NaN values in row 14579 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14580 :- 0 and it's percentage : 0.0
 Total NaN values in row 14581 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14582 :- 0 and it's percentage : 0.0
 Total NaN values in row 14583 :- 0 and it's percentage : 0.0
 Total NaN values in row 14584 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 14585 :- 0 and it's percentage : 0.0
 Total NaN values in row 14586 :- 0 and it's percentage : 0.0
 Total NaN values in row 14587 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14588 :- 0 and it's percentage : 0.0
 Total NaN values in row 14589 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14590 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14591 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14592 :- 0 and it's percentage : 0.0
 Total NaN values in row 14593 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14594 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14595 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14596 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14597 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14598 :- 0 and it's percentage : 0.0
 Total NaN values in row 14599 :- 0 and it's percentage : 0.0
 Total NaN values in row 14600 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14601 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14602 :- 0 and it's percentage : 0.0
 Total NaN values in row 14603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14604 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14605 :- 0 and it's percentage : 0.0
 Total NaN values in row 14606 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14607 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14608 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 14609 :- 0 and it's percentage : 0.0
 Total NaN values in row 14610 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14611 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14612 :- 0 and it's percentage : 0.0
 Total NaN values in row 14613 :- 0 and it's percentage : 0.0
 Total NaN values in row 14614 :- 0 and it's percentage : 0.0
 Total NaN values in row 14615 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14616 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14617 :- 0 and it's percentage : 0.0
 Total NaN values in row 14618 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14619 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14620 :- 0 and it's percentage : 0.0
 Total NaN values in row 14621 :- 0 and it's percentage : 0.0
 Total NaN values in row 14622 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14623 :- 0 and it's percentage : 0.0
 Total NaN values in row 14624 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14625 :- 0 and it's percentage : 0.0
 Total NaN values in row 14626 :- 0 and it's percentage : 0.0
 Total NaN values in row 14627 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14629 :- 0 and it's percentage : 0.0
 Total NaN values in row 14630 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14631 :- 0 and it's percentage : 0.0
 Total NaN values in row 14632 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14633 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14634 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14635 :- 0 and it's percentage : 0.0
 Total NaN values in row 14636 :- 0 and it's percentage : 0.0
 Total NaN values in row 14637 :- 0 and it's percentage : 0.0
 Total NaN values in row 14638 :- 0 and it's percentage : 0.0
 Total NaN values in row 14639 :- 0 and it's percentage : 0.0
 Total NaN values in row 14640 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14641 :- 0 and it's percentage : 0.0
 Total NaN values in row 14642 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14643 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14644 :- 0 and it's percentage : 0.0
 Total NaN values in row 14645 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14646 :- 0 and it's percentage : 0.0
 Total NaN values in row 14647 :- 0 and it's percentage : 0.0
 Total NaN values in row 14648 :- 0 and it's percentage : 0.0
 Total NaN values in row 14649 :- 0 and it's percentage : 0.0
 Total NaN values in row 14650 :- 0 and it's percentage : 0.0
 Total NaN values in row 14651 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14652 :- 0 and it's percentage : 0.0
 Total NaN values in row 14653 :- 0 and it's percentage : 0.0
 Total NaN values in row 14654 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14655 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14656 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14657 :- 0 and it's percentage : 0.0
 Total NaN values in row 14658 :- 0 and it's percentage : 0.0
 Total NaN values in row 14659 :- 0 and it's percentage : 0.0
 Total NaN values in row 14660 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14661 :- 0 and it's percentage : 0.0
 Total NaN values in row 14662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14663 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14664 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14665 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14666 :- 0 and it's percentage : 0.0
 Total NaN values in row 14667 :- 0 and it's percentage : 0.0
 Total NaN values in row 14668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14669 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14670 :- 0 and it's percentage : 0.0
 Total NaN values in row 14671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14672 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14673 :- 0 and it's percentage : 0.0
 Total NaN values in row 14674 :- 0 and it's percentage : 0.0
 Total NaN values in row 14675 :- 0 and it's percentage : 0.0
 Total NaN values in row 14676 :- 0 and it's percentage : 0.0
 Total NaN values in row 14677 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14678 :- 0 and it's percentage : 0.0
 Total NaN values in row 14679 :- 0 and it's percentage : 0.0
 Total NaN values in row 14680 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14681 :- 0 and it's percentage : 0.0
 Total NaN values in row 14682 :- 0 and it's percentage : 0.0
 Total NaN values in row 14683 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14684 :- 0 and it's percentage : 0.0
 Total NaN values in row 14685 :- 0 and it's percentage : 0.0
 Total NaN values in row 14686 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14688 :- 0 and it's percentage : 0.0
 Total NaN values in row 14689 :- 0 and it's percentage : 0.0
 Total NaN values in row 14690 :- 0 and it's percentage : 0.0
 Total NaN values in row 14691 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14693 :- 0 and it's percentage : 0.0
 Total NaN values in row 14694 :- 0 and it's percentage : 0.0
 Total NaN values in row 14695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14696 :- 0 and it's percentage : 0.0
 Total NaN values in row 14697 :- 0 and it's percentage : 0.0
 Total NaN values in row 14698 :- 0 and it's percentage : 0.0
 Total NaN values in row 14699 :- 0 and it's percentage : 0.0
 Total NaN values in row 14700 :- 0 and it's percentage : 0.0
 Total NaN values in row 14701 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14702 :- 0 and it's percentage : 0.0
 Total NaN values in row 14703 :- 0 and it's percentage : 0.0
 Total NaN values in row 14704 :- 0 and it's percentage : 0.0
 Total NaN values in row 14705 :- 0 and it's percentage : 0.0
 Total NaN values in row 14706 :- 0 and it's percentage : 0.0
 Total NaN values in row 14707 :- 0 and it's percentage : 0.0
 Total NaN values in row 14708 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14709 :- 0 and it's percentage : 0.0
 Total NaN values in row 14710 :- 0 and it's percentage : 0.0
 Total NaN values in row 14711 :- 0 and it's percentage : 0.0
 Total NaN values in row 14712 :- 0 and it's percentage : 0.0
 Total NaN values in row 14713 :- 0 and it's percentage : 0.0
 Total NaN values in row 14714 :- 0 and it's percentage : 0.0
 Total NaN values in row 14715 :- 0 and it's percentage : 0.0
 Total NaN values in row 14716 :- 0 and it's percentage : 0.0
 Total NaN values in row 14717 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14718 :- 0 and it's percentage : 0.0
 Total NaN values in row 14719 :- 0 and it's percentage : 0.0
 Total NaN values in row 14720 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14721 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14722 :- 0 and it's percentage : 0.0
 Total NaN values in row 14723 :- 0 and it's percentage : 0.0
 Total NaN values in row 14724 :- 0 and it's percentage : 0.0
 Total NaN values in row 14725 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14726 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14727 :- 0 and it's percentage : 0.0
 Total NaN values in row 14728 :- 0 and it's percentage : 0.0
 Total NaN values in row 14729 :- 0 and it's percentage : 0.0
 Total NaN values in row 14730 :- 0 and it's percentage : 0.0
 Total NaN values in row 14731 :- 0 and it's percentage : 0.0
 Total NaN values in row 14732 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14733 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14734 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14735 :- 0 and it's percentage : 0.0
 Total NaN values in row 14736 :- 0 and it's percentage : 0.0
 Total NaN values in row 14737 :- 0 and it's percentage : 0.0
 Total NaN values in row 14738 :- 0 and it's percentage : 0.0
 Total NaN values in row 14739 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14740 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14741 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14743 :- 0 and it's percentage : 0.0

 Total NaN values in row 14744 :- 0 and it's percentage : 0.0
 Total NaN values in row 14745 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14746 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14747 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14748 :- 0 and it's percentage : 0.0
 Total NaN values in row 14749 :- 0 and it's percentage : 0.0
 Total NaN values in row 14750 :- 0 and it's percentage : 0.0
 Total NaN values in row 14751 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14753 :- 0 and it's percentage : 0.0
 Total NaN values in row 14754 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14755 :- 0 and it's percentage : 0.0
 Total NaN values in row 14756 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14757 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14758 :- 0 and it's percentage : 0.0
 Total NaN values in row 14759 :- 0 and it's percentage : 0.0
 Total NaN values in row 14760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14761 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14762 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14763 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14764 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14765 :- 0 and it's percentage : 0.0
 Total NaN values in row 14766 :- 0 and it's percentage : 0.0
 Total NaN values in row 14767 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14770 :- 0 and it's percentage : 0.0
 Total NaN values in row 14771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14772 :- 0 and it's percentage : 0.0
 Total NaN values in row 14773 :- 0 and it's percentage : 0.0
 Total NaN values in row 14774 :- 0 and it's percentage : 0.0
 Total NaN values in row 14775 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14777 :- 0 and it's percentage : 0.0
 Total NaN values in row 14778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14779 :- 0 and it's percentage : 0.0
 Total NaN values in row 14780 :- 0 and it's percentage : 0.0
 Total NaN values in row 14781 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14782 :- 0 and it's percentage : 0.0
 Total NaN values in row 14783 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14784 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14785 :- 0 and it's percentage : 0.0
 Total NaN values in row 14786 :- 0 and it's percentage : 0.0
 Total NaN values in row 14787 :- 0 and it's percentage : 0.0
 Total NaN values in row 14788 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14789 :- 0 and it's percentage : 0.0
 Total NaN values in row 14790 :- 0 and it's percentage : 0.0
 Total NaN values in row 14791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14792 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14793 :- 0 and it's percentage : 0.0
 Total NaN values in row 14794 :- 0 and it's percentage : 0.0
 Total NaN values in row 14795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14796 :- 0 and it's percentage : 0.0
 Total NaN values in row 14797 :- 0 and it's percentage : 0.0
 Total NaN values in row 14798 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14799 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14800 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14801 :- 0 and it's percentage : 0.0
 Total NaN values in row 14802 :- 0 and it's percentage : 0.0
 Total NaN values in row 14803 :- 0 and it's percentage : 0.0
 Total NaN values in row 14804 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14805 :- 0 and it's percentage : 0.0
 Total NaN values in row 14806 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14807 :- 0 and it's percentage : 0.0
 Total NaN values in row 14808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14809 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14810 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14811 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14812 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14813 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14814 :- 0 and it's percentage : 0.0
 Total NaN values in row 14815 :- 0 and it's percentage : 0.0
 Total NaN values in row 14816 :- 0 and it's percentage : 0.0
 Total NaN values in row 14817 :- 0 and it's percentage : 0.0
 Total NaN values in row 14818 :- 0 and it's percentage : 0.0
 Total NaN values in row 14819 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14820 :- 0 and it's percentage : 0.0
 Total NaN values in row 14821 :- 0 and it's percentage : 0.0
 Total NaN values in row 14822 :- 0 and it's percentage : 0.0
 Total NaN values in row 14823 :- 0 and it's percentage : 0.0
 Total NaN values in row 14824 :- 0 and it's percentage : 0.0
 Total NaN values in row 14825 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14826 :- 0 and it's percentage : 0.0
 Total NaN values in row 14827 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14828 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14829 :- 0 and it's percentage : 0.0
 Total NaN values in row 14830 :- 0 and it's percentage : 0.0
 Total NaN values in row 14831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14832 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14833 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14834 :- 0 and it's percentage : 0.0
 Total NaN values in row 14835 :- 0 and it's percentage : 0.0
 Total NaN values in row 14836 :- 0 and it's percentage : 0.0
 Total NaN values in row 14837 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14838 :- 0 and it's percentage : 0.0
 Total NaN values in row 14839 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14840 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14841 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14843 :- 0 and it's percentage : 0.0
 Total NaN values in row 14844 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14845 :- 0 and it's percentage : 0.0
 Total NaN values in row 14846 :- 0 and it's percentage : 0.0
 Total NaN values in row 14847 :- 0 and it's percentage : 0.0
 Total NaN values in row 14848 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14849 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14850 :- 0 and it's percentage : 0.0
 Total NaN values in row 14851 :- 0 and it's percentage : 0.0
 Total NaN values in row 14852 :- 0 and it's percentage : 0.0
 Total NaN values in row 14853 :- 0 and it's percentage : 0.0
 Total NaN values in row 14854 :- 0 and it's percentage : 0.0
 Total NaN values in row 14855 :- 0 and it's percentage : 0.0
 Total NaN values in row 14856 :- 0 and it's percentage : 0.0
 Total NaN values in row 14857 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14858 :- 0 and it's percentage : 0.0
 Total NaN values in row 14859 :- 0 and it's percentage : 0.0
 Total NaN values in row 14860 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14861 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14862 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14863 :- 0 and it's percentage : 0.0
 Total NaN values in row 14864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14865 :- 0 and it's percentage : 0.0
 Total NaN values in row 14866 :- 0 and it's percentage : 0.0
 Total NaN values in row 14867 :- 0 and it's percentage : 0.0
 Total NaN values in row 14868 :- 0 and it's percentage : 0.0

 Total NaN values in row 14869 :- 0 and it's percentage : 0.0
 Total NaN values in row 14870 :- 0 and it's percentage : 0.0
 Total NaN values in row 14871 :- 0 and it's percentage : 0.0
 Total NaN values in row 14872 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14873 :- 0 and it's percentage : 0.0
 Total NaN values in row 14874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14875 :- 0 and it's percentage : 0.0
 Total NaN values in row 14876 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14877 :- 0 and it's percentage : 0.0
 Total NaN values in row 14878 :- 0 and it's percentage : 0.0
 Total NaN values in row 14879 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14880 :- 0 and it's percentage : 0.0
 Total NaN values in row 14881 :- 0 and it's percentage : 0.0
 Total NaN values in row 14882 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14883 :- 0 and it's percentage : 0.0
 Total NaN values in row 14884 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14885 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14886 :- 0 and it's percentage : 0.0
 Total NaN values in row 14887 :- 0 and it's percentage : 0.0
 Total NaN values in row 14888 :- 0 and it's percentage : 0.0
 Total NaN values in row 14889 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14890 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14891 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14892 :- 0 and it's percentage : 0.0
 Total NaN values in row 14893 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14894 :- 0 and it's percentage : 0.0
 Total NaN values in row 14895 :- 0 and it's percentage : 0.0
 Total NaN values in row 14896 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14897 :- 0 and it's percentage : 0.0
 Total NaN values in row 14898 :- 0 and it's percentage : 0.0
 Total NaN values in row 14899 :- 0 and it's percentage : 0.0
 Total NaN values in row 14900 :- 0 and it's percentage : 0.0
 Total NaN values in row 14901 :- 0 and it's percentage : 0.0
 Total NaN values in row 14902 :- 0 and it's percentage : 0.0
 Total NaN values in row 14903 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14904 :- 0 and it's percentage : 0.0
 Total NaN values in row 14905 :- 0 and it's percentage : 0.0
 Total NaN values in row 14906 :- 0 and it's percentage : 0.0
 Total NaN values in row 14907 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14908 :- 0 and it's percentage : 0.0
 Total NaN values in row 14909 :- 0 and it's percentage : 0.0
 Total NaN values in row 14910 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14911 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14912 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14913 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14915 :- 0 and it's percentage : 0.0
 Total NaN values in row 14916 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14917 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14918 :- 0 and it's percentage : 0.0
 Total NaN values in row 14919 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14921 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14924 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14925 :- 0 and it's percentage : 0.0
 Total NaN values in row 14926 :- 0 and it's percentage : 0.0
 Total NaN values in row 14927 :- 0 and it's percentage : 0.0
 Total NaN values in row 14928 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14929 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14930 :- 0 and it's percentage : 0.0
 Total NaN values in row 14931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14932 :- 0 and it's percentage : 0.0
 Total NaN values in row 14933 :- 0 and it's percentage : 0.0
 Total NaN values in row 14934 :- 0 and it's percentage : 0.0
 Total NaN values in row 14935 :- 0 and it's percentage : 0.0
 Total NaN values in row 14936 :- 0 and it's percentage : 0.0
 Total NaN values in row 14937 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14938 :- 0 and it's percentage : 0.0
 Total NaN values in row 14939 :- 0 and it's percentage : 0.0
 Total NaN values in row 14940 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14941 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14943 :- 0 and it's percentage : 0.0
 Total NaN values in row 14944 :- 0 and it's percentage : 0.0
 Total NaN values in row 14945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14946 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14947 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14948 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 14949 :- 0 and it's percentage : 0.0
 Total NaN values in row 14950 :- 0 and it's percentage : 0.0
 Total NaN values in row 14951 :- 0 and it's percentage : 0.0
 Total NaN values in row 14952 :- 0 and it's percentage : 0.0
 Total NaN values in row 14953 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14954 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14955 :- 0 and it's percentage : 0.0
 Total NaN values in row 14956 :- 0 and it's percentage : 0.0
 Total NaN values in row 14957 :- 0 and it's percentage : 0.0
 Total NaN values in row 14958 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14959 :- 0 and it's percentage : 0.0
 Total NaN values in row 14960 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14961 :- 0 and it's percentage : 0.0
 Total NaN values in row 14962 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14963 :- 0 and it's percentage : 0.0
 Total NaN values in row 14964 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14965 :- 0 and it's percentage : 0.0
 Total NaN values in row 14966 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14967 :- 0 and it's percentage : 0.0
 Total NaN values in row 14968 :- 0 and it's percentage : 0.0
 Total NaN values in row 14969 :- 0 and it's percentage : 0.0
 Total NaN values in row 14970 :- 0 and it's percentage : 0.0
 Total NaN values in row 14971 :- 0 and it's percentage : 0.0
 Total NaN values in row 14972 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14973 :- 0 and it's percentage : 0.0
 Total NaN values in row 14974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14975 :- 0 and it's percentage : 0.0
 Total NaN values in row 14976 :- 0 and it's percentage : 0.0
 Total NaN values in row 14977 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 14978 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14979 :- 0 and it's percentage : 0.0
 Total NaN values in row 14980 :- 0 and it's percentage : 0.0
 Total NaN values in row 14981 :- 0 and it's percentage : 0.0
 Total NaN values in row 14982 :- 0 and it's percentage : 0.0
 Total NaN values in row 14983 :- 0 and it's percentage : 0.0
 Total NaN values in row 14984 :- 0 and it's percentage : 0.0
 Total NaN values in row 14985 :- 0 and it's percentage : 0.0
 Total NaN values in row 14986 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14987 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14988 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14989 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14991 :- 0 and it's percentage : 0.0
 Total NaN values in row 14992 :- 0 and it's percentage : 0.0
 Total NaN values in row 14993 :- 0 and it's percentage : 0.0
 Total NaN values in row 14994 :- 0 and it's percentage : 0.0
 Total NaN values in row 14995 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 14996 :- 0 and it's percentage : 0.0
 Total NaN values in row 14997 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14998 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 14999 :- 0 and it's percentage : 0.0
 Total NaN values in row 15000 :- 0 and it's percentage : 0.0
 Total NaN values in row 15001 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15003 :- 0 and it's percentage : 0.0
 Total NaN values in row 15004 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15005 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15006 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15007 :- 0 and it's percentage : 0.0
 Total NaN values in row 15008 :- 0 and it's percentage : 0.0
 Total NaN values in row 15009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15010 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15011 :- 0 and it's percentage : 0.0
 Total NaN values in row 15012 :- 0 and it's percentage : 0.0
 Total NaN values in row 15013 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15015 :- 0 and it's percentage : 0.0
 Total NaN values in row 15016 :- 0 and it's percentage : 0.0
 Total NaN values in row 15017 :- 0 and it's percentage : 0.0
 Total NaN values in row 15018 :- 0 and it's percentage : 0.0
 Total NaN values in row 15019 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15020 :- 0 and it's percentage : 0.0
 Total NaN values in row 15021 :- 0 and it's percentage : 0.0
 Total NaN values in row 15022 :- 0 and it's percentage : 0.0
 Total NaN values in row 15023 :- 0 and it's percentage : 0.0
 Total NaN values in row 15024 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15025 :- 0 and it's percentage : 0.0
 Total NaN values in row 15026 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15028 :- 0 and it's percentage : 0.0
 Total NaN values in row 15029 :- 0 and it's percentage : 0.0
 Total NaN values in row 15030 :- 0 and it's percentage : 0.0
 Total NaN values in row 15031 :- 0 and it's percentage : 0.0
 Total NaN values in row 15032 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15033 :- 0 and it's percentage : 0.0
 Total NaN values in row 15034 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15035 :- 0 and it's percentage : 0.0
 Total NaN values in row 15036 :- 0 and it's percentage : 0.0
 Total NaN values in row 15037 :- 0 and it's percentage : 0.0
 Total NaN values in row 15038 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15039 :- 0 and it's percentage : 0.0
 Total NaN values in row 15040 :- 0 and it's percentage : 0.0
 Total NaN values in row 15041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15042 :- 0 and it's percentage : 0.0
 Total NaN values in row 15043 :- 0 and it's percentage : 0.0
 Total NaN values in row 15044 :- 0 and it's percentage : 0.0
 Total NaN values in row 15045 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15047 :- 0 and it's percentage : 0.0
 Total NaN values in row 15048 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15049 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15050 :- 0 and it's percentage : 0.0
 Total NaN values in row 15051 :- 0 and it's percentage : 0.0
 Total NaN values in row 15052 :- 7 and it's percentage : 38.888888888888886

 Total NaN values in row 15053 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15054 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15055 :- 0 and it's percentage : 0.0
 Total NaN values in row 15056 :- 0 and it's percentage : 0.0
 Total NaN values in row 15057 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15058 :- 0 and it's percentage : 0.0
 Total NaN values in row 15059 :- 0 and it's percentage : 0.0
 Total NaN values in row 15060 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15061 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15062 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15063 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15064 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15066 :- 0 and it's percentage : 0.0
 Total NaN values in row 15067 :- 0 and it's percentage : 0.0
 Total NaN values in row 15068 :- 0 and it's percentage : 0.0
 Total NaN values in row 15069 :- 0 and it's percentage : 0.0
 Total NaN values in row 15070 :- 0 and it's percentage : 0.0
 Total NaN values in row 15071 :- 0 and it's percentage : 0.0
 Total NaN values in row 15072 :- 0 and it's percentage : 0.0
 Total NaN values in row 15073 :- 0 and it's percentage : 0.0
 Total NaN values in row 15074 :- 0 and it's percentage : 0.0
 Total NaN values in row 15075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15076 :- 0 and it's percentage : 0.0
 Total NaN values in row 15077 :- 0 and it's percentage : 0.0
 Total NaN values in row 15078 :- 0 and it's percentage : 0.0
 Total NaN values in row 15079 :- 0 and it's percentage : 0.0
 Total NaN values in row 15080 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15081 :- 0 and it's percentage : 0.0
 Total NaN values in row 15082 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15083 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15084 :- 0 and it's percentage : 0.0
 Total NaN values in row 15085 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15086 :- 0 and it's percentage : 0.0
 Total NaN values in row 15087 :- 0 and it's percentage : 0.0
 Total NaN values in row 15088 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15089 :- 0 and it's percentage : 0.0
 Total NaN values in row 15090 :- 0 and it's percentage : 0.0
 Total NaN values in row 15091 :- 0 and it's percentage : 0.0
 Total NaN values in row 15092 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15093 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15094 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15095 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15096 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15097 :- 0 and it's percentage : 0.0
 Total NaN values in row 15098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15099 :- 0 and it's percentage : 0.0
 Total NaN values in row 15100 :- 0 and it's percentage : 0.0
 Total NaN values in row 15101 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15102 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15103 :- 0 and it's percentage : 0.0
 Total NaN values in row 15104 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15105 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15106 :- 0 and it's percentage : 0.0
 Total NaN values in row 15107 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15108 :- 0 and it's percentage : 0.0
 Total NaN values in row 15109 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15110 :- 0 and it's percentage : 0.0
 Total NaN values in row 15111 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15112 :- 0 and it's percentage : 0.0
 Total NaN values in row 15113 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15114 :- 0 and it's percentage : 0.0
 Total NaN values in row 15115 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15116 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15118 :- 0 and it's percentage : 0.0
 Total NaN values in row 15119 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15120 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15121 :- 0 and it's percentage : 0.0
 Total NaN values in row 15122 :- 0 and it's percentage : 0.0
 Total NaN values in row 15123 :- 0 and it's percentage : 0.0
 Total NaN values in row 15124 :- 0 and it's percentage : 0.0
 Total NaN values in row 15125 :- 0 and it's percentage : 0.0
 Total NaN values in row 15126 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15129 :- 0 and it's percentage : 0.0
 Total NaN values in row 15130 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15131 :- 0 and it's percentage : 0.0
 Total NaN values in row 15132 :- 0 and it's percentage : 0.0
 Total NaN values in row 15133 :- 0 and it's percentage : 0.0
 Total NaN values in row 15134 :- 0 and it's percentage : 0.0
 Total NaN values in row 15135 :- 0 and it's percentage : 0.0
 Total NaN values in row 15136 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15137 :- 0 and it's percentage : 0.0
 Total NaN values in row 15138 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15139 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15140 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15143 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15144 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15145 :- 0 and it's percentage : 0.0
 Total NaN values in row 15146 :- 0 and it's percentage : 0.0
 Total NaN values in row 15147 :- 0 and it's percentage : 0.0
 Total NaN values in row 15148 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15149 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15150 :- 0 and it's percentage : 0.0
 Total NaN values in row 15151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15152 :- 0 and it's percentage : 0.0
 Total NaN values in row 15153 :- 0 and it's percentage : 0.0
 Total NaN values in row 15154 :- 0 and it's percentage : 0.0
 Total NaN values in row 15155 :- 0 and it's percentage : 0.0
 Total NaN values in row 15156 :- 0 and it's percentage : 0.0
 Total NaN values in row 15157 :- 0 and it's percentage : 0.0
 Total NaN values in row 15158 :- 0 and it's percentage : 0.0
 Total NaN values in row 15159 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15160 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15161 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15162 :- 0 and it's percentage : 0.0
 Total NaN values in row 15163 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15164 :- 0 and it's percentage : 0.0
 Total NaN values in row 15165 :- 0 and it's percentage : 0.0
 Total NaN values in row 15166 :- 0 and it's percentage : 0.0
 Total NaN values in row 15167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15168 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15169 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15171 :- 0 and it's percentage : 0.0
 Total NaN values in row 15172 :- 0 and it's percentage : 0.0
 Total NaN values in row 15173 :- 0 and it's percentage : 0.0
 Total NaN values in row 15174 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15175 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15176 :- 0 and it's percentage : 0.0
 Total NaN values in row 15177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15180 :- 0 and it's percentage : 0.0
 Total NaN values in row 15181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15182 :- 0 and it's percentage : 0.0
 Total NaN values in row 15183 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15184 :- 0 and it's percentage : 0.0
 Total NaN values in row 15185 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 15186 :- 0 and it's percentage : 0.0
 Total NaN values in row 15187 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15188 :- 0 and it's percentage : 0.0
 Total NaN values in row 15189 :- 0 and it's percentage : 0.0
 Total NaN values in row 15190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15191 :- 0 and it's percentage : 0.0
 Total NaN values in row 15192 :- 0 and it's percentage : 0.0
 Total NaN values in row 15193 :- 0 and it's percentage : 0.0
 Total NaN values in row 15194 :- 0 and it's percentage : 0.0
 Total NaN values in row 15195 :- 0 and it's percentage : 0.0
 Total NaN values in row 15196 :- 0 and it's percentage : 0.0
 Total NaN values in row 15197 :- 0 and it's percentage : 0.0
 Total NaN values in row 15198 :- 0 and it's percentage : 0.0
 Total NaN values in row 15199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15200 :- 0 and it's percentage : 0.0
 Total NaN values in row 15201 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15202 :- 0 and it's percentage : 0.0
 Total NaN values in row 15203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15204 :- 0 and it's percentage : 0.0
 Total NaN values in row 15205 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15207 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15208 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15209 :- 0 and it's percentage : 0.0
 Total NaN values in row 15210 :- 0 and it's percentage : 0.0
 Total NaN values in row 15211 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15212 :- 0 and it's percentage : 0.0
 Total NaN values in row 15213 :- 0 and it's percentage : 0.0
 Total NaN values in row 15214 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 15215 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15216 :- 0 and it's percentage : 0.0
 Total NaN values in row 15217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15218 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15219 :- 0 and it's percentage : 0.0
 Total NaN values in row 15220 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15221 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15222 :- 0 and it's percentage : 0.0
 Total NaN values in row 15223 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15224 :- 0 and it's percentage : 0.0
 Total NaN values in row 15225 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15226 :- 0 and it's percentage : 0.0
 Total NaN values in row 15227 :- 0 and it's percentage : 0.0
 Total NaN values in row 15228 :- 0 and it's percentage : 0.0
 Total NaN values in row 15229 :- 0 and it's percentage : 0.0
 Total NaN values in row 15230 :- 0 and it's percentage : 0.0
 Total NaN values in row 15231 :- 0 and it's percentage : 0.0
 Total NaN values in row 15232 :- 0 and it's percentage : 0.0
 Total NaN values in row 15233 :- 0 and it's percentage : 0.0
 Total NaN values in row 15234 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15235 :- 0 and it's percentage : 0.0
 Total NaN values in row 15236 :- 0 and it's percentage : 0.0
 Total NaN values in row 15237 :- 0 and it's percentage : 0.0
 Total NaN values in row 15238 :- 0 and it's percentage : 0.0
 Total NaN values in row 15239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15240 :- 0 and it's percentage : 0.0
 Total NaN values in row 15241 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15242 :- 0 and it's percentage : 0.0
 Total NaN values in row 15243 :- 0 and it's percentage : 0.0
 Total NaN values in row 15244 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15245 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15246 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15248 :- 0 and it's percentage : 0.0
 Total NaN values in row 15249 :- 0 and it's percentage : 0.0
 Total NaN values in row 15250 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15251 :- 0 and it's percentage : 0.0
 Total NaN values in row 15252 :- 0 and it's percentage : 0.0
 Total NaN values in row 15253 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15254 :- 0 and it's percentage : 0.0
 Total NaN values in row 15255 :- 0 and it's percentage : 0.0
 Total NaN values in row 15256 :- 0 and it's percentage : 0.0
 Total NaN values in row 15257 :- 0 and it's percentage : 0.0
 Total NaN values in row 15258 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15259 :- 0 and it's percentage : 0.0
 Total NaN values in row 15260 :- 0 and it's percentage : 0.0
 Total NaN values in row 15261 :- 0 and it's percentage : 0.0
 Total NaN values in row 15262 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15263 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15264 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15265 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15267 :- 0 and it's percentage : 0.0
 Total NaN values in row 15268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15269 :- 0 and it's percentage : 0.0
 Total NaN values in row 15270 :- 0 and it's percentage : 0.0
 Total NaN values in row 15271 :- 0 and it's percentage : 0.0
 Total NaN values in row 15272 :- 0 and it's percentage : 0.0
 Total NaN values in row 15273 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15274 :- 0 and it's percentage : 0.0
 Total NaN values in row 15275 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15276 :- 0 and it's percentage : 0.0
 Total NaN values in row 15277 :- 0 and it's percentage : 0.0
 Total NaN values in row 15278 :- 0 and it's percentage : 0.0
 Total NaN values in row 15279 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 15280 :- 0 and it's percentage : 0.0
 Total NaN values in row 15281 :- 0 and it's percentage : 0.0
 Total NaN values in row 15282 :- 0 and it's percentage : 0.0
 Total NaN values in row 15283 :- 0 and it's percentage : 0.0
 Total NaN values in row 15284 :- 0 and it's percentage : 0.0
 Total NaN values in row 15285 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15286 :- 0 and it's percentage : 0.0
 Total NaN values in row 15287 :- 0 and it's percentage : 0.0
 Total NaN values in row 15288 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15289 :- 0 and it's percentage : 0.0
 Total NaN values in row 15290 :- 0 and it's percentage : 0.0
 Total NaN values in row 15291 :- 0 and it's percentage : 0.0
 Total NaN values in row 15292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15293 :- 0 and it's percentage : 0.0
 Total NaN values in row 15294 :- 0 and it's percentage : 0.0
 Total NaN values in row 15295 :- 0 and it's percentage : 0.0
 Total NaN values in row 15296 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15297 :- 0 and it's percentage : 0.0
 Total NaN values in row 15298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15299 :- 0 and it's percentage : 0.0
 Total NaN values in row 15300 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15301 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15302 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15303 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15304 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15305 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15306 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15307 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15308 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15309 :- 0 and it's percentage : 0.0
 Total NaN values in row 15310 :- 0 and it's percentage : 0.0
 Total NaN values in row 15311 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15312 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15313 :- 0 and it's percentage : 0.0
 Total NaN values in row 15314 :- 0 and it's percentage : 0.0
 Total NaN values in row 15315 :- 0 and it's percentage : 0.0
 Total NaN values in row 15316 :- 0 and it's percentage : 0.0
 Total NaN values in row 15317 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15318 :- 0 and it's percentage : 0.0
 Total NaN values in row 15319 :- 0 and it's percentage : 0.0
 Total NaN values in row 15320 :- 0 and it's percentage : 0.0
 Total NaN values in row 15321 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 15322 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15323 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15324 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15325 :- 0 and it's percentage : 0.0
 Total NaN values in row 15326 :- 0 and it's percentage : 0.0
 Total NaN values in row 15327 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15328 :- 0 and it's percentage : 0.0
 Total NaN values in row 15329 :- 0 and it's percentage : 0.0
 Total NaN values in row 15330 :- 0 and it's percentage : 0.0
 Total NaN values in row 15331 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15332 :- 0 and it's percentage : 0.0
 Total NaN values in row 15333 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15334 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15335 :- 0 and it's percentage : 0.0
 Total NaN values in row 15336 :- 0 and it's percentage : 0.0
 Total NaN values in row 15337 :- 0 and it's percentage : 0.0
 Total NaN values in row 15338 :- 0 and it's percentage : 0.0
 Total NaN values in row 15339 :- 0 and it's percentage : 0.0
 Total NaN values in row 15340 :- 0 and it's percentage : 0.0
 Total NaN values in row 15341 :- 0 and it's percentage : 0.0
 Total NaN values in row 15342 :- 0 and it's percentage : 0.0
 Total NaN values in row 15343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15344 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15345 :- 0 and it's percentage : 0.0
 Total NaN values in row 15346 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15347 :- 0 and it's percentage : 0.0
 Total NaN values in row 15348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15349 :- 0 and it's percentage : 0.0
 Total NaN values in row 15350 :- 0 and it's percentage : 0.0
 Total NaN values in row 15351 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15352 :- 0 and it's percentage : 0.0
 Total NaN values in row 15353 :- 0 and it's percentage : 0.0
 Total NaN values in row 15354 :- 0 and it's percentage : 0.0
 Total NaN values in row 15355 :- 0 and it's percentage : 0.0
 Total NaN values in row 15356 :- 0 and it's percentage : 0.0
 Total NaN values in row 15357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15358 :- 0 and it's percentage : 0.0
 Total NaN values in row 15359 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15360 :- 0 and it's percentage : 0.0
 Total NaN values in row 15361 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15362 :- 0 and it's percentage : 0.0
 Total NaN values in row 15363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15364 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15365 :- 0 and it's percentage : 0.0
 Total NaN values in row 15366 :- 0 and it's percentage : 0.0
 Total NaN values in row 15367 :- 0 and it's percentage : 0.0
 Total NaN values in row 15368 :- 0 and it's percentage : 0.0
 Total NaN values in row 15369 :- 0 and it's percentage : 0.0
 Total NaN values in row 15370 :- 0 and it's percentage : 0.0
 Total NaN values in row 15371 :- 0 and it's percentage : 0.0
 Total NaN values in row 15372 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15373 :- 0 and it's percentage : 0.0
 Total NaN values in row 15374 :- 0 and it's percentage : 0.0
 Total NaN values in row 15375 :- 0 and it's percentage : 0.0
 Total NaN values in row 15376 :- 0 and it's percentage : 0.0
 Total NaN values in row 15377 :- 0 and it's percentage : 0.0
 Total NaN values in row 15378 :- 0 and it's percentage : 0.0
 Total NaN values in row 15379 :- 0 and it's percentage : 0.0
 Total NaN values in row 15380 :- 0 and it's percentage : 0.0
 Total NaN values in row 15381 :- 0 and it's percentage : 0.0
 Total NaN values in row 15382 :- 0 and it's percentage : 0.0
 Total NaN values in row 15383 :- 0 and it's percentage : 0.0
 Total NaN values in row 15384 :- 0 and it's percentage : 0.0
 Total NaN values in row 15385 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15386 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15387 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15388 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15389 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15390 :- 0 and it's percentage : 0.0
 Total NaN values in row 15391 :- 0 and it's percentage : 0.0
 Total NaN values in row 15392 :- 0 and it's percentage : 0.0
 Total NaN values in row 15393 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15394 :- 0 and it's percentage : 0.0
 Total NaN values in row 15395 :- 0 and it's percentage : 0.0
 Total NaN values in row 15396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15397 :- 0 and it's percentage : 0.0
 Total NaN values in row 15398 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15399 :- 0 and it's percentage : 0.0
 Total NaN values in row 15400 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15401 :- 0 and it's percentage : 0.0
 Total NaN values in row 15402 :- 0 and it's percentage : 0.0
 Total NaN values in row 15403 :- 0 and it's percentage : 0.0
 Total NaN values in row 15404 :- 0 and it's percentage : 0.0
 Total NaN values in row 15405 :- 0 and it's percentage : 0.0
 Total NaN values in row 15406 :- 0 and it's percentage : 0.0
 Total NaN values in row 15407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15408 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15409 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15410 :- 0 and it's percentage : 0.0
 Total NaN values in row 15411 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15412 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15413 :- 0 and it's percentage : 0.0
 Total NaN values in row 15414 :- 0 and it's percentage : 0.0
 Total NaN values in row 15415 :- 0 and it's percentage : 0.0
 Total NaN values in row 15416 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15417 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15418 :- 0 and it's percentage : 0.0
 Total NaN values in row 15419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15420 :- 0 and it's percentage : 0.0
 Total NaN values in row 15421 :- 0 and it's percentage : 0.0
 Total NaN values in row 15422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15423 :- 0 and it's percentage : 0.0
 Total NaN values in row 15424 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15425 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15426 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15427 :- 0 and it's percentage : 0.0
 Total NaN values in row 15428 :- 0 and it's percentage : 0.0
 Total NaN values in row 15429 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15430 :- 0 and it's percentage : 0.0
 Total NaN values in row 15431 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15433 :- 0 and it's percentage : 0.0
 Total NaN values in row 15434 :- 0 and it's percentage : 0.0
 Total NaN values in row 15435 :- 0 and it's percentage : 0.0
 Total NaN values in row 15436 :- 0 and it's percentage : 0.0
 Total NaN values in row 15437 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15438 :- 0 and it's percentage : 0.0
 Total NaN values in row 15439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15440 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15441 :- 0 and it's percentage : 0.0
 Total NaN values in row 15442 :- 0 and it's percentage : 0.0
 Total NaN values in row 15443 :- 0 and it's percentage : 0.0
 Total NaN values in row 15444 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15445 :- 0 and it's percentage : 0.0
 Total NaN values in row 15446 :- 0 and it's percentage : 0.0
 Total NaN values in row 15447 :- 0 and it's percentage : 0.0
 Total NaN values in row 15448 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15449 :- 0 and it's percentage : 0.0
 Total NaN values in row 15450 :- 0 and it's percentage : 0.0
 Total NaN values in row 15451 :- 0 and it's percentage : 0.0
 Total NaN values in row 15452 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15453 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15454 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15456 :- 0 and it's percentage : 0.0
 Total NaN values in row 15457 :- 0 and it's percentage : 0.0
 Total NaN values in row 15458 :- 0 and it's percentage : 0.0
 Total NaN values in row 15459 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15460 :- 0 and it's percentage : 0.0
 Total NaN values in row 15461 :- 0 and it's percentage : 0.0
 Total NaN values in row 15462 :- 0 and it's percentage : 0.0
 Total NaN values in row 15463 :- 0 and it's percentage : 0.0
 Total NaN values in row 15464 :- 0 and it's percentage : 0.0
 Total NaN values in row 15465 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 15466 :- 0 and it's percentage : 0.0
 Total NaN values in row 15467 :- 0 and it's percentage : 0.0
 Total NaN values in row 15468 :- 0 and it's percentage : 0.0
 Total NaN values in row 15469 :- 0 and it's percentage : 0.0
 Total NaN values in row 15470 :- 0 and it's percentage : 0.0
 Total NaN values in row 15471 :- 0 and it's percentage : 0.0
 Total NaN values in row 15472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15473 :- 0 and it's percentage : 0.0
 Total NaN values in row 15474 :- 0 and it's percentage : 0.0
 Total NaN values in row 15475 :- 0 and it's percentage : 0.0
 Total NaN values in row 15476 :- 0 and it's percentage : 0.0
 Total NaN values in row 15477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15479 :- 0 and it's percentage : 0.0
 Total NaN values in row 15480 :- 0 and it's percentage : 0.0
 Total NaN values in row 15481 :- 0 and it's percentage : 0.0
 Total NaN values in row 15482 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15483 :- 0 and it's percentage : 0.0
 Total NaN values in row 15484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15485 :- 0 and it's percentage : 0.0
 Total NaN values in row 15486 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15487 :- 0 and it's percentage : 0.0
 Total NaN values in row 15488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15489 :- 0 and it's percentage : 0.0
 Total NaN values in row 15490 :- 0 and it's percentage : 0.0
 Total NaN values in row 15491 :- 0 and it's percentage : 0.0
 Total NaN values in row 15492 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15493 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15494 :- 0 and it's percentage : 0.0
 Total NaN values in row 15495 :- 0 and it's percentage : 0.0
 Total NaN values in row 15496 :- 0 and it's percentage : 0.0
 Total NaN values in row 15497 :- 0 and it's percentage : 0.0
 Total NaN values in row 15498 :- 0 and it's percentage : 0.0
 Total NaN values in row 15499 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15501 :- 0 and it's percentage : 0.0
 Total NaN values in row 15502 :- 0 and it's percentage : 0.0
 Total NaN values in row 15503 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15504 :- 0 and it's percentage : 0.0
 Total NaN values in row 15505 :- 0 and it's percentage : 0.0
 Total NaN values in row 15506 :- 0 and it's percentage : 0.0
 Total NaN values in row 15507 :- 0 and it's percentage : 0.0
 Total NaN values in row 15508 :- 0 and it's percentage : 0.0
 Total NaN values in row 15509 :- 0 and it's percentage : 0.0
 Total NaN values in row 15510 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15511 :- 0 and it's percentage : 0.0
 Total NaN values in row 15512 :- 0 and it's percentage : 0.0
 Total NaN values in row 15513 :- 0 and it's percentage : 0.0
 Total NaN values in row 15514 :- 0 and it's percentage : 0.0
 Total NaN values in row 15515 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15516 :- 0 and it's percentage : 0.0
 Total NaN values in row 15517 :- 0 and it's percentage : 0.0
 Total NaN values in row 15518 :- 0 and it's percentage : 0.0
 Total NaN values in row 15519 :- 0 and it's percentage : 0.0
 Total NaN values in row 15520 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15521 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15522 :- 0 and it's percentage : 0.0
 Total NaN values in row 15523 :- 0 and it's percentage : 0.0
 Total NaN values in row 15524 :- 0 and it's percentage : 0.0
 Total NaN values in row 15525 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15526 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15527 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15528 :- 0 and it's percentage : 0.0
 Total NaN values in row 15529 :- 0 and it's percentage : 0.0
 Total NaN values in row 15530 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15531 :- 0 and it's percentage : 0.0
 Total NaN values in row 15532 :- 0 and it's percentage : 0.0
 Total NaN values in row 15533 :- 0 and it's percentage : 0.0
 Total NaN values in row 15534 :- 0 and it's percentage : 0.0
 Total NaN values in row 15535 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15536 :- 0 and it's percentage : 0.0
 Total NaN values in row 15537 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 15538 :- 0 and it's percentage : 0.0
 Total NaN values in row 15539 :- 0 and it's percentage : 0.0
 Total NaN values in row 15540 :- 0 and it's percentage : 0.0
 Total NaN values in row 15541 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15542 :- 0 and it's percentage : 0.0
 Total NaN values in row 15543 :- 0 and it's percentage : 0.0
 Total NaN values in row 15544 :- 0 and it's percentage : 0.0
 Total NaN values in row 15545 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15546 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15547 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15549 :- 0 and it's percentage : 0.0
 Total NaN values in row 15550 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15551 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15553 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15554 :- 0 and it's percentage : 0.0
 Total NaN values in row 15555 :- 0 and it's percentage : 0.0
 Total NaN values in row 15556 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15557 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15558 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15559 :- 0 and it's percentage : 0.0
 Total NaN values in row 15560 :- 0 and it's percentage : 0.0
 Total NaN values in row 15561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15562 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 15563 :- 0 and it's percentage : 0.0
 Total NaN values in row 15564 :- 0 and it's percentage : 0.0
 Total NaN values in row 15565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15566 :- 0 and it's percentage : 0.0
 Total NaN values in row 15567 :- 0 and it's percentage : 0.0
 Total NaN values in row 15568 :- 0 and it's percentage : 0.0
 Total NaN values in row 15569 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15570 :- 0 and it's percentage : 0.0
 Total NaN values in row 15571 :- 0 and it's percentage : 0.0
 Total NaN values in row 15572 :- 0 and it's percentage : 0.0
 Total NaN values in row 15573 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15574 :- 0 and it's percentage : 0.0
 Total NaN values in row 15575 :- 0 and it's percentage : 0.0
 Total NaN values in row 15576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15577 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15578 :- 0 and it's percentage : 0.0
 Total NaN values in row 15579 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15580 :- 0 and it's percentage : 0.0
 Total NaN values in row 15581 :- 0 and it's percentage : 0.0
 Total NaN values in row 15582 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15583 :- 0 and it's percentage : 0.0
 Total NaN values in row 15584 :- 0 and it's percentage : 0.0
 Total NaN values in row 15585 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15586 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15587 :- 0 and it's percentage : 0.0
 Total NaN values in row 15588 :- 0 and it's percentage : 0.0
 Total NaN values in row 15589 :- 0 and it's percentage : 0.0
 Total NaN values in row 15590 :- 0 and it's percentage : 0.0
 Total NaN values in row 15591 :- 0 and it's percentage : 0.0
 Total NaN values in row 15592 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15593 :- 0 and it's percentage : 0.0
 Total NaN values in row 15594 :- 0 and it's percentage : 0.0
 Total NaN values in row 15595 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15596 :- 0 and it's percentage : 0.0
 Total NaN values in row 15597 :- 0 and it's percentage : 0.0
 Total NaN values in row 15598 :- 0 and it's percentage : 0.0
 Total NaN values in row 15599 :- 0 and it's percentage : 0.0
 Total NaN values in row 15600 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15601 :- 0 and it's percentage : 0.0
 Total NaN values in row 15602 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15603 :- 0 and it's percentage : 0.0
 Total NaN values in row 15604 :- 0 and it's percentage : 0.0
 Total NaN values in row 15605 :- 0 and it's percentage : 0.0
 Total NaN values in row 15606 :- 0 and it's percentage : 0.0
 Total NaN values in row 15607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15608 :- 0 and it's percentage : 0.0
 Total NaN values in row 15609 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15610 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15611 :- 0 and it's percentage : 0.0
 Total NaN values in row 15612 :- 0 and it's percentage : 0.0
 Total NaN values in row 15613 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15614 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15615 :- 0 and it's percentage : 0.0
 Total NaN values in row 15616 :- 0 and it's percentage : 0.0
 Total NaN values in row 15617 :- 0 and it's percentage : 0.0
 Total NaN values in row 15618 :- 0 and it's percentage : 0.0
 Total NaN values in row 15619 :- 0 and it's percentage : 0.0
 Total NaN values in row 15620 :- 0 and it's percentage : 0.0
 Total NaN values in row 15621 :- 0 and it's percentage : 0.0
 Total NaN values in row 15622 :- 0 and it's percentage : 0.0
 Total NaN values in row 15623 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 15624 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15625 :- 0 and it's percentage : 0.0
 Total NaN values in row 15626 :- 0 and it's percentage : 0.0
 Total NaN values in row 15627 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15628 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15629 :- 0 and it's percentage : 0.0
 Total NaN values in row 15630 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15631 :- 0 and it's percentage : 0.0
 Total NaN values in row 15632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15633 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15634 :- 0 and it's percentage : 0.0
 Total NaN values in row 15635 :- 0 and it's percentage : 0.0
 Total NaN values in row 15636 :- 0 and it's percentage : 0.0
 Total NaN values in row 15637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15638 :- 0 and it's percentage : 0.0
 Total NaN values in row 15639 :- 0 and it's percentage : 0.0
 Total NaN values in row 15640 :- 0 and it's percentage : 0.0
 Total NaN values in row 15641 :- 0 and it's percentage : 0.0
 Total NaN values in row 15642 :- 0 and it's percentage : 0.0
 Total NaN values in row 15643 :- 0 and it's percentage : 0.0
 Total NaN values in row 15644 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15645 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15646 :- 0 and it's percentage : 0.0
 Total NaN values in row 15647 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15649 :- 0 and it's percentage : 0.0
 Total NaN values in row 15650 :- 0 and it's percentage : 0.0
 Total NaN values in row 15651 :- 0 and it's percentage : 0.0
 Total NaN values in row 15652 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15653 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15654 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15655 :- 0 and it's percentage : 0.0
 Total NaN values in row 15656 :- 0 and it's percentage : 0.0
 Total NaN values in row 15657 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15658 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15659 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15660 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15661 :- 0 and it's percentage : 0.0
 Total NaN values in row 15662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15663 :- 0 and it's percentage : 0.0
 Total NaN values in row 15664 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15665 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15666 :- 0 and it's percentage : 0.0
 Total NaN values in row 15667 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15668 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15669 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15670 :- 0 and it's percentage : 0.0
 Total NaN values in row 15671 :- 0 and it's percentage : 0.0
 Total NaN values in row 15672 :- 0 and it's percentage : 0.0
 Total NaN values in row 15673 :- 0 and it's percentage : 0.0
 Total NaN values in row 15674 :- 0 and it's percentage : 0.0
 Total NaN values in row 15675 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15676 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15677 :- 0 and it's percentage : 0.0
 Total NaN values in row 15678 :- 0 and it's percentage : 0.0
 Total NaN values in row 15679 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15680 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15681 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15682 :- 0 and it's percentage : 0.0
 Total NaN values in row 15683 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15684 :- 0 and it's percentage : 0.0
 Total NaN values in row 15685 :- 0 and it's percentage : 0.0
 Total NaN values in row 15686 :- 0 and it's percentage : 0.0
 Total NaN values in row 15687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15688 :- 0 and it's percentage : 0.0
 Total NaN values in row 15689 :- 0 and it's percentage : 0.0
 Total NaN values in row 15690 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15691 :- 0 and it's percentage : 0.0
 Total NaN values in row 15692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15693 :- 0 and it's percentage : 0.0
 Total NaN values in row 15694 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15695 :- 0 and it's percentage : 0.0
 Total NaN values in row 15696 :- 0 and it's percentage : 0.0
 Total NaN values in row 15697 :- 0 and it's percentage : 0.0
 Total NaN values in row 15698 :- 0 and it's percentage : 0.0
 Total NaN values in row 15699 :- 0 and it's percentage : 0.0
 Total NaN values in row 15700 :- 0 and it's percentage : 0.0
 Total NaN values in row 15701 :- 0 and it's percentage : 0.0
 Total NaN values in row 15702 :- 0 and it's percentage : 0.0
 Total NaN values in row 15703 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 15704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15705 :- 0 and it's percentage : 0.0
 Total NaN values in row 15706 :- 0 and it's percentage : 0.0
 Total NaN values in row 15707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15708 :- 0 and it's percentage : 0.0
 Total NaN values in row 15709 :- 0 and it's percentage : 0.0
 Total NaN values in row 15710 :- 0 and it's percentage : 0.0
 Total NaN values in row 15711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15712 :- 0 and it's percentage : 0.0
 Total NaN values in row 15713 :- 0 and it's percentage : 0.0
 Total NaN values in row 15714 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15715 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15717 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15718 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15719 :- 0 and it's percentage : 0.0
 Total NaN values in row 15720 :- 0 and it's percentage : 0.0
 Total NaN values in row 15721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15722 :- 0 and it's percentage : 0.0
 Total NaN values in row 15723 :- 0 and it's percentage : 0.0
 Total NaN values in row 15724 :- 0 and it's percentage : 0.0
 Total NaN values in row 15725 :- 0 and it's percentage : 0.0
 Total NaN values in row 15726 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15727 :- 0 and it's percentage : 0.0
 Total NaN values in row 15728 :- 0 and it's percentage : 0.0
 Total NaN values in row 15729 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15730 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15731 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15732 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15733 :- 0 and it's percentage : 0.0
 Total NaN values in row 15734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15735 :- 0 and it's percentage : 0.0
 Total NaN values in row 15736 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15737 :- 0 and it's percentage : 0.0
 Total NaN values in row 15738 :- 0 and it's percentage : 0.0
 Total NaN values in row 15739 :- 0 and it's percentage : 0.0
 Total NaN values in row 15740 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15741 :- 0 and it's percentage : 0.0
 Total NaN values in row 15742 :- 0 and it's percentage : 0.0
 Total NaN values in row 15743 :- 0 and it's percentage : 0.0
 Total NaN values in row 15744 :- 0 and it's percentage : 0.0
 Total NaN values in row 15745 :- 0 and it's percentage : 0.0
 Total NaN values in row 15746 :- 0 and it's percentage : 0.0
 Total NaN values in row 15747 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15748 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 15749 :- 0 and it's percentage : 0.0
 Total NaN values in row 15750 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15751 :- 0 and it's percentage : 0.0
 Total NaN values in row 15752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15753 :- 0 and it's percentage : 0.0
 Total NaN values in row 15754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15755 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15756 :- 0 and it's percentage : 0.0
 Total NaN values in row 15757 :- 0 and it's percentage : 0.0
 Total NaN values in row 15758 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15759 :- 0 and it's percentage : 0.0
 Total NaN values in row 15760 :- 0 and it's percentage : 0.0
 Total NaN values in row 15761 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15762 :- 0 and it's percentage : 0.0
 Total NaN values in row 15763 :- 0 and it's percentage : 0.0
 Total NaN values in row 15764 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15765 :- 0 and it's percentage : 0.0
 Total NaN values in row 15766 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15767 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15768 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15769 :- 0 and it's percentage : 0.0
 Total NaN values in row 15770 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15771 :- 0 and it's percentage : 0.0
 Total NaN values in row 15772 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15774 :- 0 and it's percentage : 0.0
 Total NaN values in row 15775 :- 0 and it's percentage : 0.0
 Total NaN values in row 15776 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15777 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15778 :- 0 and it's percentage : 0.0
 Total NaN values in row 15779 :- 0 and it's percentage : 0.0
 Total NaN values in row 15780 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15781 :- 0 and it's percentage : 0.0
 Total NaN values in row 15782 :- 0 and it's percentage : 0.0
 Total NaN values in row 15783 :- 0 and it's percentage : 0.0
 Total NaN values in row 15784 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15785 :- 0 and it's percentage : 0.0
 Total NaN values in row 15786 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 15787 :- 0 and it's percentage : 0.0
 Total NaN values in row 15788 :- 0 and it's percentage : 0.0
 Total NaN values in row 15789 :- 0 and it's percentage : 0.0
 Total NaN values in row 15790 :- 0 and it's percentage : 0.0
 Total NaN values in row 15791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15792 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15793 :- 0 and it's percentage : 0.0
 Total NaN values in row 15794 :- 0 and it's percentage : 0.0
 Total NaN values in row 15795 :- 0 and it's percentage : 0.0
 Total NaN values in row 15796 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15797 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15798 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15799 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15800 :- 0 and it's percentage : 0.0
 Total NaN values in row 15801 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15802 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15803 :- 0 and it's percentage : 0.0
 Total NaN values in row 15804 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15805 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15806 :- 0 and it's percentage : 0.0
 Total NaN values in row 15807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15808 :- 0 and it's percentage : 0.0
 Total NaN values in row 15809 :- 0 and it's percentage : 0.0
 Total NaN values in row 15810 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15811 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15812 :- 0 and it's percentage : 0.0
 Total NaN values in row 15813 :- 0 and it's percentage : 0.0
 Total NaN values in row 15814 :- 0 and it's percentage : 0.0
 Total NaN values in row 15815 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15816 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15817 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15818 :- 0 and it's percentage : 0.0
 Total NaN values in row 15819 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15820 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15821 :- 0 and it's percentage : 0.0
 Total NaN values in row 15822 :- 0 and it's percentage : 0.0
 Total NaN values in row 15823 :- 0 and it's percentage : 0.0
 Total NaN values in row 15824 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15825 :- 0 and it's percentage : 0.0
 Total NaN values in row 15826 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15827 :- 0 and it's percentage : 0.0
 Total NaN values in row 15828 :- 0 and it's percentage : 0.0
 Total NaN values in row 15829 :- 0 and it's percentage : 0.0
 Total NaN values in row 15830 :- 0 and it's percentage : 0.0
 Total NaN values in row 15831 :- 0 and it's percentage : 0.0
 Total NaN values in row 15832 :- 0 and it's percentage : 0.0
 Total NaN values in row 15833 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15834 :- 0 and it's percentage : 0.0
 Total NaN values in row 15835 :- 0 and it's percentage : 0.0
 Total NaN values in row 15836 :- 0 and it's percentage : 0.0
 Total NaN values in row 15837 :- 0 and it's percentage : 0.0
 Total NaN values in row 15838 :- 0 and it's percentage : 0.0
 Total NaN values in row 15839 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15840 :- 0 and it's percentage : 0.0
 Total NaN values in row 15841 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15843 :- 0 and it's percentage : 0.0
 Total NaN values in row 15844 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15845 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15846 :- 0 and it's percentage : 0.0
 Total NaN values in row 15847 :- 0 and it's percentage : 0.0
 Total NaN values in row 15848 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15849 :- 0 and it's percentage : 0.0
 Total NaN values in row 15850 :- 0 and it's percentage : 0.0
 Total NaN values in row 15851 :- 0 and it's percentage : 0.0
 Total NaN values in row 15852 :- 0 and it's percentage : 0.0
 Total NaN values in row 15853 :- 0 and it's percentage : 0.0
 Total NaN values in row 15854 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15855 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15856 :- 0 and it's percentage : 0.0
 Total NaN values in row 15857 :- 0 and it's percentage : 0.0
 Total NaN values in row 15858 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15859 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15860 :- 0 and it's percentage : 0.0
 Total NaN values in row 15861 :- 0 and it's percentage : 0.0
 Total NaN values in row 15862 :- 0 and it's percentage : 0.0
 Total NaN values in row 15863 :- 0 and it's percentage : 0.0
 Total NaN values in row 15864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15865 :- 0 and it's percentage : 0.0
 Total NaN values in row 15866 :- 0 and it's percentage : 0.0
 Total NaN values in row 15867 :- 0 and it's percentage : 0.0
 Total NaN values in row 15868 :- 0 and it's percentage : 0.0
 Total NaN values in row 15869 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15870 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15871 :- 0 and it's percentage : 0.0
 Total NaN values in row 15872 :- 0 and it's percentage : 0.0
 Total NaN values in row 15873 :- 0 and it's percentage : 0.0
 Total NaN values in row 15874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15875 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15876 :- 0 and it's percentage : 0.0
 Total NaN values in row 15877 :- 0 and it's percentage : 0.0
 Total NaN values in row 15878 :- 0 and it's percentage : 0.0
 Total NaN values in row 15879 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 15880 :- 0 and it's percentage : 0.0
 Total NaN values in row 15881 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15882 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15883 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15884 :- 0 and it's percentage : 0.0
 Total NaN values in row 15885 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15886 :- 0 and it's percentage : 0.0
 Total NaN values in row 15887 :- 0 and it's percentage : 0.0
 Total NaN values in row 15888 :- 0 and it's percentage : 0.0
 Total NaN values in row 15889 :- 0 and it's percentage : 0.0
 Total NaN values in row 15890 :- 0 and it's percentage : 0.0
 Total NaN values in row 15891 :- 0 and it's percentage : 0.0
 Total NaN values in row 15892 :- 0 and it's percentage : 0.0
 Total NaN values in row 15893 :- 0 and it's percentage : 0.0
 Total NaN values in row 15894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15895 :- 0 and it's percentage : 0.0
 Total NaN values in row 15896 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15898 :- 0 and it's percentage : 0.0
 Total NaN values in row 15899 :- 0 and it's percentage : 0.0
 Total NaN values in row 15900 :- 0 and it's percentage : 0.0
 Total NaN values in row 15901 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15902 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15903 :- 0 and it's percentage : 0.0
 Total NaN values in row 15904 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15905 :- 0 and it's percentage : 0.0
 Total NaN values in row 15906 :- 0 and it's percentage : 0.0
 Total NaN values in row 15907 :- 0 and it's percentage : 0.0
 Total NaN values in row 15908 :- 0 and it's percentage : 0.0
 Total NaN values in row 15909 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15910 :- 0 and it's percentage : 0.0
 Total NaN values in row 15911 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15912 :- 0 and it's percentage : 0.0
 Total NaN values in row 15913 :- 0 and it's percentage : 0.0
 Total NaN values in row 15914 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15915 :- 0 and it's percentage : 0.0
 Total NaN values in row 15916 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15917 :- 0 and it's percentage : 0.0
 Total NaN values in row 15918 :- 0 and it's percentage : 0.0
 Total NaN values in row 15919 :- 0 and it's percentage : 0.0
 Total NaN values in row 15920 :- 0 and it's percentage : 0.0
 Total NaN values in row 15921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15922 :- 0 and it's percentage : 0.0
 Total NaN values in row 15923 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15924 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15925 :- 0 and it's percentage : 0.0
 Total NaN values in row 15926 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15928 :- 0 and it's percentage : 0.0
 Total NaN values in row 15929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15930 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15931 :- 0 and it's percentage : 0.0
 Total NaN values in row 15932 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15933 :- 0 and it's percentage : 0.0
 Total NaN values in row 15934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15935 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15936 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15937 :- 0 and it's percentage : 0.0
 Total NaN values in row 15938 :- 0 and it's percentage : 0.0
 Total NaN values in row 15939 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15940 :- 0 and it's percentage : 0.0
 Total NaN values in row 15941 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15942 :- 0 and it's percentage : 0.0
 Total NaN values in row 15943 :- 0 and it's percentage : 0.0
 Total NaN values in row 15944 :- 0 and it's percentage : 0.0
 Total NaN values in row 15945 :- 0 and it's percentage : 0.0
 Total NaN values in row 15946 :- 0 and it's percentage : 0.0
 Total NaN values in row 15947 :- 0 and it's percentage : 0.0
 Total NaN values in row 15948 :- 0 and it's percentage : 0.0
 Total NaN values in row 15949 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15950 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15951 :- 0 and it's percentage : 0.0
 Total NaN values in row 15952 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15954 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15955 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15956 :- 0 and it's percentage : 0.0
 Total NaN values in row 15957 :- 0 and it's percentage : 0.0
 Total NaN values in row 15958 :- 0 and it's percentage : 0.0
 Total NaN values in row 15959 :- 0 and it's percentage : 0.0
 Total NaN values in row 15960 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15961 :- 0 and it's percentage : 0.0
 Total NaN values in row 15962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15963 :- 0 and it's percentage : 0.0
 Total NaN values in row 15964 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15965 :- 0 and it's percentage : 0.0
 Total NaN values in row 15966 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15967 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15968 :- 0 and it's percentage : 0.0
 Total NaN values in row 15969 :- 0 and it's percentage : 0.0
 Total NaN values in row 15970 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15971 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15972 :- 0 and it's percentage : 0.0
 Total NaN values in row 15973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15974 :- 0 and it's percentage : 0.0
 Total NaN values in row 15975 :- 0 and it's percentage : 0.0
 Total NaN values in row 15976 :- 0 and it's percentage : 0.0
 Total NaN values in row 15977 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15978 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15979 :- 0 and it's percentage : 0.0
 Total NaN values in row 15980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15981 :- 0 and it's percentage : 0.0
 Total NaN values in row 15982 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15983 :- 0 and it's percentage : 0.0
 Total NaN values in row 15984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15985 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15986 :- 0 and it's percentage : 0.0
 Total NaN values in row 15987 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15988 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 15989 :- 0 and it's percentage : 0.0
 Total NaN values in row 15990 :- 0 and it's percentage : 0.0
 Total NaN values in row 15991 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15992 :- 0 and it's percentage : 0.0
 Total NaN values in row 15993 :- 0 and it's percentage : 0.0
 Total NaN values in row 15994 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15995 :- 0 and it's percentage : 0.0
 Total NaN values in row 15996 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 15997 :- 0 and it's percentage : 0.0
 Total NaN values in row 15998 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 15999 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16000 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16001 :- 0 and it's percentage : 0.0
 Total NaN values in row 16002 :- 0 and it's percentage : 0.0
 Total NaN values in row 16003 :- 0 and it's percentage : 0.0
 Total NaN values in row 16004 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16005 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16006 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16007 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16008 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16009 :- 0 and it's percentage : 0.0

 Total NaN values in row 16010 :- 0 and it's percentage : 0.0
 Total NaN values in row 16011 :- 0 and it's percentage : 0.0
 Total NaN values in row 16012 :- 0 and it's percentage : 0.0
 Total NaN values in row 16013 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16014 :- 0 and it's percentage : 0.0
 Total NaN values in row 16015 :- 0 and it's percentage : 0.0
 Total NaN values in row 16016 :- 0 and it's percentage : 0.0
 Total NaN values in row 16017 :- 0 and it's percentage : 0.0
 Total NaN values in row 16018 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16019 :- 0 and it's percentage : 0.0
 Total NaN values in row 16020 :- 0 and it's percentage : 0.0
 Total NaN values in row 16021 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16022 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16023 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16024 :- 0 and it's percentage : 0.0
 Total NaN values in row 16025 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16026 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16027 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16029 :- 0 and it's percentage : 0.0
 Total NaN values in row 16030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16031 :- 0 and it's percentage : 0.0
 Total NaN values in row 16032 :- 0 and it's percentage : 0.0
 Total NaN values in row 16033 :- 0 and it's percentage : 0.0
 Total NaN values in row 16034 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16035 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16036 :- 0 and it's percentage : 0.0
 Total NaN values in row 16037 :- 0 and it's percentage : 0.0
 Total NaN values in row 16038 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16039 :- 0 and it's percentage : 0.0
 Total NaN values in row 16040 :- 0 and it's percentage : 0.0
 Total NaN values in row 16041 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16042 :- 0 and it's percentage : 0.0
 Total NaN values in row 16043 :- 0 and it's percentage : 0.0
 Total NaN values in row 16044 :- 0 and it's percentage : 0.0
 Total NaN values in row 16045 :- 0 and it's percentage : 0.0
 Total NaN values in row 16046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16047 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16048 :- 0 and it's percentage : 0.0
 Total NaN values in row 16049 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16051 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16052 :- 0 and it's percentage : 0.0
 Total NaN values in row 16053 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16054 :- 0 and it's percentage : 0.0
 Total NaN values in row 16055 :- 0 and it's percentage : 0.0
 Total NaN values in row 16056 :- 0 and it's percentage : 0.0
 Total NaN values in row 16057 :- 0 and it's percentage : 0.0
 Total NaN values in row 16058 :- 0 and it's percentage : 0.0
 Total NaN values in row 16059 :- 0 and it's percentage : 0.0
 Total NaN values in row 16060 :- 0 and it's percentage : 0.0
 Total NaN values in row 16061 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16062 :- 0 and it's percentage : 0.0
 Total NaN values in row 16063 :- 0 and it's percentage : 0.0
 Total NaN values in row 16064 :- 0 and it's percentage : 0.0
 Total NaN values in row 16065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16066 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16067 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16068 :- 0 and it's percentage : 0.0
 Total NaN values in row 16069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16070 :- 0 and it's percentage : 0.0
 Total NaN values in row 16071 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16072 :- 0 and it's percentage : 0.0
 Total NaN values in row 16073 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16074 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16075 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16076 :- 0 and it's percentage : 0.0
 Total NaN values in row 16077 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16078 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16079 :- 0 and it's percentage : 0.0
 Total NaN values in row 16080 :- 0 and it's percentage : 0.0
 Total NaN values in row 16081 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16082 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16083 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16084 :- 0 and it's percentage : 0.0
 Total NaN values in row 16085 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16086 :- 0 and it's percentage : 0.0
 Total NaN values in row 16087 :- 0 and it's percentage : 0.0
 Total NaN values in row 16088 :- 0 and it's percentage : 0.0
 Total NaN values in row 16089 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16090 :- 0 and it's percentage : 0.0
 Total NaN values in row 16091 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16092 :- 0 and it's percentage : 0.0
 Total NaN values in row 16093 :- 0 and it's percentage : 0.0
 Total NaN values in row 16094 :- 0 and it's percentage : 0.0
 Total NaN values in row 16095 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16096 :- 0 and it's percentage : 0.0
 Total NaN values in row 16097 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16099 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16100 :- 0 and it's percentage : 0.0
 Total NaN values in row 16101 :- 0 and it's percentage : 0.0
 Total NaN values in row 16102 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16103 :- 0 and it's percentage : 0.0
 Total NaN values in row 16104 :- 0 and it's percentage : 0.0
 Total NaN values in row 16105 :- 0 and it's percentage : 0.0
 Total NaN values in row 16106 :- 0 and it's percentage : 0.0
 Total NaN values in row 16107 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16108 :- 0 and it's percentage : 0.0
 Total NaN values in row 16109 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16110 :- 0 and it's percentage : 0.0
 Total NaN values in row 16111 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16112 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16113 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16114 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16115 :- 0 and it's percentage : 0.0
 Total NaN values in row 16116 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16118 :- 0 and it's percentage : 0.0
 Total NaN values in row 16119 :- 0 and it's percentage : 0.0
 Total NaN values in row 16120 :- 0 and it's percentage : 0.0
 Total NaN values in row 16121 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 16122 :- 0 and it's percentage : 0.0
 Total NaN values in row 16123 :- 0 and it's percentage : 0.0
 Total NaN values in row 16124 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16125 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16126 :- 0 and it's percentage : 0.0
 Total NaN values in row 16127 :- 0 and it's percentage : 0.0
 Total NaN values in row 16128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16129 :- 0 and it's percentage : 0.0
 Total NaN values in row 16130 :- 0 and it's percentage : 0.0
 Total NaN values in row 16131 :- 0 and it's percentage : 0.0
 Total NaN values in row 16132 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16133 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16134 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16135 :- 0 and it's percentage : 0.0
 Total NaN values in row 16136 :- 0 and it's percentage : 0.0
 Total NaN values in row 16137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16139 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16140 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16141 :- 0 and it's percentage : 0.0
 Total NaN values in row 16142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16143 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16144 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16145 :- 0 and it's percentage : 0.0
 Total NaN values in row 16146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16147 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16148 :- 0 and it's percentage : 0.0
 Total NaN values in row 16149 :- 0 and it's percentage : 0.0
 Total NaN values in row 16150 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16151 :- 0 and it's percentage : 0.0
 Total NaN values in row 16152 :- 0 and it's percentage : 0.0
 Total NaN values in row 16153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16154 :- 0 and it's percentage : 0.0
 Total NaN values in row 16155 :- 0 and it's percentage : 0.0
 Total NaN values in row 16156 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16157 :- 0 and it's percentage : 0.0
 Total NaN values in row 16158 :- 0 and it's percentage : 0.0
 Total NaN values in row 16159 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16160 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16161 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16162 :- 0 and it's percentage : 0.0
 Total NaN values in row 16163 :- 0 and it's percentage : 0.0
 Total NaN values in row 16164 :- 0 and it's percentage : 0.0
 Total NaN values in row 16165 :- 0 and it's percentage : 0.0
 Total NaN values in row 16166 :- 0 and it's percentage : 0.0
 Total NaN values in row 16167 :- 0 and it's percentage : 0.0
 Total NaN values in row 16168 :- 0 and it's percentage : 0.0
 Total NaN values in row 16169 :- 0 and it's percentage : 0.0
 Total NaN values in row 16170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16171 :- 0 and it's percentage : 0.0
 Total NaN values in row 16172 :- 0 and it's percentage : 0.0
 Total NaN values in row 16173 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16174 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16175 :- 0 and it's percentage : 0.0
 Total NaN values in row 16176 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16179 :- 0 and it's percentage : 0.0
 Total NaN values in row 16180 :- 0 and it's percentage : 0.0
 Total NaN values in row 16181 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16182 :- 0 and it's percentage : 0.0
 Total NaN values in row 16183 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 16184 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16186 :- 0 and it's percentage : 0.0
 Total NaN values in row 16187 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16188 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16189 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16191 :- 0 and it's percentage : 0.0
 Total NaN values in row 16192 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16193 :- 0 and it's percentage : 0.0
 Total NaN values in row 16194 :- 0 and it's percentage : 0.0
 Total NaN values in row 16195 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16196 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16197 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16198 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16200 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16201 :- 0 and it's percentage : 0.0
 Total NaN values in row 16202 :- 0 and it's percentage : 0.0
 Total NaN values in row 16203 :- 0 and it's percentage : 0.0
 Total NaN values in row 16204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16205 :- 0 and it's percentage : 0.0
 Total NaN values in row 16206 :- 0 and it's percentage : 0.0
 Total NaN values in row 16207 :- 0 and it's percentage : 0.0
 Total NaN values in row 16208 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16209 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16210 :- 0 and it's percentage : 0.0
 Total NaN values in row 16211 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16212 :- 0 and it's percentage : 0.0
 Total NaN values in row 16213 :- 0 and it's percentage : 0.0
 Total NaN values in row 16214 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16216 :- 0 and it's percentage : 0.0
 Total NaN values in row 16217 :- 0 and it's percentage : 0.0
 Total NaN values in row 16218 :- 0 and it's percentage : 0.0
 Total NaN values in row 16219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16220 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16221 :- 0 and it's percentage : 0.0
 Total NaN values in row 16222 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16223 :- 0 and it's percentage : 0.0
 Total NaN values in row 16224 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16225 :- 0 and it's percentage : 0.0
 Total NaN values in row 16226 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16228 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16229 :- 0 and it's percentage : 0.0
 Total NaN values in row 16230 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16231 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16233 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16234 :- 0 and it's percentage : 0.0
 Total NaN values in row 16235 :- 0 and it's percentage : 0.0
 Total NaN values in row 16236 :- 0 and it's percentage : 0.0
 Total NaN values in row 16237 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16238 :- 0 and it's percentage : 0.0
 Total NaN values in row 16239 :- 0 and it's percentage : 0.0
 Total NaN values in row 16240 :- 0 and it's percentage : 0.0
 Total NaN values in row 16241 :- 0 and it's percentage : 0.0
 Total NaN values in row 16242 :- 0 and it's percentage : 0.0
 Total NaN values in row 16243 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16244 :- 0 and it's percentage : 0.0
 Total NaN values in row 16245 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16246 :- 0 and it's percentage : 0.0
 Total NaN values in row 16247 :- 0 and it's percentage : 0.0
 Total NaN values in row 16248 :- 0 and it's percentage : 0.0
 Total NaN values in row 16249 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16250 :- 0 and it's percentage : 0.0
 Total NaN values in row 16251 :- 0 and it's percentage : 0.0
 Total NaN values in row 16252 :- 0 and it's percentage : 0.0
 Total NaN values in row 16253 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16254 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16255 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16256 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16257 :- 0 and it's percentage : 0.0
 Total NaN values in row 16258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16259 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16260 :- 0 and it's percentage : 0.0
 Total NaN values in row 16261 :- 0 and it's percentage : 0.0
 Total NaN values in row 16262 :- 0 and it's percentage : 0.0
 Total NaN values in row 16263 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16264 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16265 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16266 :- 0 and it's percentage : 0.0
 Total NaN values in row 16267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16268 :- 0 and it's percentage : 0.0
 Total NaN values in row 16269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16270 :- 0 and it's percentage : 0.0
 Total NaN values in row 16271 :- 0 and it's percentage : 0.0
 Total NaN values in row 16272 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16273 :- 0 and it's percentage : 0.0
 Total NaN values in row 16274 :- 0 and it's percentage : 0.0
 Total NaN values in row 16275 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16276 :- 0 and it's percentage : 0.0
 Total NaN values in row 16277 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16279 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16280 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16281 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16283 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16284 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16285 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16286 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16287 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16288 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16289 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16290 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16291 :- 0 and it's percentage : 0.0
 Total NaN values in row 16292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16293 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16294 :- 0 and it's percentage : 0.0
 Total NaN values in row 16295 :- 0 and it's percentage : 0.0
 Total NaN values in row 16296 :- 0 and it's percentage : 0.0
 Total NaN values in row 16297 :- 0 and it's percentage : 0.0
 Total NaN values in row 16298 :- 0 and it's percentage : 0.0
 Total NaN values in row 16299 :- 0 and it's percentage : 0.0
 Total NaN values in row 16300 :- 0 and it's percentage : 0.0
 Total NaN values in row 16301 :- 0 and it's percentage : 0.0
 Total NaN values in row 16302 :- 0 and it's percentage : 0.0
 Total NaN values in row 16303 :- 0 and it's percentage : 0.0
 Total NaN values in row 16304 :- 0 and it's percentage : 0.0
 Total NaN values in row 16305 :- 0 and it's percentage : 0.0
 Total NaN values in row 16306 :- 0 and it's percentage : 0.0
 Total NaN values in row 16307 :- 0 and it's percentage : 0.0
 Total NaN values in row 16308 :- 0 and it's percentage : 0.0
 Total NaN values in row 16309 :- 0 and it's percentage : 0.0
 Total NaN values in row 16310 :- 0 and it's percentage : 0.0
 Total NaN values in row 16311 :- 0 and it's percentage : 0.0
 Total NaN values in row 16312 :- 0 and it's percentage : 0.0
 Total NaN values in row 16313 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16314 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16315 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16316 :- 0 and it's percentage : 0.0
 Total NaN values in row 16317 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 16318 :- 0 and it's percentage : 0.0
 Total NaN values in row 16319 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16320 :- 0 and it's percentage : 0.0
 Total NaN values in row 16321 :- 0 and it's percentage : 0.0
 Total NaN values in row 16322 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16323 :- 0 and it's percentage : 0.0
 Total NaN values in row 16324 :- 0 and it's percentage : 0.0
 Total NaN values in row 16325 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16326 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16327 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16331 :- 0 and it's percentage : 0.0
 Total NaN values in row 16332 :- 0 and it's percentage : 0.0
 Total NaN values in row 16333 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16334 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16335 :- 0 and it's percentage : 0.0
 Total NaN values in row 16336 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16337 :- 0 and it's percentage : 0.0
 Total NaN values in row 16338 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16339 :- 0 and it's percentage : 0.0
 Total NaN values in row 16340 :- 0 and it's percentage : 0.0
 Total NaN values in row 16341 :- 0 and it's percentage : 0.0
 Total NaN values in row 16342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16343 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16344 :- 0 and it's percentage : 0.0
 Total NaN values in row 16345 :- 0 and it's percentage : 0.0
 Total NaN values in row 16346 :- 0 and it's percentage : 0.0
 Total NaN values in row 16347 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16348 :- 0 and it's percentage : 0.0
 Total NaN values in row 16349 :- 0 and it's percentage : 0.0
 Total NaN values in row 16350 :- 0 and it's percentage : 0.0
 Total NaN values in row 16351 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16352 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16353 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16354 :- 0 and it's percentage : 0.0
 Total NaN values in row 16355 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16356 :- 0 and it's percentage : 0.0
 Total NaN values in row 16357 :- 0 and it's percentage : 0.0
 Total NaN values in row 16358 :- 0 and it's percentage : 0.0
 Total NaN values in row 16359 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 16360 :- 0 and it's percentage : 0.0
 Total NaN values in row 16361 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16362 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16363 :- 0 and it's percentage : 0.0
 Total NaN values in row 16364 :- 0 and it's percentage : 0.0
 Total NaN values in row 16365 :- 0 and it's percentage : 0.0
 Total NaN values in row 16366 :- 0 and it's percentage : 0.0
 Total NaN values in row 16367 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 16368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16369 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16370 :- 0 and it's percentage : 0.0
 Total NaN values in row 16371 :- 0 and it's percentage : 0.0
 Total NaN values in row 16372 :- 0 and it's percentage : 0.0
 Total NaN values in row 16373 :- 0 and it's percentage : 0.0
 Total NaN values in row 16374 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16376 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16378 :- 0 and it's percentage : 0.0
 Total NaN values in row 16379 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16380 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16381 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16382 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16383 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16384 :- 0 and it's percentage : 0.0
 Total NaN values in row 16385 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16386 :- 0 and it's percentage : 0.0
 Total NaN values in row 16387 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16388 :- 0 and it's percentage : 0.0
 Total NaN values in row 16389 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16390 :- 0 and it's percentage : 0.0
 Total NaN values in row 16391 :- 0 and it's percentage : 0.0
 Total NaN values in row 16392 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16393 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 16394 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16395 :- 0 and it's percentage : 0.0
 Total NaN values in row 16396 :- 0 and it's percentage : 0.0
 Total NaN values in row 16397 :- 0 and it's percentage : 0.0
 Total NaN values in row 16398 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16399 :- 0 and it's percentage : 0.0
 Total NaN values in row 16400 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16401 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16402 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16403 :- 0 and it's percentage : 0.0
 Total NaN values in row 16404 :- 0 and it's percentage : 0.0
 Total NaN values in row 16405 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16406 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16407 :- 0 and it's percentage : 0.0
 Total NaN values in row 16408 :- 0 and it's percentage : 0.0
 Total NaN values in row 16409 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16410 :- 0 and it's percentage : 0.0
 Total NaN values in row 16411 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16412 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16413 :- 0 and it's percentage : 0.0
 Total NaN values in row 16414 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16415 :- 0 and it's percentage : 0.0
 Total NaN values in row 16416 :- 0 and it's percentage : 0.0
 Total NaN values in row 16417 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16418 :- 0 and it's percentage : 0.0
 Total NaN values in row 16419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16420 :- 0 and it's percentage : 0.0
 Total NaN values in row 16421 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16422 :- 0 and it's percentage : 0.0
 Total NaN values in row 16423 :- 0 and it's percentage : 0.0
 Total NaN values in row 16424 :- 0 and it's percentage : 0.0
 Total NaN values in row 16425 :- 0 and it's percentage : 0.0
 Total NaN values in row 16426 :- 0 and it's percentage : 0.0
 Total NaN values in row 16427 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16428 :- 0 and it's percentage : 0.0
 Total NaN values in row 16429 :- 0 and it's percentage : 0.0
 Total NaN values in row 16430 :- 0 and it's percentage : 0.0
 Total NaN values in row 16431 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16433 :- 0 and it's percentage : 0.0
 Total NaN values in row 16434 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16435 :- 0 and it's percentage : 0.0
 Total NaN values in row 16436 :- 0 and it's percentage : 0.0
 Total NaN values in row 16437 :- 0 and it's percentage : 0.0
 Total NaN values in row 16438 :- 0 and it's percentage : 0.0
 Total NaN values in row 16439 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16440 :- 0 and it's percentage : 0.0
 Total NaN values in row 16441 :- 0 and it's percentage : 0.0
 Total NaN values in row 16442 :- 0 and it's percentage : 0.0
 Total NaN values in row 16443 :- 0 and it's percentage : 0.0
 Total NaN values in row 16444 :- 0 and it's percentage : 0.0
 Total NaN values in row 16445 :- 0 and it's percentage : 0.0
 Total NaN values in row 16446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16447 :- 0 and it's percentage : 0.0
 Total NaN values in row 16448 :- 0 and it's percentage : 0.0
 Total NaN values in row 16449 :- 0 and it's percentage : 0.0

 Total NaN values in row 16450 :- 0 and it's percentage : 0.0
 Total NaN values in row 16451 :- 0 and it's percentage : 0.0
 Total NaN values in row 16452 :- 0 and it's percentage : 0.0
 Total NaN values in row 16453 :- 0 and it's percentage : 0.0
 Total NaN values in row 16454 :- 0 and it's percentage : 0.0
 Total NaN values in row 16455 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16456 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16457 :- 0 and it's percentage : 0.0
 Total NaN values in row 16458 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16459 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16460 :- 0 and it's percentage : 0.0
 Total NaN values in row 16461 :- 0 and it's percentage : 0.0
 Total NaN values in row 16462 :- 0 and it's percentage : 0.0
 Total NaN values in row 16463 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16464 :- 0 and it's percentage : 0.0
 Total NaN values in row 16465 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16466 :- 0 and it's percentage : 0.0
 Total NaN values in row 16467 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16468 :- 0 and it's percentage : 0.0
 Total NaN values in row 16469 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16470 :- 0 and it's percentage : 0.0
 Total NaN values in row 16471 :- 0 and it's percentage : 0.0
 Total NaN values in row 16472 :- 0 and it's percentage : 0.0
 Total NaN values in row 16473 :- 0 and it's percentage : 0.0
 Total NaN values in row 16474 :- 0 and it's percentage : 0.0
 Total NaN values in row 16475 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16476 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16477 :- 0 and it's percentage : 0.0
 Total NaN values in row 16478 :- 0 and it's percentage : 0.0
 Total NaN values in row 16479 :- 0 and it's percentage : 0.0
 Total NaN values in row 16480 :- 0 and it's percentage : 0.0
 Total NaN values in row 16481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16482 :- 0 and it's percentage : 0.0
 Total NaN values in row 16483 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16485 :- 0 and it's percentage : 0.0
 Total NaN values in row 16486 :- 0 and it's percentage : 0.0
 Total NaN values in row 16487 :- 0 and it's percentage : 0.0
 Total NaN values in row 16488 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16489 :- 0 and it's percentage : 0.0
 Total NaN values in row 16490 :- 0 and it's percentage : 0.0
 Total NaN values in row 16491 :- 0 and it's percentage : 0.0
 Total NaN values in row 16492 :- 0 and it's percentage : 0.0
 Total NaN values in row 16493 :- 0 and it's percentage : 0.0
 Total NaN values in row 16494 :- 0 and it's percentage : 0.0
 Total NaN values in row 16495 :- 0 and it's percentage : 0.0
 Total NaN values in row 16496 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16497 :- 0 and it's percentage : 0.0
 Total NaN values in row 16498 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16499 :- 0 and it's percentage : 0.0
 Total NaN values in row 16500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16501 :- 0 and it's percentage : 0.0
 Total NaN values in row 16502 :- 0 and it's percentage : 0.0
 Total NaN values in row 16503 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 16504 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16505 :- 0 and it's percentage : 0.0
 Total NaN values in row 16506 :- 0 and it's percentage : 0.0
 Total NaN values in row 16507 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16508 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16509 :- 0 and it's percentage : 0.0
 Total NaN values in row 16510 :- 0 and it's percentage : 0.0
 Total NaN values in row 16511 :- 0 and it's percentage : 0.0
 Total NaN values in row 16512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16513 :- 0 and it's percentage : 0.0
 Total NaN values in row 16514 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16515 :- 0 and it's percentage : 0.0
 Total NaN values in row 16516 :- 0 and it's percentage : 0.0
 Total NaN values in row 16517 :- 0 and it's percentage : 0.0
 Total NaN values in row 16518 :- 0 and it's percentage : 0.0
 Total NaN values in row 16519 :- 0 and it's percentage : 0.0
 Total NaN values in row 16520 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 16521 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16522 :- 0 and it's percentage : 0.0
 Total NaN values in row 16523 :- 0 and it's percentage : 0.0
 Total NaN values in row 16524 :- 0 and it's percentage : 0.0
 Total NaN values in row 16525 :- 0 and it's percentage : 0.0
 Total NaN values in row 16526 :- 0 and it's percentage : 0.0
 Total NaN values in row 16527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16528 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16529 :- 0 and it's percentage : 0.0
 Total NaN values in row 16530 :- 0 and it's percentage : 0.0
 Total NaN values in row 16531 :- 0 and it's percentage : 0.0
 Total NaN values in row 16532 :- 0 and it's percentage : 0.0
 Total NaN values in row 16533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16534 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16535 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16536 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16537 :- 0 and it's percentage : 0.0
 Total NaN values in row 16538 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16539 :- 0 and it's percentage : 0.0
 Total NaN values in row 16540 :- 0 and it's percentage : 0.0
 Total NaN values in row 16541 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16542 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16543 :- 0 and it's percentage : 0.0
 Total NaN values in row 16544 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16545 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16546 :- 0 and it's percentage : 0.0
 Total NaN values in row 16547 :- 0 and it's percentage : 0.0
 Total NaN values in row 16548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16549 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16550 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16551 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16552 :- 0 and it's percentage : 0.0
 Total NaN values in row 16553 :- 0 and it's percentage : 0.0
 Total NaN values in row 16554 :- 0 and it's percentage : 0.0
 Total NaN values in row 16555 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16556 :- 0 and it's percentage : 0.0
 Total NaN values in row 16557 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16558 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16559 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16560 :- 0 and it's percentage : 0.0
 Total NaN values in row 16561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16562 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16563 :- 0 and it's percentage : 0.0
 Total NaN values in row 16564 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16565 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 16566 :- 0 and it's percentage : 0.0
 Total NaN values in row 16567 :- 0 and it's percentage : 0.0
 Total NaN values in row 16568 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16569 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16570 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16571 :- 0 and it's percentage : 0.0
 Total NaN values in row 16572 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16573 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16575 :- 0 and it's percentage : 0.0
 Total NaN values in row 16576 :- 0 and it's percentage : 0.0
 Total NaN values in row 16577 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16578 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16580 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16581 :- 0 and it's percentage : 0.0
 Total NaN values in row 16582 :- 0 and it's percentage : 0.0
 Total NaN values in row 16583 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16584 :- 0 and it's percentage : 0.0
 Total NaN values in row 16585 :- 0 and it's percentage : 0.0
 Total NaN values in row 16586 :- 0 and it's percentage : 0.0
 Total NaN values in row 16587 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16588 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16589 :- 0 and it's percentage : 0.0
 Total NaN values in row 16590 :- 0 and it's percentage : 0.0
 Total NaN values in row 16591 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 16592 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16593 :- 0 and it's percentage : 0.0
 Total NaN values in row 16594 :- 0 and it's percentage : 0.0
 Total NaN values in row 16595 :- 0 and it's percentage : 0.0
 Total NaN values in row 16596 :- 0 and it's percentage : 0.0
 Total NaN values in row 16597 :- 0 and it's percentage : 0.0
 Total NaN values in row 16598 :- 0 and it's percentage : 0.0
 Total NaN values in row 16599 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16600 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16601 :- 0 and it's percentage : 0.0
 Total NaN values in row 16602 :- 0 and it's percentage : 0.0
 Total NaN values in row 16603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16604 :- 0 and it's percentage : 0.0
 Total NaN values in row 16605 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16606 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16607 :- 0 and it's percentage : 0.0
 Total NaN values in row 16608 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16609 :- 0 and it's percentage : 0.0
 Total NaN values in row 16610 :- 0 and it's percentage : 0.0
 Total NaN values in row 16611 :- 0 and it's percentage : 0.0
 Total NaN values in row 16612 :- 0 and it's percentage : 0.0
 Total NaN values in row 16613 :- 0 and it's percentage : 0.0
 Total NaN values in row 16614 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16615 :- 0 and it's percentage : 0.0
 Total NaN values in row 16616 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16617 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16618 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16619 :- 0 and it's percentage : 0.0
 Total NaN values in row 16620 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16621 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16622 :- 0 and it's percentage : 0.0
 Total NaN values in row 16623 :- 0 and it's percentage : 0.0
 Total NaN values in row 16624 :- 0 and it's percentage : 0.0
 Total NaN values in row 16625 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16626 :- 0 and it's percentage : 0.0
 Total NaN values in row 16627 :- 0 and it's percentage : 0.0
 Total NaN values in row 16628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16629 :- 0 and it's percentage : 0.0
 Total NaN values in row 16630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16631 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16632 :- 0 and it's percentage : 0.0
 Total NaN values in row 16633 :- 0 and it's percentage : 0.0
 Total NaN values in row 16634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16635 :- 0 and it's percentage : 0.0
 Total NaN values in row 16636 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16638 :- 0 and it's percentage : 0.0
 Total NaN values in row 16639 :- 0 and it's percentage : 0.0
 Total NaN values in row 16640 :- 0 and it's percentage : 0.0
 Total NaN values in row 16641 :- 0 and it's percentage : 0.0
 Total NaN values in row 16642 :- 0 and it's percentage : 0.0
 Total NaN values in row 16643 :- 0 and it's percentage : 0.0
 Total NaN values in row 16644 :- 0 and it's percentage : 0.0
 Total NaN values in row 16645 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16646 :- 0 and it's percentage : 0.0
 Total NaN values in row 16647 :- 0 and it's percentage : 0.0
 Total NaN values in row 16648 :- 0 and it's percentage : 0.0
 Total NaN values in row 16649 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16650 :- 0 and it's percentage : 0.0
 Total NaN values in row 16651 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16652 :- 0 and it's percentage : 0.0
 Total NaN values in row 16653 :- 0 and it's percentage : 0.0
 Total NaN values in row 16654 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16655 :- 0 and it's percentage : 0.0
 Total NaN values in row 16656 :- 0 and it's percentage : 0.0
 Total NaN values in row 16657 :- 0 and it's percentage : 0.0
 Total NaN values in row 16658 :- 0 and it's percentage : 0.0
 Total NaN values in row 16659 :- 0 and it's percentage : 0.0
 Total NaN values in row 16660 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16661 :- 0 and it's percentage : 0.0
 Total NaN values in row 16662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16663 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16664 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16665 :- 0 and it's percentage : 0.0
 Total NaN values in row 16666 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 16667 :- 0 and it's percentage : 0.0
 Total NaN values in row 16668 :- 0 and it's percentage : 0.0
 Total NaN values in row 16669 :- 0 and it's percentage : 0.0
 Total NaN values in row 16670 :- 0 and it's percentage : 0.0
 Total NaN values in row 16671 :- 0 and it's percentage : 0.0
 Total NaN values in row 16672 :- 0 and it's percentage : 0.0
 Total NaN values in row 16673 :- 0 and it's percentage : 0.0
 Total NaN values in row 16674 :- 0 and it's percentage : 0.0
 Total NaN values in row 16675 :- 0 and it's percentage : 0.0
 Total NaN values in row 16676 :- 0 and it's percentage : 0.0
 Total NaN values in row 16677 :- 0 and it's percentage : 0.0
 Total NaN values in row 16678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16679 :- 0 and it's percentage : 0.0
 Total NaN values in row 16680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16681 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16682 :- 0 and it's percentage : 0.0
 Total NaN values in row 16683 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16684 :- 0 and it's percentage : 0.0
 Total NaN values in row 16685 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16686 :- 0 and it's percentage : 0.0
 Total NaN values in row 16687 :- 0 and it's percentage : 0.0
 Total NaN values in row 16688 :- 0 and it's percentage : 0.0
 Total NaN values in row 16689 :- 0 and it's percentage : 0.0
 Total NaN values in row 16690 :- 0 and it's percentage : 0.0
 Total NaN values in row 16691 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16692 :- 0 and it's percentage : 0.0
 Total NaN values in row 16693 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16694 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16696 :- 0 and it's percentage : 0.0
 Total NaN values in row 16697 :- 0 and it's percentage : 0.0
 Total NaN values in row 16698 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16699 :- 0 and it's percentage : 0.0
 Total NaN values in row 16700 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16701 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16702 :- 0 and it's percentage : 0.0
 Total NaN values in row 16703 :- 0 and it's percentage : 0.0
 Total NaN values in row 16704 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16705 :- 0 and it's percentage : 0.0
 Total NaN values in row 16706 :- 0 and it's percentage : 0.0
 Total NaN values in row 16707 :- 0 and it's percentage : 0.0
 Total NaN values in row 16708 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16709 :- 0 and it's percentage : 0.0
 Total NaN values in row 16710 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16711 :- 0 and it's percentage : 0.0
 Total NaN values in row 16712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16714 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16715 :- 0 and it's percentage : 0.0
 Total NaN values in row 16716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16717 :- 0 and it's percentage : 0.0
 Total NaN values in row 16718 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16719 :- 0 and it's percentage : 0.0
 Total NaN values in row 16720 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16722 :- 0 and it's percentage : 0.0
 Total NaN values in row 16723 :- 0 and it's percentage : 0.0
 Total NaN values in row 16724 :- 0 and it's percentage : 0.0
 Total NaN values in row 16725 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16726 :- 0 and it's percentage : 0.0
 Total NaN values in row 16727 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16728 :- 0 and it's percentage : 0.0
 Total NaN values in row 16729 :- 0 and it's percentage : 0.0
 Total NaN values in row 16730 :- 0 and it's percentage : 0.0
 Total NaN values in row 16731 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 16732 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16733 :- 0 and it's percentage : 0.0
 Total NaN values in row 16734 :- 0 and it's percentage : 0.0
 Total NaN values in row 16735 :- 0 and it's percentage : 0.0
 Total NaN values in row 16736 :- 0 and it's percentage : 0.0
 Total NaN values in row 16737 :- 0 and it's percentage : 0.0
 Total NaN values in row 16738 :- 0 and it's percentage : 0.0
 Total NaN values in row 16739 :- 0 and it's percentage : 0.0
 Total NaN values in row 16740 :- 0 and it's percentage : 0.0
 Total NaN values in row 16741 :- 0 and it's percentage : 0.0
 Total NaN values in row 16742 :- 0 and it's percentage : 0.0
 Total NaN values in row 16743 :- 0 and it's percentage : 0.0
 Total NaN values in row 16744 :- 0 and it's percentage : 0.0
 Total NaN values in row 16745 :- 0 and it's percentage : 0.0
 Total NaN values in row 16746 :- 0 and it's percentage : 0.0
 Total NaN values in row 16747 :- 0 and it's percentage : 0.0
 Total NaN values in row 16748 :- 0 and it's percentage : 0.0
 Total NaN values in row 16749 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16750 :- 0 and it's percentage : 0.0
 Total NaN values in row 16751 :- 0 and it's percentage : 0.0
 Total NaN values in row 16752 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16753 :- 0 and it's percentage : 0.0
 Total NaN values in row 16754 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16755 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16756 :- 0 and it's percentage : 0.0
 Total NaN values in row 16757 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16758 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16759 :- 0 and it's percentage : 0.0
 Total NaN values in row 16760 :- 0 and it's percentage : 0.0
 Total NaN values in row 16761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16762 :- 0 and it's percentage : 0.0
 Total NaN values in row 16763 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16764 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16765 :- 0 and it's percentage : 0.0
 Total NaN values in row 16766 :- 0 and it's percentage : 0.0
 Total NaN values in row 16767 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16768 :- 0 and it's percentage : 0.0
 Total NaN values in row 16769 :- 0 and it's percentage : 0.0
 Total NaN values in row 16770 :- 0 and it's percentage : 0.0
 Total NaN values in row 16771 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16772 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16774 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16775 :- 0 and it's percentage : 0.0
 Total NaN values in row 16776 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16777 :- 0 and it's percentage : 0.0
 Total NaN values in row 16778 :- 0 and it's percentage : 0.0
 Total NaN values in row 16779 :- 0 and it's percentage : 0.0
 Total NaN values in row 16780 :- 0 and it's percentage : 0.0
 Total NaN values in row 16781 :- 0 and it's percentage : 0.0
 Total NaN values in row 16782 :- 0 and it's percentage : 0.0
 Total NaN values in row 16783 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16784 :- 0 and it's percentage : 0.0
 Total NaN values in row 16785 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16786 :- 0 and it's percentage : 0.0
 Total NaN values in row 16787 :- 0 and it's percentage : 0.0
 Total NaN values in row 16788 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16789 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16790 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16791 :- 0 and it's percentage : 0.0
 Total NaN values in row 16792 :- 0 and it's percentage : 0.0
 Total NaN values in row 16793 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16794 :- 0 and it's percentage : 0.0
 Total NaN values in row 16795 :- 0 and it's percentage : 0.0
 Total NaN values in row 16796 :- 0 and it's percentage : 0.0
 Total NaN values in row 16797 :- 0 and it's percentage : 0.0
 Total NaN values in row 16798 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16799 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16800 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16801 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16802 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16803 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16804 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16805 :- 0 and it's percentage : 0.0
 Total NaN values in row 16806 :- 0 and it's percentage : 0.0
 Total NaN values in row 16807 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16808 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16809 :- 0 and it's percentage : 0.0
 Total NaN values in row 16810 :- 0 and it's percentage : 0.0
 Total NaN values in row 16811 :- 0 and it's percentage : 0.0
 Total NaN values in row 16812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16813 :- 0 and it's percentage : 0.0
 Total NaN values in row 16814 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16815 :- 0 and it's percentage : 0.0
 Total NaN values in row 16816 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16817 :- 0 and it's percentage : 0.0
 Total NaN values in row 16818 :- 0 and it's percentage : 0.0
 Total NaN values in row 16819 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16820 :- 0 and it's percentage : 0.0
 Total NaN values in row 16821 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16822 :- 0 and it's percentage : 0.0
 Total NaN values in row 16823 :- 0 and it's percentage : 0.0
 Total NaN values in row 16824 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16825 :- 0 and it's percentage : 0.0
 Total NaN values in row 16826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16827 :- 0 and it's percentage : 0.0
 Total NaN values in row 16828 :- 0 and it's percentage : 0.0
 Total NaN values in row 16829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16830 :- 0 and it's percentage : 0.0
 Total NaN values in row 16831 :- 0 and it's percentage : 0.0
 Total NaN values in row 16832 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16833 :- 0 and it's percentage : 0.0
 Total NaN values in row 16834 :- 0 and it's percentage : 0.0
 Total NaN values in row 16835 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16836 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16837 :- 0 and it's percentage : 0.0
 Total NaN values in row 16838 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16839 :- 0 and it's percentage : 0.0
 Total NaN values in row 16840 :- 0 and it's percentage : 0.0
 Total NaN values in row 16841 :- 0 and it's percentage : 0.0
 Total NaN values in row 16842 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16843 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16844 :- 0 and it's percentage : 0.0
 Total NaN values in row 16845 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16846 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16847 :- 0 and it's percentage : 0.0
 Total NaN values in row 16848 :- 0 and it's percentage : 0.0
 Total NaN values in row 16849 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16850 :- 0 and it's percentage : 0.0
 Total NaN values in row 16851 :- 0 and it's percentage : 0.0
 Total NaN values in row 16852 :- 0 and it's percentage : 0.0
 Total NaN values in row 16853 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16854 :- 0 and it's percentage : 0.0
 Total NaN values in row 16855 :- 0 and it's percentage : 0.0
 Total NaN values in row 16856 :- 0 and it's percentage : 0.0
 Total NaN values in row 16857 :- 0 and it's percentage : 0.0
 Total NaN values in row 16858 :- 0 and it's percentage : 0.0
 Total NaN values in row 16859 :- 0 and it's percentage : 0.0
 Total NaN values in row 16860 :- 0 and it's percentage : 0.0
 Total NaN values in row 16861 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16862 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 16863 :- 0 and it's percentage : 0.0
 Total NaN values in row 16864 :- 0 and it's percentage : 0.0
 Total NaN values in row 16865 :- 0 and it's percentage : 0.0
 Total NaN values in row 16866 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16867 :- 0 and it's percentage : 0.0
 Total NaN values in row 16868 :- 0 and it's percentage : 0.0
 Total NaN values in row 16869 :- 0 and it's percentage : 0.0
 Total NaN values in row 16870 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16872 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16873 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16875 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16876 :- 0 and it's percentage : 0.0
 Total NaN values in row 16877 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16878 :- 0 and it's percentage : 0.0
 Total NaN values in row 16879 :- 0 and it's percentage : 0.0
 Total NaN values in row 16880 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16881 :- 0 and it's percentage : 0.0
 Total NaN values in row 16882 :- 0 and it's percentage : 0.0
 Total NaN values in row 16883 :- 0 and it's percentage : 0.0
 Total NaN values in row 16884 :- 0 and it's percentage : 0.0
 Total NaN values in row 16885 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16886 :- 0 and it's percentage : 0.0
 Total NaN values in row 16887 :- 0 and it's percentage : 0.0
 Total NaN values in row 16888 :- 0 and it's percentage : 0.0
 Total NaN values in row 16889 :- 0 and it's percentage : 0.0
 Total NaN values in row 16890 :- 0 and it's percentage : 0.0
 Total NaN values in row 16891 :- 0 and it's percentage : 0.0
 Total NaN values in row 16892 :- 0 and it's percentage : 0.0
 Total NaN values in row 16893 :- 0 and it's percentage : 0.0
 Total NaN values in row 16894 :- 0 and it's percentage : 0.0
 Total NaN values in row 16895 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16896 :- 0 and it's percentage : 0.0
 Total NaN values in row 16897 :- 0 and it's percentage : 0.0
 Total NaN values in row 16898 :- 0 and it's percentage : 0.0
 Total NaN values in row 16899 :- 0 and it's percentage : 0.0
 Total NaN values in row 16900 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16901 :- 0 and it's percentage : 0.0
 Total NaN values in row 16902 :- 0 and it's percentage : 0.0
 Total NaN values in row 16903 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16904 :- 0 and it's percentage : 0.0
 Total NaN values in row 16905 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16906 :- 0 and it's percentage : 0.0
 Total NaN values in row 16907 :- 0 and it's percentage : 0.0
 Total NaN values in row 16908 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16909 :- 0 and it's percentage : 0.0
 Total NaN values in row 16910 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16911 :- 0 and it's percentage : 0.0
 Total NaN values in row 16912 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16913 :- 0 and it's percentage : 0.0
 Total NaN values in row 16914 :- 0 and it's percentage : 0.0
 Total NaN values in row 16915 :- 0 and it's percentage : 0.0
 Total NaN values in row 16916 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16917 :- 0 and it's percentage : 0.0
 Total NaN values in row 16918 :- 0 and it's percentage : 0.0
 Total NaN values in row 16919 :- 0 and it's percentage : 0.0
 Total NaN values in row 16920 :- 0 and it's percentage : 0.0
 Total NaN values in row 16921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16923 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16924 :- 0 and it's percentage : 0.0
 Total NaN values in row 16925 :- 0 and it's percentage : 0.0
 Total NaN values in row 16926 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16927 :- 0 and it's percentage : 0.0
 Total NaN values in row 16928 :- 0 and it's percentage : 0.0
 Total NaN values in row 16929 :- 0 and it's percentage : 0.0
 Total NaN values in row 16930 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16931 :- 0 and it's percentage : 0.0
 Total NaN values in row 16932 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16933 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16934 :- 0 and it's percentage : 0.0
 Total NaN values in row 16935 :- 0 and it's percentage : 0.0
 Total NaN values in row 16936 :- 0 and it's percentage : 0.0
 Total NaN values in row 16937 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16938 :- 0 and it's percentage : 0.0
 Total NaN values in row 16939 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16940 :- 0 and it's percentage : 0.0
 Total NaN values in row 16941 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16942 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16943 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16944 :- 0 and it's percentage : 0.0
 Total NaN values in row 16945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16946 :- 0 and it's percentage : 0.0
 Total NaN values in row 16947 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16948 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16949 :- 0 and it's percentage : 0.0
 Total NaN values in row 16950 :- 0 and it's percentage : 0.0
 Total NaN values in row 16951 :- 0 and it's percentage : 0.0
 Total NaN values in row 16952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16954 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 16955 :- 0 and it's percentage : 0.0
 Total NaN values in row 16956 :- 0 and it's percentage : 0.0
 Total NaN values in row 16957 :- 0 and it's percentage : 0.0
 Total NaN values in row 16958 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16959 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16960 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16961 :- 0 and it's percentage : 0.0
 Total NaN values in row 16962 :- 0 and it's percentage : 0.0
 Total NaN values in row 16963 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16964 :- 0 and it's percentage : 0.0
 Total NaN values in row 16965 :- 0 and it's percentage : 0.0
 Total NaN values in row 16966 :- 0 and it's percentage : 0.0
 Total NaN values in row 16967 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16968 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16969 :- 0 and it's percentage : 0.0
 Total NaN values in row 16970 :- 0 and it's percentage : 0.0
 Total NaN values in row 16971 :- 0 and it's percentage : 0.0
 Total NaN values in row 16972 :- 0 and it's percentage : 0.0
 Total NaN values in row 16973 :- 0 and it's percentage : 0.0
 Total NaN values in row 16974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16975 :- 0 and it's percentage : 0.0
 Total NaN values in row 16976 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16977 :- 0 and it's percentage : 0.0
 Total NaN values in row 16978 :- 0 and it's percentage : 0.0
 Total NaN values in row 16979 :- 0 and it's percentage : 0.0
 Total NaN values in row 16980 :- 0 and it's percentage : 0.0
 Total NaN values in row 16981 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16982 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16983 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16984 :- 0 and it's percentage : 0.0
 Total NaN values in row 16985 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16986 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16987 :- 0 and it's percentage : 0.0
 Total NaN values in row 16988 :- 0 and it's percentage : 0.0
 Total NaN values in row 16989 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16990 :- 0 and it's percentage : 0.0
 Total NaN values in row 16991 :- 0 and it's percentage : 0.0
 Total NaN values in row 16992 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 16993 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 16994 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16995 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 16996 :- 0 and it's percentage : 0.0
 Total NaN values in row 16997 :- 0 and it's percentage : 0.0
 Total NaN values in row 16998 :- 0 and it's percentage : 0.0
 Total NaN values in row 16999 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17000 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17001 :- 0 and it's percentage : 0.0
 Total NaN values in row 17002 :- 0 and it's percentage : 0.0
 Total NaN values in row 17003 :- 0 and it's percentage : 0.0
 Total NaN values in row 17004 :- 0 and it's percentage : 0.0
 Total NaN values in row 17005 :- 0 and it's percentage : 0.0
 Total NaN values in row 17006 :- 0 and it's percentage : 0.0
 Total NaN values in row 17007 :- 0 and it's percentage : 0.0
 Total NaN values in row 17008 :- 0 and it's percentage : 0.0
 Total NaN values in row 17009 :- 0 and it's percentage : 0.0
 Total NaN values in row 17010 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17011 :- 0 and it's percentage : 0.0
 Total NaN values in row 17012 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 17013 :- 0 and it's percentage : 0.0
 Total NaN values in row 17014 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17015 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17016 :- 0 and it's percentage : 0.0
 Total NaN values in row 17017 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 17018 :- 0 and it's percentage : 0.0
 Total NaN values in row 17019 :- 0 and it's percentage : 0.0
 Total NaN values in row 17020 :- 0 and it's percentage : 0.0
 Total NaN values in row 17021 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17022 :- 0 and it's percentage : 0.0
 Total NaN values in row 17023 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17024 :- 0 and it's percentage : 0.0
 Total NaN values in row 17025 :- 0 and it's percentage : 0.0
 Total NaN values in row 17026 :- 0 and it's percentage : 0.0
 Total NaN values in row 17027 :- 0 and it's percentage : 0.0
 Total NaN values in row 17028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17029 :- 0 and it's percentage : 0.0
 Total NaN values in row 17030 :- 0 and it's percentage : 0.0
 Total NaN values in row 17031 :- 0 and it's percentage : 0.0
 Total NaN values in row 17032 :- 0 and it's percentage : 0.0
 Total NaN values in row 17033 :- 0 and it's percentage : 0.0
 Total NaN values in row 17034 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17035 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17036 :- 0 and it's percentage : 0.0
 Total NaN values in row 17037 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17038 :- 0 and it's percentage : 0.0
 Total NaN values in row 17039 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17040 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17041 :- 0 and it's percentage : 0.0
 Total NaN values in row 17042 :- 0 and it's percentage : 0.0
 Total NaN values in row 17043 :- 0 and it's percentage : 0.0
 Total NaN values in row 17044 :- 0 and it's percentage : 0.0
 Total NaN values in row 17045 :- 0 and it's percentage : 0.0
 Total NaN values in row 17046 :- 0 and it's percentage : 0.0
 Total NaN values in row 17047 :- 0 and it's percentage : 0.0
 Total NaN values in row 17048 :- 0 and it's percentage : 0.0
 Total NaN values in row 17049 :- 0 and it's percentage : 0.0
 Total NaN values in row 17050 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17051 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17052 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17053 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17054 :- 0 and it's percentage : 0.0
 Total NaN values in row 17055 :- 0 and it's percentage : 0.0
 Total NaN values in row 17056 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17057 :- 0 and it's percentage : 0.0
 Total NaN values in row 17058 :- 0 and it's percentage : 0.0
 Total NaN values in row 17059 :- 0 and it's percentage : 0.0
 Total NaN values in row 17060 :- 0 and it's percentage : 0.0
 Total NaN values in row 17061 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17062 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17063 :- 0 and it's percentage : 0.0
 Total NaN values in row 17064 :- 0 and it's percentage : 0.0
 Total NaN values in row 17065 :- 0 and it's percentage : 0.0
 Total NaN values in row 17066 :- 0 and it's percentage : 0.0
 Total NaN values in row 17067 :- 0 and it's percentage : 0.0
 Total NaN values in row 17068 :- 0 and it's percentage : 0.0
 Total NaN values in row 17069 :- 0 and it's percentage : 0.0
 Total NaN values in row 17070 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17071 :- 0 and it's percentage : 0.0
 Total NaN values in row 17072 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17073 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17074 :- 0 and it's percentage : 0.0
 Total NaN values in row 17075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17077 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17078 :- 0 and it's percentage : 0.0
 Total NaN values in row 17079 :- 0 and it's percentage : 0.0
 Total NaN values in row 17080 :- 0 and it's percentage : 0.0
 Total NaN values in row 17081 :- 0 and it's percentage : 0.0
 Total NaN values in row 17082 :- 0 and it's percentage : 0.0
 Total NaN values in row 17083 :- 0 and it's percentage : 0.0
 Total NaN values in row 17084 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17085 :- 0 and it's percentage : 0.0
 Total NaN values in row 17086 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17087 :- 0 and it's percentage : 0.0
 Total NaN values in row 17088 :- 0 and it's percentage : 0.0
 Total NaN values in row 17089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17090 :- 0 and it's percentage : 0.0
 Total NaN values in row 17091 :- 0 and it's percentage : 0.0
 Total NaN values in row 17092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17093 :- 0 and it's percentage : 0.0
 Total NaN values in row 17094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17095 :- 0 and it's percentage : 0.0
 Total NaN values in row 17096 :- 0 and it's percentage : 0.0
 Total NaN values in row 17097 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17098 :- 0 and it's percentage : 0.0
 Total NaN values in row 17099 :- 0 and it's percentage : 0.0
 Total NaN values in row 17100 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17101 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17102 :- 0 and it's percentage : 0.0
 Total NaN values in row 17103 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17104 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17105 :- 0 and it's percentage : 0.0
 Total NaN values in row 17106 :- 0 and it's percentage : 0.0
 Total NaN values in row 17107 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17108 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17109 :- 0 and it's percentage : 0.0
 Total NaN values in row 17110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17111 :- 0 and it's percentage : 0.0
 Total NaN values in row 17112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17113 :- 0 and it's percentage : 0.0
 Total NaN values in row 17114 :- 0 and it's percentage : 0.0
 Total NaN values in row 17115 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17116 :- 0 and it's percentage : 0.0
 Total NaN values in row 17117 :- 0 and it's percentage : 0.0
 Total NaN values in row 17118 :- 0 and it's percentage : 0.0
 Total NaN values in row 17119 :- 0 and it's percentage : 0.0
 Total NaN values in row 17120 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17121 :- 0 and it's percentage : 0.0
 Total NaN values in row 17122 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17123 :- 0 and it's percentage : 0.0
 Total NaN values in row 17124 :- 0 and it's percentage : 0.0
 Total NaN values in row 17125 :- 0 and it's percentage : 0.0
 Total NaN values in row 17126 :- 0 and it's percentage : 0.0
 Total NaN values in row 17127 :- 0 and it's percentage : 0.0
 Total NaN values in row 17128 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17129 :- 0 and it's percentage : 0.0
 Total NaN values in row 17130 :- 0 and it's percentage : 0.0
 Total NaN values in row 17131 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17132 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17133 :- 0 and it's percentage : 0.0
 Total NaN values in row 17134 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17135 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17136 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17137 :- 0 and it's percentage : 0.0
 Total NaN values in row 17138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17139 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17140 :- 0 and it's percentage : 0.0
 Total NaN values in row 17141 :- 0 and it's percentage : 0.0
 Total NaN values in row 17142 :- 0 and it's percentage : 0.0
 Total NaN values in row 17143 :- 0 and it's percentage : 0.0
 Total NaN values in row 17144 :- 0 and it's percentage : 0.0
 Total NaN values in row 17145 :- 0 and it's percentage : 0.0
 Total NaN values in row 17146 :- 0 and it's percentage : 0.0
 Total NaN values in row 17147 :- 0 and it's percentage : 0.0
 Total NaN values in row 17148 :- 0 and it's percentage : 0.0
 Total NaN values in row 17149 :- 0 and it's percentage : 0.0
 Total NaN values in row 17150 :- 0 and it's percentage : 0.0
 Total NaN values in row 17151 :- 0 and it's percentage : 0.0
 Total NaN values in row 17152 :- 0 and it's percentage : 0.0
 Total NaN values in row 17153 :- 0 and it's percentage : 0.0
 Total NaN values in row 17154 :- 0 and it's percentage : 0.0
 Total NaN values in row 17155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17156 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17157 :- 0 and it's percentage : 0.0
 Total NaN values in row 17158 :- 0 and it's percentage : 0.0
 Total NaN values in row 17159 :- 0 and it's percentage : 0.0
 Total NaN values in row 17160 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17161 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17162 :- 0 and it's percentage : 0.0
 Total NaN values in row 17163 :- 0 and it's percentage : 0.0
 Total NaN values in row 17164 :- 0 and it's percentage : 0.0
 Total NaN values in row 17165 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17166 :- 0 and it's percentage : 0.0
 Total NaN values in row 17167 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17168 :- 0 and it's percentage : 0.0

 Total NaN values in row 17169 :- 0 and it's percentage : 0.0
 Total NaN values in row 17170 :- 0 and it's percentage : 0.0
 Total NaN values in row 17171 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17172 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17173 :- 0 and it's percentage : 0.0
 Total NaN values in row 17174 :- 0 and it's percentage : 0.0
 Total NaN values in row 17175 :- 0 and it's percentage : 0.0
 Total NaN values in row 17176 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17177 :- 0 and it's percentage : 0.0
 Total NaN values in row 17178 :- 0 and it's percentage : 0.0
 Total NaN values in row 17179 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17180 :- 0 and it's percentage : 0.0
 Total NaN values in row 17181 :- 0 and it's percentage : 0.0
 Total NaN values in row 17182 :- 0 and it's percentage : 0.0
 Total NaN values in row 17183 :- 0 and it's percentage : 0.0
 Total NaN values in row 17184 :- 0 and it's percentage : 0.0
 Total NaN values in row 17185 :- 0 and it's percentage : 0.0
 Total NaN values in row 17186 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17187 :- 0 and it's percentage : 0.0
 Total NaN values in row 17188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17189 :- 0 and it's percentage : 0.0
 Total NaN values in row 17190 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17191 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17192 :- 0 and it's percentage : 0.0
 Total NaN values in row 17193 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17194 :- 0 and it's percentage : 0.0
 Total NaN values in row 17195 :- 0 and it's percentage : 0.0
 Total NaN values in row 17196 :- 0 and it's percentage : 0.0
 Total NaN values in row 17197 :- 0 and it's percentage : 0.0
 Total NaN values in row 17198 :- 0 and it's percentage : 0.0
 Total NaN values in row 17199 :- 0 and it's percentage : 0.0
 Total NaN values in row 17200 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17201 :- 0 and it's percentage : 0.0
 Total NaN values in row 17202 :- 0 and it's percentage : 0.0
 Total NaN values in row 17203 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17205 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17206 :- 0 and it's percentage : 0.0
 Total NaN values in row 17207 :- 0 and it's percentage : 0.0
 Total NaN values in row 17208 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17209 :- 0 and it's percentage : 0.0
 Total NaN values in row 17210 :- 0 and it's percentage : 0.0
 Total NaN values in row 17211 :- 0 and it's percentage : 0.0
 Total NaN values in row 17212 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17213 :- 0 and it's percentage : 0.0
 Total NaN values in row 17214 :- 0 and it's percentage : 0.0
 Total NaN values in row 17215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17216 :- 0 and it's percentage : 0.0
 Total NaN values in row 17217 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17218 :- 0 and it's percentage : 0.0
 Total NaN values in row 17219 :- 0 and it's percentage : 0.0
 Total NaN values in row 17220 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17221 :- 0 and it's percentage : 0.0
 Total NaN values in row 17222 :- 0 and it's percentage : 0.0
 Total NaN values in row 17223 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17224 :- 0 and it's percentage : 0.0
 Total NaN values in row 17225 :- 0 and it's percentage : 0.0
 Total NaN values in row 17226 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17227 :- 0 and it's percentage : 0.0
 Total NaN values in row 17228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17230 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17231 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17233 :- 0 and it's percentage : 0.0
 Total NaN values in row 17234 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17235 :- 0 and it's percentage : 0.0
 Total NaN values in row 17236 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17237 :- 0 and it's percentage : 0.0
 Total NaN values in row 17238 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17239 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17240 :- 0 and it's percentage : 0.0
 Total NaN values in row 17241 :- 0 and it's percentage : 0.0
 Total NaN values in row 17242 :- 0 and it's percentage : 0.0
 Total NaN values in row 17243 :- 0 and it's percentage : 0.0
 Total NaN values in row 17244 :- 0 and it's percentage : 0.0
 Total NaN values in row 17245 :- 0 and it's percentage : 0.0
 Total NaN values in row 17246 :- 0 and it's percentage : 0.0
 Total NaN values in row 17247 :- 0 and it's percentage : 0.0
 Total NaN values in row 17248 :- 0 and it's percentage : 0.0
 Total NaN values in row 17249 :- 0 and it's percentage : 0.0
 Total NaN values in row 17250 :- 0 and it's percentage : 0.0
 Total NaN values in row 17251 :- 0 and it's percentage : 0.0
 Total NaN values in row 17252 :- 0 and it's percentage : 0.0
 Total NaN values in row 17253 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17254 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17255 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17256 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17257 :- 0 and it's percentage : 0.0
 Total NaN values in row 17258 :- 0 and it's percentage : 0.0
 Total NaN values in row 17259 :- 0 and it's percentage : 0.0
 Total NaN values in row 17260 :- 0 and it's percentage : 0.0
 Total NaN values in row 17261 :- 0 and it's percentage : 0.0
 Total NaN values in row 17262 :- 0 and it's percentage : 0.0
 Total NaN values in row 17263 :- 0 and it's percentage : 0.0
 Total NaN values in row 17264 :- 0 and it's percentage : 0.0
 Total NaN values in row 17265 :- 0 and it's percentage : 0.0
 Total NaN values in row 17266 :- 0 and it's percentage : 0.0
 Total NaN values in row 17267 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17269 :- 0 and it's percentage : 0.0
 Total NaN values in row 17270 :- 0 and it's percentage : 0.0
 Total NaN values in row 17271 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17272 :- 0 and it's percentage : 0.0
 Total NaN values in row 17273 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17274 :- 0 and it's percentage : 0.0
 Total NaN values in row 17275 :- 0 and it's percentage : 0.0
 Total NaN values in row 17276 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17277 :- 0 and it's percentage : 0.0
 Total NaN values in row 17278 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17279 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17280 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17282 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17283 :- 0 and it's percentage : 0.0
 Total NaN values in row 17284 :- 0 and it's percentage : 0.0
 Total NaN values in row 17285 :- 0 and it's percentage : 0.0
 Total NaN values in row 17286 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17287 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17288 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17289 :- 0 and it's percentage : 0.0

 Total NaN values in row 17290 :- 0 and it's percentage : 0.0
 Total NaN values in row 17291 :- 0 and it's percentage : 0.0
 Total NaN values in row 17292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17293 :- 0 and it's percentage : 0.0
 Total NaN values in row 17294 :- 0 and it's percentage : 0.0
 Total NaN values in row 17295 :- 0 and it's percentage : 0.0
 Total NaN values in row 17296 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17297 :- 0 and it's percentage : 0.0
 Total NaN values in row 17298 :- 0 and it's percentage : 0.0
 Total NaN values in row 17299 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17300 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17301 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17302 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17303 :- 0 and it's percentage : 0.0
 Total NaN values in row 17304 :- 0 and it's percentage : 0.0
 Total NaN values in row 17305 :- 0 and it's percentage : 0.0
 Total NaN values in row 17306 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17308 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 17309 :- 0 and it's percentage : 0.0
 Total NaN values in row 17310 :- 0 and it's percentage : 0.0
 Total NaN values in row 17311 :- 0 and it's percentage : 0.0
 Total NaN values in row 17312 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17313 :- 0 and it's percentage : 0.0
 Total NaN values in row 17314 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17315 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17316 :- 0 and it's percentage : 0.0
 Total NaN values in row 17317 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17318 :- 0 and it's percentage : 0.0
 Total NaN values in row 17319 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17320 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17321 :- 0 and it's percentage : 0.0
 Total NaN values in row 17322 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17323 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17324 :- 0 and it's percentage : 0.0
 Total NaN values in row 17325 :- 0 and it's percentage : 0.0
 Total NaN values in row 17326 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 17327 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17328 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17329 :- 0 and it's percentage : 0.0
 Total NaN values in row 17330 :- 0 and it's percentage : 0.0
 Total NaN values in row 17331 :- 0 and it's percentage : 0.0
 Total NaN values in row 17332 :- 0 and it's percentage : 0.0
 Total NaN values in row 17333 :- 0 and it's percentage : 0.0
 Total NaN values in row 17334 :- 0 and it's percentage : 0.0
 Total NaN values in row 17335 :- 0 and it's percentage : 0.0
 Total NaN values in row 17336 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17337 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17339 :- 0 and it's percentage : 0.0
 Total NaN values in row 17340 :- 0 and it's percentage : 0.0
 Total NaN values in row 17341 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17343 :- 0 and it's percentage : 0.0
 Total NaN values in row 17344 :- 0 and it's percentage : 0.0
 Total NaN values in row 17345 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17346 :- 0 and it's percentage : 0.0
 Total NaN values in row 17347 :- 0 and it's percentage : 0.0
 Total NaN values in row 17348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17349 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17350 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17351 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17352 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17353 :- 0 and it's percentage : 0.0
 Total NaN values in row 17354 :- 0 and it's percentage : 0.0
 Total NaN values in row 17355 :- 0 and it's percentage : 0.0
 Total NaN values in row 17356 :- 0 and it's percentage : 0.0
 Total NaN values in row 17357 :- 0 and it's percentage : 0.0
 Total NaN values in row 17358 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17359 :- 0 and it's percentage : 0.0
 Total NaN values in row 17360 :- 0 and it's percentage : 0.0
 Total NaN values in row 17361 :- 0 and it's percentage : 0.0
 Total NaN values in row 17362 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17363 :- 0 and it's percentage : 0.0
 Total NaN values in row 17364 :- 0 and it's percentage : 0.0
 Total NaN values in row 17365 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17367 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17368 :- 0 and it's percentage : 0.0
 Total NaN values in row 17369 :- 0 and it's percentage : 0.0
 Total NaN values in row 17370 :- 0 and it's percentage : 0.0
 Total NaN values in row 17371 :- 0 and it's percentage : 0.0
 Total NaN values in row 17372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17373 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17375 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17376 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17377 :- 0 and it's percentage : 0.0
 Total NaN values in row 17378 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17379 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17380 :- 0 and it's percentage : 0.0
 Total NaN values in row 17381 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17382 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17383 :- 0 and it's percentage : 0.0
 Total NaN values in row 17384 :- 0 and it's percentage : 0.0
 Total NaN values in row 17385 :- 0 and it's percentage : 0.0
 Total NaN values in row 17386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17387 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17388 :- 0 and it's percentage : 0.0
 Total NaN values in row 17389 :- 0 and it's percentage : 0.0
 Total NaN values in row 17390 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17391 :- 0 and it's percentage : 0.0
 Total NaN values in row 17392 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17393 :- 0 and it's percentage : 0.0
 Total NaN values in row 17394 :- 0 and it's percentage : 0.0
 Total NaN values in row 17395 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17397 :- 0 and it's percentage : 0.0
 Total NaN values in row 17398 :- 0 and it's percentage : 0.0
 Total NaN values in row 17399 :- 0 and it's percentage : 0.0
 Total NaN values in row 17400 :- 0 and it's percentage : 0.0
 Total NaN values in row 17401 :- 0 and it's percentage : 0.0
 Total NaN values in row 17402 :- 0 and it's percentage : 0.0
 Total NaN values in row 17403 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17404 :- 0 and it's percentage : 0.0
 Total NaN values in row 17405 :- 0 and it's percentage : 0.0
 Total NaN values in row 17406 :- 0 and it's percentage : 0.0
 Total NaN values in row 17407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17408 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17409 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17410 :- 0 and it's percentage : 0.0
 Total NaN values in row 17411 :- 0 and it's percentage : 0.0
 Total NaN values in row 17412 :- 0 and it's percentage : 0.0
 Total NaN values in row 17413 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17414 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17415 :- 0 and it's percentage : 0.0
 Total NaN values in row 17416 :- 0 and it's percentage : 0.0
 Total NaN values in row 17417 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17418 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17419 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17420 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 17421 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17422 :- 0 and it's percentage : 0.0
 Total NaN values in row 17423 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17424 :- 0 and it's percentage : 0.0
 Total NaN values in row 17425 :- 0 and it's percentage : 0.0

 Total NaN values in row 17426 :- 0 and it's percentage : 0.0
 Total NaN values in row 17427 :- 0 and it's percentage : 0.0
 Total NaN values in row 17428 :- 0 and it's percentage : 0.0
 Total NaN values in row 17429 :- 0 and it's percentage : 0.0
 Total NaN values in row 17430 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17431 :- 0 and it's percentage : 0.0
 Total NaN values in row 17432 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17433 :- 0 and it's percentage : 0.0
 Total NaN values in row 17434 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17435 :- 0 and it's percentage : 0.0
 Total NaN values in row 17436 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17437 :- 0 and it's percentage : 0.0
 Total NaN values in row 17438 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17439 :- 0 and it's percentage : 0.0
 Total NaN values in row 17440 :- 0 and it's percentage : 0.0
 Total NaN values in row 17441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17442 :- 0 and it's percentage : 0.0
 Total NaN values in row 17443 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17444 :- 0 and it's percentage : 0.0
 Total NaN values in row 17445 :- 0 and it's percentage : 0.0
 Total NaN values in row 17446 :- 0 and it's percentage : 0.0
 Total NaN values in row 17447 :- 0 and it's percentage : 0.0
 Total NaN values in row 17448 :- 0 and it's percentage : 0.0
 Total NaN values in row 17449 :- 0 and it's percentage : 0.0
 Total NaN values in row 17450 :- 0 and it's percentage : 0.0
 Total NaN values in row 17451 :- 0 and it's percentage : 0.0
 Total NaN values in row 17452 :- 0 and it's percentage : 0.0
 Total NaN values in row 17453 :- 0 and it's percentage : 0.0
 Total NaN values in row 17454 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17455 :- 0 and it's percentage : 0.0
 Total NaN values in row 17456 :- 0 and it's percentage : 0.0
 Total NaN values in row 17457 :- 0 and it's percentage : 0.0
 Total NaN values in row 17458 :- 0 and it's percentage : 0.0
 Total NaN values in row 17459 :- 0 and it's percentage : 0.0
 Total NaN values in row 17460 :- 0 and it's percentage : 0.0
 Total NaN values in row 17461 :- 0 and it's percentage : 0.0
 Total NaN values in row 17462 :- 0 and it's percentage : 0.0
 Total NaN values in row 17463 :- 0 and it's percentage : 0.0
 Total NaN values in row 17464 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17465 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17466 :- 0 and it's percentage : 0.0
 Total NaN values in row 17467 :- 0 and it's percentage : 0.0
 Total NaN values in row 17468 :- 0 and it's percentage : 0.0
 Total NaN values in row 17469 :- 0 and it's percentage : 0.0
 Total NaN values in row 17470 :- 0 and it's percentage : 0.0
 Total NaN values in row 17471 :- 0 and it's percentage : 0.0
 Total NaN values in row 17472 :- 0 and it's percentage : 0.0
 Total NaN values in row 17473 :- 0 and it's percentage : 0.0
 Total NaN values in row 17474 :- 0 and it's percentage : 0.0
 Total NaN values in row 17475 :- 0 and it's percentage : 0.0
 Total NaN values in row 17476 :- 0 and it's percentage : 0.0
 Total NaN values in row 17477 :- 0 and it's percentage : 0.0
 Total NaN values in row 17478 :- 0 and it's percentage : 0.0
 Total NaN values in row 17479 :- 0 and it's percentage : 0.0
 Total NaN values in row 17480 :- 0 and it's percentage : 0.0
 Total NaN values in row 17481 :- 0 and it's percentage : 0.0
 Total NaN values in row 17482 :- 0 and it's percentage : 0.0
 Total NaN values in row 17483 :- 0 and it's percentage : 0.0
 Total NaN values in row 17484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17485 :- 0 and it's percentage : 0.0
 Total NaN values in row 17486 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17487 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17489 :- 0 and it's percentage : 0.0
 Total NaN values in row 17490 :- 0 and it's percentage : 0.0
 Total NaN values in row 17491 :- 0 and it's percentage : 0.0
 Total NaN values in row 17492 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17493 :- 0 and it's percentage : 0.0
 Total NaN values in row 17494 :- 0 and it's percentage : 0.0
 Total NaN values in row 17495 :- 0 and it's percentage : 0.0
 Total NaN values in row 17496 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17497 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 17498 :- 0 and it's percentage : 0.0
 Total NaN values in row 17499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17500 :- 0 and it's percentage : 0.0
 Total NaN values in row 17501 :- 0 and it's percentage : 0.0
 Total NaN values in row 17502 :- 0 and it's percentage : 0.0
 Total NaN values in row 17503 :- 0 and it's percentage : 0.0
 Total NaN values in row 17504 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17505 :- 0 and it's percentage : 0.0
 Total NaN values in row 17506 :- 0 and it's percentage : 0.0
 Total NaN values in row 17507 :- 0 and it's percentage : 0.0
 Total NaN values in row 17508 :- 0 and it's percentage : 0.0
 Total NaN values in row 17509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17511 :- 0 and it's percentage : 0.0
 Total NaN values in row 17512 :- 0 and it's percentage : 0.0
 Total NaN values in row 17513 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17514 :- 0 and it's percentage : 0.0
 Total NaN values in row 17515 :- 0 and it's percentage : 0.0
 Total NaN values in row 17516 :- 0 and it's percentage : 0.0
 Total NaN values in row 17517 :- 0 and it's percentage : 0.0
 Total NaN values in row 17518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17519 :- 0 and it's percentage : 0.0
 Total NaN values in row 17520 :- 0 and it's percentage : 0.0
 Total NaN values in row 17521 :- 0 and it's percentage : 0.0
 Total NaN values in row 17522 :- 0 and it's percentage : 0.0
 Total NaN values in row 17523 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17524 :- 0 and it's percentage : 0.0
 Total NaN values in row 17525 :- 0 and it's percentage : 0.0
 Total NaN values in row 17526 :- 0 and it's percentage : 0.0
 Total NaN values in row 17527 :- 0 and it's percentage : 0.0
 Total NaN values in row 17528 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17529 :- 0 and it's percentage : 0.0
 Total NaN values in row 17530 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17531 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17532 :- 0 and it's percentage : 0.0
 Total NaN values in row 17533 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17534 :- 0 and it's percentage : 0.0
 Total NaN values in row 17535 :- 0 and it's percentage : 0.0
 Total NaN values in row 17536 :- 0 and it's percentage : 0.0
 Total NaN values in row 17537 :- 0 and it's percentage : 0.0
 Total NaN values in row 17538 :- 0 and it's percentage : 0.0
 Total NaN values in row 17539 :- 0 and it's percentage : 0.0
 Total NaN values in row 17540 :- 0 and it's percentage : 0.0
 Total NaN values in row 17541 :- 0 and it's percentage : 0.0
 Total NaN values in row 17542 :- 0 and it's percentage : 0.0
 Total NaN values in row 17543 :- 0 and it's percentage : 0.0
 Total NaN values in row 17544 :- 0 and it's percentage : 0.0
 Total NaN values in row 17545 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17546 :- 0 and it's percentage : 0.0
 Total NaN values in row 17547 :- 0 and it's percentage : 0.0
 Total NaN values in row 17548 :- 0 and it's percentage : 0.0
 Total NaN values in row 17549 :- 0 and it's percentage : 0.0
 Total NaN values in row 17550 :- 0 and it's percentage : 0.0
 Total NaN values in row 17551 :- 0 and it's percentage : 0.0
 Total NaN values in row 17552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17553 :- 0 and it's percentage : 0.0
 Total NaN values in row 17554 :- 0 and it's percentage : 0.0
 Total NaN values in row 17555 :- 0 and it's percentage : 0.0
 Total NaN values in row 17556 :- 0 and it's percentage : 0.0
 Total NaN values in row 17557 :- 0 and it's percentage : 0.0
 Total NaN values in row 17558 :- 0 and it's percentage : 0.0

 Total NaN values in row 17559 :- 0 and it's percentage : 0.0
 Total NaN values in row 17560 :- 0 and it's percentage : 0.0
 Total NaN values in row 17561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17563 :- 0 and it's percentage : 0.0
 Total NaN values in row 17564 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17565 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17566 :- 0 and it's percentage : 0.0
 Total NaN values in row 17567 :- 0 and it's percentage : 0.0
 Total NaN values in row 17568 :- 0 and it's percentage : 0.0
 Total NaN values in row 17569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17570 :- 0 and it's percentage : 0.0
 Total NaN values in row 17571 :- 0 and it's percentage : 0.0
 Total NaN values in row 17572 :- 0 and it's percentage : 0.0
 Total NaN values in row 17573 :- 0 and it's percentage : 0.0
 Total NaN values in row 17574 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17575 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17576 :- 0 and it's percentage : 0.0
 Total NaN values in row 17577 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17578 :- 0 and it's percentage : 0.0
 Total NaN values in row 17579 :- 0 and it's percentage : 0.0
 Total NaN values in row 17580 :- 0 and it's percentage : 0.0
 Total NaN values in row 17581 :- 0 and it's percentage : 0.0
 Total NaN values in row 17582 :- 0 and it's percentage : 0.0
 Total NaN values in row 17583 :- 0 and it's percentage : 0.0
 Total NaN values in row 17584 :- 0 and it's percentage : 0.0
 Total NaN values in row 17585 :- 0 and it's percentage : 0.0
 Total NaN values in row 17586 :- 0 and it's percentage : 0.0
 Total NaN values in row 17587 :- 0 and it's percentage : 0.0
 Total NaN values in row 17588 :- 0 and it's percentage : 0.0
 Total NaN values in row 17589 :- 0 and it's percentage : 0.0
 Total NaN values in row 17590 :- 0 and it's percentage : 0.0
 Total NaN values in row 17591 :- 0 and it's percentage : 0.0
 Total NaN values in row 17592 :- 0 and it's percentage : 0.0
 Total NaN values in row 17593 :- 0 and it's percentage : 0.0
 Total NaN values in row 17594 :- 0 and it's percentage : 0.0
 Total NaN values in row 17595 :- 0 and it's percentage : 0.0
 Total NaN values in row 17596 :- 0 and it's percentage : 0.0
 Total NaN values in row 17597 :- 0 and it's percentage : 0.0
 Total NaN values in row 17598 :- 0 and it's percentage : 0.0
 Total NaN values in row 17599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17600 :- 0 and it's percentage : 0.0
 Total NaN values in row 17601 :- 0 and it's percentage : 0.0
 Total NaN values in row 17602 :- 0 and it's percentage : 0.0
 Total NaN values in row 17603 :- 0 and it's percentage : 0.0
 Total NaN values in row 17604 :- 0 and it's percentage : 0.0
 Total NaN values in row 17605 :- 0 and it's percentage : 0.0
 Total NaN values in row 17606 :- 0 and it's percentage : 0.0
 Total NaN values in row 17607 :- 0 and it's percentage : 0.0
 Total NaN values in row 17608 :- 0 and it's percentage : 0.0
 Total NaN values in row 17609 :- 0 and it's percentage : 0.0
 Total NaN values in row 17610 :- 0 and it's percentage : 0.0
 Total NaN values in row 17611 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17612 :- 0 and it's percentage : 0.0
 Total NaN values in row 17613 :- 0 and it's percentage : 0.0
 Total NaN values in row 17614 :- 0 and it's percentage : 0.0
 Total NaN values in row 17615 :- 0 and it's percentage : 0.0
 Total NaN values in row 17616 :- 0 and it's percentage : 0.0
 Total NaN values in row 17617 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 17618 :- 0 and it's percentage : 0.0
 Total NaN values in row 17619 :- 0 and it's percentage : 0.0
 Total NaN values in row 17620 :- 0 and it's percentage : 0.0
 Total NaN values in row 17621 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 17622 :- 0 and it's percentage : 0.0
 Total NaN values in row 17623 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17624 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17625 :- 0 and it's percentage : 0.0
 Total NaN values in row 17626 :- 0 and it's percentage : 0.0
 Total NaN values in row 17627 :- 0 and it's percentage : 0.0
 Total NaN values in row 17628 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17629 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17630 :- 0 and it's percentage : 0.0
 Total NaN values in row 17631 :- 0 and it's percentage : 0.0
 Total NaN values in row 17632 :- 0 and it's percentage : 0.0
 Total NaN values in row 17633 :- 0 and it's percentage : 0.0
 Total NaN values in row 17634 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17635 :- 0 and it's percentage : 0.0
 Total NaN values in row 17636 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17637 :- 0 and it's percentage : 0.0
 Total NaN values in row 17638 :- 0 and it's percentage : 0.0
 Total NaN values in row 17639 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17640 :- 0 and it's percentage : 0.0
 Total NaN values in row 17641 :- 0 and it's percentage : 0.0
 Total NaN values in row 17642 :- 0 and it's percentage : 0.0
 Total NaN values in row 17643 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17644 :- 0 and it's percentage : 0.0
 Total NaN values in row 17645 :- 0 and it's percentage : 0.0
 Total NaN values in row 17646 :- 0 and it's percentage : 0.0
 Total NaN values in row 17647 :- 0 and it's percentage : 0.0
 Total NaN values in row 17648 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17649 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17650 :- 0 and it's percentage : 0.0
 Total NaN values in row 17651 :- 0 and it's percentage : 0.0
 Total NaN values in row 17652 :- 0 and it's percentage : 0.0
 Total NaN values in row 17653 :- 0 and it's percentage : 0.0
 Total NaN values in row 17654 :- 0 and it's percentage : 0.0
 Total NaN values in row 17655 :- 0 and it's percentage : 0.0
 Total NaN values in row 17656 :- 0 and it's percentage : 0.0
 Total NaN values in row 17657 :- 0 and it's percentage : 0.0
 Total NaN values in row 17658 :- 0 and it's percentage : 0.0
 Total NaN values in row 17659 :- 0 and it's percentage : 0.0
 Total NaN values in row 17660 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17661 :- 0 and it's percentage : 0.0
 Total NaN values in row 17662 :- 0 and it's percentage : 0.0
 Total NaN values in row 17663 :- 0 and it's percentage : 0.0
 Total NaN values in row 17664 :- 0 and it's percentage : 0.0
 Total NaN values in row 17665 :- 0 and it's percentage : 0.0
 Total NaN values in row 17666 :- 0 and it's percentage : 0.0
 Total NaN values in row 17667 :- 0 and it's percentage : 0.0
 Total NaN values in row 17668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17669 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17670 :- 0 and it's percentage : 0.0
 Total NaN values in row 17671 :- 0 and it's percentage : 0.0
 Total NaN values in row 17672 :- 0 and it's percentage : 0.0
 Total NaN values in row 17673 :- 0 and it's percentage : 0.0
 Total NaN values in row 17674 :- 0 and it's percentage : 0.0
 Total NaN values in row 17675 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17676 :- 0 and it's percentage : 0.0
 Total NaN values in row 17677 :- 0 and it's percentage : 0.0
 Total NaN values in row 17678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17679 :- 0 and it's percentage : 0.0
 Total NaN values in row 17680 :- 0 and it's percentage : 0.0
 Total NaN values in row 17681 :- 0 and it's percentage : 0.0
 Total NaN values in row 17682 :- 0 and it's percentage : 0.0
 Total NaN values in row 17683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17684 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17685 :- 0 and it's percentage : 0.0
 Total NaN values in row 17686 :- 0 and it's percentage : 0.0
 Total NaN values in row 17687 :- 0 and it's percentage : 0.0
 Total NaN values in row 17688 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17689 :- 0 and it's percentage : 0.0
 Total NaN values in row 17690 :- 0 and it's percentage : 0.0
 Total NaN values in row 17691 :- 0 and it's percentage : 0.0
 Total NaN values in row 17692 :- 0 and it's percentage : 0.0
 Total NaN values in row 17693 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17694 :- 0 and it's percentage : 0.0
 Total NaN values in row 17695 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17696 :- 0 and it's percentage : 0.0
 Total NaN values in row 17697 :- 0 and it's percentage : 0.0
 Total NaN values in row 17698 :- 0 and it's percentage : 0.0
 Total NaN values in row 17699 :- 0 and it's percentage : 0.0
 Total NaN values in row 17700 :- 0 and it's percentage : 0.0
 Total NaN values in row 17701 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17702 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17703 :- 0 and it's percentage : 0.0
 Total NaN values in row 17704 :- 0 and it's percentage : 0.0
 Total NaN values in row 17705 :- 0 and it's percentage : 0.0
 Total NaN values in row 17706 :- 0 and it's percentage : 0.0
 Total NaN values in row 17707 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17708 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17709 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17710 :- 0 and it's percentage : 0.0
 Total NaN values in row 17711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17714 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 17715 :- 0 and it's percentage : 0.0
 Total NaN values in row 17716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17717 :- 0 and it's percentage : 0.0
 Total NaN values in row 17718 :- 0 and it's percentage : 0.0
 Total NaN values in row 17719 :- 0 and it's percentage : 0.0
 Total NaN values in row 17720 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17722 :- 0 and it's percentage : 0.0
 Total NaN values in row 17723 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17724 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17725 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 17726 :- 0 and it's percentage : 0.0
 Total NaN values in row 17727 :- 0 and it's percentage : 0.0
 Total NaN values in row 17728 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17729 :- 0 and it's percentage : 0.0
 Total NaN values in row 17730 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17731 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17732 :- 0 and it's percentage : 0.0
 Total NaN values in row 17733 :- 0 and it's percentage : 0.0
 Total NaN values in row 17734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17735 :- 0 and it's percentage : 0.0
 Total NaN values in row 17736 :- 0 and it's percentage : 0.0
 Total NaN values in row 17737 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17738 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17739 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17740 :- 0 and it's percentage : 0.0
 Total NaN values in row 17741 :- 0 and it's percentage : 0.0
 Total NaN values in row 17742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17743 :- 0 and it's percentage : 0.0
 Total NaN values in row 17744 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17745 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17746 :- 0 and it's percentage : 0.0
 Total NaN values in row 17747 :- 0 and it's percentage : 0.0
 Total NaN values in row 17748 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17749 :- 0 and it's percentage : 0.0
 Total NaN values in row 17750 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17751 :- 0 and it's percentage : 0.0
 Total NaN values in row 17752 :- 0 and it's percentage : 0.0
 Total NaN values in row 17753 :- 0 and it's percentage : 0.0
 Total NaN values in row 17754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17755 :- 0 and it's percentage : 0.0
 Total NaN values in row 17756 :- 0 and it's percentage : 0.0
 Total NaN values in row 17757 :- 0 and it's percentage : 0.0
 Total NaN values in row 17758 :- 0 and it's percentage : 0.0
 Total NaN values in row 17759 :- 0 and it's percentage : 0.0
 Total NaN values in row 17760 :- 0 and it's percentage : 0.0
 Total NaN values in row 17761 :- 0 and it's percentage : 0.0
 Total NaN values in row 17762 :- 0 and it's percentage : 0.0
 Total NaN values in row 17763 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17764 :- 0 and it's percentage : 0.0
 Total NaN values in row 17765 :- 0 and it's percentage : 0.0
 Total NaN values in row 17766 :- 0 and it's percentage : 0.0
 Total NaN values in row 17767 :- 0 and it's percentage : 0.0
 Total NaN values in row 17768 :- 0 and it's percentage : 0.0
 Total NaN values in row 17769 :- 0 and it's percentage : 0.0
 Total NaN values in row 17770 :- 0 and it's percentage : 0.0
 Total NaN values in row 17771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17772 :- 0 and it's percentage : 0.0
 Total NaN values in row 17773 :- 0 and it's percentage : 0.0
 Total NaN values in row 17774 :- 0 and it's percentage : 0.0
 Total NaN values in row 17775 :- 0 and it's percentage : 0.0
 Total NaN values in row 17776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17777 :- 0 and it's percentage : 0.0
 Total NaN values in row 17778 :- 0 and it's percentage : 0.0
 Total NaN values in row 17779 :- 0 and it's percentage : 0.0
 Total NaN values in row 17780 :- 0 and it's percentage : 0.0
 Total NaN values in row 17781 :- 0 and it's percentage : 0.0
 Total NaN values in row 17782 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17783 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17784 :- 0 and it's percentage : 0.0
 Total NaN values in row 17785 :- 0 and it's percentage : 0.0
 Total NaN values in row 17786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17787 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17788 :- 0 and it's percentage : 0.0
 Total NaN values in row 17789 :- 0 and it's percentage : 0.0
 Total NaN values in row 17790 :- 0 and it's percentage : 0.0
 Total NaN values in row 17791 :- 0 and it's percentage : 0.0
 Total NaN values in row 17792 :- 0 and it's percentage : 0.0
 Total NaN values in row 17793 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17794 :- 0 and it's percentage : 0.0
 Total NaN values in row 17795 :- 0 and it's percentage : 0.0
 Total NaN values in row 17796 :- 0 and it's percentage : 0.0
 Total NaN values in row 17797 :- 0 and it's percentage : 0.0
 Total NaN values in row 17798 :- 0 and it's percentage : 0.0
 Total NaN values in row 17799 :- 0 and it's percentage : 0.0
 Total NaN values in row 17800 :- 0 and it's percentage : 0.0
 Total NaN values in row 17801 :- 0 and it's percentage : 0.0
 Total NaN values in row 17802 :- 0 and it's percentage : 0.0
 Total NaN values in row 17803 :- 0 and it's percentage : 0.0
 Total NaN values in row 17804 :- 0 and it's percentage : 0.0
 Total NaN values in row 17805 :- 0 and it's percentage : 0.0
 Total NaN values in row 17806 :- 0 and it's percentage : 0.0
 Total NaN values in row 17807 :- 0 and it's percentage : 0.0
 Total NaN values in row 17808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17809 :- 0 and it's percentage : 0.0
 Total NaN values in row 17810 :- 0 and it's percentage : 0.0
 Total NaN values in row 17811 :- 0 and it's percentage : 0.0
 Total NaN values in row 17812 :- 0 and it's percentage : 0.0
 Total NaN values in row 17813 :- 0 and it's percentage : 0.0
 Total NaN values in row 17814 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17815 :- 0 and it's percentage : 0.0
 Total NaN values in row 17816 :- 0 and it's percentage : 0.0
 Total NaN values in row 17817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17818 :- 0 and it's percentage : 0.0
 Total NaN values in row 17819 :- 0 and it's percentage : 0.0
 Total NaN values in row 17820 :- 0 and it's percentage : 0.0
 Total NaN values in row 17821 :- 0 and it's percentage : 0.0
 Total NaN values in row 17822 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17823 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17824 :- 0 and it's percentage : 0.0
 Total NaN values in row 17825 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17827 :- 0 and it's percentage : 0.0
 Total NaN values in row 17828 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17829 :- 0 and it's percentage : 0.0
 Total NaN values in row 17830 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17832 :- 0 and it's percentage : 0.0
 Total NaN values in row 17833 :- 0 and it's percentage : 0.0
 Total NaN values in row 17834 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17835 :- 0 and it's percentage : 0.0
 Total NaN values in row 17836 :- 0 and it's percentage : 0.0
 Total NaN values in row 17837 :- 0 and it's percentage : 0.0
 Total NaN values in row 17838 :- 0 and it's percentage : 0.0
 Total NaN values in row 17839 :- 0 and it's percentage : 0.0

 Total NaN values in row 17840 :- 0 and it's percentage : 0.0
 Total NaN values in row 17841 :- 0 and it's percentage : 0.0
 Total NaN values in row 17842 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17843 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17844 :- 0 and it's percentage : 0.0
 Total NaN values in row 17845 :- 0 and it's percentage : 0.0
 Total NaN values in row 17846 :- 0 and it's percentage : 0.0
 Total NaN values in row 17847 :- 0 and it's percentage : 0.0
 Total NaN values in row 17848 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17849 :- 0 and it's percentage : 0.0
 Total NaN values in row 17850 :- 0 and it's percentage : 0.0
 Total NaN values in row 17851 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17852 :- 0 and it's percentage : 0.0
 Total NaN values in row 17853 :- 0 and it's percentage : 0.0
 Total NaN values in row 17854 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17855 :- 0 and it's percentage : 0.0
 Total NaN values in row 17856 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17857 :- 0 and it's percentage : 0.0
 Total NaN values in row 17858 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17859 :- 0 and it's percentage : 0.0
 Total NaN values in row 17860 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17861 :- 0 and it's percentage : 0.0
 Total NaN values in row 17862 :- 0 and it's percentage : 0.0
 Total NaN values in row 17863 :- 0 and it's percentage : 0.0
 Total NaN values in row 17864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17865 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17866 :- 0 and it's percentage : 0.0
 Total NaN values in row 17867 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17868 :- 0 and it's percentage : 0.0
 Total NaN values in row 17869 :- 0 and it's percentage : 0.0
 Total NaN values in row 17870 :- 0 and it's percentage : 0.0
 Total NaN values in row 17871 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17872 :- 0 and it's percentage : 0.0
 Total NaN values in row 17873 :- 0 and it's percentage : 0.0
 Total NaN values in row 17874 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17875 :- 0 and it's percentage : 0.0
 Total NaN values in row 17876 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17877 :- 0 and it's percentage : 0.0
 Total NaN values in row 17878 :- 0 and it's percentage : 0.0
 Total NaN values in row 17879 :- 0 and it's percentage : 0.0
 Total NaN values in row 17880 :- 0 and it's percentage : 0.0
 Total NaN values in row 17881 :- 0 and it's percentage : 0.0
 Total NaN values in row 17882 :- 0 and it's percentage : 0.0
 Total NaN values in row 17883 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17884 :- 0 and it's percentage : 0.0
 Total NaN values in row 17885 :- 0 and it's percentage : 0.0
 Total NaN values in row 17886 :- 0 and it's percentage : 0.0
 Total NaN values in row 17887 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17888 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17889 :- 0 and it's percentage : 0.0
 Total NaN values in row 17890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17891 :- 0 and it's percentage : 0.0
 Total NaN values in row 17892 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17893 :- 0 and it's percentage : 0.0
 Total NaN values in row 17894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17895 :- 0 and it's percentage : 0.0
 Total NaN values in row 17896 :- 0 and it's percentage : 0.0
 Total NaN values in row 17897 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17899 :- 0 and it's percentage : 0.0
 Total NaN values in row 17900 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17901 :- 0 and it's percentage : 0.0
 Total NaN values in row 17902 :- 0 and it's percentage : 0.0
 Total NaN values in row 17903 :- 0 and it's percentage : 0.0
 Total NaN values in row 17904 :- 0 and it's percentage : 0.0
 Total NaN values in row 17905 :- 0 and it's percentage : 0.0
 Total NaN values in row 17906 :- 0 and it's percentage : 0.0
 Total NaN values in row 17907 :- 0 and it's percentage : 0.0
 Total NaN values in row 17908 :- 0 and it's percentage : 0.0
 Total NaN values in row 17909 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17910 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17911 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17912 :- 0 and it's percentage : 0.0
 Total NaN values in row 17913 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17915 :- 0 and it's percentage : 0.0
 Total NaN values in row 17916 :- 0 and it's percentage : 0.0
 Total NaN values in row 17917 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17918 :- 0 and it's percentage : 0.0
 Total NaN values in row 17919 :- 0 and it's percentage : 0.0
 Total NaN values in row 17920 :- 0 and it's percentage : 0.0
 Total NaN values in row 17921 :- 0 and it's percentage : 0.0
 Total NaN values in row 17922 :- 0 and it's percentage : 0.0
 Total NaN values in row 17923 :- 0 and it's percentage : 0.0
 Total NaN values in row 17924 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17925 :- 0 and it's percentage : 0.0
 Total NaN values in row 17926 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17927 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17928 :- 0 and it's percentage : 0.0
 Total NaN values in row 17929 :- 0 and it's percentage : 0.0
 Total NaN values in row 17930 :- 0 and it's percentage : 0.0
 Total NaN values in row 17931 :- 0 and it's percentage : 0.0
 Total NaN values in row 17932 :- 0 and it's percentage : 0.0
 Total NaN values in row 17933 :- 0 and it's percentage : 0.0
 Total NaN values in row 17934 :- 0 and it's percentage : 0.0
 Total NaN values in row 17935 :- 0 and it's percentage : 0.0
 Total NaN values in row 17936 :- 0 and it's percentage : 0.0
 Total NaN values in row 17937 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17939 :- 0 and it's percentage : 0.0
 Total NaN values in row 17940 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17941 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17942 :- 0 and it's percentage : 0.0
 Total NaN values in row 17943 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17944 :- 0 and it's percentage : 0.0
 Total NaN values in row 17945 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 17946 :- 0 and it's percentage : 0.0
 Total NaN values in row 17947 :- 0 and it's percentage : 0.0
 Total NaN values in row 17948 :- 0 and it's percentage : 0.0
 Total NaN values in row 17949 :- 0 and it's percentage : 0.0
 Total NaN values in row 17950 :- 0 and it's percentage : 0.0
 Total NaN values in row 17951 :- 0 and it's percentage : 0.0
 Total NaN values in row 17952 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17953 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17955 :- 0 and it's percentage : 0.0
 Total NaN values in row 17956 :- 0 and it's percentage : 0.0
 Total NaN values in row 17957 :- 0 and it's percentage : 0.0
 Total NaN values in row 17958 :- 0 and it's percentage : 0.0
 Total NaN values in row 17959 :- 0 and it's percentage : 0.0
 Total NaN values in row 17960 :- 0 and it's percentage : 0.0
 Total NaN values in row 17961 :- 0 and it's percentage : 0.0
 Total NaN values in row 17962 :- 0 and it's percentage : 0.0
 Total NaN values in row 17963 :- 0 and it's percentage : 0.0
 Total NaN values in row 17964 :- 0 and it's percentage : 0.0
 Total NaN values in row 17965 :- 0 and it's percentage : 0.0
 Total NaN values in row 17966 :- 0 and it's percentage : 0.0
 Total NaN values in row 17967 :- 0 and it's percentage : 0.0
 Total NaN values in row 17968 :- 0 and it's percentage : 0.0
 Total NaN values in row 17969 :- 0 and it's percentage : 0.0
 Total NaN values in row 17970 :- 0 and it's percentage : 0.0
 Total NaN values in row 17971 :- 0 and it's percentage : 0.0
 Total NaN values in row 17972 :- 0 and it's percentage : 0.0
 Total NaN values in row 17973 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 17974 :- 0 and it's percentage : 0.0
 Total NaN values in row 17975 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 17976 :- 0 and it's percentage : 0.0
 Total NaN values in row 17977 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17978 :- 0 and it's percentage : 0.0
 Total NaN values in row 17979 :- 0 and it's percentage : 0.0
 Total NaN values in row 17980 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17981 :- 0 and it's percentage : 0.0
 Total NaN values in row 17982 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17983 :- 0 and it's percentage : 0.0
 Total NaN values in row 17984 :- 0 and it's percentage : 0.0
 Total NaN values in row 17985 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 17986 :- 0 and it's percentage : 0.0
 Total NaN values in row 17987 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17988 :- 0 and it's percentage : 0.0
 Total NaN values in row 17989 :- 0 and it's percentage : 0.0
 Total NaN values in row 17990 :- 0 and it's percentage : 0.0
 Total NaN values in row 17991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 17992 :- 0 and it's percentage : 0.0
 Total NaN values in row 17993 :- 0 and it's percentage : 0.0
 Total NaN values in row 17994 :- 0 and it's percentage : 0.0
 Total NaN values in row 17995 :- 0 and it's percentage : 0.0
 Total NaN values in row 17996 :- 0 and it's percentage : 0.0
 Total NaN values in row 17997 :- 0 and it's percentage : 0.0
 Total NaN values in row 17998 :- 0 and it's percentage : 0.0
 Total NaN values in row 17999 :- 0 and it's percentage : 0.0
 Total NaN values in row 18000 :- 0 and it's percentage : 0.0
 Total NaN values in row 18001 :- 0 and it's percentage : 0.0
 Total NaN values in row 18002 :- 0 and it's percentage : 0.0
 Total NaN values in row 18003 :- 0 and it's percentage : 0.0
 Total NaN values in row 18004 :- 0 and it's percentage : 0.0
 Total NaN values in row 18005 :- 0 and it's percentage : 0.0
 Total NaN values in row 18006 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18007 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18008 :- 0 and it's percentage : 0.0
 Total NaN values in row 18009 :- 0 and it's percentage : 0.0
 Total NaN values in row 18010 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18011 :- 0 and it's percentage : 0.0
 Total NaN values in row 18012 :- 0 and it's percentage : 0.0
 Total NaN values in row 18013 :- 0 and it's percentage : 0.0
 Total NaN values in row 18014 :- 0 and it's percentage : 0.0
 Total NaN values in row 18015 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18016 :- 0 and it's percentage : 0.0
 Total NaN values in row 18017 :- 0 and it's percentage : 0.0
 Total NaN values in row 18018 :- 0 and it's percentage : 0.0
 Total NaN values in row 18019 :- 0 and it's percentage : 0.0
 Total NaN values in row 18020 :- 0 and it's percentage : 0.0
 Total NaN values in row 18021 :- 0 and it's percentage : 0.0
 Total NaN values in row 18022 :- 0 and it's percentage : 0.0
 Total NaN values in row 18023 :- 0 and it's percentage : 0.0
 Total NaN values in row 18024 :- 0 and it's percentage : 0.0
 Total NaN values in row 18025 :- 0 and it's percentage : 0.0
 Total NaN values in row 18026 :- 0 and it's percentage : 0.0
 Total NaN values in row 18027 :- 0 and it's percentage : 0.0
 Total NaN values in row 18028 :- 0 and it's percentage : 0.0
 Total NaN values in row 18029 :- 0 and it's percentage : 0.0
 Total NaN values in row 18030 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18031 :- 0 and it's percentage : 0.0
 Total NaN values in row 18032 :- 0 and it's percentage : 0.0
 Total NaN values in row 18033 :- 0 and it's percentage : 0.0
 Total NaN values in row 18034 :- 0 and it's percentage : 0.0
 Total NaN values in row 18035 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18036 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18037 :- 0 and it's percentage : 0.0
 Total NaN values in row 18038 :- 0 and it's percentage : 0.0
 Total NaN values in row 18039 :- 0 and it's percentage : 0.0
 Total NaN values in row 18040 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18041 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18042 :- 0 and it's percentage : 0.0
 Total NaN values in row 18043 :- 0 and it's percentage : 0.0
 Total NaN values in row 18044 :- 0 and it's percentage : 0.0
 Total NaN values in row 18045 :- 0 and it's percentage : 0.0
 Total NaN values in row 18046 :- 0 and it's percentage : 0.0
 Total NaN values in row 18047 :- 0 and it's percentage : 0.0
 Total NaN values in row 18048 :- 0 and it's percentage : 0.0
 Total NaN values in row 18049 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18050 :- 0 and it's percentage : 0.0
 Total NaN values in row 18051 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18052 :- 0 and it's percentage : 0.0
 Total NaN values in row 18053 :- 0 and it's percentage : 0.0
 Total NaN values in row 18054 :- 0 and it's percentage : 0.0
 Total NaN values in row 18055 :- 0 and it's percentage : 0.0
 Total NaN values in row 18056 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18057 :- 0 and it's percentage : 0.0
 Total NaN values in row 18058 :- 0 and it's percentage : 0.0
 Total NaN values in row 18059 :- 0 and it's percentage : 0.0
 Total NaN values in row 18060 :- 0 and it's percentage : 0.0
 Total NaN values in row 18061 :- 0 and it's percentage : 0.0
 Total NaN values in row 18062 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18063 :- 0 and it's percentage : 0.0
 Total NaN values in row 18064 :- 0 and it's percentage : 0.0
 Total NaN values in row 18065 :- 0 and it's percentage : 0.0
 Total NaN values in row 18066 :- 0 and it's percentage : 0.0
 Total NaN values in row 18067 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18068 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18069 :- 0 and it's percentage : 0.0
 Total NaN values in row 18070 :- 0 and it's percentage : 0.0
 Total NaN values in row 18071 :- 0 and it's percentage : 0.0
 Total NaN values in row 18072 :- 0 and it's percentage : 0.0
 Total NaN values in row 18073 :- 0 and it's percentage : 0.0
 Total NaN values in row 18074 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18076 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18077 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18078 :- 0 and it's percentage : 0.0
 Total NaN values in row 18079 :- 0 and it's percentage : 0.0
 Total NaN values in row 18080 :- 0 and it's percentage : 0.0
 Total NaN values in row 18081 :- 0 and it's percentage : 0.0
 Total NaN values in row 18082 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18083 :- 0 and it's percentage : 0.0
 Total NaN values in row 18084 :- 0 and it's percentage : 0.0
 Total NaN values in row 18085 :- 0 and it's percentage : 0.0
 Total NaN values in row 18086 :- 0 and it's percentage : 0.0
 Total NaN values in row 18087 :- 0 and it's percentage : 0.0
 Total NaN values in row 18088 :- 0 and it's percentage : 0.0
 Total NaN values in row 18089 :- 0 and it's percentage : 0.0
 Total NaN values in row 18090 :- 0 and it's percentage : 0.0
 Total NaN values in row 18091 :- 0 and it's percentage : 0.0
 Total NaN values in row 18092 :- 0 and it's percentage : 0.0
 Total NaN values in row 18093 :- 0 and it's percentage : 0.0
 Total NaN values in row 18094 :- 0 and it's percentage : 0.0
 Total NaN values in row 18095 :- 0 and it's percentage : 0.0
 Total NaN values in row 18096 :- 0 and it's percentage : 0.0
 Total NaN values in row 18097 :- 0 and it's percentage : 0.0
 Total NaN values in row 18098 :- 0 and it's percentage : 0.0
 Total NaN values in row 18099 :- 0 and it's percentage : 0.0
 Total NaN values in row 18100 :- 0 and it's percentage : 0.0
 Total NaN values in row 18101 :- 0 and it's percentage : 0.0
 Total NaN values in row 18102 :- 0 and it's percentage : 0.0
 Total NaN values in row 18103 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18104 :- 0 and it's percentage : 0.0
 Total NaN values in row 18105 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18106 :- 0 and it's percentage : 0.0
 Total NaN values in row 18107 :- 0 and it's percentage : 0.0
 Total NaN values in row 18108 :- 0 and it's percentage : 0.0
 Total NaN values in row 18109 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18111 :- 0 and it's percentage : 0.0
 Total NaN values in row 18112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18113 :- 0 and it's percentage : 0.0
 Total NaN values in row 18114 :- 0 and it's percentage : 0.0
 Total NaN values in row 18115 :- 0 and it's percentage : 0.0
 Total NaN values in row 18116 :- 0 and it's percentage : 0.0
 Total NaN values in row 18117 :- 0 and it's percentage : 0.0
 Total NaN values in row 18118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18119 :- 0 and it's percentage : 0.0
 Total NaN values in row 18120 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18121 :- 0 and it's percentage : 0.0
 Total NaN values in row 18122 :- 0 and it's percentage : 0.0
 Total NaN values in row 18123 :- 0 and it's percentage : 0.0
 Total NaN values in row 18124 :- 0 and it's percentage : 0.0
 Total NaN values in row 18125 :- 0 and it's percentage : 0.0
 Total NaN values in row 18126 :- 0 and it's percentage : 0.0
 Total NaN values in row 18127 :- 0 and it's percentage : 0.0
 Total NaN values in row 18128 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 18129 :- 0 and it's percentage : 0.0
 Total NaN values in row 18130 :- 0 and it's percentage : 0.0
 Total NaN values in row 18131 :- 0 and it's percentage : 0.0
 Total NaN values in row 18132 :- 0 and it's percentage : 0.0
 Total NaN values in row 18133 :- 0 and it's percentage : 0.0
 Total NaN values in row 18134 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18135 :- 0 and it's percentage : 0.0
 Total NaN values in row 18136 :- 0 and it's percentage : 0.0
 Total NaN values in row 18137 :- 0 and it's percentage : 0.0
 Total NaN values in row 18138 :- 0 and it's percentage : 0.0
 Total NaN values in row 18139 :- 0 and it's percentage : 0.0
 Total NaN values in row 18140 :- 0 and it's percentage : 0.0
 Total NaN values in row 18141 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18142 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 18143 :- 0 and it's percentage : 0.0
 Total NaN values in row 18144 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18145 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18146 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18147 :- 0 and it's percentage : 0.0
 Total NaN values in row 18148 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18149 :- 0 and it's percentage : 0.0
 Total NaN values in row 18150 :- 0 and it's percentage : 0.0
 Total NaN values in row 18151 :- 0 and it's percentage : 0.0
 Total NaN values in row 18152 :- 0 and it's percentage : 0.0
 Total NaN values in row 18153 :- 0 and it's percentage : 0.0
 Total NaN values in row 18154 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18155 :- 0 and it's percentage : 0.0
 Total NaN values in row 18156 :- 0 and it's percentage : 0.0
 Total NaN values in row 18157 :- 0 and it's percentage : 0.0
 Total NaN values in row 18158 :- 0 and it's percentage : 0.0
 Total NaN values in row 18159 :- 0 and it's percentage : 0.0
 Total NaN values in row 18160 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18161 :- 0 and it's percentage : 0.0
 Total NaN values in row 18162 :- 0 and it's percentage : 0.0
 Total NaN values in row 18163 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18164 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18165 :- 0 and it's percentage : 0.0
 Total NaN values in row 18166 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18167 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18168 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18169 :- 0 and it's percentage : 0.0
 Total NaN values in row 18170 :- 0 and it's percentage : 0.0
 Total NaN values in row 18171 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18172 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18173 :- 0 and it's percentage : 0.0
 Total NaN values in row 18174 :- 0 and it's percentage : 0.0
 Total NaN values in row 18175 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18176 :- 0 and it's percentage : 0.0
 Total NaN values in row 18177 :- 0 and it's percentage : 0.0
 Total NaN values in row 18178 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18180 :- 0 and it's percentage : 0.0
 Total NaN values in row 18181 :- 0 and it's percentage : 0.0
 Total NaN values in row 18182 :- 0 and it's percentage : 0.0
 Total NaN values in row 18183 :- 0 and it's percentage : 0.0
 Total NaN values in row 18184 :- 0 and it's percentage : 0.0
 Total NaN values in row 18185 :- 0 and it's percentage : 0.0
 Total NaN values in row 18186 :- 0 and it's percentage : 0.0
 Total NaN values in row 18187 :- 0 and it's percentage : 0.0
 Total NaN values in row 18188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18189 :- 0 and it's percentage : 0.0
 Total NaN values in row 18190 :- 0 and it's percentage : 0.0
 Total NaN values in row 18191 :- 0 and it's percentage : 0.0
 Total NaN values in row 18192 :- 0 and it's percentage : 0.0
 Total NaN values in row 18193 :- 0 and it's percentage : 0.0
 Total NaN values in row 18194 :- 0 and it's percentage : 0.0
 Total NaN values in row 18195 :- 0 and it's percentage : 0.0
 Total NaN values in row 18196 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18197 :- 0 and it's percentage : 0.0
 Total NaN values in row 18198 :- 0 and it's percentage : 0.0
 Total NaN values in row 18199 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18200 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18201 :- 0 and it's percentage : 0.0
 Total NaN values in row 18202 :- 0 and it's percentage : 0.0
 Total NaN values in row 18203 :- 0 and it's percentage : 0.0
 Total NaN values in row 18204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18205 :- 0 and it's percentage : 0.0
 Total NaN values in row 18206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18207 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18208 :- 0 and it's percentage : 0.0
 Total NaN values in row 18209 :- 0 and it's percentage : 0.0
 Total NaN values in row 18210 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18211 :- 0 and it's percentage : 0.0
 Total NaN values in row 18212 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18213 :- 0 and it's percentage : 0.0
 Total NaN values in row 18214 :- 0 and it's percentage : 0.0
 Total NaN values in row 18215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18216 :- 0 and it's percentage : 0.0
 Total NaN values in row 18217 :- 0 and it's percentage : 0.0
 Total NaN values in row 18218 :- 0 and it's percentage : 0.0
 Total NaN values in row 18219 :- 0 and it's percentage : 0.0
 Total NaN values in row 18220 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18221 :- 0 and it's percentage : 0.0
 Total NaN values in row 18222 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18223 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18224 :- 0 and it's percentage : 0.0
 Total NaN values in row 18225 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18226 :- 0 and it's percentage : 0.0
 Total NaN values in row 18227 :- 0 and it's percentage : 0.0
 Total NaN values in row 18228 :- 0 and it's percentage : 0.0
 Total NaN values in row 18229 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18230 :- 0 and it's percentage : 0.0
 Total NaN values in row 18231 :- 0 and it's percentage : 0.0
 Total NaN values in row 18232 :- 0 and it's percentage : 0.0
 Total NaN values in row 18233 :- 0 and it's percentage : 0.0
 Total NaN values in row 18234 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18235 :- 0 and it's percentage : 0.0
 Total NaN values in row 18236 :- 0 and it's percentage : 0.0
 Total NaN values in row 18237 :- 0 and it's percentage : 0.0
 Total NaN values in row 18238 :- 0 and it's percentage : 0.0
 Total NaN values in row 18239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18240 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18241 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18242 :- 0 and it's percentage : 0.0
 Total NaN values in row 18243 :- 0 and it's percentage : 0.0
 Total NaN values in row 18244 :- 0 and it's percentage : 0.0
 Total NaN values in row 18245 :- 0 and it's percentage : 0.0
 Total NaN values in row 18246 :- 0 and it's percentage : 0.0
 Total NaN values in row 18247 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18248 :- 0 and it's percentage : 0.0
 Total NaN values in row 18249 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18251 :- 0 and it's percentage : 0.0
 Total NaN values in row 18252 :- 0 and it's percentage : 0.0
 Total NaN values in row 18253 :- 0 and it's percentage : 0.0
 Total NaN values in row 18254 :- 0 and it's percentage : 0.0
 Total NaN values in row 18255 :- 0 and it's percentage : 0.0
 Total NaN values in row 18256 :- 0 and it's percentage : 0.0
 Total NaN values in row 18257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18258 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 18259 :- 0 and it's percentage : 0.0
 Total NaN values in row 18260 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18261 :- 0 and it's percentage : 0.0
 Total NaN values in row 18262 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18263 :- 0 and it's percentage : 0.0
 Total NaN values in row 18264 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18265 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18269 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18271 :- 0 and it's percentage : 0.0
 Total NaN values in row 18272 :- 0 and it's percentage : 0.0
 Total NaN values in row 18273 :- 0 and it's percentage : 0.0
 Total NaN values in row 18274 :- 0 and it's percentage : 0.0
 Total NaN values in row 18275 :- 0 and it's percentage : 0.0
 Total NaN values in row 18276 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18277 :- 0 and it's percentage : 0.0
 Total NaN values in row 18278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18279 :- 0 and it's percentage : 0.0
 Total NaN values in row 18280 :- 0 and it's percentage : 0.0
 Total NaN values in row 18281 :- 0 and it's percentage : 0.0
 Total NaN values in row 18282 :- 0 and it's percentage : 0.0
 Total NaN values in row 18283 :- 0 and it's percentage : 0.0
 Total NaN values in row 18284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18285 :- 0 and it's percentage : 0.0
 Total NaN values in row 18286 :- 0 and it's percentage : 0.0
 Total NaN values in row 18287 :- 0 and it's percentage : 0.0
 Total NaN values in row 18288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18289 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18290 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18291 :- 0 and it's percentage : 0.0
 Total NaN values in row 18292 :- 0 and it's percentage : 0.0
 Total NaN values in row 18293 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18294 :- 0 and it's percentage : 0.0
 Total NaN values in row 18295 :- 0 and it's percentage : 0.0
 Total NaN values in row 18296 :- 0 and it's percentage : 0.0
 Total NaN values in row 18297 :- 0 and it's percentage : 0.0
 Total NaN values in row 18298 :- 0 and it's percentage : 0.0
 Total NaN values in row 18299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18300 :- 0 and it's percentage : 0.0
 Total NaN values in row 18301 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18302 :- 0 and it's percentage : 0.0
 Total NaN values in row 18303 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18304 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18305 :- 0 and it's percentage : 0.0
 Total NaN values in row 18306 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18307 :- 0 and it's percentage : 0.0
 Total NaN values in row 18308 :- 0 and it's percentage : 0.0
 Total NaN values in row 18309 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 18310 :- 0 and it's percentage : 0.0
 Total NaN values in row 18311 :- 0 and it's percentage : 0.0
 Total NaN values in row 18312 :- 0 and it's percentage : 0.0
 Total NaN values in row 18313 :- 0 and it's percentage : 0.0
 Total NaN values in row 18314 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18315 :- 0 and it's percentage : 0.0
 Total NaN values in row 18316 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18317 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18318 :- 0 and it's percentage : 0.0
 Total NaN values in row 18319 :- 0 and it's percentage : 0.0
 Total NaN values in row 18320 :- 0 and it's percentage : 0.0
 Total NaN values in row 18321 :- 0 and it's percentage : 0.0
 Total NaN values in row 18322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18323 :- 0 and it's percentage : 0.0
 Total NaN values in row 18324 :- 0 and it's percentage : 0.0
 Total NaN values in row 18325 :- 0 and it's percentage : 0.0
 Total NaN values in row 18326 :- 0 and it's percentage : 0.0
 Total NaN values in row 18327 :- 0 and it's percentage : 0.0
 Total NaN values in row 18328 :- 0 and it's percentage : 0.0
 Total NaN values in row 18329 :- 0 and it's percentage : 0.0
 Total NaN values in row 18330 :- 0 and it's percentage : 0.0
 Total NaN values in row 18331 :- 0 and it's percentage : 0.0
 Total NaN values in row 18332 :- 0 and it's percentage : 0.0
 Total NaN values in row 18333 :- 0 and it's percentage : 0.0
 Total NaN values in row 18334 :- 0 and it's percentage : 0.0
 Total NaN values in row 18335 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18336 :- 0 and it's percentage : 0.0
 Total NaN values in row 18337 :- 0 and it's percentage : 0.0
 Total NaN values in row 18338 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18339 :- 0 and it's percentage : 0.0
 Total NaN values in row 18340 :- 0 and it's percentage : 0.0
 Total NaN values in row 18341 :- 0 and it's percentage : 0.0
 Total NaN values in row 18342 :- 0 and it's percentage : 0.0
 Total NaN values in row 18343 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18344 :- 0 and it's percentage : 0.0
 Total NaN values in row 18345 :- 0 and it's percentage : 0.0
 Total NaN values in row 18346 :- 0 and it's percentage : 0.0
 Total NaN values in row 18347 :- 0 and it's percentage : 0.0
 Total NaN values in row 18348 :- 0 and it's percentage : 0.0
 Total NaN values in row 18349 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18350 :- 0 and it's percentage : 0.0
 Total NaN values in row 18351 :- 0 and it's percentage : 0.0
 Total NaN values in row 18352 :- 0 and it's percentage : 0.0
 Total NaN values in row 18353 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18354 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18355 :- 0 and it's percentage : 0.0
 Total NaN values in row 18356 :- 0 and it's percentage : 0.0
 Total NaN values in row 18357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18358 :- 0 and it's percentage : 0.0
 Total NaN values in row 18359 :- 0 and it's percentage : 0.0
 Total NaN values in row 18360 :- 0 and it's percentage : 0.0
 Total NaN values in row 18361 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18362 :- 0 and it's percentage : 0.0
 Total NaN values in row 18363 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18364 :- 0 and it's percentage : 0.0
 Total NaN values in row 18365 :- 0 and it's percentage : 0.0
 Total NaN values in row 18366 :- 0 and it's percentage : 0.0
 Total NaN values in row 18367 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18368 :- 0 and it's percentage : 0.0
 Total NaN values in row 18369 :- 0 and it's percentage : 0.0
 Total NaN values in row 18370 :- 0 and it's percentage : 0.0
 Total NaN values in row 18371 :- 0 and it's percentage : 0.0
 Total NaN values in row 18372 :- 0 and it's percentage : 0.0
 Total NaN values in row 18373 :- 0 and it's percentage : 0.0
 Total NaN values in row 18374 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18376 :- 0 and it's percentage : 0.0
 Total NaN values in row 18377 :- 0 and it's percentage : 0.0
 Total NaN values in row 18378 :- 0 and it's percentage : 0.0
 Total NaN values in row 18379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18380 :- 0 and it's percentage : 0.0
 Total NaN values in row 18381 :- 0 and it's percentage : 0.0
 Total NaN values in row 18382 :- 0 and it's percentage : 0.0
 Total NaN values in row 18383 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18384 :- 0 and it's percentage : 0.0
 Total NaN values in row 18385 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18386 :- 0 and it's percentage : 0.0
 Total NaN values in row 18387 :- 0 and it's percentage : 0.0
 Total NaN values in row 18388 :- 0 and it's percentage : 0.0
 Total NaN values in row 18389 :- 0 and it's percentage : 0.0
 Total NaN values in row 18390 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18391 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18392 :- 0 and it's percentage : 0.0
 Total NaN values in row 18393 :- 0 and it's percentage : 0.0
 Total NaN values in row 18394 :- 0 and it's percentage : 0.0
 Total NaN values in row 18395 :- 0 and it's percentage : 0.0

 Total NaN values in row 18396 :- 0 and it's percentage : 0.0
 Total NaN values in row 18397 :- 0 and it's percentage : 0.0
 Total NaN values in row 18398 :- 0 and it's percentage : 0.0
 Total NaN values in row 18399 :- 0 and it's percentage : 0.0
 Total NaN values in row 18400 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18401 :- 0 and it's percentage : 0.0
 Total NaN values in row 18402 :- 0 and it's percentage : 0.0
 Total NaN values in row 18403 :- 0 and it's percentage : 0.0
 Total NaN values in row 18404 :- 0 and it's percentage : 0.0
 Total NaN values in row 18405 :- 0 and it's percentage : 0.0
 Total NaN values in row 18406 :- 0 and it's percentage : 0.0
 Total NaN values in row 18407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18408 :- 0 and it's percentage : 0.0
 Total NaN values in row 18409 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18410 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18411 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18412 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18413 :- 0 and it's percentage : 0.0
 Total NaN values in row 18414 :- 0 and it's percentage : 0.0
 Total NaN values in row 18415 :- 0 and it's percentage : 0.0
 Total NaN values in row 18416 :- 0 and it's percentage : 0.0
 Total NaN values in row 18417 :- 0 and it's percentage : 0.0
 Total NaN values in row 18418 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18419 :- 0 and it's percentage : 0.0
 Total NaN values in row 18420 :- 0 and it's percentage : 0.0
 Total NaN values in row 18421 :- 0 and it's percentage : 0.0
 Total NaN values in row 18422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18423 :- 0 and it's percentage : 0.0
 Total NaN values in row 18424 :- 0 and it's percentage : 0.0
 Total NaN values in row 18425 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18426 :- 0 and it's percentage : 0.0
 Total NaN values in row 18427 :- 0 and it's percentage : 0.0
 Total NaN values in row 18428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18429 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18430 :- 0 and it's percentage : 0.0
 Total NaN values in row 18431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18432 :- 0 and it's percentage : 0.0
 Total NaN values in row 18433 :- 0 and it's percentage : 0.0
 Total NaN values in row 18434 :- 0 and it's percentage : 0.0
 Total NaN values in row 18435 :- 0 and it's percentage : 0.0
 Total NaN values in row 18436 :- 0 and it's percentage : 0.0
 Total NaN values in row 18437 :- 0 and it's percentage : 0.0
 Total NaN values in row 18438 :- 0 and it's percentage : 0.0
 Total NaN values in row 18439 :- 0 and it's percentage : 0.0
 Total NaN values in row 18440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18443 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18444 :- 0 and it's percentage : 0.0
 Total NaN values in row 18445 :- 0 and it's percentage : 0.0
 Total NaN values in row 18446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18448 :- 0 and it's percentage : 0.0
 Total NaN values in row 18449 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18450 :- 0 and it's percentage : 0.0
 Total NaN values in row 18451 :- 0 and it's percentage : 0.0
 Total NaN values in row 18452 :- 0 and it's percentage : 0.0
 Total NaN values in row 18453 :- 0 and it's percentage : 0.0
 Total NaN values in row 18454 :- 0 and it's percentage : 0.0
 Total NaN values in row 18455 :- 0 and it's percentage : 0.0
 Total NaN values in row 18456 :- 0 and it's percentage : 0.0
 Total NaN values in row 18457 :- 0 and it's percentage : 0.0
 Total NaN values in row 18458 :- 0 and it's percentage : 0.0
 Total NaN values in row 18459 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18460 :- 0 and it's percentage : 0.0
 Total NaN values in row 18461 :- 0 and it's percentage : 0.0
 Total NaN values in row 18462 :- 0 and it's percentage : 0.0
 Total NaN values in row 18463 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18464 :- 0 and it's percentage : 0.0
 Total NaN values in row 18465 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18466 :- 0 and it's percentage : 0.0
 Total NaN values in row 18467 :- 0 and it's percentage : 0.0
 Total NaN values in row 18468 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18469 :- 0 and it's percentage : 0.0
 Total NaN values in row 18470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18472 :- 0 and it's percentage : 0.0
 Total NaN values in row 18473 :- 0 and it's percentage : 0.0
 Total NaN values in row 18474 :- 0 and it's percentage : 0.0
 Total NaN values in row 18475 :- 0 and it's percentage : 0.0
 Total NaN values in row 18476 :- 0 and it's percentage : 0.0
 Total NaN values in row 18477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18479 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18480 :- 0 and it's percentage : 0.0
 Total NaN values in row 18481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18482 :- 0 and it's percentage : 0.0
 Total NaN values in row 18483 :- 0 and it's percentage : 0.0
 Total NaN values in row 18484 :- 0 and it's percentage : 0.0
 Total NaN values in row 18485 :- 0 and it's percentage : 0.0
 Total NaN values in row 18486 :- 0 and it's percentage : 0.0
 Total NaN values in row 18487 :- 0 and it's percentage : 0.0
 Total NaN values in row 18488 :- 0 and it's percentage : 0.0
 Total NaN values in row 18489 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18491 :- 0 and it's percentage : 0.0
 Total NaN values in row 18492 :- 0 and it's percentage : 0.0
 Total NaN values in row 18493 :- 0 and it's percentage : 0.0
 Total NaN values in row 18494 :- 0 and it's percentage : 0.0
 Total NaN values in row 18495 :- 0 and it's percentage : 0.0
 Total NaN values in row 18496 :- 0 and it's percentage : 0.0
 Total NaN values in row 18497 :- 0 and it's percentage : 0.0
 Total NaN values in row 18498 :- 0 and it's percentage : 0.0
 Total NaN values in row 18499 :- 0 and it's percentage : 0.0
 Total NaN values in row 18500 :- 0 and it's percentage : 0.0
 Total NaN values in row 18501 :- 0 and it's percentage : 0.0
 Total NaN values in row 18502 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18503 :- 0 and it's percentage : 0.0
 Total NaN values in row 18504 :- 0 and it's percentage : 0.0
 Total NaN values in row 18505 :- 0 and it's percentage : 0.0
 Total NaN values in row 18506 :- 0 and it's percentage : 0.0
 Total NaN values in row 18507 :- 0 and it's percentage : 0.0
 Total NaN values in row 18508 :- 0 and it's percentage : 0.0
 Total NaN values in row 18509 :- 0 and it's percentage : 0.0
 Total NaN values in row 18510 :- 0 and it's percentage : 0.0
 Total NaN values in row 18511 :- 0 and it's percentage : 0.0
 Total NaN values in row 18512 :- 0 and it's percentage : 0.0
 Total NaN values in row 18513 :- 0 and it's percentage : 0.0
 Total NaN values in row 18514 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18515 :- 0 and it's percentage : 0.0
 Total NaN values in row 18516 :- 0 and it's percentage : 0.0
 Total NaN values in row 18517 :- 0 and it's percentage : 0.0
 Total NaN values in row 18518 :- 0 and it's percentage : 0.0
 Total NaN values in row 18519 :- 0 and it's percentage : 0.0
 Total NaN values in row 18520 :- 0 and it's percentage : 0.0
 Total NaN values in row 18521 :- 0 and it's percentage : 0.0
 Total NaN values in row 18522 :- 0 and it's percentage : 0.0
 Total NaN values in row 18523 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18524 :- 10 and it's percentage : 55.55555555555556

 Total NaN values in row 18525 :- 0 and it's percentage : 0.0
 Total NaN values in row 18526 :- 0 and it's percentage : 0.0
 Total NaN values in row 18527 :- 0 and it's percentage : 0.0
 Total NaN values in row 18528 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18529 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18530 :- 0 and it's percentage : 0.0
 Total NaN values in row 18531 :- 0 and it's percentage : 0.0
 Total NaN values in row 18532 :- 0 and it's percentage : 0.0
 Total NaN values in row 18533 :- 0 and it's percentage : 0.0
 Total NaN values in row 18534 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18535 :- 0 and it's percentage : 0.0
 Total NaN values in row 18536 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18537 :- 0 and it's percentage : 0.0
 Total NaN values in row 18538 :- 0 and it's percentage : 0.0
 Total NaN values in row 18539 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18540 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18541 :- 0 and it's percentage : 0.0
 Total NaN values in row 18542 :- 0 and it's percentage : 0.0
 Total NaN values in row 18543 :- 0 and it's percentage : 0.0
 Total NaN values in row 18544 :- 0 and it's percentage : 0.0
 Total NaN values in row 18545 :- 0 and it's percentage : 0.0
 Total NaN values in row 18546 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18547 :- 0 and it's percentage : 0.0
 Total NaN values in row 18548 :- 0 and it's percentage : 0.0
 Total NaN values in row 18549 :- 0 and it's percentage : 0.0
 Total NaN values in row 18550 :- 0 and it's percentage : 0.0
 Total NaN values in row 18551 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18552 :- 0 and it's percentage : 0.0
 Total NaN values in row 18553 :- 0 and it's percentage : 0.0
 Total NaN values in row 18554 :- 0 and it's percentage : 0.0
 Total NaN values in row 18555 :- 0 and it's percentage : 0.0
 Total NaN values in row 18556 :- 0 and it's percentage : 0.0
 Total NaN values in row 18557 :- 0 and it's percentage : 0.0
 Total NaN values in row 18558 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18559 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18560 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18561 :- 0 and it's percentage : 0.0
 Total NaN values in row 18562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18563 :- 0 and it's percentage : 0.0
 Total NaN values in row 18564 :- 0 and it's percentage : 0.0
 Total NaN values in row 18565 :- 0 and it's percentage : 0.0
 Total NaN values in row 18566 :- 0 and it's percentage : 0.0
 Total NaN values in row 18567 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18568 :- 0 and it's percentage : 0.0
 Total NaN values in row 18569 :- 0 and it's percentage : 0.0
 Total NaN values in row 18570 :- 0 and it's percentage : 0.0
 Total NaN values in row 18571 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18572 :- 0 and it's percentage : 0.0
 Total NaN values in row 18573 :- 0 and it's percentage : 0.0
 Total NaN values in row 18574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18575 :- 0 and it's percentage : 0.0
 Total NaN values in row 18576 :- 0 and it's percentage : 0.0
 Total NaN values in row 18577 :- 0 and it's percentage : 0.0
 Total NaN values in row 18578 :- 0 and it's percentage : 0.0
 Total NaN values in row 18579 :- 0 and it's percentage : 0.0
 Total NaN values in row 18580 :- 0 and it's percentage : 0.0
 Total NaN values in row 18581 :- 0 and it's percentage : 0.0
 Total NaN values in row 18582 :- 0 and it's percentage : 0.0
 Total NaN values in row 18583 :- 0 and it's percentage : 0.0
 Total NaN values in row 18584 :- 0 and it's percentage : 0.0
 Total NaN values in row 18585 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18586 :- 0 and it's percentage : 0.0
 Total NaN values in row 18587 :- 0 and it's percentage : 0.0
 Total NaN values in row 18588 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18589 :- 0 and it's percentage : 0.0
 Total NaN values in row 18590 :- 0 and it's percentage : 0.0
 Total NaN values in row 18591 :- 0 and it's percentage : 0.0
 Total NaN values in row 18592 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18593 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18594 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18595 :- 0 and it's percentage : 0.0
 Total NaN values in row 18596 :- 0 and it's percentage : 0.0
 Total NaN values in row 18597 :- 0 and it's percentage : 0.0
 Total NaN values in row 18598 :- 0 and it's percentage : 0.0
 Total NaN values in row 18599 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18600 :- 0 and it's percentage : 0.0
 Total NaN values in row 18601 :- 0 and it's percentage : 0.0
 Total NaN values in row 18602 :- 0 and it's percentage : 0.0
 Total NaN values in row 18603 :- 0 and it's percentage : 0.0
 Total NaN values in row 18604 :- 0 and it's percentage : 0.0
 Total NaN values in row 18605 :- 0 and it's percentage : 0.0
 Total NaN values in row 18606 :- 0 and it's percentage : 0.0
 Total NaN values in row 18607 :- 0 and it's percentage : 0.0
 Total NaN values in row 18608 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18609 :- 0 and it's percentage : 0.0
 Total NaN values in row 18610 :- 0 and it's percentage : 0.0
 Total NaN values in row 18611 :- 0 and it's percentage : 0.0
 Total NaN values in row 18612 :- 0 and it's percentage : 0.0
 Total NaN values in row 18613 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18614 :- 0 and it's percentage : 0.0
 Total NaN values in row 18615 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 18616 :- 0 and it's percentage : 0.0
 Total NaN values in row 18617 :- 0 and it's percentage : 0.0
 Total NaN values in row 18618 :- 0 and it's percentage : 0.0
 Total NaN values in row 18619 :- 0 and it's percentage : 0.0
 Total NaN values in row 18620 :- 0 and it's percentage : 0.0
 Total NaN values in row 18621 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18622 :- 0 and it's percentage : 0.0
 Total NaN values in row 18623 :- 0 and it's percentage : 0.0
 Total NaN values in row 18624 :- 0 and it's percentage : 0.0
 Total NaN values in row 18625 :- 0 and it's percentage : 0.0
 Total NaN values in row 18626 :- 0 and it's percentage : 0.0
 Total NaN values in row 18627 :- 0 and it's percentage : 0.0
 Total NaN values in row 18628 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18629 :- 0 and it's percentage : 0.0
 Total NaN values in row 18630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18631 :- 0 and it's percentage : 0.0
 Total NaN values in row 18632 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18633 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18634 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18635 :- 0 and it's percentage : 0.0
 Total NaN values in row 18636 :- 0 and it's percentage : 0.0
 Total NaN values in row 18637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18638 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18639 :- 0 and it's percentage : 0.0
 Total NaN values in row 18640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18642 :- 0 and it's percentage : 0.0
 Total NaN values in row 18643 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 18644 :- 0 and it's percentage : 0.0
 Total NaN values in row 18645 :- 0 and it's percentage : 0.0
 Total NaN values in row 18646 :- 0 and it's percentage : 0.0
 Total NaN values in row 18647 :- 0 and it's percentage : 0.0
 Total NaN values in row 18648 :- 0 and it's percentage : 0.0
 Total NaN values in row 18649 :- 0 and it's percentage : 0.0
 Total NaN values in row 18650 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18651 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18652 :- 0 and it's percentage : 0.0
 Total NaN values in row 18653 :- 0 and it's percentage : 0.0
 Total NaN values in row 18654 :- 0 and it's percentage : 0.0
 Total NaN values in row 18655 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18656 :- 0 and it's percentage : 0.0
 Total NaN values in row 18657 :- 0 and it's percentage : 0.0
 Total NaN values in row 18658 :- 0 and it's percentage : 0.0
 Total NaN values in row 18659 :- 0 and it's percentage : 0.0
 Total NaN values in row 18660 :- 0 and it's percentage : 0.0
 Total NaN values in row 18661 :- 0 and it's percentage : 0.0
 Total NaN values in row 18662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18663 :- 0 and it's percentage : 0.0
 Total NaN values in row 18664 :- 0 and it's percentage : 0.0
 Total NaN values in row 18665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18666 :- 0 and it's percentage : 0.0
 Total NaN values in row 18667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18668 :- 0 and it's percentage : 0.0
 Total NaN values in row 18669 :- 0 and it's percentage : 0.0
 Total NaN values in row 18670 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18672 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18673 :- 0 and it's percentage : 0.0
 Total NaN values in row 18674 :- 0 and it's percentage : 0.0
 Total NaN values in row 18675 :- 4 and it's percentage : 22.22222222222222

 Total NaN values in row 18676 :- 0 and it's percentage : 0.0
 Total NaN values in row 18677 :- 0 and it's percentage : 0.0
 Total NaN values in row 18678 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18679 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18680 :- 0 and it's percentage : 0.0
 Total NaN values in row 18681 :- 0 and it's percentage : 0.0
 Total NaN values in row 18682 :- 0 and it's percentage : 0.0
 Total NaN values in row 18683 :- 0 and it's percentage : 0.0
 Total NaN values in row 18684 :- 0 and it's percentage : 0.0
 Total NaN values in row 18685 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18686 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18688 :- 0 and it's percentage : 0.0
 Total NaN values in row 18689 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18691 :- 0 and it's percentage : 0.0
 Total NaN values in row 18692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18693 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18694 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18695 :- 0 and it's percentage : 0.0
 Total NaN values in row 18696 :- 0 and it's percentage : 0.0
 Total NaN values in row 18697 :- 0 and it's percentage : 0.0
 Total NaN values in row 18698 :- 0 and it's percentage : 0.0
 Total NaN values in row 18699 :- 0 and it's percentage : 0.0
 Total NaN values in row 18700 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18701 :- 0 and it's percentage : 0.0
 Total NaN values in row 18702 :- 0 and it's percentage : 0.0
 Total NaN values in row 18703 :- 0 and it's percentage : 0.0
 Total NaN values in row 18704 :- 0 and it's percentage : 0.0
 Total NaN values in row 18705 :- 0 and it's percentage : 0.0
 Total NaN values in row 18706 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18707 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18708 :- 0 and it's percentage : 0.0
 Total NaN values in row 18709 :- 0 and it's percentage : 0.0
 Total NaN values in row 18710 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18711 :- 0 and it's percentage : 0.0
 Total NaN values in row 18712 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18713 :- 0 and it's percentage : 0.0
 Total NaN values in row 18714 :- 0 and it's percentage : 0.0
 Total NaN values in row 18715 :- 0 and it's percentage : 0.0
 Total NaN values in row 18716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18717 :- 0 and it's percentage : 0.0
 Total NaN values in row 18718 :- 0 and it's percentage : 0.0
 Total NaN values in row 18719 :- 0 and it's percentage : 0.0
 Total NaN values in row 18720 :- 0 and it's percentage : 0.0
 Total NaN values in row 18721 :- 0 and it's percentage : 0.0
 Total NaN values in row 18722 :- 0 and it's percentage : 0.0
 Total NaN values in row 18723 :- 0 and it's percentage : 0.0
 Total NaN values in row 18724 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18725 :- 0 and it's percentage : 0.0
 Total NaN values in row 18726 :- 0 and it's percentage : 0.0
 Total NaN values in row 18727 :- 0 and it's percentage : 0.0
 Total NaN values in row 18728 :- 0 and it's percentage : 0.0
 Total NaN values in row 18729 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18730 :- 0 and it's percentage : 0.0
 Total NaN values in row 18731 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18732 :- 0 and it's percentage : 0.0
 Total NaN values in row 18733 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18734 :- 0 and it's percentage : 0.0
 Total NaN values in row 18735 :- 0 and it's percentage : 0.0
 Total NaN values in row 18736 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18737 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18738 :- 0 and it's percentage : 0.0
 Total NaN values in row 18739 :- 0 and it's percentage : 0.0
 Total NaN values in row 18740 :- 0 and it's percentage : 0.0
 Total NaN values in row 18741 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18742 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18744 :- 0 and it's percentage : 0.0
 Total NaN values in row 18745 :- 0 and it's percentage : 0.0
 Total NaN values in row 18746 :- 0 and it's percentage : 0.0
 Total NaN values in row 18747 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18748 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18749 :- 0 and it's percentage : 0.0
 Total NaN values in row 18750 :- 0 and it's percentage : 0.0
 Total NaN values in row 18751 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18752 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18753 :- 0 and it's percentage : 0.0
 Total NaN values in row 18754 :- 0 and it's percentage : 0.0
 Total NaN values in row 18755 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18756 :- 0 and it's percentage : 0.0
 Total NaN values in row 18757 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18758 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18759 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18760 :- 0 and it's percentage : 0.0
 Total NaN values in row 18761 :- 0 and it's percentage : 0.0
 Total NaN values in row 18762 :- 0 and it's percentage : 0.0
 Total NaN values in row 18763 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18764 :- 0 and it's percentage : 0.0
 Total NaN values in row 18765 :- 0 and it's percentage : 0.0
 Total NaN values in row 18766 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18767 :- 0 and it's percentage : 0.0
 Total NaN values in row 18768 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18769 :- 0 and it's percentage : 0.0
 Total NaN values in row 18770 :- 0 and it's percentage : 0.0
 Total NaN values in row 18771 :- 0 and it's percentage : 0.0
 Total NaN values in row 18772 :- 0 and it's percentage : 0.0
 Total NaN values in row 18773 :- 0 and it's percentage : 0.0
 Total NaN values in row 18774 :- 0 and it's percentage : 0.0
 Total NaN values in row 18775 :- 0 and it's percentage : 0.0
 Total NaN values in row 18776 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18777 :- 0 and it's percentage : 0.0
 Total NaN values in row 18778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18779 :- 0 and it's percentage : 0.0
 Total NaN values in row 18780 :- 0 and it's percentage : 0.0
 Total NaN values in row 18781 :- 0 and it's percentage : 0.0
 Total NaN values in row 18782 :- 0 and it's percentage : 0.0
 Total NaN values in row 18783 :- 0 and it's percentage : 0.0
 Total NaN values in row 18784 :- 0 and it's percentage : 0.0
 Total NaN values in row 18785 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18786 :- 0 and it's percentage : 0.0
 Total NaN values in row 18787 :- 0 and it's percentage : 0.0
 Total NaN values in row 18788 :- 0 and it's percentage : 0.0
 Total NaN values in row 18789 :- 0 and it's percentage : 0.0
 Total NaN values in row 18790 :- 0 and it's percentage : 0.0
 Total NaN values in row 18791 :- 0 and it's percentage : 0.0
 Total NaN values in row 18792 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18793 :- 0 and it's percentage : 0.0
 Total NaN values in row 18794 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 18795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18796 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18797 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18798 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18799 :- 0 and it's percentage : 0.0
 Total NaN values in row 18800 :- 0 and it's percentage : 0.0
 Total NaN values in row 18801 :- 0 and it's percentage : 0.0
 Total NaN values in row 18802 :- 0 and it's percentage : 0.0
 Total NaN values in row 18803 :- 0 and it's percentage : 0.0
 Total NaN values in row 18804 :- 0 and it's percentage : 0.0
 Total NaN values in row 18805 :- 0 and it's percentage : 0.0
 Total NaN values in row 18806 :- 0 and it's percentage : 0.0
 Total NaN values in row 18807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18808 :- 0 and it's percentage : 0.0
 Total NaN values in row 18809 :- 0 and it's percentage : 0.0
 Total NaN values in row 18810 :- 0 and it's percentage : 0.0
 Total NaN values in row 18811 :- 0 and it's percentage : 0.0
 Total NaN values in row 18812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18813 :- 0 and it's percentage : 0.0
 Total NaN values in row 18814 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 18815 :- 0 and it's percentage : 0.0
 Total NaN values in row 18816 :- 0 and it's percentage : 0.0
 Total NaN values in row 18817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18818 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18819 :- 0 and it's percentage : 0.0
 Total NaN values in row 18820 :- 0 and it's percentage : 0.0
 Total NaN values in row 18821 :- 0 and it's percentage : 0.0
 Total NaN values in row 18822 :- 0 and it's percentage : 0.0
 Total NaN values in row 18823 :- 0 and it's percentage : 0.0
 Total NaN values in row 18824 :- 0 and it's percentage : 0.0
 Total NaN values in row 18825 :- 0 and it's percentage : 0.0
 Total NaN values in row 18826 :- 0 and it's percentage : 0.0
 Total NaN values in row 18827 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18828 :- 0 and it's percentage : 0.0
 Total NaN values in row 18829 :- 0 and it's percentage : 0.0
 Total NaN values in row 18830 :- 0 and it's percentage : 0.0
 Total NaN values in row 18831 :- 0 and it's percentage : 0.0
 Total NaN values in row 18832 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18833 :- 0 and it's percentage : 0.0
 Total NaN values in row 18834 :- 0 and it's percentage : 0.0
 Total NaN values in row 18835 :- 0 and it's percentage : 0.0
 Total NaN values in row 18836 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18837 :- 0 and it's percentage : 0.0
 Total NaN values in row 18838 :- 0 and it's percentage : 0.0
 Total NaN values in row 18839 :- 0 and it's percentage : 0.0
 Total NaN values in row 18840 :- 0 and it's percentage : 0.0
 Total NaN values in row 18841 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18843 :- 0 and it's percentage : 0.0
 Total NaN values in row 18844 :- 0 and it's percentage : 0.0
 Total NaN values in row 18845 :- 0 and it's percentage : 0.0
 Total NaN values in row 18846 :- 0 and it's percentage : 0.0
 Total NaN values in row 18847 :- 0 and it's percentage : 0.0
 Total NaN values in row 18848 :- 0 and it's percentage : 0.0
 Total NaN values in row 18849 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18850 :- 0 and it's percentage : 0.0
 Total NaN values in row 18851 :- 0 and it's percentage : 0.0
 Total NaN values in row 18852 :- 0 and it's percentage : 0.0
 Total NaN values in row 18853 :- 0 and it's percentage : 0.0
 Total NaN values in row 18854 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18855 :- 0 and it's percentage : 0.0
 Total NaN values in row 18856 :- 0 and it's percentage : 0.0
 Total NaN values in row 18857 :- 0 and it's percentage : 0.0
 Total NaN values in row 18858 :- 0 and it's percentage : 0.0
 Total NaN values in row 18859 :- 0 and it's percentage : 0.0
 Total NaN values in row 18860 :- 0 and it's percentage : 0.0
 Total NaN values in row 18861 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18862 :- 0 and it's percentage : 0.0
 Total NaN values in row 18863 :- 0 and it's percentage : 0.0
 Total NaN values in row 18864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18865 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18866 :- 0 and it's percentage : 0.0
 Total NaN values in row 18867 :- 0 and it's percentage : 0.0
 Total NaN values in row 18868 :- 0 and it's percentage : 0.0
 Total NaN values in row 18869 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18870 :- 0 and it's percentage : 0.0
 Total NaN values in row 18871 :- 0 and it's percentage : 0.0
 Total NaN values in row 18872 :- 0 and it's percentage : 0.0
 Total NaN values in row 18873 :- 0 and it's percentage : 0.0
 Total NaN values in row 18874 :- 0 and it's percentage : 0.0
 Total NaN values in row 18875 :- 0 and it's percentage : 0.0
 Total NaN values in row 18876 :- 0 and it's percentage : 0.0
 Total NaN values in row 18877 :- 0 and it's percentage : 0.0
 Total NaN values in row 18878 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 18879 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18880 :- 0 and it's percentage : 0.0
 Total NaN values in row 18881 :- 0 and it's percentage : 0.0
 Total NaN values in row 18882 :- 0 and it's percentage : 0.0
 Total NaN values in row 18883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18884 :- 0 and it's percentage : 0.0
 Total NaN values in row 18885 :- 0 and it's percentage : 0.0
 Total NaN values in row 18886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18887 :- 0 and it's percentage : 0.0
 Total NaN values in row 18888 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18889 :- 0 and it's percentage : 0.0
 Total NaN values in row 18890 :- 0 and it's percentage : 0.0
 Total NaN values in row 18891 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18892 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18893 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18894 :- 0 and it's percentage : 0.0
 Total NaN values in row 18895 :- 0 and it's percentage : 0.0
 Total NaN values in row 18896 :- 0 and it's percentage : 0.0
 Total NaN values in row 18897 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18898 :- 0 and it's percentage : 0.0
 Total NaN values in row 18899 :- 0 and it's percentage : 0.0
 Total NaN values in row 18900 :- 0 and it's percentage : 0.0
 Total NaN values in row 18901 :- 0 and it's percentage : 0.0
 Total NaN values in row 18902 :- 0 and it's percentage : 0.0
 Total NaN values in row 18903 :- 0 and it's percentage : 0.0
 Total NaN values in row 18904 :- 0 and it's percentage : 0.0
 Total NaN values in row 18905 :- 0 and it's percentage : 0.0
 Total NaN values in row 18906 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18907 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18908 :- 0 and it's percentage : 0.0
 Total NaN values in row 18909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18910 :- 0 and it's percentage : 0.0
 Total NaN values in row 18911 :- 0 and it's percentage : 0.0
 Total NaN values in row 18912 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18913 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18914 :- 0 and it's percentage : 0.0
 Total NaN values in row 18915 :- 0 and it's percentage : 0.0
 Total NaN values in row 18916 :- 0 and it's percentage : 0.0
 Total NaN values in row 18917 :- 0 and it's percentage : 0.0
 Total NaN values in row 18918 :- 0 and it's percentage : 0.0
 Total NaN values in row 18919 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18920 :- 0 and it's percentage : 0.0
 Total NaN values in row 18921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18922 :- 0 and it's percentage : 0.0
 Total NaN values in row 18923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18924 :- 0 and it's percentage : 0.0
 Total NaN values in row 18925 :- 0 and it's percentage : 0.0
 Total NaN values in row 18926 :- 0 and it's percentage : 0.0
 Total NaN values in row 18927 :- 0 and it's percentage : 0.0
 Total NaN values in row 18928 :- 0 and it's percentage : 0.0
 Total NaN values in row 18929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18930 :- 0 and it's percentage : 0.0
 Total NaN values in row 18931 :- 0 and it's percentage : 0.0
 Total NaN values in row 18932 :- 0 and it's percentage : 0.0
 Total NaN values in row 18933 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18934 :- 0 and it's percentage : 0.0
 Total NaN values in row 18935 :- 0 and it's percentage : 0.0
 Total NaN values in row 18936 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18937 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18938 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 18939 :- 0 and it's percentage : 0.0
 Total NaN values in row 18940 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18941 :- 0 and it's percentage : 0.0
 Total NaN values in row 18942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18943 :- 0 and it's percentage : 0.0
 Total NaN values in row 18944 :- 0 and it's percentage : 0.0
 Total NaN values in row 18945 :- 0 and it's percentage : 0.0
 Total NaN values in row 18946 :- 0 and it's percentage : 0.0
 Total NaN values in row 18947 :- 0 and it's percentage : 0.0
 Total NaN values in row 18948 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18949 :- 0 and it's percentage : 0.0
 Total NaN values in row 18950 :- 0 and it's percentage : 0.0
 Total NaN values in row 18951 :- 0 and it's percentage : 0.0
 Total NaN values in row 18952 :- 0 and it's percentage : 0.0
 Total NaN values in row 18953 :- 0 and it's percentage : 0.0
 Total NaN values in row 18954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18955 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18956 :- 0 and it's percentage : 0.0
 Total NaN values in row 18957 :- 0 and it's percentage : 0.0
 Total NaN values in row 18958 :- 0 and it's percentage : 0.0
 Total NaN values in row 18959 :- 0 and it's percentage : 0.0
 Total NaN values in row 18960 :- 0 and it's percentage : 0.0
 Total NaN values in row 18961 :- 0 and it's percentage : 0.0
 Total NaN values in row 18962 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18963 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18964 :- 0 and it's percentage : 0.0
 Total NaN values in row 18965 :- 0 and it's percentage : 0.0
 Total NaN values in row 18966 :- 0 and it's percentage : 0.0
 Total NaN values in row 18967 :- 0 and it's percentage : 0.0
 Total NaN values in row 18968 :- 0 and it's percentage : 0.0
 Total NaN values in row 18969 :- 0 and it's percentage : 0.0
 Total NaN values in row 18970 :- 0 and it's percentage : 0.0
 Total NaN values in row 18971 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18972 :- 0 and it's percentage : 0.0
 Total NaN values in row 18973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18974 :- 0 and it's percentage : 0.0
 Total NaN values in row 18975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18976 :- 0 and it's percentage : 0.0
 Total NaN values in row 18977 :- 0 and it's percentage : 0.0
 Total NaN values in row 18978 :- 0 and it's percentage : 0.0
 Total NaN values in row 18979 :- 0 and it's percentage : 0.0
 Total NaN values in row 18980 :- 0 and it's percentage : 0.0
 Total NaN values in row 18981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18982 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18983 :- 0 and it's percentage : 0.0
 Total NaN values in row 18984 :- 0 and it's percentage : 0.0
 Total NaN values in row 18985 :- 0 and it's percentage : 0.0
 Total NaN values in row 18986 :- 0 and it's percentage : 0.0
 Total NaN values in row 18987 :- 0 and it's percentage : 0.0
 Total NaN values in row 18988 :- 0 and it's percentage : 0.0
 Total NaN values in row 18989 :- 0 and it's percentage : 0.0
 Total NaN values in row 18990 :- 0 and it's percentage : 0.0
 Total NaN values in row 18991 :- 0 and it's percentage : 0.0
 Total NaN values in row 18992 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 18993 :- 0 and it's percentage : 0.0
 Total NaN values in row 18994 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 18995 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 18996 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 18997 :- 0 and it's percentage : 0.0
 Total NaN values in row 18998 :- 0 and it's percentage : 0.0
 Total NaN values in row 18999 :- 0 and it's percentage : 0.0
 Total NaN values in row 19000 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19001 :- 0 and it's percentage : 0.0
 Total NaN values in row 19002 :- 0 and it's percentage : 0.0
 Total NaN values in row 19003 :- 0 and it's percentage : 0.0
 Total NaN values in row 19004 :- 0 and it's percentage : 0.0
 Total NaN values in row 19005 :- 0 and it's percentage : 0.0
 Total NaN values in row 19006 :- 0 and it's percentage : 0.0
 Total NaN values in row 19007 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19008 :- 0 and it's percentage : 0.0
 Total NaN values in row 19009 :- 0 and it's percentage : 0.0
 Total NaN values in row 19010 :- 0 and it's percentage : 0.0
 Total NaN values in row 19011 :- 0 and it's percentage : 0.0
 Total NaN values in row 19012 :- 0 and it's percentage : 0.0
 Total NaN values in row 19013 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19015 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19016 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19017 :- 0 and it's percentage : 0.0
 Total NaN values in row 19018 :- 0 and it's percentage : 0.0
 Total NaN values in row 19019 :- 0 and it's percentage : 0.0
 Total NaN values in row 19020 :- 0 and it's percentage : 0.0
 Total NaN values in row 19021 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19022 :- 0 and it's percentage : 0.0
 Total NaN values in row 19023 :- 0 and it's percentage : 0.0
 Total NaN values in row 19024 :- 0 and it's percentage : 0.0
 Total NaN values in row 19025 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19026 :- 0 and it's percentage : 0.0
 Total NaN values in row 19027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19028 :- 0 and it's percentage : 0.0
 Total NaN values in row 19029 :- 0 and it's percentage : 0.0
 Total NaN values in row 19030 :- 0 and it's percentage : 0.0
 Total NaN values in row 19031 :- 0 and it's percentage : 0.0
 Total NaN values in row 19032 :- 0 and it's percentage : 0.0
 Total NaN values in row 19033 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19034 :- 0 and it's percentage : 0.0
 Total NaN values in row 19035 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19036 :- 0 and it's percentage : 0.0
 Total NaN values in row 19037 :- 0 and it's percentage : 0.0
 Total NaN values in row 19038 :- 0 and it's percentage : 0.0
 Total NaN values in row 19039 :- 0 and it's percentage : 0.0
 Total NaN values in row 19040 :- 0 and it's percentage : 0.0
 Total NaN values in row 19041 :- 0 and it's percentage : 0.0
 Total NaN values in row 19042 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19043 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19044 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19045 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19046 :- 0 and it's percentage : 0.0
 Total NaN values in row 19047 :- 0 and it's percentage : 0.0
 Total NaN values in row 19048 :- 0 and it's percentage : 0.0
 Total NaN values in row 19049 :- 0 and it's percentage : 0.0
 Total NaN values in row 19050 :- 0 and it's percentage : 0.0
 Total NaN values in row 19051 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19052 :- 0 and it's percentage : 0.0
 Total NaN values in row 19053 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19054 :- 0 and it's percentage : 0.0
 Total NaN values in row 19055 :- 0 and it's percentage : 0.0
 Total NaN values in row 19056 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19058 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19059 :- 0 and it's percentage : 0.0
 Total NaN values in row 19060 :- 0 and it's percentage : 0.0
 Total NaN values in row 19061 :- 0 and it's percentage : 0.0
 Total NaN values in row 19062 :- 0 and it's percentage : 0.0
 Total NaN values in row 19063 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19064 :- 0 and it's percentage : 0.0
 Total NaN values in row 19065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19066 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19067 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19068 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19070 :- 0 and it's percentage : 0.0
 Total NaN values in row 19071 :- 0 and it's percentage : 0.0
 Total NaN values in row 19072 :- 0 and it's percentage : 0.0

 Total NaN values in row 19073 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19074 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19075 :- 0 and it's percentage : 0.0
 Total NaN values in row 19076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19077 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19078 :- 0 and it's percentage : 0.0
 Total NaN values in row 19079 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19080 :- 0 and it's percentage : 0.0
 Total NaN values in row 19081 :- 0 and it's percentage : 0.0
 Total NaN values in row 19082 :- 0 and it's percentage : 0.0
 Total NaN values in row 19083 :- 0 and it's percentage : 0.0
 Total NaN values in row 19084 :- 0 and it's percentage : 0.0
 Total NaN values in row 19085 :- 0 and it's percentage : 0.0
 Total NaN values in row 19086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19087 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19088 :- 0 and it's percentage : 0.0
 Total NaN values in row 19089 :- 0 and it's percentage : 0.0
 Total NaN values in row 19090 :- 0 and it's percentage : 0.0
 Total NaN values in row 19091 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19093 :- 0 and it's percentage : 0.0
 Total NaN values in row 19094 :- 0 and it's percentage : 0.0
 Total NaN values in row 19095 :- 0 and it's percentage : 0.0
 Total NaN values in row 19096 :- 0 and it's percentage : 0.0
 Total NaN values in row 19097 :- 0 and it's percentage : 0.0
 Total NaN values in row 19098 :- 0 and it's percentage : 0.0
 Total NaN values in row 19099 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19100 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19101 :- 0 and it's percentage : 0.0
 Total NaN values in row 19102 :- 0 and it's percentage : 0.0
 Total NaN values in row 19103 :- 0 and it's percentage : 0.0
 Total NaN values in row 19104 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19105 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19107 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19108 :- 0 and it's percentage : 0.0
 Total NaN values in row 19109 :- 0 and it's percentage : 0.0
 Total NaN values in row 19110 :- 0 and it's percentage : 0.0
 Total NaN values in row 19111 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19112 :- 0 and it's percentage : 0.0
 Total NaN values in row 19113 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19114 :- 0 and it's percentage : 0.0
 Total NaN values in row 19115 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19116 :- 0 and it's percentage : 0.0
 Total NaN values in row 19117 :- 0 and it's percentage : 0.0
 Total NaN values in row 19118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19119 :- 0 and it's percentage : 0.0
 Total NaN values in row 19120 :- 0 and it's percentage : 0.0
 Total NaN values in row 19121 :- 0 and it's percentage : 0.0
 Total NaN values in row 19122 :- 0 and it's percentage : 0.0
 Total NaN values in row 19123 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19124 :- 0 and it's percentage : 0.0
 Total NaN values in row 19125 :- 0 and it's percentage : 0.0
 Total NaN values in row 19126 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19127 :- 0 and it's percentage : 0.0
 Total NaN values in row 19128 :- 0 and it's percentage : 0.0
 Total NaN values in row 19129 :- 0 and it's percentage : 0.0
 Total NaN values in row 19130 :- 0 and it's percentage : 0.0
 Total NaN values in row 19131 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19132 :- 0 and it's percentage : 0.0
 Total NaN values in row 19133 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19134 :- 0 and it's percentage : 0.0
 Total NaN values in row 19135 :- 0 and it's percentage : 0.0
 Total NaN values in row 19136 :- 0 and it's percentage : 0.0
 Total NaN values in row 19137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19138 :- 0 and it's percentage : 0.0
 Total NaN values in row 19139 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19140 :- 0 and it's percentage : 0.0
 Total NaN values in row 19141 :- 0 and it's percentage : 0.0
 Total NaN values in row 19142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19143 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19144 :- 0 and it's percentage : 0.0
 Total NaN values in row 19145 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19146 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19147 :- 0 and it's percentage : 0.0
 Total NaN values in row 19148 :- 0 and it's percentage : 0.0
 Total NaN values in row 19149 :- 0 and it's percentage : 0.0
 Total NaN values in row 19150 :- 0 and it's percentage : 0.0
 Total NaN values in row 19151 :- 0 and it's percentage : 0.0
 Total NaN values in row 19152 :- 0 and it's percentage : 0.0
 Total NaN values in row 19153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19154 :- 0 and it's percentage : 0.0
 Total NaN values in row 19155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19156 :- 0 and it's percentage : 0.0
 Total NaN values in row 19157 :- 0 and it's percentage : 0.0
 Total NaN values in row 19158 :- 0 and it's percentage : 0.0
 Total NaN values in row 19159 :- 0 and it's percentage : 0.0
 Total NaN values in row 19160 :- 0 and it's percentage : 0.0
 Total NaN values in row 19161 :- 0 and it's percentage : 0.0
 Total NaN values in row 19162 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19163 :- 0 and it's percentage : 0.0
 Total NaN values in row 19164 :- 0 and it's percentage : 0.0
 Total NaN values in row 19165 :- 0 and it's percentage : 0.0
 Total NaN values in row 19166 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19168 :- 0 and it's percentage : 0.0
 Total NaN values in row 19169 :- 0 and it's percentage : 0.0
 Total NaN values in row 19170 :- 0 and it's percentage : 0.0
 Total NaN values in row 19171 :- 0 and it's percentage : 0.0
 Total NaN values in row 19172 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19173 :- 0 and it's percentage : 0.0
 Total NaN values in row 19174 :- 0 and it's percentage : 0.0
 Total NaN values in row 19175 :- 0 and it's percentage : 0.0
 Total NaN values in row 19176 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19177 :- 0 and it's percentage : 0.0
 Total NaN values in row 19178 :- 0 and it's percentage : 0.0
 Total NaN values in row 19179 :- 0 and it's percentage : 0.0
 Total NaN values in row 19180 :- 0 and it's percentage : 0.0
 Total NaN values in row 19181 :- 0 and it's percentage : 0.0
 Total NaN values in row 19182 :- 0 and it's percentage : 0.0
 Total NaN values in row 19183 :- 0 and it's percentage : 0.0
 Total NaN values in row 19184 :- 0 and it's percentage : 0.0
 Total NaN values in row 19185 :- 0 and it's percentage : 0.0
 Total NaN values in row 19186 :- 0 and it's percentage : 0.0
 Total NaN values in row 19187 :- 0 and it's percentage : 0.0
 Total NaN values in row 19188 :- 0 and it's percentage : 0.0
 Total NaN values in row 19189 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19190 :- 0 and it's percentage : 0.0
 Total NaN values in row 19191 :- 0 and it's percentage : 0.0
 Total NaN values in row 19192 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19193 :- 0 and it's percentage : 0.0
 Total NaN values in row 19194 :- 0 and it's percentage : 0.0
 Total NaN values in row 19195 :- 0 and it's percentage : 0.0
 Total NaN values in row 19196 :- 0 and it's percentage : 0.0
 Total NaN values in row 19197 :- 0 and it's percentage : 0.0
 Total NaN values in row 19198 :- 0 and it's percentage : 0.0
 Total NaN values in row 19199 :- 0 and it's percentage : 0.0
 Total NaN values in row 19200 :- 0 and it's percentage : 0.0
 Total NaN values in row 19201 :- 0 and it's percentage : 0.0
 Total NaN values in row 19202 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19203 :- 0 and it's percentage : 0.0
 Total NaN values in row 19204 :- 0 and it's percentage : 0.0

 Total NaN values in row 19205 :- 0 and it's percentage : 0.0
 Total NaN values in row 19206 :- 0 and it's percentage : 0.0
 Total NaN values in row 19207 :- 0 and it's percentage : 0.0
 Total NaN values in row 19208 :- 0 and it's percentage : 0.0
 Total NaN values in row 19209 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19210 :- 0 and it's percentage : 0.0
 Total NaN values in row 19211 :- 0 and it's percentage : 0.0
 Total NaN values in row 19212 :- 0 and it's percentage : 0.0
 Total NaN values in row 19213 :- 0 and it's percentage : 0.0
 Total NaN values in row 19214 :- 0 and it's percentage : 0.0
 Total NaN values in row 19215 :- 0 and it's percentage : 0.0
 Total NaN values in row 19216 :- 0 and it's percentage : 0.0
 Total NaN values in row 19217 :- 0 and it's percentage : 0.0
 Total NaN values in row 19218 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19220 :- 0 and it's percentage : 0.0
 Total NaN values in row 19221 :- 0 and it's percentage : 0.0
 Total NaN values in row 19222 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19223 :- 0 and it's percentage : 0.0
 Total NaN values in row 19224 :- 0 and it's percentage : 0.0
 Total NaN values in row 19225 :- 0 and it's percentage : 0.0
 Total NaN values in row 19226 :- 0 and it's percentage : 0.0
 Total NaN values in row 19227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19228 :- 0 and it's percentage : 0.0
 Total NaN values in row 19229 :- 0 and it's percentage : 0.0
 Total NaN values in row 19230 :- 0 and it's percentage : 0.0
 Total NaN values in row 19231 :- 0 and it's percentage : 0.0
 Total NaN values in row 19232 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19233 :- 0 and it's percentage : 0.0
 Total NaN values in row 19234 :- 0 and it's percentage : 0.0
 Total NaN values in row 19235 :- 0 and it's percentage : 0.0
 Total NaN values in row 19236 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19237 :- 0 and it's percentage : 0.0
 Total NaN values in row 19238 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19239 :- 0 and it's percentage : 0.0
 Total NaN values in row 19240 :- 0 and it's percentage : 0.0
 Total NaN values in row 19241 :- 0 and it's percentage : 0.0
 Total NaN values in row 19242 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19243 :- 0 and it's percentage : 0.0
 Total NaN values in row 19244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19245 :- 0 and it's percentage : 0.0
 Total NaN values in row 19246 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19248 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19249 :- 0 and it's percentage : 0.0
 Total NaN values in row 19250 :- 0 and it's percentage : 0.0
 Total NaN values in row 19251 :- 0 and it's percentage : 0.0
 Total NaN values in row 19252 :- 0 and it's percentage : 0.0
 Total NaN values in row 19253 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19254 :- 0 and it's percentage : 0.0
 Total NaN values in row 19255 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19256 :- 0 and it's percentage : 0.0
 Total NaN values in row 19257 :- 0 and it's percentage : 0.0
 Total NaN values in row 19258 :- 0 and it's percentage : 0.0
 Total NaN values in row 19259 :- 0 and it's percentage : 0.0
 Total NaN values in row 19260 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19261 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19262 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19263 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19264 :- 0 and it's percentage : 0.0
 Total NaN values in row 19265 :- 0 and it's percentage : 0.0
 Total NaN values in row 19266 :- 0 and it's percentage : 0.0
 Total NaN values in row 19267 :- 0 and it's percentage : 0.0
 Total NaN values in row 19268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19270 :- 0 and it's percentage : 0.0
 Total NaN values in row 19271 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19272 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19273 :- 0 and it's percentage : 0.0
 Total NaN values in row 19274 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19275 :- 0 and it's percentage : 0.0
 Total NaN values in row 19276 :- 0 and it's percentage : 0.0
 Total NaN values in row 19277 :- 0 and it's percentage : 0.0
 Total NaN values in row 19278 :- 0 and it's percentage : 0.0
 Total NaN values in row 19279 :- 0 and it's percentage : 0.0
 Total NaN values in row 19280 :- 0 and it's percentage : 0.0
 Total NaN values in row 19281 :- 0 and it's percentage : 0.0
 Total NaN values in row 19282 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19283 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19285 :- 0 and it's percentage : 0.0
 Total NaN values in row 19286 :- 0 and it's percentage : 0.0
 Total NaN values in row 19287 :- 0 and it's percentage : 0.0
 Total NaN values in row 19288 :- 0 and it's percentage : 0.0
 Total NaN values in row 19289 :- 0 and it's percentage : 0.0
 Total NaN values in row 19290 :- 0 and it's percentage : 0.0
 Total NaN values in row 19291 :- 0 and it's percentage : 0.0
 Total NaN values in row 19292 :- 0 and it's percentage : 0.0
 Total NaN values in row 19293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19294 :- 0 and it's percentage : 0.0
 Total NaN values in row 19295 :- 0 and it's percentage : 0.0
 Total NaN values in row 19296 :- 0 and it's percentage : 0.0
 Total NaN values in row 19297 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19298 :- 0 and it's percentage : 0.0
 Total NaN values in row 19299 :- 0 and it's percentage : 0.0
 Total NaN values in row 19300 :- 0 and it's percentage : 0.0
 Total NaN values in row 19301 :- 0 and it's percentage : 0.0
 Total NaN values in row 19302 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19303 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19304 :- 0 and it's percentage : 0.0
 Total NaN values in row 19305 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19306 :- 0 and it's percentage : 0.0
 Total NaN values in row 19307 :- 0 and it's percentage : 0.0
 Total NaN values in row 19308 :- 0 and it's percentage : 0.0
 Total NaN values in row 19309 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19310 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19311 :- 0 and it's percentage : 0.0
 Total NaN values in row 19312 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19313 :- 0 and it's percentage : 0.0
 Total NaN values in row 19314 :- 0 and it's percentage : 0.0
 Total NaN values in row 19315 :- 0 and it's percentage : 0.0
 Total NaN values in row 19316 :- 0 and it's percentage : 0.0
 Total NaN values in row 19317 :- 0 and it's percentage : 0.0
 Total NaN values in row 19318 :- 0 and it's percentage : 0.0
 Total NaN values in row 19319 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19320 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19321 :- 0 and it's percentage : 0.0
 Total NaN values in row 19322 :- 0 and it's percentage : 0.0
 Total NaN values in row 19323 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19324 :- 0 and it's percentage : 0.0
 Total NaN values in row 19325 :- 0 and it's percentage : 0.0
 Total NaN values in row 19326 :- 0 and it's percentage : 0.0
 Total NaN values in row 19327 :- 0 and it's percentage : 0.0
 Total NaN values in row 19328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19329 :- 0 and it's percentage : 0.0
 Total NaN values in row 19330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19331 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19333 :- 0 and it's percentage : 0.0
 Total NaN values in row 19334 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19336 :- 0 and it's percentage : 0.0
 Total NaN values in row 19337 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19338 :- 0 and it's percentage : 0.0
 Total NaN values in row 19339 :- 0 and it's percentage : 0.0
 Total NaN values in row 19340 :- 0 and it's percentage : 0.0
 Total NaN values in row 19341 :- 0 and it's percentage : 0.0
 Total NaN values in row 19342 :- 0 and it's percentage : 0.0
 Total NaN values in row 19343 :- 0 and it's percentage : 0.0
 Total NaN values in row 19344 :- 0 and it's percentage : 0.0
 Total NaN values in row 19345 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19346 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19347 :- 0 and it's percentage : 0.0
 Total NaN values in row 19348 :- 0 and it's percentage : 0.0
 Total NaN values in row 19349 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19350 :- 0 and it's percentage : 0.0
 Total NaN values in row 19351 :- 0 and it's percentage : 0.0
 Total NaN values in row 19352 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 19353 :- 0 and it's percentage : 0.0
 Total NaN values in row 19354 :- 0 and it's percentage : 0.0
 Total NaN values in row 19355 :- 0 and it's percentage : 0.0
 Total NaN values in row 19356 :- 0 and it's percentage : 0.0
 Total NaN values in row 19357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19358 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19359 :- 0 and it's percentage : 0.0
 Total NaN values in row 19360 :- 0 and it's percentage : 0.0
 Total NaN values in row 19361 :- 0 and it's percentage : 0.0
 Total NaN values in row 19362 :- 0 and it's percentage : 0.0
 Total NaN values in row 19363 :- 0 and it's percentage : 0.0
 Total NaN values in row 19364 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19365 :- 0 and it's percentage : 0.0
 Total NaN values in row 19366 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19367 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19368 :- 0 and it's percentage : 0.0
 Total NaN values in row 19369 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19370 :- 0 and it's percentage : 0.0
 Total NaN values in row 19371 :- 0 and it's percentage : 0.0
 Total NaN values in row 19372 :- 0 and it's percentage : 0.0
 Total NaN values in row 19373 :- 0 and it's percentage : 0.0
 Total NaN values in row 19374 :- 0 and it's percentage : 0.0
 Total NaN values in row 19375 :- 0 and it's percentage : 0.0
 Total NaN values in row 19376 :- 0 and it's percentage : 0.0
 Total NaN values in row 19377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19378 :- 0 and it's percentage : 0.0
 Total NaN values in row 19379 :- 0 and it's percentage : 0.0
 Total NaN values in row 19380 :- 0 and it's percentage : 0.0
 Total NaN values in row 19381 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19382 :- 0 and it's percentage : 0.0
 Total NaN values in row 19383 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19384 :- 0 and it's percentage : 0.0
 Total NaN values in row 19385 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19386 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19387 :- 0 and it's percentage : 0.0
 Total NaN values in row 19388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19389 :- 0 and it's percentage : 0.0
 Total NaN values in row 19390 :- 0 and it's percentage : 0.0
 Total NaN values in row 19391 :- 0 and it's percentage : 0.0
 Total NaN values in row 19392 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19393 :- 0 and it's percentage : 0.0
 Total NaN values in row 19394 :- 0 and it's percentage : 0.0
 Total NaN values in row 19395 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19396 :- 0 and it's percentage : 0.0
 Total NaN values in row 19397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19398 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 19399 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19401 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19402 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19403 :- 0 and it's percentage : 0.0
 Total NaN values in row 19404 :- 0 and it's percentage : 0.0
 Total NaN values in row 19405 :- 0 and it's percentage : 0.0
 Total NaN values in row 19406 :- 0 and it's percentage : 0.0
 Total NaN values in row 19407 :- 0 and it's percentage : 0.0
 Total NaN values in row 19408 :- 0 and it's percentage : 0.0
 Total NaN values in row 19409 :- 0 and it's percentage : 0.0
 Total NaN values in row 19410 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19411 :- 0 and it's percentage : 0.0
 Total NaN values in row 19412 :- 0 and it's percentage : 0.0
 Total NaN values in row 19413 :- 0 and it's percentage : 0.0
 Total NaN values in row 19414 :- 0 and it's percentage : 0.0
 Total NaN values in row 19415 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19416 :- 0 and it's percentage : 0.0
 Total NaN values in row 19417 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19418 :- 0 and it's percentage : 0.0
 Total NaN values in row 19419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19420 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19421 :- 0 and it's percentage : 0.0
 Total NaN values in row 19422 :- 0 and it's percentage : 0.0
 Total NaN values in row 19423 :- 0 and it's percentage : 0.0
 Total NaN values in row 19424 :- 0 and it's percentage : 0.0
 Total NaN values in row 19425 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19426 :- 0 and it's percentage : 0.0
 Total NaN values in row 19427 :- 0 and it's percentage : 0.0
 Total NaN values in row 19428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19429 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19431 :- 0 and it's percentage : 0.0
 Total NaN values in row 19432 :- 0 and it's percentage : 0.0
 Total NaN values in row 19433 :- 0 and it's percentage : 0.0
 Total NaN values in row 19434 :- 0 and it's percentage : 0.0
 Total NaN values in row 19435 :- 0 and it's percentage : 0.0
 Total NaN values in row 19436 :- 0 and it's percentage : 0.0
 Total NaN values in row 19437 :- 0 and it's percentage : 0.0
 Total NaN values in row 19438 :- 0 and it's percentage : 0.0
 Total NaN values in row 19439 :- 0 and it's percentage : 0.0
 Total NaN values in row 19440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19441 :- 0 and it's percentage : 0.0
 Total NaN values in row 19442 :- 0 and it's percentage : 0.0
 Total NaN values in row 19443 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19444 :- 0 and it's percentage : 0.0
 Total NaN values in row 19445 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19446 :- 0 and it's percentage : 0.0
 Total NaN values in row 19447 :- 0 and it's percentage : 0.0
 Total NaN values in row 19448 :- 0 and it's percentage : 0.0
 Total NaN values in row 19449 :- 0 and it's percentage : 0.0
 Total NaN values in row 19450 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19451 :- 0 and it's percentage : 0.0
 Total NaN values in row 19452 :- 0 and it's percentage : 0.0
 Total NaN values in row 19453 :- 0 and it's percentage : 0.0
 Total NaN values in row 19454 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19455 :- 0 and it's percentage : 0.0
 Total NaN values in row 19456 :- 0 and it's percentage : 0.0
 Total NaN values in row 19457 :- 0 and it's percentage : 0.0
 Total NaN values in row 19458 :- 0 and it's percentage : 0.0
 Total NaN values in row 19459 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19460 :- 0 and it's percentage : 0.0
 Total NaN values in row 19461 :- 0 and it's percentage : 0.0
 Total NaN values in row 19462 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19463 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19464 :- 0 and it's percentage : 0.0
 Total NaN values in row 19465 :- 0 and it's percentage : 0.0
 Total NaN values in row 19466 :- 0 and it's percentage : 0.0
 Total NaN values in row 19467 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19468 :- 0 and it's percentage : 0.0
 Total NaN values in row 19469 :- 0 and it's percentage : 0.0
 Total NaN values in row 19470 :- 0 and it's percentage : 0.0
 Total NaN values in row 19471 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19474 :- 0 and it's percentage : 0.0
 Total NaN values in row 19475 :- 0 and it's percentage : 0.0
 Total NaN values in row 19476 :- 0 and it's percentage : 0.0
 Total NaN values in row 19477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19478 :- 0 and it's percentage : 0.0

 Total NaN values in row 19479 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19480 :- 0 and it's percentage : 0.0
 Total NaN values in row 19481 :- 0 and it's percentage : 0.0
 Total NaN values in row 19482 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19483 :- 0 and it's percentage : 0.0
 Total NaN values in row 19484 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19485 :- 0 and it's percentage : 0.0
 Total NaN values in row 19486 :- 0 and it's percentage : 0.0
 Total NaN values in row 19487 :- 0 and it's percentage : 0.0
 Total NaN values in row 19488 :- 0 and it's percentage : 0.0
 Total NaN values in row 19489 :- 0 and it's percentage : 0.0
 Total NaN values in row 19490 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19491 :- 0 and it's percentage : 0.0
 Total NaN values in row 19492 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19493 :- 0 and it's percentage : 0.0
 Total NaN values in row 19494 :- 0 and it's percentage : 0.0
 Total NaN values in row 19495 :- 0 and it's percentage : 0.0
 Total NaN values in row 19496 :- 0 and it's percentage : 0.0
 Total NaN values in row 19497 :- 0 and it's percentage : 0.0
 Total NaN values in row 19498 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19499 :- 0 and it's percentage : 0.0
 Total NaN values in row 19500 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19501 :- 0 and it's percentage : 0.0
 Total NaN values in row 19502 :- 0 and it's percentage : 0.0
 Total NaN values in row 19503 :- 0 and it's percentage : 0.0
 Total NaN values in row 19504 :- 0 and it's percentage : 0.0
 Total NaN values in row 19505 :- 0 and it's percentage : 0.0
 Total NaN values in row 19506 :- 0 and it's percentage : 0.0
 Total NaN values in row 19507 :- 0 and it's percentage : 0.0
 Total NaN values in row 19508 :- 0 and it's percentage : 0.0
 Total NaN values in row 19509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19510 :- 0 and it's percentage : 0.0
 Total NaN values in row 19511 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19513 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19514 :- 0 and it's percentage : 0.0
 Total NaN values in row 19515 :- 0 and it's percentage : 0.0
 Total NaN values in row 19516 :- 0 and it's percentage : 0.0
 Total NaN values in row 19517 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19518 :- 0 and it's percentage : 0.0
 Total NaN values in row 19519 :- 0 and it's percentage : 0.0
 Total NaN values in row 19520 :- 0 and it's percentage : 0.0
 Total NaN values in row 19521 :- 0 and it's percentage : 0.0
 Total NaN values in row 19522 :- 0 and it's percentage : 0.0
 Total NaN values in row 19523 :- 0 and it's percentage : 0.0
 Total NaN values in row 19524 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19525 :- 0 and it's percentage : 0.0
 Total NaN values in row 19526 :- 0 and it's percentage : 0.0
 Total NaN values in row 19527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19528 :- 0 and it's percentage : 0.0
 Total NaN values in row 19529 :- 0 and it's percentage : 0.0
 Total NaN values in row 19530 :- 0 and it's percentage : 0.0
 Total NaN values in row 19531 :- 0 and it's percentage : 0.0
 Total NaN values in row 19532 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19533 :- 0 and it's percentage : 0.0
 Total NaN values in row 19534 :- 0 and it's percentage : 0.0
 Total NaN values in row 19535 :- 0 and it's percentage : 0.0
 Total NaN values in row 19536 :- 0 and it's percentage : 0.0
 Total NaN values in row 19537 :- 0 and it's percentage : 0.0
 Total NaN values in row 19538 :- 0 and it's percentage : 0.0
 Total NaN values in row 19539 :- 0 and it's percentage : 0.0
 Total NaN values in row 19540 :- 0 and it's percentage : 0.0
 Total NaN values in row 19541 :- 0 and it's percentage : 0.0
 Total NaN values in row 19542 :- 0 and it's percentage : 0.0
 Total NaN values in row 19543 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19544 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19545 :- 0 and it's percentage : 0.0
 Total NaN values in row 19546 :- 0 and it's percentage : 0.0
 Total NaN values in row 19547 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19549 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19550 :- 0 and it's percentage : 0.0
 Total NaN values in row 19551 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19552 :- 0 and it's percentage : 0.0
 Total NaN values in row 19553 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19554 :- 0 and it's percentage : 0.0
 Total NaN values in row 19555 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19556 :- 0 and it's percentage : 0.0
 Total NaN values in row 19557 :- 0 and it's percentage : 0.0
 Total NaN values in row 19558 :- 0 and it's percentage : 0.0
 Total NaN values in row 19559 :- 0 and it's percentage : 0.0
 Total NaN values in row 19560 :- 0 and it's percentage : 0.0
 Total NaN values in row 19561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19562 :- 0 and it's percentage : 0.0
 Total NaN values in row 19563 :- 0 and it's percentage : 0.0
 Total NaN values in row 19564 :- 0 and it's percentage : 0.0
 Total NaN values in row 19565 :- 0 and it's percentage : 0.0
 Total NaN values in row 19566 :- 0 and it's percentage : 0.0
 Total NaN values in row 19567 :- 0 and it's percentage : 0.0
 Total NaN values in row 19568 :- 0 and it's percentage : 0.0
 Total NaN values in row 19569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19570 :- 0 and it's percentage : 0.0
 Total NaN values in row 19571 :- 0 and it's percentage : 0.0
 Total NaN values in row 19572 :- 0 and it's percentage : 0.0
 Total NaN values in row 19573 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19574 :- 0 and it's percentage : 0.0
 Total NaN values in row 19575 :- 0 and it's percentage : 0.0
 Total NaN values in row 19576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19577 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19578 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19580 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19581 :- 0 and it's percentage : 0.0
 Total NaN values in row 19582 :- 0 and it's percentage : 0.0
 Total NaN values in row 19583 :- 0 and it's percentage : 0.0
 Total NaN values in row 19584 :- 0 and it's percentage : 0.0
 Total NaN values in row 19585 :- 0 and it's percentage : 0.0
 Total NaN values in row 19586 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19587 :- 0 and it's percentage : 0.0
 Total NaN values in row 19588 :- 0 and it's percentage : 0.0
 Total NaN values in row 19589 :- 0 and it's percentage : 0.0
 Total NaN values in row 19590 :- 0 and it's percentage : 0.0
 Total NaN values in row 19591 :- 0 and it's percentage : 0.0
 Total NaN values in row 19592 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19593 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19594 :- 0 and it's percentage : 0.0
 Total NaN values in row 19595 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19596 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19597 :- 0 and it's percentage : 0.0
 Total NaN values in row 19598 :- 0 and it's percentage : 0.0
 Total NaN values in row 19599 :- 0 and it's percentage : 0.0
 Total NaN values in row 19600 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19601 :- 0 and it's percentage : 0.0
 Total NaN values in row 19602 :- 0 and it's percentage : 0.0
 Total NaN values in row 19603 :- 0 and it's percentage : 0.0
 Total NaN values in row 19604 :- 0 and it's percentage : 0.0
 Total NaN values in row 19605 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19606 :- 0 and it's percentage : 0.0
 Total NaN values in row 19607 :- 0 and it's percentage : 0.0
 Total NaN values in row 19608 :- 0 and it's percentage : 0.0
 Total NaN values in row 19609 :- 0 and it's percentage : 0.0
 Total NaN values in row 19610 :- 0 and it's percentage : 0.0
 Total NaN values in row 19611 :- 0 and it's percentage : 0.0
 Total NaN values in row 19612 :- 0 and it's percentage : 0.0
 Total NaN values in row 19613 :- 0 and it's percentage : 0.0
 Total NaN values in row 19614 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19615 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19616 :- 0 and it's percentage : 0.0
 Total NaN values in row 19617 :- 0 and it's percentage : 0.0
 Total NaN values in row 19618 :- 0 and it's percentage : 0.0
 Total NaN values in row 19619 :- 0 and it's percentage : 0.0
 Total NaN values in row 19620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19621 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19622 :- 0 and it's percentage : 0.0
 Total NaN values in row 19623 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19624 :- 0 and it's percentage : 0.0

 Total NaN values in row 19625 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19626 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19627 :- 0 and it's percentage : 0.0
 Total NaN values in row 19628 :- 0 and it's percentage : 0.0
 Total NaN values in row 19629 :- 0 and it's percentage : 0.0
 Total NaN values in row 19630 :- 0 and it's percentage : 0.0
 Total NaN values in row 19631 :- 0 and it's percentage : 0.0
 Total NaN values in row 19632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19633 :- 0 and it's percentage : 0.0
 Total NaN values in row 19634 :- 0 and it's percentage : 0.0
 Total NaN values in row 19635 :- 0 and it's percentage : 0.0
 Total NaN values in row 19636 :- 0 and it's percentage : 0.0
 Total NaN values in row 19637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19638 :- 0 and it's percentage : 0.0
 Total NaN values in row 19639 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19640 :- 0 and it's percentage : 0.0
 Total NaN values in row 19641 :- 0 and it's percentage : 0.0
 Total NaN values in row 19642 :- 0 and it's percentage : 0.0
 Total NaN values in row 19643 :- 0 and it's percentage : 0.0
 Total NaN values in row 19644 :- 0 and it's percentage : 0.0
 Total NaN values in row 19645 :- 0 and it's percentage : 0.0
 Total NaN values in row 19646 :- 0 and it's percentage : 0.0
 Total NaN values in row 19647 :- 0 and it's percentage : 0.0
 Total NaN values in row 19648 :- 0 and it's percentage : 0.0
 Total NaN values in row 19649 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19650 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19651 :- 0 and it's percentage : 0.0
 Total NaN values in row 19652 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19653 :- 0 and it's percentage : 0.0
 Total NaN values in row 19654 :- 0 and it's percentage : 0.0
 Total NaN values in row 19655 :- 0 and it's percentage : 0.0
 Total NaN values in row 19656 :- 0 and it's percentage : 0.0
 Total NaN values in row 19657 :- 0 and it's percentage : 0.0
 Total NaN values in row 19658 :- 0 and it's percentage : 0.0
 Total NaN values in row 19659 :- 0 and it's percentage : 0.0
 Total NaN values in row 19660 :- 0 and it's percentage : 0.0
 Total NaN values in row 19661 :- 0 and it's percentage : 0.0
 Total NaN values in row 19662 :- 0 and it's percentage : 0.0
 Total NaN values in row 19663 :- 0 and it's percentage : 0.0
 Total NaN values in row 19664 :- 0 and it's percentage : 0.0
 Total NaN values in row 19665 :- 0 and it's percentage : 0.0
 Total NaN values in row 19666 :- 0 and it's percentage : 0.0
 Total NaN values in row 19667 :- 0 and it's percentage : 0.0
 Total NaN values in row 19668 :- 0 and it's percentage : 0.0
 Total NaN values in row 19669 :- 0 and it's percentage : 0.0
 Total NaN values in row 19670 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19671 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19673 :- 0 and it's percentage : 0.0
 Total NaN values in row 19674 :- 0 and it's percentage : 0.0
 Total NaN values in row 19675 :- 0 and it's percentage : 0.0
 Total NaN values in row 19676 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19677 :- 0 and it's percentage : 0.0
 Total NaN values in row 19678 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19679 :- 0 and it's percentage : 0.0
 Total NaN values in row 19680 :- 0 and it's percentage : 0.0
 Total NaN values in row 19681 :- 0 and it's percentage : 0.0
 Total NaN values in row 19682 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19684 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19685 :- 0 and it's percentage : 0.0
 Total NaN values in row 19686 :- 0 and it's percentage : 0.0
 Total NaN values in row 19687 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19688 :- 0 and it's percentage : 0.0
 Total NaN values in row 19689 :- 0 and it's percentage : 0.0
 Total NaN values in row 19690 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19691 :- 0 and it's percentage : 0.0
 Total NaN values in row 19692 :- 0 and it's percentage : 0.0
 Total NaN values in row 19693 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19694 :- 0 and it's percentage : 0.0
 Total NaN values in row 19695 :- 0 and it's percentage : 0.0
 Total NaN values in row 19696 :- 0 and it's percentage : 0.0
 Total NaN values in row 19697 :- 0 and it's percentage : 0.0
 Total NaN values in row 19698 :- 0 and it's percentage : 0.0
 Total NaN values in row 19699 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19700 :- 0 and it's percentage : 0.0
 Total NaN values in row 19701 :- 0 and it's percentage : 0.0
 Total NaN values in row 19702 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19703 :- 0 and it's percentage : 0.0
 Total NaN values in row 19704 :- 0 and it's percentage : 0.0
 Total NaN values in row 19705 :- 0 and it's percentage : 0.0
 Total NaN values in row 19706 :- 0 and it's percentage : 0.0
 Total NaN values in row 19707 :- 0 and it's percentage : 0.0
 Total NaN values in row 19708 :- 0 and it's percentage : 0.0
 Total NaN values in row 19709 :- 0 and it's percentage : 0.0
 Total NaN values in row 19710 :- 0 and it's percentage : 0.0
 Total NaN values in row 19711 :- 0 and it's percentage : 0.0
 Total NaN values in row 19712 :- 0 and it's percentage : 0.0
 Total NaN values in row 19713 :- 0 and it's percentage : 0.0
 Total NaN values in row 19714 :- 0 and it's percentage : 0.0
 Total NaN values in row 19715 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19716 :- 0 and it's percentage : 0.0
 Total NaN values in row 19717 :- 0 and it's percentage : 0.0
 Total NaN values in row 19718 :- 0 and it's percentage : 0.0
 Total NaN values in row 19719 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19720 :- 0 and it's percentage : 0.0
 Total NaN values in row 19721 :- 0 and it's percentage : 0.0
 Total NaN values in row 19722 :- 0 and it's percentage : 0.0
 Total NaN values in row 19723 :- 0 and it's percentage : 0.0
 Total NaN values in row 19724 :- 0 and it's percentage : 0.0
 Total NaN values in row 19725 :- 0 and it's percentage : 0.0
 Total NaN values in row 19726 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19727 :- 0 and it's percentage : 0.0
 Total NaN values in row 19728 :- 0 and it's percentage : 0.0
 Total NaN values in row 19729 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19730 :- 0 and it's percentage : 0.0
 Total NaN values in row 19731 :- 0 and it's percentage : 0.0
 Total NaN values in row 19732 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19733 :- 0 and it's percentage : 0.0
 Total NaN values in row 19734 :- 0 and it's percentage : 0.0
 Total NaN values in row 19735 :- 0 and it's percentage : 0.0
 Total NaN values in row 19736 :- 0 and it's percentage : 0.0
 Total NaN values in row 19737 :- 0 and it's percentage : 0.0
 Total NaN values in row 19738 :- 0 and it's percentage : 0.0
 Total NaN values in row 19739 :- 0 and it's percentage : 0.0
 Total NaN values in row 19740 :- 0 and it's percentage : 0.0
 Total NaN values in row 19741 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19742 :- 0 and it's percentage : 0.0
 Total NaN values in row 19743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19744 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19745 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19746 :- 0 and it's percentage : 0.0
 Total NaN values in row 19747 :- 0 and it's percentage : 0.0
 Total NaN values in row 19748 :- 0 and it's percentage : 0.0
 Total NaN values in row 19749 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 19750 :- 0 and it's percentage : 0.0
 Total NaN values in row 19751 :- 0 and it's percentage : 0.0
 Total NaN values in row 19752 :- 0 and it's percentage : 0.0
 Total NaN values in row 19753 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19754 :- 0 and it's percentage : 0.0
 Total NaN values in row 19755 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19756 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19757 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19758 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19759 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19762 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19763 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19764 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19765 :- 0 and it's percentage : 0.0
 Total NaN values in row 19766 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19767 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19768 :- 0 and it's percentage : 0.0
 Total NaN values in row 19769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19770 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19772 :- 0 and it's percentage : 0.0
 Total NaN values in row 19773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19774 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19775 :- 0 and it's percentage : 0.0
 Total NaN values in row 19776 :- 0 and it's percentage : 0.0
 Total NaN values in row 19777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19778 :- 0 and it's percentage : 0.0
 Total NaN values in row 19779 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19782 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19783 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19784 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19785 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19787 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 19788 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19789 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19790 :- 0 and it's percentage : 0.0
 Total NaN values in row 19791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19792 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19793 :- 0 and it's percentage : 0.0
 Total NaN values in row 19794 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19795 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19796 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19797 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19798 :- 0 and it's percentage : 0.0
 Total NaN values in row 19799 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19800 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19801 :- 0 and it's percentage : 0.0
 Total NaN values in row 19802 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19803 :- 0 and it's percentage : 0.0
 Total NaN values in row 19804 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19805 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19806 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19807 :- 0 and it's percentage : 0.0
 Total NaN values in row 19808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19809 :- 0 and it's percentage : 0.0
 Total NaN values in row 19810 :- 0 and it's percentage : 0.0
 Total NaN values in row 19811 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19812 :- 0 and it's percentage : 0.0
 Total NaN values in row 19813 :- 0 and it's percentage : 0.0
 Total NaN values in row 19814 :- 0 and it's percentage : 0.0
 Total NaN values in row 19815 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19816 :- 0 and it's percentage : 0.0
 Total NaN values in row 19817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19818 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19819 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19820 :- 0 and it's percentage : 0.0
 Total NaN values in row 19821 :- 0 and it's percentage : 0.0
 Total NaN values in row 19822 :- 0 and it's percentage : 0.0
 Total NaN values in row 19823 :- 0 and it's percentage : 0.0
 Total NaN values in row 19824 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19825 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19826 :- 0 and it's percentage : 0.0
 Total NaN values in row 19827 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19828 :- 0 and it's percentage : 0.0
 Total NaN values in row 19829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19830 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19831 :- 0 and it's percentage : 0.0
 Total NaN values in row 19832 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19833 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19834 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19836 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19837 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19838 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19839 :- 0 and it's percentage : 0.0
 Total NaN values in row 19840 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19841 :- 0 and it's percentage : 0.0
 Total NaN values in row 19842 :- 0 and it's percentage : 0.0
 Total NaN values in row 19843 :- 0 and it's percentage : 0.0
 Total NaN values in row 19844 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19845 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19846 :- 0 and it's percentage : 0.0
 Total NaN values in row 19847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19848 :- 0 and it's percentage : 0.0
 Total NaN values in row 19849 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19850 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19851 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19852 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19853 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19854 :- 0 and it's percentage : 0.0
 Total NaN values in row 19855 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 19856 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19857 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19858 :- 0 and it's percentage : 0.0
 Total NaN values in row 19859 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19860 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19861 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19862 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19863 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19864 :- 0 and it's percentage : 0.0
 Total NaN values in row 19865 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19866 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19867 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19868 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19869 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19870 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19872 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19873 :- 0 and it's percentage : 0.0

 Total NaN values in row 19874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19875 :- 0 and it's percentage : 0.0
 Total NaN values in row 19876 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19878 :- 0 and it's percentage : 0.0
 Total NaN values in row 19879 :- 0 and it's percentage : 0.0
 Total NaN values in row 19880 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19881 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19882 :- 0 and it's percentage : 0.0
 Total NaN values in row 19883 :- 0 and it's percentage : 0.0
 Total NaN values in row 19884 :- 0 and it's percentage : 0.0
 Total NaN values in row 19885 :- 0 and it's percentage : 0.0
 Total NaN values in row 19886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19887 :- 0 and it's percentage : 0.0
 Total NaN values in row 19888 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19889 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19891 :- 0 and it's percentage : 0.0
 Total NaN values in row 19892 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19893 :- 0 and it's percentage : 0.0
 Total NaN values in row 19894 :- 0 and it's percentage : 0.0
 Total NaN values in row 19895 :- 0 and it's percentage : 0.0
 Total NaN values in row 19896 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19897 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19898 :- 0 and it's percentage : 0.0
 Total NaN values in row 19899 :- 0 and it's percentage : 0.0
 Total NaN values in row 19900 :- 0 and it's percentage : 0.0
 Total NaN values in row 19901 :- 0 and it's percentage : 0.0
 Total NaN values in row 19902 :- 0 and it's percentage : 0.0
 Total NaN values in row 19903 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19904 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19905 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19906 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19907 :- 0 and it's percentage : 0.0
 Total NaN values in row 19908 :- 0 and it's percentage : 0.0
 Total NaN values in row 19909 :- 0 and it's percentage : 0.0
 Total NaN values in row 19910 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19911 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19912 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19913 :- 0 and it's percentage : 0.0
 Total NaN values in row 19914 :- 0 and it's percentage : 0.0
 Total NaN values in row 19915 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19916 :- 0 and it's percentage : 0.0
 Total NaN values in row 19917 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19918 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19919 :- 0 and it's percentage : 0.0
 Total NaN values in row 19920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19923 :- 0 and it's percentage : 0.0
 Total NaN values in row 19924 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19925 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19926 :- 0 and it's percentage : 0.0
 Total NaN values in row 19927 :- 0 and it's percentage : 0.0
 Total NaN values in row 19928 :- 0 and it's percentage : 0.0
 Total NaN values in row 19929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19930 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19931 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19932 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19933 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19934 :- 0 and it's percentage : 0.0
 Total NaN values in row 19935 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19936 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19937 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19938 :- 0 and it's percentage : 0.0
 Total NaN values in row 19939 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19940 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19941 :- 0 and it's percentage : 0.0
 Total NaN values in row 19942 :- 0 and it's percentage : 0.0
 Total NaN values in row 19943 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19944 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19946 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19947 :- 0 and it's percentage : 0.0
 Total NaN values in row 19948 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19949 :- 0 and it's percentage : 0.0
 Total NaN values in row 19950 :- 0 and it's percentage : 0.0
 Total NaN values in row 19951 :- 0 and it's percentage : 0.0
 Total NaN values in row 19952 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19953 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19954 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19955 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19956 :- 0 and it's percentage : 0.0
 Total NaN values in row 19957 :- 0 and it's percentage : 0.0
 Total NaN values in row 19958 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19959 :- 0 and it's percentage : 0.0
 Total NaN values in row 19960 :- 0 and it's percentage : 0.0
 Total NaN values in row 19961 :- 0 and it's percentage : 0.0
 Total NaN values in row 19962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19963 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19964 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19965 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19966 :- 0 and it's percentage : 0.0
 Total NaN values in row 19967 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19968 :- 0 and it's percentage : 0.0
 Total NaN values in row 19969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19970 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19971 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19972 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19973 :- 0 and it's percentage : 0.0
 Total NaN values in row 19974 :- 0 and it's percentage : 0.0
 Total NaN values in row 19975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19976 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19977 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19978 :- 0 and it's percentage : 0.0
 Total NaN values in row 19979 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19980 :- 0 and it's percentage : 0.0
 Total NaN values in row 19981 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 19982 :- 0 and it's percentage : 0.0
 Total NaN values in row 19983 :- 0 and it's percentage : 0.0
 Total NaN values in row 19984 :- 0 and it's percentage : 0.0
 Total NaN values in row 19985 :- 0 and it's percentage : 0.0
 Total NaN values in row 19986 :- 0 and it's percentage : 0.0
 Total NaN values in row 19987 :- 0 and it's percentage : 0.0
 Total NaN values in row 19988 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19989 :- 0 and it's percentage : 0.0
 Total NaN values in row 19990 :- 0 and it's percentage : 0.0
 Total NaN values in row 19991 :- 0 and it's percentage : 0.0
 Total NaN values in row 19992 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19993 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19994 :- 0 and it's percentage : 0.0
 Total NaN values in row 19995 :- 0 and it's percentage : 0.0
 Total NaN values in row 19996 :- 0 and it's percentage : 0.0
 Total NaN values in row 19997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 19998 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 19999 :- 0 and it's percentage : 0.0
 Total NaN values in row 20000 :- 0 and it's percentage : 0.0
 Total NaN values in row 20001 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20003 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20004 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20005 :- 0 and it's percentage : 0.0
 Total NaN values in row 20006 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20007 :- 0 and it's percentage : 0.0
 Total NaN values in row 20008 :- 0 and it's percentage : 0.0
 Total NaN values in row 20009 :- 0 and it's percentage : 0.0
 Total NaN values in row 20010 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20011 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20012 :- 0 and it's percentage : 0.0
 Total NaN values in row 20013 :- 0 and it's percentage : 0.0
 Total NaN values in row 20014 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20015 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20016 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20017 :- 0 and it's percentage : 0.0
 Total NaN values in row 20018 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20019 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20020 :- 0 and it's percentage : 0.0
 Total NaN values in row 20021 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20022 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20023 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20024 :- 0 and it's percentage : 0.0

 Total NaN values in row 20025 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20026 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20027 :- 0 and it's percentage : 0.0
 Total NaN values in row 20028 :- 0 and it's percentage : 0.0
 Total NaN values in row 20029 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20031 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20032 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20033 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20034 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20035 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20036 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 20037 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20038 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20039 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20040 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20041 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20043 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20044 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20045 :- 0 and it's percentage : 0.0
 Total NaN values in row 20046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20047 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20048 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20049 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20051 :- 0 and it's percentage : 0.0
 Total NaN values in row 20052 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20053 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20054 :- 0 and it's percentage : 0.0
 Total NaN values in row 20055 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20056 :- 0 and it's percentage : 0.0
 Total NaN values in row 20057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20058 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20060 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20061 :- 0 and it's percentage : 0.0
 Total NaN values in row 20062 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20063 :- 0 and it's percentage : 0.0
 Total NaN values in row 20064 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20066 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20067 :- 0 and it's percentage : 0.0
 Total NaN values in row 20068 :- 0 and it's percentage : 0.0
 Total NaN values in row 20069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20070 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20071 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20072 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20073 :- 0 and it's percentage : 0.0
 Total NaN values in row 20074 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20077 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20078 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20079 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20080 :- 0 and it's percentage : 0.0
 Total NaN values in row 20081 :- 0 and it's percentage : 0.0
 Total NaN values in row 20082 :- 0 and it's percentage : 0.0
 Total NaN values in row 20083 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20084 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20085 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20086 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20087 :- 0 and it's percentage : 0.0
 Total NaN values in row 20088 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20089 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20090 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20091 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20093 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20094 :- 0 and it's percentage : 0.0
 Total NaN values in row 20095 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20096 :- 0 and it's percentage : 0.0
 Total NaN values in row 20097 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20099 :- 0 and it's percentage : 0.0
 Total NaN values in row 20100 :- 0 and it's percentage : 0.0
 Total NaN values in row 20101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20102 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20103 :- 0 and it's percentage : 0.0
 Total NaN values in row 20104 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20105 :- 0 and it's percentage : 0.0
 Total NaN values in row 20106 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 20107 :- 0 and it's percentage : 0.0
 Total NaN values in row 20108 :- 0 and it's percentage : 0.0
 Total NaN values in row 20109 :- 0 and it's percentage : 0.0
 Total NaN values in row 20110 :- 0 and it's percentage : 0.0
 Total NaN values in row 20111 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20113 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20114 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20115 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20116 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20117 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20119 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20120 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20121 :- 0 and it's percentage : 0.0
 Total NaN values in row 20122 :- 0 and it's percentage : 0.0
 Total NaN values in row 20123 :- 0 and it's percentage : 0.0
 Total NaN values in row 20124 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20125 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20126 :- 0 and it's percentage : 0.0
 Total NaN values in row 20127 :- 0 and it's percentage : 0.0
 Total NaN values in row 20128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20129 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20130 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20131 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20132 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20133 :- 0 and it's percentage : 0.0
 Total NaN values in row 20134 :- 0 and it's percentage : 0.0
 Total NaN values in row 20135 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20136 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20138 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20139 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20142 :- 0 and it's percentage : 0.0

 Total NaN values in row 20143 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20144 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20145 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20146 :- 0 and it's percentage : 0.0
 Total NaN values in row 20147 :- 0 and it's percentage : 0.0
 Total NaN values in row 20148 :- 0 and it's percentage : 0.0
 Total NaN values in row 20149 :- 0 and it's percentage : 0.0
 Total NaN values in row 20150 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20152 :- 0 and it's percentage : 0.0
 Total NaN values in row 20153 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 20154 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20155 :- 0 and it's percentage : 0.0
 Total NaN values in row 20156 :- 0 and it's percentage : 0.0
 Total NaN values in row 20157 :- 0 and it's percentage : 0.0
 Total NaN values in row 20158 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20159 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20160 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20161 :- 0 and it's percentage : 0.0
 Total NaN values in row 20162 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20163 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20164 :- 0 and it's percentage : 0.0
 Total NaN values in row 20165 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20166 :- 0 and it's percentage : 0.0
 Total NaN values in row 20167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20168 :- 0 and it's percentage : 0.0
 Total NaN values in row 20169 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20170 :- 0 and it's percentage : 0.0
 Total NaN values in row 20171 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20172 :- 0 and it's percentage : 0.0
 Total NaN values in row 20173 :- 0 and it's percentage : 0.0
 Total NaN values in row 20174 :- 0 and it's percentage : 0.0
 Total NaN values in row 20175 :- 0 and it's percentage : 0.0
 Total NaN values in row 20176 :- 0 and it's percentage : 0.0
 Total NaN values in row 20177 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20179 :- 0 and it's percentage : 0.0
 Total NaN values in row 20180 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20181 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20182 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20184 :- 0 and it's percentage : 0.0
 Total NaN values in row 20185 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20186 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20187 :- 0 and it's percentage : 0.0
 Total NaN values in row 20188 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20189 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20190 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20191 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20192 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20193 :- 0 and it's percentage : 0.0
 Total NaN values in row 20194 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20195 :- 0 and it's percentage : 0.0
 Total NaN values in row 20196 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20197 :- 0 and it's percentage : 0.0
 Total NaN values in row 20198 :- 0 and it's percentage : 0.0
 Total NaN values in row 20199 :- 0 and it's percentage : 0.0
 Total NaN values in row 20200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20201 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20202 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20203 :- 0 and it's percentage : 0.0
 Total NaN values in row 20204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20205 :- 0 and it's percentage : 0.0
 Total NaN values in row 20206 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20208 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20209 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20210 :- 0 and it's percentage : 0.0
 Total NaN values in row 20211 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20212 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20213 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20214 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20215 :- 0 and it's percentage : 0.0
 Total NaN values in row 20216 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20218 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20220 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20221 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20222 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20223 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20224 :- 0 and it's percentage : 0.0
 Total NaN values in row 20225 :- 0 and it's percentage : 0.0
 Total NaN values in row 20226 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20228 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20229 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20230 :- 0 and it's percentage : 0.0
 Total NaN values in row 20231 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20232 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20233 :- 0 and it's percentage : 0.0
 Total NaN values in row 20234 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20235 :- 0 and it's percentage : 0.0
 Total NaN values in row 20236 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20237 :- 0 and it's percentage : 0.0
 Total NaN values in row 20238 :- 0 and it's percentage : 0.0
 Total NaN values in row 20239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20240 :- 0 and it's percentage : 0.0
 Total NaN values in row 20241 :- 0 and it's percentage : 0.0
 Total NaN values in row 20242 :- 0 and it's percentage : 0.0
 Total NaN values in row 20243 :- 0 and it's percentage : 0.0
 Total NaN values in row 20244 :- 0 and it's percentage : 0.0
 Total NaN values in row 20245 :- 0 and it's percentage : 0.0
 Total NaN values in row 20246 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20248 :- 0 and it's percentage : 0.0
 Total NaN values in row 20249 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20251 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20252 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20253 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20254 :- 0 and it's percentage : 0.0
 Total NaN values in row 20255 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20256 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20259 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20260 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20261 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20262 :- 0 and it's percentage : 0.0
 Total NaN values in row 20263 :- 0 and it's percentage : 0.0
 Total NaN values in row 20264 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20265 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20269 :- 0 and it's percentage : 0.0
 Total NaN values in row 20270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20271 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20272 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20273 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20274 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20275 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20276 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20277 :- 0 and it's percentage : 0.0
 Total NaN values in row 20278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20279 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 20280 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20281 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20282 :- 0 and it's percentage : 0.0
 Total NaN values in row 20283 :- 0 and it's percentage : 0.0
 Total NaN values in row 20284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20285 :- 0 and it's percentage : 0.0
 Total NaN values in row 20286 :- 0 and it's percentage : 0.0
 Total NaN values in row 20287 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20288 :- 0 and it's percentage : 0.0
 Total NaN values in row 20289 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20290 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20291 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20292 :- 0 and it's percentage : 0.0
 Total NaN values in row 20293 :- 0 and it's percentage : 0.0
 Total NaN values in row 20294 :- 0 and it's percentage : 0.0
 Total NaN values in row 20295 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20296 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20297 :- 0 and it's percentage : 0.0
 Total NaN values in row 20298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20299 :- 0 and it's percentage : 0.0
 Total NaN values in row 20300 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20301 :- 0 and it's percentage : 0.0
 Total NaN values in row 20302 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20303 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20304 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20305 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20306 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20307 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20308 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20309 :- 0 and it's percentage : 0.0
 Total NaN values in row 20310 :- 0 and it's percentage : 0.0
 Total NaN values in row 20311 :- 0 and it's percentage : 0.0
 Total NaN values in row 20312 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20313 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20314 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20315 :- 0 and it's percentage : 0.0
 Total NaN values in row 20316 :- 0 and it's percentage : 0.0
 Total NaN values in row 20317 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20318 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20319 :- 0 and it's percentage : 0.0
 Total NaN values in row 20320 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20321 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20323 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20324 :- 0 and it's percentage : 0.0
 Total NaN values in row 20325 :- 0 and it's percentage : 0.0
 Total NaN values in row 20326 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20327 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20328 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20331 :- 0 and it's percentage : 0.0
 Total NaN values in row 20332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20333 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20334 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20336 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20337 :- 0 and it's percentage : 0.0
 Total NaN values in row 20338 :- 0 and it's percentage : 0.0
 Total NaN values in row 20339 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20340 :- 0 and it's percentage : 0.0
 Total NaN values in row 20341 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20344 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20345 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20346 :- 0 and it's percentage : 0.0
 Total NaN values in row 20347 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20349 :- 0 and it's percentage : 0.0
 Total NaN values in row 20350 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20351 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20352 :- 0 and it's percentage : 0.0
 Total NaN values in row 20353 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20354 :- 0 and it's percentage : 0.0
 Total NaN values in row 20355 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20356 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20357 :- 0 and it's percentage : 0.0
 Total NaN values in row 20358 :- 0 and it's percentage : 0.0
 Total NaN values in row 20359 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20360 :- 0 and it's percentage : 0.0
 Total NaN values in row 20361 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20362 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20363 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20364 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20365 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20367 :- 0 and it's percentage : 0.0
 Total NaN values in row 20368 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20369 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20370 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20371 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20372 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20373 :- 0 and it's percentage : 0.0
 Total NaN values in row 20374 :- 0 and it's percentage : 0.0
 Total NaN values in row 20375 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20376 :- 0 and it's percentage : 0.0
 Total NaN values in row 20377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20378 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20380 :- 0 and it's percentage : 0.0
 Total NaN values in row 20381 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20382 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20383 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20384 :- 0 and it's percentage : 0.0
 Total NaN values in row 20385 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20387 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20389 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20390 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20391 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20392 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20393 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20394 :- 0 and it's percentage : 0.0
 Total NaN values in row 20395 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20396 :- 0 and it's percentage : 0.0
 Total NaN values in row 20397 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20398 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20399 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20401 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20402 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20403 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20404 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20405 :- 0 and it's percentage : 0.0
 Total NaN values in row 20406 :- 0 and it's percentage : 0.0

 Total NaN values in row 20407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20408 :- 0 and it's percentage : 0.0
 Total NaN values in row 20409 :- 0 and it's percentage : 0.0
 Total NaN values in row 20410 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20411 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20412 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20413 :- 0 and it's percentage : 0.0
 Total NaN values in row 20414 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20415 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20416 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20417 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20418 :- 0 and it's percentage : 0.0
 Total NaN values in row 20419 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20420 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20421 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20423 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20424 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20425 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20426 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20427 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20428 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20429 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20430 :- 0 and it's percentage : 0.0
 Total NaN values in row 20431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20432 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20434 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20435 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 20436 :- 0 and it's percentage : 0.0
 Total NaN values in row 20437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20441 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20443 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20444 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20445 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20449 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20450 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20451 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20452 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20453 :- 0 and it's percentage : 0.0
 Total NaN values in row 20454 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20456 :- 0 and it's percentage : 0.0
 Total NaN values in row 20457 :- 0 and it's percentage : 0.0
 Total NaN values in row 20458 :- 0 and it's percentage : 0.0
 Total NaN values in row 20459 :- 0 and it's percentage : 0.0
 Total NaN values in row 20460 :- 0 and it's percentage : 0.0
 Total NaN values in row 20461 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20462 :- 0 and it's percentage : 0.0
 Total NaN values in row 20463 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20464 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20465 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20466 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20467 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20468 :- 0 and it's percentage : 0.0
 Total NaN values in row 20469 :- 0 and it's percentage : 0.0
 Total NaN values in row 20470 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20471 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20472 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20473 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20474 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20475 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20477 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20479 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20480 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20481 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20482 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20483 :- 0 and it's percentage : 0.0
 Total NaN values in row 20484 :- 0 and it's percentage : 0.0
 Total NaN values in row 20485 :- 0 and it's percentage : 0.0
 Total NaN values in row 20486 :- 0 and it's percentage : 0.0
 Total NaN values in row 20487 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 20488 :- 0 and it's percentage : 0.0
 Total NaN values in row 20489 :- 0 and it's percentage : 0.0
 Total NaN values in row 20490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20491 :- 0 and it's percentage : 0.0
 Total NaN values in row 20492 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20493 :- 0 and it's percentage : 0.0
 Total NaN values in row 20494 :- 0 and it's percentage : 0.0
 Total NaN values in row 20495 :- 0 and it's percentage : 0.0
 Total NaN values in row 20496 :- 0 and it's percentage : 0.0
 Total NaN values in row 20497 :- 0 and it's percentage : 0.0
 Total NaN values in row 20498 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20500 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20501 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20502 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20503 :- 0 and it's percentage : 0.0
 Total NaN values in row 20504 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20505 :- 0 and it's percentage : 0.0
 Total NaN values in row 20506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20507 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20508 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20510 :- 0 and it's percentage : 0.0
 Total NaN values in row 20511 :- 0 and it's percentage : 0.0
 Total NaN values in row 20512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20513 :- 0 and it's percentage : 0.0
 Total NaN values in row 20514 :- 0 and it's percentage : 0.0
 Total NaN values in row 20515 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20517 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20519 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20520 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20521 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20522 :- 0 and it's percentage : 0.0
 Total NaN values in row 20523 :- 0 and it's percentage : 0.0
 Total NaN values in row 20524 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20525 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20526 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20527 :- 0 and it's percentage : 0.0
 Total NaN values in row 20528 :- 0 and it's percentage : 0.0
 Total NaN values in row 20529 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20530 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20531 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20532 :- 0 and it's percentage : 0.0
 Total NaN values in row 20533 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20534 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20535 :- 0 and it's percentage : 0.0
 Total NaN values in row 20536 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20538 :- 0 and it's percentage : 0.0
 Total NaN values in row 20539 :- 0 and it's percentage : 0.0
 Total NaN values in row 20540 :- 0 and it's percentage : 0.0
 Total NaN values in row 20541 :- 0 and it's percentage : 0.0
 Total NaN values in row 20542 :- 0 and it's percentage : 0.0
 Total NaN values in row 20543 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20544 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 20545 :- 0 and it's percentage : 0.0
 Total NaN values in row 20546 :- 0 and it's percentage : 0.0
 Total NaN values in row 20547 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20549 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20550 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20551 :- 0 and it's percentage : 0.0
 Total NaN values in row 20552 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20553 :- 0 and it's percentage : 0.0
 Total NaN values in row 20554 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20555 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20556 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20557 :- 0 and it's percentage : 0.0
 Total NaN values in row 20558 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20559 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20560 :- 0 and it's percentage : 0.0
 Total NaN values in row 20561 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20562 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20563 :- 0 and it's percentage : 0.0
 Total NaN values in row 20564 :- 0 and it's percentage : 0.0
 Total NaN values in row 20565 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20566 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20567 :- 0 and it's percentage : 0.0
 Total NaN values in row 20568 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20569 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20570 :- 0 and it's percentage : 0.0
 Total NaN values in row 20571 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20572 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20573 :- 0 and it's percentage : 0.0
 Total NaN values in row 20574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20575 :- 0 and it's percentage : 0.0
 Total NaN values in row 20576 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20577 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20578 :- 0 and it's percentage : 0.0
 Total NaN values in row 20579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20580 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20581 :- 0 and it's percentage : 0.0
 Total NaN values in row 20582 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20583 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20584 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20585 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20586 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20587 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20588 :- 0 and it's percentage : 0.0
 Total NaN values in row 20589 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20590 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20591 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20592 :- 0 and it's percentage : 0.0
 Total NaN values in row 20593 :- 0 and it's percentage : 0.0
 Total NaN values in row 20594 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20595 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20596 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20597 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20598 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20599 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20600 :- 0 and it's percentage : 0.0
 Total NaN values in row 20601 :- 0 and it's percentage : 0.0
 Total NaN values in row 20602 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20603 :- 0 and it's percentage : 0.0
 Total NaN values in row 20604 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20605 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20606 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20607 :- 0 and it's percentage : 0.0
 Total NaN values in row 20608 :- 0 and it's percentage : 0.0
 Total NaN values in row 20609 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20610 :- 0 and it's percentage : 0.0
 Total NaN values in row 20611 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20612 :- 0 and it's percentage : 0.0
 Total NaN values in row 20613 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20614 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20615 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20616 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20617 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20618 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20619 :- 0 and it's percentage : 0.0
 Total NaN values in row 20620 :- 0 and it's percentage : 0.0
 Total NaN values in row 20621 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20622 :- 0 and it's percentage : 0.0
 Total NaN values in row 20623 :- 0 and it's percentage : 0.0
 Total NaN values in row 20624 :- 0 and it's percentage : 0.0
 Total NaN values in row 20625 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20626 :- 0 and it's percentage : 0.0
 Total NaN values in row 20627 :- 0 and it's percentage : 0.0
 Total NaN values in row 20628 :- 0 and it's percentage : 0.0
 Total NaN values in row 20629 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20630 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20631 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20633 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20634 :- 0 and it's percentage : 0.0
 Total NaN values in row 20635 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20636 :- 0 and it's percentage : 0.0
 Total NaN values in row 20637 :- 0 and it's percentage : 0.0
 Total NaN values in row 20638 :- 0 and it's percentage : 0.0
 Total NaN values in row 20639 :- 0 and it's percentage : 0.0
 Total NaN values in row 20640 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20642 :- 0 and it's percentage : 0.0
 Total NaN values in row 20643 :- 0 and it's percentage : 0.0
 Total NaN values in row 20644 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20645 :- 0 and it's percentage : 0.0
 Total NaN values in row 20646 :- 0 and it's percentage : 0.0
 Total NaN values in row 20647 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20648 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20649 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20650 :- 0 and it's percentage : 0.0
 Total NaN values in row 20651 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20653 :- 0 and it's percentage : 0.0
 Total NaN values in row 20654 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 20655 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20656 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20657 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20658 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20659 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20660 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20661 :- 0 and it's percentage : 0.0
 Total NaN values in row 20662 :- 0 and it's percentage : 0.0
 Total NaN values in row 20663 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20664 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20666 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20667 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20669 :- 0 and it's percentage : 0.0
 Total NaN values in row 20670 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20671 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20672 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20673 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20674 :- 0 and it's percentage : 0.0
 Total NaN values in row 20675 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20676 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20677 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20678 :- 0 and it's percentage : 0.0
 Total NaN values in row 20679 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20681 :- 0 and it's percentage : 0.0

 Total NaN values in row 20682 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20683 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20684 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20685 :- 0 and it's percentage : 0.0
 Total NaN values in row 20686 :- 0 and it's percentage : 0.0
 Total NaN values in row 20687 :- 0 and it's percentage : 0.0
 Total NaN values in row 20688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20689 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20690 :- 0 and it's percentage : 0.0
 Total NaN values in row 20691 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20692 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20693 :- 0 and it's percentage : 0.0
 Total NaN values in row 20694 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20695 :- 0 and it's percentage : 0.0
 Total NaN values in row 20696 :- 0 and it's percentage : 0.0
 Total NaN values in row 20697 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20698 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20699 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20700 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20701 :- 0 and it's percentage : 0.0
 Total NaN values in row 20702 :- 0 and it's percentage : 0.0
 Total NaN values in row 20703 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20704 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20705 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20706 :- 0 and it's percentage : 0.0
 Total NaN values in row 20707 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20708 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20709 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20710 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20713 :- 0 and it's percentage : 0.0
 Total NaN values in row 20714 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20715 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20717 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20718 :- 0 and it's percentage : 0.0
 Total NaN values in row 20719 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20720 :- 0 and it's percentage : 0.0
 Total NaN values in row 20721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20722 :- 0 and it's percentage : 0.0
 Total NaN values in row 20723 :- 0 and it's percentage : 0.0
 Total NaN values in row 20724 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20725 :- 0 and it's percentage : 0.0
 Total NaN values in row 20726 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20727 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20728 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20729 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20730 :- 0 and it's percentage : 0.0
 Total NaN values in row 20731 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20732 :- 0 and it's percentage : 0.0
 Total NaN values in row 20733 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20734 :- 0 and it's percentage : 0.0
 Total NaN values in row 20735 :- 0 and it's percentage : 0.0
 Total NaN values in row 20736 :- 0 and it's percentage : 0.0
 Total NaN values in row 20737 :- 0 and it's percentage : 0.0
 Total NaN values in row 20738 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20739 :- 0 and it's percentage : 0.0
 Total NaN values in row 20740 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20741 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20744 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20745 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20746 :- 0 and it's percentage : 0.0
 Total NaN values in row 20747 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20748 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20749 :- 0 and it's percentage : 0.0
 Total NaN values in row 20750 :- 0 and it's percentage : 0.0
 Total NaN values in row 20751 :- 0 and it's percentage : 0.0
 Total NaN values in row 20752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20753 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20755 :- 0 and it's percentage : 0.0
 Total NaN values in row 20756 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20757 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20758 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20759 :- 0 and it's percentage : 0.0
 Total NaN values in row 20760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20762 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20763 :- 0 and it's percentage : 0.0
 Total NaN values in row 20764 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20765 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20766 :- 0 and it's percentage : 0.0
 Total NaN values in row 20767 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20769 :- 0 and it's percentage : 0.0
 Total NaN values in row 20770 :- 0 and it's percentage : 0.0
 Total NaN values in row 20771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20772 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20773 :- 0 and it's percentage : 0.0
 Total NaN values in row 20774 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20775 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20779 :- 0 and it's percentage : 0.0
 Total NaN values in row 20780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20781 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20782 :- 0 and it's percentage : 0.0
 Total NaN values in row 20783 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20784 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20785 :- 0 and it's percentage : 0.0
 Total NaN values in row 20786 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20787 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20788 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20789 :- 0 and it's percentage : 0.0
 Total NaN values in row 20790 :- 0 and it's percentage : 0.0
 Total NaN values in row 20791 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20792 :- 0 and it's percentage : 0.0
 Total NaN values in row 20793 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20794 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20795 :- 0 and it's percentage : 0.0
 Total NaN values in row 20796 :- 0 and it's percentage : 0.0
 Total NaN values in row 20797 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20798 :- 0 and it's percentage : 0.0
 Total NaN values in row 20799 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20800 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20801 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20802 :- 0 and it's percentage : 0.0
 Total NaN values in row 20803 :- 0 and it's percentage : 0.0
 Total NaN values in row 20804 :- 0 and it's percentage : 0.0

 Total NaN values in row 20805 :- 0 and it's percentage : 0.0
 Total NaN values in row 20806 :- 0 and it's percentage : 0.0
 Total NaN values in row 20807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20809 :- 0 and it's percentage : 0.0
 Total NaN values in row 20810 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20811 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20813 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20814 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20815 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20816 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20817 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20818 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20819 :- 0 and it's percentage : 0.0
 Total NaN values in row 20820 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20821 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20822 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20823 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 20824 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20825 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20827 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20828 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20830 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20832 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20833 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20834 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20836 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20837 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20838 :- 0 and it's percentage : 0.0
 Total NaN values in row 20839 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20840 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20841 :- 0 and it's percentage : 0.0
 Total NaN values in row 20842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20843 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 20844 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20845 :- 0 and it's percentage : 0.0
 Total NaN values in row 20846 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20847 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20848 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20849 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20850 :- 0 and it's percentage : 0.0
 Total NaN values in row 20851 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20852 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20853 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20855 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20856 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20857 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20858 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20859 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20860 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20861 :- 0 and it's percentage : 0.0
 Total NaN values in row 20862 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20863 :- 0 and it's percentage : 0.0
 Total NaN values in row 20864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20865 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20866 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20867 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20868 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20869 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20870 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20872 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20873 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20875 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20876 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20878 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20879 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20880 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20881 :- 0 and it's percentage : 0.0
 Total NaN values in row 20882 :- 0 and it's percentage : 0.0
 Total NaN values in row 20883 :- 0 and it's percentage : 0.0
 Total NaN values in row 20884 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20885 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20887 :- 0 and it's percentage : 0.0
 Total NaN values in row 20888 :- 0 and it's percentage : 0.0
 Total NaN values in row 20889 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20891 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20892 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20893 :- 0 and it's percentage : 0.0
 Total NaN values in row 20894 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20895 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20896 :- 0 and it's percentage : 0.0
 Total NaN values in row 20897 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20898 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20899 :- 0 and it's percentage : 0.0
 Total NaN values in row 20900 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20901 :- 0 and it's percentage : 0.0
 Total NaN values in row 20902 :- 0 and it's percentage : 0.0
 Total NaN values in row 20903 :- 0 and it's percentage : 0.0
 Total NaN values in row 20904 :- 0 and it's percentage : 0.0
 Total NaN values in row 20905 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20906 :- 0 and it's percentage : 0.0
 Total NaN values in row 20907 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20908 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20910 :- 0 and it's percentage : 0.0
 Total NaN values in row 20911 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20912 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20913 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 20914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20915 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20916 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20917 :- 0 and it's percentage : 0.0
 Total NaN values in row 20918 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20919 :- 0 and it's percentage : 0.0
 Total NaN values in row 20920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20921 :- 0 and it's percentage : 0.0
 Total NaN values in row 20922 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20923 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20924 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20925 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20926 :- 0 and it's percentage : 0.0
 Total NaN values in row 20927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20928 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20929 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20930 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20931 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20932 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20933 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20935 :- 0 and it's percentage : 0.0
 Total NaN values in row 20936 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20937 :- 0 and it's percentage : 0.0

 Total NaN values in row 20938 :- 0 and it's percentage : 0.0
 Total NaN values in row 20939 :- 0 and it's percentage : 0.0
 Total NaN values in row 20940 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20941 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20942 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20943 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20944 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20945 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20946 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20947 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20948 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20949 :- 0 and it's percentage : 0.0
 Total NaN values in row 20950 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20951 :- 0 and it's percentage : 0.0
 Total NaN values in row 20952 :- 0 and it's percentage : 0.0
 Total NaN values in row 20953 :- 0 and it's percentage : 0.0
 Total NaN values in row 20954 :- 0 and it's percentage : 0.0
 Total NaN values in row 20955 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20956 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20957 :- 0 and it's percentage : 0.0
 Total NaN values in row 20958 :- 0 and it's percentage : 0.0
 Total NaN values in row 20959 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20960 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20961 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20963 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20964 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20965 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20966 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20967 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20968 :- 0 and it's percentage : 0.0
 Total NaN values in row 20969 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 20970 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20971 :- 0 and it's percentage : 0.0
 Total NaN values in row 20972 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20976 :- 0 and it's percentage : 0.0
 Total NaN values in row 20977 :- 0 and it's percentage : 0.0
 Total NaN values in row 20978 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20979 :- 0 and it's percentage : 0.0
 Total NaN values in row 20980 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20982 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20983 :- 0 and it's percentage : 0.0
 Total NaN values in row 20984 :- 0 and it's percentage : 0.0
 Total NaN values in row 20985 :- 0 and it's percentage : 0.0
 Total NaN values in row 20986 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20987 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20988 :- 0 and it's percentage : 0.0
 Total NaN values in row 20989 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20990 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20991 :- 0 and it's percentage : 0.0
 Total NaN values in row 20992 :- 0 and it's percentage : 0.0
 Total NaN values in row 20993 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 20994 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20995 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20996 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 20997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 20998 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 20999 :- 0 and it's percentage : 0.0
 Total NaN values in row 21000 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21001 :- 0 and it's percentage : 0.0
 Total NaN values in row 21002 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21003 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21004 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21005 :- 0 and it's percentage : 0.0
 Total NaN values in row 21006 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21007 :- 0 and it's percentage : 0.0
 Total NaN values in row 21008 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21010 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21011 :- 0 and it's percentage : 0.0
 Total NaN values in row 21012 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21013 :- 0 and it's percentage : 0.0
 Total NaN values in row 21014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21015 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21016 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21017 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21018 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21019 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21020 :- 0 and it's percentage : 0.0
 Total NaN values in row 21021 :- 0 and it's percentage : 0.0
 Total NaN values in row 21022 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21023 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21024 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21025 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21026 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21027 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21029 :- 0 and it's percentage : 0.0
 Total NaN values in row 21030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21031 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21032 :- 0 and it's percentage : 0.0
 Total NaN values in row 21033 :- 0 and it's percentage : 0.0
 Total NaN values in row 21034 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21035 :- 0 and it's percentage : 0.0
 Total NaN values in row 21036 :- 0 and it's percentage : 0.0
 Total NaN values in row 21037 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21038 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21039 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21040 :- 0 and it's percentage : 0.0
 Total NaN values in row 21041 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21043 :- 0 and it's percentage : 0.0
 Total NaN values in row 21044 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21045 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21047 :- 0 and it's percentage : 0.0
 Total NaN values in row 21048 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21049 :- 0 and it's percentage : 0.0
 Total NaN values in row 21050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21051 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21052 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21053 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21054 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21055 :- 0 and it's percentage : 0.0
 Total NaN values in row 21056 :- 0 and it's percentage : 0.0
 Total NaN values in row 21057 :- 0 and it's percentage : 0.0
 Total NaN values in row 21058 :- 0 and it's percentage : 0.0
 Total NaN values in row 21059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21060 :- 0 and it's percentage : 0.0
 Total NaN values in row 21061 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21062 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21063 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21064 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21065 :- 0 and it's percentage : 0.0
 Total NaN values in row 21066 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21067 :- 0 and it's percentage : 0.0
 Total NaN values in row 21068 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21069 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21070 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21071 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 21072 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21073 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21074 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21077 :- 0 and it's percentage : 0.0
 Total NaN values in row 21078 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21079 :- 0 and it's percentage : 0.0
 Total NaN values in row 21080 :- 0 and it's percentage : 0.0
 Total NaN values in row 21081 :- 0 and it's percentage : 0.0
 Total NaN values in row 21082 :- 0 and it's percentage : 0.0
 Total NaN values in row 21083 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21084 :- 0 and it's percentage : 0.0
 Total NaN values in row 21085 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21086 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21087 :- 0 and it's percentage : 0.0
 Total NaN values in row 21088 :- 0 and it's percentage : 0.0
 Total NaN values in row 21089 :- 0 and it's percentage : 0.0
 Total NaN values in row 21090 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21091 :- 0 and it's percentage : 0.0
 Total NaN values in row 21092 :- 0 and it's percentage : 0.0
 Total NaN values in row 21093 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21095 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21096 :- 0 and it's percentage : 0.0
 Total NaN values in row 21097 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21098 :- 0 and it's percentage : 0.0
 Total NaN values in row 21099 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21100 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21102 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21103 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21104 :- 0 and it's percentage : 0.0
 Total NaN values in row 21105 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21107 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21108 :- 0 and it's percentage : 0.0
 Total NaN values in row 21109 :- 0 and it's percentage : 0.0
 Total NaN values in row 21110 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21111 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21112 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21113 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21114 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21115 :- 0 and it's percentage : 0.0
 Total NaN values in row 21116 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21118 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21119 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21120 :- 0 and it's percentage : 0.0
 Total NaN values in row 21121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21122 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21123 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21124 :- 0 and it's percentage : 0.0
 Total NaN values in row 21125 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 21126 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21127 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21129 :- 0 and it's percentage : 0.0
 Total NaN values in row 21130 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21131 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21132 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21133 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21134 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21135 :- 0 and it's percentage : 0.0
 Total NaN values in row 21136 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21137 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 21138 :- 0 and it's percentage : 0.0
 Total NaN values in row 21139 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21142 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21143 :- 0 and it's percentage : 0.0
 Total NaN values in row 21144 :- 0 and it's percentage : 0.0
 Total NaN values in row 21145 :- 0 and it's percentage : 0.0
 Total NaN values in row 21146 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21147 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21148 :- 0 and it's percentage : 0.0
 Total NaN values in row 21149 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21150 :- 0 and it's percentage : 0.0
 Total NaN values in row 21151 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21152 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21153 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21154 :- 0 and it's percentage : 0.0
 Total NaN values in row 21155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21156 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21157 :- 0 and it's percentage : 0.0
 Total NaN values in row 21158 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21159 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21160 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21161 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21162 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21163 :- 0 and it's percentage : 0.0
 Total NaN values in row 21164 :- 0 and it's percentage : 0.0
 Total NaN values in row 21165 :- 0 and it's percentage : 0.0
 Total NaN values in row 21166 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21167 :- 0 and it's percentage : 0.0
 Total NaN values in row 21168 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21169 :- 0 and it's percentage : 0.0
 Total NaN values in row 21170 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21171 :- 0 and it's percentage : 0.0
 Total NaN values in row 21172 :- 0 and it's percentage : 0.0
 Total NaN values in row 21173 :- 0 and it's percentage : 0.0
 Total NaN values in row 21174 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21175 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21176 :- 0 and it's percentage : 0.0
 Total NaN values in row 21177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21180 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21182 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21184 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21186 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21187 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21188 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21189 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21190 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21191 :- 0 and it's percentage : 0.0
 Total NaN values in row 21192 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21193 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21194 :- 0 and it's percentage : 0.0
 Total NaN values in row 21195 :- 0 and it's percentage : 0.0
 Total NaN values in row 21196 :- 0 and it's percentage : 0.0
 Total NaN values in row 21197 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21198 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21200 :- 0 and it's percentage : 0.0
 Total NaN values in row 21201 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21202 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21204 :- 0 and it's percentage : 0.0
 Total NaN values in row 21205 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21208 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21209 :- 0 and it's percentage : 0.0
 Total NaN values in row 21210 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21211 :- 0 and it's percentage : 0.0
 Total NaN values in row 21212 :- 0 and it's percentage : 0.0
 Total NaN values in row 21213 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 21214 :- 0 and it's percentage : 0.0
 Total NaN values in row 21215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21216 :- 0 and it's percentage : 0.0
 Total NaN values in row 21217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21218 :- 0 and it's percentage : 0.0
 Total NaN values in row 21219 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21220 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21221 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21222 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21223 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21224 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21225 :- 0 and it's percentage : 0.0
 Total NaN values in row 21226 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21227 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21229 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21230 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21231 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21232 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21233 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21234 :- 0 and it's percentage : 0.0
 Total NaN values in row 21235 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21236 :- 0 and it's percentage : 0.0
 Total NaN values in row 21237 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21238 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21239 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21240 :- 0 and it's percentage : 0.0
 Total NaN values in row 21241 :- 0 and it's percentage : 0.0
 Total NaN values in row 21242 :- 0 and it's percentage : 0.0
 Total NaN values in row 21243 :- 0 and it's percentage : 0.0
 Total NaN values in row 21244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21245 :- 0 and it's percentage : 0.0
 Total NaN values in row 21246 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21247 :- 0 and it's percentage : 0.0
 Total NaN values in row 21248 :- 0 and it's percentage : 0.0
 Total NaN values in row 21249 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21251 :- 0 and it's percentage : 0.0
 Total NaN values in row 21252 :- 0 and it's percentage : 0.0
 Total NaN values in row 21253 :- 0 and it's percentage : 0.0
 Total NaN values in row 21254 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21255 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21256 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21257 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21258 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21259 :- 0 and it's percentage : 0.0
 Total NaN values in row 21260 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21261 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21262 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21263 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21264 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21265 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21266 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21267 :- 0 and it's percentage : 0.0
 Total NaN values in row 21268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21269 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21271 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21272 :- 0 and it's percentage : 0.0
 Total NaN values in row 21273 :- 0 and it's percentage : 0.0
 Total NaN values in row 21274 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21275 :- 0 and it's percentage : 0.0
 Total NaN values in row 21276 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21277 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21278 :- 0 and it's percentage : 0.0
 Total NaN values in row 21279 :- 0 and it's percentage : 0.0
 Total NaN values in row 21280 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21283 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21285 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21286 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21287 :- 0 and it's percentage : 0.0
 Total NaN values in row 21288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21289 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21290 :- 0 and it's percentage : 0.0
 Total NaN values in row 21291 :- 0 and it's percentage : 0.0
 Total NaN values in row 21292 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21294 :- 0 and it's percentage : 0.0
 Total NaN values in row 21295 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21296 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21297 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21298 :- 0 and it's percentage : 0.0
 Total NaN values in row 21299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21300 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21301 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21302 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21303 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21304 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21305 :- 0 and it's percentage : 0.0
 Total NaN values in row 21306 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21308 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21309 :- 0 and it's percentage : 0.0
 Total NaN values in row 21310 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21311 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21312 :- 0 and it's percentage : 0.0
 Total NaN values in row 21313 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21314 :- 0 and it's percentage : 0.0
 Total NaN values in row 21315 :- 0 and it's percentage : 0.0
 Total NaN values in row 21316 :- 0 and it's percentage : 0.0
 Total NaN values in row 21317 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21318 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21319 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21320 :- 0 and it's percentage : 0.0
 Total NaN values in row 21321 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21322 :- 0 and it's percentage : 0.0
 Total NaN values in row 21323 :- 0 and it's percentage : 0.0
 Total NaN values in row 21324 :- 0 and it's percentage : 0.0
 Total NaN values in row 21325 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21326 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21327 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21328 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21329 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21331 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21333 :- 0 and it's percentage : 0.0
 Total NaN values in row 21334 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21335 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21336 :- 0 and it's percentage : 0.0
 Total NaN values in row 21337 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21339 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21340 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21341 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21343 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21344 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21345 :- 0 and it's percentage : 0.0
 Total NaN values in row 21346 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21347 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21348 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21349 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21350 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21351 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21352 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21353 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21354 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21355 :- 0 and it's percentage : 0.0
 Total NaN values in row 21356 :- 0 and it's percentage : 0.0
 Total NaN values in row 21357 :- 0 and it's percentage : 0.0
 Total NaN values in row 21358 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21359 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21360 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21361 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 21362 :- 0 and it's percentage : 0.0
 Total NaN values in row 21363 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21364 :- 0 and it's percentage : 0.0
 Total NaN values in row 21365 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21366 :- 0 and it's percentage : 0.0
 Total NaN values in row 21367 :- 0 and it's percentage : 0.0
 Total NaN values in row 21368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21369 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21370 :- 0 and it's percentage : 0.0
 Total NaN values in row 21371 :- 0 and it's percentage : 0.0
 Total NaN values in row 21372 :- 0 and it's percentage : 0.0
 Total NaN values in row 21373 :- 0 and it's percentage : 0.0
 Total NaN values in row 21374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21375 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21376 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21378 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21379 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21380 :- 0 and it's percentage : 0.0
 Total NaN values in row 21381 :- 0 and it's percentage : 0.0
 Total NaN values in row 21382 :- 0 and it's percentage : 0.0
 Total NaN values in row 21383 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21384 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21385 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21386 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21387 :- 0 and it's percentage : 0.0
 Total NaN values in row 21388 :- 0 and it's percentage : 0.0
 Total NaN values in row 21389 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21390 :- 0 and it's percentage : 0.0
 Total NaN values in row 21391 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21392 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21393 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21394 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21395 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21396 :- 0 and it's percentage : 0.0
 Total NaN values in row 21397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21398 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21399 :- 0 and it's percentage : 0.0
 Total NaN values in row 21400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21401 :- 0 and it's percentage : 0.0
 Total NaN values in row 21402 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21403 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21404 :- 0 and it's percentage : 0.0
 Total NaN values in row 21405 :- 0 and it's percentage : 0.0
 Total NaN values in row 21406 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21407 :- 0 and it's percentage : 0.0
 Total NaN values in row 21408 :- 0 and it's percentage : 0.0
 Total NaN values in row 21409 :- 0 and it's percentage : 0.0
 Total NaN values in row 21410 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21411 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21412 :- 0 and it's percentage : 0.0
 Total NaN values in row 21413 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 21414 :- 0 and it's percentage : 0.0
 Total NaN values in row 21415 :- 0 and it's percentage : 0.0
 Total NaN values in row 21416 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21417 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21418 :- 0 and it's percentage : 0.0
 Total NaN values in row 21419 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21420 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21421 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21423 :- 0 and it's percentage : 0.0
 Total NaN values in row 21424 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21425 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21426 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21427 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21429 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21431 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21432 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21434 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21435 :- 0 and it's percentage : 0.0
 Total NaN values in row 21436 :- 0 and it's percentage : 0.0
 Total NaN values in row 21437 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21441 :- 0 and it's percentage : 0.0
 Total NaN values in row 21442 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21443 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21444 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21445 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21446 :- 0 and it's percentage : 0.0
 Total NaN values in row 21447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21448 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21449 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21450 :- 0 and it's percentage : 0.0
 Total NaN values in row 21451 :- 0 and it's percentage : 0.0
 Total NaN values in row 21452 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21453 :- 0 and it's percentage : 0.0
 Total NaN values in row 21454 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21456 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21457 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21458 :- 0 and it's percentage : 0.0
 Total NaN values in row 21459 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21460 :- 0 and it's percentage : 0.0
 Total NaN values in row 21461 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21462 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 21463 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21464 :- 0 and it's percentage : 0.0
 Total NaN values in row 21465 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21466 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21467 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21468 :- 0 and it's percentage : 0.0
 Total NaN values in row 21469 :- 0 and it's percentage : 0.0
 Total NaN values in row 21470 :- 0 and it's percentage : 0.0
 Total NaN values in row 21471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21473 :- 0 and it's percentage : 0.0
 Total NaN values in row 21474 :- 0 and it's percentage : 0.0
 Total NaN values in row 21475 :- 0 and it's percentage : 0.0
 Total NaN values in row 21476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21477 :- 2 and it's percentage : 11.11111111111111

 Total NaN values in row 21478 :- 0 and it's percentage : 0.0
 Total NaN values in row 21479 :- 0 and it's percentage : 0.0
 Total NaN values in row 21480 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21481 :- 0 and it's percentage : 0.0
 Total NaN values in row 21482 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21483 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21484 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21486 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21487 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21489 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21491 :- 0 and it's percentage : 0.0
 Total NaN values in row 21492 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21493 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21494 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21495 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21496 :- 0 and it's percentage : 0.0
 Total NaN values in row 21497 :- 0 and it's percentage : 0.0
 Total NaN values in row 21498 :- 0 and it's percentage : 0.0
 Total NaN values in row 21499 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21500 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21501 :- 0 and it's percentage : 0.0
 Total NaN values in row 21502 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21503 :- 0 and it's percentage : 0.0
 Total NaN values in row 21504 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21505 :- 0 and it's percentage : 0.0
 Total NaN values in row 21506 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21507 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21508 :- 0 and it's percentage : 0.0
 Total NaN values in row 21509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21510 :- 0 and it's percentage : 0.0
 Total NaN values in row 21511 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21513 :- 0 and it's percentage : 0.0
 Total NaN values in row 21514 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21515 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21516 :- 0 and it's percentage : 0.0
 Total NaN values in row 21517 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21519 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21520 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21521 :- 0 and it's percentage : 0.0
 Total NaN values in row 21522 :- 0 and it's percentage : 0.0
 Total NaN values in row 21523 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21524 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21525 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21526 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21528 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21529 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21530 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21531 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21532 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 21533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21534 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21535 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21536 :- 0 and it's percentage : 0.0
 Total NaN values in row 21537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21538 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21539 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21540 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21541 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21542 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21543 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21544 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21545 :- 0 and it's percentage : 0.0
 Total NaN values in row 21546 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21547 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21549 :- 0 and it's percentage : 0.0
 Total NaN values in row 21550 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21551 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21552 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21553 :- 0 and it's percentage : 0.0
 Total NaN values in row 21554 :- 0 and it's percentage : 0.0
 Total NaN values in row 21555 :- 0 and it's percentage : 0.0
 Total NaN values in row 21556 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21557 :- 0 and it's percentage : 0.0
 Total NaN values in row 21558 :- 0 and it's percentage : 0.0
 Total NaN values in row 21559 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21560 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21561 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21563 :- 0 and it's percentage : 0.0
 Total NaN values in row 21564 :- 0 and it's percentage : 0.0
 Total NaN values in row 21565 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21566 :- 0 and it's percentage : 0.0
 Total NaN values in row 21567 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21568 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21569 :- 0 and it's percentage : 0.0
 Total NaN values in row 21570 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21571 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21572 :- 0 and it's percentage : 0.0
 Total NaN values in row 21573 :- 0 and it's percentage : 0.0
 Total NaN values in row 21574 :- 0 and it's percentage : 0.0
 Total NaN values in row 21575 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21576 :- 0 and it's percentage : 0.0
 Total NaN values in row 21577 :- 0 and it's percentage : 0.0
 Total NaN values in row 21578 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 21579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21580 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21581 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21582 :- 0 and it's percentage : 0.0
 Total NaN values in row 21583 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21584 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21585 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21586 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21587 :- 0 and it's percentage : 0.0
 Total NaN values in row 21588 :- 0 and it's percentage : 0.0
 Total NaN values in row 21589 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21590 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21591 :- 0 and it's percentage : 0.0
 Total NaN values in row 21592 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21593 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21594 :- 0 and it's percentage : 0.0
 Total NaN values in row 21595 :- 0 and it's percentage : 0.0
 Total NaN values in row 21596 :- 0 and it's percentage : 0.0
 Total NaN values in row 21597 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21598 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21599 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21600 :- 0 and it's percentage : 0.0
 Total NaN values in row 21601 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21602 :- 0 and it's percentage : 0.0
 Total NaN values in row 21603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21604 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21605 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21606 :- 0 and it's percentage : 0.0
 Total NaN values in row 21607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21608 :- 0 and it's percentage : 0.0
 Total NaN values in row 21609 :- 0 and it's percentage : 0.0
 Total NaN values in row 21610 :- 0 and it's percentage : 0.0
 Total NaN values in row 21611 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21612 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21613 :- 0 and it's percentage : 0.0
 Total NaN values in row 21614 :- 0 and it's percentage : 0.0
 Total NaN values in row 21615 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21616 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21617 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21618 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21619 :- 0 and it's percentage : 0.0

 Total NaN values in row 21620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21621 :- 0 and it's percentage : 0.0
 Total NaN values in row 21622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21623 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21624 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21625 :- 0 and it's percentage : 0.0
 Total NaN values in row 21626 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21627 :- 0 and it's percentage : 0.0
 Total NaN values in row 21628 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21629 :- 0 and it's percentage : 0.0
 Total NaN values in row 21630 :- 0 and it's percentage : 0.0
 Total NaN values in row 21631 :- 0 and it's percentage : 0.0
 Total NaN values in row 21632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21633 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21635 :- 0 and it's percentage : 0.0
 Total NaN values in row 21636 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21637 :- 0 and it's percentage : 0.0
 Total NaN values in row 21638 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21639 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21640 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21641 :- 0 and it's percentage : 0.0
 Total NaN values in row 21642 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21643 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21644 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21645 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21646 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21647 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21648 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21649 :- 0 and it's percentage : 0.0
 Total NaN values in row 21650 :- 0 and it's percentage : 0.0
 Total NaN values in row 21651 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21653 :- 0 and it's percentage : 0.0
 Total NaN values in row 21654 :- 0 and it's percentage : 0.0
 Total NaN values in row 21655 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21656 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21657 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21658 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21659 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21660 :- 0 and it's percentage : 0.0
 Total NaN values in row 21661 :- 0 and it's percentage : 0.0
 Total NaN values in row 21662 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21664 :- 0 and it's percentage : 0.0
 Total NaN values in row 21665 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21666 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21667 :- 0 and it's percentage : 0.0
 Total NaN values in row 21668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21669 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21670 :- 0 and it's percentage : 0.0
 Total NaN values in row 21671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21672 :- 0 and it's percentage : 0.0
 Total NaN values in row 21673 :- 0 and it's percentage : 0.0
 Total NaN values in row 21674 :- 0 and it's percentage : 0.0
 Total NaN values in row 21675 :- 0 and it's percentage : 0.0
 Total NaN values in row 21676 :- 0 and it's percentage : 0.0
 Total NaN values in row 21677 :- 0 and it's percentage : 0.0
 Total NaN values in row 21678 :- 0 and it's percentage : 0.0
 Total NaN values in row 21679 :- 0 and it's percentage : 0.0
 Total NaN values in row 21680 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21681 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21682 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 21683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21684 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21685 :- 0 and it's percentage : 0.0
 Total NaN values in row 21686 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21687 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21689 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21690 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21691 :- 0 and it's percentage : 0.0
 Total NaN values in row 21692 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21693 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21694 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21695 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21696 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21697 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21698 :- 0 and it's percentage : 0.0
 Total NaN values in row 21699 :- 0 and it's percentage : 0.0
 Total NaN values in row 21700 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21701 :- 0 and it's percentage : 0.0
 Total NaN values in row 21702 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21703 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21704 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21705 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21706 :- 0 and it's percentage : 0.0
 Total NaN values in row 21707 :- 0 and it's percentage : 0.0
 Total NaN values in row 21708 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21709 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21710 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21711 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21712 :- 0 and it's percentage : 0.0
 Total NaN values in row 21713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21714 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21715 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21716 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21717 :- 0 and it's percentage : 0.0
 Total NaN values in row 21718 :- 0 and it's percentage : 0.0
 Total NaN values in row 21719 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21720 :- 0 and it's percentage : 0.0
 Total NaN values in row 21721 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21722 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21723 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21724 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21725 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21726 :- 0 and it's percentage : 0.0
 Total NaN values in row 21727 :- 0 and it's percentage : 0.0
 Total NaN values in row 21728 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21729 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21730 :- 0 and it's percentage : 0.0
 Total NaN values in row 21731 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21732 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21733 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21735 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21736 :- 0 and it's percentage : 0.0
 Total NaN values in row 21737 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21738 :- 0 and it's percentage : 0.0
 Total NaN values in row 21739 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21740 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21741 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21744 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21745 :- 0 and it's percentage : 0.0
 Total NaN values in row 21746 :- 0 and it's percentage : 0.0
 Total NaN values in row 21747 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21748 :- 0 and it's percentage : 0.0
 Total NaN values in row 21749 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21750 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21751 :- 0 and it's percentage : 0.0
 Total NaN values in row 21752 :- 0 and it's percentage : 0.0
 Total NaN values in row 21753 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21755 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21756 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21757 :- 0 and it's percentage : 0.0
 Total NaN values in row 21758 :- 0 and it's percentage : 0.0
 Total NaN values in row 21759 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21761 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21762 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21763 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21764 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21765 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21766 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21767 :- 0 and it's percentage : 0.0
 Total NaN values in row 21768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21770 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21771 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21772 :- 0 and it's percentage : 0.0
 Total NaN values in row 21773 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21774 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21775 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21776 :- 0 and it's percentage : 0.0
 Total NaN values in row 21777 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21778 :- 0 and it's percentage : 0.0
 Total NaN values in row 21779 :- 0 and it's percentage : 0.0
 Total NaN values in row 21780 :- 0 and it's percentage : 0.0
 Total NaN values in row 21781 :- 0 and it's percentage : 0.0
 Total NaN values in row 21782 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21783 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21784 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21785 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21787 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21788 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21789 :- 0 and it's percentage : 0.0
 Total NaN values in row 21790 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21791 :- 0 and it's percentage : 0.0
 Total NaN values in row 21792 :- 0 and it's percentage : 0.0
 Total NaN values in row 21793 :- 0 and it's percentage : 0.0
 Total NaN values in row 21794 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21795 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21796 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21797 :- 0 and it's percentage : 0.0
 Total NaN values in row 21798 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 21799 :- 0 and it's percentage : 0.0
 Total NaN values in row 21800 :- 0 and it's percentage : 0.0
 Total NaN values in row 21801 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21802 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21803 :- 0 and it's percentage : 0.0
 Total NaN values in row 21804 :- 0 and it's percentage : 0.0
 Total NaN values in row 21805 :- 0 and it's percentage : 0.0
 Total NaN values in row 21806 :- 0 and it's percentage : 0.0
 Total NaN values in row 21807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21808 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21809 :- 0 and it's percentage : 0.0
 Total NaN values in row 21810 :- 0 and it's percentage : 0.0
 Total NaN values in row 21811 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21813 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21814 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21815 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21816 :- 0 and it's percentage : 0.0
 Total NaN values in row 21817 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21818 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21819 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21820 :- 0 and it's percentage : 0.0
 Total NaN values in row 21821 :- 0 and it's percentage : 0.0
 Total NaN values in row 21822 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21823 :- 0 and it's percentage : 0.0
 Total NaN values in row 21824 :- 0 and it's percentage : 0.0
 Total NaN values in row 21825 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21826 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21827 :- 0 and it's percentage : 0.0
 Total NaN values in row 21828 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21830 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21831 :- 0 and it's percentage : 0.0
 Total NaN values in row 21832 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21833 :- 0 and it's percentage : 0.0
 Total NaN values in row 21834 :- 0 and it's percentage : 0.0
 Total NaN values in row 21835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21836 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21837 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21838 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21839 :- 0 and it's percentage : 0.0
 Total NaN values in row 21840 :- 0 and it's percentage : 0.0
 Total NaN values in row 21841 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21842 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21843 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21844 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21845 :- 0 and it's percentage : 0.0
 Total NaN values in row 21846 :- 0 and it's percentage : 0.0
 Total NaN values in row 21847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21848 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21849 :- 0 and it's percentage : 0.0
 Total NaN values in row 21850 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21851 :- 0 and it's percentage : 0.0
 Total NaN values in row 21852 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21853 :- 0 and it's percentage : 0.0
 Total NaN values in row 21854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21855 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21856 :- 0 and it's percentage : 0.0
 Total NaN values in row 21857 :- 0 and it's percentage : 0.0
 Total NaN values in row 21858 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21859 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21860 :- 0 and it's percentage : 0.0
 Total NaN values in row 21861 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21862 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21863 :- 0 and it's percentage : 0.0
 Total NaN values in row 21864 :- 0 and it's percentage : 0.0
 Total NaN values in row 21865 :- 0 and it's percentage : 0.0
 Total NaN values in row 21866 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21867 :- 0 and it's percentage : 0.0
 Total NaN values in row 21868 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21869 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21870 :- 0 and it's percentage : 0.0
 Total NaN values in row 21871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21872 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21873 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21874 :- 0 and it's percentage : 0.0
 Total NaN values in row 21875 :- 0 and it's percentage : 0.0
 Total NaN values in row 21876 :- 0 and it's percentage : 0.0
 Total NaN values in row 21877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21878 :- 0 and it's percentage : 0.0
 Total NaN values in row 21879 :- 0 and it's percentage : 0.0
 Total NaN values in row 21880 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21881 :- 0 and it's percentage : 0.0
 Total NaN values in row 21882 :- 0 and it's percentage : 0.0
 Total NaN values in row 21883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21884 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21885 :- 0 and it's percentage : 0.0
 Total NaN values in row 21886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21887 :- 0 and it's percentage : 0.0
 Total NaN values in row 21888 :- 0 and it's percentage : 0.0
 Total NaN values in row 21889 :- 0 and it's percentage : 0.0
 Total NaN values in row 21890 :- 0 and it's percentage : 0.0
 Total NaN values in row 21891 :- 0 and it's percentage : 0.0
 Total NaN values in row 21892 :- 0 and it's percentage : 0.0
 Total NaN values in row 21893 :- 0 and it's percentage : 0.0
 Total NaN values in row 21894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21895 :- 0 and it's percentage : 0.0
 Total NaN values in row 21896 :- 0 and it's percentage : 0.0
 Total NaN values in row 21897 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21898 :- 0 and it's percentage : 0.0
 Total NaN values in row 21899 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21900 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21901 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21902 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21903 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21904 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21905 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21906 :- 0 and it's percentage : 0.0
 Total NaN values in row 21907 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21908 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21909 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21910 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21911 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21912 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21913 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21914 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21915 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 21916 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21917 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21918 :- 0 and it's percentage : 0.0
 Total NaN values in row 21919 :- 0 and it's percentage : 0.0
 Total NaN values in row 21920 :- 0 and it's percentage : 0.0
 Total NaN values in row 21921 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21922 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21924 :- 0 and it's percentage : 0.0
 Total NaN values in row 21925 :- 0 and it's percentage : 0.0
 Total NaN values in row 21926 :- 0 and it's percentage : 0.0
 Total NaN values in row 21927 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21928 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21929 :- 0 and it's percentage : 0.0
 Total NaN values in row 21930 :- 0 and it's percentage : 0.0
 Total NaN values in row 21931 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21932 :- 0 and it's percentage : 0.0
 Total NaN values in row 21933 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21934 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21935 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21936 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 21937 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21938 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21939 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21940 :- 0 and it's percentage : 0.0
 Total NaN values in row 21941 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21943 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21944 :- 0 and it's percentage : 0.0
 Total NaN values in row 21945 :- 0 and it's percentage : 0.0
 Total NaN values in row 21946 :- 0 and it's percentage : 0.0
 Total NaN values in row 21947 :- 0 and it's percentage : 0.0
 Total NaN values in row 21948 :- 0 and it's percentage : 0.0
 Total NaN values in row 21949 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21950 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21951 :- 0 and it's percentage : 0.0
 Total NaN values in row 21952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21953 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21954 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21955 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21956 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21957 :- 0 and it's percentage : 0.0
 Total NaN values in row 21958 :- 0 and it's percentage : 0.0
 Total NaN values in row 21959 :- 0 and it's percentage : 0.0
 Total NaN values in row 21960 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21961 :- 0 and it's percentage : 0.0
 Total NaN values in row 21962 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21963 :- 0 and it's percentage : 0.0
 Total NaN values in row 21964 :- 0 and it's percentage : 0.0
 Total NaN values in row 21965 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21966 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21967 :- 0 and it's percentage : 0.0
 Total NaN values in row 21968 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21969 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21970 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 21971 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 21972 :- 0 and it's percentage : 0.0
 Total NaN values in row 21973 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21975 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21976 :- 0 and it's percentage : 0.0
 Total NaN values in row 21977 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21978 :- 0 and it's percentage : 0.0
 Total NaN values in row 21979 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21980 :- 0 and it's percentage : 0.0
 Total NaN values in row 21981 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 21982 :- 0 and it's percentage : 0.0
 Total NaN values in row 21983 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21984 :- 0 and it's percentage : 0.0
 Total NaN values in row 21985 :- 0 and it's percentage : 0.0
 Total NaN values in row 21986 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21987 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21988 :- 0 and it's percentage : 0.0
 Total NaN values in row 21989 :- 0 and it's percentage : 0.0
 Total NaN values in row 21990 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21991 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21992 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21993 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21994 :- 0 and it's percentage : 0.0
 Total NaN values in row 21995 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21996 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21997 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21998 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 21999 :- 0 and it's percentage : 0.0
 Total NaN values in row 22000 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22001 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22002 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22003 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22004 :- 0 and it's percentage : 0.0
 Total NaN values in row 22005 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22006 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22007 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22008 :- 0 and it's percentage : 0.0
 Total NaN values in row 22009 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22010 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22011 :- 0 and it's percentage : 0.0
 Total NaN values in row 22012 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22013 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22015 :- 0 and it's percentage : 0.0
 Total NaN values in row 22016 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22017 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22018 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22019 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22020 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22021 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22022 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22023 :- 0 and it's percentage : 0.0
 Total NaN values in row 22024 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22025 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22026 :- 0 and it's percentage : 0.0
 Total NaN values in row 22027 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22028 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22029 :- 0 and it's percentage : 0.0
 Total NaN values in row 22030 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 22031 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22032 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22033 :- 0 and it's percentage : 0.0
 Total NaN values in row 22034 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22035 :- 0 and it's percentage : 0.0
 Total NaN values in row 22036 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22037 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22038 :- 0 and it's percentage : 0.0
 Total NaN values in row 22039 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22040 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22041 :- 0 and it's percentage : 0.0
 Total NaN values in row 22042 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22043 :- 0 and it's percentage : 0.0
 Total NaN values in row 22044 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22045 :- 0 and it's percentage : 0.0
 Total NaN values in row 22046 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22047 :- 0 and it's percentage : 0.0
 Total NaN values in row 22048 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22049 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22051 :- 0 and it's percentage : 0.0
 Total NaN values in row 22052 :- 0 and it's percentage : 0.0
 Total NaN values in row 22053 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22054 :- 0 and it's percentage : 0.0
 Total NaN values in row 22055 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22056 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22058 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22059 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22060 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22061 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22062 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22063 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22064 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22065 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22066 :- 0 and it's percentage : 0.0
 Total NaN values in row 22067 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22068 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22070 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22071 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22072 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 22073 :- 0 and it's percentage : 0.0

 Total NaN values in row 22074 :- 0 and it's percentage : 0.0
 Total NaN values in row 22075 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22076 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22077 :- 0 and it's percentage : 0.0
 Total NaN values in row 22078 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22079 :- 0 and it's percentage : 0.0
 Total NaN values in row 22080 :- 0 and it's percentage : 0.0
 Total NaN values in row 22081 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22082 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22083 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22084 :- 0 and it's percentage : 0.0
 Total NaN values in row 22085 :- 0 and it's percentage : 0.0
 Total NaN values in row 22086 :- 0 and it's percentage : 0.0
 Total NaN values in row 22087 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22088 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22089 :- 0 and it's percentage : 0.0
 Total NaN values in row 22090 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22091 :- 0 and it's percentage : 0.0
 Total NaN values in row 22092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22093 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22095 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22096 :- 0 and it's percentage : 0.0
 Total NaN values in row 22097 :- 0 and it's percentage : 0.0
 Total NaN values in row 22098 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22099 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22100 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22102 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22103 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22104 :- 0 and it's percentage : 0.0
 Total NaN values in row 22105 :- 0 and it's percentage : 0.0
 Total NaN values in row 22106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22107 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22108 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22109 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 22110 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22111 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22112 :- 0 and it's percentage : 0.0
 Total NaN values in row 22113 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22114 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22115 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22116 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22118 :- 0 and it's percentage : 0.0
 Total NaN values in row 22119 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22120 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22121 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22122 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22123 :- 0 and it's percentage : 0.0
 Total NaN values in row 22124 :- 0 and it's percentage : 0.0
 Total NaN values in row 22125 :- 0 and it's percentage : 0.0
 Total NaN values in row 22126 :- 0 and it's percentage : 0.0
 Total NaN values in row 22127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22128 :- 0 and it's percentage : 0.0
 Total NaN values in row 22129 :- 0 and it's percentage : 0.0
 Total NaN values in row 22130 :- 0 and it's percentage : 0.0
 Total NaN values in row 22131 :- 0 and it's percentage : 0.0
 Total NaN values in row 22132 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22133 :- 0 and it's percentage : 0.0
 Total NaN values in row 22134 :- 0 and it's percentage : 0.0
 Total NaN values in row 22135 :- 0 and it's percentage : 0.0
 Total NaN values in row 22136 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22137 :- 0 and it's percentage : 0.0
 Total NaN values in row 22138 :- 0 and it's percentage : 0.0
 Total NaN values in row 22139 :- 0 and it's percentage : 0.0
 Total NaN values in row 22140 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22141 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22142 :- 0 and it's percentage : 0.0
 Total NaN values in row 22143 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22144 :- 0 and it's percentage : 0.0
 Total NaN values in row 22145 :- 0 and it's percentage : 0.0
 Total NaN values in row 22146 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22147 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22148 :- 0 and it's percentage : 0.0
 Total NaN values in row 22149 :- 0 and it's percentage : 0.0
 Total NaN values in row 22150 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22151 :- 0 and it's percentage : 0.0
 Total NaN values in row 22152 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22154 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22155 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22156 :- 0 and it's percentage : 0.0
 Total NaN values in row 22157 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22158 :- 0 and it's percentage : 0.0
 Total NaN values in row 22159 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22160 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22161 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22162 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22163 :- 0 and it's percentage : 0.0
 Total NaN values in row 22164 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22165 :- 0 and it's percentage : 0.0
 Total NaN values in row 22166 :- 0 and it's percentage : 0.0
 Total NaN values in row 22167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22168 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22169 :- 0 and it's percentage : 0.0
 Total NaN values in row 22170 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22171 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22172 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22173 :- 0 and it's percentage : 0.0
 Total NaN values in row 22174 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22175 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22176 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22177 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22178 :- 0 and it's percentage : 0.0
 Total NaN values in row 22179 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22180 :- 0 and it's percentage : 0.0
 Total NaN values in row 22181 :- 0 and it's percentage : 0.0
 Total NaN values in row 22182 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22183 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22184 :- 0 and it's percentage : 0.0
 Total NaN values in row 22185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22186 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22187 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22188 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22189 :- 0 and it's percentage : 0.0
 Total NaN values in row 22190 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22191 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22192 :- 0 and it's percentage : 0.0
 Total NaN values in row 22193 :- 0 and it's percentage : 0.0
 Total NaN values in row 22194 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22195 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22196 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22197 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22198 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22199 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22201 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22202 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22204 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22205 :- 0 and it's percentage : 0.0
 Total NaN values in row 22206 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22207 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22208 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22209 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22210 :- 0 and it's percentage : 0.0
 Total NaN values in row 22211 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22212 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22213 :- 0 and it's percentage : 0.0
 Total NaN values in row 22214 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22215 :- 0 and it's percentage : 0.0
 Total NaN values in row 22216 :- 0 and it's percentage : 0.0
 Total NaN values in row 22217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22218 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22219 :- 0 and it's percentage : 0.0
 Total NaN values in row 22220 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22221 :- 0 and it's percentage : 0.0
 Total NaN values in row 22222 :- 0 and it's percentage : 0.0
 Total NaN values in row 22223 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22224 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22225 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22226 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22227 :- 0 and it's percentage : 0.0
 Total NaN values in row 22228 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22229 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22230 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22231 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22232 :- 0 and it's percentage : 0.0
 Total NaN values in row 22233 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22234 :- 0 and it's percentage : 0.0
 Total NaN values in row 22235 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22236 :- 0 and it's percentage : 0.0
 Total NaN values in row 22237 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22238 :- 0 and it's percentage : 0.0
 Total NaN values in row 22239 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22240 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22241 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22242 :- 0 and it's percentage : 0.0
 Total NaN values in row 22243 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22244 :- 0 and it's percentage : 0.0
 Total NaN values in row 22245 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22246 :- 0 and it's percentage : 0.0
 Total NaN values in row 22247 :- 0 and it's percentage : 0.0
 Total NaN values in row 22248 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22249 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22250 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22251 :- 0 and it's percentage : 0.0
 Total NaN values in row 22252 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22253 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22254 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22255 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22256 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 22257 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22258 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22259 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22260 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 22261 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22262 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22263 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22264 :- 0 and it's percentage : 0.0
 Total NaN values in row 22265 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22266 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22268 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22269 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22270 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22271 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22272 :- 0 and it's percentage : 0.0
 Total NaN values in row 22273 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22274 :- 0 and it's percentage : 0.0
 Total NaN values in row 22275 :- 0 and it's percentage : 0.0
 Total NaN values in row 22276 :- 0 and it's percentage : 0.0
 Total NaN values in row 22277 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22279 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22280 :- 0 and it's percentage : 0.0
 Total NaN values in row 22281 :- 0 and it's percentage : 0.0
 Total NaN values in row 22282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22283 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22284 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22285 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22286 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22287 :- 0 and it's percentage : 0.0
 Total NaN values in row 22288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22289 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22290 :- 0 and it's percentage : 0.0
 Total NaN values in row 22291 :- 0 and it's percentage : 0.0
 Total NaN values in row 22292 :- 0 and it's percentage : 0.0
 Total NaN values in row 22293 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22294 :- 0 and it's percentage : 0.0
 Total NaN values in row 22295 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22296 :- 0 and it's percentage : 0.0
 Total NaN values in row 22297 :- 0 and it's percentage : 0.0
 Total NaN values in row 22298 :- 0 and it's percentage : 0.0
 Total NaN values in row 22299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22300 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22301 :- 0 and it's percentage : 0.0
 Total NaN values in row 22302 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22303 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22304 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22305 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22306 :- 0 and it's percentage : 0.0
 Total NaN values in row 22307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22308 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22309 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22310 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22311 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22312 :- 0 and it's percentage : 0.0
 Total NaN values in row 22313 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22314 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22315 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22316 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22317 :- 0 and it's percentage : 0.0
 Total NaN values in row 22318 :- 0 and it's percentage : 0.0
 Total NaN values in row 22319 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22320 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22321 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22322 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22323 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22324 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22325 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22326 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22327 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22329 :- 0 and it's percentage : 0.0
 Total NaN values in row 22330 :- 0 and it's percentage : 0.0
 Total NaN values in row 22331 :- 0 and it's percentage : 0.0
 Total NaN values in row 22332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22333 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22334 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22335 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 22336 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22337 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22338 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22339 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22340 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22341 :- 0 and it's percentage : 0.0
 Total NaN values in row 22342 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22344 :- 0 and it's percentage : 0.0
 Total NaN values in row 22345 :- 0 and it's percentage : 0.0
 Total NaN values in row 22346 :- 0 and it's percentage : 0.0
 Total NaN values in row 22347 :- 0 and it's percentage : 0.0
 Total NaN values in row 22348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22349 :- 0 and it's percentage : 0.0
 Total NaN values in row 22350 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22351 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22352 :- 0 and it's percentage : 0.0
 Total NaN values in row 22353 :- 0 and it's percentage : 0.0
 Total NaN values in row 22354 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22355 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22356 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 22357 :- 0 and it's percentage : 0.0
 Total NaN values in row 22358 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22359 :- 0 and it's percentage : 0.0
 Total NaN values in row 22360 :- 0 and it's percentage : 0.0
 Total NaN values in row 22361 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22362 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22363 :- 0 and it's percentage : 0.0
 Total NaN values in row 22364 :- 0 and it's percentage : 0.0
 Total NaN values in row 22365 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22366 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22367 :- 0 and it's percentage : 0.0
 Total NaN values in row 22368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22369 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22370 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22371 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22372 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22373 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22375 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22376 :- 0 and it's percentage : 0.0
 Total NaN values in row 22377 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22378 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22379 :- 0 and it's percentage : 0.0
 Total NaN values in row 22380 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22381 :- 0 and it's percentage : 0.0
 Total NaN values in row 22382 :- 0 and it's percentage : 0.0
 Total NaN values in row 22383 :- 0 and it's percentage : 0.0
 Total NaN values in row 22384 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22385 :- 0 and it's percentage : 0.0
 Total NaN values in row 22386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22387 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22388 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22389 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22390 :- 0 and it's percentage : 0.0

 Total NaN values in row 22391 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22392 :- 0 and it's percentage : 0.0
 Total NaN values in row 22393 :- 0 and it's percentage : 0.0
 Total NaN values in row 22394 :- 0 and it's percentage : 0.0
 Total NaN values in row 22395 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22396 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22397 :- 0 and it's percentage : 0.0
 Total NaN values in row 22398 :- 0 and it's percentage : 0.0
 Total NaN values in row 22399 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22401 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22402 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22403 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22404 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22405 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22406 :- 0 and it's percentage : 0.0
 Total NaN values in row 22407 :- 0 and it's percentage : 0.0
 Total NaN values in row 22408 :- 0 and it's percentage : 0.0
 Total NaN values in row 22409 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22410 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22411 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22412 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22413 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22414 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22415 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22416 :- 0 and it's percentage : 0.0
 Total NaN values in row 22417 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22418 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22419 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22420 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22421 :- 0 and it's percentage : 0.0
 Total NaN values in row 22422 :- 0 and it's percentage : 0.0
 Total NaN values in row 22423 :- 0 and it's percentage : 0.0
 Total NaN values in row 22424 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22425 :- 0 and it's percentage : 0.0
 Total NaN values in row 22426 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22427 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22428 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22429 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22431 :- 0 and it's percentage : 0.0
 Total NaN values in row 22432 :- 0 and it's percentage : 0.0
 Total NaN values in row 22433 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22434 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22435 :- 0 and it's percentage : 0.0
 Total NaN values in row 22436 :- 0 and it's percentage : 0.0
 Total NaN values in row 22437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22438 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22439 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22441 :- 0 and it's percentage : 0.0
 Total NaN values in row 22442 :- 0 and it's percentage : 0.0
 Total NaN values in row 22443 :- 0 and it's percentage : 0.0
 Total NaN values in row 22444 :- 0 and it's percentage : 0.0
 Total NaN values in row 22445 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22447 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22448 :- 0 and it's percentage : 0.0
 Total NaN values in row 22449 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22450 :- 0 and it's percentage : 0.0
 Total NaN values in row 22451 :- 0 and it's percentage : 0.0
 Total NaN values in row 22452 :- 0 and it's percentage : 0.0
 Total NaN values in row 22453 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22454 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22456 :- 0 and it's percentage : 0.0
 Total NaN values in row 22457 :- 0 and it's percentage : 0.0
 Total NaN values in row 22458 :- 0 and it's percentage : 0.0
 Total NaN values in row 22459 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22460 :- 0 and it's percentage : 0.0
 Total NaN values in row 22461 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22462 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22463 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22464 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22465 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22466 :- 0 and it's percentage : 0.0
 Total NaN values in row 22467 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22468 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22469 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22472 :- 0 and it's percentage : 0.0
 Total NaN values in row 22473 :- 0 and it's percentage : 0.0
 Total NaN values in row 22474 :- 0 and it's percentage : 0.0
 Total NaN values in row 22475 :- 0 and it's percentage : 0.0
 Total NaN values in row 22476 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22477 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22479 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22480 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22481 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22482 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22483 :- 0 and it's percentage : 0.0
 Total NaN values in row 22484 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22486 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22487 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22489 :- 0 and it's percentage : 0.0
 Total NaN values in row 22490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22491 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22492 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22493 :- 0 and it's percentage : 0.0
 Total NaN values in row 22494 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22495 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22496 :- 0 and it's percentage : 0.0
 Total NaN values in row 22497 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22498 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22500 :- 0 and it's percentage : 0.0
 Total NaN values in row 22501 :- 0 and it's percentage : 0.0
 Total NaN values in row 22502 :- 0 and it's percentage : 0.0
 Total NaN values in row 22503 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22504 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22505 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22506 :- 0 and it's percentage : 0.0
 Total NaN values in row 22507 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22508 :- 0 and it's percentage : 0.0
 Total NaN values in row 22509 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22511 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22513 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22514 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22515 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22517 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22519 :- 0 and it's percentage : 0.0
 Total NaN values in row 22520 :- 0 and it's percentage : 0.0
 Total NaN values in row 22521 :- 0 and it's percentage : 0.0
 Total NaN values in row 22522 :- 0 and it's percentage : 0.0
 Total NaN values in row 22523 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22524 :- 0 and it's percentage : 0.0
 Total NaN values in row 22525 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22526 :- 0 and it's percentage : 0.0
 Total NaN values in row 22527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22528 :- 0 and it's percentage : 0.0
 Total NaN values in row 22529 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22530 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22531 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22532 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22533 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22534 :- 0 and it's percentage : 0.0
 Total NaN values in row 22535 :- 0 and it's percentage : 0.0
 Total NaN values in row 22536 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22537 :- 0 and it's percentage : 0.0
 Total NaN values in row 22538 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22539 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22540 :- 0 and it's percentage : 0.0
 Total NaN values in row 22541 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22542 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22543 :- 0 and it's percentage : 0.0
 Total NaN values in row 22544 :- 0 and it's percentage : 0.0
 Total NaN values in row 22545 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22546 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22547 :- 0 and it's percentage : 0.0
 Total NaN values in row 22548 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22549 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22550 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22551 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22552 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 22553 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22554 :- 0 and it's percentage : 0.0
 Total NaN values in row 22555 :- 0 and it's percentage : 0.0
 Total NaN values in row 22556 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22557 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22558 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22559 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22560 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22561 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22562 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22563 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22564 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22565 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22566 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22567 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22568 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22569 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22570 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22571 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22572 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22573 :- 0 and it's percentage : 0.0
 Total NaN values in row 22574 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22575 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22576 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22577 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22578 :- 0 and it's percentage : 0.0
 Total NaN values in row 22579 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22580 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22581 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22582 :- 0 and it's percentage : 0.0
 Total NaN values in row 22583 :- 0 and it's percentage : 0.0
 Total NaN values in row 22584 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22585 :- 0 and it's percentage : 0.0
 Total NaN values in row 22586 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22587 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22588 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22589 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22590 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22591 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22592 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22593 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22594 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22595 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22596 :- 0 and it's percentage : 0.0
 Total NaN values in row 22597 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22598 :- 0 and it's percentage : 0.0
 Total NaN values in row 22599 :- 0 and it's percentage : 0.0
 Total NaN values in row 22600 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22601 :- 0 and it's percentage : 0.0
 Total NaN values in row 22602 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22603 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22604 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22605 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22606 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22607 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22608 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22609 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22610 :- 0 and it's percentage : 0.0
 Total NaN values in row 22611 :- 0 and it's percentage : 0.0
 Total NaN values in row 22612 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22613 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22614 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22615 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22616 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22617 :- 0 and it's percentage : 0.0
 Total NaN values in row 22618 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22619 :- 0 and it's percentage : 0.0
 Total NaN values in row 22620 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22621 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22622 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22623 :- 0 and it's percentage : 0.0
 Total NaN values in row 22624 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22625 :- 0 and it's percentage : 0.0
 Total NaN values in row 22626 :- 0 and it's percentage : 0.0
 Total NaN values in row 22627 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22628 :- 0 and it's percentage : 0.0
 Total NaN values in row 22629 :- 0 and it's percentage : 0.0
 Total NaN values in row 22630 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22631 :- 0 and it's percentage : 0.0
 Total NaN values in row 22632 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22633 :- 0 and it's percentage : 0.0
 Total NaN values in row 22634 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22635 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22636 :- 0 and it's percentage : 0.0
 Total NaN values in row 22637 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22638 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22639 :- 0 and it's percentage : 0.0
 Total NaN values in row 22640 :- 0 and it's percentage : 0.0
 Total NaN values in row 22641 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22642 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22643 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22644 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22645 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22646 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22647 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22648 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22649 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22650 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22651 :- 0 and it's percentage : 0.0
 Total NaN values in row 22652 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22653 :- 0 and it's percentage : 0.0
 Total NaN values in row 22654 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22655 :- 0 and it's percentage : 0.0
 Total NaN values in row 22656 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22657 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22658 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22659 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22660 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22661 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22662 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22663 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22664 :- 0 and it's percentage : 0.0
 Total NaN values in row 22665 :- 0 and it's percentage : 0.0
 Total NaN values in row 22666 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22667 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22668 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22669 :- 0 and it's percentage : 0.0
 Total NaN values in row 22670 :- 0 and it's percentage : 0.0
 Total NaN values in row 22671 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22672 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22673 :- 0 and it's percentage : 0.0
 Total NaN values in row 22674 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22675 :- 0 and it's percentage : 0.0
 Total NaN values in row 22676 :- 0 and it's percentage : 0.0
 Total NaN values in row 22677 :- 0 and it's percentage : 0.0
 Total NaN values in row 22678 :- 0 and it's percentage : 0.0
 Total NaN values in row 22679 :- 0 and it's percentage : 0.0
 Total NaN values in row 22680 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22681 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22682 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22683 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22684 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22685 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22686 :- 0 and it's percentage : 0.0
 Total NaN values in row 22687 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22688 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22689 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22690 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22691 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22692 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 22693 :- 0 and it's percentage : 0.0
 Total NaN values in row 22694 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22695 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22696 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22697 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22698 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22699 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22700 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22701 :- 0 and it's percentage : 0.0
 Total NaN values in row 22702 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22703 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22704 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22705 :- 0 and it's percentage : 0.0
 Total NaN values in row 22706 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22707 :- 0 and it's percentage : 0.0
 Total NaN values in row 22708 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22709 :- 0 and it's percentage : 0.0
 Total NaN values in row 22710 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22711 :- 0 and it's percentage : 0.0
 Total NaN values in row 22712 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22713 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22714 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22715 :- 0 and it's percentage : 0.0
 Total NaN values in row 22716 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22717 :- 0 and it's percentage : 0.0
 Total NaN values in row 22718 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22719 :- 0 and it's percentage : 0.0
 Total NaN values in row 22720 :- 0 and it's percentage : 0.0
 Total NaN values in row 22721 :- 0 and it's percentage : 0.0
 Total NaN values in row 22722 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22723 :- 0 and it's percentage : 0.0
 Total NaN values in row 22724 :- 0 and it's percentage : 0.0
 Total NaN values in row 22725 :- 0 and it's percentage : 0.0
 Total NaN values in row 22726 :- 0 and it's percentage : 0.0
 Total NaN values in row 22727 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22728 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22729 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22730 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22731 :- 0 and it's percentage : 0.0
 Total NaN values in row 22732 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22733 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22734 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22735 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22736 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22737 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22738 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22739 :- 0 and it's percentage : 0.0
 Total NaN values in row 22740 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22741 :- 0 and it's percentage : 0.0
 Total NaN values in row 22742 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22743 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22744 :- 0 and it's percentage : 0.0
 Total NaN values in row 22745 :- 0 and it's percentage : 0.0
 Total NaN values in row 22746 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22747 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22748 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22749 :- 0 and it's percentage : 0.0
 Total NaN values in row 22750 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22751 :- 0 and it's percentage : 0.0
 Total NaN values in row 22752 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22753 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22754 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22755 :- 0 and it's percentage : 0.0
 Total NaN values in row 22756 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22757 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22758 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22759 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22760 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22761 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22762 :- 0 and it's percentage : 0.0
 Total NaN values in row 22763 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22764 :- 0 and it's percentage : 0.0
 Total NaN values in row 22765 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22766 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22767 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22768 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22769 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22770 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22771 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22772 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22773 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22774 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22775 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22776 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22777 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22778 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22779 :- 0 and it's percentage : 0.0
 Total NaN values in row 22780 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22781 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22782 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22783 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22784 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22785 :- 0 and it's percentage : 0.0
 Total NaN values in row 22786 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22787 :- 0 and it's percentage : 0.0
 Total NaN values in row 22788 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22789 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22790 :- 0 and it's percentage : 0.0
 Total NaN values in row 22791 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22792 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22793 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22794 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22795 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22796 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22797 :- 0 and it's percentage : 0.0
 Total NaN values in row 22798 :- 0 and it's percentage : 0.0
 Total NaN values in row 22799 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22800 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22801 :- 0 and it's percentage : 0.0
 Total NaN values in row 22802 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22803 :- 0 and it's percentage : 0.0
 Total NaN values in row 22804 :- 0 and it's percentage : 0.0
 Total NaN values in row 22805 :- 0 and it's percentage : 0.0
 Total NaN values in row 22806 :- 0 and it's percentage : 0.0
 Total NaN values in row 22807 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22808 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22809 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22810 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 22811 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22812 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22813 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22814 :- 0 and it's percentage : 0.0
 Total NaN values in row 22815 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22816 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22817 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 22818 :- 0 and it's percentage : 0.0
 Total NaN values in row 22819 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22820 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22821 :- 0 and it's percentage : 0.0
 Total NaN values in row 22822 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22823 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22824 :- 0 and it's percentage : 0.0
 Total NaN values in row 22825 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22826 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22827 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22828 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22829 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22830 :- 0 and it's percentage : 0.0
 Total NaN values in row 22831 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22832 :- 0 and it's percentage : 0.0
 Total NaN values in row 22833 :- 0 and it's percentage : 0.0
 Total NaN values in row 22834 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22835 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22836 :- 0 and it's percentage : 0.0
 Total NaN values in row 22837 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22838 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22839 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22840 :- 0 and it's percentage : 0.0
 Total NaN values in row 22841 :- 0 and it's percentage : 0.0
 Total NaN values in row 22842 :- 0 and it's percentage : 0.0
 Total NaN values in row 22843 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22844 :- 0 and it's percentage : 0.0
 Total NaN values in row 22845 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22846 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22847 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22848 :- 6 and it's percentage : 33.333333333333336

 Total NaN values in row 22849 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22850 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22851 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22852 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22853 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22854 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22855 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22856 :- 0 and it's percentage : 0.0
 Total NaN values in row 22857 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22858 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22859 :- 0 and it's percentage : 0.0
 Total NaN values in row 22860 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22861 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22862 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22863 :- 0 and it's percentage : 0.0
 Total NaN values in row 22864 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22865 :- 0 and it's percentage : 0.0
 Total NaN values in row 22866 :- 0 and it's percentage : 0.0
 Total NaN values in row 22867 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22868 :- 0 and it's percentage : 0.0
 Total NaN values in row 22869 :- 0 and it's percentage : 0.0
 Total NaN values in row 22870 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22871 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22872 :- 0 and it's percentage : 0.0
 Total NaN values in row 22873 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22874 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22875 :- 0 and it's percentage : 0.0
 Total NaN values in row 22876 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22877 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22878 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22879 :- 0 and it's percentage : 0.0
 Total NaN values in row 22880 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22881 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22882 :- 0 and it's percentage : 0.0
 Total NaN values in row 22883 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22884 :- 0 and it's percentage : 0.0
 Total NaN values in row 22885 :- 0 and it's percentage : 0.0
 Total NaN values in row 22886 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22887 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22888 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22889 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22890 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22891 :- 0 and it's percentage : 0.0
 Total NaN values in row 22892 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22893 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22894 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22895 :- 0 and it's percentage : 0.0
 Total NaN values in row 22896 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22897 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22898 :- 0 and it's percentage : 0.0
 Total NaN values in row 22899 :- 0 and it's percentage : 0.0
 Total NaN values in row 22900 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22901 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22902 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22903 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22904 :- 0 and it's percentage : 0.0
 Total NaN values in row 22905 :- 0 and it's percentage : 0.0
 Total NaN values in row 22906 :- 0 and it's percentage : 0.0
 Total NaN values in row 22907 :- 0 and it's percentage : 0.0
 Total NaN values in row 22908 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22909 :- 0 and it's percentage : 0.0
 Total NaN values in row 22910 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22911 :- 0 and it's percentage : 0.0
 Total NaN values in row 22912 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22913 :- 0 and it's percentage : 0.0
 Total NaN values in row 22914 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22915 :- 0 and it's percentage : 0.0
 Total NaN values in row 22916 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 22917 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22918 :- 0 and it's percentage : 0.0
 Total NaN values in row 22919 :- 0 and it's percentage : 0.0
 Total NaN values in row 22920 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22921 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22922 :- 0 and it's percentage : 0.0
 Total NaN values in row 22923 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22924 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22925 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22926 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22927 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22928 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22929 :- 0 and it's percentage : 0.0
 Total NaN values in row 22930 :- 0 and it's percentage : 0.0
 Total NaN values in row 22931 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22932 :- 0 and it's percentage : 0.0
 Total NaN values in row 22933 :- 0 and it's percentage : 0.0
 Total NaN values in row 22934 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22935 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22936 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22937 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22938 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22939 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22940 :- 0 and it's percentage : 0.0
 Total NaN values in row 22941 :- 0 and it's percentage : 0.0
 Total NaN values in row 22942 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22943 :- 0 and it's percentage : 0.0
 Total NaN values in row 22944 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22945 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22946 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22947 :- 0 and it's percentage : 0.0
 Total NaN values in row 22948 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22949 :- 0 and it's percentage : 0.0
 Total NaN values in row 22950 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22951 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22952 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22953 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22954 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22955 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22956 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22957 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22958 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22959 :- 0 and it's percentage : 0.0
 Total NaN values in row 22960 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22961 :- 0 and it's percentage : 0.0
 Total NaN values in row 22962 :- 0 and it's percentage : 0.0
 Total NaN values in row 22963 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22964 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22965 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22966 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22967 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22968 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22969 :- 0 and it's percentage : 0.0
 Total NaN values in row 22970 :- 0 and it's percentage : 0.0
 Total NaN values in row 22971 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22972 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 22973 :- 0 and it's percentage : 0.0
 Total NaN values in row 22974 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22975 :- 0 and it's percentage : 0.0
 Total NaN values in row 22976 :- 0 and it's percentage : 0.0
 Total NaN values in row 22977 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 22978 :- 0 and it's percentage : 0.0
 Total NaN values in row 22979 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22980 :- 0 and it's percentage : 0.0
 Total NaN values in row 22981 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22982 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22983 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22984 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22985 :- 0 and it's percentage : 0.0
 Total NaN values in row 22986 :- 0 and it's percentage : 0.0
 Total NaN values in row 22987 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 22988 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22989 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22990 :- 0 and it's percentage : 0.0
 Total NaN values in row 22991 :- 0 and it's percentage : 0.0
 Total NaN values in row 22992 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22993 :- 7 and it's percentage : 38.888888888888886

 Total NaN values in row 22994 :- 0 and it's percentage : 0.0
 Total NaN values in row 22995 :- 0 and it's percentage : 0.0
 Total NaN values in row 22996 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 22997 :- 0 and it's percentage : 0.0
 Total NaN values in row 22998 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 22999 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23000 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23001 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23002 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23003 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23004 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23005 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23006 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23007 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23008 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23009 :- 0 and it's percentage : 0.0
 Total NaN values in row 23010 :- 0 and it's percentage : 0.0
 Total NaN values in row 23011 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23012 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23013 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23014 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23015 :- 0 and it's percentage : 0.0
 Total NaN values in row 23016 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23017 :- 0 and it's percentage : 0.0
 Total NaN values in row 23018 :- 0 and it's percentage : 0.0
 Total NaN values in row 23019 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 23020 :- 0 and it's percentage : 0.0
 Total NaN values in row 23021 :- 0 and it's percentage : 0.0
 Total NaN values in row 23022 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23023 :- 0 and it's percentage : 0.0
 Total NaN values in row 23024 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23025 :- 0 and it's percentage : 0.0
 Total NaN values in row 23026 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23027 :- 0 and it's percentage : 0.0
 Total NaN values in row 23028 :- 0 and it's percentage : 0.0
 Total NaN values in row 23029 :- 0 and it's percentage : 0.0
 Total NaN values in row 23030 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23031 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23032 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23033 :- 0 and it's percentage : 0.0
 Total NaN values in row 23034 :- 0 and it's percentage : 0.0
 Total NaN values in row 23035 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23036 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23037 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23038 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23039 :- 0 and it's percentage : 0.0
 Total NaN values in row 23040 :- 0 and it's percentage : 0.0
 Total NaN values in row 23041 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23042 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23043 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23044 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23045 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23046 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 23047 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23048 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23049 :- 0 and it's percentage : 0.0
 Total NaN values in row 23050 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23051 :- 0 and it's percentage : 0.0
 Total NaN values in row 23052 :- 0 and it's percentage : 0.0
 Total NaN values in row 23053 :- 0 and it's percentage : 0.0
 Total NaN values in row 23054 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23055 :- 0 and it's percentage : 0.0
 Total NaN values in row 23056 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23057 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23058 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23059 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23060 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23061 :- 0 and it's percentage : 0.0
 Total NaN values in row 23062 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23063 :- 0 and it's percentage : 0.0
 Total NaN values in row 23064 :- 0 and it's percentage : 0.0
 Total NaN values in row 23065 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23066 :- 0 and it's percentage : 0.0
 Total NaN values in row 23067 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23068 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23069 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23070 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23071 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23072 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23073 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23074 :- 0 and it's percentage : 0.0
 Total NaN values in row 23075 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23076 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23077 :- 0 and it's percentage : 0.0
 Total NaN values in row 23078 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23079 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23080 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23081 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23082 :- 0 and it's percentage : 0.0
 Total NaN values in row 23083 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23084 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23085 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23086 :- 0 and it's percentage : 0.0
 Total NaN values in row 23087 :- 0 and it's percentage : 0.0
 Total NaN values in row 23088 :- 0 and it's percentage : 0.0
 Total NaN values in row 23089 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23090 :- 0 and it's percentage : 0.0
 Total NaN values in row 23091 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23092 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23093 :- 0 and it's percentage : 0.0
 Total NaN values in row 23094 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23095 :- 0 and it's percentage : 0.0
 Total NaN values in row 23096 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23097 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23098 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23099 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23100 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23101 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23102 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23103 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23104 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23105 :- 0 and it's percentage : 0.0
 Total NaN values in row 23106 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23107 :- 0 and it's percentage : 0.0
 Total NaN values in row 23108 :- 0 and it's percentage : 0.0
 Total NaN values in row 23109 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23110 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 23111 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23112 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23113 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23114 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23115 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 23116 :- 0 and it's percentage : 0.0
 Total NaN values in row 23117 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23118 :- 0 and it's percentage : 0.0
 Total NaN values in row 23119 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23120 :- 0 and it's percentage : 0.0
 Total NaN values in row 23121 :- 0 and it's percentage : 0.0
 Total NaN values in row 23122 :- 0 and it's percentage : 0.0
 Total NaN values in row 23123 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23124 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23125 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23126 :- 0 and it's percentage : 0.0
 Total NaN values in row 23127 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23128 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23129 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23130 :- 0 and it's percentage : 0.0
 Total NaN values in row 23131 :- 0 and it's percentage : 0.0
 Total NaN values in row 23132 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23133 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23134 :- 0 and it's percentage : 0.0
 Total NaN values in row 23135 :- 0 and it's percentage : 0.0
 Total NaN values in row 23136 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23137 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23138 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23139 :- 0 and it's percentage : 0.0
 Total NaN values in row 23140 :- 0 and it's percentage : 0.0
 Total NaN values in row 23141 :- 0 and it's percentage : 0.0
 Total NaN values in row 23142 :- 0 and it's percentage : 0.0
 Total NaN values in row 23143 :- 0 and it's percentage : 0.0
 Total NaN values in row 23144 :- 0 and it's percentage : 0.0
 Total NaN values in row 23145 :- 0 and it's percentage : 0.0
 Total NaN values in row 23146 :- 0 and it's percentage : 0.0
 Total NaN values in row 23147 :- 0 and it's percentage : 0.0
 Total NaN values in row 23148 :- 0 and it's percentage : 0.0
 Total NaN values in row 23149 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23150 :- 0 and it's percentage : 0.0
 Total NaN values in row 23151 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23152 :- 0 and it's percentage : 0.0
 Total NaN values in row 23153 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23154 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23155 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23156 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23157 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23158 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23159 :- 0 and it's percentage : 0.0
 Total NaN values in row 23160 :- 0 and it's percentage : 0.0
 Total NaN values in row 23161 :- 0 and it's percentage : 0.0
 Total NaN values in row 23162 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23163 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23164 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23165 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23166 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23167 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23168 :- 0 and it's percentage : 0.0
 Total NaN values in row 23169 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23170 :- 0 and it's percentage : 0.0
 Total NaN values in row 23171 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23172 :- 0 and it's percentage : 0.0
 Total NaN values in row 23173 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23174 :- 0 and it's percentage : 0.0
 Total NaN values in row 23175 :- 0 and it's percentage : 0.0
 Total NaN values in row 23176 :- 0 and it's percentage : 0.0
 Total NaN values in row 23177 :- 0 and it's percentage : 0.0
 Total NaN values in row 23178 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23179 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23180 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23181 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23182 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23183 :- 0 and it's percentage : 0.0
 Total NaN values in row 23184 :- 0 and it's percentage : 0.0
 Total NaN values in row 23185 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23186 :- 0 and it's percentage : 0.0
 Total NaN values in row 23187 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23188 :- 0 and it's percentage : 0.0
 Total NaN values in row 23189 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23190 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23191 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23192 :- 0 and it's percentage : 0.0
 Total NaN values in row 23193 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23194 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23195 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23196 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23197 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23198 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23199 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23200 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23201 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23202 :- 0 and it's percentage : 0.0
 Total NaN values in row 23203 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23204 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23205 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23206 :- 0 and it's percentage : 0.0
 Total NaN values in row 23207 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23208 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23209 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23210 :- 0 and it's percentage : 0.0
 Total NaN values in row 23211 :- 0 and it's percentage : 0.0
 Total NaN values in row 23212 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23213 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23214 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23215 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23216 :- 0 and it's percentage : 0.0
 Total NaN values in row 23217 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23218 :- 0 and it's percentage : 0.0
 Total NaN values in row 23219 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23220 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23221 :- 0 and it's percentage : 0.0
 Total NaN values in row 23222 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23223 :- 0 and it's percentage : 0.0
 Total NaN values in row 23224 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 23225 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23226 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23227 :- 0 and it's percentage : 0.0
 Total NaN values in row 23228 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23229 :- 0 and it's percentage : 0.0
 Total NaN values in row 23230 :- 0 and it's percentage : 0.0
 Total NaN values in row 23231 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23232 :- 0 and it's percentage : 0.0
 Total NaN values in row 23233 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23234 :- 0 and it's percentage : 0.0
 Total NaN values in row 23235 :- 0 and it's percentage : 0.0
 Total NaN values in row 23236 :- 0 and it's percentage : 0.0
 Total NaN values in row 23237 :- 0 and it's percentage : 0.0
 Total NaN values in row 23238 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23239 :- 0 and it's percentage : 0.0
 Total NaN values in row 23240 :- 0 and it's percentage : 0.0
 Total NaN values in row 23241 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23242 :- 0 and it's percentage : 0.0
 Total NaN values in row 23243 :- 0 and it's percentage : 0.0
 Total NaN values in row 23244 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23245 :- 0 and it's percentage : 0.0
 Total NaN values in row 23246 :- 0 and it's percentage : 0.0
 Total NaN values in row 23247 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23248 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23249 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23250 :- 0 and it's percentage : 0.0
 Total NaN values in row 23251 :- 0 and it's percentage : 0.0
 Total NaN values in row 23252 :- 0 and it's percentage : 0.0
 Total NaN values in row 23253 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23254 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23255 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23256 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23257 :- 0 and it's percentage : 0.0
 Total NaN values in row 23258 :- 0 and it's percentage : 0.0
 Total NaN values in row 23259 :- 0 and it's percentage : 0.0
 Total NaN values in row 23260 :- 0 and it's percentage : 0.0
 Total NaN values in row 23261 :- 0 and it's percentage : 0.0
 Total NaN values in row 23262 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23263 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23264 :- 0 and it's percentage : 0.0
 Total NaN values in row 23265 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23266 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23267 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23268 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23269 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23270 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23271 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23272 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23273 :- 0 and it's percentage : 0.0
 Total NaN values in row 23274 :- 0 and it's percentage : 0.0
 Total NaN values in row 23275 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23276 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23277 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23278 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23279 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 23280 :- 0 and it's percentage : 0.0
 Total NaN values in row 23281 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23282 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23283 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23284 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 23285 :- 0 and it's percentage : 0.0
 Total NaN values in row 23286 :- 0 and it's percentage : 0.0

 Total NaN values in row 23287 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23288 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23289 :- 0 and it's percentage : 0.0
 Total NaN values in row 23290 :- 0 and it's percentage : 0.0
 Total NaN values in row 23291 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23292 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23293 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23294 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23295 :- 0 and it's percentage : 0.0
 Total NaN values in row 23296 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23297 :- 0 and it's percentage : 0.0
 Total NaN values in row 23298 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23299 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23300 :- 0 and it's percentage : 0.0
 Total NaN values in row 23301 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23302 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23303 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23304 :- 0 and it's percentage : 0.0
 Total NaN values in row 23305 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23306 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23307 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23308 :- 0 and it's percentage : 0.0
 Total NaN values in row 23309 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23310 :- 0 and it's percentage : 0.0
 Total NaN values in row 23311 :- 0 and it's percentage : 0.0
 Total NaN values in row 23312 :- 0 and it's percentage : 0.0
 Total NaN values in row 23313 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23314 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23315 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23316 :- 0 and it's percentage : 0.0
 Total NaN values in row 23317 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23318 :- 0 and it's percentage : 0.0
 Total NaN values in row 23319 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23320 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23321 :- 0 and it's percentage : 0.0
 Total NaN values in row 23322 :- 0 and it's percentage : 0.0
 Total NaN values in row 23323 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23324 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23325 :- 0 and it's percentage : 0.0
 Total NaN values in row 23326 :- 0 and it's percentage : 0.0
 Total NaN values in row 23327 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23328 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23329 :- 0 and it's percentage : 0.0
 Total NaN values in row 23330 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23331 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23332 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23333 :- 0 and it's percentage : 0.0
 Total NaN values in row 23334 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23335 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23336 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23337 :- 0 and it's percentage : 0.0
 Total NaN values in row 23338 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23339 :- 0 and it's percentage : 0.0
 Total NaN values in row 23340 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23341 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23342 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23343 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23344 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23345 :- 0 and it's percentage : 0.0
 Total NaN values in row 23346 :- 0 and it's percentage : 0.0
 Total NaN values in row 23347 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23348 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23349 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23350 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23351 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23352 :- 0 and it's percentage : 0.0
 Total NaN values in row 23353 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23354 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23355 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23356 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23357 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23358 :- 0 and it's percentage : 0.0
 Total NaN values in row 23359 :- 0 and it's percentage : 0.0
 Total NaN values in row 23360 :- 0 and it's percentage : 0.0
 Total NaN values in row 23361 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23362 :- 0 and it's percentage : 0.0
 Total NaN values in row 23363 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23364 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23365 :- 0 and it's percentage : 0.0
 Total NaN values in row 23366 :- 0 and it's percentage : 0.0
 Total NaN values in row 23367 :- 0 and it's percentage : 0.0
 Total NaN values in row 23368 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23369 :- 0 and it's percentage : 0.0
 Total NaN values in row 23370 :- 0 and it's percentage : 0.0
 Total NaN values in row 23371 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23372 :- 0 and it's percentage : 0.0
 Total NaN values in row 23373 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23374 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23375 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23376 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23377 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23378 :- 0 and it's percentage : 0.0
 Total NaN values in row 23379 :- 0 and it's percentage : 0.0
 Total NaN values in row 23380 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23381 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23382 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23383 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 23384 :- 0 and it's percentage : 0.0
 Total NaN values in row 23385 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23386 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23387 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23388 :- 0 and it's percentage : 0.0
 Total NaN values in row 23389 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23390 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23391 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23392 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23393 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23394 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23395 :- 0 and it's percentage : 0.0
 Total NaN values in row 23396 :- 0 and it's percentage : 0.0
 Total NaN values in row 23397 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23398 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23399 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23400 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23401 :- 0 and it's percentage : 0.0
 Total NaN values in row 23402 :- 0 and it's percentage : 0.0
 Total NaN values in row 23403 :- 0 and it's percentage : 0.0
 Total NaN values in row 23404 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23405 :- 0 and it's percentage : 0.0
 Total NaN values in row 23406 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23407 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23408 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23409 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23410 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23411 :- 0 and it's percentage : 0.0
 Total NaN values in row 23412 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23413 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23414 :- 0 and it's percentage : 0.0
 Total NaN values in row 23415 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23416 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23417 :- 0 and it's percentage : 0.0
 Total NaN values in row 23418 :- 0 and it's percentage : 0.0
 Total NaN values in row 23419 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23420 :- 0 and it's percentage : 0.0
 Total NaN values in row 23421 :- 0 and it's percentage : 0.0
 Total NaN values in row 23422 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23423 :- 0 and it's percentage : 0.0
 Total NaN values in row 23424 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23425 :- 7 and it's percentage : 38.888888888888886
 Total NaN values in row 23426 :- 0 and it's percentage : 0.0
 Total NaN values in row 23427 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23428 :- 0 and it's percentage : 0.0
 Total NaN values in row 23429 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23430 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23431 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23432 :- 0 and it's percentage : 0.0
 Total NaN values in row 23433 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23434 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23435 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23436 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23437 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23438 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23439 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23440 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23441 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23442 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23443 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23444 :- 1 and it's percentage : 5.555555555555555

 Total NaN values in row 23445 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23446 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23447 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23448 :- 0 and it's percentage : 0.0
 Total NaN values in row 23449 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23450 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23451 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23452 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23453 :- 0 and it's percentage : 0.0
 Total NaN values in row 23454 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23455 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23456 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23457 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23458 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23459 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 23460 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23461 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23462 :- 0 and it's percentage : 0.0
 Total NaN values in row 23463 :- 0 and it's percentage : 0.0
 Total NaN values in row 23464 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23465 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23466 :- 0 and it's percentage : 0.0
 Total NaN values in row 23467 :- 0 and it's percentage : 0.0
 Total NaN values in row 23468 :- 0 and it's percentage : 0.0
 Total NaN values in row 23469 :- 0 and it's percentage : 0.0
 Total NaN values in row 23470 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23471 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23472 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23473 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23474 :- 0 and it's percentage : 0.0
 Total NaN values in row 23475 :- 0 and it's percentage : 0.0
 Total NaN values in row 23476 :- 0 and it's percentage : 0.0
 Total NaN values in row 23477 :- 0 and it's percentage : 0.0
 Total NaN values in row 23478 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23479 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23480 :- 0 and it's percentage : 0.0
 Total NaN values in row 23481 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23482 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23483 :- 0 and it's percentage : 0.0
 Total NaN values in row 23484 :- 4 and it's percentage : 22.22222222222222
 Total NaN values in row 23485 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23486 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23487 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23488 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23489 :- 0 and it's percentage : 0.0
 Total NaN values in row 23490 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23491 :- 0 and it's percentage : 0.0
 Total NaN values in row 23492 :- 0 and it's percentage : 0.0
 Total NaN values in row 23493 :- 0 and it's percentage : 0.0
 Total NaN values in row 23494 :- 0 and it's percentage : 0.0
 Total NaN values in row 23495 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23496 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23497 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23498 :- 0 and it's percentage : 0.0
 Total NaN values in row 23499 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23500 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23501 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23502 :- 0 and it's percentage : 0.0
 Total NaN values in row 23503 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23504 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23505 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23506 :- 3 and it's percentage : 16.666666666666668
 Total NaN values in row 23507 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23508 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23509 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23510 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23511 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23512 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23513 :- 0 and it's percentage : 0.0
 Total NaN values in row 23514 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23515 :- 0 and it's percentage : 0.0
 Total NaN values in row 23516 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23517 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23518 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23519 :- 0 and it's percentage : 0.0
 Total NaN values in row 23520 :- 0 and it's percentage : 0.0
 Total NaN values in row 23521 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23522 :- 0 and it's percentage : 0.0
 Total NaN values in row 23523 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23524 :- 0 and it's percentage : 0.0
 Total NaN values in row 23525 :- 0 and it's percentage : 0.0
 Total NaN values in row 23526 :- 0 and it's percentage : 0.0
 Total NaN values in row 23527 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23528 :- 0 and it's percentage : 0.0
 Total NaN values in row 23529 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23530 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23531 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23532 :- 6 and it's percentage : 33.333333333333336
 Total NaN values in row 23533 :- 0 and it's percentage : 0.0
 Total NaN values in row 23534 :- 2 and it's percentage : 11.11111111111111
 Total NaN values in row 23535 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23536 :- 0 and it's percentage : 0.0
 Total NaN values in row 23537 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23538 :- 0 and it's percentage : 0.0
 Total NaN values in row 23539 :- 0 and it's percentage : 0.0
 Total NaN values in row 23540 :- 0 and it's percentage : 0.0
 Total NaN values in row 23541 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23542 :- 0 and it's percentage : 0.0
 Total NaN values in row 23543 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23544 :- 5 and it's percentage : 27.77777777777778
 Total NaN values in row 23545 :- 1 and it's percentage : 5.555555555555555
 Total NaN values in row 23546 :- 0 and it's percentage : 0.0
 Total NaN values in row 23547 :- 1 and it's percentage : 5.555555555555555

11. Display the description of data and percentage of missing values still left column wise.

In [12]:
data2

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,2.0,1.0,1.0,126.0,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,2.0,1.0,1.0,202.0,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,3.0,2.0,1.0,0.0,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,3.0,1.0,0.0,552.0,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,4.0,3.0,2.0,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,4.0,2.0,2.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [13]:
# percentage of missing values still left column wise

missing_percentage2 = data2.isnull().sum() * 100 / len(data2)
print(missing_percentage2)

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            21.875398
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.004247
Postcode          0.004247
Bedroom2         19.030025
Bathroom         19.042766
Car              19.645815
Landsize         26.062768
Lattitude        18.278337
Longtitude       18.278337
Regionname        0.004247
Propertycount     0.004247
dtype: float64

12. Considering the 'Price' column as target variable which is to be predicted, how will you treat the missing values? Give a brief explanation and treat the missing values in 'Price' column.

In [14]:
# Here the target column has missing values and going to treat them with fillna 
# Going to fill the missing values with the mean of the price column

data2['Price'].fillna((data2['Price'].mean()), inplace=True)
data2['Price']

0        1.056697e+06
1        1.480000e+06
2        1.035000e+06
3        1.056697e+06
4        1.465000e+06
             ...
23673    1.056697e+06
23674    1.056697e+06
23675    1.100000e+06
23676    1.285000e+06
23677    1.050000e+06
Name: Price, Length: 23547, dtype: float64

13. Now check the percentage of missing values in each column again, if missing values exist, treat it with the most suitable method.

In [15]:
missing_percentage3 = data2.isnull().sum() * 100 / len(data2)
print(missing_percentage3)

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price             0.000000
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.004247
Postcode          0.004247
Bedroom2         19.030025
Bathroom         19.042766
Car              19.645815
Landsize         26.062768
Lattitude        18.278337
Longtitude       18.278337
Regionname        0.004247
Propertycount     0.004247
dtype: float64

There are many ways to treat missing values

1.Ignore the missing values

2.Drop the missing values

3.Case Deletion

4.Imputation by Mean/Mode/Median

5.Regression Methods

6.Multiple Imputation

Here i'm choosing mean method to fill the missing value

In [16]:
data2['Bedroom2'].fillna((data2['Bedroom2'].mean()), inplace=True)
data2['Bathroom'].fillna((data2['Bathroom'].mean()), inplace=True)
data2['Car'].fillna((data2['Car'].mean()), inplace=True)
data2['Landsize'].fillna((data2['Landsize'].mean()), inplace=True)
data2['Lattitude'].fillna((data2['Lattitude'].mean()), inplace=True)
data2['Longtitude'].fillna((data2['Longtitude'].mean()), inplace=True)
data2

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,1.056697e+06,SS,Jellis,03-09-2016,2.5,3067.0,2.000000,1.000000,1.000000,126.000000,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1.480000e+06,S,Biggin,03-12-2016,2.5,3067.0,2.000000,1.000000,1.000000,202.000000,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1.035000e+06,S,Biggin,04-02-2016,2.5,3067.0,2.000000,1.000000,0.000000,156.000000,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,1.056697e+06,VB,Rounds,04-02-2016,2.5,3067.0,3.000000,2.000000,1.000000,0.000000,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1.465000e+06,SP,Biggin,04-03-2017,2.5,3067.0,3.000000,2.000000,0.000000,134.000000,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23673,Wyndham Vale,25 Clitheroe Dr,3.0,u,1.056697e+06,PN,Harcourts,26-08-2017,27.2,3024.0,3.000000,1.000000,0.000000,552.000000,-37.90032,144.61839,Western Metropolitan,5262.0
23674,Wyndham Vale,19 Dalrymple Bvd,4.0,h,1.056697e+06,S,hockingstuart,26-08-2017,27.2,3024.0,2.951956,1.570897,1.626235,551.783458,-37.87882,144.60184,Western Metropolitan,5262.0
23675,Yallambie,17 Amaroo Wy,4.0,h,1.100000e+06,S,Buckingham,26-08-2017,12.7,3085.0,4.000000,3.000000,2.000000,551.783458,-37.72006,145.10547,Northern Metropolitan,1369.0
23676,Yarraville,6 Agnes St,4.0,h,1.285000e+06,SP,Village,26-08-2017,6.3,3013.0,4.000000,1.000000,1.000000,362.000000,-37.81188,144.88449,Western Metropolitan,6543.0
23677,Yarraville,33 Freeman St,4.0,h,1.050000e+06,VB,Village,26-08-2017,6.3,3013.0,4.000000,2.000000,2.000000,551.783458,-37.81829,144.87404,Western Metropolitan,6543.0

14. Now since you have completed your data cleaning, determine the number and percentage of columns removed

Since we came to an end of data cleaning process calculating the number and percentage of columns removed 

so here we totally removed 3 columns because it has more than 30% of missing values percentage

14.2 % of columns has been removed from this dataset

15. Determine the number and percentage of rows removed in whole process. Also comment briefly that according to you the amount of data lost is justified or not.

Here coming to the rows portion we have removed totally of 131 rows which were completely empty rows 

total percentage of data lose row-wise is less than 1 % 

Here losing these percentage of data is acceptable depending on dataset.